Repository redwoodjs/graphql, pull requests merged in 2020-09, with the labels that each got.

#1048 Removes @redwoodjs/forms from @redwoodjs/web
  packages/web/package.json
  packages/web/src/form/index.js
  packages/web/src/index.js
Labels: next release, next release docs, next release test

#1033 Add supabase auth provider
  packages/api/src/auth/decoders/index.ts
  packages/api/src/functions/authDecoder.test.ts
  packages/auth/package.json
  packages/auth/src/authClients/index.ts
  packages/auth/src/authClients/supabase.ts
  packages/cli/src/commands/generate/auth/providers/supabase.js
  yarn.lock
Labels: next release, next release docs, topic: auth

#1094 quote paths and keywords with <tt> instead of quotation marks in JSX template generator
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/multiWordPage.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/paramPage.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/pluralWordPage.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/singleWordPage.js
  packages/cli/src/commands/generate/page/templates/page.js.template
Labels: next release

#1057 Adds signup() to Auth to default UI to a signup tab/form when available
  packages/auth/README.md
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/authClients/auth0.ts
  packages/auth/src/authClients/firebase.ts
  packages/auth/src/authClients/goTrue.ts
  packages/auth/src/authClients/index.ts
  packages/auth/src/authClients/magicLink.ts
  packages/auth/src/authClients/netlify.ts
  packages/auth/src/authClients/supabase.ts
  yarn.lock
Labels: next release, next release test, topic: auth

#1102 Create Directory Named Import plugin
  packages/core/config/babel-preset.js
  packages/core/config/webpack.common.js
  packages/core/package.json
  packages/core/src/babelPlugins/__tests__/__fixtures__/directory-named-imports/JSX/JSX.jsx
  packages/core/src/babelPlugins/__tests__/__fixtures__/directory-named-imports/Module/Module.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/directory-named-imports/TS/TS.ts
  packages/core/src/babelPlugins/__tests__/__fixtures__/directory-named-imports/TSX/TSX.tsx
  packages/core/src/babelPlugins/__tests__/__fixtures__/directory-named-imports/indexModule/index.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/directory-named-imports/indexModule/indexModue.js
  packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-directory-named-imports.ts
  packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts
  packages/core/src/configs/browser/jest.createConfig.ts
  packages/core/src/configs/node/jest.createConfig.ts
  packages/internal/src/paths.ts
  yarn.lock
Labels: next release, next release test

#1121 Fix tailwind webpack configuration
  packages/cli/src/commands/generate/util/tailwind/tailwind.js
  packages/core/config/webpack.common.js
Labels: bug/2-confirmed

#1005 Upgrade @apollo/client v3.1.3
  packages/api/package.json
  packages/core/src/configs/browser/jest.createConfig.ts
  packages/structure/package.json
  packages/web/package.json
  packages/web/src/graphql/index.js
  packages/web/src/graphql/withCell.js
  packages/web/src/index.d.ts
  packages/web/src/index.js
  yarn.lock
Labels: breaking change

#1112 rename diagnostics to check
  packages/cli/src/commands/check.js
Labels: next release, next release docs

#1133 feat: support styling Flash with style object
  packages/web/src/flash/Flash.js
  packages/web/src/flash/FlashReducer.js
  packages/web/src/flash/__tests__/flash.test.js
Labels: next release

#1134 Fixes #932: Adds Storybook index.scss and index.sass support
  packages/core/config/storybook/main.js
Labels: next release

#1144 Add the necessary prisma binaries when generating deploy config for a…
  packages/cli/src/commands/generate/deploy/deploy.js
  packages/cli/src/commands/generate/deploy/providers/aws_serverless.js
Labels: next release

#1173 Improve CLI speed
  packages/cli/src/commands/build.js
  packages/cli/src/commands/check.js
  packages/cli/src/commands/deploy/api/api.js
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/test.js
Labels: next release, next release test

#1175 Allow CORS to be passed to AWS Lambda Handler
  packages/api/src/functions/graphql.ts
Labels: next release, next release test

#1162 Resolve destroy page "propParam is not defined" error
  packages/cli/src/commands/destroy/page/page.js
Labels: bug/2-confirmed, next release, next release test

#1142 fix cell generated test template
  packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/multiWordCell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/singleWordCell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.test.js
  packages/cli/src/commands/generate/cell/templates/test.js.template
Labels: next release

#1185 Implement missing Apollo methods
  packages/web/src/index.js
Labels: next release

#1188 Fix of TypeError: merge is not a function
  packages/core/config/webpack.common.js
Labels: next release

#1154 Add the setup command
  packages/cli/src/commands/generate.js
  packages/cli/src/commands/setup.js
  packages/cli/src/commands/setup/i18n/i18n.js
  packages/cli/src/commands/setup/i18n/templates/i18n.js.template
  packages/cli/src/commands/setup/tailwind/tailwind.js
  packages/cli/src/commands/setup/tailwind/templates/postcss.config.js.template
  packages/internal/src/paths.ts
Labels: next release docs, next release test, topic: cli

#1207 Fix usage of private variable
  packages/core/src/configs/node/jest.setup.js
Labels: next release, topic: testing

#1209 Fix cwd in getConfigPath to actual cwd
  packages/internal/src/paths.ts
Labels: bug/2-confirmed, next release

#1208 Add jest-watch-typeahead
  packages/core/config/jest.config.js
  packages/core/package.json
  yarn.lock
Labels: topic: testing

#1241 ✨ @redwood/web typing: Add types to createGraphQLClient and GraphQLProvider
  packages/web/src/global.web-auto-imports.ts
  packages/web/src/graphql/index.tsx
  packages/web/src/index.ts
Labels: topic: web

#1247 🧫 @redwood/web typing: Add types to withCell
  packages/web/src/graphql/index.tsx
  packages/web/src/graphql/withCell.tsx
Labels: next release, next release test
