Repository redwoodjs/graphql, pull requests merged in 2020-07, with the labels that each got.

#691 Allow configuring test database
  packages/cli/src/commands/dbCommands/save.js
  packages/cli/src/commands/test.js
  packages/core/config/jest.config.api.js
  packages/core/config/jest.setup.api.js
  packages/internal/src/paths.ts
Labels: topic: testing

#773 Edit api readme
  packages/api/README.md
Labels: topic: api, topic: docs

#788 Make sub-directories work in import-dir
  packages/core/src/__tests__/__fixtures__/import-dir/__fixtures__/nested/d.js
  packages/core/src/__tests__/__fixtures__/import-dir/import-dir-default/code.js
  packages/core/src/__tests__/__fixtures__/import-dir/import-dir-default/output.js
  packages/core/src/babel-plugin-redwood-import-dir.ts
Labels: next release, topic: cli

#790 Add initial types to Router
  packages/router/README.md
  packages/router/package.json
  packages/router/src/index.d.ts
Labels: next release, topic: router

#793 Replace importAll docs with babel-plugin import docs
  packages/api/README.md
Labels: kind/improvement, topic: api, topic: docs

#799 Add prisma studio via db studio command
  packages/cli/src/commands/dbCommands/studio.js
Labels: kind/improvement, topic: prisma

#801 Remove dev.db/migrations check in db studio
  packages/cli/src/commands/dbCommands/studio.js
Labels: kind/improvement, topic: cli, topic: prisma

#796 Add cache-and-network fetchPolicy to beforeQuery
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/indexCell.js
  packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.js.template
  packages/web/src/graphql/withCell.js
Labels: kind/improvement, topic: web

#779 getCurrentUser given both decoded & access tokens
  .vscode/settings.json
  packages/api/src/auth/authHeaders.ts
  packages/api/src/auth/decoders/auth0.ts
  packages/api/src/auth/decoders/index.ts
  packages/api/src/auth/decoders/netlify.ts
  packages/api/src/auth/index.ts
  packages/api/src/functions/graphql.ts
  packages/api/src/main.ts
  packages/api/src/makeMergedSchema/rootSchema.ts
  packages/auth/README.md
  packages/cli/src/commands/generate/auth/auth.js
  packages/cli/src/commands/generate/auth/providers/auth0.js
  packages/cli/src/commands/generate/auth/providers/firebase.js
  packages/cli/src/commands/generate/auth/providers/goTrue.js
  packages/cli/src/commands/generate/auth/providers/magicLink.js
  packages/cli/src/commands/generate/auth/providers/netlify.js
  packages/cli/src/commands/generate/auth/templates/auth.js.template
  packages/cli/src/commands/generate/auth/templates/firebase.auth.js.template
Labels: next release, topic: auth

#815 Add @storybook/react to @redwoodjs/core
  packages/core/package.json
Labels: kind/question, topic: web

#833 Add alias sb for storybook command
  packages/cli/src/commands/storybook.js
Labels: kind/improvement, topic: generators

#832 Fix auth generator regex
  packages/cli/src/commands/generate/auth/auth.js
Labels: topic: auth, topic: generators

#834 Form: use context to handle coercions
  packages/web/src/form/__tests__/form.test.js
  packages/web/src/form/coercion.js
  packages/web/src/form/form.js
Labels: next release

#855 improve structure/outline + enable interactive CLI
  packages/structure/package.json
  packages/structure/src/ide.ts
  packages/structure/src/interactive_cli/RedwoodCommandString.ts
  packages/structure/src/interactive_cli/command_builder.ts
  packages/structure/src/interactive_cli/command_runner.ts
  packages/structure/src/interactive_cli/dry_run.ts
  packages/structure/src/interactive_cli/index.ts
  packages/structure/src/interactive_cli/sandbox_builder_with_cliui.ts
  packages/structure/src/language_server/RWLanguageServer.ts
  packages/structure/src/model/RWRouter.ts
  packages/structure/src/outline/outline.ts
  packages/structure/src/outline/types.ts
  packages/structure/src/x/URL.ts
  packages/structure/src/x/__tests__/URL.test.ts
  packages/structure/src/x/vscode-languageserver-types.ts
  packages/structure/src/x/yargs.ts
Labels: next release

#867 Give a Cell's query an operation name
  babel.config.js
  packages/cli/src/commands/destroy/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/multiWordCell.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/singleWordCell.js
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/cell/templates/cell.js.template
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  packages/cli/tsconfig.json
  tsconfig.json
Labels: next release

#824 Fix sdl generator to support Json type
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/editCell.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/form.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/index.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/indexCell.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/show.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/showCell.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/components/Name.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/NameForm.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/jsonGeneratedSdl.js
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/jsonGeneratedSdl.ts
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/sdl/__tests__/sdl.test.js
  packages/cli/src/commands/generate/sdl/sdl.js
Labels: kind/improvement, topic: generators

#836 Convert LocationProvider to function component and add cleanup effects
  packages/router/src/location.js
Labels: next release

#848 dev-server: wildcard match lambda functions
  packages/dev-server/src/http.ts
Labels: next release

#850 Lambda function list with no comma
  packages/dev-server/src/http.ts
Labels: next release

#858 Add Router tests
  packages/router/src/__tests__/router.test.js
Labels: next release

#862 Bump kill-port
  packages/internal/package.json
  yarn.lock
Labels: next release

#865 Export useLazyQuery/useSubscription from @apollo
  packages/web/src/index.js
Labels: next release

#856 Add a way to mock data in Storybook and Jest
  __fixtures__/example-todo-main/web/src/components/NumTodosCell/NumTodosCell.js
  __fixtures__/example-todo-main/web/src/components/NumTodosCell/NumTodosCell.mock.js
  __fixtures__/example-todo-main/web/src/components/TodoListCell/TodoListCell.js
  __fixtures__/example-todo-main/web/src/components/TodoListCell/TodoListCell.mock.js
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/multiWordCell.mock.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/multiWordCell.stories.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/singleWordCell.mock.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/singleWordCell.stories.js
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/cell/templates/mock.js.template
  packages/cli/src/commands/generate/cell/templates/stories.js.template
  packages/cli/src/commands/storybook.js
  packages/core/config/babel-preset.js
  packages/core/config/storybook/main.js
  packages/core/config/storybook/preview.js
  packages/core/config/webpack.common.js
  packages/core/src/__tests__/__fixtures__/mock-cell-data/output_NumTodosCell.mock.js
  packages/core/src/__tests__/__fixtures__/mock-cell-data/output_TodoListCell.mock.js
  packages/core/src/__tests__/babel-plugin-redwood-mock-cell-data.test.ts
  packages/core/src/babel-plugin-redwood-mock-cell-data.ts
  packages/core/src/storybook/index.tsx
  packages/core/tsconfig.json
  packages/eslint-config/index.js
  packages/internal/src/paths.ts
  packages/structure/package.json
  packages/structure/src/index.ts
  packages/structure/src/language_server/RWLanguageServer.ts
  packages/structure/src/x/vscode.ts
  packages/testing/src/index.ts
  packages/testing/src/mockRequests.ts
  packages/testing/src/mockServer.ts
  wallaby.js
Labels: next release

#863 Add .idea/ dir for Jetbrains IDE's config to .gitignore
  .gitignore
  __fixtures__/example-todo-main-with-errors/.gitignore
  __fixtures__/example-todo-main/.gitignore
  __fixtures__/new-project/.gitignore
Labels: next release

#878 isAuthenticated should be false when getCurrentUser fails
  packages/auth/README.md
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/auth/src/authClients/index.ts
  yarn.lock
Labels: next release

#869 Fix test db path on Windows
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/test.js
  packages/cli/src/redwood-tools.js
  packages/internal/src/__tests__/paths.test.ts
  packages/internal/src/paths.ts
Labels: topic: windows

#885 Remove warnings about "act" in router tests.
  packages/router/src/__tests__/router.test.js
Labels: topic: testing

#874 Ignore coercion for unsupported form fields
  packages/web/src/form/coercion.js
Labels: next release, topic: forms

#876 redirectTo a url on login after authenticated
  packages/auth/README.md
  packages/auth/src/authClients/auth0.ts
  packages/router/README.md
  packages/router/src/router.js
Labels: next release, topic: auth, topic: router

#877 Stringify function body prevents Netlify 502 error
  packages/cli/src/commands/generate/function/__tests__/fixtures/multiWord.js
  packages/cli/src/commands/generate/function/__tests__/fixtures/singleWord.js
  packages/cli/src/commands/generate/function/templates/function.js.template
Labels: next release, topic: deployment

#888 Fix #883 - Cell Operation Names not PascalCased
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.mock.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.stories.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.mock.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.stories.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.mock.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.stories.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.test.js
  packages/cli/src/commands/generate/cell/cell.js
Labels: next release

#894 Add graphQL mocks to jest
  packages/cli/src/commands/test.js
  packages/core/src/configs/browser/jest.createConfig.ts
  packages/core/src/configs/browser/jest.setup.js
  packages/core/src/configs/node/jest.createConfig.ts
  packages/structure/src/model/RWProject.ts
  packages/testing/src/mockRequests.ts
Labels: next release, topic: testing

#899 Improve Language Server
  packages/structure/.vscode/launch.json
  packages/structure/src/ide.ts
  packages/structure/src/language_server/RWLanguageServer.ts
  packages/structure/src/language_server/commands.ts
  packages/structure/src/language_server/diagnostics.ts
  packages/structure/src/language_server/outline.ts
  packages/structure/src/language_server/xmethods.ts
  packages/structure/src/model/RWRoute.ts
  packages/structure/src/model/RWRouter.ts
  packages/structure/src/model/util/__tests__/advanced_path_parser.test.ts
  packages/structure/src/model/util/advanced_path_parser.ts
  packages/structure/src/outline/outline.ts
  packages/structure/src/x/vscode-languageserver-types.ts
  packages/structure/src/x/vscode.ts
Labels: next release

#904 Add `yarn rw dev` option to pass any Webpack config as a string
  packages/cli/src/commands/dev.js
Labels: next release

#841 Upgrade Prisma v2.3.0
  packages/api/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/structure/package.json
  yarn.lock
Labels: next release

#898 fix(auth-decoder): Make auth decoder backwards compatible with 0.12
  packages/api/src/__tests__/authDecoder.test.ts
  packages/api/src/__tests__/fixtures/apiGatewayProxyEvent.fixture.ts
  packages/api/src/auth/decoders/index.ts
Labels: next release
