Repository redwoodjs/graphql, pull requests merged in 2020-04, with the labels that each got.

#364 [Web] Add SelectField
  packages/web/src/form/form.js
Labels: kind/improvement, topic: forms

#386 Updates Prisma to 2.0.0-beta.1
  packages/api/package.json
  packages/cli/package.json
  packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js
  packages/cli/src/commands/dbCommands/down.js
  packages/cli/src/commands/dbCommands/generate.js
  packages/cli/src/commands/dbCommands/save.js
  packages/cli/src/commands/dbCommands/up.js
  packages/cli/src/commands/dev.js
  packages/cli/src/commands/generate/commands/sdl.js
  packages/core/package.json
  yarn.lock
Labels: topic: prisma

#363 Windows Local Dev: Construct build scripts for cross-platform use
  .gitattributes
  .github/workflows/build-eslint-jest.yaml
  package.json
  packages/api/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/create-redwood-app/package.json
  packages/dev-server/package.json
  packages/eslint-plugin-redwood/package.json
  packages/internal/package.json
  packages/router/package.json
  packages/web/package.json
  yarn.lock
Labels: kind/improvement, topic: windows

#357 Use URLSearchParams for parsing search params
  packages/router/src/util.js
Labels: topic: router

#407 Upgrade to Prisma v2-beta.2
  packages/api/package.json
  packages/cli/package.json
  packages/core/package.json
  yarn.lock
Labels: topic: prisma

#395 Windows: Fix ESlint errors
  .github/workflows/build-eslint-jest.yaml
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  packages/eslint-config/package.json
  yarn.lock
Labels: kind/bug, topic: CI | test | lint | build, topic: windows

#420 [Router] fixes `validatePath` duplicate params & reject spaces in routes
  packages/router/src/__tests__/util.test.js
  packages/router/src/util.js
Labels: next release

#416 [Router] Add useMatch for crafting stateful links
  packages/router/package.json
  packages/router/src/__tests__/links.test.js
  packages/router/src/index.js
  packages/router/src/links.js
  packages/router/src/location.js
Labels: next release

#438 TypeScript support: Let api-dev-server and webpack load .ts and .tsx files
  packages/core/config/webpack.common.js
  packages/internal/package.json
  packages/internal/src/paths.ts
Labels: next release

#442 change rwdev to redwood-tools, aliased rwt
  packages/cli/package.json
  packages/cli/src/redwood-tools.js
Labels: next release

#436 Add 'yarn rw upgrade' helper to upgrade @redwoodjs packages
  packages/cli/src/commands/upgrade.js
Labels: next release

#435 Edit and proofread CONTRIBUTING.md
  CONTRIBUTING.md
Labels: next release
