Repository redwoodjs/graphql, pull requests merged in 2020-03, with the labels that each got.

#229 update sdl.js to use scalar datatypes in input types
  packages/cli/src/commands/generate/commands/sdl.js
Labels: enhancement

#230 Update send button accepts references
  packages/web/src/form/form.js
Labels: enhancement

#303 upgrade prisma preview24
  packages/api/package.json
  packages/cli/package.json
  packages/core/package.json
  yarn.lock
Labels: topic: prisma

#289 Check for local app's copy of dbInstance before resorting to @redwoodjs/api copy
  packages/core/config/babel-preset.js
  packages/internal/src/paths.ts
  packages/internal/src/types.ts
Labels: kind/improvement

#326 Fix service generator
  packages/cli/src/commands/generate/commands/service.js
Labels: bug/2-confirmed

#329 add system info cli command
  packages/cli/package.json
  packages/cli/src/commands/info.js
  yarn.lock
Labels: kind/improvement, topic: cli

#331 Improves Yargs --help output on Windows
  packages/cli/src/index.js
Labels: kind/improvement, topic: cli, topic: windows

#350 Prisma2 packages upgrade to preview025
  packages/api/package.json
  packages/cli/package.json
  packages/core/package.json
  yarn.lock
Labels: dependencies
