Repository redwoodjs/graphql, pull requests merged in 2020-08, with the labels that each got.

#918 Switch Date and Time scalar types to graphql-scalars
  packages/api/package.json
  packages/api/src/makeMergedSchema/rootSchema.ts
  yarn.lock
Labels: dependencies, kind/improvement, next release, topic: api

#931 Fix graphQLClientConfig bug in GraphQLWithAuth provider
  packages/web/src/components/RedwoodProvider.js
Labels: next release

#895 Remove importAll.macro
  packages/api/package.json
  packages/api/src/__tests__/__snapshots__/importAll.macro.test.js.snap
  packages/api/src/__tests__/fixtures/api/src/graphql/posts.sdl.ts
  packages/api/src/__tests__/fixtures/api/src/graphql/users.sdl.js
  packages/api/src/__tests__/fixtures/api/src/services/posts.ts
  packages/api/src/__tests__/fixtures/api/src/services/todos/todos.js
  packages/api/src/__tests__/fixtures/api/src/services/todos/todos.test.js
  packages/api/src/__tests__/fixtures/api/src/services/users.js
  packages/api/src/__tests__/importAll.macro.test.js
  packages/api/src/functions/authDecoder.test.ts
  packages/api/src/functions/fixtures/apiGatewayProxyEvent.fixture.ts
  packages/api/src/functions/graphql.test.ts
  packages/api/src/importAll.macro.js
  packages/core/config/babel-preset.js
  packages/core/src/__tests__/babel-plugin-redwood-import-dir.test.ts
  packages/core/src/__tests__/babel-plugin-redwood-mock-cell-data.test.ts
  packages/core/src/babel-plugin-redwood-import-dir.ts
  packages/internal/src/paths.ts
  packages/structure/src/ide.ts
  yarn.lock
Labels: next release

#938 Cleanup build commands
  .github/workflows/build-eslint-jest.yaml
  .gitignore
  .prettierignore
  babel.config.js
  package.json
  packages/api/package.json
  packages/api/src/functions/graphql.ts
  packages/api/tsconfig.json
  packages/auth/package.json
  packages/auth/tsconfig.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/tsconfig.json
  packages/create-redwood-app/package.json
  packages/dev-server/package.json
  packages/dev-server/tsconfig.json
  packages/eslint-plugin-redwood/package.json
  packages/forms/package.json
  packages/forms/src/types.d.ts
  packages/forms/tsconfig.json
  packages/internal/package.json
  packages/internal/src/__tests__/fixtures/api/test/test.ts
  packages/internal/tsconfig.json
  packages/router/package.json
  packages/structure/package.json
  packages/structure/tsconfig.json
  packages/testing/package.json
  packages/testing/tsconfig.json
  packages/web/package.json
  packages/web/src/global.web-auto-imports.ts
  packages/web/tsconfig.json
  tsconfig.compilerOption.json
  tsconfig.json
  yarn.lock
Labels: next release

#922 added types to @redwood/web, @redwood/forms
  .github/workflows/build-eslint-jest.yaml
  .gitignore
  package.json
  packages/api/package.json
  packages/api/tsconfig.json
  packages/auth/package.json
  packages/auth/tsconfig.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/tsconfig.json
  packages/create-redwood-app/package.json
  packages/dev-server/package.json
  packages/dev-server/tsconfig.json
  packages/eslint-config/index.js
  packages/eslint-plugin-redwood/package.json
  packages/forms/package.json
  packages/forms/src/index.d.ts
  packages/forms/src/types.d.ts
  packages/forms/tsconfig.json
  packages/internal/package.json
  packages/internal/tsconfig.json
  packages/router/package.json
  packages/router/src/index.d.ts
  packages/structure/package.json
  packages/structure/tsconfig.json
  packages/testing/package.json
  packages/testing/src/global.ts
  packages/testing/tsconfig.json
  packages/web/package.json
  packages/web/src/global.web-auto-imports.ts
  packages/web/src/index.d.ts
  tsconfig.compilerOption.json
  tsconfig.json
  yarn.lock
Labels: kind/improvement, topic: web

#948 dataMigrate exits(1) when failing
  packages/cli/src/commands/generate/dataMigration/dataMigration.js
Labels: kind/improvement

#882 Generate pages with route parameters
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/multiWordPage.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/paramPage.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/paramPage.stories.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/paramPage.test.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/pluralWordPage.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/singleWordPage.js
  packages/cli/src/commands/generate/page/__tests__/page.test.js
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/page/templates/page.js.template
  packages/cli/src/commands/generate/page/templates/stories.js.template
  packages/cli/src/commands/generate/page/templates/test.js.template
  packages/cli/src/lib/index.js
  packages/cli/src/lib/test.js
Labels: kind/improvement, next release, topic: generators, topic: router

#939 Add hasRole to Auth for RBAC
  .gitignore
  packages/api/src/functions/parseJWT.test.ts
  packages/api/src/index.ts
  packages/api/src/parseJWT.ts
  packages/auth/README.md
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/cli/src/commands/generate/auth/providers/auth0.js
  packages/cli/src/commands/generate/auth/templates/auth.js.template
  packages/router/src/router.js
Labels: next release, topic: auth

#940 Fix intermittent connection issues between web and api in devServer
  packages/core/config/webpack.development.js
Labels: next release, topic: web

#952 Warn instead of error on "prettier" deviations
  packages/eslint-config/index.js
Labels: next release

#959 Add a way to remove history listeners.
  packages/router/src/history.js
  packages/router/src/location.js
Labels: bug/2-confirmed, topic: router

#946 add forwardRef to form inputs
  packages/forms/package.json
  packages/forms/src/__tests__/form.test.js
  packages/forms/src/index.js
  yarn.lock
Labels: kind/improvement, topic: forms

#966 Add option to skip yarn install to create-redwood-app
  packages/create-redwood-app/src/create-redwood-app.js
Labels: next release, topic: create-redwood-app

#945 narrow main branch push trigger to markdown file changes
  .github/workflows/netlify-build.yaml
Labels: kind/improvement, topic: docs

#987 Add env variable diagnostics (fix #983 #971)
  packages/structure/package.json
  packages/structure/src/ide.ts
  packages/structure/src/language_server/RWLanguageServer.ts
  packages/structure/src/model/RWEnvHelper.ts
  packages/structure/src/model/RWProject.ts
  packages/structure/src/model/RWTOML.ts
  packages/structure/src/model/__tests__/model.test.ts
  packages/structure/src/model/util/__tests__/process_env_diagnostics.test.ts
  packages/structure/src/model/util/process_env.ts
  packages/structure/src/x/__tests__/prisma.test.ts
  packages/structure/src/x/__tests__/vscode-languageserver-types-x.test.ts
  packages/structure/src/x/prisma.ts
  packages/structure/src/x/vscode-languageserver-types.ts
  packages/structure/src/x/vscode.ts
  yarn.lock
Labels: next release, topic: project-structure

#792 Add `usePageLoadingContext` demo video to Router documentation.
  packages/router/README.md
Labels: next release, topic: docs, topic: router

#956 Memoize routes and named routes
  packages/router/src/router.js
Labels: next release, topic: router

#828 Add tailwind generator
  packages/cli/src/commands/generate.js
  packages/cli/src/commands/generate/util.js
  packages/cli/src/commands/generate/util/tailwind/tailwind.js
  packages/cli/src/commands/generate/util/tailwind/templates/postcss.config.js.template
Labels: next release, topic: generators

#984 Add Scaffold generator CLI warning when model contains @relation
  packages/cli/package.json
  packages/cli/src/commands/generate/scaffold/scaffold.js
Labels: next release

#1003 Fix webpack merge TypeError
  packages/core/config/webpack.development.js
Labels: topic: web

#935 Add documentation links to outline
  packages/structure/src/outline/outline.ts
Labels: next release

#1025 Fix tailwind generator
  packages/cli/src/commands/generate/util/tailwind/templates/postcss.config.js.template
Labels: topic: generators

#1026 Make tailwind generator append to index.css
  packages/cli/src/commands/generate/util/tailwind/tailwind.js
Labels: topic: generators

#973 support passing coercion functions to form fields
  packages/forms/src/__tests__/form.test.js
  packages/forms/src/coercion.js
  packages/forms/src/index.js
Labels: next release, next release docs, next release test, topic: forms

#1012 Add deploy command for api with aws_serverless provider
  packages/cli/src/commands/deploy.js
  packages/cli/src/commands/deploy/api/__tests__/api.test.js
  packages/cli/src/commands/deploy/api/api.js
  packages/cli/src/commands/deploy/api/providers/aws_serverless.js
Labels: next release, next release docs, next release test, topic: deployment

#1016 Auth RBAC, hasRole accepts a single role or an array of roles
  packages/auth/README.md
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/cli/src/commands/generate/auth/templates/auth.js.template
  packages/router/src/index.d.ts
  packages/router/src/router.js
Labels: next release, topic: auth

#976 Add aws_serverless provider for generate deploy command
  packages/cli/src/commands/generate/deploy/deploy.js
  packages/cli/src/commands/generate/deploy/providers/aws_serverless.js
Labels: next release

#960 Add a way to write and reference generated types
  .eslintignore
  packages/core/config/babel-preset.js
  packages/core/src/__tests__/babel-plugin-redwood-import-dir.test.ts
  packages/core/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-commented-exports/code.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-commented-exports/output.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-and-other-named-export/code.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-and-other-named-export/output.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-export/code.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-export/output.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-required-exports/code.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-required-exports/output.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/import-dir/__fixtures__/a.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/import-dir/__fixtures__/a.test.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/import-dir/__fixtures__/b.ts
  packages/core/src/babelPlugins/__tests__/__fixtures__/import-dir/__fixtures__/c.sdl.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/import-dir/__fixtures__/nested/d.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/import-dir/import-dir-default/code.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/import-dir/import-dir-default/output.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/mock-cell-data/output_NumTodosCell.mock.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/mock-cell-data/output_TodoListCell.mock.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/routes-auto-loader/routes-with-no-imports/code.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/routes-auto-loader/routes-with-no-imports/output.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/routes-auto-loader/routes-with-some-imports/code.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/routes-auto-loader/routes-with-some-imports/output.js
  packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-cell.test.ts
  packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-import-dir.test.ts
  packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-mock-cell-data.test.ts
  packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
  packages/core/src/babelPlugins/__tests__/generateTypes.test.ts
  packages/core/src/babelPlugins/babel-plugin-redwood-cell.ts
  packages/core/src/babelPlugins/babel-plugin-redwood-import-dir.ts
  packages/core/src/babelPlugins/babel-plugin-redwood-mock-cell-data.ts
  packages/core/src/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts
  packages/core/src/babelPlugins/generateTypes.ts
  packages/eslint-config/index.js
  packages/internal/src/paths.ts
  packages/router/src/index.d.ts
  packages/structure/src/hosts.ts
  packages/structure/src/ide.ts
  packages/structure/src/index.ts
  packages/structure/src/model/RWProject.ts
  packages/structure/src/model/RWRouter.ts
  packages/structure/src/model/__tests__/model.test.ts
  packages/structure/src/outline/__tests__/outline.test.ts
  wallaby.js
Labels: next release, next release docs

#964 feat: react-hook-form upgraded to latest version
  packages/forms/package.json
  packages/forms/src/index.js
  yarn.lock
Labels: breaking change
