Repository redwoodjs/graphql, pull requests merged in 2020-10, with the labels that each got.

#1234 Improve new Setup command
  packages/cli/src/commands/generate/util.js
  packages/cli/src/commands/generate/util/tailwind/tailwind.js
  packages/cli/src/commands/generate/util/tailwind/templates/postcss.config.js.template
  packages/cli/src/commands/setup.js
  packages/cli/src/commands/setup/tailwind/tailwind.js
Labels: next release, next release docs

#1179 modify generated tailwind config to opt-in to upcoming change
  packages/cli/src/commands/setup/tailwind/tailwind.js
Labels: topic: cli

#1294 (rw setup): Add command to setup webpack.config.js for web
  packages/cli/src/commands/setup/webpack/templates/webpack.config.js.template
  packages/cli/src/commands/setup/webpack/webpack.js
Labels: next release docs

#1300 Upgrade Prisma v2.8.1
  packages/api/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/structure/package.json
  yarn.lock
Labels: next release test

#1270 improve Upgrade command so `-t` accepts any string
  packages/cli/src/commands/upgrade.js
Labels: next release docs

#1291 🥮 @redwood/web typing: Add types to RedwoodProvider
  packages/auth/src/index.ts
  packages/web/src/components/RedwoodProvider.tsx
  packages/web/src/graphql/index.tsx
  packages/web/src/graphql/withCell.tsx
  packages/web/src/index.ts
Labels: next release

#1273 converted FatalErrorBoundary to typescript
  packages/web/src/components/FatalErrorBoundary.tsx
  packages/web/src/index.ts
Labels: next release

#1324 Fix storybook on Windows
  packages/core/config/storybook/main.js
Labels: next release, next release test

#1340 add validation for private routes
  packages/router/src/__tests__/router.test.js
  packages/router/src/router.js
Labels: next release

#1325 diagnostics throws error if a notfound route is within a Private tag
  packages/structure/src/model/RWRoute.ts
Labels: next release

#1284 Fix loaders initialization
  packages/router/package.json
  packages/router/src/__tests__/router.test.js
  packages/router/src/page-loader.js
  packages/router/src/router.js
  yarn.lock
Labels: next release, next release test

#1304 improve(cli): Add validation for tag supplied to rw upgrade
  packages/cli/src/commands/upgrade.js
Labels: next release docs

#1326 fix #1256 router "Create Page..." codelens positon
  packages/structure/src/model/RWRouter.ts
Labels: topic: project-structure, topic: vs-code IDE

#1331 Update VS Code private icon logic
  packages/structure/src/model/RWRoute.ts
  packages/structure/src/outline/outline.ts
Labels: topic: vs-code IDE

#1332 fix(web): Fix importing .ts/.tsx files in web with directory-named-import plugin
  packages/core/src/babelPlugins/__tests__/__fixtures__/directory-named-imports/TSWithIndex/TSWithIndex.ts
  packages/core/src/babelPlugins/__tests__/__fixtures__/directory-named-imports/TSWithIndex/index.js
  packages/core/src/babelPlugins/__tests__/__fixtures__/directory-named-imports/indexModule/indexModule.js
  packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-directory-named-imports.ts
  packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts
  packages/internal/src/paths.ts
Labels: next release

#1376 Fix Apollo Client imports
  package.json
  packages/api-server/ambient.d.ts
  packages/api-server/package.json
  packages/api-server/src/error.ts
  packages/auth/package.json
  packages/cli/src/commands/test.js
  packages/core/package.json
  packages/dev-server/ambient.d.ts
  packages/dev-server/package.json
  packages/dev-server/src/error.ts
  packages/forms/jest.config.js
  packages/forms/package.json
  packages/forms/src/__tests__/form.test.js
  packages/testing/package.json
  packages/web/package.json
  packages/web/src/graphql/withCell.tsx
  packages/web/src/index.ts
  yarn.lock
Labels: next release, next release test
