Repository redwoodjs/graphql, pull requests merged in 2020-11, with the labels that each got.

#1422 🚚 Updated the CLI command rw generate deploy anchor links to match the documentation for Netlify and Vercel
  packages/cli/src/commands/generate/deploy/providers/netlify.js
  packages/cli/src/commands/generate/deploy/providers/vercel.js
Labels: hacktoberfest-accepted

#1428 Add fetchPolicy and nextFetchPolicy to beforeQuery
  packages/web/src/graphql/withCell.tsx
Labels: breaking change, next release, next release docs

#1412 improve(auth): Add multiproviders for firebase auth
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/authClients/firebase.ts
Labels: hacktoberfest-accepted, next release

#1425 Add prismaVersion to redwood graphQL call
  packages/api/src/makeMergedSchema/rootSchema.ts
Labels: next release, next release test

#1431 @redwoodjs/forms: Convert to TS
  packages/forms/package.json
  packages/forms/src/__tests__/form.test.tsx
  packages/forms/src/coercion.js
  packages/forms/src/coercion.tsx
  packages/forms/src/index.d.ts
  packages/forms/src/index.tsx
  packages/forms/tsconfig.json
  yarn.lock
Labels: next release, next release test

#1432 fix nested scaffolding QUERY import filepaths
  packages/cli/src/commands/generate/scaffold/templates/components/Name.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template
Labels: bug/2-confirmed, next release, next release test

#1440 fix prisma version field resolver not working
  packages/api/src/makeMergedSchema/rootSchema.ts
Labels: bug/2-confirmed, next release, next release test

#1415 Fix `rw test` watch logic
  packages/cli/src/commands/test.js
Labels: hacktoberfest-accepted, next release, next release test

#1461 Add fast-refresh plugin. Experimental support only
  packages/core/config/webpack.common.js
  packages/core/config/webpack.development.js
  packages/core/package.json
  packages/internal/src/config.ts
  yarn.lock
Labels: next release, next release test

#1445 Add flag to storybook command
  packages/cli/src/commands/storybook.js
Labels: kind/improvement, next release, next release test, topic: cli, topic: docs, topic: storybook

#1441 Small http server tweaks
  packages/api-server/src/http.ts
  packages/dev-server/src/http.ts
Labels: next release, next release test

#1447 Run Jest tests in sequence
  packages/cli/src/commands/test.js
Labels: next release, next release test, topic: testing

#1442 Fixes setting Prisma Version in root redwood schema
  packages/api/src/makeMergedSchema/rootSchema.ts
Labels: kind/improvement, next release, next release test, topic: api, topic: prisma

#1464 Move fast-refresh config to work with storybook
  packages/core/config/webpack.common.js
  packages/core/config/webpack.development.js
Labels: next release, next release test

#1424 Add schema path
  packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js
  packages/cli/src/commands/dbCommands/down.js
  packages/cli/src/commands/dbCommands/generate.js
  packages/cli/src/commands/dbCommands/introspect.js
  packages/cli/src/commands/dbCommands/options.ts
  packages/cli/src/commands/dbCommands/save.js
  packages/cli/src/commands/dbCommands/studio.js
  packages/cli/src/commands/dbCommands/up.js
  packages/cli/src/index.d.ts
  packages/cli/src/lib/index.js
  packages/internal/src/__tests__/config.test.ts
  packages/internal/src/config.ts
  packages/internal/src/paths.ts
Labels: kind/improvement, topic: api, topic: generators, topic: prisma

#1492 Fixes DB Generators failing when a schema path includes spaces or other problematic characters
  packages/cli/src/commands/__tests__/build.test.js
  packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js
  packages/cli/src/commands/dbCommands/down.js
  packages/cli/src/commands/dbCommands/generate.js
  packages/cli/src/commands/dbCommands/introspect.js
  packages/cli/src/commands/dbCommands/save.js
  packages/cli/src/commands/dbCommands/studio.js
  packages/cli/src/commands/dbCommands/up.js
Labels: topic: generators, topic: prisma

#1495 Fix #1278 launch Storybook with path w/ spaces
  packages/cli/src/commands/storybook.js
Labels: topic: cli, topic: storybook

#1494 Fixes #1279 Cannot run tests when the project app path includes spaces or other problematic characters
  packages/cli/src/commands/test.js
Labels: topic: cli, topic: testing

#1497 Remove unnecessary refetchQuery calls
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/new.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/new.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/show.js
  packages/cli/src/commands/generate/scaffold/templates/components/Name.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template
Labels: next release docs

#1498 Allow users to "bring your own" GraphQL Library
  packages/web/src/components/FetchConfigProvider.test.tsx
  packages/web/src/components/FetchConfigProvider.tsx
  packages/web/src/components/GraphQLHooksProvider.test.tsx
  packages/web/src/components/GraphQLHooksProvider.tsx
  packages/web/src/components/RedwoodApolloProvider.tsx
  packages/web/src/components/RedwoodProvider.tsx
  packages/web/src/components/withCellHOC.tsx
  packages/web/src/config.ts
  packages/web/src/graphql/index.tsx
  packages/web/src/index.ts
  packages/web/tsconfig.json
Labels: next release, next release docs, next release test

#1515 Fix FetchConfigProvider to reprise handling no auth
  packages/web/src/components/FetchConfigProvider.tsx
Labels: kind/bug, topic: web

#1516 Add --build option to `yarn rw storybook`
  packages/cli/src/commands/storybook.js
  packages/core/config/storybook/main.js
Labels: next release, next release docs

#1405 update diagnostics to display success message when no errors or warnings are encountered
  packages/structure/src/index.ts
Labels: hacktoberfest-accepted, next release, topic: project-structure

#1519 Only stop rendering on Private routes
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/router/package.json
  packages/router/src/__tests__/router.test.js
  packages/router/src/router.js
  packages/testing/src/MockProviders.tsx
  packages/web/src/components/FetchConfigProvider.test.tsx
  packages/web/src/components/FetchConfigProvider.tsx
Labels: next release, next release docs, next release test
