Repository redwoodjs/graphql, pull requests merged in 2020-06, with the labels that each got.

#632 Convert component generator to TS
  packages/cli/src/commands/generate/component/__tests__/component.test.js
  packages/cli/src/commands/generate/component/__tests__/component.test.ts
  packages/cli/src/commands/generate/component/__tests__/fixtures/multiWordComponent.test.tsx
  packages/cli/src/commands/generate/component/__tests__/fixtures/multiWordComponent.tsx
  packages/cli/src/commands/generate/component/__tests__/fixtures/singleWordComponent.test.tsx
  packages/cli/src/commands/generate/component/__tests__/fixtures/singleWordComponent.tsx
  packages/cli/src/commands/generate/component/component.js
  packages/cli/src/commands/generate/component/templates/component.tsx.template
  packages/cli/src/commands/generate/component/templates/test.tsx.template
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/enumGeneratedSdl.js
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/multiWordSdl.js
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/multiWordSdlCrud.js
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdl.js
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdlCrud.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/multiWord.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/multiWord.test.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/multiWord_crud.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/multiWord_crud.test.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord.test.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_belongsTo.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_crud.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_crud.test.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_hasMany.js
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_multiple.js
  packages/cli/src/index.d.ts
  packages/cli/src/lib/index.js
Labels: next release

#543 Fix Windows CI Runner Failing Tests
  .github/workflows/build-eslint-jest.yaml
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/component/__tests__/component.test.ts
  packages/cli/src/commands/generate/function/__tests__/function.test.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/layout/__tests__/layout.test.js
  packages/cli/src/commands/generate/page/__tests__/page.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPath.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiword.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathNested.test.js
  packages/cli/src/commands/generate/sdl/__tests__/sdl.test.js
  packages/cli/src/commands/generate/service/__tests__/service.test.js
Labels: help wanted, topic: CI | test | lint | build, topic: windows

#662 SCSS/CSS Module support
  packages/core/config/webpack.common.js
Labels: next release

#665 Fix windows matching paths in babel.
  packages/core/config/babel-preset.js
Labels: next release

#599 Format errors in terminal
  packages/api/src/functions/graphQLServer.ts
  packages/cli/src/commands/dev.js
  packages/dev-server/ambient.d.ts
  packages/dev-server/package.json
  packages/dev-server/src/error.ts
  packages/dev-server/src/main.ts
  packages/dev-server/src/requestHandlers/awsLambda.ts
  packages/dev-server/src/watchApiSide.ts
  yarn.lock
Labels: next release

#643 Firebase generator
  packages/cli/src/commands/generate/auth/auth.js
  packages/cli/src/commands/generate/auth/providers/auth0.js
  packages/cli/src/commands/generate/auth/providers/firebase.js
  packages/cli/src/commands/generate/auth/providers/magic-link.js
  packages/cli/src/commands/generate/auth/providers/netlify.js
  packages/cli/src/commands/generate/auth/templates/firebase.auth.js.template
Labels: next release

#637 Reorganize @redwoodjs/auth
  package.json
  packages/api/README.md
  packages/api/package.json
  packages/api/src/__tests__/graphql.test.ts
  packages/api/src/auth/authHeaders.ts
  packages/api/src/functions/graphql.ts
  packages/api/src/globalContext.ts
  packages/api/src/main.ts
  packages/api/src/makeMergedSchema/rootSchema.ts
  packages/api/tsconfig.json
  packages/auth/README.md
  packages/auth/package.json
  packages/auth/src/AuthProvider.test.tsx
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/authClient.ts
  packages/auth/src/authClients/auth0.ts
  packages/auth/src/authClients/custom.ts
  packages/auth/src/authClients/firebase.ts
  packages/auth/src/authClients/goTrue.ts
  packages/auth/src/authClients/index.ts
  packages/auth/src/authClients/magicLink.ts
  packages/auth/src/authClients/netlify.ts
  packages/auth/src/index.ts
  packages/auth/src/useAuth.ts
  packages/auth/tsconfig.json
  packages/cli/src/commands/generate/auth/providers/magicLink.js
  packages/eslint-config/index.js
  yarn.lock
Labels: next release

#661 Add --auto-approve to `db up`
  packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js
  packages/cli/src/commands/dbCommands/up.js
Labels: next release

#677 Links: Use browser default behavior for ctrl-clicks etc
  packages/router/src/links.js
Labels: next release

#671 feat(create-redwood-app): cli flags to show up help and version information
  packages/create-redwood-app/src/create-redwood-app.js
Labels: kind/improvement, topic: cli, topic: create-redwood-app

#703 Make `yarn rw build api` also transpile .ts extensions.
  packages/cli/package.json
Labels: next release

#694 rwt copy fix for Windows
  CONTRIBUTING.md
  packages/cli/src/redwood-tools.js
Labels: next release

#696 Use PostCSS loader if a PostCSS config file is present
  packages/core/config/webpack.common.js
  packages/internal/src/paths.ts
Labels: next release

#699 Remove `prisma generate --watch` task from dev command.
  packages/cli/src/commands/dev.js
  yarn.lock
Labels: next release

#689 Wrap MSW graphql for convenience
  packages/auth/package.json
  packages/core/package.json
  packages/testing/package.json
  packages/testing/src/index.js
  packages/testing/src/index.ts
  packages/testing/tsconfig.json
  packages/web/package.json
  tsconfig.json
  yarn.lock
Labels: topic: testing

#685 Convert layout generator to TypeScript
  packages/cli/src/commands/generate/component/__tests__/component.test.ts
  packages/cli/src/commands/generate/component/__tests__/fixtures/multiWordComponent.tsx
  packages/cli/src/commands/generate/component/__tests__/fixtures/singleWordComponent.tsx
  packages/cli/src/commands/generate/component/component.js
  packages/cli/src/commands/generate/component/templates/component.tsx.template
  packages/cli/src/commands/generate/layout/__tests__/fixtures/multiWordLayout.js
  packages/cli/src/commands/generate/layout/__tests__/fixtures/multiWordLayout.test.tsx
  packages/cli/src/commands/generate/layout/__tests__/fixtures/multiWordLayout.tsx
  packages/cli/src/commands/generate/layout/__tests__/fixtures/singleWordLayout.js
  packages/cli/src/commands/generate/layout/__tests__/fixtures/singleWordLayout.test.tsx
  packages/cli/src/commands/generate/layout/__tests__/fixtures/singleWordLayout.tsx
  packages/cli/src/commands/generate/layout/__tests__/layout.test.js
  packages/cli/src/commands/generate/layout/__tests__/layout.test.ts
  packages/cli/src/commands/generate/layout/layout.js
  packages/cli/src/commands/generate/layout/templates/layout.js.template
  packages/cli/src/commands/generate/layout/templates/layout.tsx.template
  packages/cli/src/commands/generate/layout/templates/test.tsx.template
  packages/cli/src/index.d.ts
Labels: next release, topic: generators

#650 Add useLocation hook to Redwood Router
  packages/router/src/__tests__/location.test.js
  packages/router/src/index.js
  packages/router/src/links.js
  packages/router/src/location.js
Labels: next release, topic: router

#721 Add reauthenticate method to useAuth
  packages/auth/README.md
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/__tests__/AuthProvider.test.tsx
Labels: next release, topic: auth

#720 Suggestion: Change custom authHeader to return type
  packages/api/src/auth/authHeaders.ts
Labels: next release, topic: auth

#704 chore: leverage yargs arg-parser lib
  packages/create-redwood-app/package.json
  packages/create-redwood-app/src/create-redwood-app.js
Labels: next release, topic: cli

#724 Optimize Flash component
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/assets/scaffold.css
  packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template
  packages/web/src/flash/Flash.js
Labels: next release

#729 Fixes auth firebase
  packages/auth/package.json
  packages/cli/src/commands/generate/auth/templates/firebase.auth.js.template
Labels: next release, topic: auth

#728 Add cypress integration tests for tutorial
  CONTRIBUTING.md
  __fixtures__/new-project/.editorconfig
  __fixtures__/new-project/.env.defaults
  __fixtures__/new-project/.gitignore
  __fixtures__/new-project/.nvmrc
  __fixtures__/new-project/.vscode/extensions.json
  __fixtures__/new-project/.vscode/settings.json
  __fixtures__/new-project/LICENSE
  __fixtures__/new-project/README.md
  __fixtures__/new-project/api/.babelrc.js
  __fixtures__/new-project/api/jsconfig.json
  __fixtures__/new-project/api/package.json
  __fixtures__/new-project/api/prisma/schema.prisma
  __fixtures__/new-project/api/prisma/seeds.js
  __fixtures__/new-project/api/src/functions/graphql.js
  __fixtures__/new-project/api/src/graphql/.keep
  __fixtures__/new-project/api/src/lib/db.js
  __fixtures__/new-project/api/src/services/.keep
  __fixtures__/new-project/babel.config.js
  __fixtures__/new-project/netlify.toml
  __fixtures__/new-project/package.json
  __fixtures__/new-project/prettier.config.js
  __fixtures__/new-project/redwood.toml
  __fixtures__/new-project/web/.babelrc.js
  __fixtures__/new-project/web/jsconfig.json
  __fixtures__/new-project/web/package.json
  __fixtures__/new-project/web/public/README.md
  __fixtures__/new-project/web/public/favicon.png
  __fixtures__/new-project/web/public/robots.txt
  __fixtures__/new-project/web/src/Routes.js
  __fixtures__/new-project/web/src/components/.keep
  __fixtures__/new-project/web/src/index.css
  __fixtures__/new-project/web/src/index.html
  __fixtures__/new-project/web/src/index.js
  __fixtures__/new-project/web/src/layouts/.keep
  __fixtures__/new-project/web/src/pages/FatalErrorPage/FatalErrorPage.js
  __fixtures__/new-project/web/src/pages/NotFoundPage/NotFoundPage.js
  __fixtures__/new-project/yarn.lock
  tasks/e2e/cypress.json
  tasks/e2e/cypress/integration/tutorial/codemods/Step2_1_PagesHome.js
  tasks/e2e/cypress/integration/tutorial/codemods/Step2_2_PagesAbout.js
  tasks/e2e/cypress/integration/tutorial/codemods/Step3_1_LayoutsBlog.js
  tasks/e2e/cypress/integration/tutorial/codemods/Step3_2_PagesHome.js
  tasks/e2e/cypress/integration/tutorial/codemods/Step3_3_PagesAbout.js
  tasks/e2e/cypress/integration/tutorial/codemods/Step4_1_DbSchema.js
  tasks/e2e/cypress/integration/tutorial/codemods/Step5_1_ComponentsCellBlogPost.js
  tasks/e2e/cypress/integration/tutorial/codemods/Step5_2_PagesHome.js
  tasks/e2e/cypress/integration/tutorial/tutorial.js
  tasks/e2e/cypress/plugins/index.js
  tasks/e2e/cypress/support/commands.js
  tasks/e2e/cypress/support/index.js
  tasks/e2e/package.json
  tasks/e2e/yarn.lock
  tasks/test-tutorial
Labels: next release, topic: contributor-dx

#735 Generate Prisma client if it doesn't exist
  packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js
  packages/cli/src/commands/dbCommands/generate.js
  packages/cli/src/commands/dev.js
Labels: next release, topic: prisma

#736 commandeer ports when they are in use
  packages/cli/src/commands/dev.js
  packages/internal/ambient.d.ts
  packages/internal/package.json
  packages/internal/src/dev.ts
  packages/internal/src/main.ts
  packages/internal/tsconfig.json
  yarn.lock
Labels: next release, topic: cli

#744 Actually build TS files.
  packages/cli/src/commands/build.js
Labels: bug/2-confirmed

#746 fix(import-dir): Ignore file extensions | Ignore .test files
  packages/core/src/__tests__/__fixtures__/import-dir/__fixtures__/a.test.js
  packages/core/src/__tests__/__fixtures__/import-dir/import-dir-default/output.js
  packages/core/src/babel-plugin-redwood-import-dir.ts
Labels: next release

#732 scaffold: Use checkbox to display boolean value
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/assets/scaffold.css
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/index.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template
  packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template
Labels: topic: scaffold

#733 scaffold: humanize <th>
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/index.js
  packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template
Labels: topic: scaffold

#756 Add useLocation hook to router readme
  packages/router/README.md
Labels: topic: docs, topic: router

#742 Add support for Storybook
  .eslintignore
  __fixtures__/new-project/api/package.json
  __fixtures__/new-project/package.json
  __fixtures__/new-project/web/package.json
  __fixtures__/new-project/yarn.lock
  package.json
  packages/cli/package.json
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/multiWordCell.stories.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/singleWordCell.stories.js
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/cell/templates/stories.js.template
  packages/cli/src/commands/generate/component/__tests__/component.test.ts
  packages/cli/src/commands/generate/component/__tests__/fixtures/multiWordComponent.stories.tsx
  packages/cli/src/commands/generate/component/__tests__/fixtures/singleWordComponent.stories.tsx
  packages/cli/src/commands/generate/component/component.js
  packages/cli/src/commands/generate/component/templates/stories.tsx.template
  packages/cli/src/commands/generate/layout/__tests__/fixtures/multiWordLayout.stories.tsx
  packages/cli/src/commands/generate/layout/__tests__/fixtures/singleWordLayout.stories.tsx
  packages/cli/src/commands/generate/layout/__tests__/layout.test.ts
  packages/cli/src/commands/generate/layout/layout.js
  packages/cli/src/commands/generate/layout/templates/stories.tsx.template
  packages/cli/src/commands/generate/page/__tests__/fixtures/multiWordPage.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/multiWordPage.stories.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/pluralWordPage.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/singleWordPage.js
  packages/cli/src/commands/generate/page/__tests__/fixtures/singleWordPage.stories.js
  packages/cli/src/commands/generate/page/__tests__/page.test.js
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/page/templates/page.js.template
  packages/cli/src/commands/generate/page/templates/stories.js.template
  packages/cli/src/commands/storybook.js
  packages/core/config/jest.config.web.js
  packages/core/config/storybook/.babelrc
  packages/core/config/storybook/main.js
  packages/core/config/storybook/preview.js
  packages/core/config/webpack.common.js
  packages/core/package.json
  packages/core/tsconfig.json
  packages/eslint-config/index.js
  packages/testing/src/MockProviders.tsx
  packages/testing/src/MockRouter.tsx
  packages/testing/src/customRender.tsx
  packages/testing/src/fileMock.ts
  packages/testing/src/index.ts
  packages/testing/src/mockServer.ts
  packages/testing/src/redwoodjs_router.d.ts
  packages/testing/src/redwoodjs_web.d.ts
  packages/testing/src/render.js
  packages/testing/tsconfig.json
  yarn.lock
Labels: next release, topic: web

#763 Generators: Workaround for POSIX-to-Windows path conversion
  packages/cli/src/commands/generate/page/__tests__/page.test.js
  packages/cli/src/commands/generate/page/page.js
Labels: next release

#769 Add a GoTrue-JS provider to the CLI auth generator
  packages/auth/README.md
  packages/cli/src/commands/generate/auth/providers/goTrue.js
Labels: kind/improvement, next release, topic: auth, topic: generators

#770 API: Fix for function based context to run on each request
  packages/api/src/__tests__/graphql.test.ts
  packages/api/src/functions/graphql.ts
Labels: next release
