Repository redwoodjs/graphql, pull requests merged in 2021-11, with the labels that each got.

#3657 Fix prerender if run inside `web` directory
  packages/internal/src/build/babel/web.ts
  packages/prerender/src/runPrerender.tsx
Labels: hacktoberfest-accepted

#3584 Use a green hue shift for the app favicon
  packages/create-redwood-app/template/web/public/favicon.png
Labels: hacktoberfest-accepted

#3644 Create Tailwind version of scaffold.css if Tailwind installed
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/shouldUseTailwindCSS.test.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template
  packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.tailwind.css.template
  packages/cli/src/lib/test.js
Labels: topic/generators-&-scaffolds, hacktoberfest-accepted, v1/for-consideration

#3653 Update docs for codemod to make contributions easier
  packages/codemods/README.md
Labels: hacktoberfest-accepted

#3687 Update package.json to include the repository
  packages/api-server/package.json
  packages/api/package.json
  packages/auth/package.json
  packages/cli/package.json
  packages/codemods/package.json
  packages/core/package.json
  packages/create-redwood-app/package.json
  packages/eslint-config/package.json
  packages/forms/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/testing/package.json
  packages/web/package.json
Labels: triage/processing

#3490 Upgrade Azure Active Directory authentication from msal to @azure/msal-*
  packages/api/src/auth/decoders/azureActiveDirectory.ts
  packages/auth/src/authClients/azureActiveDirectory.ts
Labels: next-release/breaking, hacktoberfest-accepted, next-release/code-mod

#3696 Fix styling of logo on splash page after tailwind setup
  packages/router/src/splash-page.tsx
Labels: triage/processing

#3698 dbAuth: Resolved typos and inconsistencies in templates
  packages/cli/src/commands/generate/dbAuth/templates/forgotPassword.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/resetPassword.tsx.template
Labels: topic/auth

#3699 Glob param type should not include ellipsis in extracted variable name
  packages/router/src/__tests__/util.test.ts
  packages/router/src/util.ts
Labels: topic/router, bug/confirmed, v1/priority

#3697 createCell tests
  packages/web/src/components/createCell.test.tsx
  packages/web/src/components/createCell.tsx
Labels: topic/cells, v1/priority

#3681 Move api-server to fastify 🏎️
  README.md
  packages/api-server/ambient.d.ts
  packages/api-server/package.json
  packages/api-server/src/__tests__/withWebServer.test.ts
  packages/api-server/src/app.ts
  packages/api-server/src/cliHandlers.ts
  packages/api-server/src/error.ts
  packages/api-server/src/index.ts
  packages/api-server/src/middleware/withApiProxy.ts
  packages/api-server/src/middleware/withWebServer.ts
  packages/api-server/src/plugins/withApiProxy.ts
  packages/api-server/src/plugins/withFunctions.ts
  packages/api-server/src/plugins/withWebServer.ts
  packages/api-server/src/requestHandlers/awsLambdaFastify.ts
  packages/api-server/src/server.ts
  packages/api-server/src/watch.ts
  packages/cli/src/commands/serve.js
  packages/codemods/package.json
  packages/internal/src/files.ts
  yarn.lock
Labels: topic/api, v1/priority

#3618 Update README.md with testing details
  README.md
Labels: hacktoberfest-accepted

#3709 Fixes syntax error Firebase Auth template initializeApp
  packages/cli/src/commands/setup/auth/templates/firebase.auth.ts.template
Labels: triage/processing

#3708 feat(rw-toml): Support env var interpolation in redwood.toml
  packages/internal/package.json
  packages/internal/src/__tests__/config.test.ts
  packages/internal/src/__tests__/fixtures/redwood.withEnv.toml
  packages/internal/src/config.ts
  yarn.lock
Labels: next-release/update-docs

#3702 Teach named route function to handle glob routes
  packages/router/src/__tests__/util.test.ts
  packages/router/src/util.ts
Labels: triage/processing

#3717 Remove Codesee integration
  .github/workflows/codesee-arch-diagram.yml
Labels: triage/processing

#3718 More router tests
  packages/router/src/__tests__/util.test.ts
Labels: triage/processing

#3705 Base64 encode smaller required images during prerender
  packages/prerender/package.json
  packages/prerender/src/babelPlugins/__tests__/babel-plugin-redwood-prerender-media-imports.test.ts
  packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts
  packages/prerender/src/babelPlugins/utils.ts
  yarn.lock
Labels: triage/processing

#3716 Have Redwood figure out in what order tables need to be cleared during scenario teardown
  packages/testing/config/jest/api/jest.setup.js
Labels: bug/confirmed, v1/priority

#3722 Regenerate lock file(s)
  packages/router/src/__tests__/util.test.ts
Labels: triage/processing

#3714 Throw error on missing param in named route function
  packages/router/src/__tests__/util.test.ts
  packages/router/src/util.ts
Labels: v1/priority

#3724 Scenario teardown needs to catch different error codes from Postgres and MySQL
  packages/testing/config/jest/api/jest.setup.js
Labels: triage/processing

#3732 Rename paramType properties
  README.md
  packages/internal/src/generate/templates/web-routerRoutes.d.ts.template
  packages/router/src/util.ts
Labels: triage/processing

#3720 Set Apollo's verbosity to debug and update Cell's error message
  packages/web/src/apollo/index.tsx
  packages/web/src/components/createCell.tsx
Labels: triage/processing

#3735 Add RWJS_API_URL to global
  packages/auth/ambient.d.ts
  packages/core/config/webpack.common.js
  packages/prerender/ambient.d.ts
  packages/router/ambient.d.ts
  packages/web/ambient.d.ts
  packages/web/src/config.ts
  packages/web/src/global.web-auto-imports.ts
Labels: next-release/update-docs, triage/processing

#3635 Adds warning in auth templates about the return of getCurrentUser() on the web side
  packages/cli/src/commands/setup/auth/templates/auth.ts.template
  packages/cli/src/commands/setup/auth/templates/azureActiveDirectory.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/ethereum.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/firebase.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/magicLink.auth.js.template
Labels: hacktoberfest-accepted, next-release/update-docs, next-release/code-mod

#3694 Feat: Allow to override `isEmpty` in Cells
  packages/internal/src/build/babelPlugins/babel-plugin-redwood-cell.ts
  packages/web/src/components/createCell.tsx
Labels: topic/cells, v1/priority

#3746 Make Apollo Client cache resilient to changes in Auth
  packages/web/src/apollo/index.tsx
Labels: bug/confirmed

#3749 cli: deprecate `setup tailwind` and move into new command `setup ui <library>`
  packages/cli/src/commands/setup.js
  packages/cli/src/commands/setup/custom-web-index/custom-web-index.js
  packages/cli/src/commands/setup/i18n/i18n.js
  packages/cli/src/commands/setup/tailwind.js
  packages/cli/src/commands/setup/tsconfig/tsconfig.js
  packages/cli/src/commands/setup/ui.js
  packages/cli/src/commands/setup/ui/tailwindcss.js
  packages/cli/src/commands/setup/ui/templates/postcss.config.js.template
  packages/cli/src/commands/setup/webpack/webpack.js
  tasks/test-project/tasks.js
Labels: next-release/breaking, next-release/update-docs, triage/processing

#3736 Various gql codegen fixes
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/internal/src/__tests__/typeDefinitions.test.ts
  packages/internal/src/generate/typeDefinitions.ts
  yarn.lock
Labels: next-release/update-docs, triage/processing

#3719 Removes babel configuration from users project
  .eslintrc.js
  __fixtures__/example-todo-main/api/src/lib/transform.js
  __fixtures__/example-todo-main/babel.config.js
  __fixtures__/example-todo-main/web/.babelrc.js
  babel.config.js
  packages/api/package.json
  packages/cli/package.json
  packages/cli/src/commands/build.js
  packages/cli/src/commands/dev.js
  packages/cli/src/commands/test.js
  packages/cli/src/middleware/checkForBabelConfig.js
  packages/core/config/babel-preset.js
  packages/core/config/webpack.common.js
  packages/create-redwood-app/template/babel.config.js
  packages/create-redwood-app/template/web/.babelrc.js
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/eslint-config/shared.js
  packages/internal/src/__tests__/build_api.test.ts
  packages/internal/src/build/babel/api.ts
  packages/internal/src/build/babel/common.ts
  packages/internal/src/build/babel/web.ts
  packages/internal/src/index.ts
  packages/internal/tsconfig.json
  packages/testing/config/jest/api/index.js
  packages/testing/config/jest/web/index.js
  packages/testing/config/storybook/.babelrc
  yarn.lock
Labels: next-release/breaking, next-release/update-docs, next-release/code-mod

#3723 fix: Update serverless framework integration for TS compatibility
  packages/cli/src/commands/deploy/aws-providers/serverless.js
  packages/cli/src/commands/setup/deploy/providers/aws-serverless.js
Labels: topic/deployment

#3713 Update Auth templates for CurrentUser types and JWT/Error imports
  packages/cli/src/commands/setup/auth/templates/auth.ts.template
  packages/cli/src/commands/setup/auth/templates/azureActiveDirectory.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/firebase.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/magicLink.auth.js.template
Labels: v1/priority, next-release/code-mod

#3656 Fix Scaffold Checkbox required field
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/scaffold.js
Labels: hacktoberfest-accepted

#3658 [RedwoodApolloProvider] Make Apollo Link configurable
  packages/web/src/apollo/index.tsx
Labels: hacktoberfest-accepted

#3748 Don't show splashPage on production
  packages/router/src/router.tsx
Labels: triage/processing

#3725 chore: Upgrade ESLint from v7 to v8
  package.json
  packages/eslint-config/package.json
  packages/forms/src/index.tsx
  packages/internal/src/generate/graphqlSchema.ts
  packages/router/src/links.tsx
  yarn.lock
Labels: dependencies, next-release/breaking

#2896 [v1.0.0-rc] Remove deprecated features
  packages/cli/README.md
  packages/cli/package.json
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/redwood-tools.js
  packages/router/ambient.d.ts
  packages/web/src/global.web-auto-imports.ts
  yarn.lock
Labels: next-release/breaking, next-release/update-docs, v1/priority, next-release/code-mod

#3688 Storybook: Add support for a custom `manager.js`
  packages/cli/src/commands/storybook.js
  packages/internal/src/paths.ts
  packages/testing/config/storybook/main.js
  packages/testing/config/storybook/manager.example.js
  packages/testing/config/storybook/manager.js
Labels: topic/storybook, v1/for-consideration

#3759 Upgrade misc dependencies for v0.39.0 (including TS 4.5)
  package.json
  packages/api-server/package.json
  packages/api/package.json
  packages/auth/package.json
  packages/cli/package.json
  packages/codemods/package.json
  packages/core/package.json
  packages/create-redwood-app/package.json
  packages/eslint-config/package.json
  packages/forms/package.json
  packages/graphql-server/package.json
  packages/graphql-server/src/plugins/useRedwoodLogger.ts
  packages/internal/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/testing/package.json
  packages/web/package.json
  tasks/e2e/cypress/integration/03-storybook/storybook.spec.js
  tasks/e2e/package.json
  tasks/e2e/yarn.lock
  tasks/framework-tools/package.json
  tasks/framework-tools/yarn.lock
  yarn.lock
Labels: dependencies, next-release/breaking

#3761 bump CRWA node engine to 14.17
  packages/codemods/src/codemods/v0.38.x/updateNodeEngine/README.md
  packages/codemods/src/codemods/v0.38.x/updateNodeEngine/updateNodeEngine.ts
  packages/create-redwood-app/template/package.json
Labels: next-release/breaking, next-release/update-docs, next-release/code-mod

#3651 Upgrade Clerk Auth to v2
  packages/auth/package.json
  yarn.lock
Labels: next-release/breaking, hacktoberfest-accepted, triage/processing

#3763 Add tests for isEmpty
  packages/web/src/components/createCell.test.tsx
Labels: triage/processing

#3754 Run jscodeshift programmatically
  packages/codemods/README.md
  packages/codemods/package.json
  packages/codemods/src/codemods/v0.37.x/updateApiImports/__tests__/updateApiImports.test.ts
  packages/codemods/src/codemods/v0.37.x/updateApiImports/updateApiImports.yargs.ts
  packages/codemods/src/codemods/v0.37.x/updateForms/__tests__/updateForms.test.ts
  packages/codemods/src/codemods/v0.37.x/updateForms/updateForms.yargs.ts
  packages/codemods/src/codemods/v0.37.x/updateGraphQLFunction/__tests__/updateGraphQLFunction.test.ts
  packages/codemods/src/codemods/v0.37.x/updateGraphQLFunction/updateGraphQLFunction.yargs.ts
  packages/codemods/src/codemods/v0.37.x/updateScenarios/__tests__/updateScenarios.test.ts
  packages/codemods/src/codemods/v0.37.x/updateScenarios/updateScenarios.yargs.ts
  packages/codemods/src/lib/runTransform.ts
  packages/codemods/testUtils/index.ts
  yarn.lock
Labels: triage/processing

#3766 Running tests no longer warn about api and graphql-server multiple jest configurations
  packages/api/package.json
  packages/graphql-server/package.json
Labels: triage/processing

#3770 onClick should be optional on Link
  packages/router/src/links.tsx
Labels: topic/router, topic/typescript, triage/processing

#3771 Update Supabase to favor use of session over deprecated data and use ApiError in auth api responses
  packages/auth/package.json
  packages/auth/src/authClients/supabase.ts
  yarn.lock
Labels: next-release/breaking

#3774 Upgrade Apollo Client
  packages/web/package.json
  packages/web/src/components/createCell.tsx
  yarn.lock
Labels: topic/graphql, v1/priority

#3760 upgrade graphql v16.0.1
  packages/core/package.json
  packages/forms/src/FormError.tsx
  packages/graphql-server/package.json
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/functions/types.ts
  packages/internal/package.json
  packages/structure/package.json
  packages/web/package.json
  packages/web/src/components/createCell.tsx
  yarn.lock
Labels: next-release/breaking

#3769 Give Cells a displayName
  packages/internal/src/build/babelPlugins/__tests__/__fixtures__/cell/cell-with-commented-exports/output.js
  packages/internal/src/build/babelPlugins/__tests__/__fixtures__/cell/cell-with-required-exports/output.js
  packages/internal/src/build/babelPlugins/babel-plugin-redwood-cell.ts
  packages/web/src/components/createCell.tsx
Labels: topic/cells

#3776 Refactor `createCell`
  packages/web/src/apollo/index.tsx
  packages/web/src/components/createCell.tsx
Labels: topic/cells

#3785 Implements a wrapper for serverless functions to support requireAuth
  packages/cli/src/commands/setup/auth/templates/auth.ts.template
  packages/graphql-server/src/functions/__tests__/useRequireAuth.test.ts
  packages/graphql-server/src/functions/useRequireAuth.ts
  packages/graphql-server/src/index.ts
Labels: triage/processing

#3734 Adds experimental RedwoodRecord package
  .eslintrc.js
  packages/api/src/validations/__tests__/validations.test.js
  packages/api/src/validations/errors.ts
  packages/cli/src/commands/generate/model/model.js
  packages/cli/src/commands/generate/model/templates/model.js.template
  packages/cli/src/commands/record.js
  packages/cli/src/commands/record/init.js
  packages/internal/src/paths.ts
  packages/record/.babelrc.js
  packages/record/README.md
  packages/record/package.json
  packages/record/src/errors.js
  packages/record/src/index.js
  packages/record/src/redwoodrecord/Core.js
  packages/record/src/redwoodrecord/RedwoodRecord.js
  packages/record/src/redwoodrecord/Reflection.js
  packages/record/src/redwoodrecord/RelationProxy.js
  packages/record/src/redwoodrecord/ValidationMixin.js
  packages/record/src/redwoodrecord/__tests__/Core.test.js
  packages/record/src/redwoodrecord/__tests__/RedwoodRecord.test.js
  packages/record/src/redwoodrecord/__tests__/Reflection.test.js
  packages/record/src/redwoodrecord/__tests__/RelationProxy.test.js
  packages/record/src/redwoodrecord/__tests__/Validation.test.js
  packages/record/src/redwoodrecord/__tests__/data.json
  packages/record/src/redwoodrecord/__tests__/datamodel.json
  packages/record/src/tasks/parse.js
  yarn.lock
Labels: next-release/update-docs, hopper, topic/record

#3788 lazy import record package in cli
  packages/cli/src/commands/generate/model/model.js
Labels: triage/processing

#3790 Allow configuration of preset-react on the web side
  packages/internal/src/build/babel/web.ts
Labels: triage/processing

#3798 [Renovate] Enable lock file updates, order config
  .github/renovate.json
Labels: triage/processing
