Repository redwoodjs/graphql, pull requests merged in 2021-12, with the labels that each got.

#3815 Windows babel fixes for v0.39.x
  packages/internal/src/build/babel/web.ts
  packages/prerender/src/runPrerender.tsx
Labels: bug/confirmed

#3824 update all contributors v0.39
  README.md
  tasks/all-contributors/.all-contributorsrc
  tasks/all-contributors/.learn.all-contributorsrc
  tasks/all-contributors/.rwjs.com.all-contributorsrc
  tasks/all-contributors/README.md
Labels: triage/processing

#3828 Fix/prerender explicit page imports
  packages/internal/src/__tests__/build_web.test.ts
  packages/internal/src/build/babel/web.ts
  packages/internal/src/build/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts
  packages/internal/src/build/web.ts
  packages/internal/src/files.ts
  packages/testing/config/jest/web/index.js
  tasks/e2e/cypress/integration/01-tutorial/codemods/Step6_1_Routes.js
Labels: triage/processing

#3830 fix(babel): Fix jest.mock module resolution
  __fixtures__/example-todo-main/api/src/services/todos/todos.test.js
  packages/internal/src/__tests__/build_api.test.ts
  packages/internal/src/build/api.ts
  packages/internal/src/build/babel/api.ts
  packages/testing/config/jest/api/index.js
Labels: triage/processing

#3831 Move lerna up to the root
  babel.config.js
  lerna.json
  package.json
  tasks/framework-tools/package.json
  tasks/framework-tools/src/lib/framework.mjs
  tasks/framework-tools/yarn.lock
  yarn.lock
Labels: triage/processing

#3833 Tweak renovate settings
  .github/renovate.json
Labels: triage/processing

#3860 Fix rwfw project:sync
  tasks/framework-tools/src/lib/framework.mjs
Labels: triage/processing

#3868 Fix rwfw project:sync loop
  tasks/framework-tools/src/lib/framework.mjs
Labels: triage/processing

#3878 add chalk to renovate blocklist
  .github/renovate.json
Labels: triage/processing

#3885 Uses current RW version for setup commands auth and deploy
  packages/cli/src/commands/setup.js
  packages/cli/src/commands/setup/auth/auth.js
  packages/cli/src/commands/setup/deploy/deploy.js
  packages/cli/src/middleware/detectProjectRwVersion.js
Labels: triage/processing

#3886 install latest tailwindcss during setup ui
  packages/cli/src/commands/setup/ui/tailwindcss.js
Labels: triage/processing

#3881 Make onClick prop of NavLink optional.
  packages/router/src/links.tsx
Labels: topic/typescript, v1/priority

#3874 Update seed.ts in template
  packages/create-redwood-app/template/scripts/seed.ts
Labels: topic/typescript

#3890 Simplify template MetaTags description
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/page/templates/page.tsx.template
Labels: topic/generators-&-scaffolds, triage/processing

#3896 Add scripts/{j,t}sconfig.json to CRWA template
  packages/create-redwood-app/template/scripts/tsconfig.json
  packages/internal/src/ts2js.ts
Labels: topic/create-redwood-app, v1/priority

#3877 Simplify log message format for web in api-server
  packages/api-server/package.json
  packages/api-server/src/app.ts
  yarn.lock
Labels: v1/priority

#3899 Remove the test project's package.json in favor of the root workspace
  package.json
  tasks/test-project/package.json
  tasks/test-project/yarn.lock
  yarn.lock
Labels: topic/ops-&-contributing-dx, v1/priority

#3904 `rw exec` fixes/updates
  packages/cli/src/commands/exec.js
  packages/cli/src/commands/generate/script/__tests__/__snapshots__/script.test.ts.snap
  packages/cli/src/commands/generate/script/templates/script.js.template
  packages/cli/src/commands/generate/script/templates/tsconfig.json.template
  packages/create-redwood-app/template/scripts/tsconfig.json
  packages/internal/src/build/babel/api.ts
Labels: next-release/update-docs

#3911 exit(1) in dataMigrate on caught errors
  packages/cli/src/commands/dataMigrate/up.js
Labels: triage/processing

#3915 [Renovate] Run dedupe after install
  .github/renovate.json
Labels: topic/ops-&-contributing-dx, v1/priority

#3908 Move framework-tools deps to root package.json
  package.json
  packages/cli/src/rwfw.js
  tasks/framework-tools/frameworkDepsToProject.mjs
  tasks/framework-tools/frameworkFilesToProject.mjs
  tasks/framework-tools/frameworkSyncToProject.mjs
  tasks/framework-tools/lib/framework.mjs
  tasks/framework-tools/lib/project.mjs
  tasks/framework-tools/package.json
  tasks/framework-tools/yarn.lock
  tasks/run-e2e
  tasks/test-project/frameworkLinking.js
  tasks/test-project/util.js
  yarn.lock
Labels: topic/ops-&-contributing-dx, v1/priority

#3907 [e2e] Move dependencies to the root workspace
  .github/workflows/e2e.yaml
  package.json
  tasks/e2e/package.json
  tasks/e2e/yarn.lock
  tasks/run-e2e
  yarn.lock
Labels: topic/ops-&-contributing-dx, v1/priority

#3895 Update documentation on contributing
  CONTRIBUTING.md
Labels: triage/processing

#3939 fix(cors): Handle empty base64 requests
  packages/graphql-server/src/functions/__tests__/normalizeRequest.test.ts
  packages/graphql-server/src/functions/__tests__/useRequireAuth.test.ts
  packages/graphql-server/src/functions/graphql.ts
Labels: triage/processing

#3892 Add documentation to validation options
  packages/api/src/validations/validations.ts
Labels: topic/api, v1/priority

#3940 fix(types): Add aws-lambda to rwjs/testing so its available as dev ti…
  packages/testing/package.json
  yarn.lock
Labels: triage/processing

#3946 Still allow generic Errors in redwood forms
  packages/forms/src/FormError.tsx
Labels: topic/forms, topic/typescript, v1/priority

#3953 fix(webpack): Disable sourcemaps in prod
  packages/core/config/webpack.common.js
  packages/internal/src/__tests__/config.test.ts
  packages/internal/src/config.ts
Labels: topic/config, next-release/update-docs, v1/priority

#3891 Fix #3873 - Inline fragment crash
  packages/internal/src/__tests__/gql.test.ts
  packages/internal/src/gql.ts
Labels: bug/confirmed, topic/graphql, v1/priority

#3772 Fix: Router white flash on first navigation to page
  packages/router/src/ActivePageContext.tsx
  packages/router/src/PageLoadingContext.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/active-route-loader.tsx
  packages/router/src/links.tsx
  packages/router/src/location.tsx
  packages/router/src/page-loader.tsx
  packages/router/src/params.tsx
  packages/router/src/router-context.tsx
  packages/router/src/router.tsx
  packages/router/src/useIsMounted.ts
  packages/router/src/util.ts
  packages/testing/src/web/__tests__/MockRouter.test.tsx
Labels: topic/router, next-release/update-docs, v1/priority

#3782 Replace netlify's zip-it-and-ship-it for serverless deploy
  packages/cli/src/commands/deploy/aws-providers/serverless.js
  packages/cli/src/commands/deploy/aws.js
  packages/cli/src/commands/deploy/packing/nft.js
  packages/cli/src/commands/setup/deploy/providers/aws-serverless.js
Labels: topic/deployment, v1/priority

#3947 Implement Redwood LogFormatter
  packages/api-server/package.json
  packages/api-server/src/app.ts
  packages/api-server/src/logFormatter/README.md
  packages/api-server/src/logFormatter/ambient.d.ts
  packages/api-server/src/logFormatter/bin.ts
  packages/api-server/src/logFormatter/index.ts
  packages/api-server/src/logFormatter/logFormatter.test.ts
  packages/api-server/src/requestHandlers/awsLambdaFastify.ts
  packages/api/package.json
  packages/api/src/logger/index.ts
  packages/api/src/logger/logger.test.ts
  packages/cli/src/commands/dev.js
  packages/create-redwood-app/template/api/src/lib/logger.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodLogger.test.ts
  tasks/e2e/cypress/integration/04-logger/codemods/Step1_1_Setup_Logger.js
  yarn.lock
Labels: topic/config, v1/priority

#3884 Properly merge typeDefs in makeMergedSchema
  packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts
Labels: bug/repro-available, topic/api, topic/graphql, v1/priority

#3969 (chore) merge #3884 into main
  packages/api-server/src/app.ts
  packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts
Labels: triage/processing

#3973 Update All Contributors v0.41.0; add agiannelli to Core Team
  README.md
  tasks/all-contributors/.all-contributorsrc
  tasks/all-contributors/.learn.all-contributorsrc
  tasks/all-contributors/.rwjs.com.all-contributorsrc
  tasks/all-contributors/README.md
Labels: triage/processing

#3984 Add GitHub Action requiring PRs to include one of the "release:*" labels
  .github/renovate.json
  .github/workflows/require-PR-label.yaml
Labels: release:chore
