Repository redwoodjs/graphql, pull requests merged in 2021-03, with the labels that each got.

#1851 Upgrade to Prisma v2.18.0 (skipping v2.17.0)
  packages/api/package.json
  packages/cli/package.json
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/service/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/test.js
  packages/core/package.json
  packages/structure/package.json
  yarn.lock
Labels: breaking change, next release docs

#1705 Upgrade React to v17.
  package.json
  packages/api/src/auth/index.ts
  packages/auth/package.json
  packages/auth/src/authClients/nhost.ts
  packages/core/package.json
  packages/create-redwood-app/template/web/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/structure/src/x/child_process.ts
  packages/testing/package.json
  packages/web/package.json
  tasks/e2e/cypress.json
  yarn.lock
Labels: breaking change, next release docs

#1906 Fixes marshalling datetimes in and out of forms
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/form.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/components/NameForm.js.template
  packages/forms/src/__tests__/form.test.tsx
  packages/forms/src/coercion.tsx
Labels: next release

#1903 Fixes 1902 to rwt link when path has spaces/parens
  packages/cli/src/redwood-tools.js
Labels: topic: cli

#1789 Add per request global context
  package.json
  packages/api/src/functions/graphql.test.ts
  packages/api/src/functions/graphql.ts
  packages/api/src/globalContext.ts
Labels: next release docs

#1828 Make storybook configurable in a redwood app
  packages/core/config/storybook/main.js
  packages/core/config/storybook/preview.js
  packages/internal/src/paths.ts
Labels: kind/improvement, topic: config, topic: storybook

#1853 Update service generator to use Prisma namespace
  packages/cli/src/commands/generate/service/__tests__/fixtures/multiWord_crud.ts
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_belongsTo.ts
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_crud.ts
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_hasMany.ts
  packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_multiple.ts
  packages/cli/src/commands/generate/service/templates/service.ts.template
Labels: topic: prisma, topic: testing

#1939 Fix/rwt link on canary
  packages/cli/src/redwood-tools.js
Labels: topic: contributor-dx

#1891 Allow prerendering NotFoundPage as 404.html
  packages/prerender/src/__tests__/detectRoutes.test.ts
  packages/prerender/src/router.ts
  packages/prerender/src/runPrerender.tsx
Labels: topic: prerender

#1856 Replaces Flash with react-hot-toast
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/assets/scaffold.css
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/editCell.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/edit.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/new.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/index.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/new.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/show.js
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/layouts/layout.js
  packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template
  packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/Name.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template
  packages/cli/src/commands/generate/scaffold/templates/layouts/NamesLayout.js.template
  packages/web/package.json
  packages/web/src/apollo/index.tsx
  packages/web/src/flash/Flash.tsx
  packages/web/src/flash/FlashContext.tsx
  packages/web/src/flash/FlashReducer.ts
  packages/web/src/flash/README.md
  packages/web/src/flash/__tests__/FlashContext.test.js
  packages/web/src/flash/__tests__/flash.test.js
  packages/web/src/flash/index.ts
  packages/web/src/index.ts
  packages/web/src/toast/index.ts
  packages/web/toast/index.js
  packages/web/toast/package.json
  tasks/e2e/cypress/integration/01-tutorial/tutorial.spec.js
  yarn.lock
Labels: topic: forms

#1847 i18n Setup : Simpler configuration + examples
  packages/cli/src/commands/setup/i18n/i18n.js
  packages/cli/src/commands/setup/i18n/templates/en.json.template
  packages/cli/src/commands/setup/i18n/templates/fr.json.template
  packages/cli/src/commands/setup/i18n/templates/i18n.js.template
Labels: next release test

#1946 Bump CRWA Node.js Engine requirement from 12 to 14
  .github/workflows/build-eslint-jest.yaml
  .github/workflows/create_pr_artifact.yaml
  .github/workflows/e2e.yaml
  .github/workflows/publish-npm-canary.yaml
  .gitignore
  packages/create-redwood-app/template/.nvmrc
  packages/create-redwood-app/template/package.json
Labels: breaking change, next release

#1962 Run a diagnostic check when prerender fails
  packages/cli/src/commands/prerender.js
Labels: topic: cli, topic: prerender

#2000 globalContext.tsx: Fix lint warning
  packages/api/src/globalContext.ts
Labels: next release

#2004 Update error message in tasks/publish-local to point to tasks/run-loc…
  tasks/publish-local
Labels: next release

#1967 withCellHOC: Fix TS error
  packages/web/src/components/withCellHOC.tsx
Labels: next release

#2010 Azure Active Directory Auth: Adding try-catch block on callback to capture empty key
  packages/api/src/auth/decoders/azureActiveDirectory.ts
Labels: next release, topic: auth

#1964 Add makeExecSchema options
  packages/api/package.json
  packages/api/src/makeMergedSchema/makeMergedSchema.test.ts
  packages/api/src/makeMergedSchema/makeMergedSchema.ts
  yarn.lock
Labels: next release

#1992 AuthProvider: return `signup()` output from auth client
  packages/auth/src/AuthProvider.tsx
Labels: topic: auth

#2007 Improve auth cli filesystem calls
  packages/cli/src/commands/setup/auth/auth.js
Labels: next release

#2002 Fix grabbing a user's storybook config
  packages/core/config/storybook/main.js
Labels: bug/2-confirmed, next release, topic: storybook

#1990 Fix issue with verify email redirect using Auth0
  packages/auth/src/authClients/auth0.ts
Labels: next release

#1958 Refactor: Converted Prisma.ts to js
  packages/cli/src/commands/prisma.js
Labels: next release

#2017 Fix lint breaking when deleting a side
  packages/cli/src/commands/lint.js
Labels: next release

#1948 Add experimental ESBuild for api side
  __fixtures__/example-todo-main/api/src/functions/graphql.js
  __fixtures__/example-todo-main/api/src/lib/db.js
  packages/api-server/ambient.d.ts
  packages/api-server/package.json
  packages/api-server/src/http.ts
  packages/api-server/src/index.ts
  packages/api-server/src/requestHandlers/awsLambda.ts
  packages/api-server/src/watch.ts
  packages/cli/src/commands/build.js
  packages/cli/src/commands/dev.js
  packages/cli/src/redwood-tools.js
  packages/core/esbuild/apiBuild.d.ts
  packages/core/esbuild/apiBuild.js
  packages/core/esbuild/apiGlobals.js
  packages/core/esbuild/index.js
  packages/core/package.json
  packages/internal/src/paths.ts
  yarn.lock
Labels: next release

#1937 Implement Redwood API side Logger
  packages/api/README.md
  packages/api/ambient.d.ts
  packages/api/logger/index.js
  packages/api/logger/package.json
  packages/api/package.json
  packages/api/src/logger/README.md
  packages/api/src/logger/index.ts
  packages/api/src/logger/logger.test.ts
  packages/api/tsconfig.json
  packages/auth/src/authClients/supabase.ts
  packages/create-redwood-app/template/.env.defaults
  packages/create-redwood-app/template/.env.example
  packages/create-redwood-app/template/api/src/lib/db.ts
  packages/create-redwood-app/template/api/src/lib/logger.ts
  packages/create-redwood-app/template/api/src/lib/prisma.ts
  packages/router/src/page-loader.tsx
  yarn.lock
Labels: topic: api, topic: prisma, topic:logging

#1908 Pass event and context into getCurrentUser
  packages/api/src/functions/graphql.ts
  packages/cli/src/commands/setup/auth/templates/auth.js.template
Labels: topic: auth

#1898 Router: <Set wrap={}>
  packages/router/README.md
  packages/router/src/Set.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/history.tsx
  packages/router/src/index.ts
  packages/router/src/internal.ts
  packages/router/src/location.tsx
  packages/router/src/named-routes.tsx
  packages/router/src/private-context.tsx
  packages/router/src/router-context.tsx
  packages/router/src/router.tsx
  packages/router/src/util.ts
Labels: next release, topic: router

#1817 Steps towards a11y for Redwood Router
  packages/cli/src/commands/generate/layout/__tests__/fixtures/withSkipLinkLayout.tsx
  packages/cli/src/commands/generate/layout/__tests__/layout.test.ts
  packages/cli/src/commands/generate/layout/layout.js
  packages/cli/src/commands/generate/layout/templates/layout.tsx.a11yTemplate
  packages/router/package.json
  packages/router/src/__tests__/route-announcer.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/index.ts
  packages/router/src/page-loader.tsx
  packages/router/src/route-announcement.tsx
  packages/router/src/util.ts
  yarn.lock
Labels: topic: accessibility, topic: router

#2043 Make useParams usable in layouts in `<Set>`
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/page-loader.tsx
  packages/router/src/params.ts
  packages/router/src/params.tsx
  packages/router/src/router.tsx
Labels: next release, topic: router

#2046 Make per-request-context rely on lazy initialization
  packages/api/src/functions/graphql.test.ts
  packages/api/src/functions/graphql.ts
  packages/api/src/globalContext.ts
  packages/core/src/configs/node/jest.setup.js
Labels: next release

#2047 Fixes case when File Logging didn't get set with the correct logger options
  packages/api/src/logger/README.md
  packages/api/src/logger/index.ts
  packages/api/src/logger/logger.test.ts
Labels: topic:logging

#2049 Use esbuild-loader for web side.
  packages/api-server/src/watch.ts
  packages/cli/src/commands/dev.js
  packages/core/config/webpack.common.js
  packages/core/esbuild/apiBuild.js
  packages/core/package.json
  tasks/e2e/cypress/integration/01-tutorial/tutorial.spec.js
Labels: next release

#2054 Bump Storybook to 6.1
  packages/core/config/storybook/main.js
  packages/core/config/storybook/preview.example.js
  packages/core/config/storybook/preview.js
  packages/core/package.json
  packages/internal/src/paths.ts
  yarn.lock
Labels: next release

#2055 Fix Logger Readme destination param in transport examples
  packages/api/src/logger/README.md
Labels: topic: docs, topic:logging

#2056 fix(html-mismatch): Fixes warning in browser console
  packages/core/config/webpack.common.js
  packages/web/src/entry/index.js
Labels: next release

#2044 fix: mock window.scrollTo to stop jest's consoling
  packages/eslint-config/shared.js
  packages/router/jest.config.js
  packages/router/jest.setup.js
Labels: next release, topic: router, topic: testing

#1849 Add a11y configuration for eslint and storybook
  package.json
  packages/core/config/storybook/main.js
  packages/core/package.json
  packages/eslint-config/index.js
  packages/internal/src/__tests__/config.test.ts
  packages/internal/src/config.ts
  yarn.lock
Labels: next release, topic: accessibility, topic: config, topic: storybook

#2087 Remove a11y addon (for now)
  packages/core/config/storybook/main.js
Labels: topic: accessibility, topic: config, topic: storybook

#2089 Fix invalid html in route announcer test
  packages/router/src/__tests__/route-announcer.test.tsx
Labels: bug/2-confirmed, topic: router

#2094 Replaces logger docs with link to www site docs
  packages/api/src/logger/README.md
Labels: topic: docs, topic:logging

#2097 Add the new Set component to the Router docs
  packages/router/README.md
Labels: topic: docs, topic: router

#2085 feat(fast-refresh): Enables fast refresh by default in dev mode
  packages/core/config/webpack.common.js
  packages/internal/src/__tests__/config.test.ts
  packages/internal/src/config.ts
Labels: topic: config, topic: web

#2154 Fix: named routes types
  packages/cli/src/commands/setup/tsconfig/tsconfig.js
  packages/cli/src/lib/index.js
  packages/core/src/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts
  packages/create-redwood-app/template/web/tsconfig.json
  packages/router/src/index.ts
  packages/router/src/router.tsx
Labels: topic: config
