Repository redwoodjs/graphql, pull requests merged in 2021-02, with the labels that each got.

#1703 Azure Active Directory: Updating default auth request for acquireTokenSilent
  packages/auth/src/authClients/azureActiveDirectory.ts
Labels: topic: auth

#1666 Router: TypeScript rewrite
  packages/core/config/webpack.common.js
  packages/core/src/configs/browser/jest.createConfig.ts
  packages/router/package.json
  packages/router/src/__tests__/links.test.tsx
  packages/router/src/__tests__/location.test.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/util.test.ts
  packages/router/src/history.tsx
  packages/router/src/index.d.ts
  packages/router/src/index.ts
  packages/router/src/internal.ts
  packages/router/src/links.js
  packages/router/src/links.tsx
  packages/router/src/location.tsx
  packages/router/src/named-routes.tsx
  packages/router/src/page-loader.tsx
  packages/router/src/params.ts
  packages/router/src/router.tsx
  packages/router/src/splash-page.js
  packages/router/src/splash-page.tsx
  packages/router/src/util.ts
  packages/router/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: topic: router

#1668 Revise the CRWA package README
  packages/create-redwood-app/README.md
Labels: next release, next release docs

#1718 Corrects dataMigrate install instructions
  packages/cli/src/commands/dataMigrate/install.js
Labels: topic: cli, topic: generators

#1724 Format generated *.d.ts files
  packages/core/src/babelPlugins/babel-plugin-redwood-import-dir.ts
  packages/core/src/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts
Labels: topic: router

#1729 Fix env loading in users webpack config
  packages/cli/src/commands/setup/webpack/templates/webpack.config.js.template
Labels: bug/2-confirmed, topic: generators

#1723 Router: Automatically import .ts Page files
  packages/internal/src/paths.ts
Labels: next release, topic: router

#1739 Adds Facebook to list of supported Supabase OAuth providers
  packages/auth/package.json
  packages/auth/src/authClients/supabase.ts
  yarn.lock
Labels: topic: auth

#1720 [breaking] upgrade Prisma v2.16.0 and replace `rw db` commands with `rw prisma`
  packages/api/package.json
  packages/cli/package.json
  packages/cli/src/commands/build.js
  packages/cli/src/commands/db.js
  packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js
  packages/cli/src/commands/dbCommands/down.js
  packages/cli/src/commands/dbCommands/introspect.js
  packages/cli/src/commands/dbCommands/options.ts
  packages/cli/src/commands/dbCommands/save.js
  packages/cli/src/commands/dbCommands/seed.js
  packages/cli/src/commands/dbCommands/studio.js
  packages/cli/src/commands/dbCommands/up.js
  packages/cli/src/commands/dev.js
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/prisma.js
  packages/cli/src/commands/prisma/generate.js
  packages/cli/src/lib/colors.js
  packages/core/package.json
  packages/create-redwood-app/template/api/db/seed.js
  packages/internal/src/paths.ts
  packages/structure/package.json
  tasks/e2e/cypress/integration/tutorial/tutorial.js
  yarn.lock
Labels: breaking change, next release docs, next release test

#1681 MockProvider: Wrap children in LocationProvider
  packages/router/src/index.ts
  packages/testing/src/MockProviders.tsx
  packages/testing/tsconfig.json
Labels: next release, topic: testing

#1755 Specify node_env before running build web
  packages/cli/src/commands/__tests__/build.test.js
  packages/cli/src/commands/build.js
Labels: kind/improvement

#1747 restructure and update Deploy command and change Setup Deploy command template [breaking]
  packages/cli/src/commands/deploy.js
  packages/cli/src/commands/deploy/__tests__/api.test.js
  packages/cli/src/commands/deploy/aws-providers/serverless.js
  packages/cli/src/commands/deploy/aws.js
  packages/cli/src/commands/deploy/helpers/helpers.js
  packages/cli/src/commands/deploy/netlify.js
  packages/cli/src/commands/deploy/vercel.js
  packages/cli/src/commands/setup/deploy/providers/aws-serverless.js
  packages/cli/src/commands/setup/deploy/providers/netlify.js
Labels: breaking change, next release docs, next release test

#1758 [v0.25] Scaffolded many-to-many relationship fixes
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/generate/service/__tests__/scenario.test.js
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/lib/index.js
Labels: next release docs

#1757 [v0.25] Remove warning if you scaffold a model with a relation
  packages/cli/src/commands/generate/scaffold/scaffold.js
Labels: next release docs

#1155 Rebuild Prisma Client between upgrades
  packages/cli/src/commands/upgrade.js
Labels: topic: cli

#1790 Hotfix: Use inherit to allow interactivity in yarn rw prisma
  packages/cli/src/commands/prisma.ts
Labels: next release, topic: cli, topic: prisma

#1787 dataMigrate install uses prisma migrate command
  packages/cli/src/commands/dataMigrate/install.js
  packages/cli/src/commands/dataMigrate/up.js
Labels: bug/2-confirmed, topic: cli, topic: prisma

#996 Docs: link to roadmap in readme
  README.md
Labels: topic: docs

#1721 Feature/prerender image support
  packages/core/config/babel-preset.js
  packages/core/config/webpack.common.js
  packages/core/package.json
  packages/prerender/jest.config.js
  packages/prerender/package.json
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/distDir/manifest.json
  packages/prerender/src/babelPlugins/__tests__/babel-plugin-redwood-prerender-media-imports.test.ts
  packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts
  packages/prerender/src/runPrerender.tsx
  yarn.lock
Labels: next release

#1821 Better messages when no routes marked with prerender
  packages/cli/src/commands/__tests__/build.test.js
  packages/cli/src/commands/build.js
  packages/cli/src/commands/prerender.js
Labels: next release, topic: cli, topic: prerender

#1744 Generate globals for routes
  packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
  packages/core/src/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts
  packages/core/src/babelPlugins/generateGlobals.ts
  packages/internal/src/__tests__/paths.test.ts
  packages/internal/src/paths.ts
Labels: next release, topic: router

#1823 Router: Fix TS types
  packages/router/src/router.tsx
Labels: next release, topic: router, typescript

#1704 Router: <Route redirect="">
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/router.tsx
Labels: next release, topic: router

#1725 Nhost Auth 1.0
  packages/api/src/auth/decoders/index.ts
  packages/auth/README.md
  packages/auth/package.json
  packages/auth/src/authClients/index.ts
  packages/auth/src/authClients/nhost.ts
  packages/cli/src/commands/setup/auth/providers/nhost.js
  yarn.lock
Labels: topic: auth

#1791 Passthrough error codes on cli failures
  packages/cli/src/commands/dataMigrate/install.js
  packages/cli/src/commands/dataMigrate/up.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/setup/auth/__tests__/auth.test.js
  packages/cli/src/commands/setup/auth/auth.js
  packages/cli/src/commands/setup/deploy/deploy.js
  packages/cli/src/commands/setup/i18n/i18n.js
  packages/cli/src/commands/setup/tailwind/tailwind.js
  packages/cli/src/commands/setup/webpack/webpack.js
  packages/cli/src/commands/test.js
  packages/cli/src/commands/upgrade.js
Labels: next release, next release test

#1795 Don't open storybook when --open=false is given
  packages/cli/src/commands/storybook.js
Labels: next release

#1824 [TS] Add types to flash, clean up some logic
  packages/web/src/flash/Flash.tsx
  packages/web/src/flash/FlashContext.js
  packages/web/src/flash/FlashContext.tsx
  packages/web/src/flash/FlashReducer.js
  packages/web/src/flash/FlashReducer.ts
  packages/web/src/flash/index.ts
  packages/web/tsconfig.json
Labels: kind/improvement, next release, typescript

#1792 New contributor workflow
  .gitignore
  packages/api-server/package.json
  packages/cli/package.json
  packages/cli/src/redwood-tools.js
  packages/dev-server/package.json
  packages/eslint-plugin-redwood/package.json
  yarn.lock
Labels: next release, topic: contributor-dx

#1803 Docs: Update contributor workflow to yarn rwt link
  CONTRIBUTING.md
Labels: next release, topic: contributor-dx, topic: docs

#1776 Use createMany in Seed database example
  packages/create-redwood-app/template/api/db/seed.js
Labels: topic: prisma

#1844 Remove bundlesize dependency
  package.json
  packages/auth/package.json
  yarn.lock
Labels: next release

#1848 Fixes generating scenarios for relations where the field name is different than the relation name
  packages/cli/src/commands/generate/service/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/service/__tests__/scenario.test.js
  packages/cli/src/commands/generate/service/__tests__/service.test.js
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/generate/service/templates/test.ts.template
  packages/cli/src/lib/index.js
Labels: next release

#1842 Hide entry.js | Add setup command to restore
  .eslintrc.js
  packages/cli/src/commands/setup/custom-entry/custom-entry.js
  packages/cli/src/commands/setup/custom-entry/templates/entry.js.template
  packages/core/config/webpack.common.js
  packages/web/src/entry/index.js
Labels: breaking change, next release, topic: prerender, topic: project-structure
