Repository redwoodjs/graphql, pull requests merged in 2021-06, with the labels that each got.

#2564 add esbuild config to CLI build and dev
  packages/cli/src/commands/build.js
  packages/cli/src/commands/dev.js
  packages/create-redwood-app/template/redwood.toml
  packages/internal/src/__tests__/config.test.ts
  packages/internal/src/config.ts
Labels: next-release/breaking, topic/config, v1/priority

#2630 fix(rw test): Ability to filter tests by filename
  packages/cli/src/commands/__tests__/test.test.js
  packages/cli/src/commands/test.js
  packages/cli/src/lib/test.js
Labels: next-release/update-docs, topic/cli

#2643 TypeScript support for scenarios and service testing
  packages/cli/src/commands/generate/__tests__/createYargsForComponentGeneration.test.js
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
  packages/cli/src/commands/generate/service/__tests__/service.test.js
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/generate/service/templates/scenarios.ts.template
  packages/cli/src/commands/generate/service/templates/test.ts.template
  packages/internal/src/__tests__/typeDefinitions.test.ts
  packages/internal/src/generate/helpers.js
  packages/internal/src/generate/templates/api-scenarios.d.ts.template
  packages/internal/src/generate/typeDefinitions.ts
  packages/testing/src/index.ts
  packages/testing/src/scenario.ts
Labels: topic/api, topic/testing, topic/typescript, v1/priority

#2677 schemaPath must be the same as default toml
  packages/internal/src/__tests__/config.test.ts
  packages/internal/src/config.ts
Labels: next-release/breaking, topic/api, topic/config, topic/prisma

#2667 Add command to create functional project to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: topic/docs

#2635 Add action for updating PR milestone
  .github/workflows/proj.yml
  tasks/actions/README.md
  tasks/actions/change-milestone/action.yml
  tasks/actions/change-milestone/index.js
  tasks/actions/package.json
  tasks/actions/yarn.lock
Labels: topic/ops-&-contributing-dx

#2642 rw test (cli): add `db-push` flag
  packages/cli/src/commands/__tests__/test.test.js
  packages/cli/src/commands/test.js
Labels: topic/testing, v1/priority

#2737 Fix: running rw test web in linked project
  packages/cli/src/redwood-tools.js
Labels: topic/ops-&-contributing-dx

#2712 Support RedwoodJS framework detection with Netlify CLI
  packages/cli/src/commands/setup/deploy/providers/netlify.js
Labels: topic/deployment

#2150 Remove unused QUERY variable generated through scaffolding
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template
Labels: bug/confirmed, topic/generators-&-scaffolds, v1/priority

#2786 Adds some minor polish to the TS to JS command
  packages/internal/src/ts2js.ts
Labels: topic/typescript

#2785 Use consistent GQL operation name case in cell scaffolds generators
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/NameCell.js.template
Labels: topic/cells, topic/generators-&-scaffolds

#2796 fix(rw-deploy): Deploy cmd fails correctly if one of the steps fail
  packages/cli/src/commands/deploy/helpers/helpers.js
Labels: topic/deployment

#2770 Run "yarn rw-gen" during create redwood app
  packages/create-redwood-app/src/create-redwood-app.js
Labels: bug/confirmed, topic/create-redwood-app, v1/priority

#2641 Add Updating to Cells
  packages/web/src/components/createCell.tsx
Labels: next-release/breaking, topic/cells, v1/priority

#2753 Deprecate eslint-plugin-redwood
  .eslintrc.js
  CONTRIBUTING.md
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/eslint-plugin-redwood/.babelrc.js
  packages/eslint-plugin-redwood/README.md
  packages/eslint-plugin-redwood/package.json
  packages/eslint-plugin-redwood/src/index.js
  packages/eslint-plugin-redwood/src/no-unavailable-pages.js
Labels: topic/config, v1/priority

#2798 Adds cypress tests api-side logging as part of e2e
  tasks/e2e/cypress/integration/04-logger/codemods/Step0_1_Setup_Logger.js
  tasks/e2e/cypress/integration/04-logger/codemods/Step0_2_Add_Logger_to_Posts.js
  tasks/e2e/cypress/integration/04-logger/codemods/Step1_1_Routes.js
  tasks/e2e/cypress/integration/04-logger/codemods/Step2_1_DbSchema.js
  tasks/e2e/cypress/integration/04-logger/logger.spec.js
Labels: topic/logging, topic/testing

#2769 Re-organize packages: Build, design and runtime.
  .eslintignore
  .eslintrc.js
  babel.config.js
  package.json
  packages/cli/README.md
  packages/cli/package.json
  packages/cli/src/commands/info.js
  packages/cli/src/commands/prisma.js
  packages/cli/src/commands/storybook.js
  packages/cli/src/commands/test.js
  packages/cli/src/redwood-tools.js
  packages/core/esbuild/index.js
  packages/core/package.json
  packages/core/src/configs/browser/jest.createConfig.ts
  packages/core/src/configs/node/jest.createConfig.ts
  packages/core/src/getConfig.ts
  packages/core/tsconfig.json
  packages/create-redwood-app/template/api/jest.config.js
  packages/create-redwood-app/template/package.json
  packages/create-redwood-app/template/web/jest.config.js
  packages/eslint-config/package.json
  packages/internal/package.json
  packages/internal/src/__tests__/files.test.ts
  packages/internal/src/__tests__/typeDefinitions.test.ts
  packages/internal/src/paths.ts
  packages/testing/config/jest/api/index.js
  packages/testing/config/jest/api/jest.setup.js
  packages/testing/config/jest/jest.config.js
  packages/testing/config/jest/web/index.js
  packages/testing/config/jest/web/jest.setup.js
  packages/testing/config/storybook/.babelrc
  packages/testing/config/storybook/main.js
  packages/testing/config/storybook/preview.example.js
  packages/testing/config/storybook/preview.js
  packages/testing/package.json
  packages/testing/src/StorybookProvider.tsx
  packages/web/package.json
  tasks/build-and-copy
  tasks/framework-tools/lerna.json
  tasks/framework-tools/package.json
  tasks/framework-tools/yarn.lock
  tasks/run-e2e
  yarn.lock
Labels: next-release/breaking, v1/priority

#2812 Add rw typeCheck command
  packages/cli/src/commands/__tests__/test.test.js
  packages/cli/src/commands/__tests__/type-check.test.js
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/typeCheck.js
  packages/web/src/components/createCell.tsx
Labels: topic/typescript

#2823 Fix test generation with crud action and foreign key as required field
  packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
  packages/cli/src/commands/generate/service/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/service/__tests__/service.test.js
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/generate/service/templates/test.ts.template
Labels: topic/generators-&-scaffolds

#2860 Create test values for Decimal and Boolean types
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/generate/service/__tests__/scenario.test.js
  packages/cli/src/commands/generate/service/service.js
Labels: topic/generators-&-scaffolds

#2850 Fix scaffold generator: handle model name when plural form is unknown (aka the "Pokemon" bug)
  packages/cli/src/commands/destroy/helpers.js
  packages/cli/src/commands/destroy/scaffold/scaffold.js
  packages/cli/src/commands/destroy/sdl/sdl.js
  packages/cli/src/commands/destroy/service/service.js
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/generate/service/service.js
Labels: v1/priority

#1952 Create SECURITY.md
  SECURITY.md
Labels: topic/security, v1/priority

#2873 Upgrades Envelop to 0.3.1
  packages/graphql-server/package.json
  packages/graphql-server/src/functions/graphql.ts
  yarn.lock
Labels: topic/graphql

#2891 fix(graphql-server): context exports from graphql-server
  packages/graphql-server/src/index.ts
  packages/graphql-server/tsconfig.json
Labels: topic/graphql

#2829 Don't generate scaffold for invalid models
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
Labels: topic/generators-&-scaffolds

#2855 Adds Failure Component to Scaffolded Cells
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/NameCell.js.template
  packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.js.template
  tasks/e2e/cypress/integration/01-tutorial/codemods/Step8_1_RequireAuth.js
  tasks/e2e/cypress/integration/01-tutorial/codemods/Step8_2_PostsRequireAuth.js
  tasks/e2e/cypress/integration/01-tutorial/codemods/Step8_3_DisableAuth.js
  tasks/e2e/cypress/integration/01-tutorial/tutorial.spec.js
  tasks/run-e2e
Labels: topic/generators-&-scaffolds

#2826 Router: Remove RouteScanner, don't store all routes in context
  packages/router/src/Set.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/params.tsx
  packages/router/src/router-context.tsx
  packages/router/src/router.tsx
Labels: v1/priority
