Repository redwoodjs/graphql, pull requests merged in 2022-11, with the labels that each got.

#6772 [CI]: Add Prisma resolutions to tutorial-e2e test project
  tasks/run-e2e
Labels: release:chore

#6775 [CI]: Fix and rebuild test project fixture
  __fixtures__/test-project/web/package.json
  tasks/test-project/tasks.js
Labels: release:chore

#6757 Fix WebAuthn when event body is base64 encoded (like when deploying to Vercel)
  packages/auth-providers-api/src/dbAuth/DbAuthHandler.ts
  packages/auth-providers-api/src/dbAuth/__tests__/DbAuthHandler.test.js
Labels: topic/auth, release:fix

#6778 Strip resetToken and resetTokenExpiresAt from dbAuth forgotPassword handler
  packages/auth-providers-api/src/dbAuth/DbAuthHandler.ts
  packages/auth-providers-api/src/dbAuth/__tests__/DbAuthHandler.test.js
Labels: topic/auth, release:fix

#6794 [CI]: Publish canary using premajor
  .github/workflows/publish-canary.yml
Labels: release:chore

#6789 fix flightcontrol config template
  packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
Labels: release:fix, fixture-ok

#6771 Update generated render.yaml
  packages/cli/src/commands/setup/deploy/templates/render.js
Labels: release:fix, fixture-ok

#6791 docs: Add mocking useLocation to docs
  docs/docs/testing.md
Labels: release:docs

#6722 (docs): Minor Command update about Storybook
  docs/docs/cli-commands.md
Labels: release:docs

#6723 [CRWA]: Switch to using enquirer, add engine compatibility override option
  packages/create-redwood-app/package.json
  packages/create-redwood-app/src/create-redwood-app.js
  yarn.lock
Labels: topic/cli, topic/crwa, release:feature

#6804 Custom auth: Fix comment in template
  packages/auth-providers-setup/src/custom/templates/web/auth.ts.template
Labels: release:chore

#6801 [Tutorial]: Fix Typescript code blocks inconsistency
  docs/docs/tutorial/chapter3/saving-data.md
Labels: release:docs

#6806 fix: have scaffold set titleTo and buttonTo depend on getTemplateStrings
  packages/cli/src/commands/generate/scaffold/scaffold.js
Labels: release:fix, fixture-ok

#6797 [Docs]: Move hooks section after components section in testing reference
  docs/docs/testing.md
Labels: release:docs

#6805 (crwa): Add git init option
  docs/docs/cli-commands.md
  packages/create-redwood-app/src/create-redwood-app.js
  tasks/run-e2e
Labels: release:feature

#6812 Handle multiple set-cookie headers
  packages/api-server/src/__tests__/requestHandlers/awsLambdaFastify.test.ts
  packages/api-server/src/__tests__/requestHandlers/utils.test.ts
  packages/api-server/src/requestHandlers/awsLambdaFastify.ts
  packages/api-server/src/requestHandlers/utils.ts
Labels: release:fix, needs-cherry-pick

#6828 chore(generate): update scaffoldPath test
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPath.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMulti.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiword.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiwordNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathNoNest.test.js
Labels: release:chore, fixture-ok

#6827 chore(generate): refactor functions generator tests for performance
  packages/cli/src/commands/generate/function/__tests__/__snapshots__/function.test.ts.snap
  packages/cli/src/commands/generate/function/__tests__/function.test.ts
Labels: release:chore, fixture-ok

#6826 chore(generate): refactor layout generator tests for performance
  packages/cli/src/commands/generate/layout/__tests__/__snapshots__/layout.test.ts.snap
  packages/cli/src/commands/generate/layout/__tests__/layout.test.ts
Labels: release:chore, fixture-ok

#6825 chore(generate): Refactor how page tests are written
  packages/cli/package.json
  packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap
  packages/cli/src/commands/generate/page/__tests__/page.test.js
Labels: release:chore, fixture-ok

#6815 docs: Fix capitalization of "--webauthn"
  docs/docs/auth/dbauth.md
Labels: release:docs

#6839 Change to use @iarna/toml instead of toml
  packages/codemods/package.json
  packages/codemods/src/lib/getRWPaths.ts
  packages/internal/package.json
  packages/internal/src/config.ts
  packages/structure/package.json
  packages/structure/src/model/RWTOML.ts
  yarn.lock
Labels: release:chore

#6857 [Chore]: Add branch strategy tooling
  package.json
  tasks/release/branchStrategy/branchStrategyCLI.mjs
  tasks/release/branchStrategy/branchStrategyLib.mjs
  tasks/release/branchStrategy/findPRCommand.mjs
  tasks/release/branchStrategy/triageMainCache.json
  tasks/release/branchStrategy/triageMainCommand.mjs
  tasks/release/branchStrategy/triageNextCache.json
  tasks/release/branchStrategy/triageNextCommand.mjs
  tasks/release/branchStrategy/validateMilestonesCommand.mjs
Labels: release:chore

#6861 [Fix]: Rebuild test-project fixture by passing `--no-git`
  tasks/test-project/test-project
Labels: release:chore

#6082 Adds caching for services
  docs/docs/cli-commands.md
  docs/docs/services.md
  docs/docs/testing.md
  packages/api/cache/index.js
  packages/api/cache/package.json
  packages/api/package.json
  packages/api/src/cache/__tests__/cache.test.ts
  packages/api/src/cache/__tests__/cacheFindMany.test.ts
  packages/api/src/cache/__tests__/disconnect.test.ts
  packages/api/src/cache/__tests__/shared.test.ts
  packages/api/src/cache/clients/BaseClient.ts
  packages/api/src/cache/clients/InMemoryClient.ts
  packages/api/src/cache/clients/MemcachedClient.ts
  packages/api/src/cache/clients/RedisClient.ts
  packages/api/src/cache/errors.ts
  packages/api/src/cache/index.ts
  packages/auth-providers-setup/src/dbAuth/setupData.ts
  packages/cli-helpers/src/lib/project.ts
  packages/cli/src/commands/setup/cache/cache.js
  packages/cli/src/commands/setup/cache/templates/memcached.ts.template
  packages/cli/src/commands/setup/cache/templates/redis.ts.template
  packages/cli/src/commands/setup/deploy/helpers/index.js
  packages/cli/src/commands/setup/deploy/providers/baremetal.js
  packages/cli/src/commands/setup/deploy/providers/layer0.js
  packages/cli/src/commands/setup/deploy/providers/serverless.js
  packages/cli/src/lib/index.js
  packages/testing/cache/index.js
  packages/testing/cache/package.json
  packages/testing/package.json
  packages/testing/src/cache/index.ts
  yarn.lock
Labels: topic/performance, release:feature, fixture-ok

#6871 fix: print notes straight to stdout
  packages/cli-helpers/src/auth/authTasks.ts
  packages/cli-helpers/src/auth/setupHelpers.ts
Labels: release:fix, fixture-ok

#6347 Ensure env vars are loaded at the start of the CLI
  packages/cli/package.json
  packages/cli/src/__tests__/cwd.test.js
  packages/cli/src/commands/__tests__/serve.test.js
  packages/cli/src/commands/destroy/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/destroy/scaffold/__tests__/scaffoldNoNest.test.js
  packages/cli/src/commands/generate.js
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/dataMigration/dataMigration.js
  packages/cli/src/commands/generate/dbAuth/dbAuth.js
  packages/cli/src/commands/generate/directive/directive.js
  packages/cli/src/commands/generate/function/function.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/layout/layout.js
  packages/cli/src/commands/generate/model/model.js
  packages/cli/src/commands/generate/scaffold/__tests__/editableColumns.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldNoNest.test.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/script/script.js
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/serve.js
  packages/cli/src/index.js
  packages/telemetry/src/telemetry.ts
  yarn.lock
Labels: topic/cli, release:fix, fixture-ok

#6913 [Feat(branch strategy)]: Add readme, expand milestone validation
  tasks/release/branchStrategy/README.md
  tasks/release/branchStrategy/branchStrategyCLI.mjs
  tasks/release/branchStrategy/branchStrategyLib.mjs
  tasks/release/branchStrategy/triageNextCommand.mjs
  tasks/release/branchStrategy/validateMilestonesCommand.mjs
Labels: release:chore

#6926 chore(smoke-test): Temporarily disable replay
  .github/workflows/ci.yml
Labels: release:chore

#6924 chore: Additional tests for paths and config
  packages/internal/src/__tests__/config.test.ts
  packages/internal/src/__tests__/configPath.test.ts
  packages/internal/src/__tests__/paths.test.ts
Labels: release:chore

#6437 feat: Port in use checking for development server
  packages/api-server/src/watch.ts
  packages/cli/package.json
  packages/cli/src/commands/__tests__/dev.test.js
  packages/cli/src/commands/devHandler.js
  packages/cli/src/lib/ports.js
  yarn.lock
Labels: topic/cli, release:feature

#6902 Fix: Add missing `jsonDisplay` function to formatters.tsx.template
  __fixtures__/test-project/api/db/migrations/20221116000917_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20221116000936_create_contact/migration.sql
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/src/lib/formatters.test.tsx
  __fixtures__/test-project/web/src/lib/formatters.tsx
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/lib/formatters.test.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/lib/formatters.tsx.template
Labels: release:fix

#6941 Update flightcontrol.js
  packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
Labels: release:fix, fixture-ok

#6912 working fix for Set whileLoadingPage prop
  packages/router/src/PageLoadingContext.tsx
  packages/router/src/Set.tsx
Labels: release:feature

#6945 chore: Mock dev server port check during cli test
  packages/cli/src/commands/__tests__/dev.test.js
Labels: release:fix

#6932 Better explanation of how MockRouter works
  packages/testing/src/web/MockRouter.tsx
Labels: release:chore

#6942 chore: Correct paths test, test-project pages
  packages/internal/src/__tests__/paths.test.ts
Labels: release:chore

#6940 [Docs] Replaced outdated information about prerendering cells
  docs/docs/seo-head.md
Labels: release:docs

#6925 chore(generators): Refactor cell tests for performance
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
Labels: release:chore, fixture-ok

#6835 [Dev Server] Feature: Duplicate routes checking and warning
  __fixtures__/test-project/api/db/migrations/20221124162258_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20221124162319_create_contact/migration.sql
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/src/Routes.tsx
  __fixtures__/test-project/web/src/layouts/BlogLayout/BlogLayout.tsx
  __fixtures__/test-project/web/src/pages/ContactPage/ContactPage.stories.tsx
  __fixtures__/test-project/web/src/pages/ContactUsPage/ContactUsPage.stories.tsx
  __fixtures__/test-project/web/src/pages/ContactUsPage/ContactUsPage.test.tsx
  __fixtures__/test-project/web/src/pages/ContactUsPage/ContactUsPage.tsx
  packages/internal/src/__tests__/paths.test.ts
  packages/internal/src/__tests__/routes.test.ts
  packages/internal/src/generate/watch.ts
  packages/internal/src/index.ts
  packages/internal/src/routes.ts
  tasks/smoke-test/tests/prerender.spec.ts
  tasks/test-project/codemods/blogLayout.js
  tasks/test-project/codemods/contactUsPage.js
  tasks/test-project/tasks.js
Labels: topic/router, release:feature

#6963 pin auth0 js sdk
  packages/cli/src/commands/setup/auth/providers/auth0.js
Labels: release:fix

#6973 small tweak to flightcontrol deploy docs
  docs/docs/deploy/flightcontrol.md
Labels: release:docs

#6972 fix launch.json
  __fixtures__/test-project/.vscode/launch.json
  packages/create-redwood-app/template/.vscode/launch.json
Labels: release:fix

#6905 Render Deploy: Define plan in template
  packages/cli/src/commands/setup/deploy/templates/render.js
Labels: release:fix, fixture-ok

#6969 fix: extractCookie from GraphiQLHeader (#6894)
  packages/auth-providers-api/src/dbAuth/__tests__/DbAuthHandler.test.js
  packages/auth-providers-api/src/dbAuth/__tests__/shared.test.js
  packages/auth-providers-api/src/dbAuth/shared.ts
Labels: release:fix

#6498 docs: Adds Troubleshooting Section to Serverless
  docs/docs/deploy/serverless.md
Labels: release:docs

#6497 Chore: RedwoodJS Directives - Make it clearer that can use directiveArgs in Transformer directive
  packages/testing/src/api/directive.ts
Labels: release:chore

#6922 auth0 and netlify auth packages
  package.json
  packages/auth-providers/auth0/api/.babelrc.js
  packages/auth-providers/auth0/api/README.md
  packages/auth-providers/auth0/api/jest.config.js
  packages/auth-providers/auth0/api/package.json
  packages/auth-providers/auth0/api/src/__tests__/auth0.test.ts
  packages/auth-providers/auth0/api/src/decoder.ts
  packages/auth-providers/auth0/api/src/index.ts
  packages/auth-providers/auth0/api/tsconfig.json
  packages/auth-providers/auth0/setup/.babelrc.js
  packages/auth-providers/auth0/setup/README.md
  packages/auth-providers/auth0/setup/jest.config.js
  packages/auth-providers/auth0/setup/package.json
  packages/auth-providers/auth0/setup/src/__tests__/setup.test.ts
  packages/auth-providers/auth0/setup/src/index.ts
  packages/auth-providers/auth0/setup/src/setup.ts
  packages/auth-providers/auth0/setup/src/templates/api/lib/auth.ts.template
  packages/auth-providers/auth0/setup/src/templates/web/auth.ts.template
  packages/auth-providers/auth0/setup/tsconfig.json
  packages/auth-providers/auth0/web/.babelrc.js
  packages/auth-providers/auth0/web/README.md
  packages/auth-providers/auth0/web/jest.config.js
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/auth0/web/src/__tests__/auth0.test.tsx
  packages/auth-providers/auth0/web/src/auth0.ts
  packages/auth-providers/auth0/web/src/index.ts
  packages/auth-providers/auth0/web/tsconfig.json
  packages/auth-providers/netlify/api/.babelrc.js
  packages/auth-providers/netlify/api/README.md
  packages/auth-providers/netlify/api/jest.config.js
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/netlify/api/src/__tests__/netlify.test.ts
  packages/auth-providers/netlify/api/src/decoder.ts
  packages/auth-providers/netlify/api/src/index.ts
  packages/auth-providers/netlify/api/tsconfig.json
  packages/auth-providers/netlify/setup/.babelrc.js
  packages/auth-providers/netlify/setup/README.md
  packages/auth-providers/netlify/setup/jest.config.js
  packages/auth-providers/netlify/setup/package.json
  packages/auth-providers/netlify/setup/src/__tests__/setup.test.ts
  packages/auth-providers/netlify/setup/src/index.ts
  packages/auth-providers/netlify/setup/src/setup.ts
  packages/auth-providers/netlify/setup/src/templates/api/lib/auth.ts.template
  packages/auth-providers/netlify/setup/src/templates/web/auth.ts.template
  packages/auth-providers/netlify/setup/tsconfig.json
  packages/auth-providers/netlify/web/.babelrc.js
  packages/auth-providers/netlify/web/README.md
  packages/auth-providers/netlify/web/jest.config.js
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/netlify/web/src/__tests__/netlify.test.tsx
  packages/auth-providers/netlify/web/src/index.ts
  packages/auth-providers/netlify/web/src/netlify.ts
  packages/auth-providers/netlify/web/tsconfig.json
  yarn.lock
Labels: release:chore

#6982 azure auth package
  packages/auth-providers/azureActiveDirectory/api/.babelrc.js
  packages/auth-providers/azureActiveDirectory/api/README.md
  packages/auth-providers/azureActiveDirectory/api/jest.config.js
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/api/src/__tests__/azureActiveDirectory.test.ts
  packages/auth-providers/azureActiveDirectory/api/src/decoder.ts
  packages/auth-providers/azureActiveDirectory/api/src/index.ts
  packages/auth-providers/azureActiveDirectory/api/tsconfig.json
  packages/auth-providers/azureActiveDirectory/setup/.babelrc.js
  packages/auth-providers/azureActiveDirectory/setup/README.md
  packages/auth-providers/azureActiveDirectory/setup/jest.config.js
  packages/auth-providers/azureActiveDirectory/setup/package.json
  packages/auth-providers/azureActiveDirectory/setup/src/__tests__/setup.test.ts
  packages/auth-providers/azureActiveDirectory/setup/src/index.ts
  packages/auth-providers/azureActiveDirectory/setup/src/setup.ts
  packages/auth-providers/azureActiveDirectory/setup/src/templates/api/lib/auth.ts.template
  packages/auth-providers/azureActiveDirectory/setup/src/templates/web/auth.ts.template
  packages/auth-providers/azureActiveDirectory/setup/tsconfig.json
  packages/auth-providers/azureActiveDirectory/web/.babelrc.js
  packages/auth-providers/azureActiveDirectory/web/README.md
  packages/auth-providers/azureActiveDirectory/web/jest.config.js
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/azureActiveDirectory/web/src/__tests__/azureActiveDirectory.test.tsx
  packages/auth-providers/azureActiveDirectory/web/src/azureActiveDirectory.ts
  packages/auth-providers/azureActiveDirectory/web/src/index.ts
  packages/auth-providers/azureActiveDirectory/web/tsconfig.json
  yarn.lock
Labels: release:chore

#6984 Custom auth package
  packages/auth-providers/custom/api/.babelrc.js
  packages/auth-providers/custom/api/README.md
  packages/auth-providers/custom/api/jest.config.js
  packages/auth-providers/custom/api/package.json
  packages/auth-providers/custom/api/src/__tests__/custom.test.ts
  packages/auth-providers/custom/api/src/decoder.ts
  packages/auth-providers/custom/api/src/index.ts
  packages/auth-providers/custom/api/tsconfig.json
  packages/auth-providers/custom/setup/.babelrc.js
  packages/auth-providers/custom/setup/README.md
  packages/auth-providers/custom/setup/jest.config.js
  packages/auth-providers/custom/setup/package.json
  packages/auth-providers/custom/setup/src/__tests__/setup.test.ts
  packages/auth-providers/custom/setup/src/index.ts
  packages/auth-providers/custom/setup/src/setup.ts
  packages/auth-providers/custom/setup/src/templates/api/lib/auth.ts.template
  packages/auth-providers/custom/setup/src/templates/web/auth.ts.template
  packages/auth-providers/custom/setup/tsconfig.json
  yarn.lock
Labels: release:chore

#6968 Remove api db auth global
  packages/auth-providers-web/src/dbAuth/dbAuth.ts
  packages/auth-providers-web/src/dbAuth/webAuthn.ts
  packages/core/config/webpack.common.js
  packages/internal/src/config.ts
  packages/prerender/ambient.d.ts
  packages/router/ambient.d.ts
  packages/web/ambient.d.ts
  packages/web/src/config.ts
  packages/web/src/global.web-auto-imports.ts
Labels: release:chore

#6986 Custom auth should not have api package
  packages/auth-providers/custom/api/.babelrc.js
  packages/auth-providers/custom/api/README.md
  packages/auth-providers/custom/api/jest.config.js
  packages/auth-providers/custom/api/package.json
  packages/auth-providers/custom/api/src/__tests__/custom.test.ts
  packages/auth-providers/custom/api/src/decoder.ts
  packages/auth-providers/custom/api/src/index.ts
  packages/auth-providers/custom/api/tsconfig.json
  yarn.lock
Labels: release:chore

#6971 chore(docs): Change edit link text
  docs/i18n/en/code.json
Labels: release:docs

#6985 Use auth provider specific packages
  packages/auth-providers-api/src/auth0/__tests__/auth0.test.ts
  packages/auth-providers-api/src/auth0/decoder.ts
  packages/auth-providers-api/src/azureActiveDirectory/__tests__/azureActiveDirectory.test.ts
  packages/auth-providers-api/src/azureActiveDirectory/decoder.ts
  packages/auth-providers-api/src/custom/decoder.ts
  packages/auth-providers-api/src/index.ts
  packages/auth-providers-api/src/netlify/__tests__/netlify.test.ts
  packages/auth-providers-api/src/netlify/decoder.ts
  packages/auth-providers-setup/package.json
  packages/auth-providers-setup/src/auth0/setup.ts
  packages/auth-providers-setup/src/auth0/templates/api/lib/auth.ts.template
  packages/auth-providers-setup/src/auth0/templates/web/auth.ts.template
  packages/auth-providers-setup/src/azureActiveDirectory/setup.ts
  packages/auth-providers-setup/src/azureActiveDirectory/templates/api/lib/auth.ts.template
  packages/auth-providers-setup/src/azureActiveDirectory/templates/web/auth.ts.template
  packages/auth-providers-setup/src/custom/setup.ts
  packages/auth-providers-setup/src/custom/templates/api/lib/auth.ts.template
  packages/auth-providers-setup/src/custom/templates/web/auth.ts.template
  packages/auth-providers-setup/src/index.ts
  packages/auth-providers-setup/src/netlify/__tests__/setup.test.ts
  packages/auth-providers-setup/src/netlify/setup.ts
  packages/auth-providers-setup/src/netlify/templates/api/lib/auth.ts.template
  packages/auth-providers-setup/src/netlify/templates/web/auth.ts.template
  packages/auth-providers-web/src/auth0/__tests__/auth0.test.tsx
  packages/auth-providers-web/src/auth0/auth0.ts
  packages/auth-providers-web/src/azureActiveDirectory/__tests__/azureActiveDirectory.test.tsx
  packages/auth-providers-web/src/azureActiveDirectory/azureActiveDirectory.ts
  packages/auth-providers-web/src/index.ts
  packages/auth-providers-web/src/netlify/__tests__/netlify.test.tsx
  packages/auth-providers-web/src/netlify/netlify.ts
  packages/auth-providers/auth0/setup/src/setup.ts
  packages/auth-providers/azureActiveDirectory/setup/src/setup.ts
  packages/auth-providers/netlify/setup/src/setup.ts
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:chore, fixture-ok

#6997 fix(cli): Handle importing optional setup auth commands
  packages/auth-providers/azureActiveDirectory/setup/src/__tests__/setup.test.ts
  packages/auth-providers/azureActiveDirectory/setup/src/setup.ts
  packages/cli/src/commands/setup/auth/auth.js
  tasks/framework-tools/lib/framework.mjs
  tasks/framework-tools/lib/project.mjs
Labels: release:fix, fixture-ok
