Repository redwoodjs/graphql, pull requests merged in 2022-08, with the labels that each got.

#6086 Update Azure auth docs
  docs/docs/auth/azure.md
Labels: release:docs

#6007 fix: Adds defensive check for GraphQL Errors when rendering errors of other types in Forms
  packages/forms/src/index.tsx
Labels: release:fix

#6095 docs(ts): Update some TS links, and add a tip to the tutorial
  docs/docs/tutorial/chapter2/cells.md
  docs/docs/tutorial/chapter2/routing-params.md
  docs/docs/tutorial/chapter3/saving-data.md
  docs/docs/typescript/generated-types.md
  docs/versioned_docs/version-2.2/tutorial/chapter2/routing-params.md
Labels: release:docs

#6085 docs: Fix deploy serverless command
  docs/docs/deploy/introduction.md
  docs/versioned_docs/version-2.2/deploy/introduction.md
Labels: release:docs

#6110 Update `requireAuth` param types in src/lib/auth templates
  __fixtures__/test-project/api/db/migrations/20220802121151_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220802121200_create_contact/migration.sql
  __fixtures__/test-project/api/src/lib/auth.ts
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/src/components/Contact/EditContactCell/EditContactCell.tsx
  __fixtures__/test-project/web/src/components/Post/EditPostCell/EditPostCell.tsx
  packages/cli/src/commands/setup/auth/templates/auth0.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/azureActiveDirectory.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/clerk.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.webAuthn.ts.template
  packages/cli/src/commands/setup/auth/templates/okta.auth.ts.template
Labels: release:fix

#6098 codemod(v2.3): Adds codemod to modify web/tsconfig.json to allow $api imports
  packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/README.md
  packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/__testfixtures__/default/input/web/tsconfig.json
  packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/__testfixtures__/default/output/web/tsconfig.json
  packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/__tests__/tsconfigForRouteHooks.test.ts
  packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/tsconfigForRouteHooks.ts
  packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/tsconfigForRouteHooks.yargs.ts
  packages/codemods/src/lib/prettify.ts
Labels: release:chore

#6038 chore: Updates envelop types to v.2.3.0
  packages/graphql-server/package.json
  packages/graphql-server/src/__tests__/makeDirectives.test.ts
  packages/graphql-server/src/directives/makeDirectives.ts
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodDirective.test.ts
  packages/graphql-server/src/plugins/useRedwoodDirective.ts
  packages/testing/src/api/directive.ts
  yarn.lock
Labels: release:chore

#6121 fix(codemods): Add typescript as a dependency of codemods package
  packages/codemods/package.json
  yarn.lock
Labels: release:fix

#5824 Auto-generate GraphQL comments in SDL to support a self-documenting API
  __fixtures__/test-project/api/db/schema.prisma
  docs/docs/cli-commands.md
  docs/docs/graphql.md
  docs/static/img/docusuarus.png
  docs/static/img/graphql-api-docs/contact-query.png
  docs/static/img/graphql-api-docs/contact-type.png
  docs/static/img/graphql-api-docs/graphiql-input-type.png
  docs/static/img/graphql-api-docs/graphiql-mutations.png
  docs/static/img/graphql-api-docs/graphiql-queries.png
  docs/static/img/graphql-api-docs/graphiql-type.png
  docs/static/img/graphql-api-docs/schema-directive.png
  docs/static/img/graphql-api-docs/schema-doc.png
  docs/static/img/graphql-api-docs/schema-input.png
  docs/static/img/graphql-api-docs/schema-mutation.png
  docs/static/img/graphql-api-docs/schema-scalar.png
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/sdl/__tests__/__snapshots__/sdl.test.js.snap
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/sdl/__tests__/sdl.test.js
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/generate/sdl/templates/sdl.js.template
  packages/cli/src/commands/generate/sdl/templates/sdl.ts.template
  packages/graphql-server/src/rootSchema.ts
  packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
  packages/internal/src/__tests__/__snapshots__/graphqlSchema.test.ts.snap
Labels: release:feature

#6123 fix: Use the GraphQL codegen add plugin to include the Prisma namespace needed for the web type generation
  packages/internal/package.json
  packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
  packages/internal/src/generate/graphqlCodeGen.ts
  yarn.lock
Labels: release:fix

#6093 Generate Prisma Client when prerendering
  packages/cli/src/commands/buildHandler.js
  packages/cli/src/commands/prerenderHandler.js
Labels: release:fix

#6130 docs: Remove 'W' from from pm2 installation command
  docs/docs/how-to/self-hosting-redwood.md
Labels: release:fix

#5924 [Chore]: Upgrade prisma dependencies and specifiers to v4
  packages/api/package.json
  packages/cli/package.json
  packages/cli/src/commands/setup/deploy/providers/flightcontrol.js
  packages/cli/src/commands/setup/deploy/providers/render.js
  packages/cli/src/lib/schemaHelpers.js
  packages/graphql-server/package.json
  packages/record/package.json
  packages/record/src/tasks/parse.js
  packages/structure/package.json
  packages/structure/src/model/RWProject.ts
  packages/testing/config/jest/api/jest.setup.js
  yarn.lock
Labels: release:feature-breaking, next-release/major, fixture-ok

#6119 tailwindcss ui: Support yarn v1 while setting up
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
Labels: release:fix, fixture-ok

#6031 Update sending-emails.md
  docs/docs/how-to/sending-emails.md
Labels: release:docs

#6077 Handful of doc fixes - typos and light highlights
  docs/docs/environment-variables.md
  docs/docs/graphql.md
  docs/docs/serverless-functions.md
  docs/docs/services.md
  docs/docs/testing.md
Labels: release:docs

#6117 Added full qualified path and mockServiceWorker.js to webpack file copy globOptions
  CONTRIBUTING.md
  packages/core/config/webpack.common.js
Labels: release:fix

#6150 Include ./scripts and ./web/config folders when linting
  packages/cli/src/commands/lint.js
Labels: release:fix

#6158 Tutorial 4.1: Update lib/auth code & remove warning about non-existent TS error (fixed via #5856, shipped in v2.1)
  docs/docs/tutorial/chapter4/authentication.md
Labels: release:docs

#6160 Fix a typo in TS docs (there is no hasRole*s* function)
  docs/docs/typescript/strict-mode.md
Labels: release:docs

#4900 `cli/lib/merge` & `setup ui mantine`
  docs/docs/cli-commands.md
  package.json
  packages/cli/src/commands/setup/i18n/i18n.js
  packages/cli/src/commands/setup/ui/libraries/chakra-ui.js
  packages/cli/src/commands/setup/ui/libraries/mantine.js
  packages/cli/src/commands/setup/ui/tasks/setup-chakra.js
  packages/cli/src/commands/setup/ui/templates/chakra.storybook.preview.js.template
  packages/cli/src/commands/setup/ui/templates/mantine.storybook.preview.js.template
  packages/cli/src/commands/setup/ui/templates/storybook.preview.js.template
  packages/cli/src/lib/__tests__/fixtures/merge/chakraIntoI18n/base.jsx
  packages/cli/src/lib/__tests__/fixtures/merge/chakraIntoI18n/expected.jsx
  packages/cli/src/lib/__tests__/fixtures/merge/chakraIntoI18n/ext.jsx
  packages/cli/src/lib/__tests__/fixtures/merge/chakraIntoI18n/it.txt
  packages/cli/src/lib/__tests__/fixtures/merge/i18nIntoBase/base.jsx
  packages/cli/src/lib/__tests__/fixtures/merge/i18nIntoBase/expected.jsx
  packages/cli/src/lib/__tests__/fixtures/merge/i18nIntoBase/ext.jsx
  packages/cli/src/lib/__tests__/fixtures/merge/i18nIntoBase/it.txt
  packages/cli/src/lib/__tests__/fixtures/unindented.js
  packages/cli/src/lib/__tests__/mergeBasics.test.js
  packages/cli/src/lib/__tests__/mergeConfig.test.js
  packages/cli/src/lib/__tests__/mergeSemantics.test.js
  packages/cli/src/lib/configureStorybook.js
  packages/cli/src/lib/extendFile.js
  packages/cli/src/lib/merge/README.md
  packages/cli/src/lib/merge/algorithms.js
  packages/cli/src/lib/merge/index.js
  packages/cli/src/lib/merge/semanticIdentity.js
  packages/cli/src/lib/merge/strategy.js
  packages/cli/src/lib/templates/storybook.preview.js.template
  yarn.lock
Labels: release:feature, fixture-ok

#5827 Fix unused import in generator cell test template
  __fixtures__/test-project/web/src/components/BlogPostCell/BlogPostCell.test.tsx
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.test.tsx
  __fixtures__/test-project/web/src/components/WaterfallBlogPostCell/WaterfallBlogPostCell.test.tsx
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/templates/test.js.template
Labels: topic/generators-&-scaffolds, release:fix

#6168 Setup exclude: Eagerly match all 'setup' in path
  packages/cli/src/commands/generate.js
  packages/cli/src/commands/setup.js
Labels: release:fix, fixture-ok

#6135 Revert auth provider refactor
  packages/auth/package.json
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/auth/src/authClients/AuthClient.ts
  packages/auth/src/authClients/SupportedAuthClients.ts
  packages/auth/src/authClients/clerk.ts
  packages/auth/src/authClients/index.ts
  packages/cli/src/commands/setup/auth/providers/clerk.js
  packages/codemods/src/codemods/v2.2.x/updateClerk/README.md
  packages/codemods/src/codemods/v2.2.x/updateClerk/__testfixtures__/app.input.js
  packages/codemods/src/codemods/v2.2.x/updateClerk/__testfixtures__/app.output.js
  packages/codemods/src/codemods/v2.2.x/updateClerk/__tests__/updateClerk.test.ts
  packages/codemods/src/codemods/v2.2.x/updateClerk/updateClerk.ts
  packages/codemods/src/codemods/v2.2.x/updateClerk/updateClerk.yargs.ts
  packages/core/config/webpack.common.js
  packages/testing/config/storybook/main.js
  yarn.lock
Labels: release:fix, fixture-ok

#6115 docs(tutorial): Adds more TS hints in the toturial
  docs/docs/tutorial/chapter2/cells.md
  docs/docs/tutorial/chapter7/rbac.md
  docs/versioned_docs/version-2.2/tutorial/chapter2/cells.md
  docs/versioned_docs/version-2.2/tutorial/chapter7/rbac.md
Labels: release:docs

#6059 Amend import order in auth templates according to ESLint rules introduced in v2.0
  packages/cli/src/commands/generate/dbAuth/templates/forgotPassword.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/login.webAuthn.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/resetPassword.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/signup.tsx.template
  packages/cli/src/commands/setup/auth/templates/clerk.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.webAuthn.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.function.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.function.webAuthn.ts.template
  packages/cli/src/commands/setup/auth/templates/firebase.auth.ts.template
Labels: topic/crwa, release:fix, fixture-ok

#6159 Harmonize optional chaining across all `hasRole` flavors & reduce duplication, avoiding errors on empty currentUser
  __fixtures__/test-project/api/src/lib/auth.ts
  docs/docs/tutorial/chapter4/authentication.md
  docs/docs/tutorial/chapter7/rbac.md
  docs/docs/typescript/strict-mode.md
  packages/cli/src/commands/setup/auth/templates/auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.webAuthn.ts.template
  packages/cli/src/commands/setup/auth/templates/okta.auth.ts.template
Labels: release:chore

#6195 fix(generators): Dont set tests=false in sdl generators by default
  __fixtures__/test-project/api/db/migrations/20220809160848_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220809160910_create_contact/migration.sql
  __fixtures__/test-project/api/db/schema.prisma
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/scripts/seed.ts
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/components/AuthorCell/AuthorCell.test.tsx
  packages/cli/src/commands/generate/sdl/sdl.js
  tasks/test-project/codemods/models.js
Labels: release:chore

#6199 Leverage PROJECT_CWD to set cwd in yarn 3 bin "proxies"
  packages/api/src/bins/redwood.ts
  packages/api/src/bins/rwfw.ts
  packages/cli/src/index.js
  packages/core/src/bins/cross-env.ts
  packages/core/src/bins/redwood.ts
  packages/core/src/bins/rwfw.ts
  packages/web/src/bins/msw.ts
  packages/web/src/bins/redwood.ts
  packages/web/src/bins/rwfw.ts
Labels: topic/cli, release:fix

#6145 testing.md: Update file path in code snippet
  docs/docs/testing.md
Labels: release:docs

#6045 Tutorial 6.3: Fix prisma type error on comment creation
  docs/docs/tutorial/chapter6/comments-schema.md
Labels: release:docs

#5896 Fix redwood root schema definition link on GraphQL docs page
  docs/docs/graphql.md
Labels: release:docs

#6211 Tutorial Chapter 4: Miniscule typo fixup
  docs/docs/tutorial/chapter4/deployment.md
  docs/versioned_docs/version-2.2/tutorial/chapter4/deployment.md
Labels: release:docs

#6206 chore(dx): Improve errors and warnings during Cell prerendering
  docs/docs/prerender.md
  packages/cli/src/commands/__tests__/build.test.js
  packages/cli/src/commands/buildHandler.js
  packages/cli/src/commands/prerenderHandler.js
  packages/prerender/src/errors.tsx
  packages/prerender/src/graphql/graphql.ts
  packages/prerender/src/runPrerender.tsx
  packages/web/src/components/CellCacheContext.tsx
  packages/web/src/components/createCell.tsx
Labels: release:chore

#6202 docs(ts): Add section on core concepts and reorg introduction
  docs/docs/typescript/generated-types.md
  docs/docs/typescript/introduction.md
Labels: release:docs

#5868 Add section on VSCode folder-/watcher-ignore settings to "Project Configuration" docs (using `.yarn`-folder as an example)
  docs/docs/project-configuration-dev-test-build.mdx
Labels: release:docs

#6222 fix(ts): Avoid using partial resolver return types in codegen
  docs/docs/typescript/strict-mode.md
  packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
  packages/internal/src/__tests__/resolverFn.test.ts
  packages/internal/src/generate/graphqlCodeGen.ts
Labels: release:fix

#6208 [Build] Add more api-side polyfill tests
  __fixtures__/example-todo-main/api/src/lib/polyfill.js
  packages/internal/src/__tests__/build_api.test.ts
  packages/internal/src/build/babel/api.ts
Labels: release:chore

#6126 Force file paths computed during Baremetal deploy to always have forward slashes
  packages/cli/src/commands/deploy/baremetal.js
Labels: topic/deployment, release:fix

#6224 Tutorial: Use curly braces and `return` in ArticleCell Success
  docs/docs/tutorial/chapter2/routing-params.md
Labels: release:docs

#6229 [Build] Bump Node.js target from 12 to 14
  babel.config.js
  packages/internal/src/__tests__/build_api.test.ts
  packages/internal/src/build/api.ts
  packages/internal/src/build/babel/api.ts
Labels: release:feature-breaking, next-release/major

#6234 Specify content-type in Yoga CORS test
  packages/graphql-server/src/__tests__/cors.test.ts
Labels: release:fix

#6118 [Docs] Adds a doc about getting started with SSH and real servers
  docs/docs/deploy/baremetal.md
  docs/docs/intro-to-servers.md
  docs/versioned_docs/version-2.0/deploy/baremetal.md
  docs/versioned_docs/version-2.0/intro-to-servers.md
  docs/versioned_docs/version-2.1/deploy/baremetal.md
  docs/versioned_docs/version-2.1/intro-to-servers.md
  docs/versioned_docs/version-2.2/deploy/baremetal.md
  docs/versioned_docs/version-2.2/intro-to-servers.md
Labels: topic/deployment, release:docs

#6241 Set content-type header when prerendering
  packages/prerender/src/graphql/graphql.ts
Labels: release:fix

#6102 docs: update netlify deployment settings
  docs/docs/tutorial/chapter4/deployment.md
Labels: topic/deployment, release:docs

#6240 More helpful prerender error message
  packages/prerender/package.json
  packages/prerender/src/errors.tsx
  packages/prerender/src/runPrerender.tsx
  yarn.lock
Labels: release:feature

#6216 Add arg types to @requireAuth
  packages/create-redwood-app/template/api/src/directives/requireAuth/requireAuth.ts
Labels: release:fix, fixture-ok

#6263 More SSH doc updates, finally adds nginx config details to Baremetal doc
  docs/docs/deploy/baremetal.md
  docs/docs/intro-to-servers.md
  docs/versioned_docs/version-2.0/deploy/baremetal.md
  docs/versioned_docs/version-2.0/intro-to-servers.md
  docs/versioned_docs/version-2.1/deploy/baremetal.md
  docs/versioned_docs/version-2.1/intro-to-servers.md
  docs/versioned_docs/version-2.2/deploy/baremetal.md
  docs/versioned_docs/version-2.2/intro-to-servers.md
Labels: release:docs

#6273 [Fix] Swap `testURL` for `testEnvironmentOptions.url` in Jest web preset
  packages/testing/config/jest/web/jest-preset.js
Labels: release:fix

#6264 Fix DOM nesting warning in test project
  __fixtures__/test-project/api/db/migrations/20220823002342_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220823002351_create_contact/migration.sql
  __fixtures__/test-project/api/src/directives/requireAuth/requireAuth.ts
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/src/components/AuthorCell/AuthorCell.tsx
  tasks/test-project/codemods/authorCell.js
Labels: release:fix

#6276 Fix jest-preset formatting
  packages/testing/config/jest/web/jest-preset.js
Labels: release:chore

#6220 Fix strict mode errors in Name and NameForm scaffold templates
  __fixtures__/test-project/api/db/migrations/20220823213645_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220823213655_create_contact/migration.sql
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/src/components/Contact/Contact/Contact.tsx
  __fixtures__/test-project/web/src/components/Contact/ContactForm/ContactForm.tsx
  __fixtures__/test-project/web/src/components/Post/Post/Post.tsx
  __fixtures__/test-project/web/src/components/Post/PostForm/PostForm.tsx
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/components/Name.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NameForm.tsx.template
Labels: release:fix

#6278 Rename scaffolded type to FormName
  __fixtures__/test-project/api/db/migrations/20220824103905_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220824103915_create_contact/migration.sql
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/src/components/Contact/ContactForm/ContactForm.tsx
  __fixtures__/test-project/web/src/components/Post/PostForm/PostForm.tsx
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/components/NameForm.tsx.template
Labels: release:chore

#6280 chore(lint): Fix seed lint issue
  packages/create-redwood-app/template/scripts/seed.ts
Labels: release:chore, fixture-ok

#6272 feat(ts): Improve types for directives
  __fixtures__/test-project/api/src/directives/requireAuth/requireAuth.ts
  docs/docs/directives.md
  docs/docs/typescript/utility-types.md
  packages/cli/src/commands/generate/directive/__tests__/__snapshots__/directive.test.ts.snap
  packages/cli/src/commands/generate/directive/templates/validator.directive.ts.template
  packages/create-redwood-app/template/api/src/directives/requireAuth/requireAuth.ts
  packages/graphql-server/src/index.ts
  packages/graphql-server/src/plugins/useRedwoodDirective.ts
Labels: release:feature

#6257 [Fix] Install `@emotion/react` with mantine packages
  packages/cli/src/commands/setup/ui/libraries/mantine.js
Labels: topic/cli, release:fix, fixture-ok

#6213 fix: `import/order` should treat "glob star" imports as their own group
  .eslintrc.js
  __fixtures__/test-project/api/src/functions/graphql.ts
  packages/create-redwood-app/template/api/src/functions/graphql.ts
  packages/eslint-config/shared.js
  packages/graphql-server/src/functions/graphql.ts
  packages/prerender/src/graphql/graphql.ts
Labels: release:feature-breaking, next-release/major

#6261 Docs: Clarify Netlify build and deployment and advise not to use the Netlify CLI
  docs/docs/cli-commands.md
  docs/docs/deploy/netlify.md
  docs/docs/tutorial/chapter4/deployment.md
Labels: release:chore

#6298 [Fix] Try reverting `tough-cookie` patch change
  packages/testing/config/jest/web/jest-preset.js
Labels: release:fix

#6304 Adds a Deploy Keys section to server doc
  docs/docs/intro-to-servers.md
  docs/versioned_docs/version-2.0/intro-to-servers.md
  docs/versioned_docs/version-2.1/intro-to-servers.md
  docs/versioned_docs/version-2.2/intro-to-servers.md
Labels: topic/deployment, release:docs

#6310 docs: fix typos
  docs/docs/app-configuration-redwood-toml.md
  docs/docs/auth/dbauth.md
  docs/docs/graphql.md
  docs/docs/how-to/sending-emails.md
  docs/docs/project-configuration-dev-test-build.mdx
  docs/versioned_docs/version-1.0/how-to/sending-emails.md
  docs/versioned_docs/version-1.0/project-configuration-dev-test-build.mdx
  docs/versioned_docs/version-1.0/tutorial/chapter6/comment-form.md
  docs/versioned_docs/version-1.0/tutorial/chapter7/rbac.md
  docs/versioned_docs/version-1.1/how-to/sending-emails.md
  docs/versioned_docs/version-1.1/project-configuration-dev-test-build.mdx
  docs/versioned_docs/version-1.1/tutorial/chapter7/rbac.md
  docs/versioned_docs/version-1.2/how-to/sending-emails.md
  docs/versioned_docs/version-1.2/project-configuration-dev-test-build.mdx
  docs/versioned_docs/version-1.2/tutorial/chapter7/rbac.md
  docs/versioned_docs/version-1.3/how-to/sending-emails.md
  docs/versioned_docs/version-1.3/project-configuration-dev-test-build.mdx
  docs/versioned_docs/version-1.4/how-to/sending-emails.md
  docs/versioned_docs/version-1.4/project-configuration-dev-test-build.mdx
  docs/versioned_docs/version-1.5/how-to/sending-emails.md
  docs/versioned_docs/version-1.5/project-configuration-dev-test-build.mdx
  docs/versioned_docs/version-2.0/how-to/sending-emails.md
  docs/versioned_docs/version-2.1/auth/azure.md
  docs/versioned_docs/version-2.1/how-to/sending-emails.md
  docs/versioned_docs/version-2.2/auth/azure.md
  docs/versioned_docs/version-2.2/how-to/sending-emails.md
Labels: release:docs

#6308 CodeGen: Try to generate prisma client if no models are found
  packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
  packages/internal/src/__tests__/graphqlCodeGen.test.ts
  packages/internal/src/generate/graphqlCodeGen.ts
Labels: release:feature

#6305 [Docs]: Update GraphiQL Paragraph
  docs/docs/tutorial/chapter3/saving-data.md
Labels: release:docs

#6281 feat(jest): Improve performance of jest
  .eslintrc.js
  packages/eslint-config/index.js
  packages/testing/config/jest/api/apiBabelConfig.js
  packages/testing/config/jest/api/jest-preset.js
  packages/testing/config/jest/web/jest-preset.js
  packages/testing/config/jest/web/jest.setup.js
  packages/testing/config/jest/web/webBabelConfig.js
  packages/testing/config/storybook/main.js
  packages/testing/package.json
  packages/testing/src/web/__tests__/findCellMocks.test.ts
  packages/testing/src/web/findCellMocks.ts
  packages/testing/src/web/index.ts
  packages/testing/src/web/mockRequests.ts
  yarn.lock
Labels: release:feature

#6318 Updates simplewebauthn package to latest version
  __fixtures__/test-project/web/src/scaffold.css
  packages/api/package.json
  packages/api/src/functions/dbAuth/DbAuthHandler.ts
  packages/auth/package.json
  packages/cli/src/commands/generate/dbAuth/templates/login.webAuthn.tsx.template
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template
  packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.tailwind.css.template
  yarn.lock
Labels: topic/auth, release:chore

#6228 feat(ts): Improves return types of QueryResolvers, MutationResolvers and <Model>Resolvers
  __fixtures__/test-project/api/db/migrations/20220829111559_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220829111607_create_contact/migration.sql
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/package.json
  docs/docs/typescript/strict-mode.md
  packages/api/src/__tests__/transforms.test.ts
  packages/api/src/functions/dbAuth/DbAuthHandler.ts
  packages/api/src/index.ts
  packages/api/src/transforms.ts
  packages/api/src/types.ts
  packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
  packages/internal/src/__tests__/graphqlCodeGen.test.ts
  packages/internal/src/generate/graphqlCodeGen.ts
  tasks/smoke-test/tests/storybook.spec.ts
Labels: release:feature
