Repository redwoodjs/graphql, pull requests merged in 2022-10, with the labels that each got.

#6487 Align comment with code
  babel.config.js
Labels: release:chore

#6486 Add docs for dbauth generator
  docs/docs/cli-commands.md
Labels: release:docs

#6463 Improve copy for docs on registering fastify plugins
  docs/docs/app-configuration-redwood-toml.md
Labels: release:docs

#6488 awsLambdaFastify test: Hide scary looking red error text
  packages/api-server/src/__tests__/requestHandlers/awsLambdaFastify.test.ts
Labels: release:chore

#6493 Try fixing flaky test on Windows
  packages/router/src/__tests__/router.test.tsx
Labels: release:fix

#6489 Configure eslint to support es2022
  .eslintrc.js
  packages/cli/src/commands/generate/service/service.js
Labels: release:chore, fixture-ok

#6494 update flightcontrol deploy config
  packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
Labels: topic/cli, topic/deployment, release:chore, fixture-ok

#6387 Change type of validateUniqueness
  packages/api/src/validations/validations.ts
Labels: topic/api, topic/typescript, release:fix

#6447 [CRWA]: Upgrade from `listr` to `listr2`
  packages/create-redwood-app/package.json
  packages/create-redwood-app/src/create-redwood-app.js
  yarn.lock
Labels: topic/cli, release:fix

#6491 Support Decimal in scenario tests
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/generate/service/templates/test.ts.template
Labels: release:fix, fixture-ok

#6506 Move to Listr2 for test-project
  package.json
  tasks/test-project/tasks.js
  tasks/test-project/test-project
  yarn.lock
Labels: release:chore

#6372 Adds password validation function to dbAuth
  __fixtures__/test-project/api/src/functions/auth.ts
  docs/docs/auth/dbauth.md
  packages/api/src/functions/dbAuth/DbAuthHandler.ts
  packages/api/src/functions/dbAuth/__tests__/DbAuthHandler.test.js
  packages/api/src/functions/dbAuth/errors.ts
  packages/api/src/index.ts
  packages/cli/src/commands/setup/auth/templates/dbAuth.function.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.function.webAuthn.ts.template
Labels: topic/auth, release:feature

#6503 feat: handle updating all contributors via a cron GitHub action
  .github/actions/update_all_contributors/action.yml
  .github/actions/update_all_contributors/update_all_contributors.mjs
  .github/workflows/update-all-contributors.yml
  .yarn/patches/all-contributors-cli-npm-6.20.0-ba332c4a3e.patch
  package.json
  tasks/release/cli.mjs
  tasks/release/release.mjs
  yarn.lock
Labels: topic/ops-&-contributing-dx, release:chore

#6532 fix: resolve firebase packages to CommonJS in web tests
  packages/testing/config/jest/web/resolver.js
Labels: topic/testing, release:fix

#6557 Fix homebrew formula name for postgresql
  docs/docs/local-postgres-setup.md
Labels: release:docs

#6519 add example for controlled components
  docs/docs/forms.md
Labels: release:docs

#6606 chore(Spelling): Fix tiny spelling issue
  docs/versioned_docs/version-1.0/graphql.md
Labels: release:docs

#6609 sdl.js: Format comment
  packages/cli/src/commands/generate/sdl/sdl.js
Labels: release:chore, fixture-ok

#6608 command_builder: Explicitly convert args to strings
  packages/structure/src/interactive_cli/command_builder.ts
Labels: release:fix

#6611 Telemetry: Fix sensitive spelling
  packages/telemetry/src/sendTelemetry.ts
Labels: release:chore

#6462 Update connection-pooling for Digital Ocean
  docs/docs/connection-pooling.md
Labels: release:docs

#6614 Fully move telemetry to TS
  packages/telemetry/src/index.ts
  packages/telemetry/src/sendTelemetry.ts
  packages/telemetry/tsconfig.json
Labels: release:chore

#6631 docs: Defined `id` in the Props interface
  docs/docs/tutorial/chapter2/routing-params.md
Labels: release:docs

#6633 Make cli-helpers fixtures reflect actual files
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.webAuthn.ts.template
Labels: release:chore

#6634 Check if test-project fixture needs updating when updating cli-helpers
  .github/actions/check_test_project_fixture/check_test_project_fixture.mjs
Labels: release:chore

#6640 auth2
  packages/auth2/.babelrc.js
  packages/auth2/README.md
  packages/auth2/ambient.d.ts
  packages/auth2/jest.config.js
  packages/auth2/package.json
  packages/auth2/src/AuthContext.ts
  packages/auth2/src/AuthImplementation.ts
  packages/auth2/src/AuthProvider/AuthProvider.tsx
  packages/auth2/src/AuthProvider/AuthProviderState.ts
  packages/auth2/src/AuthProvider/useCurrentUser.ts
  packages/auth2/src/AuthProvider/useForgotPassword.ts
  packages/auth2/src/AuthProvider/useHasRole.ts
  packages/auth2/src/AuthProvider/useLogIn.ts
  packages/auth2/src/AuthProvider/useLogOut.ts
  packages/auth2/src/AuthProvider/useReauthenticate.ts
  packages/auth2/src/AuthProvider/useResetPassword.ts
  packages/auth2/src/AuthProvider/useSignUp.ts
  packages/auth2/src/AuthProvider/useToken.ts
  packages/auth2/src/AuthProvider/useValidateResetToken.ts
  packages/auth2/src/__tests__/AuthProvider.test.tsx
  packages/auth2/src/__tests__/fixtures/customTestAuth.ts
  packages/auth2/src/authFactory.ts
  packages/auth2/src/index.ts
  packages/auth2/src/useAuth.ts
  packages/auth2/tsconfig.json
  yarn.lock
Labels: release:chore

#6615 [CLI] Chore: quiet listr output during tests
  packages/cli/src/commands/__tests__/prisma.test.js
  packages/cli/src/commands/__tests__/type-check.test.js
  packages/cli/src/commands/destroy/cell/__tests__/cell.test.js
  packages/cli/src/commands/destroy/component/__tests__/component.test.js
  packages/cli/src/commands/destroy/directive/__tests__/directive.test.js
  packages/cli/src/commands/destroy/function/__tests__/function.test.js
  packages/cli/src/commands/destroy/layout/__tests__/layout.test.js
  packages/cli/src/commands/destroy/service/__tests__/service.test.js
  packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap
  packages/cli/src/commands/generate/page/__tests__/page.test.js
  packages/cli/src/commands/generate/sdl/__tests__/sdl.test.js
Labels: release:chore, fixture-ok

#6653 Router test tweaks
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/set.test.tsx
Labels: release:chore

#6501 Add firebase anonymous authentication option
  packages/auth/src/authClients/firebase.ts
Labels: release:feature

#6656 graphql-server: Stricter types
  packages/graphql-server/src/functions/__tests__/fixtures/auth.ts
  packages/graphql-server/src/functions/__tests__/useRequireAuth.test.ts
  packages/graphql-server/src/functions/useRequireAuth.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodAuthContext.test.ts
Labels: release:chore

#6655 Make rbac spec less flaky
  tasks/smoke-test/tests/rbacChecks.spec.ts
Labels: release:chore

#6657 Router/testing/mocking cleanup and tweaks
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/router-context.tsx
  packages/router/src/router.tsx
  packages/testing/src/web/MockRouter.tsx
  packages/testing/src/web/customRender.tsx
Labels: release:chore

#6555 augment ResetPasswordFlowOptions handler type definition
  packages/api/src/functions/dbAuth/DbAuthHandler.ts
Labels: release:fix

#6664 [CI] Try setting Nx Cloud access token env var
  .github/workflows/ci.yml
  nx.json
Labels: release:chore

#6617 [Docs] Update Self Hosting to point users to Baremetal
  docs/docs/how-to/self-hosting-redwood.md
Labels: release:docs

#6672 Adds docs about removing any UserCredential relationship manually from generated User SDL
  docs/docs/auth/dbauth.md
  docs/versioned_docs/version-3.0/auth/dbauth.md
  docs/versioned_docs/version-3.1/auth/dbauth.md
  packages/cli/src/commands/setup/auth/providers/dbAuth.webAuthn.js
Labels: release:chore, fixture-ok

#6659 Minor tweaks to apollo index.tsx
  packages/web/src/apollo/index.tsx
Labels: release:chore

#6683 chore: run lerna repair
  lerna.json
  nx.json
Labels: release:chore

#6690 fixes: dbAuth template and Apollo comment
  packages/auth-providers-setup/src/dbAuth/templates/api/functions/auth.ts.template
  packages/auth-providers-setup/src/dbAuth/templates/api/functions/auth.webAuthn.ts.template
  packages/web/src/apollo/index.tsx
Labels: release:fix

#6691 chore: run lint fix post merge #5985
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:chore, fixture-ok

#6692 chore: remove private field on new packages package.json
  packages/auth-providers-api/package.json
  packages/auth-providers-setup/package.json
  packages/auth-providers-web/package.json
  packages/cli-helpers/package.json
Labels: release:chore

#6695 chore: make misc change to trigger canary publishing
  packages/cli-helpers/README.md
Labels: release:chore

#6697 Netlify: Enable auth-providers-api and auth-providers-web installation
  packages/auth-providers-setup/src/netlify/setup.ts
Labels: release:chore

#6698 fix(dbAuth): add required packages to setup command
  __fixtures__/test-project/api/package.json
  __fixtures__/test-project/web/package.json
  packages/auth-providers-setup/src/dbAuth/setup.ts
  packages/auth-providers-setup/src/dbAuth/webAuthn.setupData.ts
  packages/cli-helpers/src/auth/setupHelpers.ts
Labels: release:fix

#6703 fix(CI): don't PR against "next" if we can't cleanly cherry pick
  .github/workflows/cherry-pick-into-next-branch.yml
Labels: release:chore

#6505 feat: publish 2nd canary (@next) from release branch
  .github/workflows/publish-canary.yml
Labels: topic/ops-&-contributing-dx, release:chore

#6709 Fix decouple auth related type errors
  packages/graphql-server/src/plugins/__tests__/useRedwoodAuthContext.test.ts
  packages/web/src/components/FetchConfigProvider.test.tsx
Labels: release:fix

#6710 Update the Clerk setup script and templates
  packages/auth-providers-setup/src/clerk/setup.ts
  packages/auth-providers-setup/src/clerk/templates/web/auth.tsx.template
Labels: release:fix

#6714 chore: Remove redundant space " "
  docs/docs/tutorial/chapter6/comment-form.md
Labels: release:docs

#6716 Auth: Update firebase setup script
  packages/auth-providers-setup/src/firebase/setup.ts
Labels: release:fix

#6718 Add auth decoder to clerk auth setup
  packages/auth-providers-setup/src/clerk/setup.ts
Labels: release:fix, skip-cherry-pick

#6713 Clerk: Simplify web implementation
  packages/auth-providers-web/src/clerk/clerk.tsx
Labels: release:chore, skip-cherry-pick

#6717 Update firebase auth docs
  docs/docs/auth/firebase.md
Labels: release:docs, skip-cherry-pick

#6712 Update Clerk docs
  docs/docs/auth/clerk.md
Labels: release:docs, skip-cherry-pick

#6739 fix(Supabase): Set Supabase webPackage to 1.35.7 (from main)
  packages/auth-providers-setup/src/supabase/setup.ts
Labels: release:fix

#6743 supabase auth setup: Add missing rw packages
  packages/auth-providers-setup/src/supabase/setup.ts
Labels: release:fix, skip-cherry-pick

#6740 Missing packages for Ethereum auth setup
  packages/auth-providers-setup/src/ethereum/setup.ts
Labels: release:fix, skip-cherry-pick

#6685 Update Clerk import in decoder
  packages/auth-providers-api/src/clerk/decoder.ts
Labels: topic/auth, release:fix

#6744 supertokens setup auth: Add missing RW packages
  packages/auth-providers-setup/src/supertokens/setup.ts
Labels: release:fix, skip-cherry-pick

#6741 Add missing packages to magicLink setup
  packages/auth-providers-setup/src/magicLink/setup.ts
Labels: release:fix, skip-cherry-pick

#6742 nhost auth setup: Add missing packages
  packages/auth-providers-setup/src/nhost/setup.ts
Labels: release:fix, skip-cherry-pick

#6734 Auth0 setup: Install correct packages
  packages/auth-providers-setup/src/auth0/setup.ts
Labels: release:fix, skip-cherry-pick

#6733 Setup auth: Update goTrue
  packages/auth-providers-setup/src/goTrue/setup.ts
Labels: release:fix, skip-cherry-pick

#6736 Azure setup auth: Install and import all needed packages
  packages/auth-providers-setup/src/azureActiveDirectory/setup.ts
Labels: release:fix, skip-cherry-pick

#6745 [Chore]: tweak release script for publishing from the next branch
  tasks/release/release.mjs
Labels: release:chore

#6746 Update auth setup warning message
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:chore, fixture-ok, skip-cherry-pick

#6748 Update Netlify auth docs
  docs/docs/auth/netlify.md
Labels: release:docs

#6749 Update auth docs to not import global context
  docs/docs/authentication.md
  docs/versioned_docs/version-3.2/authentication.md
Labels: release:docs

#6465 [Tutorial] Adds api-side usage of currentUser
  docs/docs/tutorial/chapter5/first-story.md
  docs/docs/tutorial/chapter5/first-test.md
  docs/docs/tutorial/chapter5/testing.md
  docs/docs/tutorial/chapter6/comment-form.md
  docs/docs/tutorial/chapter6/comments-schema.md
  docs/docs/tutorial/chapter6/multiple-comments.md
  docs/docs/tutorial/chapter6/the-redwood-way.md
  docs/docs/tutorial/chapter7/api-side-currentuser.md
  docs/docs/tutorial/chapter7/rbac.md
  docs/sidebars.js
Labels: release:docs

#5957 fix: handle Storybook `webpackFinal` merging separately
  packages/testing/config/storybook/main.js
Labels: topic/config, topic/storybook, release:fix

#6754 Backports tutorial updates to versioned docs 3.1 and 3.2
  docs/versioned_docs/version-3.1/tutorial/chapter2/routing-params.md
  docs/versioned_docs/version-3.1/tutorial/chapter5/first-story.md
  docs/versioned_docs/version-3.1/tutorial/chapter5/first-test.md
  docs/versioned_docs/version-3.1/tutorial/chapter5/testing.md
  docs/versioned_docs/version-3.1/tutorial/chapter6/comment-form.md
  docs/versioned_docs/version-3.1/tutorial/chapter6/comments-schema.md
  docs/versioned_docs/version-3.1/tutorial/chapter6/multiple-comments.md
  docs/versioned_docs/version-3.1/tutorial/chapter6/the-redwood-way.md
  docs/versioned_docs/version-3.1/tutorial/chapter7/api-side-currentuser.md
  docs/versioned_docs/version-3.1/tutorial/chapter7/rbac.md
  docs/versioned_docs/version-3.2/tutorial/chapter5/first-story.md
  docs/versioned_docs/version-3.2/tutorial/chapter5/first-test.md
  docs/versioned_docs/version-3.2/tutorial/chapter5/testing.md
  docs/versioned_docs/version-3.2/tutorial/chapter6/comment-form.md
  docs/versioned_docs/version-3.2/tutorial/chapter6/comments-schema.md
  docs/versioned_docs/version-3.2/tutorial/chapter6/multiple-comments.md
  docs/versioned_docs/version-3.2/tutorial/chapter6/the-redwood-way.md
  docs/versioned_docs/version-3.2/tutorial/chapter7/api-side-currentuser.md
  docs/versioned_docs/version-3.2/tutorial/chapter7/rbac.md
Labels: release:docs

#6764 Fix auth0 decoder import
  packages/auth-providers-setup/src/auth0/setup.ts
Labels: release:fix

#6766 fix(api-server): Fixes issue using fastify compress plugin
  packages/api-server/src/requestHandlers/awsLambdaFastify.ts
Labels: release:fix

#6769 Fix dbAuth webAuthn template (redundant type import)
  packages/auth-providers-setup/src/dbAuth/templates/api/functions/auth.webAuthn.ts.template
Labels: release:fix
