Repository redwoodjs/graphql, pull requests merged in 2022-01, with the labels that each got.

#4020 Redwood GraphQL Logger better handles results and errors in parse, validate, and context building phases
  packages/api-server/src/logFormatter/index.ts
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/plugins/useRedwoodLogger.ts
Labels: release:fix, release:feature

#3985 Log error messages on GraphQL parse and validation
  packages/api-server/package.json
  packages/graphql-server/src/plugins/__fixtures__/common.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodLogger.test.ts
  packages/graphql-server/src/plugins/useRedwoodLogger.ts
  yarn.lock
Labels: triage/processing, release:feature

#4048 Remove extra colon
  .github/workflows/require-PR-label.yaml
Labels: topic/ops-&-contributing-dx, release:fix

#4047 Populate global.location when prerendering
  packages/prerender/src/internal.ts
  packages/prerender/src/runPrerender.tsx
Labels: topic/prerender, v1/for-consideration, release:fix

#4055 fix(babel-check): Scope glob for babelrc check
  packages/cli/src/middleware/checkForBabelConfig.js
Labels: bug/confirmed, release:fix

#4053 Support and format custom GraphQL Scalar validation error messages
  packages/graphql-server/src/functions/graphql.ts
Labels: topic/graphql, v1/priority, release:fix

#4061 fix(setup): Fix handling of nested setup commands
  packages/cli/src/commands/setup.js
  packages/cli/src/commands/setup/ui/libraries/chakra-ui.js
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
  packages/cli/src/commands/setup/ui/ui.js
Labels: topic/cli, topic/windows, v1/priority, release:fix

#4035 Adds Support for BigInts in GraphQL SDL, Schema, Type Generation, and Tests + Scenarios (Scaffolding)
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/service/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/service/__tests__/scenario.test.js
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/generate/service/templates/scenarios.ts.template
  packages/cli/src/commands/generate/service/templates/test.ts.template
  packages/graphql-server/src/rootSchema.ts
  packages/internal/src/generate/graphqlSchema.ts
  packages/internal/src/generate/typeDefinitions.ts
Labels: topic/graphql, v1/priority, release:feature

#4023 Add stream to resolve fallback polyfill config fixed (#4022)
  packages/testing/config/storybook/main.js
Labels: release:chore

#4068 Update Storybook Config per PR #3515
  packages/testing/config/storybook/main.js
Labels: release:chore

#4019 Re-add missing config for shared types
  packages/create-redwood-app/template/api/tsconfig.json
  packages/create-redwood-app/template/web/tsconfig.json
Labels: topic/typescript, v1/priority, release:fix

#4073 Revert webpack-dev-server upgrade
  packages/core/package.json
  yarn.lock
Labels: topic/ops-&-contributing-dx, release:chore

#4082 Try fixing e2e network flakiness
  .github/workflows/e2e.yaml
Labels: topic/ops-&-contributing-dx, v1/priority, release:chore

#4057 Ignore pascalcase
  .github/renovate.json
Labels: topic/ops-&-contributing-dx, release:chore

#4089 added exports to form-component props
  packages/forms/src/index.tsx
Labels: release:fix

#4080 Upgrade webpack dev server
  packages/core/package.json
  yarn.lock
Labels: release:chore

#4083 Add missing type for `only` in scenario
  packages/testing/src/api/scenario.ts
Labels: topic/testing, topic/typescript, release:fix

#4107 [CI] Configure cy wait until
  tasks/e2e/cypress/integration/01-tutorial/sharedTests.js
Labels: topic/ops-&-contributing-dx, release:chore

#4122 Remove license from create-redwood-app templates
  packages/create-redwood-app/template/LICENSE
Labels: triage/processing, release:chore

#3981 Adds SuperTokens integration + fix to multiHeaderValue
  packages/api-server/src/requestHandlers/awsLambdaFastify.ts
  packages/api/package.json
  packages/api/src/auth/decoders/index.ts
  packages/api/src/auth/decoders/supertokens.ts
  packages/auth/package.json
  packages/auth/src/authClients/index.ts
  packages/auth/src/authClients/supertokens.ts
  yarn.lock
Labels: topic/auth, v1/for-consideration, release:feature

#4134 replace vscode-ripgrep with @vscode/ripgrep
  packages/codemods/package.json
  packages/codemods/src/lib/getFilesWithPattern.ts
  yarn.lock
Labels: release:chore

#4084 fix: running tests with mysql datasource
  packages/testing/config/jest/api/jest.setup.js
Labels: triage/processing, release:fix

#4143 chore: test-project workaround for tailwind PostCSS error
  tasks/test-project/tasks.js
Labels: release:chore

#4065 chore(setup-deploy): refactor setup deploy
  packages/cli/src/commands/deploy/aws-providers/serverless.js
  packages/cli/src/commands/deploy/aws.js
  packages/cli/src/commands/deploy/packing/nft.js
  packages/cli/src/commands/setup/deploy/deploy.js
  packages/cli/src/commands/setup/deploy/helpers/index.js
  packages/cli/src/commands/setup/deploy/providers/aws-serverless.js
  packages/cli/src/commands/setup/deploy/providers/netlify.js
  packages/cli/src/commands/setup/deploy/providers/render.js
  packages/cli/src/commands/setup/deploy/providers/vercel.js
  packages/cli/src/commands/setup/deploy/templates/netlify.js
  packages/cli/src/commands/setup/deploy/templates/render.js
  packages/cli/src/commands/setup/deploy/templates/serverless.js
Labels: triage/processing, release:feature

#4155 Update Issue and PR templates with v1-rc status
  .github/issue_template.md
  .github/pull_request_template.md
Labels: release:chore

#4024 Fix: Run web tests in parallel
  packages/cli/src/commands/__tests__/test.test.js
  packages/cli/src/commands/test.js
  packages/internal/src/build/babel/api.ts
  packages/testing/config/jest/api/apiBabelConfig.js
  packages/testing/config/jest/api/index.js
  packages/testing/config/jest/jest-serial-runner.js
  packages/testing/config/jest/web/RedwoodWebJestEnv.js
  packages/testing/config/jest/web/index.js
  packages/testing/config/jest/web/webBabelConfig.js
Labels: topic/testing, release:fix

#4166 Don't mask GraphQL errors when you're in the dev environment
  packages/graphql-server/src/functions/graphql.ts
Labels: triage/processing, release:chore

#4171 Remove projects beta automation
  .github/workflows/projects_beta_automation.yml
Labels: release:chore

#4086 Refactor `rw type-check`
  packages/cli/package.json
  packages/cli/src/commands/__tests__/type-check.test.js
  packages/cli/src/commands/dev.js
  packages/cli/src/commands/type-check.js
  yarn.lock
Labels: topic/cli, release:fix

#4176 chore: add PropTypes
  packages/forms/src/index.tsx
Labels: topic/forms, release:fix

#4190 fix(generator): Fix incorrect TS page param type on scaffold
  packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap
  packages/cli/src/commands/generate/page/__tests__/page.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/pages/NamePage.tsx.template
Labels: release:fix

#4157 Support generation of typescript dataMigrations
  packages/cli/src/commands/dataMigrate/up.js
  packages/cli/src/commands/generate/dataMigration/__tests__/__snapshots__/dataMigration.test.js.snap
  packages/cli/src/commands/generate/dataMigration/__tests__/dataMigration.test.js
  packages/cli/src/commands/generate/dataMigration/__tests__/fixtures/dataMigration.js
  packages/cli/src/commands/generate/dataMigration/dataMigration.js
  packages/cli/src/commands/generate/dataMigration/templates/dataMigration.js.template
  packages/cli/src/commands/generate/dataMigration/templates/dataMigration.ts.template
Labels: topic/typescript, v1/priority, release:chore

#4196 Revert "Don't mask GraphQL errors when you're in the dev environment"
  packages/graphql-server/src/functions/graphql.ts
Labels: release:chore

#4161 fix: Update clerk-js to latest version
  packages/auth/package.json
  packages/auth/src/authClients/clerk.ts
  yarn.lock
Labels: release:chore

#4203 chore: remove crwa unused dependencies
  packages/create-redwood-app/package.json
  yarn.lock
Labels: release:chore

#4165 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release:chore

#4180 Test-Project: Update cell query names and add codemod for mocks
  tasks/test-project/codemods/blogPost.js
  tasks/test-project/codemods/blogPostCell.js
  tasks/test-project/codemods/blogPostsCell.js
  tasks/test-project/codemods/contactPage.js
  tasks/test-project/codemods/updateBlogPostMocks.js
  tasks/test-project/tasks.js
  tasks/test-project/util.js
Labels: release:chore

#3013 Telemetry
  .eslintrc.js
  .github/workflows/telemetry-benchmarks.yaml
  .gitpod.yml
  packages/auth/src/authClients/clerk.ts
  packages/cli/package.json
  packages/cli/src/commands/__tests__/type-check.test.js
  packages/cli/src/commands/build.js
  packages/cli/src/commands/dataMigrate/install.js
  packages/cli/src/commands/dataMigrate/up.js
  packages/cli/src/commands/dev.js
  packages/cli/src/commands/generate/function/__tests__/function.test.ts
  packages/cli/src/commands/generate/function/function.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/script/script.js
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/prerender.js
  packages/cli/src/commands/prisma.js
  packages/cli/src/commands/setup/auth/__tests__/addAuthConfigToApp.test.js
  packages/cli/src/commands/setup/auth/__tests__/authHandler.test.js
  packages/cli/src/commands/setup/auth/auth.js
  packages/cli/src/commands/setup/custom-web-index/custom-web-index.js
  packages/cli/src/commands/setup/deploy/providers/aws-serverless.js
  packages/cli/src/commands/setup/deploy/providers/netlify.js
  packages/cli/src/commands/setup/deploy/providers/render.js
  packages/cli/src/commands/setup/deploy/providers/vercel.js
  packages/cli/src/commands/setup/i18n/i18n.js
  packages/cli/src/commands/setup/tsconfig/tsconfig.js
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
  packages/cli/src/commands/setup/webpack/webpack.js
  packages/cli/src/commands/test.js
  packages/cli/src/commands/type-check.js
  packages/cli/src/commands/upgrade.js
  packages/cli/src/index.js
  packages/cli/src/lib/mockTelemetry.js
  packages/cli/src/lib/test.js
  packages/create-redwood-app/package.json
  packages/create-redwood-app/src/create-redwood-app.js
  packages/create-redwood-app/src/telemetry.js
  packages/internal/package.json
  packages/telemetry/.babelrc.js
  packages/telemetry/README.md
  packages/telemetry/package.json
  packages/telemetry/src/__tests__/sendTelemetry.test.js
  packages/telemetry/src/index.js
  packages/telemetry/src/scripts/invoke.ts
  packages/telemetry/src/sendTelemetry.ts
  packages/telemetry/src/telemetry.ts
  tasks/run-e2e
  yarn.lock
Labels: v1/priority, release:feature

#4212 Update release notes script
  tasks/release-notes/release-notes.mjs
Labels: release:chore

#4204 Add path param array to `rw lint [path]`
  packages/cli/src/commands/lint.js
Labels: release:feature

#4216 Update yarn lock post release
  yarn.lock
Labels: release:chore

#4215 [Release notes] Only use list items for renovate
  tasks/release-notes/release-notes.mjs
Labels: release:chore

#4228 [Renovate] Rearrange config, ignore redwoodjs packages
  .github/renovate.json
Labels: release:chore

#4169 Added Decimal field type to Scaffold
  packages/cli/src/commands/generate/scaffold/scaffold.js
Labels: release:feature

#4226 Adds test from a BigInt scaffold Form input element
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma
Labels: topic/generators-&-scaffolds, topic/testing, release:fix

#4230 Adds Test for Prisma Decimal type with Form Inputs when Scaffolding
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma
Labels: topic/prisma, topic/generators-&-scaffolds, release:chore

#4242 resolve yarn doctor issues
  packages/api-server/package.json
  packages/api/package.json
  packages/auth/package.json
  packages/cli/package.json
  packages/create-redwood-app/package.json
  packages/forms/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/prerender/package.json
  packages/record/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/telemetry/package.json
  packages/testing/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore

#4219 Fix type definitions for page components that take props
  packages/router/src/router.tsx
Labels: topic/router, release:fix

#3515 Add storybook ci option to test that Storybook starts "ok"
  .github/workflows/e2e.yaml
  packages/cli/src/commands/storybook.js
  packages/core/config/webpack.common.js
  packages/testing/config/storybook/main.js
  tasks/e2e/cypress/integration/03-storybook/storybook.spec.js
Labels: topic/storybook, v1/priority, release:chore

#4247 Fixed netlify api config
  packages/cli/src/commands/setup/deploy/providers/netlify.js
Labels: topic/deployment, release:fix

#4258 Update scripts tsconfig
  packages/create-redwood-app/template/scripts/tsconfig.json
Labels: topic/typescript, v1/for-consideration, release:fix

#4164 Type fix for `mockGraphQL` data argument
  packages/testing/src/web/mockRequests.ts
Labels: topic/testing, v1/priority, release:fix

#4281 fix(telemetry): Safely lookup shell for windows
  packages/telemetry/src/sendTelemetry.ts
Labels: release:fix

#4265 Updates scaffold templates to handle null DateTime values
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/components/Name.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/Names.tsx.template
Labels: release:fix

#4286 (chore) upgrade node-fetch 2.6.7 (security)
  packages/codemods/package.json
  packages/graphql-server/package.json
  packages/prerender/package.json
  packages/telemetry/package.json
  yarn.lock
Labels: release:chore

#4285 Update release tooling
  package.json
  tasks/release/__tests__/__snapshots__/generateReleaseNotes.test.mjs.snap
  tasks/release/__tests__/generateReleaseNotes.test.mjs
  tasks/release/__tests__/updateNextReleasePullRequestsMilestone.test.mjs
  tasks/release/cli.mjs
  tasks/release/generateReleaseNotes.mjs
  tasks/release/jest.config.mjs
  tasks/release/jest.setup.mjs
  tasks/release/octokit.mjs
  tasks/release/prompts.mjs
  tasks/release/release.mjs
  tasks/release/updateNextReleasePullRequestsMilestone.mjs
  yarn.lock
Labels: release:chore

#4261 Dedupe generator postfix
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/component/__tests__/component.test.ts
  packages/cli/src/commands/generate/directive/__tests__/directive.test.ts
  packages/cli/src/commands/generate/function/__tests__/function.test.ts
  packages/cli/src/commands/generate/function/function.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/layout/__tests__/layout.test.ts
  packages/cli/src/commands/generate/layout/layout.js
  packages/cli/src/commands/generate/page/__tests__/page.test.js
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/script/__tests__/script.test.ts
  packages/cli/src/commands/generate/service/__tests__/service.test.js
Labels: release:feature

#4298 Scaffold: Fix deserialize spelling
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/components/NameForm.tsx.template
Labels: release:chore

#4299 Scaffold: Enable all tests again and update snapshots
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
Labels: release:chore

#4305 Update release script
  tasks/release/__tests__/release.test.mjs
  tasks/release/__tests__/updateNextReleasePullRequestsMilestone.test.mjs
  tasks/release/prompts.mjs
  tasks/release/release.mjs
  tasks/release/updateNextReleasePullRequestsMilestone.mjs
Labels: release:chore

#4312 Tweak release script
  tasks/release/prompts.mjs
  tasks/release/release.mjs
Labels: release:chore

#4310 Add missing deps to @redwoodjs/forms package.json
  packages/forms/jest.config.js
  packages/forms/package.json
  yarn.lock
Labels: release:chore

#4313 Fix telemetry showing Node version for Yarn and npm
  packages/telemetry/src/sendTelemetry.ts
Labels: bug/confirmed, release:fix
