Repository redwoodjs/graphql, pull requests merged in 2022-03, with the labels that each got.

#4541 Tailwind: Generate prettier-approved code
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
Labels: release:fix

#4604 fixi(prisma): Set default cwd for runCommand task to base
  packages/cli/src/lib/index.js
Labels: release:fix

#4398 Revamp Readme for 1.0
  README.md
Labels: release:chore

#4590 remove --schema option from `rw prisma migrate diff`
  packages/cli/src/commands/prisma.js
Labels: next-release/update-docs, release:fix

#4626 part II of #4623
  __fixtures__/test-project/api/db/migrations/20220302044927_create_product/migration.sql
  __fixtures__/test-project/api/db/migrations/20220302044942_create_contact/migration.sql
  __fixtures__/test-project/api/db/migrations/20220302045019_db_auth/migration.sql
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/src/index.css
  tasks/test-project/tasks.js
Labels: release:chore

#4619 Add custom log payload support to logFormatter
  packages/api-server/package.json
  packages/api-server/src/__tests__/logFormatter.test.ts
  packages/api-server/src/logFormatter/index.ts
Labels: next-release/update-docs, release:chore

#4608 Webhook verifiers: Make them all support timestamp diff check
  packages/api/src/auth/verifiers/__tests__/timestampSchemeVerifier.test.ts
  packages/api/src/auth/verifiers/common.ts
  packages/api/src/auth/verifiers/timestampSchemeVerifier.ts
  packages/api/src/webhooks/index.ts
  packages/api/src/webhooks/webhooks.test.ts
Labels: next-release/update-docs, next-release/code-mod, release:feature

#4444 [WIP] Enable yarn 3 for Redwood projects
  package.json
  packages/api/package.json
  packages/api/src/bins/redwood.ts
  packages/api/src/bins/rwfw.ts
  packages/api/src/bins/tsc.ts
  packages/cli/src/commands/__tests__/type-check.test.js
  packages/cli/src/commands/build.js
  packages/cli/src/commands/setup/deploy/helpers/index.js
  packages/cli/src/commands/setup/deploy/providers/serverless.js
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
  packages/cli/src/commands/type-check.js
  packages/cli/src/commands/upgrade.js
  packages/cli/src/lib/generatePrismaClient.js
  packages/cli/src/rwfw.js
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/README.md
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/__testfixtures__/default/input/.gitignore
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/__testfixtures__/default/input/.keep
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/__testfixtures__/default/input/package.json
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/__testfixtures__/default/output/.gitignore
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/__testfixtures__/default/output/.keep
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/__testfixtures__/default/output/.yarnrc.yml
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/__testfixtures__/default/output/package.json
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/upgradeYarn.ts
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/upgradeYarn.yargs.ts
  packages/core/.babelrc.js
  packages/core/package.json
  packages/core/src/bins/cross-env.ts
  packages/core/src/bins/eslint.ts
  packages/core/src/bins/jest.ts
  packages/core/src/bins/nodemon.ts
  packages/core/src/bins/redwood.ts
  packages/core/src/bins/rimraf.ts
  packages/core/src/bins/rw-api-server-watch.ts
  packages/core/src/bins/rw-gen-watch.ts
  packages/core/src/bins/rw-gen.ts
  packages/core/src/bins/rwfw.ts
  packages/internal/src/generate/generate.ts
  packages/web/package.json
  packages/web/src/bins/build-storybook.ts
  packages/web/src/bins/cross-env.ts
  packages/web/src/bins/msw.ts
  packages/web/src/bins/redwood.ts
  packages/web/src/bins/rwfw.ts
  packages/web/src/bins/start-storybook.ts
  packages/web/src/bins/tsc.ts
  packages/web/src/bins/webpack.ts
  tasks/framework-tools/frameworkDepsToYarn3Project.mjs
  tasks/framework-tools/lib/project.mjs
  tasks/run-e2e
  yarn.lock
Labels: topic/create-redwood-app, v1/for-consideration, release:feature

#4612 updates the release script used to bump package versions
  tasks/update-package-versions
Labels: release:chore

#4645 [Codemod] Handle node versions that don't bundle corepack
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/upgradeYarn.ts
Labels: release:chore

#4638 [CI] E2E wait for server start and Test move `setTimeout` outside test block
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__tests__/updateJestConfig.test.ts
  tasks/e2e/cypress/integration/01-tutorial/tutorial.spec.js
Labels: release:chore

#4637 Remove yarn 3 project deps script
  package.json
  tasks/framework-tools/frameworkDepsToYarn3Project.mjs
  tasks/run-e2e
Labels: release:chore

#4658 jscodeshift and webhook verifier doc updates
  packages/api/src/auth/verifiers/common.ts
  packages/codemods/README.md
Labels: release:fix

#4659 Mod upgrade yarn codemod to handle CI
  .github/workflows/e2e.yaml
  tasks/run-e2e
Labels: release:chore

#4662 Make upgrade-yarn codemod more robust by preparing yarn version
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/upgradeYarn.ts
Labels: release:fix

#4671 Clear up dev log in error page
  packages/web/src/components/DevFatalErrorPage.tsx
Labels: topic/web, release:fix

#4675 Codemod for webhook verifier option renaming
  packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/README.md
  packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/__testfixtures__/simple.input.js
  packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/__testfixtures__/simple.output.js
  packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/__tests__/renameVerifierTimestamp.test.ts
  packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/renameVerifierTimestamp.ts
  packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/renameVerifierTimestamp.yargs.ts
Labels: release:feature

#4695 [Yarn 3] Add bin proxy for rw-log-formatter
  packages/core/package.json
  packages/core/src/bins/rw-log-formatter.ts
  yarn.lock
Labels: release:fix

#4699 fix storybook DX by removing default type check config
  packages/testing/config/storybook/main.js
Labels: release:fix

#4700 Allow the number 0 for numericality validation values
  packages/api/src/validations/__tests__/validations.test.js
  packages/api/src/validations/validations.ts
Labels: release:fix

#4674 Fix react/prop-types lint warnings
  packages/router/src/router.tsx
  packages/router/src/splash-page.tsx
Labels: topic/router, release:fix

#4678 fix(auth): hasRole handles when currentUser.roles is a string
  __fixtures__/test-project/.vscode/extensions.json
  __fixtures__/test-project/api/db/migrations/20220309090011_create_product/migration.sql
  __fixtures__/test-project/api/db/migrations/20220309090020_create_contact/migration.sql
  __fixtures__/test-project/api/db/migrations/20220309090044_db_auth/migration.sql
  __fixtures__/test-project/api/src/functions/auth.ts
  __fixtures__/test-project/api/src/lib/auth.ts
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/cli/src/commands/setup/auth/templates/auth.ts.template
  packages/cli/src/commands/setup/auth/templates/auth0.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/azureActiveDirectory.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/clerk.auth.js.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
  tasks/test-project/tasks.js
Labels: release:fix

#4715 Remove supertokens-node from packages/api dependencies
  packages/api/package.json
  yarn.lock
Labels: release:chore

#4696 Pretty print query in DevFatalErrorPage for better DX and readability
  packages/create-redwood-app/template/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  packages/web/src/apollo/index.tsx
  packages/web/src/components/DevFatalErrorPage.tsx
  packages/web/src/index.ts
Labels: release:chore

#4723 Fix failing codemod test for RedwoodDevFatalErrorPage
  packages/codemods/src/codemods/v47.x/updateDevFatalErrorPage/__testfixtures__/default/output/web/src/pages/FatalErrorPage/FatalErrorPage.js
Labels: release:fix

#4704 allow Redirect to use navigate options.replace
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/links.tsx
Labels: next-release/update-docs, release:feature

#4738 useRequireAuth: Refactor to make it easier to read
  packages/api/src/auth/index.ts
  packages/graphql-server/src/functions/useRequireAuth.ts
Labels: release:chore

#4736 Serverles api template: Fix spelling
  packages/cli/src/commands/setup/deploy/templates/serverless/api.js
Labels: release:fix

#4734 jwtVerifier: Remove unreachable code
  packages/api/src/auth/verifiers/jwtVerifier.ts
Labels: release:chore

#4737 graphql-server types: Fix/format jsdocs
  packages/graphql-server/src/functions/types.ts
Labels: release:fix

#4744 Send a 'ready' message to parent process if api server was spawned
  packages/api-server/src/cliHandlers.ts
Labels: topic/api, release:feature

#4759 [Renovate] Ignore @types/lru-cache
  .github/renovate.json
Labels: release:chore

#4722 Sets Secure cookie attribute in config template to be dependent on NODE_ENV
  packages/cli/src/commands/setup/auth/templates/dbAuth.function.ts.template
Labels: topic/auth, next-release/update-docs, next-release/code-mod, release:fix

#4673 Auth smoke tests
  __fixtures__/test-project/api/db/migrations/20220315214705_create_product/migration.sql
  __fixtures__/test-project/api/db/migrations/20220315214719_create_contact/migration.sql
  __fixtures__/test-project/api/db/migrations/20220315214751_db_auth/migration.sql
  __fixtures__/test-project/api/src/directives/requireAuth/requireAuth.test.ts
  __fixtures__/test-project/api/src/functions/auth.ts
  __fixtures__/test-project/api/src/graphql/contacts.sdl.ts
  __fixtures__/test-project/api/src/lib/auth.ts
  __fixtures__/test-project/api/src/services/contacts/contacts.test.ts
  __fixtures__/test-project/api/src/services/contacts/contacts.ts
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/src/Routes.tsx
  __fixtures__/test-project/web/src/components/Contact/Contact/Contact.tsx
  __fixtures__/test-project/web/src/components/Contact/ContactCell/ContactCell.tsx
  __fixtures__/test-project/web/src/components/Contact/ContactForm/ContactForm.tsx
  __fixtures__/test-project/web/src/components/Contact/Contacts/Contacts.tsx
  __fixtures__/test-project/web/src/components/Contact/ContactsCell/ContactsCell.tsx
  __fixtures__/test-project/web/src/components/Contact/EditContactCell/EditContactCell.tsx
  __fixtures__/test-project/web/src/components/Contact/NewContact/NewContact.tsx
  __fixtures__/test-project/web/src/layouts/ContactsLayout/ContactsLayout.tsx
  __fixtures__/test-project/web/src/pages/Contact/ContactPage/ContactPage.tsx
  __fixtures__/test-project/web/src/pages/Contact/ContactsPage/ContactsPage.tsx
  __fixtures__/test-project/web/src/pages/Contact/EditContactPage/EditContactPage.tsx
  __fixtures__/test-project/web/src/pages/Contact/NewContactPage/NewContactPage.tsx
  __fixtures__/test-project/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  __fixtures__/test-project/web/src/pages/ProfilePage/ProfilePage.stories.tsx
  __fixtures__/test-project/web/src/pages/ProfilePage/ProfilePage.test.tsx
  __fixtures__/test-project/web/src/pages/ProfilePage/ProfilePage.tsx
  tasks/smoke-test/playwright-fixtures/devServer.fixture.ts
  tasks/smoke-test/playwright-fixtures/rwServe.fixture.ts
  tasks/smoke-test/playwright.config.ts
  tasks/smoke-test/tests/authChecks.spec.ts
  tasks/smoke-test/tests/common.ts
  tasks/smoke-test/tests/rbacChecks.spec.ts
  tasks/smoke-test/util.ts
  tasks/test-project/codemods/profilePage.js
  tasks/test-project/codemods/routes.js
  tasks/test-project/tasks.js
  tasks/test-project/test-project
Labels: release:chore

#4634 Update minor node version engine requirement to 14.19
  packages/create-redwood-app/template/package.json
Labels: topic/create-redwood-app, release:feature-breaking, next-release/code-mod

#4771 (docs) update link to Tutorial forms section
  packages/forms/src/index.tsx
Labels: release:chore

#4681 Update private routes and Set to use roles vs role
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/router/src/Set.tsx
  packages/router/src/__tests__/router.test.tsx
Labels: release:feature-breaking

#4770 Auth Provider: Update Nhost to V2
  packages/auth/package.json
  packages/auth/src/authClients/nhost.ts
  packages/cli/src/commands/setup/auth/__tests__/__snapshots__/addAuthConfigToApp.test.js.snap
  packages/cli/src/commands/setup/auth/providers/nhost.js
  yarn.lock
Labels: next-release/update-docs, next-release/code-mod, release:feature

#4760 feat: only wrap affected resolver functions by using the 'onSchemaChange' hook with 'mapSchema' instead of the 'onResolverCalled' hook.
  packages/graphql-server/src/plugins/useRedwoodDirective.ts
Labels: release:fix

#4618 Fix: netlify build with rw record
  packages/record/package.json
  packages/record/src/redwoodrecord/__fixtures__/datamodel.js
  packages/record/src/redwoodrecord/__tests__/Core.test.js
  packages/record/src/redwoodrecord/__tests__/RedwoodRecord.test.js
  packages/record/src/redwoodrecord/__tests__/Reflection.test.js
  packages/record/src/redwoodrecord/__tests__/RelationProxy.test.js
  packages/record/src/redwoodrecord/__tests__/datamodel.json
  packages/record/src/tasks/parse.js
  yarn.lock
Labels: release:fix

#4756 Service Validations - Adds error message for FormError fields
  packages/api/src/errors.ts
  packages/api/src/validations/__tests__/validations.test.js
  packages/api/src/validations/errors.ts
  packages/api/src/validations/validations.ts
  packages/record/src/redwoodrecord/__tests__/RedwoodRecord.test.js
  packages/record/src/redwoodrecord/__tests__/Validation.test.js
Labels: release:fix

#4750 Adds baremetal deploy strategy
  packages/cli/package.json
  packages/cli/src/commands/deploy/baremetal.js
  packages/cli/src/commands/setup/deploy/providers/baremetal.js
  packages/cli/src/commands/setup/deploy/templates/baremetal.js
  yarn.lock
Labels: topic/deployment, release:feature

#4669 Catch getToken error and set token to null
  packages/auth/src/AuthProvider.tsx
  packages/auth/src/__tests__/AuthProvider.test.tsx
Labels: topic/auth, v1/priority, release:fix

#4791 Chore: Change yarn cache key, to bust invalid cache
  .github/workflows/build-eslint-jest.yaml
  .github/workflows/e2e.yaml
  .github/workflows/publish-npm-canary.yaml
  .github/workflows/smoke-test.yaml
Labels: release:chore

#4790 Reorg codemod for dev fatal error page
  packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/README.md
  packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/__testfixtures__/default/input/web/src/pages/FatalErrorPage/FatalErrorPage.js
  packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/__testfixtures__/default/output/web/src/pages/FatalErrorPage/FatalErrorPage.js
  packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/__tests__/updateDevFatalErrorPage.test.ts
  packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/updateDevFatalErrorPage.ts
  packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/updateDevFatalErrorPage.yargs.ts
Labels: release:chore

#4680 Allow requireAuth directive to be used with a string or array of strings
  __fixtures__/example-todo-main-with-errors/api/src/graphql/todosMutations.sdl.js
  __fixtures__/example-todo-main-with-errors/api/src/graphql/todosWithAuthInvalidRolesErrors.sdl.js
  __fixtures__/example-todo-main-with-errors/api/src/graphql/todosWithAuthMissingRoleError.sdl.js
  __fixtures__/example-todo-main-with-errors/api/src/graphql/todosWithAuthRoles.sdl.js
  __fixtures__/example-todo-main-with-errors/api/src/graphql/todosWithBuiltInDirectives.sdl.js
  __fixtures__/example-todo-main-with-errors/api/src/graphql/todosWithMissingAuthRolesAttributeError.sdl.js
  __fixtures__/example-todo-main-with-errors/api/src/graphql/todosWithMissingAuthRolesAttributeNumericError.sdl.js
  __fixtures__/example-todo-main-with-errors/api/src/graphql/todosWithNumericRoleAuthError.sdl.js
  __fixtures__/example-todo-main-with-errors/api/src/services/todos/todos.js
  docs/docs/authentication.md
  docs/docs/cookbook/role-based-access-control.md
  packages/cli/src/commands/setup/auth/templates/auth.ts.template
  packages/cli/src/commands/setup/auth/templates/auth0.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/azureActiveDirectory.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/clerk.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/firebase.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/magicLink.auth.js.template
  packages/internal/src/__tests__/validateSchema.test.ts
  packages/internal/src/__tests__/validateSchemaForAuthDirectives.test.ts
  packages/internal/src/__tests__/validateSchemaWithErrors.test.ts
  packages/internal/src/validateSchema.ts
Labels: next-release/update-docs, release:fix

#4792 Service Validations: Returns error message as an array in faked extensions
  packages/api/package.json
  packages/api/src/validations/errors.ts
  packages/forms/src/FormError.tsx
  yarn.lock
Labels: topic/forms, topic/services, release:fix

#4782 Always generate 200.html as part of web build | Change
  packages/cli/src/commands/build.js
  packages/cli/src/commands/prerender.js
  packages/cli/src/commands/setup/deploy/templates/netlify.js
  packages/prerender/src/internal.ts
  packages/prerender/src/runPrerender.tsx
Labels: next-release/code-mod, release:fix

#4787 Documents how to regenerate just SDL
  docs/docs/cli-commands.md
Labels: next-release/update-docs, release:chore

#4806 Reverse logic in smoke test for setting yarn 1
  .github/workflows/build-eslint-jest.yaml
  tasks/test-project/test-project
Labels: release:fix

#4816 Consider not running CI on changes to docs
  .github/workflows/build-eslint-jest.yaml
  .github/workflows/e2e.yaml
  .github/workflows/smoke-test.yaml
Labels: release:chore

#4819 Copy content and fixes from redwoodjs.com
  docs/docs/cells.md
  docs/docs/cli-commands.md
  docs/docs/router.md
Labels: topic/docs, release:chore

#4810 Copy fix from learn PR #198
  docs/docs/tutorial/side-quest-how-redwood-works-with-data.md
Labels: topic/docs, release:fix

#4809 Copy fix from learn PR #207
  docs/docs/tutorial/saving-data.md
Labels: topic/docs, release:fix

#4807 Copy fix from learn PR #217
  docs/docs/tutorial/cells.md
Labels: topic/docs, release:fix

#4804 Copy fix from learn PR #221
  docs/docs/tutorial2/our-first-test.md
Labels: topic/docs, release:fix

#4803 Copy fix from learn PR #222
  docs/docs/tutorial2/multiple-comments.md
Labels: topic/docs, release:fix

#4781 Update links and codeblocks in tutorial
  docs/docs/tutorial/a-second-page-and-a-link.md
  docs/docs/tutorial/authentication.md
  docs/docs/tutorial/building-a-form.md
  docs/docs/tutorial/cells.md
  docs/docs/tutorial/deployment.md
  docs/docs/tutorial/getting-dynamic.md
  docs/docs/tutorial/layouts.md
  docs/docs/tutorial/our-first-page.md
  docs/docs/tutorial/prerequisites.md
  docs/docs/tutorial/redwood-file-structure.md
  docs/docs/tutorial/routing-params.md
  docs/docs/tutorial/saving-data.md
  docs/docs/tutorial/side-quest-how-redwood-works-with-data.md
  docs/docs/tutorial/wrapping-up.md
  docs/docs/tutorial2/adding-comments-to-the-schema.md
  docs/docs/tutorial2/building-a-component-the-redwood-way.md
  docs/docs/tutorial2/creating-a-comment-form.md
  docs/docs/tutorial2/introduction-to-storybook.md
  docs/docs/tutorial2/multiple-comments.md
  docs/docs/tutorial2/our-first-story.md
  docs/docs/tutorial2/our-first-test.md
  docs/docs/tutorial2/prerequisites.md
  docs/docs/tutorial2/role-based-authorization-control-rbac.md
  docs/docs/tutorial2/wrapping-up.md
Labels: topic/docs, release:chore

#4785 Generate CRUD by default for SDL and Services to mitigate issues in GraphQL used in cells
  docs/docs/cli-commands.md
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/sdl/__tests__/__snapshots__/sdl.test.js.snap
  packages/cli/src/commands/generate/sdl/__tests__/sdl.test.js
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
  packages/cli/src/commands/generate/service/__tests__/service.test.js
  packages/cli/src/commands/generate/service/service.js
Labels: next-release/update-docs, release:fix

#4761 Add yarn 3 to create redwood app template
  .github/workflows/smoke-test.yaml
  __fixtures__/test-project/.gitignore
  __fixtures__/test-project/.yarn/releases/yarn-3.2.0.cjs
  __fixtures__/test-project/.yarnrc.yml
  __fixtures__/test-project/package.json
  packages/create-redwood-app/src/create-redwood-app.js
  packages/create-redwood-app/template/.yarn/releases/yarn-3.2.0.cjs
  packages/create-redwood-app/template/.yarnrc.yml
  packages/create-redwood-app/template/gitignore.template
  packages/create-redwood-app/template/package.json
  tasks/run-e2e
  tasks/test-project/tasks.js
  tasks/test-project/test-project
Labels: release:feature

#4788 Add flightcontrol deploy command
  packages/cli/src/commands/deploy/flightcontrol.js
  packages/cli/src/commands/setup/deploy/providers/flightcontrol.js
  packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
Labels: release:feature

#4778 When mocking a cell, set the id value as a String or Number based on the type of primary key
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/cell/templates/mock.js.template
  packages/cli/src/commands/generate/cell/templates/mockList.js.template
Labels: release:fix

#4838 Fix import in tutorial
  docs/docs/tutorial2/our-first-test.md
Labels: topic/docs, release:fix

#4841 Minor tweaks to the "regenerate" docs
  docs/docs/cli-commands.md
Labels: release:chore

#4851 Update algolia config
  docs/docusaurus.config.js
Labels: release:fix

#4852 Fix URL of all tutorial path
  README.md
  docs/docs/app-configuration-redwood-toml.md
  docs/docs/authentication.md
  docs/docs/cells.md
  docs/docs/cli-commands.md
  docs/docs/contributing-walkthrough.md
  docs/docs/cookbook/file-uploads.md
  docs/docs/cookbook/gotrue-auth.md
  docs/docs/cookbook/pagination.md
  docs/docs/cookbook/role-based-access-control.md
  docs/docs/cookbook/supabase-auth.md
  docs/docs/deploy.md
  docs/docs/quick-start.md
  docs/docs/router.md
  packages/create-redwood-app/README.md
  packages/create-redwood-app/src/create-redwood-app.js
  packages/create-redwood-app/template/README.md
  packages/structure/src/outline/outline.ts
  tasks/e2e/cypress/integration/01-tutorial/sharedTests.js
  tasks/e2e/cypress/integration/01-tutorial/tutorial.spec.js
Labels: release:fix

#4859 Fix linting warnings on new gql function
  packages/graphql-server/src/functions/graphql.ts
Labels: release:fix

#4855 Reorgnize tutorial into chapters
  CONTRIBUTING.md
  docs/README.md
  docs/docs/app-configuration-redwood-toml.md
  docs/docs/authentication.md
  docs/docs/cells.md
  docs/docs/cli-commands.md
  docs/docs/cookbook/file-uploads.md
  docs/docs/cookbook/gotrue-auth.md
  docs/docs/cookbook/role-based-access-control.md
  docs/docs/cookbook/supabase-auth.md
  docs/docs/cookbook/windows-development-setup.md
  docs/docs/deploy.md
  docs/docs/quick-start.md
  docs/docs/router.md
  docs/docs/tutorial/afterword.md
  docs/docs/tutorial/chapter1/file-structure.md
  docs/docs/tutorial/chapter1/first-page.md
  docs/docs/tutorial/chapter1/installation.md
  docs/docs/tutorial/chapter1/layouts.md
  docs/docs/tutorial/chapter1/prerequisites.md
  docs/docs/tutorial/chapter1/second-page.md
  docs/docs/tutorial/chapter2/cells.md
  docs/docs/tutorial/chapter2/getting-dynamic.md
  docs/docs/tutorial/chapter2/routing-params.md
  docs/docs/tutorial/chapter2/side-quest.md
  docs/docs/tutorial/chapter3/forms.md
  docs/docs/tutorial/chapter3/saving-data.md
  docs/docs/tutorial/chapter4/authentication.md
  docs/docs/tutorial/chapter4/deployment.md
  docs/docs/tutorial/chapter5/first-story.md
  docs/docs/tutorial/chapter5/first-test.md
  docs/docs/tutorial/chapter5/storybook.md
  docs/docs/tutorial/chapter5/testing.md
  docs/docs/tutorial/chapter6/comment-form.md
  docs/docs/tutorial/chapter6/comments-schema.md
  docs/docs/tutorial/chapter6/multiple-comments.md
  docs/docs/tutorial/chapter6/the-redwood-way.md
  docs/docs/tutorial/chapter7/rbac.md
  docs/docs/tutorial/forward.md
  docs/docs/tutorial/intermission.md
  docs/docs/tutorial/wrapping-up.md
  docs/docs/tutorial2/prerequisites.md
  docs/docs/tutorial2/welcome-to-redwood-part-ii-redwoods-revenge.md
  docs/docs/tutorial2/wrapping-up.md
  docs/docusaurus.config.js
  docs/netlify.toml
  docs/sidebars.js
  packages/create-redwood-app/src/create-redwood-app.js
  packages/create-redwood-app/template/README.md
  packages/forms/src/index.tsx
  packages/router/src/splash-page.tsx
  packages/structure/src/outline/outline.ts
  tasks/e2e/cypress/integration/01-tutorial/sharedTests.js
  tasks/e2e/cypress/integration/01-tutorial/tutorial.spec.js
Labels: topic/docs, release:chore

#4843 change flightcontrol setup to use yarn v3 and change cookie config
  packages/cli/src/commands/setup/deploy/providers/flightcontrol.js
  packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
Labels: release:fix

#4864 Handle case when requestContext is undefined getting protocol
  packages/graphql-server/src/functions/graphql.ts
Labels: release:fix

#4826 (docs) add Flightcontrol.dev Deploy
  docs/docs/deploy.md
Labels: release:chore

#4866 Make doc links to relative file paths
  docs/docs/app-configuration-redwood-toml.md
  docs/docs/authentication.md
  docs/docs/builds.md
  docs/docs/cells.md
  docs/docs/cli-commands.md
  docs/docs/contributing-overview.md
  docs/docs/contributing-walkthrough.md
  docs/docs/cookbook/background-worker.md
  docs/docs/cookbook/file-uploads.md
  docs/docs/cookbook/gotrue-auth.md
  docs/docs/cookbook/pagination.md
  docs/docs/cookbook/role-based-access-control.md
  docs/docs/cookbook/supabase-auth.md
  docs/docs/cookbook/windows-development-setup.md
  docs/docs/cors.md
  docs/docs/data-migrations.md
  docs/docs/deploy.md
  docs/docs/directives.md
  docs/docs/environment-variables.md
  docs/docs/graphql.md
  docs/docs/logger.md
  docs/docs/prerender.md
  docs/docs/quick-start.md
  docs/docs/router.md
  docs/docs/security.md
  docs/docs/seo-head.md
  docs/docs/serverless-functions.md
  docs/docs/services.md
  docs/docs/testing.md
  docs/docs/tutorial/chapter1/first-page.md
  docs/docs/tutorial/chapter1/prerequisites.md
  docs/docs/tutorial/chapter1/second-page.md
  docs/docs/tutorial/chapter2/cells.md
  docs/docs/tutorial/chapter2/routing-params.md
  docs/docs/tutorial/chapter2/side-quest.md
  docs/docs/tutorial/chapter3/forms.md
  docs/docs/tutorial/chapter3/saving-data.md
  docs/docs/tutorial/chapter4/authentication.md
  docs/docs/tutorial/chapter4/deployment.md
  docs/docs/tutorial/chapter5/first-test.md
  docs/docs/tutorial/chapter5/testing.md
  docs/docs/tutorial/chapter7/rbac.md
  docs/docs/tutorial/foreword.md
  docs/docs/webhooks.md
  docs/docusaurus.config.js
  docs/netlify.toml
  docs/sidebars.js
Labels: topic/docs, release:fix

#4870 Fix Request object passed to Yoga
  packages/graphql-server/package.json
  packages/graphql-server/src/functions/graphql.ts
  yarn.lock
Labels: release:fix

#4874 Fix favicon on docs site
  docs/netlify.toml
Labels: release:fix

#4876 [WIP] Try modifying path to favicon
  docs/docusaurus.config.js
Labels: release:fix

#4877 event.requestContext can be optional for domain name
  packages/graphql-server/src/functions/graphql.ts
Labels: release:fix

#4883 GraphQL Yoga / Rework multi and non-multi query string param handling when building request
  packages/graphql-server/src/functions/graphql.ts
Labels: release:fix

#4889 add rw-server bin to core bins
  packages/core/src/bins/rw-server.ts
Labels: release:fix

#4856 Cleanup deprecated features
  CHANGELOG.md
  packages/api-server/README.md
  packages/api-server/package.json
  packages/api-server/src/index.ts
  packages/api-server/src/watch.ts
  packages/api/src/functions/dbAuth/DbAuthHandler.ts
  packages/api/src/functions/dbAuth/__tests__/DbAuthHandler.test.js
  packages/cli/src/commands/setup/tailwind.js
  yarn.lock
Labels: release:feature-breaking

#4892 Use Node's Buffer.from to decode base64 instead of atob
  packages/graphql-server/src/functions/graphql.ts
Labels: release:fix

#4893 Fix link to docs/contributing
  docs/docs/contributing-overview.md
Labels: release:fix

#4903 Add toml syntax highlighting
  docs/docusaurus.config.js
Labels: topic/docs, release:feature

#4694 Enable debugging api server as forked by "yarn rw dev" on configured port
  packages/api-server/src/watch.ts
  packages/cli/src/commands/dev.js
  packages/create-redwood-app/template/.vscode/launch.json
  packages/internal/src/config.ts
Labels: release:feature

#4908 Change algolia config
  docs/docusaurus.config.js
Labels: topic/docs, release:fix

#4909 [Search] Try external url regex
  docs/docusaurus.config.js
Labels: topic/docs, release:fix

#4911 Use learn instead of redwoodjs.com for external url regex
  docs/docusaurus.config.js
Labels: topic/docs, release:fix

#4846 Clerk: Switch to getToken
  packages/api/src/auth/decoders/clerk.ts
  packages/auth/src/authClients/clerk.ts
Labels: release:chore

#4912 Fix regression where GraphQL Yoga would rename all errors to the default value before other plugins could consume them
  packages/graphql-server/src/functions/graphql.ts
Labels: release:fix

#4901 Check multi-value query as array or string
  packages/graphql-server/src/functions/graphql.ts
Labels: release:fix

#4933 Update docs for yarn v3
  docs/docs/cli-commands.md
Labels: release:fix

#4931 Remove node-ssh dependency, add to api/package.json at setup time
  packages/cli/package.json
  packages/cli/src/commands/deploy/baremetal.js
  packages/cli/src/commands/setup/deploy/providers/baremetal.js
  yarn.lock
Labels: topic/deployment, release:fix

#4922 Update Clerk docs and instructions
  docs/docs/authentication.md
  packages/cli/src/commands/setup/auth/providers/clerk.js
Labels: release:chore

#4825 4593 BUG - Auth setup script issues
  packages/cli/src/commands/setup/auth/__tests__/__snapshots__/addAuthConfigToApp.test.js.snap
  packages/cli/src/commands/setup/auth/__tests__/addAuthConfigToApp.test.js
  packages/cli/src/commands/setup/auth/__tests__/fixtures/AppWithCustomRedwoodApolloProvider.js
  packages/cli/src/commands/setup/auth/__tests__/fixtures/AppWithExplicitReturn.js
  packages/cli/src/commands/setup/auth/__tests__/fixtures/AppWithoutRedwoodApolloProvider.js
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:fix

#4943 More clerk doc comment updates
  packages/cli/src/commands/setup/auth/providers/clerk.js
Labels: release:chore

#4942 Fix test-project task linting errors
  tasks/test-project/test-project
Labels: release:chore

#4934 fix flightcontrol template and doc
  docs/docs/deploy/flightcontrol.md
  packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
Labels: release:chore

#4950 Add setup step for prisma client on Layer0 provider
  packages/cli/src/commands/setup/deploy/providers/layer0.js
Labels: next-release/code-mod, release:fix

#4765 Add @storybook/addon-essentials by default
  packages/testing/config/storybook/main.js
  packages/testing/package.json
  yarn.lock
Labels: topic/storybook, release:feature

#4764 Add Storybook template for i18n
  packages/cli/src/commands/setup/i18n/i18n.js
  packages/cli/src/commands/setup/i18n/templates/i18n.js.template
  packages/cli/src/commands/setup/i18n/templates/storybook.preview.js.template
  packages/cli/src/commands/setup/ui/libraries/chakra-ui.js
  packages/cli/src/commands/setup/ui/tasks/configure-storybook.js
  packages/cli/src/lib/configureStorybook.js
Labels: topic/cli, topic/storybook, release:feature

#4971 small copy paste error s/posts/articles
  docs/docs/tutorial/chapter2/cells.md
Labels: release:chore

#4964 Clarify tutorial cell aliasing
  docs/docs/tutorial/chapter2/cells.md
Labels: release:chore

#4956 Fix magic.link token expiry logic
  packages/auth/src/authClients/magicLink.ts
Labels: release:fix

#4974 Fix: Don't swallow typegen errors
  packages/internal/src/__tests__/graphqlCodeGen.test.ts
  packages/internal/src/generate/graphqlCodeGen.ts
  packages/internal/src/generate/graphqlSchema.ts
Labels: topic/core, release:fix
