Repository redwoodjs/graphql, pull requests merged in 2022-09, with the labels that each got.

#6329 Fix getCurrentUser type to get rid of red squiggles
  __fixtures__/test-project/api/db/migrations/20220831192006_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220831192018_create_contact/migration.sql
  __fixtures__/test-project/api/src/functions/auth.ts
  __fixtures__/test-project/api/src/lib/auth.ts
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
  __fixtures__/test-project/web/src/pages/ResetPasswordPage/ResetPasswordPage.tsx
  packages/api/src/auth/decoders/index.ts
  packages/api/src/auth/index.ts
  packages/api/src/auth/parseJWT.ts
  packages/cli/src/commands/generate/dbAuth/templates/forgotPassword.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/resetPassword.tsx.template
  packages/cli/src/commands/setup/auth/templates/auth.ts.template
  packages/cli/src/commands/setup/auth/templates/auth0.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/azureActiveDirectory.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.webAuthn.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.function.ts.template
  packages/cli/src/commands/setup/auth/templates/dbAuth.function.webAuthn.ts.template
  packages/graphql-server/src/plugins/useRedwoodAuthContext.ts
Labels: release:fix

#6335 [Chore] Bump test project to v3 RC
  __fixtures__/test-project/api/package.json
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
Labels: release:chore

#6336 Fix: Fixes an error seen with the Configure Fastify codemod for v3-rc
  packages/codemods/src/codemods/v2.x.x/configureFastify/configureFastify.yargs.ts
Labels: release:fix

#6331 correct auth playground github link
  docs/docs/authentication.md
Labels: topic/docs, release:docs

#6337 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release:docs

#6235 Tutorial chapter 2: Make JS code sample match actual generated code
  docs/docs/tutorial/chapter2/routing-params.md
Labels: release:docs

#6099 Updated baremetal deploy config
  docs/docs/contributing-walkthrough.md
  packages/cli/src/commands/setup/deploy/templates/baremetal.js
Labels: release:fix, fixture-ok

#5537 Handle special props `ref` and `key` in path and search params
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/util.test.ts
  packages/router/src/router.tsx
  packages/router/src/util.ts
Labels: topic/router, release:fix

#6340 Add missing commit to 6329
  __fixtures__/test-project/api/db/migrations/20220902171701_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220902171716_create_contact/migration.sql
  __fixtures__/test-project/api/src/lib/auth.ts
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
  packages/graphql-server/src/plugins/useRedwoodAuthContext.ts
Labels: release:fix

#6325 issue#5852 added windows fix for nodeFileTrace
  packages/internal/src/build/babelPlugins/__tests__/babel-plugin-redwood-src-alias.test.ts
  packages/internal/src/build/babelPlugins/babel-plugin-redwood-src-alias.ts
Labels: release:fix

#6342 feat(codemod): Add codemod to make relation resolvers partial
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/README.md
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/__tests__/updateResolverTypes.test.ts
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/updateResolverTypes.ts
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/updateResolverTypes.yargs.ts
  packages/codemods/src/testUtils/matchTransformSnapshot.ts
  packages/codemods/tasks/generateCodemod/templates/code/codemod.yargs.ts.template
Labels: release:chore

#6358 Use try/catch to access unauthenticated
  packages/router/src/Set.tsx
Labels: release:fix

#6203 bugfix replace slash in tailwind config on windows
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
Labels: topic/cli, release:fix, fixture-ok

#6365 Adds `privateKeyPath` option to Baremetal deploy
  docs/docs/deploy/baremetal.md
  packages/cli/src/commands/deploy/baremetal.js
  packages/cli/src/commands/setup/deploy/templates/baremetal.js
Labels: topic/deployment, release:feature, fixture-ok

#6359 Better private Set error handling and test coverage
  packages/router/src/Set.tsx
  packages/router/src/__tests__/router.test.tsx
Labels: release:fix

#6360 (feat): Add TS prompt to Create Redwood App
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:feature

#6327 fix(performance): Jest api side performance improvements
  packages/internal/src/build/babel/api.ts
  packages/testing/config/jest/api/globalSetup.js
  packages/testing/config/jest/api/jest-preset.js
  packages/testing/config/jest/api/jest.setup.js
  packages/testing/config/jest/web/jest-preset.js
Labels: release:fix

#6379 fix(crwa): add prompts to dependencies
  packages/create-redwood-app/package.json
  yarn.lock
Labels: topic/crwa, release:fix, fixture-ok

#6375 Fix #6374 - Render.com web builds fail
  packages/cli/src/commands/setup/deploy/templates/render.js
Labels: topic/cli, topic/deployment, release:fix, fixture-ok

#6382 fix(prerender): Allow overriding prerender parameter in a Route nested in a Set
  packages/prerender/src/__tests__/detectRoutes.test.ts
  packages/structure/src/model/RWRoute.ts
  packages/structure/src/model/RWRouter.ts
Labels: release:fix

#6341 Different ResolverFn depending on if args are required or not
  __fixtures__/test-project/api/db/migrations/20220913212918_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220913212929_create_contact/migration.sql
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/posts/posts.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.ts
  __fixtures__/test-project/web/package.json
  docs/docs/tutorial/chapter6/comments-schema.md
  docs/docs/typescript/strict-mode.md
  packages/cli/src/commands/generate/sdl/__tests__/__snapshots__/sdl.test.js.snap
  packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
  packages/cli/src/commands/generate/service/templates/service.ts.template
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/README.md
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/__testfixtures__/default.input.ts
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/__testfixtures__/default.output.ts
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/__tests__/updateResolverTypes.test.ts
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/updateResolverTypes.ts
  packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
  packages/internal/src/generate/graphqlCodeGen.ts
  packages/internal/src/generate/plugins/rw-typescript-resolvers/index.ts
  packages/internal/src/generate/plugins/rw-typescript-resolvers/visitor.ts
Labels: release:feature

#6383 Fix: The configureFastify codemod now handles missing config case
  packages/codemods/src/codemods/v2.x.x/configureFastify/configureFastify.yargs.ts
Labels: release:fix

#6320 chore(react): upgrade React typings to use a more explicit `children` prop declaration
  packages/auth/src/AuthProvider.tsx
  packages/router/src/location.tsx
  packages/router/src/params.tsx
  packages/router/src/router-context.tsx
  packages/router/src/router.tsx
  packages/testing/src/web/MockParamsProvider.tsx
  packages/testing/src/web/MockProviders.tsx
  packages/testing/src/web/MockRouter.tsx
  packages/web/src/apollo/index.tsx
  packages/web/src/components/FetchConfigProvider.tsx
Labels: release:chore

#6364 fix(typescript): Fix incorrect type generated for glob route parameters | Add type tests
  package.json
  packages/internal/src/generate/templates/web-routerRoutes.d.ts.template
  packages/router/jest.config.js
  packages/router/package.json
  packages/router/src/__tests__/util.test.ts
  packages/router/src/__typetests__/routeParamsTypes.test.ts
  packages/router/src/__typetests__/tsconfig.json
  packages/router/src/index.ts
  packages/router/src/routeParamsTypes.ts
  yarn.lock
Labels: release:fix

#6408 Fix red squiggles in router tests
  packages/router/src/__tests__/router.test.tsx
Labels: release:fix

#6414 [Chore] Add cherry pick CI
  .github/actions/only_doc_changes/only_doc_changes.mjs
  .github/workflows/cherry-pick-into-release-pr.yml
  .github/workflows/enable-auto-merge.yml
Labels: release:chore

#6421 chore(deps): update dependency cypress to v10.8.0
  package.json
  yarn.lock
Labels: release:chore, cherry-pick

#6221 Scaffolds: Don't generate unused methods
  __fixtures__/test-project/api/db/migrations/20220918091756_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220918091807_create_contact/migration.sql
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/components/Contact/Contact/Contact.tsx
  __fixtures__/test-project/web/src/components/Contact/Contacts/Contacts.tsx
  __fixtures__/test-project/web/src/components/Post/Post/Post.tsx
  __fixtures__/test-project/web/src/components/Post/Posts/Posts.tsx
  __fixtures__/test-project/web/src/lib/formatters.test.tsx
  __fixtures__/test-project/web/src/lib/formatters.tsx
  packages/cli/package.json
  packages/cli/src/commands/destroy/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/destroy/scaffold/__tests__/scaffoldNoNest.test.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/editableColumns.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPath.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMulti.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiword.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiwordNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathNoNest.test.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/components/Name.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/Names.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/lib/formatters.test.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/lib/formatters.tsx.template
  packages/cli/src/lib/index.js
  yarn.lock
Labels: release:fix

#6434 fix(crwa): Fixes telemetry issues on CRWA
  .eslintrc.js
  packages/create-redwood-app/README.md
  packages/internal/package.json
  packages/structure/src/hosts.ts
  packages/structure/src/index.ts
  packages/structure/src/model/RWProject.ts
  packages/structure/src/model/RWRouter.ts
  packages/structure/src/model/__tests__/model.test.ts
  packages/structure/src/outline/outline.ts
  packages/telemetry/README.md
  packages/telemetry/src/sendTelemetry.ts
Labels: release:fix

#6424 chore(react): use `updater` callback function
  packages/auth/src/AuthProvider.tsx
  packages/router/src/__tests__/router.test.tsx
Labels: release:fix

#6433 Tell user to say no when asked to enable WebAuth
  docs/docs/tutorial/chapter4/authentication.md
  docs/versioned_docs/version-3.0/tutorial/chapter4/authentication.md
Labels: release:docs

#6428 fix: Added default port ssh port 22 and forwarding of config port setting
  docs/docs/deploy/baremetal.md
  packages/cli/src/commands/deploy/__tests__/baremetal.test.js
  packages/cli/src/commands/deploy/baremetal.js
Labels: topic/deployment, release:feature

#6438 fix(jest): Fix watchmode on api tests
  packages/testing/config/jest/api/jest-preset.js
  packages/testing/config/jest/api/jest.setup.js
Labels: release:fix

#6442 Setting query name in cell generator
  __fixtures__/test-project/api/db/migrations/20220926103708_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220926103723_create_contact/migration.sql
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/package.json
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/cell/utils/utils.js
Labels: release:feature

#6453 chore(lint): Fix lint issues in cell test
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
Labels: release:chore, fixture-ok

#6436 Update local-postgres-setup.md with correct brew postgres install command
  docs/docs/local-postgres-setup.md
Labels: topic/docs, topic/cli, release:docs

#6445 Add docs for `sourceMap` flag in `redwood.toml`
  docs/docs/app-configuration-redwood-toml.md
Labels: release:docs

#6435 docs(crwa): Fix incorrect command to test crwa canary
  packages/create-redwood-app/README.md
Labels: release:docs

#6454 fix(deploy): Fix deploy on Fly.io
  packages/cli/src/commands/buildHandler.js
Labels: release:fix

#6443 chore(nx): bust build cache on babel config change
  nx.json
Labels: topic/ops-&-contributing-dx, release:chore

#6455 Fix warnings in CLI destroy tests
  packages/cli/src/commands/destroy/cell/__tests__/cell.test.js
  packages/cli/src/commands/destroy/function/__tests__/function.test.js
Labels: release:chore

#6385 Update scaffolds to use a shared ScaffoldLayout
  __fixtures__/test-project/web/src/Routes.tsx
  __fixtures__/test-project/web/src/layouts/ScaffoldLayout/ScaffoldLayout.tsx
  docs/docs/tutorial/chapter2/getting-dynamic.md
  docs/docs/tutorial/chapter2/routing-params.md
  docs/docs/tutorial/chapter3/forms.md
  docs/docs/tutorial/chapter4/authentication.md
  docs/docs/tutorial/chapter7/rbac.md
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPath.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMulti.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiword.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiwordNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathNoNest.test.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/layouts/NamesLayout.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/layouts/ScaffoldLayout.tsx.template
  packages/cli/src/lib/index.js
  tasks/e2e/cypress/e2e/01-tutorial/codemods/Step6_1_Routes.js
  tasks/e2e/cypress/e2e/01-tutorial/codemods/Step7_4_Routes.js
Labels: topic/generators-&-scaffolds, release:feature

#6470 [Docs]: CLI Cell query flag added
  docs/docs/cli-commands.md
Labels: release:docs

#6394 fix(cli) Generated services use Date objects for DateTime types in the tests
  __fixtures__/test-project/api/db/migrations/20220930080940_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220930081046_create_contact/migration.sql
  __fixtures__/test-project/api/src/services/contacts/contacts.test.ts
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/posts/posts.test.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  docs/docs/testing.md
  packages/cli/src/commands/generate/sdl/__tests__/__snapshots__/sdl.test.js.snap
  packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
  packages/cli/src/commands/generate/service/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/service/__tests__/scenario.test.js
  packages/cli/src/commands/generate/service/__tests__/service.test.js
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/generate/service/templates/test.ts.template
Labels: release:fix
