Repository redwoodjs/graphql, pull requests merged in 2022-02, with the labels that each got.

#4218 Add explanation and docs link in generated tests
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/templates/test.js.template
  packages/cli/src/commands/generate/component/__tests__/__snapshots__/component.test.ts.snap
  packages/cli/src/commands/generate/component/templates/test.tsx.template
  packages/cli/src/commands/generate/function/__tests__/__snapshots__/function.test.ts.snap
  packages/cli/src/commands/generate/function/templates/test.ts.template
  packages/cli/src/commands/generate/layout/__tests__/__snapshots__/layout.test.ts.snap
  packages/cli/src/commands/generate/layout/templates/test.tsx.template
  packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap
  packages/cli/src/commands/generate/page/templates/test.tsx.template
  packages/cli/src/commands/generate/sdl/__tests__/__snapshots__/sdl.test.js.snap
  packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
  packages/cli/src/commands/generate/service/templates/test.ts.template
Labels: topic/generators-&-scaffolds, release:fix

#4309 Sort package.jsons
  .github/workflows/build-eslint-jest.yaml
  CONTRIBUTING.md
  package.json
  packages/api-server/package.json
  packages/api/package.json
  packages/auth/package.json
  packages/cli/package.json
  packages/codemods/package.json
  packages/core/package.json
  packages/create-redwood-app/package.json
  packages/eslint-config/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/prerender/package.json
  packages/record/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/telemetry/package.json
  packages/testing/package.json
  packages/web/package.json
  tasks/check/action.yml
  tasks/check/check.mjs
  yarn.lock
Labels: release:chore

#3919 Upgrade yarn to 3.1.1
  .github/workflows/telemetry-benchmarks.yaml
  .yarn/releases/yarn-3.0.2.cjs
  .yarn/releases/yarn-3.1.1.cjs
  .yarnrc.yml
  package.json
  tasks/run-e2e
  yarn.lock
Labels: topic/ops-&-contributing-dx, dependencies, v1/priority, release:chore

#4325 update contributing content
  CONTRIBUTING.md
Labels: release:chore

#4304 createCell: Give cell results priority over cell props
  packages/web/src/components/createCell.tsx
Labels: release:fix

#4341 Update the copy related to Gitpod
  CONTRIBUTING.md
Labels: release:chore

#4302 Forms: Automatically handle optional relation fields
  packages/forms/src/__tests__/form.test.tsx
  packages/forms/src/index.tsx
Labels: next-release/update-docs, release:feature

#4096 (jest) improves performance and mem use reduction; adds compatibility with 3rd party tools; fwds all args to jest command
  packages/cli/src/commands/__tests__/test.test.js
  packages/cli/src/commands/test.js
  packages/cli/src/middleware/checkForBabelConfig.js
  packages/create-redwood-app/template/api/jest.config.js
  packages/create-redwood-app/template/jest.config.js
  packages/create-redwood-app/template/web/jest.config.js
  packages/testing/config/jest/api/index.js
  packages/testing/config/jest/api/jest-preset.js
  packages/testing/config/jest/api/jest.setup.js
  packages/testing/config/jest/jest.config.js
  packages/testing/config/jest/web/index.js
  packages/testing/config/jest/web/jest-preset.js
Labels: topic/testing, v1/for-consideration, topic/fully-integrated-dx, release:fix

#4363 revert dotenv ignorestub
  packages/core/config/webpack.common.js
Labels: release:chore

#4355 Add codemods for 3rd-party compatible jest config
  packages/codemods/jest.setup.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/README.md
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/custom/input/api/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/custom/input/web/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/custom/output/api/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/custom/output/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/custom/output/web/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/input/api/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/input/web/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/output/api/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/output/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/output/web/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/missing/input/api/.keep
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/missing/input/web/.keep
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/missing/output/api/.keep
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/missing/output/api/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/missing/output/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/missing/output/web/.keep
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/missing/output/web/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__tests__/updateJestConfig.test.ts
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/updateJestConfig.transform.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/updateJestConfig.ts
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/updateJestConfig.yargs.ts
  packages/codemods/src/lib/fetchFileFromTemplate.ts
  packages/codemods/src/testUtils/matchFolderTransform.ts
  packages/codemods/testUtils.d.ts
Labels: release:feature

#4159 Updates serverless deploy option
  packages/cli/src/commands/deploy/aws-providers/serverless.js
  packages/cli/src/commands/deploy/aws.js
  packages/cli/src/commands/deploy/serverless.js
  packages/cli/src/commands/setup/deploy/helpers/index.js
  packages/cli/src/commands/setup/deploy/providers/aws-serverless.js
  packages/cli/src/commands/setup/deploy/providers/serverless.js
  packages/cli/src/commands/setup/deploy/templates/serverless.js
  packages/cli/src/commands/setup/deploy/templates/serverless/api.js
  packages/cli/src/commands/setup/deploy/templates/serverless/web.js
Labels: topic/cli, topic/deployment, next-release/update-docs, v1/priority, release:feature

#4342 Reduce the amount of problemMatcher outputs in the PR
  .github/workflows/build-eslint-jest.yaml
Labels: release:chore

#4378 fix(scenario): Accidentally comitted debugging change
  packages/testing/config/jest/api/jest.setup.js
Labels: release:fix

#4381 (render deploy) use bin for prisma migrate command
  packages/cli/src/commands/deploy/render.js
Labels: release:fix

#4376 fix(generators): Generate types after gen-ing files
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/sdl/sdl.js
Labels: release:fix

#4385 Add extra checks for setup commands on the cli
  .github/workflows/e2e.yaml
Labels: release:chore

#4389 Try fixing codemod test timeout
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/input/api/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/input/web/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/output/api/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/output/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/output/web/jest.config.js
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__tests__/updateJestConfig.test.ts
Labels: release:chore

#4391 Increase test timeout
  packages/codemods/jest.config.js
  packages/testing/src/web/__tests__/MockHandlers.test.tsx
Labels: release:chore

#4406 Add types for react-testing library to tsconfig
  packages/create-redwood-app/template/web/tsconfig.json
Labels: release:fix

#4403 Changed delimiter to a correct one.
  packages/cli/src/commands/setup/auth/providers/dbAuth.js
Labels: topic/create-redwood-app, release:fix

#4402 Prepare release script for patches
  package.json
  tasks/release/__tests__/release.test.mjs
  tasks/release/__tests__/updatePullRequestsMilestone.test.mjs
  tasks/release/cli.mjs
  tasks/release/prompts.mjs
  tasks/release/release.mjs
  tasks/release/updatePRsMilestone.mjs
Labels: release:chore

#4370 Add missing deps to api/web, add check:deps/check:tarball script
  package.json
  packages/api/package.json
  packages/web/package.json
  tasks/__snapshots__/checkTarball.test.js.snap
  tasks/checkDeps.mjs
  tasks/checkTarball.test.js
  yarn.lock
Labels: release:chore

#4411 Downgrade Prisma to 3.8.1
  packages/api/package.json
  packages/cli/package.json
  packages/graphql-server/package.json
  packages/record/package.json
  packages/structure/package.json
  yarn.lock
Labels: release:fix

#4417 Polish release script
  tasks/release/__tests__/updatePRsMilestone.test.mjs
  tasks/release/release.mjs
  tasks/release/updatePRsMilestone.mjs
Labels: release:chore

#4395 Support enums when scaffolding modes to display values and generate form inputs
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template
  packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.tailwind.css.template
  packages/cli/src/commands/generate/scaffold/templates/components/Name.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NameForm.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/Names.tsx.template
Labels: topic/generators-&-scaffolds, release:feature

#4433 (render.com deployment) resolve deploy render exceeding memory on free tier
  packages/cli/src/commands/deploy/render.js
Labels: release:fix

#4439 Upgrade Prisma to 3.9.2
  packages/api/package.json
  packages/cli/package.json
  packages/graphql-server/package.json
  packages/record/package.json
  packages/structure/package.json
  yarn.lock
Labels: release:chore

#4440 api server: Windows fix, ensure posix paths
  packages/api-server/src/index.ts
Labels: release:fix

#4416 Fix: Allow `x-www-form-urlencoded` and `multipart/form-data` content type in api-server
  packages/api-server/src/plugins/withFunctions.ts
Labels: topic/api, release:fix

#4442 Ignore lru-cache
  .github/renovate.json
Labels: release:chore

#4451 Feb security vulnerabilities
  yarn.lock
Labels: release:chore

#3762 refactor(forms): Change typing to omit `type` property + Workaround for upstream react/prop-types lint rule
  packages/forms/src/index.tsx
Labels: topic/forms, topic/typescript, release:fix

#4462 fix(test-project): Ignore exit code from rimraf if dist not present
  package.json
Labels: release:chore

#4465 package.json: Quote path to rimraf to let rimraf do globbing
  package.json
Labels: release:fix

#4475 [CLI] Enable short-form prisma options
  packages/cli/src/commands/prisma.js
Labels: topic/prisma, topic/cli, v1/for-consideration, release:fix

#4405 fix(tsc-web): Fix web tsc when api/src/lib/auth imports other files
  packages/create-redwood-app/template/web/tsconfig.json
Labels: release:fix

#4474 [Renovate] Ignore pretty bytes
  .github/renovate.json
Labels: release:chore

#4422 Handle webpack dev server errors helpfully when api server is reloading our to api change or unavailable
  packages/core/config/webpack.development.js
  tasks/e2e/cypress/integration/01-tutorial/sharedTests.js
  tasks/e2e/cypress/integration/01-tutorial/tutorial.spec.js
  tasks/e2e/cypress/integration/04-logger/logger.spec.js
Labels: topic/forms, topic/api, topic/cells, release:fix

#4432 Update Auth0 auth template to extract namespaced roles
  packages/cli/src/commands/setup/auth/templates/auth0.auth.ts.template
Labels: next-release/update-docs, release:chore

#4320 Apollo: isAuthenticated might not be up-to-date
  packages/auth/src/AuthProvider.tsx
  packages/web/src/apollo/index.tsx
  packages/web/src/components/FetchConfigProvider.tsx
Labels: release:fix

#4490 Fix release script
  tasks/release/release.mjs
  tasks/release/updatePRsMilestone.mjs
Labels: release:chore

#3963 yarn rw check throws on failure
  packages/structure/src/index.ts
Labels: release:fix

#4443 Update Clerk auth provider logic
  packages/auth/src/AuthProvider.tsx
  packages/cli/src/commands/setup/auth/auth.js
  packages/cli/src/commands/setup/auth/providers/clerk.js
  packages/cli/src/commands/setup/auth/templates/clerk.auth.js.template
Labels: release:fix

#4526 Try increasing timeout for flaky codemods test
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__tests__/updateJestConfig.test.ts
Labels: release:chore

#4538 Envelop: Don't use useImmediateIntrospection as it causes auth bug
  packages/graphql-server/src/functions/graphql.ts
Labels: release:fix

#4539 Netlify client getToken fix when GoTrue client refreshes JWT
  packages/auth/src/authClients/goTrue.ts
  packages/auth/src/authClients/netlify.ts
Labels: release:fix

#4542 create-redwood-app: Correct --overwrite description
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#4390 Add generate codemod script
  packages/codemods/package.json
  packages/codemods/tasks/generateCodemod/generateCodemod.mjs
  packages/codemods/tasks/generateCodemod/templates/code/README.md.template
  packages/codemods/tasks/generateCodemod/templates/code/__testfixtures__/default.input.js
  packages/codemods/tasks/generateCodemod/templates/code/__testfixtures__/default.output.js
  packages/codemods/tasks/generateCodemod/templates/code/__tests__/codemod.test.ts.template
  packages/codemods/tasks/generateCodemod/templates/code/codemod.ts.template
  packages/codemods/tasks/generateCodemod/templates/code/codemod.yargs.ts.template
  packages/codemods/tasks/generateCodemod/templates/structure/README.md.template
  packages/codemods/tasks/generateCodemod/templates/structure/__testfixtures__/default/input/.keep
  packages/codemods/tasks/generateCodemod/templates/structure/__testfixtures__/default/input/babel.config.js
  packages/codemods/tasks/generateCodemod/templates/structure/__testfixtures__/default/output/.keep
  packages/codemods/tasks/generateCodemod/templates/structure/__tests__/codemod.test.ts.template
  packages/codemods/tasks/generateCodemod/templates/structure/codemod.ts.template
  packages/codemods/tasks/generateCodemod/templates/structure/codemod.yargs.ts.template
Labels: topic/ops-&-contributing-dx, release:chore

#4523 g secret: raw output
  packages/cli/src/commands/generate/secret/__tests__/secret.test.js
  packages/cli/src/commands/generate/secret/secret.js
Labels: release:feature

#4528 fix: allow boolean for some validators in validation recipe
  packages/api/src/validations/validations.ts
Labels: topic/api, topic/typescript, v1/priority, release:fix

#4504 Benchmark `rw test ...` duration for case of Test-project
  packages/cli/src/commands/test.js
Labels: release:chore

#4534 Support for `undefined` as a value for service validators
  packages/api/src/validations/__tests__/validations.test.js
  packages/api/src/validations/validations.ts
Labels: release:feature

#4558 fix: link anchor to dataMigrate up docs
  packages/cli/src/commands/dataMigrate/up.js
Labels: topic/docs, topic/cli, release:fix

#4544 Temp fix: move lint & test workflow to use node 16.10 to prevent Windows out of memory
  .github/workflows/build-eslint-jest.yaml
Labels: release:chore

#4497 E2E Smoke test
  .github/actions/setup_test_project/setup_test_project.mjs
  .github/workflows/smoke-test.yaml
  package.json
  tasks/smoke-test/playwright-fixtures/devServer.fixture.ts
  tasks/smoke-test/playwright-fixtures/rwServe.fixture.ts
  tasks/smoke-test/playwright.config.ts
  tasks/smoke-test/tests/common.ts
  tasks/smoke-test/tests/rwDev.spec.ts
  tasks/smoke-test/tests/rwServe.spec.ts
  tasks/smoke-test/util.ts
  tasks/test-project/tasks.js
  tasks/test-project/test-project
  yarn.lock
Labels: release:chore

#4563 add dbAuth to Test-project
  .github/workflows/smoke-test.yaml
  __fixtures__/test-project/api/db/migrations/20220223220529_create_product/migration.sql
  __fixtures__/test-project/api/db/migrations/20220223220543_create_contact/migration.sql
  __fixtures__/test-project/api/db/migrations/20220223220613_db_auth/migration.sql
  __fixtures__/test-project/api/db/schema.prisma
  __fixtures__/test-project/api/package.json
  __fixtures__/test-project/api/src/directives/requireAuth/requireAuth.test.ts
  __fixtures__/test-project/api/src/functions/auth.ts
  __fixtures__/test-project/api/src/functions/graphql.ts
  __fixtures__/test-project/api/src/graphql/contacts.sdl.ts
  __fixtures__/test-project/api/src/graphql/posts.sdl.ts
  __fixtures__/test-project/api/src/lib/auth.ts
  __fixtures__/test-project/api/src/services/contacts/contacts.ts
  __fixtures__/test-project/package.json
  __fixtures__/test-project/redwood.toml
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/App.tsx
  __fixtures__/test-project/web/src/Routes.tsx
  __fixtures__/test-project/web/src/components/BlogPost/BlogPost.tsx
  __fixtures__/test-project/web/src/components/BlogPostCell/BlogPostCell.mock.ts
  __fixtures__/test-project/web/src/components/BlogPostCell/BlogPostCell.tsx
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.mock.ts
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.tsx
  __fixtures__/test-project/web/src/components/Post/Post/Post.tsx
  __fixtures__/test-project/web/src/components/Post/PostForm/PostForm.tsx
  __fixtures__/test-project/web/src/components/Post/PostsCell/PostsCell.tsx
  __fixtures__/test-project/web/src/layouts/BlogLayout/BlogLayout.tsx
  __fixtures__/test-project/web/src/layouts/PostsLayout/PostsLayout.tsx
  __fixtures__/test-project/web/src/pages/AboutPage/AboutPage.tsx
  __fixtures__/test-project/web/src/pages/BlogPostPage/BlogPostPage.tsx
  __fixtures__/test-project/web/src/pages/ContactPage/ContactPage.tsx
  __fixtures__/test-project/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  __fixtures__/test-project/web/src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
  __fixtures__/test-project/web/src/pages/HomePage/HomePage.tsx
  __fixtures__/test-project/web/src/pages/LoginPage/LoginPage.tsx
  __fixtures__/test-project/web/src/pages/ResetPasswordPage/ResetPasswordPage.tsx
  __fixtures__/test-project/web/src/pages/SignupPage/SignupPage.tsx
  tasks/test-project/codemods/blogLayout.js
  tasks/test-project/codemods/contactsService.js
  tasks/test-project/codemods/models.js
  tasks/test-project/tasks.js
  tasks/test-project/test-project
Labels: release:chore

#4555 Deprecate 'rw open' command
  packages/cli/src/commands/open.js
Labels: release:feature-breaking, next-release/update-docs

#4574 improve rebuildFixture ts-to-js logic
  __fixtures__/test-project/api/db/migrations/20220224174918_create_product/migration.sql
  __fixtures__/test-project/api/db/migrations/20220224174932_create_contact/migration.sql
  __fixtures__/test-project/api/db/migrations/20220224175002_db_auth/migration.sql
  __fixtures__/test-project/api/src/directives/requireAuth/requireAuth.test.ts
  tasks/test-project/tasks.js
  tasks/test-project/test-project
Labels: release:chore

#4576 use rebuildFixture without passing dir, fix test-project tailwind deps installation
  __fixtures__/test-project/api/db/migrations/20220225003533_create_product/migration.sql
  __fixtures__/test-project/api/db/migrations/20220225003549_create_contact/migration.sql
  __fixtures__/test-project/api/db/migrations/20220225003620_db_auth/migration.sql
  __fixtures__/test-project/web/package.json
  tasks/test-project/tasks.js
  tasks/test-project/test-project
Labels: release:chore

#4577 Add Codemod to Update Fatal Error Page to support Development version
  packages/codemods/README.md
  packages/codemods/src/codemods/v47.x/updateDevFatalErrorPage/README.md
  packages/codemods/src/codemods/v47.x/updateDevFatalErrorPage/__testfixtures__/default/input/web/src/pages/FatalErrorPage/FatalErrorPage.js
  packages/codemods/src/codemods/v47.x/updateDevFatalErrorPage/__testfixtures__/default/output/web/src/pages/FatalErrorPage/FatalErrorPage.js
  packages/codemods/src/codemods/v47.x/updateDevFatalErrorPage/__tests__/updateDevFatalErrorPage.test.ts
  packages/codemods/src/codemods/v47.x/updateDevFatalErrorPage/updateDevFatalErrorPage.ts
  packages/codemods/src/codemods/v47.x/updateDevFatalErrorPage/updateDevFatalErrorPage.yargs.ts
Labels: release:chore

#4529 Checking jest config web api
  packages/cli/src/commands/__tests__/test.test.js
  packages/cli/src/commands/test.js
Labels: release:feature

#4600 feat(exec): Allow listing of scripts with rw exec to improve dx
  packages/cli/src/commands/exec.js
Labels: release:feature

#4566 fix dbAuth Auth template roles logic and types, run type-check on Smoke-test CI, and resolve TS errors
  .github/actions/setup_test_project/setup_test_project.mjs
  .github/workflows/smoke-test.yaml
  __fixtures__/test-project/api/db/migrations/20220228194123_create_product/migration.sql
  __fixtures__/test-project/api/db/migrations/20220228194136_create_contact/migration.sql
  __fixtures__/test-project/api/db/migrations/20220228194210_db_auth/migration.sql
  __fixtures__/test-project/api/db/schema.prisma
  __fixtures__/test-project/api/src/directives/requireAuth/requireAuth.test.ts
  __fixtures__/test-project/api/src/lib/auth.ts
  __fixtures__/test-project/package.json
  __fixtures__/test-project/scripts/seed.ts
  packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
  tasks/test-project/codemods/models.js
  tasks/test-project/tasks.js
  tasks/test-project/test-project
  tasks/test-project/util.js
Labels: release:fix
