Repository redwoodjs/graphql, pull requests merged in 2023-03, with the labels that each got.

#7685 Allow passing an array of auth decoders to createGraphQLHandler
  packages/graphql-server/src/functions/__tests__/authDecoders.test.ts
  packages/graphql-server/src/functions/types.ts
Labels: release:fix

#7679 fix(cli): disable rollbacks when using force
  packages/cli/src/commands/generate/dataMigration/dataMigration.js
  packages/cli/src/commands/generate/dbAuth/dbAuth.js
  packages/cli/src/commands/generate/directive/directive.js
  packages/cli/src/commands/generate/function/function.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/model/model.js
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/script/script.js
  packages/cli/src/commands/generate/sdl/sdl.js
Labels: release:fix, fixture-ok

#7024 fix: avoid naming conflict with `client` prop
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/README.md
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/client.input.tsx
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/client.output.tsx
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/default.input.ts
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/default.output.ts
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/failureSuccess.input.tsx
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/failureSuccess.output.tsx
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/refetch.input.tsx
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/refetch.output.tsx
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/refetchClient.input.tsx
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/refetchClient.output.tsx
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/refetchClientAliased.input.tsx
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/refetchClientAliased.output.tsx
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__tests__/cellQueryResult.test.ts
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/cellQueryResult.ts
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/cellQueryResult.yargs.ts
  packages/codemods/src/lib/cells.ts
  packages/web/src/components/createCell.tsx
Labels: release:feature-breaking

#7704 [Cells]: Show Success if there's any data in any of the fields
  packages/codemods/package.json
  packages/codemods/src/codemods/list.yargs.ts
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/cellQueryResult.yargs.ts
  packages/codemods/src/codemods/v5.x.x/detectEmptyCells/detectEmptyCells.ts
  packages/codemods/src/codemods/v5.x.x/detectEmptyCells/detectEmptyCells.yargs.ts
  packages/web/src/components/createCell.test.tsx
  packages/web/src/components/createCell.tsx
  yarn.lock
Labels: release:feature-breaking

#7362 deleteCacheKey() needs to include any global cache prefix
  packages/api/src/cache/index.ts
Labels: release:fix

#7746 docs: fix typo in utility-types.md
  docs/docs/typescript/utility-types.md
Labels: release:docs

#7719 feature: Upgrade Supabase Auth to v2.
  docs/docs/auth/supabase.md
  packages/auth-providers/supabase/setup/src/setupHandler.ts
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supabase/web/src/__tests__/supabase.test.tsx
  packages/auth-providers/supabase/web/src/supabase.ts
  yarn.lock
Labels: release:feature-breaking

#7745 Auth: Add TS types for auth method options
  packages/auth-providers/auth0/web/src/__tests__/auth0.test.tsx
  packages/auth-providers/auth0/web/src/auth0.ts
  packages/auth-providers/azureActiveDirectory/web/src/__tests__/azureActiveDirectory.test.tsx
  packages/auth-providers/azureActiveDirectory/web/src/azureActiveDirectory.ts
  packages/auth-providers/clerk/web/src/__tests__/clerk.test.tsx
  packages/auth-providers/clerk/web/src/clerk.tsx
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.test.ts
  packages/auth-providers/dbAuth/web/src/dbAuth.ts
  packages/auth-providers/firebase/web/src/__tests__/firebase.test.tsx
  packages/auth-providers/firebase/web/src/firebase.ts
  packages/auth-providers/netlify/web/src/__tests__/netlify.test.tsx
  packages/auth-providers/netlify/web/src/netlify.ts
  packages/auth-providers/supabase/web/src/__tests__/supabase.test.tsx
  packages/auth-providers/supabase/web/src/supabase.ts
  packages/auth-providers/supertokens/web/src/__tests__/supertokens.test.tsx
  packages/auth-providers/supertokens/web/src/supertokens.ts
  packages/auth/src/AuthContext.ts
  packages/auth/src/AuthImplementation.ts
  packages/auth/src/AuthProvider/AuthProvider.tsx
  packages/auth/src/AuthProvider/useForgotPassword.ts
  packages/auth/src/AuthProvider/useLogIn.ts
  packages/auth/src/AuthProvider/useLogOut.ts
  packages/auth/src/AuthProvider/useResetPassword.ts
  packages/auth/src/AuthProvider/useSignUp.ts
  packages/auth/src/AuthProvider/useValidateResetToken.ts
  packages/auth/src/__tests__/fixtures/customTestAuth.ts
  packages/auth/src/authFactory.ts
  packages/auth/src/useAuth.ts
  packages/router/src/router-context.tsx
Labels: release:feature-breaking

#7762 prerender.spec.ts: Fix TS errors
  tasks/smoke-test/tests/prerender.spec.ts
Labels: release:chore

#7763 Fix wrong cell file names in docs
  docs/docs/typescript/utility-types.md
  docs/versioned_docs/version-3.x/typescript/utility-types.md
  docs/versioned_docs/version-4.0/typescript/utility-types.md
Labels: release:docs

#6381 (docs): Minor Docusaurus setup updates
  docs/docs/graphql.md
Labels: release:docs

#7779 docs(roles): Update using roles to limit a private route
  docs/docs/router.md
Labels: topic/router, release:docs

#7778 Update isSupported function of webauthn
  packages/auth-providers/dbAuth/web/src/webAuthn.ts
Labels: release:feature

#7794 Add Logflare install instructions to logger docs
  docs/docs/logger.md
Labels: release:docs

#7858 babel-plugin-redwood-routes-auto-loader.tests.ts: Break up into separate tests
  packages/internal/src/build/babelPlugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
Labels: release:chore

#7860 Fix unit test TS errors
  packages/internal/src/__tests__/nestedPages.test.ts
  packages/structure/src/model/__tests__/model.test.ts
Labels: release:chore

#7861 Updated test-project
  __fixtures__/test-project/api/db/migrations/20220101130000_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220102130000_create_contact/migration.sql
  __fixtures__/test-project/api/tsconfig.json
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/tsconfig.json
Labels: release:chore

#7876 chore(cli): Disable telemetry during framework cli unit tests
  packages/cli/jest.config.js
  packages/cli/jest.setup.js
Labels: release:chore

#7477 Upgrade simplewebauthn packages
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/setup/src/webAuthn.setupData.ts
  packages/auth-providers/dbAuth/web/package.json
  yarn.lock
Labels: release:feature-breaking, fixture-ok

#7881 Update README.md to include newer examples
  README.md
Labels: release:docs

#7900 Merge Branch strategy tooling
  package.json
  tasks/release/__tests__/__snapshots__/generateReleaseNotes.test.mjs.snap
  tasks/release/__tests__/generateReleaseNotes.test.mjs
  tasks/release/__tests__/release.test.mjs
  tasks/release/__tests__/updatePRsMilestone.test.mjs
  tasks/release/branchStrategy/README.md
  tasks/release/branchStrategy/branchStrategyCLI.mjs
  tasks/release/branchStrategy/branchStrategyLib.mjs
  tasks/release/branchStrategy/findPRCommand.mjs
  tasks/release/branchStrategy/triageMainCache.json
  tasks/release/branchStrategy/triageMainCommand.mjs
  tasks/release/branchStrategy/triageNextCache.json
  tasks/release/branchStrategy/triageNextCommand.mjs
  tasks/release/branchStrategy/validateMilestonesCommand.mjs
  tasks/release/cli.mjs
  tasks/release/data/releaseCommits.json
  tasks/release/data/triageMainData.json
  tasks/release/data/triageNextData.json
  tasks/release/generateReleaseNotes.mjs
  tasks/release/generateReleaseNotesCommand.mjs
  tasks/release/getReleaseCommitsCommand.mjs
  tasks/release/jest.config.mjs
  tasks/release/jest.setup.mjs
  tasks/release/octokit.mjs
  tasks/release/prompts.mjs
  tasks/release/release.mjs
  tasks/release/releaseCLI.mjs
  tasks/release/releaseCommand.mjs
  tasks/release/releaseLib.mjs
  tasks/release/sandbox.mjs
  tasks/release/triageMainCommand.mjs
  tasks/release/triageNextCommand.mjs
  tasks/release/updatePRsMilestone.mjs
  tasks/release/validateMilestonesCommand.mjs
  yarn.lock
Labels: release:chore

#7681 Makes validateWith async and a new validateWithSync synchronous
  docs/docs/services.md
  packages/api/src/validations/__tests__/validations.test.js
  packages/api/src/validations/validations.ts
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/README.md
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/__tests__/renameValidateWith.test.ts
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/renameValidateWith.ts
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/renameValidateWith.yargs.ts
Labels: release:feature-breaking

#7863 [docs] Update GraphQL playground tutorial docs
  docs/README.md
  docs/docs/tutorial/chapter3/saving-data.md
Labels: release:docs

#7894 Share template variables between pages and models in scaffold
  packages/cli/src/commands/generate/scaffold/scaffold.js
Labels: release:fix, fixture-ok

#7898 Fix for directUrl usage during testing
  __fixtures__/empty-project/api/db/schema.prisma
  packages/testing/config/jest/api/globalSetup.js
  packages/testing/src/api/__tests__/directUrlHelpers.test.ts
  packages/testing/src/api/directUrlHelpers.ts
Labels: release:fix, fixture-ok

#7917 fix(Clerk): call reauthenticate before navigating
  packages/auth-providers/clerk/setup/src/templates/web/auth.tsx.template
Labels: release:fix

#7934 fix(docs): Update webhook links
  docs/docs/webhooks.md
Labels: release:docs

#7942 chore: bump @escape.tech/graphql-armor to 1.8.1
  packages/graphql-server/package.json
  yarn.lock
Labels: release:fix

#7943 fix(rw-dev): with vite
  packages/vite/bins/rw-vite-dev.mjs
Labels: release:fix

#7765 chore: Updates Supabase readme, docs and tests for sign up with options and user/session
  docs/docs/auth/supabase.md
  packages/auth-providers/supabase/web/README.md
  packages/auth-providers/supabase/web/src/__tests__/supabase.test.tsx
Labels: release:docs

#7650 [docs] How to setup Passwordless authentication
  docs/docs/how-to/dbauth-passwordless.md
Labels: release:docs

#7960 feat: add temporary tasks script for getting the latest tagged versions of `@redwoodjs` packages
  tasks/getPackagesVersionsForTag.mjs
Labels: release:chore
