Repository redwoodjs/graphql, pull requests merged in 2023-05, with the labels that each got.

#7864 Count number of prerendered routes for telemetry
  packages/telemetry/src/sendTelemetry.ts
Labels: release:feature

#8175 fix(v5): type `queryResult` in Cells
  __fixtures__/test-project/README.md
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
  packages/web/src/components/createCell.tsx
Labels: release:fix

#8185 fix(v5 codemod): handle errors in cell query parsing
  packages/codemods/src/codemods/v5.x.x/detectEmptyCells/detectEmptyCells.ts
Labels: release:fix

#8187 chore(cli): Create and report UID
  packages/create-redwood-app/package.json
  packages/create-redwood-app/src/create-redwood-app.js
  packages/create-redwood-app/src/telemetry.js
  yarn.lock
Labels: release:chore

#8178 Playwright tests for prerender rehydration
  __fixtures__/test-project/web/src/Routes.tsx
  __fixtures__/test-project/web/src/pages/DoublePage/DoublePage.stories.tsx
  __fixtures__/test-project/web/src/pages/DoublePage/DoublePage.test.tsx
  __fixtures__/test-project/web/src/pages/DoublePage/DoublePage.tsx
  tasks/smoke-test/tests/prerender.spec.ts
  tasks/smoke-test/util.ts
  tasks/test-project/tasks.js
Labels: release:chore

#8190 chore(tests): increment pages found in path test
  packages/project-config/src/__tests__/paths.test.ts
Labels: release:chore

#8200 fix(cli): Add missing CLI dependencies
  packages/cli/package.json
  yarn.lock
Labels: release:fix

#8211 fix(v5 react codemod): handle custom web index
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/upgradeToReact18.ts
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/upgradeToReact18.yargs.ts
Labels: release:fix

#8214 chore(project-config): Fix repo directory value in project.json
  packages/project-config/package.json
Labels: release:chore

#8213 chore(crwa): add template test
  packages/create-redwood-app/.babelrc.js
  packages/create-redwood-app/package.json
  packages/create-redwood-app/tests/template.test.js
  yarn.lock
Labels: release:chore, fixture-ok

#8181 fix: Fix logFormatter when no undefined ns, name, or message.
  packages/api-server/src/__tests__/logFormatter.test.ts
  packages/api-server/src/logFormatter/formatters.ts
Labels: release:fix

#8222 chore(auth-azure-active-directory-web): Fix typo in repo directory
  packages/auth-providers/azureActiveDirectory/web/package.json
Labels: release:chore

#8225 fix(crwa): correctly filter on booleans for compat checks
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#8226 fix(crwa): Prevent links including "zero width space" in URL
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#8232 fix(telemetry): Redact additional information
  packages/telemetry/src/sendTelemetry.ts
Labels: release:fix

#8235 fix(v5 docs): update Cells, utility types
  docs/docs/cells.md
  docs/docs/typescript/utility-types.md
Labels: release:docs

#8236 chore(docs): reversion docs for cell, type fixes
  docs/versioned_docs/version-5.0/cells.md
  docs/versioned_docs/version-5.0/how-to/build-dashboards-fast-with-tremor.md
  docs/versioned_docs/version-5.0/typescript/utility-types.md
Labels: release:docs

#8243 Docs: Fix link to the dbauth signup.handler()
  docs/docs/tutorial/chapter4/authentication.md
Labels: release:docs

#8138 Add jest tests for vite code paths
  packages/internal/package.json
  packages/vite/package.json
  packages/vite/src/__tests__/fixtures/nestedPages/redwood.toml
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/Routes.js
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/auth.ts
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/index.html
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/layouts/AdminLayout/AdminLayout.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/layouts/MainLayout/MainLayout.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/layouts/ShowcaseLayout/ShowcaseLayout.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Admin/User/EditUserPage/EditUserPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Admin/User/NewUserPage/NewUserPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Admin/User/UserPage/UserPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Admin/User/UsersPage/UsersPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/ForgotPasswordPage/ForgotPasswordPage.js
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/HomePage/HomePage.js
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/HomePage/HomePage.stories.js
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/HomePage/HomePage.test.js
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/AllJobProfilesPage/AllJobProfilesPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/AllJobsPage/AllJobsPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/EditJobPage/EditJobPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/EditJobProfilePage/EditJobProfilePage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/JobPage/JobPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/JobProfilePage/JobProfilePage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/JobsPage/JobsPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/NewJobPage/NewJobPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/NewJobProfilePage/NewJobProfilePage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/LoginPage/LoginPage.js
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/NotFoundPage/NotFoundPage.js
  packages/vite/src/__tests__/viteNestedPages.test.mts
  packages/vite/src/index.ts
  yarn.lock
Labels: release:chore

#8252 docs: Update build-dashboards-fast-with-tremor.md typo in frontmatter
  docs/docs/how-to/build-dashboards-fast-with-tremor.md
Labels: release:docs

#8139 chore(project-config): reduce package size by removing Babel deps
  packages/project-config/build.mjs
  packages/project-config/package.json
  yarn.lock
Labels: release:chore

#8258 fix: set node linker to node_modules
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#8237 fix(crwa): prompt for commit message and yarn install
  packages/create-redwood-app/build.mjs
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#8253 experiment: Adds Inngest configuration to the experimental cli
  __fixtures__/example-todo-main/yarn.lock
  packages/cli/README.md
  packages/cli/src/commands/experimental/setupInngest.js
  packages/cli/src/commands/experimental/setupInngestHandler.js
  packages/cli/src/commands/experimental/util.js
Labels: release:feature

#8256 chore: move CLI `exp setup` to `exp setup-opentelemetry`
  docs/docs/cli-commands.md
  packages/cli/src/commands/experimental/setup.js
  packages/cli/src/commands/experimental/setupOpentelemetry.js
  packages/cli/src/commands/experimental/setupOpentelemetryHandler.js
  packages/cli/src/commands/experimental/templates/opentelemetry.ts.template
Labels: release:chore

#8261 fix(crwa): shorten output, handle yarn 3
  .github/actions/telemetry_check/check.mjs
  .github/workflows/ci.yml
  docs/docs/quick-start.md
  docs/versioned_docs/version-5.0/quick-start.md
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#8263 chore(docs): backport recent fixes to v5
  docs/versioned_docs/version-5.0/how-to/build-dashboards-fast-with-tremor.md
  docs/versioned_docs/version-5.0/tutorial/chapter4/authentication.md
Labels: release:docs

#8265 chore(tui): Avoid reactive drawing for non-tty
  packages/tui/src/index.ts
Labels: release:chore

#8273 Fix --rebuildFixture
  __fixtures__/test-project/api/tsconfig.json
  __fixtures__/test-project/scripts/tsconfig.json
  __fixtures__/test-project/web/tsconfig.json
  tasks/test-project/tasks.js
  tasks/test-project/test-project
Labels: release:chore

#8279 fix(vite): import default from `vite-plugin-commonjs`
  packages/vite/package.json
  yarn.lock
Labels: release:fix

#8280 Only support TS test projects
  tasks/test-project/tasks.js
  tasks/test-project/test-project
Labels: release:chore

#8285 chore(cli): Add builder epilogue to experimental commands
  packages/cli/src/commands/experimental/setupOpentelemetry.js
  packages/cli/src/commands/experimental/studio.js
Labels: release:chore

#8288 chore: readme update core team and all contributors
  README.md
  tasks/all-contributors/.all-contributorsrc
Labels: release:chore

#7790 feature-experimental: add `exp setup-sentry` command
  packages/cli/src/commands/experimental/setupSentry.js
  packages/cli/src/commands/experimental/setupSentryHandler.js
  packages/cli/src/commands/experimental/templates/sentryApi.ts.template
  packages/cli/src/commands/experimental/templates/sentryWeb.ts.template
Labels: release:feature, fixture-ok

#8233 Fix GraphQL proxy in dev environments without IPv6
  .gitpod.yml
  packages/core/config/webpack.development.js
Labels: release:fix

#8297 Fix studio lint warning
  packages/studio/frontend/src/Components/SearchFilterBar.tsx
Labels: release:chore

#8298 fix(forms): disable webpack-dev-server overlay
  packages/core/config/webpack.development.js
Labels: release:fix

#8284 Recover lost connection
  packages/auth-providers/dbAuth/web/src/dbAuth.ts
Labels: release:fix

#8300 fix(cli): remove react 17/18 warning from canary upgrade
  packages/cli/src/commands/upgrade.js
Labels: release:fix

#8304 Fix broken link in project configuration docs page
  docs/docs/project-configuration-dev-test-build.mdx
Labels: release:docs

#8119 [Fastify] Extract logic into redwood plugin
  packages/cli/package.json
  packages/cli/src/commands/__tests__/serve.test.js
  packages/cli/src/commands/deploy/flightcontrol.js
  packages/cli/src/commands/deploy/render.js
  packages/cli/src/commands/experimental/setupServerFile.js
  packages/cli/src/commands/experimental/setupServerFileHandler.js
  packages/cli/src/commands/experimental/templates/server.ts.template
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveHandler.js
  packages/fastify/README.md
  packages/fastify/build.mjs
  packages/fastify/package.json
  packages/fastify/src/api.ts
  packages/fastify/src/config.ts
  packages/fastify/src/index.ts
  packages/fastify/src/lambda/index.ts
  packages/fastify/src/plugins/withApiProxy.ts
  packages/fastify/src/types.ts
  packages/fastify/src/web.ts
  packages/fastify/tsconfig.json
  yarn.lock
Labels: release:feature

#8309 fix(exp serve): pin redwood pkg versions
  packages/cli/src/commands/experimental/setupServerFileHandler.js
Labels: release:fix

#8313 Fix passwordless doc typos
  docs/docs/how-to/dbauth-passwordless.md
Labels: release:docs

#8334 fix(graphql-server): Disable the redwood opentelemetry plugin by default
  packages/graphql-server/src/functions/graphql.ts
Labels: release:fix

#8336 fix(canary): add back api server for yarn rw dev
  packages/cli/package.json
  yarn.lock
Labels: release:fix

#8234 feat(coherence deploy): add setup deploy coherence
  docs/docs/deploy/coherence.md
  docs/docs/deploy/introduction.md
  docs/sidebars.js
  packages/cli/src/commands/setup/deploy/providers/coherence.js
  packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
Labels: release:feature, fixture-ok

#8352 Update forms.md to fix small grammatical error
  docs/docs/forms.md
Labels: release:docs

#8351 fix(coherence): correct doc links, add commas to template
  docs/docs/deploy/coherence.md
  packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
Labels: release:fix, fixture-ok

#8339 Refactor GraphQL Server and CreateYoga to Support "api serve" with Fastify Server
  docs/docs/graphql.md
  packages/cli/src/commands/experimental/templates/server.ts.template
  packages/fastify/build.mjs
  packages/fastify/package.json
  packages/fastify/src/graphql.ts
  packages/fastify/src/index.ts
  packages/graphql-server/src/__tests__/cors.test.ts
  packages/graphql-server/src/__tests__/makeDirectives.test.ts
  packages/graphql-server/src/__tests__/makeMergedSchema.test.ts
  packages/graphql-server/src/__tests__/makeSubscriptions.test.ts
  packages/graphql-server/src/createGraphQLYoga.ts
  packages/graphql-server/src/functions/__tests__/authDecoders.test.ts
  packages/graphql-server/src/functions/__tests__/healthCheck.test.ts
  packages/graphql-server/src/functions/__tests__/readinessCheck.test.ts
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/functions/types.ts
  packages/graphql-server/src/functions/useRequireAuth.ts
  packages/graphql-server/src/index.ts
  packages/graphql-server/src/makeMergedSchema.ts
  packages/graphql-server/src/plugins/__tests__/useArmor.test.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodError.test.ts
  packages/graphql-server/src/plugins/useArmor.ts
  packages/graphql-server/src/plugins/useRedwoodAuthContext.ts
  packages/graphql-server/src/plugins/useRedwoodError.ts
  packages/graphql-server/src/plugins/useRedwoodGlobalContextSetter.ts
  packages/graphql-server/src/plugins/useRedwoodLogger.ts
  packages/graphql-server/src/plugins/useRedwoodPopulateContext.ts
  packages/graphql-server/src/subscriptions/makeSubscriptions.ts
  packages/graphql-server/src/types.ts
  packages/internal/src/generate/templates/api-globImports.d.ts.template
  yarn.lock
Labels: release:experiment

#8315 chore(package size): implement `findup-sync` in `@redwoodjs/project-config`
  .eslintrc.js
  packages/cli/package.json
  packages/cli/src/index.js
  packages/cli/src/lib/index.js
  packages/codemods/package.json
  packages/codemods/src/codemods/v0.37.x/addDirectives/addDirectives.ts
  packages/codemods/src/codemods/v0.37.x/updateApiImports/updateApiImports.yargs.ts
  packages/codemods/src/codemods/v0.37.x/updateForms/updateForms.yargs.ts
  packages/codemods/src/codemods/v0.37.x/updateScenarios/updateScenarios.yargs.ts
  packages/codemods/src/codemods/v0.38.x/renameApiProxyPath/renameApiProxyPath.ts
  packages/codemods/src/codemods/v0.38.x/updateScaffoldStyles/updateScaffoldStyles.ts
  packages/codemods/src/codemods/v0.38.x/updateSeedScript/updateSeedScript.ts
  packages/codemods/src/codemods/v0.39.x/updateBabelConfig/updateBabelConfig.ts
  packages/codemods/src/codemods/v0.39.x/updateCellMocks/updateCellMocks.yargs.ts
  packages/codemods/src/codemods/v0.39.x/updateRouterParamTypes/updateRouterParamTypes.yargs.ts
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/updateJestConfig.ts
  packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/renameVerifierTimestamp.yargs.ts
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/upgradeYarn.ts
  packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/updateDevFatalErrorPage.ts
  packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/tsconfigForRouteHooks.ts
  packages/codemods/src/codemods/v2.x.x/configureFastify/configureFastify.yargs.ts
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/updateResolverTypes.yargs.ts
  packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/updateClerkGetCurrentUser.yargs.ts
  packages/codemods/src/codemods/v4.x.x/useArmor/useArmor.yargs.ts
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/renameValidateWith.yargs.ts
  packages/codemods/src/codemods/v5.x.x/updateAuth0ToV2/updateAuth0ToV2.yargs.ts
  packages/codemods/src/codemods/v5.x.x/updateNodeEngineTo18/updateNodeEngineTo18.ts
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/upgradeToReact18.ts
  packages/codemods/src/lib/cells.ts
  packages/codemods/src/lib/getRWPaths.ts
  packages/codemods/src/lib/getRootPackageJSON.ts
  packages/codemods/src/lib/isTSProject.ts
  packages/codemods/src/lib/prettify.ts
  packages/codemods/src/lib/runTransform.ts
  packages/codemods/src/lib/ts2js.ts
  packages/codemods/src/testUtils/matchFolderTransform.ts
  packages/codemods/tasks/generateCodemod/templates/code/codemod.yargs.ts.template
  packages/codemods/tasks/generateCodemod/templates/structure/codemod.ts.template
  packages/internal/package.json
  packages/project-config/.dependency-cruiser.mjs
  packages/project-config/README.md
  packages/project-config/dependency-graph-dist.svg
  packages/project-config/dependency-graph-src.svg
  packages/project-config/package.json
  packages/project-config/src/configPath.ts
  packages/project-config/src/findUp.ts
  packages/project-config/src/index.ts
  packages/structure/package.json
  yarn.lock
Labels: release:chore

#8368 Fallback to auth-provider header case
  packages/api/src/auth/index.ts
Labels: release:fix

#8380 fix(coherence): fix health check path
  packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
Labels: release:fix, fixture-ok

#8374 feature: DRAFT - Support GraphQL Subscriptions on web side
  packages/internal/src/generate/graphqlSchema.ts
  packages/internal/src/gql.ts
  packages/web/src/apollo/index.tsx
  packages/web/src/apollo/typeOverride.ts
  packages/web/src/components/GraphQLHooksProvider.test.tsx
  packages/web/src/components/GraphQLHooksProvider.tsx
  packages/web/src/index.ts
Labels: release:feature

#8400 fix(cli) setup tsconfig update template path
  packages/cli/src/commands/setup/tsconfig/tsconfigHandler.js
Labels: release:fix, fixture-ok

#8342 feat(storybook): upgrade to v7
  __fixtures__/test-project/web/package.json
  packages/cli/src/commands/storybook.js
  packages/cli/src/commands/storybookHandler.js
  packages/testing/README.md
  packages/testing/config/storybook/main.js
  packages/testing/config/storybook/manager.example.js
  packages/testing/config/storybook/manager.js
  packages/testing/package.json
  packages/web/package.json
  packages/web/src/bins/build-storybook.ts
  packages/web/src/bins/storybook.ts
  tasks/smoke-test/playwright.config.ts
  tasks/smoke-test/tests/storybook.spec.ts
  yarn.lock
Labels: release:feature-breaking

#8385 feat(cli): Enable `host` option for `yarn rw serve`
  docs/docs/cli-commands.md
  packages/api-server/src/cliHandlers.ts
  packages/api-server/src/server.ts
  packages/api-server/src/watch.ts
  packages/cli/src/commands/__tests__/dev.test.js
  packages/cli/src/commands/__tests__/serve.test.js
  packages/cli/src/commands/devHandler.js
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveHandler.js
  packages/core/config/webpack.development.js
Labels: release:feature

#8375 fix(data-migrate): provide option to use db in dist instead of src
  packages/cli/src/commands/dataMigrate.js
  packages/cli/src/commands/dataMigrate/install.js
  packages/cli/src/commands/dataMigrate/installHandler.js
  packages/cli/src/commands/dataMigrate/up.js
  packages/cli/src/commands/dataMigrate/upHandler.js
  packages/cli/src/commands/generate/dataMigration/dataMigration.js
  packages/cli/src/index.js
Labels: release:fix, fixture-ok

#8407 Reserve h for help, and format docs
  docs/docs/cli-commands.md
  packages/api-server/src/cliHandlers.ts
  packages/api-server/src/watch.ts
  packages/cli/src/commands/serve.js
Labels: release:fix

#8353 Remove overly verbose data from custom formatter
  packages/api-server/src/__tests__/logFormatter.test.ts
  packages/api-server/src/logFormatter/formatters.ts
Labels: release:fix

#8406 fix(rebuild-fixture): add temporary step for Storybook v7
  __fixtures__/test-project/web/package.json
  tasks/test-project/test-project
Labels: release:chore

#8408 Corrects incorrect link to GraphIQL Headers documentation in Playground comment
  packages/graphql-server/src/createGraphQLYoga.ts
Labels: release:chore

#8427 fix(vite): Prerender media flashing
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/viteDistDir/build-manifest.json
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/webpackDistDir/build-manifest.json
  packages/prerender/src/babelPlugins/__tests__/babel-plugin-redwood-prerender-media-imports.test.ts
  packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts
  packages/prerender/src/runPrerender.tsx
Labels: release:fix

#8301 Make Vite the default bundler
  .github/actions/setup_test_project/setup_test_project.mjs
  .github/workflows/ci.yml
  .gitpod.yml
  __fixtures__/test-project/api/db/migrations/20220101190000_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220102190000_create_contact/migration.sql
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/entry-client.tsx
  __fixtures__/test-project/web/vite.config.ts
  nx.json
  package.json
  packages/cli/src/commands/devHandler.js
  packages/cli/src/commands/setup/vite/viteHandler.js
  packages/core/config/webpack.common.js
  packages/core/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/js/web/src/entry-client.jsx
  packages/create-redwood-app/templates/js/web/vite.config.js
  packages/create-redwood-app/templates/ts/web/package.json
  packages/create-redwood-app/templates/ts/web/src/entry-client.tsx
  packages/create-redwood-app/templates/ts/web/vite.config.ts
  packages/create-redwood-app/tests/template.test.js
  packages/internal/src/build/babel/web.ts
  packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts
  packages/prerender/src/runPrerender.tsx
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/config.ts
  packages/project-config/src/paths.ts
  packages/testing/package.json
  packages/vite/bins/rw-vite-dev.mjs
  packages/vite/package.json
  packages/vite/src/index.ts
  packages/vite/src/vite-plugin-jsx-loader.ts
  packages/vite/tsconfig.json
  packages/vite/vite-plugin-commonjs.d.ts
  packages/web/src/assetImports.ts
  tasks/smoke-test/playwright-fixtures/devServer.fixture.ts
  tasks/smoke-test/tests/authChecks.spec.ts
  tasks/smoke-test/tests/common.ts
  yarn.lock
Labels: release:feature-breaking
