Repository redwoodjs/graphql, pull requests merged in 2023-08, with the labels that each got.

#9007 fix(router): Prevent rerendering authenticated routes on hash change
  packages/router/src/AuthenticatedRoute.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/router.tsx
  packages/router/src/util.ts
Labels: release:fix

#8990 Docs: remove useless code in code snippet
  docs/docs/tutorial/chapter3/saving-data.md
Labels: release:docs

#8986 docs(fonts): Update @font-face recommendation
  docs/docs/assets-and-files.md
  docs/versioned_docs/version-6.0/assets-and-files.md
Labels: release:docs

#8987 Docs: Explain the entry.client.{jsx,tsx} file
  docs/docs/tutorial/chapter1/file-structure.md
Labels: release:docs

#9005 fix: Improve GraphQL Schema Validation to allow Subscription types when not using Realtime and ensure schema does not use reserved names
  packages/internal/src/__tests__/__snapshots__/validateSchemaForReservedNames.test.ts.snap
  packages/internal/src/__tests__/validateSchemaForAuthDirectives.test.ts
  packages/internal/src/__tests__/validateSchemaForReservedNames.test.ts
  packages/internal/src/project.ts
  packages/internal/src/validateSchema.ts
Labels: release:feature-breaking

#9014 fix(docs): update quick start to fix Storybook start up
  __fixtures__/test-project/README.md
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/components/AuthorCell/AuthorCell.stories.tsx
  __fixtures__/test-project/web/src/components/BlogPostCell/BlogPostCell.stories.tsx
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.stories.tsx
  __fixtures__/test-project/web/src/components/WaterfallBlogPostCell/WaterfallBlogPostCell.stories.tsx
  __fixtures__/test-project/web/src/index.css
  __fixtures__/test-project/web/src/pages/AboutPage/AboutPage.stories.tsx
  docs/docs/quick-start.md
  packages/create-redwood-app/templates/js/README.md
  packages/create-redwood-app/templates/ts/README.md
  tasks/test-project/rebuild-test-project-fixture.js
Labels: release:docs

#9004 fix(router): Do not reset scroll on url hash changes
  packages/router/src/__tests__/routeScrollReset.test.tsx
  packages/router/src/active-route-loader.tsx
  packages/router/src/location.tsx
  packages/router/src/util.ts
Labels: release:fix

#8978 feat(streaming-ssr): Fix build and server html injection
  packages/vite/ambient.d.ts
  packages/vite/bins/rw-vite-build.mjs
  packages/vite/src/buildFeServer.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/runRscFeServer.ts
  packages/vite/src/streaming/registerGlobals.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/vite/src/streaming/triggerRouteHooks.ts
  packages/vite/src/utils.ts
  packages/web/ambient.d.ts
  packages/web/package.json
  packages/web/src/components/MetaTags.tsx
  packages/web/src/components/PortalHead.tsx
  packages/web/src/components/RedwoodProvider.tsx
  packages/web/src/components/ServerInject.tsx
  packages/web/src/components/htmlTags.tsx
  packages/web/src/components/portalHead.test.tsx
  packages/web/src/index.ts
Labels: release:feature

#9025 Fix context in directive tests
  packages/graphql-server/src/plugins/useRedwoodDirective.ts
  packages/testing/src/api/directive.ts
Labels: release:fix

#9032 fix(graphql-server): Improve GraphQL API performance by not accessing project config in makeMergedSchema
  packages/graphql-server/package.json
  packages/graphql-server/src/makeMergedSchema.ts
Labels: release:fix

#9031 Remove `.only` from `createCell` test
  packages/web/src/components/createCell.test.tsx
Labels: bug/confirmed, release:chore

#9039 fix(graphql-server): Move yoga creation to avoid creation on every request
  packages/graphql-server/src/functions/graphql.ts
Labels: release:fix

#9038 exp(streaming): Allow SSR with experimental apollo client
  packages/vite/ambient.d.ts
  packages/vite/src/streaming/registerGlobals.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/web/ambient.d.ts
  packages/web/package.json
  packages/web/src/apollo/suspense.tsx
  packages/web/src/components/CellErrorBoundary.tsx
  packages/web/src/components/PortalHead.tsx
  packages/web/src/components/createCell.test.tsx
  packages/web/src/components/createCell.tsx
  packages/web/src/streamUtils/useDocumentReady.ts
  yarn.lock
Labels: release:feature

#9047 feat(streaming): Cleanup/Unify streaming dev and prod server
  packages/internal/src/routes.ts
  packages/project-config/src/paths.ts
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/registerGlobals.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/vite/src/types.ts
  packages/web/src/apollo/links.tsx
  packages/web/src/apollo/suspense.tsx
  tasks/framework-tools/frameworkSyncToProject.mjs
Labels: release:feature

#9048 Docs: Update prerender.md to fix typo
  docs/docs/prerender.md
Labels: release:docs

#9053 fix(codemod): Fix replace-component-svgs codemod to deal with re-exported
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/input/redwood.toml
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/input/web/src/components/Icons/Icons.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/input/web/src/components/Icons/currency-yen.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/input/web/src/components/Icons/cursor-click.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/input/web/src/components/Icons/database.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/input/web/src/components/Icons/device-mobile.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/input/web/src/components/other/desktop-computer.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/redwood.toml
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/Icons/CurrencyYenSVG.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/Icons/CursorClickSVG.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/Icons/DatabaseSVG.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/Icons/DeviceMobileSVG.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/Icons/Icons.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/Icons/currency-yen.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/Icons/cursor-click.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/Icons/database.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/Icons/device-mobile.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/other/DesktopComputerSVG.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/reExported/output/web/src/components/other/desktop-computer.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__tests__/replaceComponentSvgs.test.ts
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/replaceComponentSvgs.ts
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/replaceComponentSvgs.yargs.ts
Labels: release:fix

#9009 feat: Support GraphQL Subscriptions in Apollo Client using SSE links
  packages/cli/src/commands/experimental/templates/liveQueries/auctions/auctions.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/newMessage/newMessage.ts.template
  packages/fastify/src/graphql.ts
  packages/graphql-server/package.json
  packages/graphql-server/src/createGraphQLYoga.ts
  packages/realtime/package.json
  packages/realtime/src/graphql/plugins/useRedwoodRealtime.ts
  packages/studio/frontend/package.json
  packages/studio/package.json
  packages/web/package.json
  packages/web/src/apollo/index.tsx
  packages/web/src/apollo/sseLink.tsx
  packages/web/src/apollo/suspense.tsx
  yarn.lock
Labels: release:feature

#9076 fix: resolves Tailwind setup command failing due to unsupported prettier-plugin-tailwindcss v0.5
  __fixtures__/test-project/web/package.json
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
  tasks/test-project/tasks.js
  tasks/test-project/tui-tasks.js
Labels: release:fix

#9079 Limit the directories searched through for directory named modules
  packages/internal/src/files.ts
Labels: release:fix

#9087 fix(data-migrate): add `dotenv-defaults`, properly plug into CLI
  packages/cli-packages/dataMigrate/e2eTest.mjs
  packages/cli-packages/dataMigrate/package.json
  packages/cli-packages/dataMigrate/src/bin.ts
  packages/cli-packages/dataMigrate/src/index.ts
  packages/cli/src/plugin.js
  yarn.lock
Labels: release:fix

#9074 feat(streaming): Make Cells render on the server with useBackgroundQuery and useReadQuery
  packages/web/jest.config.js
  packages/web/src/apollo/index.tsx
  packages/web/src/apollo/suspense.tsx
  packages/web/src/apollo/typeOverride.ts
  packages/web/src/components/GraphQLHooksProvider.tsx
  packages/web/src/components/cell/CellCacheContext.tsx
  packages/web/src/components/cell/CellErrorBoundary.tsx
  packages/web/src/components/cell/cellTypes.tsx
  packages/web/src/components/cell/createCell.test.tsx
  packages/web/src/components/cell/createCell.tsx
  packages/web/src/components/cell/createSuspendingCell.test.tsx
  packages/web/src/components/cell/createSuspendingCell.tsx
  packages/web/src/components/cell/isCellEmpty.tsx
  packages/web/src/components/createCell.tsx
  packages/web/src/index.ts
Labels: release:feature

#9080 fix(docs): Correct documentation for `validateSync` and `validateWithSync`
  docs/docs/services.md
Labels: release:docs

#8974 Docs: Update authentication.md
  docs/docs/tutorial/chapter4/authentication.md
Labels: release:docs

#9099 Fix yarn lint warnings regarding {}
  packages/graphql-server/ambient.d.ts
  packages/studio/backend/fastify/yoga.ts
  packages/studio/backend/graphql/yoga.ts
  packages/vite/src/waku-lib/rsc-handler.ts
Labels: release:chore

#9085 chore(cli): make `@redwoodjs/cli-data-migrate` package size smaller
  packages/babel-config/dist.test.ts
  packages/babel-config/package.json
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-mock-cell-data.test.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-mock-cell-data.ts
  packages/babel-config/tsconfig.json
  packages/cli-packages/dataMigrate/package.json
  packages/cli-packages/dataMigrate/src/__tests__/install.test.ts
  packages/cli-packages/dataMigrate/src/__tests__/up.test.ts
  packages/cli-packages/dataMigrate/src/commands/install.ts
  packages/cli-packages/dataMigrate/src/commands/installHandler.ts
  packages/cli-packages/dataMigrate/src/commands/up.ts
  packages/cli-packages/dataMigrate/src/commands/upHandler.ts
  packages/cli-packages/dataMigrate/tsconfig.json
  yarn.lock
Labels: release:chore

#9066 fix(dev): Do not change origin on proxy in dev
  packages/vite/src/index.ts
Labels: release:fix

#9106 feat(Cell Suspense): Allow Cells to not Suspend
  packages/web/src/components/cell/cellTypes.tsx
  packages/web/src/components/cell/createSuspendingCell.tsx
Labels: release:feature

#9050 Minor form improvements
  packages/forms/src/__tests__/form.test.tsx
  packages/forms/src/index.tsx
Labels: release:fix

#9111 fix(create-redwood-app): fix typo in doc template
  __fixtures__/test-project/.redwood/README.md
  packages/create-redwood-app/templates/js/.redwood/README.md
  packages/create-redwood-app/templates/ts/.redwood/README.md
Labels: release:fix
