Repository redwoodjs/graphql, pull requests merged in 2023-02, with the labels that each got.

#7527 hotfix(ts): Add temporary work around for defineScenario typedef
  packages/testing/src/api/scenario.ts
Labels: release:fix

#7529 feat(cli): Additional post upgrade messages
  packages/cli/src/commands/upgrade.js
Labels: release:feature

#7528 Clerk docs: Update to use new env vars
  docs/docs/auth/clerk.md
Labels: release:docs

#7547 Docs: Add missing groupId to <Tabs>
  docs/docs/tutorial/chapter3/saving-data.md
  docs/docs/tutorial/chapter6/comments-schema.md
  docs/versioned_docs/version-4.0/tutorial/chapter3/saving-data.md
  docs/versioned_docs/version-4.0/tutorial/chapter6/comments-schema.md
Labels: release:docs

#7511 Update cli-commands.md
  docs/docs/cli-commands.md
Labels: release:docs

#7536 feat(telemetry): Capture bundler flag
  packages/telemetry/src/sendTelemetry.ts
Labels: release:chore

#7554 fix(vite): Fix Vite entry point on windows
  packages/vite/src/index.ts
Labels: release:fix

#7544 Clerk docs updates, take 2
  docs/docs/auth/clerk.md
Labels: release:docs

#7560 fix(auth): handle CRLFs in `yarn rw setup auth`
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/authTasks.ts
Labels: release:fix, fixture-ok

#7563 fix(docs): finish custom auth docs on authDecoder
  docs/docs/auth/custom.md
Labels: release:docs

#7565 Fix validation types and tests
  packages/api/src/validations/__tests__/validations.test.js
  packages/api/src/validations/validations.ts
Labels: release:fix

#7577 Set.tsx: Improve code comments
  packages/router/src/Set.tsx
Labels: release:chore

#7576 fix(vite): A few fixes for vite
  packages/vite/src/index.ts
Labels: release:fix

#7551 fix(clerk): check if we're prerendering in Clerk client getter
  packages/auth-providers/clerk/web/src/clerk.tsx
Labels: release:fix

#7572 Truly optional auth decoder
  packages/api/src/auth/__tests__/getAuthenticationContext.test.ts
  packages/api/src/auth/index.ts
  packages/graphql-server/src/functions/__tests__/fixtures/auth.ts
  packages/graphql-server/src/functions/__tests__/useRequireAuth.test.ts
  packages/graphql-server/src/functions/useRequireAuth.ts
Labels: release:fix

#7564 getDuplicateRoutes: Ignore redirects and other unnamed routes
  packages/internal/src/__tests__/routes-mocked.test.ts
  packages/internal/src/routes.ts
Labels: release:fix

#7598 Add back `buildType: nixpacks` per Flightcontrol request
  packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
Labels: release:fix, fixture-ok

#7607 Reinforce the constness of notAuthenticatedState
  packages/auth/src/AuthProvider/useReauthenticate.ts
Labels: release:chore

#7608 Check if client has loaded before saying that loading is finished
  packages/auth-providers/clerk/setup/src/templates/web/auth.tsx.template
  packages/auth-providers/clerk/web/src/clerk.tsx
  packages/auth/src/AuthImplementation.ts
  packages/auth/src/AuthProvider/useReauthenticate.ts
Labels: release:fix

#7606 fix(vite): Respect `host`, `sourceMap` settings in redwood.toml on vite dev server
  packages/vite/src/index.ts
Labels: release:fix

#7621 fix(telemetry): Avoid getConfig for CRWA
  packages/telemetry/src/sendTelemetry.ts
Labels: release:fix

#7627 Update CORS docs to reflect Redwood 4 changes
  docs/docs/cors.md
Labels: release:docs

#7605 fix(generator): add dotAll to Router regex
  packages/cli/src/lib/index.js
Labels: release:fix, fixture-ok

#7633 fix(ts): Undo skipLibCheck change
  packages/create-redwood-app/template/api/tsconfig.json
  packages/create-redwood-app/template/web/tsconfig.json
Labels: release:fix, fixture-ok

#7634 fix(docs): typo in `GraphQL` docs
  docs/docs/graphql.md
Labels: release:docs

#7623 chore(CI): CI telemetry checking
  .github/actions/telemetry_check/check.mjs
  .github/workflows/ci.yml
  packages/telemetry/src/sendTelemetry.ts
Labels: release:chore

#7638 feat(api): support building .jsx, .tsx files
  packages/internal/src/files.ts
Labels: release:feature

#7639 fix:(webAuthn) use `globalThis`, not `process.env`
  packages/auth-providers/dbAuth/web/src/__tests__/webAuthn.test.ts
  packages/auth-providers/dbAuth/web/src/webAuthn.ts
Labels: release:fix, fixture-ok

#7573 7482/validators exclude include caseinsensitive
  docs/docs/services.md
  packages/api/src/validations/__tests__/validations.test.js
  packages/api/src/validations/validations.ts
Labels: release:feature

#7640 Get rid of red squiggles in new lambda functions
  packages/cli/src/commands/generate/function/__tests__/__snapshots__/function.test.ts.snap
  packages/cli/src/commands/generate/function/templates/function.ts.template
Labels: release:chore, fixture-ok

#7658 Fix the world's most minor typo (txs -> tsx)
  docs/docs/tutorial/chapter6/the-redwood-way.md
Labels: release:docs

#7646 Update useRequireAuth docs to v4 auth
  docs/docs/serverless-functions.md
Labels: release:docs

#7656 Forms: Export EmptyAsValue
  packages/forms/src/index.tsx
Labels: release:feature

#7649 chore(deps): bump setup of Chakra UI to V2
  packages/cli/src/commands/setup/ui/libraries/chakra-ui.js
Labels: release:feature-breaking, fixture-ok

#7668 fix(clerk): Remove privateMetadata property from getCurrentUser
  packages/auth-providers/clerk/setup/src/templates/api/lib/auth.ts.template
Labels: release:fix

#7660 Fix `yarn rw exec` to set nonzero exit code on error
  packages/cli/src/commands/execHandler.js
Labels: release:fix

#7670 Update directives.md
  docs/docs/directives.md
Labels: release:docs

#7676 chore: add codemod for clerk fix in v4.2.0
  packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/__tests__/updateClerkGetCurrentUser.test.ts
  packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/updateClerkGetCurrentUser.ts
  packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/updateClerkGetCurrentUser.yargs.ts
Labels: release:chore
