Repository redwoodjs/graphql, pull requests merged in 2023-07, with the labels that each got.

#8801 fix(docs): remove the section on configuring Storybook's manager
  docs/docs/storybook.md
Labels: release:docs

#8805 structure: Update lru-cache to v7 to minimize project:copy issues
  packages/structure/package.json
  packages/structure/src/x/ts-morph.ts
  yarn.lock
Labels: release:chore

#8775 Disable prerender when streamingSsr is enabled
  packages/cli/src/commands/prerenderHandler.js
  packages/router/ambient.d.ts
  packages/router/src/active-route-loader.tsx
Labels: release:fix

#8807 "Cleaning web" is only needed for Webpack
  packages/cli/src/commands/buildHandler.js
Labels: release:fix

#8806 Use existing rw-vite-build bin for SSR as well
  packages/cli/src/commands/buildHandler.js
  packages/vite/bins/rw-vite-build.mjs
  packages/vite/src/index.ts
Labels: release:chore

#8808 entry.server and entry.client
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/vite/src/buildFeServer.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/runFeServer.ts
Labels: release:fix

#8809 fix(cli): Prevent multiple update available messages
  packages/cli/src/lib/__tests__/locking.test.js
  packages/cli/src/lib/__tests__/updateCheck.test.js
  packages/cli/src/lib/locking.js
  packages/cli/src/lib/updateCheck.js
Labels: release:fix

#8810 Add files needed for React Streaming SSR
  packages/cli/src/commands/experimental/setupStreamingSsrHandler.js
  packages/cli/src/commands/experimental/templates/streamingSsr/Document.tsx.template
  packages/cli/src/commands/experimental/templates/streamingSsr/entry.client.tsx.template
  packages/cli/src/commands/experimental/templates/streamingSsr/entry.server.tsx.template
Labels: release:feature

#8811 Streaming SSR: Fix build, serve and dev
  packages/cli/src/commands/serve.js
  packages/vite/src/devFeServer.ts
  packages/vite/src/runFeServer.ts
Labels: release:feature

#8812 Rudimentary CSS check in our smoke tests
  tasks/smoke-tests/common.ts
Labels: release:chore

#8791 feat: Configure In-Memory or Redis-backed GraphQL Live Query and Subscriptions
  packages/cli/src/commands/experimental/setupRealtimeHandler.js
  packages/cli/src/commands/experimental/templates/realtime.ts.template
  packages/cli/src/commands/experimental/templates/server.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/blank/blank.service.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/blank/blank.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/newMessage/newMessage.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/newMessage/rooms.ts.template
  packages/graphql-server/package.json
  packages/graphql-server/src/index.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodRealtime.test.ts
  packages/graphql-server/src/plugins/useRedwoodRealtime.ts
  yarn.lock
Labels: release:feature

#8815 feat: Support Authentication in Realtime Subscriptions
  packages/cli/src/commands/experimental/templates/liveQueries/auctions/auctions.sdl.ts.template
  packages/cli/src/commands/experimental/templates/liveQueries/auctions/auctions.ts.template
  packages/cli/src/commands/experimental/templates/liveQueries/blank/blank.sdl.ts.template
  packages/cli/src/commands/experimental/templates/liveQueries/blank/blank.service.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/blank/blank.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/countdown/countdown.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/newMessage/newMessage.ts.template
  packages/graphql-server/src/index.ts
  packages/graphql-server/src/plugins/useRedwoodDirective.ts
  packages/internal/src/validateSchema.ts
Labels: release:feature

#8818 ViteBuildManifest and note about import-attributes
  packages/vite/src/buildFeServer.ts
  packages/vite/src/runFeServer.ts
Labels: release:chore

#8790 feat(cli): Add README to .redwood
  __fixtures__/test-project/.gitignore
  __fixtures__/test-project/.redwood/README.md
  packages/create-redwood-app/templates/js/.redwood/README.md
  packages/create-redwood-app/templates/js/gitignore.template
  packages/create-redwood-app/templates/ts/.redwood/README.md
  packages/create-redwood-app/templates/ts/gitignore.template
  tasks/test-project/rebuild-test-project-fixture.js
Labels: release:feature

#8798 fix(cli): Telemetry improvements
  packages/cli/src/index.js
  packages/cli/src/telemetry/index.js
  packages/cli/src/telemetry/send.js
Labels: release:fix

#8825 fix(cli): Revert change to prisma error message
  packages/cli/src/commands/prismaHandler.js
Labels: release:fix

#8826 React 18.3.0-canary-035a41c4e-20230704
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/studio/frontend/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore

#8827 Use "import type" for all types
  packages/vite/src/triggerRouteHooks.ts
Labels: release:chore

#8829 fix(deploy): add hack for netlify deploy with realtime changes
  packages/graphql-server/package.json
  packages/graphql-server/src/plugins/useRedwoodRealtime.ts
Labels: release:fix

#8830 Add babel plugin to internal deps
  __fixtures__/test-project/web/package.json
  packages/core/package.json
  packages/internal/package.json
  yarn.lock
Labels: release:chore

#8831 Fix babel devDeps in internal
  packages/core/package.json
  packages/internal/package.json
  yarn.lock
Labels: release:chore

#8832 chore: use renamed babel plugin packages
  babel.config.js
  package.json
  packages/internal/package.json
  packages/internal/src/build/babel/api.ts
  packages/internal/src/build/babel/common.ts
  packages/internal/src/build/babel/web.ts
  yarn.lock
Labels: release:fix

#8838 fix: Fixes and simplifies the Countdown subscription example for Realtime
  packages/cli/src/commands/experimental/templates/subscriptions/countdown/countdown.ts.template
Labels: release:feature

#8828 cli(fix): Stop storybook command installing early
  packages/cli-packages/storybook/package.json
  packages/cli/src/plugin.js
  yarn.lock
Labels: release:fix

#8451 React Server Components (RSC)
  packages/vite/ambient.d.ts
  packages/vite/bins/rw-vite-build.mjs
  packages/vite/modules.d.ts
  packages/vite/package.json
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/client.ts
  packages/vite/src/react-server-dom-webpack/node-loader.ts
  packages/vite/src/runRscFeServer.ts
  packages/vite/src/waku-lib/build-server.ts
  packages/vite/src/waku-lib/builder.ts
  packages/vite/src/waku-lib/config.ts
  packages/vite/src/waku-lib/rsc-handler-worker.ts
  packages/vite/src/waku-lib/rsc-handler.ts
  packages/vite/src/waku-lib/rsc-utils.ts
  packages/vite/src/waku-lib/vite-plugin-rsc.ts
  packages/vite/src/waku-server.ts
  packages/vite/tsconfig.json
  packages/web/src/global.web-auto-imports.ts
  yarn.lock
Labels: release:feature

#8839 Oauth How-to: Adds note about not exposing accessToken via SDL
  docs/docs/how-to/oauth.md
  docs/versioned_docs/version-3.x/how-to/oauth.md
  docs/versioned_docs/version-4.x/how-to/oauth.md
  docs/versioned_docs/version-5.0/how-to/oauth.md
Labels: release:docs

#8686 feature(#8676): added usernameMatch criteria to login methods to match signup
  docs/docs/auth/dbauth.md
  package.json
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
  yarn.lock
Labels: release:feature

#8778 Modified contributing docs for the Create Redwood App
  packages/create-redwood-app/README.md
Labels: topic/docs, topic/crwa, release:docs

#8777 Added documentation for the Create Redwood App
  docs/docs/create-redwood-app.md
  docs/sidebars.js
Labels: topic/docs, topic/crwa, release:docs

#8844 chore: try running CI on pushes to next and release branches
  .github/workflows/ci.yml
Labels: release:chore

#8673 Additional Messaging for Compatibility Checking for Create Redwood App
  docs/docs/how-to/using-nvm.md
  docs/docs/how-to/using-yarn.md
  docs/docs/tutorial/chapter1/prerequisites.md
  packages/create-redwood-app/src/create-redwood-app.js
Labels: topic/crwa, release:feature

#8837 experimental feature flag for rsc
  packages/cli/src/commands/experimental/setupRsc.js
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/templates/rsc/App.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/Counter.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/entries.ts.template
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
  packages/router/ambient.d.ts
  packages/vite/src/index.ts
  packages/web/ambient.d.ts
  packages/web/src/config.ts
Labels: release:experiment

#8851 Update entry.client and disable vite legacy mode
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/templates/rsc/entry.client.tsx.template
  packages/vite/src/index.ts
Labels: release:fix

#8853 yarn rw upgrade: Not < v1 anymore
  packages/cli/src/commands/upgrade.js
Labels: release:fix

#8855 rw upgrade: Update package versions from template package.json
  packages/cli/src/commands/upgrade.js
Labels: release:feature

#8857 fix(v6, serverless): use named exports instead of default
  packages/cli/src/commands/deploy/__tests__/nftPack.test.js
  packages/cli/src/commands/deploy/packing/nft.js
  packages/cli/src/commands/deploy/serverless.js
Labels: release:fix

#8856 chore(renovate): audit `renovate.json`
  .github/renovate.json
  package.json
  packages/cli/package.json
  packages/structure/package.json
  packages/studio/frontend/package.json
  packages/studio/frontend/yarn.lock
  tasks/check/package.json
  tasks/check/yarn.lock
  yarn.lock
Labels: release:chore

#8859 chore(renovate): improve config to reduce noise
  .github/renovate.json
Labels: release:chore

#8862 chore(gh-actions) Dry-run publish to get next canary version
  .github/workflows/publish-canary.yml
Labels: release:chore

#8863 CRWA: Manually update rw package versions to v6 canary
  packages/create-redwood-app/templates/js/api/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/api/package.json
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-app/templates/ts/web/package.json
Labels: release:feature, fixture-ok

#8864 gh actions: Explain the publish dryrun command
  .github/workflows/publish-canary.yml
Labels: release:chore

#8865 push CRWA package version changes
  .github/workflows/publish-canary.yml
Labels: release:chore

#8866 GH Action: Set git config
  .github/workflows/publish-canary.yml
Labels: release:chore

#8867 Don't git push. Remove debug logs
  .github/workflows/publish-canary.yml
Labels: release:chore

#8868 GH Action: Increase commit count based version by one
  .github/workflows/publish-canary.yml
Labels: release:chore

#8869 CRWA use RW v5.4.3
  packages/create-redwood-app/templates/js/api/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/api/package.json
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-app/templates/ts/web/package.json
Labels: release:chore, fixture-ok

#8877 chore(ci): move canary publishing script to file
  .github/scripts/publish_canary.sh
  .github/workflows/publish-canary.yml
Labels: release:chore

#8882 Include standard vite config in RSC build
  packages/vite/src/buildRscFeServer.ts
Labels: release:feature

#8887 RSC: Initial css support
  packages/vite/package.json
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/fully-react/DevRwRscServerGlobal.ts
  packages/vite/src/fully-react/ProdRwRscServerGlobal.ts
  packages/vite/src/fully-react/RwRscServerGlobal.ts
  packages/vite/src/fully-react/assets.tsx
  packages/vite/src/fully-react/find-styles.ts
  packages/vite/src/fully-react/findAssetsInManifest.ts
  packages/vite/src/fully-react/rwRscGlobal.ts
  packages/vite/src/runRscFeServer.ts
  packages/vite/src/waku-lib/build-server.ts
Labels: release:feature

#8888 RSC: Include entries.ts in paths
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/waku-lib/rsc-handler-worker.ts
Labels: release:chore

#8894 RSC: Fix experimental setup
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/project-config/src/paths.ts
Labels: release:fix

#8893 RSC: Build using rw build
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/rscBuild.ts
Labels: release:feature

#8897 RSC: Use rw serve
  packages/cli/src/commands/serve.js
Labels: release:feature

#8896 RSC build without user config
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/index.ts
Labels: release:fix

#8898 Proofreading updates to the CRWA docs
  docs/docs/create-redwood-app.md
Labels: release:docs

#8885 Update intermission.md including a caution block to let the reader know not to look for a Typescript version
  docs/docs/tutorial/intermission.md
Labels: release:docs

#8895 docs: update ArticleQuery type in routing-params.md
  docs/docs/tutorial/chapter2/routing-params.md
Labels: release:docs

#8892 docs(services): fix numericality validation example
  docs/docs/services.md
Labels: release:docs

#8870 CRWA: --yes
  docs/docs/create-redwood-app.md
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:feature

#8905 RSC: Add css files to the example
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/templates/rsc/App.css.template
  packages/cli/src/commands/experimental/templates/rsc/App.module.css.template
  packages/cli/src/commands/experimental/templates/rsc/App.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/Counter.css.template
  packages/cli/src/commands/experimental/templates/rsc/Counter.module.css.template
  packages/cli/src/commands/experimental/templates/rsc/Counter.tsx.template
Labels: release:feature

#8906 RSC fix: setup description
  packages/cli/src/commands/experimental/setupRscHandler.js
Labels: release:fix

#8904 Update name reference in Redwood Docs
  docs/docs/tutorial/chapter2/getting-dynamic.md
Labels: release:docs

#8922 fix(ssr): Get experimental ssr setup working properly
  packages/cli/src/commands/__tests__/dev.test.js
  packages/cli/src/commands/devHandler.js
  packages/cli/src/commands/experimental/templates/streamingSsr/entry.client.tsx.template
  packages/cli/src/commands/experimental/templates/streamingSsr/entry.server.tsx.template
  packages/vite/src/devFeServer.ts
  packages/web/src/components/DevFatalErrorPage.tsx
  packages/web/src/serverContext.tsx
Labels: release:fix

#8924 chore(v6): add codemod changing `global` to `globalThis`
  packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/README.md
  packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/__tests__/changeGlobalToGlobalThis.test.ts
  packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/changeGlobalToGlobalThis.ts
  packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/changeGlobalToGlobalThis.yargs.ts
Labels: release:chore

#8929 Vite plugin to replace env vars in index.html
  packages/vite/src/index.ts
Labels: release:fix

#8930 Remove warning message about jsx in js files
  packages/cli/src/commands/devHandler.js
Labels: release:fix

#8935 Update svgr codemod to output TS for tsx inputs
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/output/mySvgs/Kitten1SVG.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/output/mySvgs/Kitten1SVG.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/output/mySvgs/LogoSVG.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/output/mySvgs/LogoSVG.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/input/AsRenderProp.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/input/Simple.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/output/AsRenderProp.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/output/Simple.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/output/web/src/mySvgs/Kitten1WithDashesSVG.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/output/web/src/mySvgs/Kitten1WithDashesSVG.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/output/web/src/mySvgs/LogoSVG.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/output/web/src/mySvgs/LogoSVG.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/replaceComponentSvgs.ts
Labels: release:fix

#8928 Expose environment variables also on import.meta.env
  packages/vite/package.json
  packages/vite/src/index.ts
  yarn.lock
Labels: release:fix

#8925 fix(graphql-server): Allow correct context behaviour in testing
  __fixtures__/test-project/api/src/__tests__/context.test.ts
  packages/graphql-server/src/functions/__tests__/globalContext.test.ts
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/functions/useRequireAuth.ts
  packages/graphql-server/src/globalContext.ts
  packages/graphql-server/src/globalContextStore.ts
  packages/graphql-server/src/index.ts
  packages/testing/config/jest/api/jest.setup.js
  packages/testing/src/api/directive.ts
  tasks/framework-tools/frameworkSyncToProject.mjs
  tasks/test-project/rebuild-test-project-fixture.js
  tasks/test-project/templates/api/context.test.ts.template
  tasks/test-project/tui-tasks.js
Labels: release:fix

#8926 chore(v6): change to React automatic runtime
  babel.config.js
  packages/internal/src/__tests__/nestedPages.test.ts
  packages/internal/src/build/babel/web.ts
Labels: release:feature-breaking

#8936 serve web: Fix socket support
  packages/cli/src/commands/serveHandler.js
Labels: release:fix

#8803 chore(cli-storybook): Add telemetry
  packages/cli-packages/storybook/package.json
  packages/cli-packages/storybook/src/commands/storybook.ts
  packages/cli-packages/storybook/src/commands/storybookHandler.ts
  packages/cli/src/telemetry/index.js
  yarn.lock
Labels: release:chore

#8949 RSC fix typo in example code
  packages/cli/src/commands/experimental/templates/rsc/entry.client.tsx.template
Labels: release:fix

#8948 RSC: react-server condition. Poisoned imports
  packages/vite/src/rscBuild.ts
  packages/vite/src/waku-lib/build-server.ts
  packages/vite/src/waku-lib/rsc-handler-worker.ts
Labels: release:feature

#8947 fix(cli): Escape telemetry in exec command
  packages/cli/package.json
  packages/cli/src/commands/execHandler.js
  packages/cli/src/telemetry/exporter.js
  yarn.lock
Labels: release:fix

#8944 @rwjs/vite: Pin acorn-loose version
  packages/vite/package.json
  yarn.lock
Labels: release:chore

#8878 fix(v6): Refactor Redwood Realtime as a new redwoodjs/realtime package to better handle dependencies
  packages/cli/src/commands/experimental/setupRealtimeHandler.js
  packages/cli/src/commands/experimental/templates/realtime.ts.template
  packages/fastify/src/graphql.ts
  packages/graphql-server/package.json
  packages/graphql-server/src/createGraphQLYoga.ts
  packages/graphql-server/src/index.ts
  packages/graphql-server/src/plugins/index.ts
  packages/graphql-server/src/subscriptions/makeSubscriptions.ts
  packages/graphql-server/src/types.ts
  packages/internal/src/generate/graphqlSchema.ts
  packages/realtime/.babelrc.js
  packages/realtime/README.md
  packages/realtime/build.mjs
  packages/realtime/package.json
  packages/realtime/src/graphql/index.ts
  packages/realtime/src/graphql/plugins/__fixtures__/common.ts
  packages/realtime/src/graphql/plugins/__tests__/__snapshots__/useRedwoodRealtime.test.ts.snap
  packages/realtime/src/graphql/plugins/__tests__/useRedwoodRealtime.test.ts
  packages/realtime/src/graphql/plugins/useRedwoodRealtime.ts
  packages/realtime/src/index.ts
  packages/realtime/tsconfig.json
  yarn.lock
Labels: release:fix

#8916 @redwoodjs/web-server
  packages/cli/src/commands/__tests__/serve.test.js
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveHandler.js
  packages/core/package.json
  packages/core/src/bins/rw-web-server.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/runRscFeServer.ts
  packages/web-server/.babelrc.js
  packages/web-server/README.md
  packages/web-server/ambient.d.ts
  packages/web-server/build.mjs
  packages/web-server/package.json
  packages/web-server/src/server.ts
  packages/web-server/src/web.ts
  packages/web-server/src/withApiProxy.ts
  packages/web-server/tsconfig.json
  yarn.lock
Labels: release:chore

#8950 fix(rw serve): conditionally import `@redwoodjs/realtime`
  packages/fastify/src/graphql.ts
Labels: release:fix

#8952 web-server: Print localhost instead of 0.0.0.0
  packages/web-server/src/server.ts
Labels: release:fix

#8958 Refactor cli serve command
  packages/cli/src/commands/__tests__/serve.test.js
  packages/cli/src/commands/deploy/flightcontrol.js
  packages/cli/src/commands/deploy/render.js
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveApiHandler.js
  packages/cli/src/commands/serveBothHandler.js
  packages/cli/src/commands/serveHandler.js
  packages/cli/src/commands/serveWebHandler.js
Labels: release:chore

#8954 Update Tailwind setup. Show extensions to install
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
Labels: release:feature, fixture-ok

#8960 docs: Change ref to webpack -> vite. Update url
  docs/docs/tutorial/chapter1/file-structure.md
Labels: release:docs

#8956 CRWA: Move git init to include yarn.lock
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#8961 RSC: Fix noExternal rule for server build
  packages/vite/src/rscBuild.ts
  packages/vite/src/waku-lib/build-server.ts
  packages/vite/src/waku-lib/rsc-handler-worker.ts
Labels: release:fix

#8955 CRWA: Prompt for installation dir
  packages/create-redwood-app/package.json
  packages/create-redwood-app/src/create-redwood-app.js
  yarn.lock
Labels: release:feature

#8957 Update SuperTokens dependencies
  packages/auth-providers/supertokens/api/package.json
  packages/auth-providers/supertokens/setup/src/__tests__/__snapshots__/setupHandler.test.ts.snap
  packages/auth-providers/supertokens/setup/src/setupHandler.ts
  packages/auth-providers/supertokens/setup/src/templates/api/lib/supertokens.ts.template
  packages/auth-providers/supertokens/setup/src/templates/web/auth.tsx.template
  packages/auth-providers/supertokens/web/package.json
  packages/auth-providers/supertokens/web/src/supertokens.ts
  yarn.lock
Labels: release:feature-breaking

#8971 fix(supertokens): improve setup and fix lint errors
  packages/auth-providers/supertokens/setup/src/__tests__/__snapshots__/setupHandler.test.ts.snap
  packages/auth-providers/supertokens/setup/src/__tests__/setupHandler.test.ts
  packages/auth-providers/supertokens/setup/src/setupHandler.ts
  packages/auth-providers/supertokens/setup/src/templates/api/lib/supertokens.ts.template
  packages/cli-helpers/src/auth/authTasks.ts
  packages/cli-helpers/src/lib/installHelpers.ts
  packages/cli-helpers/src/lib/paths.ts
  packages/cli-helpers/src/lib/project.ts
Labels: release:fix, fixture-ok

#8976 fix(firebase): improve error handling
  packages/auth-providers/firebase/api/src/decoder.ts
  packages/auth-providers/firebase/setup/src/setupHandler.ts
Labels: release:fix

#8979 RSC: Use experimental node loader
  packages/cli/src/commands/serveBothHandler.js
  packages/vite/package.json
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/waku-lib/node-loader.ts
Labels: release:fix

#8980 Webpack: Use resolve-url-loader to handle absolute paths in css url()
  packages/core/config/webpack.common.js
  packages/core/package.json
  yarn.lock
Labels: release:fix

#8977 fix(cli): Prevent unwanted SIGINT error message from storybook
  packages/cli-packages/storybook/src/commands/storybook.ts
  packages/cli/src/telemetry/index.js
Labels: release:fix

#8959 docs: Update file structure
  docs/docs/tutorial/chapter1/file-structure.md
Labels: release:docs

#8982 fix(crwa): use JSDoc in JS template for vite config
  packages/create-redwood-app/templates/js/web/vite.config.js
  packages/create-redwood-app/tsToJS.mjs
Labels: release:fix, fixture-ok

#8918 Remove the indexed type reference on AvailableRoutes
  packages/router/src/AuthenticatedRoute.tsx
  packages/router/src/index.ts
  packages/router/src/util.ts
Labels: release:fix

#8993 Make sure env var name starts with REDWOOD_ENV_
  packages/vite/src/index.ts
Labels: release:fix
