Repository redwoodjs/graphql, pull requests merged in 2023-01, with the labels that each got.

#6727 Update to GraphQL Yoga v3
  docs/docs/graphql.md
  docs/docs/how-to/using-a-third-party-api.md
  packages/api/package.json
  packages/api/src/__tests__/normalizeRequest.test.ts
  packages/api/src/cors.ts
  packages/api/src/errors.ts
  packages/api/src/transforms.ts
  packages/api/src/validations/errors.ts
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.test.ts
  packages/auth-providers/dbAuth/web/src/__tests__/webAuthn.test.ts
  packages/codemods/package.json
  packages/codemods/src/codemods/v0.37.x/addDirectives/addDirectives.ts
  packages/codemods/src/codemods/v0.38.x/updateSeedScript/updateSeedScript.ts
  packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/updateDevFatalErrorPage.ts
  packages/codemods/src/codemods/v2.x.x/configureFastify/configureFastify.yargs.ts
  packages/codemods/src/lib/fetchFileFromTemplate.ts
  packages/graphql-server/package.json
  packages/graphql-server/src/__tests__/cors.test.ts
  packages/graphql-server/src/cors.ts
  packages/graphql-server/src/errors.ts
  packages/graphql-server/src/functions/__tests__/graphql.test.ts
  packages/graphql-server/src/functions/__tests__/healthCheck.test.ts
  packages/graphql-server/src/functions/__tests__/normalizeRequest.test.ts
  packages/graphql-server/src/functions/__tests__/readinessCheck.test.ts
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/functions/types.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodAuthContext.test.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodDirective.test.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodError.test.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodGlobalContextSetter.test.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodLogger.test.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodPopulateContext.test.ts
  packages/graphql-server/src/plugins/index.ts
  packages/graphql-server/src/plugins/useRedwoodAuthContext.ts
  packages/graphql-server/src/plugins/useRedwoodDirective.ts
  packages/graphql-server/src/plugins/useRedwoodError.ts
  packages/graphql-server/src/plugins/useRedwoodGlobalContextSetter.ts
  packages/graphql-server/src/plugins/useRedwoodLogger.ts
  packages/graphql-server/src/plugins/useRedwoodPopulateContext.ts
  packages/prerender/package.json
  packages/prerender/src/internal.ts
  packages/telemetry/package.json
  packages/telemetry/src/sendTelemetry.ts
  tasks/e2e/cypress/e2e/01-tutorial/sharedTests.js
  yarn.lock
Labels: release:feature-breaking, next-release/update-docs, next-release/major

#7178 fix: Moves `fastify.addContentTypeParser(...)` above `configureFastify(...)`
  packages/api-server/src/plugins/withFunctions.ts
Labels: release:fix

#7292 Fix dbauth setup command in rebuild fixture
  __fixtures__/test-project/api/db/migrations/20230109093342_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20230109093444_create_contact/migration.sql
  __fixtures__/test-project/api/package.json
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/package.json
  tasks/test-project/tasks.js
Labels: release:chore

#7294 Separate setup vite handler, install canary version of `@redwoodjs/vite`
  packages/cli/src/commands/setup/vite/vite.js
  packages/cli/src/commands/setup/vite/viteHandler.js
Labels: release:fix, fixture-ok

#7311 fix(vite): Fix typo in setup process
  packages/cli/src/commands/setup/vite/viteHandler.js
Labels: release:fix, fixture-ok

#7323 fix(CI): cancel previous `in_progress` or `queued` canaries
  .github/workflows/publish-canary.yml
Labels: release:chore

#7322 chore(vite): Small tweaks to Vite package
  packages/vite/package.json
  packages/vite/src/index.ts
  yarn.lock
Labels: release:chore

#7325 chore: fix lint warnings forms/internal
  packages/forms/src/index.tsx
  packages/internal/src/routes.ts
Labels: release:chore

#7321 fix(prerender): Prerender pages sequentially
  packages/cli/src/commands/prerenderHandler.js
  packages/prerender/src/runPrerender.tsx
Labels: release:fix

#7332 Format playwright config file
  tasks/smoke-test/playwright.config.ts
Labels: release:chore

#7231 fix(docs): more explicit mentions of dbAuth
  docs/docs/security.md
Labels: release:docs

#7334 Test prerendering meta tags
  __fixtures__/test-project/api/db/migrations/20230112195437_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20230112195546_create_contact/migration.sql
  __fixtures__/test-project/api/package.json
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/pages/BlogPostPage/BlogPostPage.tsx
  tasks/smoke-test/tests/common.ts
  tasks/smoke-test/tests/prerender.spec.ts
  tasks/test-project/codemods/blogPostPage.js
Labels: release:chore

#7320 Fix premajor canary publishing when there's a major RC
  .github/actions/get_publish_flags/action.yml
  .github/actions/get_publish_flags/get_publish_flags.mjs
  .github/actions/message_slack_publishing/action.yml
  .github/workflows/publish-canary.yml
  .yarn/patches/@lerna-publish-npm-6.4.1-27e0fee593.patch
  package.json
  packages/cli/src/commands/upgrade.js
  yarn.lock
Labels: release:chore

#7349 Allow passing an array of auth decoders to createGraphQLHandler
  packages/api/src/auth/__tests__/getAuthenticationContext.test.ts
  packages/api/src/auth/index.ts
  packages/graphql-server/src/functions/useRequireAuth.ts
  packages/graphql-server/src/plugins/useRedwoodAuthContext.ts
Labels: release:feature

#6956 fix(setup-auth): Update setup process to make it behave consistently
  __fixtures__/test-project/api/db/migrations/20230114191659_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20230114191819_create_contact/migration.sql
  __fixtures__/test-project/api/package.json
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  __fixtures__/test-project/web/package.json
  packages/cli-helpers/src/auth/__tests__/addAuthConfig.test.ts
  packages/cli-helpers/src/auth/__tests__/setupHelpers.test.ts
  packages/cli-helpers/src/auth/authTasks.ts
  packages/cli-helpers/src/auth/setupHelpers.ts
Labels: release:fix

#7352 Fix detection of legacy auth
  packages/cli-helpers/src/auth/__tests__/__snapshots__/authTasks.test.ts.snap
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/authTasks.ts
Labels: release:fix, fixture-ok

#7353 Remove legacy auth import
  packages/cli-helpers/src/auth/__tests__/__snapshots__/authTasks.test.ts.snap
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/AppWithLegacyAuth.tsx
  packages/cli-helpers/src/auth/authTasks.ts
Labels: release:feature, fixture-ok

#7354 Remove old AuthProvider when FORCE or REPLACE
  packages/cli-helpers/src/auth/__tests__/__snapshots__/authTasks.test.ts.snap
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/authTasks.ts
Labels: release:feature, fixture-ok

#7356 Setup auth: Disable prompt
  packages/cli-helpers/src/auth/authTasks.ts
Labels: release:feature, fixture-ok

#7357 Setup auth: Handle skipping api lib auth.ts
  packages/cli-helpers/src/auth/authTasks.ts
  packages/cli-helpers/src/lib/index.ts
Labels: release:fix, fixture-ok

#7351 Fix a typo in the docs
  docs/docs/how-to/background-worker.md
Labels: release:docs

#7360 CurrentUser: Let declaration merging add `roles`
  packages/auth/src/AuthContext.ts
  packages/internal/src/generate/templates/all-currentUser.d.ts.template
Labels: release:fix

#7344 chore(CI): remove unused workflows
  .github/workflows/create-pr-artifact.yaml
  .github/workflows/netlify-build.yaml
  .github/workflows/publish-pr-packages.yaml
Labels: release:chore

#7367 feat(CI): cancel in-progress runs
  .github/workflows/check-test-project-fixture.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-release-candidate.yml
  .github/workflows/require-release-label.yml
  .github/workflows/update-all-contributors.yml
Labels: release:chore

#7291 feature: Implement GraphQLArmor
  docs/docs/directives.md
  docs/docs/graphql.md
  docs/docs/security.md
  packages/codemods/src/codemods/v4.x.x/useArmor/README.md
  packages/codemods/src/codemods/v4.x.x/useArmor/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v4.x.x/useArmor/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v4.x.x/useArmor/__testfixtures__/graphql.input.ts
  packages/codemods/src/codemods/v4.x.x/useArmor/__testfixtures__/graphql.output.ts
  packages/codemods/src/codemods/v4.x.x/useArmor/__tests__/useArmor.test.ts
  packages/codemods/src/codemods/v4.x.x/useArmor/useArmor.ts
  packages/codemods/src/codemods/v4.x.x/useArmor/useArmor.yargs.ts
  packages/graphql-server/package.json
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/functions/types.ts
  packages/graphql-server/src/plugins/__tests__/useArmor.test.ts
  packages/graphql-server/src/plugins/index.ts
  packages/graphql-server/src/plugins/useArmor.ts
  yarn.lock
Labels: release:feature-breaking

#7375 Make unit tests works with Auth0
  packages/testing/config/jest/web/RedwoodWebJestEnv.js
Labels: release:fix

#7361 Auth Netlify: Simplify hasRole implementation
  packages/auth-providers/netlify/setup/src/templates/api/lib/auth.ts.template
Labels: release:chore, fixture-ok

#7376 chore(CI): use workflow token by default in `set-up-job` action
  .github/actions/set-up-job/action.yml
  .github/actions/setup_job/action.yml
  .github/workflows/ci.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-release-candidate.yml
Labels: release:chore

#7377 chore(CI): remove cherry pick workflow and jobs
  .github/workflows/cherry-pick-into-next-branch.yml
  .github/workflows/ci.yml
Labels: release:chore

#7383 router tests: Fix AuthContext type error
  packages/router/src/__tests__/router.test.tsx
Labels: release:chore

#7339 fix(vite): Use process.env for env vars, Swap CommonJS plugin
  packages/vite/package.json
  packages/vite/src/index.ts
  yarn.lock
Labels: release:fix

#7280 chore: Update fs mocking
  packages/cli/__mocks__/fs.js
  packages/cli/src/__tests__/fs.test.js
  packages/cli/src/commands/destroy/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/destroy/scaffold/__tests__/scaffoldNoNest.test.js
  packages/cli/src/lib/__tests__/rollback.test.js
  packages/cli/src/lib/rollback.js
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:chore

#7386 Azure: Only redirect in getToken on InteractionRequiredAuthError
  packages/auth-providers/azureActiveDirectory/web/src/azureActiveDirectory.ts
Labels: release:fix

#7388 docs: use correct argument for azure auth setup
  docs/docs/auth/azure.md
Labels: release:docs

#7390 Adds note about how to view pm2 logs
  docs/docs/deploy/baremetal.md
  docs/versioned_docs/version-1.x/deploy/baremetal.md
  docs/versioned_docs/version-2.0/deploy/baremetal.md
  docs/versioned_docs/version-2.1/deploy/baremetal.md
  docs/versioned_docs/version-2.2/deploy/baremetal.md
  docs/versioned_docs/version-3.0/deploy/baremetal.md
  docs/versioned_docs/version-3.1/deploy/baremetal.md
  docs/versioned_docs/version-3.2/deploy/baremetal.md
Labels: topic/docs, topic/deployment, release:docs

#7345 Docs: Fix caching code examples
  docs/docs/services.md
Labels: release:docs

#7400 chore: remove typescript-transform-paths
  package.json
  yarn.lock
Labels: release:chore

#7401 Minor corrections to v4 GQL Armor and Auth docs
  docs/docs/auth/custom.md
  docs/docs/graphql.md
Labels: release:docs

#7023 chore: Removes instructions to use Prisma's interactiveTransactions for service uniqueness validation
  docs/docs/services.md
  packages/api/src/validations/validations.ts
Labels: next-release/update-docs, release:chore

#7001 docs: How to configure Fastify for uploads
  docs/docs/app-configuration-redwood-toml.md
Labels: next-release/update-docs, release:docs

#7177 chore(router): remove unused `lodash.isequal`, list `react`, `react-dom` in peerDependencies
  packages/router/package.json
  yarn.lock
Labels: release:chore

#6890 Update windows-development-setup.md
  docs/docs/how-to/windows-development-setup.md
Labels: release:docs

#7389 fix(telemetry): Enable telemetry on windows
  packages/telemetry/src/sendTelemetry.ts
  packages/telemetry/src/telemetry.ts
Labels: release:fix

#6918 chore: Smoke test improve output
  tasks/smoke-test/playwright-fixtures/devServer.fixture.ts
  tasks/smoke-test/playwright-fixtures/rwServe.fixture.ts
  tasks/smoke-test/playwright-fixtures/storybook.fixture.ts
Labels: release:chore

#6724 chore: E2E local process and files cleanup
  tasks/run-e2e
Labels: release:chore

#6965 ci(replay): try re-enabling replay
  .github/workflows/ci.yml
Labels: release:chore

#6907 Layer0 Deploy: Rebrand Layer0 to Edgio
  docs/docs/deploy/edgio.md
  docs/docs/deploy/introduction.md
  docs/docs/deploy/layer0.md
  docs/sidebars.js
  packages/cli/src/commands/deploy/edgio.js
  packages/cli/src/commands/setup/deploy/providers/edgio.js
Labels: release:fix, fixture-ok

#7422 fix: setup web/src/auth.js file in JS projects
  __fixtures__/test-project/api/package.json
  __fixtures__/test-project/web/package.json
  packages/cli-helpers/src/auth/authTasks.ts
Labels: release:fix

#7423 Switch to React's isValidElement
  packages/router/src/router.tsx
  packages/router/src/util.ts
Labels: release:chore

#6906 chore: Increase consistency of test-project rebuildFixture
  __fixtures__/test-project/api/db/migrations/20220101130000_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220102130000_create_contact/migration.sql
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
  tasks/test-project/.eslintrc.js
  tasks/test-project/codemods/scenarioValueSuffix.js
  tasks/test-project/tasks.js
Labels: release:chore

#6911 auth setup: auth.js for JS projects
  packages/cli-helpers/__mocks__/fs.js
  packages/cli-helpers/jest.config.js
  packages/cli-helpers/src/auth/__tests__/__snapshots__/authTasks.test.ts.snap
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/AppWithCustomRedwoodApolloProvider.js
  packages/cli-helpers/src/auth/__tests__/fixtures/AppWithExplicitReturn.js
  packages/cli-helpers/src/auth/__tests__/fixtures/AppWithLegacyAuth.tsx
  packages/cli-helpers/src/auth/__tests__/fixtures/AppWithoutRedwoodApolloProvider.js
  packages/cli-helpers/src/auth/__tests__/fixtures/RoutesWithCustomRouterProps.tsx
  packages/cli-helpers/src/auth/__tests__/fixtures/RoutesWithUseAuth.tsx
  packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/directives/requireAuth/requireAuth.test.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/directives/requireAuth/requireAuth.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/directives/skipAuth/skipAuth.test.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/directives/skipAuth/skipAuth.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/functions/graphql.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/functions/graphqlNonStandardAuthDecoder.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/graphql/.keep
  packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/lib/db.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/lib/logger.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/services/.keep
  packages/cli-helpers/src/auth/__tests__/fixtures/app/redwood.toml
  packages/cli-helpers/src/auth/__tests__/fixtures/app/web/src/App.tsx
  packages/cli-helpers/src/auth/__tests__/fixtures/app/web/src/Routes.tsx
  packages/cli-helpers/src/auth/__tests__/fixtures/app/web/src/components/.keep
  packages/cli-helpers/src/auth/__tests__/fixtures/app/web/src/index.css
  packages/cli-helpers/src/auth/__tests__/fixtures/app/web/src/index.html
  packages/cli-helpers/src/auth/__tests__/fixtures/app/web/src/layouts/.keep
  packages/cli-helpers/src/auth/__tests__/fixtures/app/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  packages/cli-helpers/src/auth/__tests__/fixtures/app/web/src/pages/NotFoundPage/NotFoundPage.tsx
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/setup.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/setupData.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/web/auth.webAuthn.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/webAuthn.setupData.ts
  packages/cli-helpers/src/auth/__tests__/fixtures/supertokensSetup/setup.ts
  packages/cli-helpers/src/auth/__tests__/mockFsFiles.ts
  packages/cli-helpers/src/auth/authTasks.ts
Labels: release:fix, fixture-ok

#7425 authTasks: Improve tests to also cover tsx template
  packages/cli-helpers/src/auth/__tests__/__snapshots__/authTasks.test.ts.snap
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/__tests__/mockFsFiles.ts
Labels: release:chore, fixture-ok

#7427 chore(test-project): Fix for timezones in consistent folder names
  __fixtures__/test-project/api/db/migrations/20220101120000_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220102120000_create_contact/migration.sql
  __fixtures__/test-project/api/package.json
  __fixtures__/test-project/web/package.json
  tasks/test-project/tasks.js
Labels: release:chore

#6783 Update sending-emails.md
  docs/docs/how-to/sending-emails.md
Labels: release:docs

#7429 auth setup: Refactor "redirect" commands
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:chore, fixture-ok

#4992 feat(react): Upgrade to React 18
  __fixtures__/test-project/api/db/migrations/20230118153725_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20230118153843_create_contact/migration.sql
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/pages/ProfilePage/ProfilePage.tsx
  babel.config.js
  docs/docs/custom-web-index.md
  package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/auth0/web/src/__tests__/auth0.test.tsx
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/azureActiveDirectory/web/src/__tests__/azureActiveDirectory.test.tsx
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/clerk/web/src/__tests__/clerk.test.tsx
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.test.ts
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/firebase/web/src/__tests__/firebase.test.tsx
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/netlify/web/src/__tests__/netlify.test.tsx
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supabase/web/src/__tests__/supabase.test.tsx
  packages/auth-providers/supertokens/web/package.json
  packages/auth-providers/supertokens/web/src/__tests__/supertokens.test.tsx
  packages/auth/package.json
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/create-redwood-app/template/web/package.json
  packages/forms/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/active-route-loader.tsx
  packages/router/src/location.tsx
  packages/testing/package.json
  packages/testing/src/web/customRender.tsx
  packages/web/package.json
  packages/web/src/entry/index.js
  tasks/test-project/codemods/profilePage.js
  yarn.lock
Labels: topic/auth, topic/web, release:feature-breaking, topic/prerender

#7382 fix(CRWA): remove `"packages/*"` from workspaces
  __fixtures__/test-project/package.json
  packages/create-redwood-app/template/package.json
Labels: release:fix

#6915 fix(ts): Fix defineScenario type for scenario definition function form
  packages/testing/src/api/scenario.ts
Labels: bug/confirmed, release:fix

#7387 Update Azure docs for RW v4 auth
  docs/docs/auth/azure.md
Labels: release:docs

#6897 [Fix]: Ensure client is defined using Clerk auth
  packages/auth-providers/clerk/web/src/clerk.tsx
  packages/auth/src/AuthProvider/AuthProviderState.ts
  packages/auth/src/AuthProvider/useReauthenticate.ts
Labels: release:fix

#7385 feat(auth): Update dependencies and support the new Clerk keys
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/api/src/__tests__/clerk.test.ts
  packages/auth-providers/clerk/api/src/decoder.ts
  packages/auth-providers/clerk/setup/src/setupHandler.ts
  packages/auth-providers/clerk/setup/src/templates/web/auth.tsx.template
  packages/auth-providers/clerk/web/package.json
  yarn.lock
Labels: release:feature, fixture-ok

#7452 [Auth] Update setup notes and templates, and constrain versions
  docs/docs/auth/custom.md
  docs/docs/auth/firebase.md
  docs/docs/auth/supabase.md
  packages/auth-providers/auth0/setup/src/setup.ts
  packages/auth-providers/auth0/setup/src/setupHandler.ts
  packages/auth-providers/auth0/setup/src/templates/web/auth.ts.template
  packages/auth-providers/azureActiveDirectory/setup/src/setup.ts
  packages/auth-providers/azureActiveDirectory/setup/src/setupHandler.ts
  packages/auth-providers/clerk/setup/src/setup.ts
  packages/auth-providers/clerk/setup/src/setupHandler.ts
  packages/auth-providers/custom/setup/src/setupHandler.ts
  packages/auth-providers/dbAuth/setup/src/setup.ts
  packages/auth-providers/firebase/setup/src/setup.ts
  packages/auth-providers/firebase/setup/src/setupHandler.ts
  packages/auth-providers/netlify/setup/src/setup.ts
  packages/auth-providers/netlify/setup/src/setupHandler.ts
  packages/auth-providers/supabase/setup/src/setup.ts
  packages/auth-providers/supabase/setup/src/setupHandler.ts
  packages/auth-providers/supertokens/setup/src/setup.ts
  packages/auth-providers/supertokens/setup/src/setupHandler.ts
  packages/cli-helpers/src/auth/setupHelpers.ts
  packages/cli/src/commands/setup/auth/auth.js
  yarn.lock
Labels: release:fix, fixture-ok

#7384 feat(vite): Switch build and dev to call Vite programatically
  .eslintrc.js
  __fixtures__/example-todo-main/web/vite.config.ts
  packages/cli/src/commands/__tests__/build.test.js
  packages/cli/src/commands/__tests__/dev.test.js
  packages/cli/src/commands/buildHandler.js
  packages/cli/src/commands/devHandler.js
  packages/cli/src/commands/setup/vite/templates/vite.config.ts.template
  packages/internal/src/__tests__/paths.test.ts
  packages/internal/src/build/web.ts
  packages/internal/src/paths.ts
  packages/vite/bins/rw-vite-dev.mjs
  packages/vite/package.json
  packages/vite/src/index.ts
  yarn.lock
Labels: release:chore, fixture-ok

#7460 feat(dev): Enable restarting vite and typgen by typing "rs"
  packages/internal/src/generate/watch.ts
  packages/vite/bins/rw-vite-dev.mjs
Labels: release:feature

#7467 Custom auth docs: Mention repos for deprecated auth providers
  docs/docs/auth/custom.md
Labels: release:docs

#7466 fix(docs): update tutorial to v4
  docs/docs/tutorial/chapter4/authentication.md
  docs/docs/tutorial/chapter6/comment-form.md
  docs/docs/tutorial/chapter7/rbac.md
Labels: release:docs

#7476 fix: pin webAuthn, SuperTokens, comment out latter
  packages/auth-providers/dbAuth/setup/src/webAuthn.setupData.ts
  packages/auth-providers/supertokens/setup/src/setupHandler.ts
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:fix, fixture-ok

#7484 Fix setup help text typo
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:fix, fixture-ok

#7480 Fix 'excludes' validator to 'exclusion'
  docs/docs/services.md
Labels: release:docs

#7483 SuperTokens setup: Add to Routes.tsx
  packages/auth-providers/supertokens/setup/__mocks__/fs.js
  packages/auth-providers/supertokens/setup/src/__tests__/__snapshots__/setupHandler.test.ts.snap
  packages/auth-providers/supertokens/setup/src/__tests__/setup.test.ts
  packages/auth-providers/supertokens/setup/src/__tests__/setupHandler.test.ts
  packages/auth-providers/supertokens/setup/src/setupHandler.ts
Labels: release:fix

#7485 Make it easier to test auth setup with rwfw project:copy
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:feature, fixture-ok

#7492 Set up auth: Fix isInstalled logic
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:fix, fixture-ok

#7494 fix(CLI): try-catch `require.resolve` in setup auth
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:fix, fixture-ok

#7496 fix(CLI): use `require.resolve.paths` to avoid `require.resolve` cache
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:fix, fixture-ok

#7063 fix: correct Cell prop types when used with `beforeQuery`
  packages/web/jest.config.js
  packages/web/package.json
  packages/web/src/__typetests__/cellProps.test.tsx
  packages/web/src/__typetests__/tsconfig.json
  packages/web/src/components/createCell.tsx
  yarn.lock
Labels: release:fix

#7503 fix(CRWA): import `hashPassword` from `@redwoodjs/auth-dbauth-api`
  __fixtures__/test-project/scripts/seed.ts
  packages/create-redwood-app/template/scripts/seed.ts
Labels: release:fix

#7504 fix(CLI): add env var to Supabase notes, Azure alias
  packages/auth-providers/supabase/setup/src/setupHandler.ts
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:fix, fixture-ok

#7510 Revert part of "Fix premajor canary publishing when there's a major RC (#7320)"
  .github/actions/get_publish_flags/action.yml
  .github/actions/get_publish_flags/get_publish_flags.mjs
  .github/workflows/publish-canary.yml
  .yarn/patches/@lerna-publish-npm-6.4.1-27e0fee593.patch
  package.json
  yarn.lock
Labels: release:chore

#7499 chore: :wrench: add skipLibCheck to api tsconfig
  __fixtures__/test-project/api/tsconfig.json
  packages/create-redwood-app/template/api/tsconfig.json
Labels: release:fix

#7498 chore: :wrench: add skipLibCheck to web tsconfig
  __fixtures__/test-project/web/tsconfig.json
  packages/create-redwood-app/template/web/tsconfig.json
Labels: release:feature, fixture-ok

#7490 SuperTokens: Update to work with v0.30
  packages/auth-providers/supertokens/setup/src/templates/api/lib/supertokens.ts.template
  packages/auth-providers/supertokens/setup/src/templates/web/auth.tsx.template
  packages/auth-providers/supertokens/web/package.json
  packages/auth-providers/supertokens/web/src/__tests__/supertokens.test.tsx
  packages/auth-providers/supertokens/web/src/supertokens.ts
  yarn.lock
Labels: release:fix

#7519 Enable yarn rw setup auth supertokens
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:feature, fixture-ok

#7162 feat: add toml option for upgrade checks
  __fixtures__/test-project/redwood.toml
  docs/docs/app-configuration-redwood-toml.md
  docs/docs/cli-commands.md
  packages/cli/src/index.js
  packages/cli/src/lib/__tests__/updateCheck.test.js
  packages/cli/src/lib/__tests__/upgradeCheck.test.js
  packages/cli/src/lib/runUpgradeCheck.js
  packages/cli/src/lib/updateCheck.js
  packages/cli/src/lib/updateCheckExecute.js
  packages/cli/src/lib/upgradeCheck.js
  packages/create-redwood-app/template/redwood.toml
  packages/internal/src/__tests__/config.test.ts
  packages/internal/src/config.ts
Labels: release:feature

#7522 SuperTokens docs
  docs/docs/auth/supertokens.md
  docs/sidebars.js
Labels: release:docs

#7526 Fix SuperTokens setup web template
  packages/auth-providers/supertokens/setup/src/templates/web/auth.tsx.template
Labels: release:fix, fixture-ok
