Repository redwoodjs/graphql, pull requests merged in 2023-10, with the labels that each got.

#9246 chore(lint): crwa linting
  packages/create-redwood-app/templates/ts/web/src/App.tsx
Labels: release:chore, fixture-ok, crwa-ok

#9253 test-project: yarn resolution for @types/react
  __fixtures__/test-project/package.json
Labels: release:chore

#9247 generate dbAuth: one more thing formatting
  packages/cli/src/commands/generate/dbAuth/dbAuth.js
Labels: release:fix, fixture-ok

#9245 fix: `await` Promise when seeding
  __fixtures__/empty-project/scripts/seed.ts
  __fixtures__/test-project/scripts/seed.ts
  packages/create-redwood-app/templates/js/scripts/seed.js
  packages/create-redwood-app/templates/ts/scripts/seed.ts
Labels: release:fix

#9270 fix(api-sever): stop infinite loop on large projects
  packages/api-server/src/watch.ts
Labels: release:fix

#9024 feat: add experimental docker setup command
  docs/docs/docker.md
  docs/sidebars.js
  packages/api-server/package.json
  packages/api-server/src/cliHandlers.ts
  packages/api-server/src/plugins/withFunctions.ts
  packages/api-server/src/types.ts
  packages/cli/src/commands/experimental/__tests__/setupDocker.test.js
  packages/cli/src/commands/experimental/setupDocker.js
  packages/cli/src/commands/experimental/setupDockerHandler.js
  packages/cli/src/commands/experimental/templates/docker/Dockerfile
  packages/cli/src/commands/experimental/templates/docker/docker-compose.dev.yml
  packages/cli/src/commands/experimental/templates/docker/docker-compose.prod.yml
  packages/cli/src/commands/experimental/templates/docker/dockerignore
  packages/web-server/package.json
  packages/web-server/src/server.ts
  yarn.lock
Labels: release:feature

#9273 auth setup: Array of extra tasks
  packages/auth-providers/dbAuth/setup/src/setupHandler.ts
  packages/auth-providers/supertokens/setup/src/__tests__/setupHandler.test.ts
  packages/auth-providers/supertokens/setup/src/setupHandler.ts
  packages/cli-helpers/src/auth/setupHelpers.ts
Labels: release:feature, fixture-ok

#9248 dbAuth: Unique session cookie name per port
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
  packages/auth-providers/dbAuth/api/src/__tests__/shared.test.ts
  packages/auth-providers/dbAuth/api/src/decoder.ts
  packages/auth-providers/dbAuth/api/src/shared.ts
  packages/auth-providers/dbAuth/api/tsconfig.json
  packages/auth-providers/dbAuth/setup/src/setupHandler.ts
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.ts.template
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.webAuthn.ts.template
  packages/auth-providers/dbAuth/setup/src/templates/api/lib/auth.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.webAuthn.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/lib/auth.ts.template
  yarn.lock
Labels: release:feature-breaking, fixture-ok

#9266 Fix broken link to most recent jest config example
  docs/docs/project-configuration-dev-test-build.mdx
Labels: release:docs

#9277 dbAuth: Fix cookie related exports
  packages/auth-providers/dbAuth/api/src/index.ts
  packages/auth-providers/dbAuth/setup/src/templates/api/lib/auth.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/lib/auth.ts.template
Labels: release:fix, fixture-ok

#9267 Fix TypeScript code highlighting (Chapter 6: Comments – Testing the service)
  docs/docs/tutorial/chapter6/comments-schema.md
Labels: release:docs

#9238 Clarify Auth0 Configuration
  docs/docs/auth/auth0.md
Labels: release:docs

#9278 dbAuth template: Add missing comma
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.ts.template
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.webAuthn.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.webAuthn.ts.template
Labels: release:fix, fixture-ok

#9240 small tweak to Flightcontrol deploy config template
  packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
Labels: release:fix, fixture-ok

#9207 docs: Clarifies the testimonial section of the What is Redwood documentation
  docs/docs/tutorial/chapter0/what-is-redwood.md
Labels: release:docs

#9281 fix(serverless): move project-config to auth-dbauth-api dependencies
  packages/auth-providers/dbAuth/api/package.json
Labels: release:fix

#9269 fix(types): Generate maps to allow improved "go to definition" behaviour
  packages/internal/package.json
  packages/internal/src/__tests__/ast.test.ts
  packages/internal/src/__tests__/jsx.test.ts
  packages/internal/src/__tests__/typeDefinitions.test.ts
  packages/internal/src/ast.ts
  packages/internal/src/generate/templates/mirror-cell.d.ts.template
  packages/internal/src/generate/templates/mirror-directoryNamedModule.d.ts.template
  packages/internal/src/generate/templates/web-routerRoutes.d.ts.template
  packages/internal/src/generate/templates/web-routesPages.d.ts.template
  packages/internal/src/generate/typeDefinitions.ts
  packages/internal/src/jsx.ts
  yarn.lock
Labels: release:fix

#9265 fix (docs): use default markdown numbered list
  docs/docs/testing.md
Labels: release:docs

#9288 Fix suggested code snippet
  packages/auth-providers/auth0/setup/src/setupHandler.ts
  packages/auth-providers/azureActiveDirectory/setup/src/setupHandler.ts
  packages/auth-providers/supabase/setup/src/setupHandler.ts
Labels: release:fix

#9286 Fix typo in RBAC @requireAuth example
  docs/docs/graphql.md
Labels: release:docs

#9285 Fix links to Prisma n:m relationship docs
  docs/docs/schema-relations.md
Labels: release:docs

#9274 chore(router): Add missing tests in analyze routes
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/util.ts
Labels: release:chore

#9283 docs: How to Use Prisma Client Extensions with DB Client and Logging
  docs/docs/logger.md
Labels: release:docs

#9301 Cell generator: Fix formatting in template
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/templates/cell.tsx.template
  packages/cli/src/commands/generate/cell/templates/cellList.tsx.template
  packages/internal/src/__tests__/ast.test.ts
  packages/internal/src/__tests__/fixtures/web/src/cell.tsx
Labels: release:fix, fixture-ok

#9037 Conditionally guarantee cell success data
  packages/web/src/__typetests__/cellSuccessData.test.tsx
  packages/web/src/components/cell/cellTypes.ts
Labels: release:fix

#9296 feat(cli-helpers): Root package install and RWJS env var
  packages/cli-helpers/src/lib/installHelpers.ts
  packages/cli-helpers/src/lib/project.ts
Labels: release:feature, fixture-ok

#9302 Router utils: Fix some spelling mistakes and other minor changes
  packages/router/src/util.ts
Labels: release:chore

#9295 feat(streaming-ssr): Various bug fixes and migrate to FetchAPI/Web streams
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/vite/package.json
  packages/vite/src/devFeServer.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/vite/src/streaming/transforms/bufferedTransform.ts
  packages/vite/src/streaming/transforms/encode-decode.ts
  packages/vite/src/streaming/transforms/serverInjectionTransform.ts
  packages/vite/src/streaming/triggerRouteHooks.ts
  packages/web/src/components/htmlTags.tsx
  packages/web/src/routeHooks.types.ts
  yarn.lock
Labels: release:feature

#9205 chore: Restore name of terminating Apollo link to httpLink
  packages/web/src/apollo/index.tsx
Labels: topic/graphql, release:fix

#9272 fix(fastify): Dont fallback to index html if requesting static assets
  packages/fastify/src/web.ts
Labels: release:fix

#9310 fix(ssr-build): Generate document in ssr build too!
  packages/vite/src/buildFeServer.ts
Labels: release:fix

#9303 `<PrivateSet>`
  packages/eslint-plugin/src/unsupported-route-components.ts
  packages/router/src/AuthenticatedRoute.tsx
  packages/router/src/Set.tsx
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/__tests__/nestedSets.test.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/router.tsx
  packages/router/src/util.ts
Labels: release:feature

#9314 Fix Set wrapper type so you can have an array of wrappers
  packages/router/src/Set.tsx
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/__tests__/links.test.tsx
  packages/router/src/__tests__/nestedSets.test.tsx
  packages/router/src/__tests__/route-announcer.test.tsx
  packages/router/src/__tests__/route-focus.test.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/__tests__/setContextReuse.test.tsx
  packages/router/tsconfig.json
Labels: release:fix

#9317 fix(stream-ssr): Cancel the timeout when the react stream has finished
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/vite/src/streaming/transforms/cancelTimeoutTransform.ts
Labels: release:fix

#9326 RSC e2e scripts: Fix console.log text. Change local test path
  .github/actions/set-up-rsc-project/setUpRscProject.mjs
  .github/actions/set-up-rsc-project/setUpRscProjectLocally.mjs
Labels: release:chore

#9328 Upgrade to vite v4.5.0
  packages/studio/package.json
  packages/vite/package.json
  yarn.lock
Labels: release:chore

#9330 RSC: createRscRequestHandler
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/runRscFeServer.ts
Labels: release:chore

#9329 fix(babel): Improved message for error relating to multiple files ending in `Page.{js,jsx,ts,tsx}` in page directories
  packages/babel-config/src/plugins/__tests__/__fixtures__/route-auto-loader/failure/redwood.toml
  packages/babel-config/src/plugins/__tests__/__fixtures__/route-auto-loader/failure/web/src/Routes.tsx
  packages/babel-config/src/plugins/__tests__/__fixtures__/route-auto-loader/failure/web/src/pages/HomePage/HomePage.tsx
  packages/babel-config/src/plugins/__tests__/__fixtures__/route-auto-loader/failure/web/src/pages/HomePage/useHomePage.tsx
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader.ts
Labels: release:fix

#9331 RSC: Implement RSC worker
  packages/cli/src/commands/serveBothHandler.js
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
  packages/vite/src/runRscFeServer.ts
  packages/vite/src/waku-lib/build-server.ts
  packages/vite/src/waku-lib/builder.ts
Labels: release:feature

#9312 Don't remount wrap components when navigating within Set
  packages/router/src/Set.tsx
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/__tests__/nestedSets.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/__tests__/setContextReuse.test.tsx
  packages/router/src/router.tsx
  packages/router/src/util.ts
Labels: release:fix

#9332 RSC: test-project-rsa: Fix TS type error in onSend
  __fixtures__/test-project-rsa/web/src/chat.ts
Labels: release:chore

#9334 Update all GitHub actions to run on Node 20
  .github/actions/check_create_redwood_app/action.yml
  .github/actions/check_test_project_fixture/action.yml
  .github/actions/only_doc_changes/action.yml
  .github/actions/require-milestone/action.yml
  .github/actions/rsc_related_changes/action.yml
  .github/actions/set-up-test-project/action.yaml
  .github/actions/update_all_contributors/action.yml
  tasks/check/action.yml
Labels: release:chore

#9280 fix(cli): Exit with non-zero exit code when `yarn rw g types` has errors
  packages/cli/src/commands/generate.js
  packages/internal/src/generate/generate.ts
Labels: release:feature-breaking, fixture-ok

#9290 fix(cli): Tailwind setup updates `scaffold.css` when needed
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
Labels: release:fix, fixture-ok

#9324 feature: Adds utility functions to add envars and update Redwood toml for plugin packages to cli helpers for use in simplifying CLI setup commands
  packages/cli-helpers/package.json
  packages/cli-helpers/src/lib/__tests__/__snapshots__/project.test.ts.snap
  packages/cli-helpers/src/lib/__tests__/project.test.ts
  packages/cli-helpers/src/lib/project.ts
  yarn.lock
Labels: release:feature, fixture-ok

#9336 chore: increase server test timeout, fix `yarn build:clean`
  package.json
  tasks/clean.mjs
  tasks/server-tests/jest.config.js
  tasks/server-tests/server.test.ts
Labels: release:chore

#9348 chore(api-server): remove server survey tests in CI
  .github/workflows/ci.yml
Labels: release:chore

#9298 fix(babel): Fix opentelemetry api wrapping and allow it to be disabled
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/directive-skipAuth/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/directive-skipAuth/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/function-auth/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/function-auth/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/function-graphql/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/function-graphql/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/lib-auth/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/lib-auth/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/lib-db/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/lib-db/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/service-basic/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/service-basic/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/service-custom/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/service-custom/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/service-instrumented/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/otel-wrapping/service-instrumented/output.js
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-otel-wrapping.test.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-otel-wrapping.ts
  packages/cli/src/commands/experimental/setupOpentelemetryHandler.js
  packages/internal/src/build/api.ts
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
Labels: release:fix

#9358 chore(k6): Fix function context test
  package.json
  tasks/benchmark/README.md
  tasks/benchmark/run-benchmarks.mts
  tasks/k6-test/README.md
  tasks/k6-test/run-k6-tests.mts
  tasks/k6-test/setups/context_magic_number/setup.mts
  tasks/k6-test/setups/context_magic_number/templates/benchmark.sdl.ts
  tasks/k6-test/setups/context_magic_number/templates/benchmarks.ts
  tasks/k6-test/setups/context_magic_number/templates/func.ts
  tasks/k6-test/setups/scalable_graphql_schema/setup.mts
  tasks/k6-test/setups/scalable_graphql_schema/templates/definition.sdl.ts
  tasks/k6-test/setups/scalable_graphql_schema/templates/implementation.ts
  tasks/k6-test/setups/scalable_graphql_schema/templates/relation.sdl.ts
  tasks/k6-test/tests/context_functions.js
  tasks/k6-test/tests/context_graphql.js
  tasks/k6-test/tests/scalable_graphql_schema.js
  tasks/k6-test/util/util.mts
Labels: release:chore

#9235 feature: Support defer and stream GraphQL Directives in RedwoodRealtime
  docs/docs/realtime.md
  docs/sidebars.js
  packages/cli/src/commands/experimental/setupRealtimeHandler.js
  packages/cli/src/commands/experimental/templates/defer/fastAndSlowFields/fastAndSlowFields.sdl.template
  packages/cli/src/commands/experimental/templates/defer/fastAndSlowFields/fastAndSlowFields.ts.template
  packages/cli/src/commands/experimental/templates/realtime.ts.template
  packages/cli/src/commands/experimental/templates/stream/alphabet/alphabet.sdl.template
  packages/cli/src/commands/experimental/templates/stream/alphabet/alphabet.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/countdown/countdown.ts.template
  packages/graphql-server/src/plugins/useRedwoodError.ts
  packages/realtime/package.json
  packages/realtime/src/graphql/index.ts
  packages/realtime/src/graphql/plugins/useRedwoodRealtime.ts
  packages/realtime/src/index.ts
  yarn.lock
Labels: release:feature

#9335 feat(cli): Setup command for mailer
  docs/docs/cli-commands.md
  packages/cli/src/commands/setup/mailer/mailer.js
  packages/cli/src/commands/setup/mailer/mailerHandler.js
  packages/cli/src/commands/setup/mailer/templates/mailer.ts.template
  packages/cli/src/commands/setup/mailer/templates/re-example.tsx.template
  packages/mailer/core/src/__tests__/mailer.test.ts
  packages/mailer/core/src/mailer.ts
Labels: release:feature, fixture-ok
