Repository redwoodjs/graphql, pull requests merged in 2023-11, with the labels that each got.

#9368 chore(k6): Fix function context test
  tasks/k6-test/run-k6-tests.mts
  tasks/k6-test/setups/context_magic_number/templates/benchmarks.ts
  tasks/k6-test/setups/context_magic_number/templates/func.ts
  tasks/k6-test/tests/context_functions.js
Labels: release:chore

#9369 fix(api-server): copy fallback fix from #9272
  packages/api-server/src/plugins/withWebServer.ts
Labels: release:fix

#9372 fix(server-file): prefix `MODULE_NOT_FOUND` with `ERR_`
  packages/internal/src/generate/graphqlSchema.ts
Labels: release:fix

#9375 fix(serverless): try-catch `getConfigPath` for `cookieName`
  packages/auth-providers/dbAuth/api/src/shared.ts
Labels: release:fix

#9349 chore(e2e): Setup e2e test for streaming SSR
  .github/actions/actionsLib.mjs
  .github/actions/set-up-test-project/action.yaml
  .github/actions/set-up-test-project/setUpTestProject.mjs
  .github/actions/ssr_related_changes/action.yml
  .github/actions/ssr_related_changes/package.json
  .github/actions/ssr_related_changes/ssr_related_changes.mjs
  .github/actions/ssr_related_changes/yarn.lock
  .github/workflows/ci.yml
  .yarnrc.yml
  packages/cli/src/commands/experimental/setupStreamingSsrHandler.js
  packages/vite/src/index.ts
  packages/vite/src/plugins/__tests__/swap-apollo-provider.test.mts
  packages/vite/src/plugins/vite-plugin-swap-apollo-provider.ts
  packages/vite/src/streaming/registerGlobals.ts
  tasks/smoke-tests/auth/tests/authChecks.spec.ts
  tasks/smoke-tests/auth/tests/rbacChecks.spec.ts
  tasks/smoke-tests/dev/tests/dev.spec.ts
  tasks/smoke-tests/prerender/tests/prerender.spec.ts
  tasks/smoke-tests/serve/tests/serve.spec.ts
  tasks/smoke-tests/shared/common.ts
  tasks/smoke-tests/shared/delayedPage.ts
  tasks/smoke-tests/shared/homePage.ts
  tasks/smoke-tests/smoke-tests.mjs
  tasks/smoke-tests/streaming-ssr-dev/playwright.config.ts
  tasks/smoke-tests/streaming-ssr-dev/tests/progressiveRendering.spec.ts
  tasks/smoke-tests/streaming-ssr-prod/playwright.config.ts
  tasks/smoke-tests/streaming-ssr-prod/tests/botRendering.spec.ts
  tasks/smoke-tests/streaming-ssr-prod/tests/progressiveRendering.spec.ts
  tasks/test-project/codemods/delayedPage.js
  tasks/test-project/convert-to-ssr-fixture
  tasks/test-project/tasks.js
  tasks/test-project/test-project
Labels: release:chore

#9350 Update crypto library, CryptoJS CVE & deprecation
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
  packages/auth-providers/dbAuth/api/src/__tests__/shared.test.ts
  packages/auth-providers/dbAuth/api/src/shared.ts
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/setup/src/setupData.ts
  packages/cli/package.json
  packages/cli/src/commands/generate/secret/__tests__/secret.test.js
  packages/cli/src/commands/generate/secret/secret.js
  packages/cli/src/commands/setup/graphiql/__tests__/graphiqlHandler.test.js
  packages/cli/src/commands/setup/graphiql/graphiqlHandler.js
  packages/cli/src/commands/setup/graphiql/supportedProviders.js
  packages/studio/api/lib/authProviderEncoders/dbAuthEncoder.ts
  packages/studio/package.json
  tasks/smoke-tests/auth/tests/authChecks.spec.ts
  tasks/smoke-tests/shared/common.ts
  yarn.lock
Labels: topic/auth, release:fix, fixture-ok, topic/security

#9365 telemetry: Insight into gitpod adoption
  packages/cli/src/telemetry/resource.js
  packages/create-redwood-app/src/telemetry.js
Labels: release:feature

#9390 chore: Relocated tsbuildinfo out of dist folder
  packages/api-server/tsconfig.json
  packages/api/tsconfig.json
  packages/auth-providers/auth0/api/tsconfig.json
  packages/auth-providers/auth0/setup/tsconfig.json
  packages/auth-providers/auth0/web/tsconfig.json
  packages/auth-providers/azureActiveDirectory/api/tsconfig.json
  packages/auth-providers/azureActiveDirectory/setup/tsconfig.json
  packages/auth-providers/azureActiveDirectory/web/tsconfig.json
  packages/auth-providers/clerk/api/tsconfig.json
  packages/auth-providers/clerk/setup/tsconfig.json
  packages/auth-providers/clerk/web/tsconfig.json
  packages/auth-providers/custom/setup/tsconfig.json
  packages/auth-providers/dbAuth/api/tsconfig.json
  packages/auth-providers/dbAuth/setup/tsconfig.json
  packages/auth-providers/dbAuth/web/tsconfig.json
  packages/auth-providers/firebase/api/tsconfig.json
  packages/auth-providers/firebase/setup/tsconfig.json
  packages/auth-providers/firebase/web/tsconfig.json
  packages/auth-providers/netlify/api/tsconfig.json
  packages/auth-providers/netlify/setup/tsconfig.json
  packages/auth-providers/netlify/web/tsconfig.json
  packages/auth-providers/supabase/api/tsconfig.json
  packages/auth-providers/supabase/setup/tsconfig.json
  packages/auth-providers/supabase/web/tsconfig.json
  packages/auth-providers/supertokens/api/tsconfig.json
  packages/auth-providers/supertokens/setup/tsconfig.json
  packages/auth-providers/supertokens/web/tsconfig.json
  packages/auth/tsconfig.json
  packages/babel-config/tsconfig.json
  packages/cli-helpers/tsconfig.json
  packages/cli-packages/dataMigrate/tsconfig.json
  packages/cli-packages/storybook/tsconfig.json
  packages/eslint-plugin/tsconfig.json
  packages/fastify/tsconfig.json
  packages/forms/tsconfig.json
  packages/graphql-server/tsconfig.json
  packages/internal/tsconfig.json
  packages/mailer/core/tsconfig.json
  packages/mailer/handlers/in-memory/tsconfig.json
  packages/mailer/handlers/nodemailer/tsconfig.json
  packages/mailer/handlers/resend/tsconfig.json
  packages/mailer/handlers/studio/tsconfig.json
  packages/mailer/renderers/mjml-react/tsconfig.json
  packages/mailer/renderers/react-email/tsconfig.json
  packages/prerender/tsconfig.json
  packages/project-config/tsconfig.json
  packages/realtime/tsconfig.json
  packages/router/tsconfig.json
  packages/structure/tsconfig.json
  packages/studio/tsconfig.json
  packages/telemetry/tsconfig.json
  packages/testing/tsconfig.json
  packages/tui/tsconfig.json
  packages/vite/tsconfig.json
  packages/web-server/tsconfig.json
  packages/web/tsconfig.json
  tasks/release/releaseCommand.mjs
Labels: release:chore, fixture-ok

#9389 fix(stream-ssr): Move wait for all ready to fix bot rendering
  packages/vite/src/streaming/streamHelpers.ts
  packages/vite/src/streaming/transforms/serverInjectionTransform.ts
  tasks/smoke-tests/streaming-ssr-prod/tests/botRendering.spec.ts
Labels: release:fix

#9382 feat(ssr): Collect CSS links during dev
  packages/vite/src/devFeServer.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/collectCss.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/web/src/components/htmlTags.tsx
Labels: release:feature

#9383 chore(ssr): Move LocationProvider inside framework for SSR
  packages/cli/src/commands/experimental/templates/streamingSsr/entry.server.tsx.template
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:chore

#9363 docs(mailer): Initial mailer docs
  docs/docs/mailer.md
  docs/sidebars.js
  docs/static/img/mailer/flow.svg
  docs/static/img/mailer/local_inbox.png
  docs/static/img/mailer/template_preview.png
Labels: release:docs

#9392 Issue Metrics GitHub action
  .github/actions/issue_metrics/monthly_issue_metrics.yml
  .github/actions/issue_metrics/monthly_issue_metrics_json.yml
  .github/actions/issue_metrics/weekly_issue_metrics.yml
Labels: release:chore

#9393 Issue Metrics GitHub action in /workflows
  .github/workflows/monthly_issue_metrics.yml
  .github/workflows/monthly_issue_metrics_json.yml
  .github/workflows/weekly_issue_metrics.yml
Labels: release:chore

#9395 Move Issue Metrics GH actions into workflow folder
  .github/workflows/monthly_issue_metrics.yml
  .github/workflows/monthly_issue_metrics_json.yml
  .github/workflows/weekly_issue_metrics.yml
Labels: release:chore

#9397 Issue Metrics: Fix weekly report
  .github/workflows/weekly_issue_metrics.yml
Labels: release:chore

#9400 Issue Metrics: Weekly JSON report
  .github/workflows/weekly_issue_metrics_json.yml
Labels: release:chore

#9402 fix(docker): pass `task` to `writeFile`
  packages/cli/src/commands/experimental/setupDockerHandler.js
Labels: release:fix

#9409 README: Add Leadership Team
  README.md
Labels: release:chore

#9411 RSC: smoke tests: install and build after project:copy
  .github/actions/set-up-rsc-project/setUpRscProject.mjs
Labels: release:chore

#9412 RSC: Move loaders to worker thread
  packages/cli/src/commands/serveBothHandler.js
  packages/vite/src/rsc/rscWorkerCommunication.ts
Labels: release:fix

#9413 RSC GH action: Move build to after copy
  .github/actions/actionsLib.mjs
Labels: release:chore

#9410 RSC: Check for rw-rsc header
  .github/actions/actionsLib.mjs
  packages/vite/src/client.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/runRscFeServer.ts
Labels: release:fix

#9367 RSC: Support client-only package and include @tobbe.dev/rsc-test in smoke test
  __fixtures__/test-project-rsc-external-packages/.yarn/patches/vite-npm-4.4.9-e845c1bbf8.patch
  __fixtures__/test-project-rsc-external-packages/package.json
  __fixtures__/test-project-rsc-external-packages/web/package.json
  __fixtures__/test-project-rsc-external-packages/web/src/App.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/Counter.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/Form.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/actions.ts
  __fixtures__/test-project-rsc-external-packages/web/src/chat.ts
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/waku-lib/build-server.ts
  tasks/smoke-tests/rsc-external-packages/tests/rsc-external-packages.spec.ts
Labels: release:feature

#9401 fix(v6.4.0 RC): conditionally remove `SSELink` from the bundle
  packages/core/config/webpack.common.js
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
  packages/vite/src/index.ts
  packages/vite/src/plugins/vite-plugin-remove-from-bundle.ts
  packages/web/src/apollo/index.tsx
  tasks/smoke-tests/shared/common.ts
Labels: release:fix

#9415 fix: handle `tsconfig.tsbuildinfo` in clean, sync
  tasks/clean.mjs
  tasks/framework-tools/frameworkSyncToProject.mjs
Labels: release:chore

#9417 chore(ci): Fix conditional workflow jobs
  .github/actions/detect-changes/action.yml
  .github/actions/detect-changes/cases/onlydocs.mjs
  .github/actions/detect-changes/cases/rsc.mjs
  .github/actions/detect-changes/cases/ssr.mjs
  .github/actions/detect-changes/detectChanges.mjs
  .github/actions/detect-changes/package.json
  .github/actions/detect-changes/yarn.lock
  .github/actions/only_doc_changes/action.yml
  .github/actions/only_doc_changes/only_doc_changes.mjs
  .github/actions/only_doc_changes/package.json
  .github/actions/rsc_related_changes/action.yml
  .github/actions/rsc_related_changes/package.json
  .github/actions/rsc_related_changes/yarn.lock
  .github/actions/ssr_related_changes/action.yml
  .github/actions/ssr_related_changes/ssr_related_changes.mjs
  .github/actions/ssr_related_changes/yarn.lock
  .github/workflows/ci.yml
Labels: release:chore

#9377 Added missing type to routing-params.md
  docs/docs/tutorial/chapter2/routing-params.md
Labels: release:docs

#9357 Update dbauth-passwordless.md
  docs/docs/how-to/dbauth-passwordless.md
Labels: release:docs

#9370 docs: Update Deployment Docs to Provide Guidance on Extending the Timeout Duration in Vercel
  docs/docs/deploy/vercel.md
Labels: release:docs

#9394 chore: migrate type tests to TSTyche
  .github/workflows/ci.yml
  package.json
  packages/router/jest.config.js
  packages/router/package.json
  packages/router/src/__typetests__/routeParamsTypes.test.ts
  packages/router/src/__typetests__/tsconfig.json
  packages/router/tsconfig.json
  packages/web/jest.config.js
  packages/web/package.json
  packages/web/src/__typetests__/cellProps.test.tsx
  packages/web/src/__typetests__/cellSuccessData.test.tsx
  packages/web/src/__typetests__/tsconfig.json
  yarn.lock
Labels: release:chore

#9462 preview stats when building storybook for Chromatic "TurboSnap"
  packages/cli-packages/storybook/src/commands/storybookHandler.ts
Labels: release:feature

#9342 feature: Realtime setup and generator commands out of experimental and into main cli
  docs/docs/cli-commands.md
  packages/cli/src/commands/experimental/setupServerFileHandler.js
  packages/cli/src/commands/experimental/util.js
  packages/cli/src/commands/generate/realtime/realtime.js
  packages/cli/src/commands/generate/realtime/realtimeHandler.js
  packages/cli/src/commands/generate/realtime/templates/liveQueries/.keep
  packages/cli/src/commands/generate/realtime/templates/liveQueries/blank/blank.sdl.ts.template
  packages/cli/src/commands/generate/realtime/templates/liveQueries/blank/blank.service.ts.template
  packages/cli/src/commands/generate/realtime/templates/realtime.ts.template
  packages/cli/src/commands/generate/realtime/templates/subscriptions/.keep
  packages/cli/src/commands/generate/realtime/templates/subscriptions/blank/blank.sdl.ts.template
  packages/cli/src/commands/generate/realtime/templates/subscriptions/blank/blank.service.ts.template
  packages/cli/src/commands/generate/realtime/templates/subscriptions/blank/blank.ts.template
  packages/cli/src/commands/setup/realtime/realtime.js
  packages/cli/src/commands/setup/realtime/realtimeHandler.js
  packages/cli/src/commands/setup/realtime/templates/defer/fastAndSlowFields/fastAndSlowFields.sdl.template
  packages/cli/src/commands/setup/realtime/templates/defer/fastAndSlowFields/fastAndSlowFields.ts.template
  packages/cli/src/commands/setup/realtime/templates/liveQueries/.keep
  packages/cli/src/commands/setup/realtime/templates/liveQueries/auctions/auctions.sdl.ts.template
  packages/cli/src/commands/setup/realtime/templates/liveQueries/auctions/auctions.ts.template
  packages/cli/src/commands/setup/realtime/templates/realtime.ts.template
  packages/cli/src/commands/setup/realtime/templates/stream/alphabet/alphabet.sdl.template
  packages/cli/src/commands/setup/realtime/templates/stream/alphabet/alphabet.ts.template
  packages/cli/src/commands/setup/realtime/templates/subscriptions/countdown/countdown.ts.template
  packages/cli/src/commands/setup/realtime/templates/subscriptions/newMessage/newMessage.ts.template
  packages/cli/src/commands/setup/realtime/templates/subscriptions/newMessage/rooms.sdl.ts.template
  packages/cli/src/commands/setup/realtime/templates/subscriptions/newMessage/rooms.ts.template
Labels: release:feature, fixture-ok

#9416 feature: Support GraphQL Trusted Documents aka Persisted Operations for added security
  __fixtures__/example-todo-main/api/src/lib/trustedDocumentsStore.ts
  __fixtures__/example-todo-main/web/src/graphql/fragment-masking.ts
  __fixtures__/example-todo-main/web/src/graphql/gql.ts
  __fixtures__/example-todo-main/web/src/graphql/graphql.ts
  __fixtures__/example-todo-main/web/src/graphql/index.ts
  __fixtures__/example-todo-main/web/src/graphql/persisted-documents.json
  __fixtures__/example-todo-main/web/src/types/types.d.ts
  __fixtures__/fragment-test-project/api/src/lib/persistedOperations.json
  __fixtures__/fragment-test-project/redwood.toml
  __fixtures__/fragment-test-project/web/src/graphql/persistedOperations.json
  __fixtures__/fragment-test-project/web/src/graphql/possible-types.ts
  __fixtures__/test-project/web/src/App.tsx
  docs/docs/graphql.md
  docs/docs/graphql/fragments.md
  docs/docs/graphql/mocking-graphql-requests.md
  docs/docs/graphql/realtime.md
  docs/docs/graphql/trusted-documents.md
  docs/docs/testing.md
  docs/sidebars.js
  packages/babel-config/src/web.ts
  packages/graphql-server/package.json
  packages/graphql-server/src/createGraphQLYoga.ts
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/plugins/index.ts
  packages/graphql-server/src/plugins/useRedwoodTrustedDocuments.ts
  packages/graphql-server/src/types.ts
  packages/internal/package.json
  packages/internal/src/__tests__/__snapshots__/possibleTypes.test.ts.snap
  packages/internal/src/__tests__/__snapshots__/typeDefinitions.test.ts.snap
  packages/internal/src/__tests__/build_web.test.ts
  packages/internal/src/__tests__/clientPreset.test.ts
  packages/internal/src/__tests__/files.test.ts
  packages/internal/src/__tests__/possibleTypes.test.ts
  packages/internal/src/__tests__/typeDefinitions.test.ts
  packages/internal/src/generate/clientPreset.ts
  packages/internal/src/generate/generate.ts
  packages/internal/src/generate/possibleTypes.ts
  packages/internal/src/generate/trustedDocuments.ts
  packages/internal/src/generate/types.ts
  packages/internal/src/generate/watch.ts
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/__tests__/fixtures/redwood.graphql.toml
  packages/project-config/src/config.ts
  packages/web/src/apollo/index.tsx
  packages/web/src/global.web-auto-imports.ts
  yarn.lock
Labels: release:feature

#9546 Prerender smoke-test: await helper function
  tasks/smoke-tests/prerender/tests/prerender.spec.ts
Labels: release:chore

#9381 chore(CI): refactor yarn `smoke-test`
  package.json
  tasks/smoke-tests/README.md
  tasks/smoke-tests/jsconfig.json
  tasks/smoke-tests/smoke-tests.mjs
Labels: release:chore

#9362 Added prompt, if the directory already exists
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:feature, crwa-ok

#9364 💬 Added details for using GitPod within Create Redwood App
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:feature

#9548 docs(docker): add troubleshooting section for python
  docs/docs/docker.md
  packages/cli/src/commands/experimental/templates/docker/Dockerfile
Labels: release:docs

#9551 fix(docker): correct links, fix typos
  docs/docs/docker.md
Labels: release:docs

#9552 Docker docs: Typo fixes
  docs/docs/docker.md
Labels: release:docs

#9553 RSC: Combine RSC server with StreamingSSR server
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveBothHandler.js
  packages/core/config/webpack.common.js
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/viteDistDir/client-build-manifest.json
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/webpackDistDir/client-build-manifest.json
  packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts
  packages/prerender/src/runPrerender.tsx
  packages/vite/src/buildFeServer.ts
  packages/vite/src/index.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/runRscFeServer.ts
  packages/vite/src/waku-lib/rsc-utils.ts
Labels: release:chore

#9559 Remove GitHub action that creates new issue with metrics
  .github/workflows/monthly_issue_metrics.yml
  .github/workflows/weekly_issue_metrics.yml
Labels: release:chore

#9391 fix(deps): update @types/react to v18.2.37
  __fixtures__/test-project-rsc-external-packages/web/package.json
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/router/package.json
  packages/studio/package.json
  packages/testing/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:fix

#9557 fix(streaming): Fix css loading on dev server on Windows
  packages/vite/src/streaming/collectCss.ts
Labels: release:fix

#9568 fix(cli): Remove boxen from default error output
  packages/cli/src/lib/exit.js
Labels: release:fix

#9573 chore: clean up `RouteParams` type test structure
  packages/router/src/__typetests__/routeParamsTypes.test.ts
Labels: release:chore

#9388 9316/update mantine setup
  .gitignore
  packages/cli/src/commands/setup/ui/libraries/mantine.js
  packages/cli/src/commands/setup/ui/templates/mantine-postcss.config.js.template
  packages/cli/src/commands/setup/ui/templates/mantine.storybook.preview.js.template
Labels: release:fix, fixture-ok

#9558 fix(streaming-ssr): Fixes running the streaming server using rw serve
  packages/vite/src/streaming/createReactStreamingHandler.ts
Labels: release:fix

#9577 Experimental Dockerfile: Fix typo in setup command
  packages/cli/src/commands/experimental/setupDockerHandler.js
Labels: release:fix

#9583 fix: Remove "god code" typos from auth READMEs
  packages/auth-providers/auth0/api/README.md
  packages/auth-providers/auth0/setup/README.md
  packages/auth-providers/auth0/web/README.md
  packages/auth-providers/azureActiveDirectory/api/README.md
  packages/auth-providers/azureActiveDirectory/setup/README.md
  packages/auth-providers/azureActiveDirectory/web/README.md
  packages/auth-providers/clerk/api/README.md
  packages/auth-providers/clerk/setup/README.md
  packages/auth-providers/clerk/web/README.md
  packages/auth-providers/custom/setup/README.md
  packages/auth-providers/dbAuth/api/README.md
  packages/auth-providers/dbAuth/setup/README.md
  packages/auth-providers/dbAuth/web/README.md
  packages/auth-providers/firebase/api/README.md
  packages/auth-providers/firebase/setup/README.md
  packages/auth-providers/firebase/web/README.md
  packages/auth-providers/netlify/api/README.md
  packages/auth-providers/netlify/setup/README.md
  packages/auth-providers/netlify/web/README.md
  packages/auth-providers/supabase/api/README.md
  packages/auth-providers/supabase/setup/README.md
  packages/auth-providers/supertokens/api/README.md
  packages/auth-providers/supertokens/setup/README.md
  packages/auth-providers/supertokens/web/README.md
  packages/auth/README.md
Labels: release:docs, fixture-ok

#9582 fix: Prevent `rw graphiql setup` from breaking with encryptSession error
  .editorconfig
  packages/cli/src/commands/setup/graphiql/supportedProviders.js
  packages/studio/api/lib/authProviderEncoders/dbAuthEncoder.ts
Labels: release:fix, fixture-ok

#9579 fix(crwa): clarify docs to avoid issues in yarn modern installs
  docs/docs/tutorial/chapter1/prerequisites.md
Labels: topic/crwa, release:docs

#9588 RSC: Refactor build process
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildClientEntriesFile.ts
  packages/vite/src/rsc/rscBuildCopyCssAssets.ts
  packages/vite/src/rsc/rscBuildServer.ts
  packages/vite/src/rsc/rscRequestHandler.ts
Labels: release:chore

#9575 chore(private-set): Wrap profile page in <PrivateSet> instead of Private
  docs/docs/authentication.md
  docs/docs/how-to/role-based-access-control.md
  docs/docs/prerender.md
  docs/docs/router.md
  docs/docs/tutorial/chapter0/what-is-redwood.md
  docs/docs/tutorial/chapter4/authentication.md
  docs/versioned_docs/version-6.0/authentication.md
  docs/versioned_docs/version-6.0/how-to/role-based-access-control.md
  docs/versioned_docs/version-6.0/prerender.md
  docs/versioned_docs/version-6.0/router.md
  docs/versioned_docs/version-6.0/tutorial/chapter4/authentication.md
  docs/versioned_docs/version-6.0/tutorial/chapter7/rbac.md
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/Routes.js
  packages/structure/src/model/RWRoute.ts
  packages/testing/src/web/__tests__/MockRouter.test.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/Routes.js
Labels: release:docs
