Repository redwoodjs/graphql, pull requests merged in 2023-12, with the labels that each got.

#9593 RSC: Fake server-side routing
  __fixtures__/test-project-rsa/web/src/AboutPage.css
  __fixtures__/test-project-rsa/web/src/AboutPage.tsx
  __fixtures__/test-project-rsa/web/src/App.css
  __fixtures__/test-project-rsa/web/src/HomePage.css
  __fixtures__/test-project-rsa/web/src/HomePage.module.css
  __fixtures__/test-project-rsa/web/src/HomePage.tsx
  __fixtures__/test-project-rsa/web/src/Routes.tsx
  __fixtures__/test-project-rsa/web/src/entries.ts
  __fixtures__/test-project-rsa/web/src/entry.client.tsx
  __fixtures__/test-project-rsa/web/src/entry.server.tsx
  __fixtures__/test-project-rsa/web/src/index.css
  __fixtures__/test-project-rsa/web/src/index.html
  __fixtures__/test-project-rsa/web/src/layouts/NavigationLayout/NavigationLayout.css
  __fixtures__/test-project-rsa/web/src/layouts/NavigationLayout/NavigationLayout.stories.tsx
  __fixtures__/test-project-rsa/web/src/layouts/NavigationLayout/NavigationLayout.test.tsx
  __fixtures__/test-project-rsa/web/src/layouts/NavigationLayout/NavigationLayout.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/AboutPage.css
  __fixtures__/test-project-rsc-external-packages/web/src/AboutPage.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/App.css
  __fixtures__/test-project-rsc-external-packages/web/src/HomePage.css
  __fixtures__/test-project-rsc-external-packages/web/src/HomePage.module.css
  __fixtures__/test-project-rsc-external-packages/web/src/HomePage.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/Routes.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/entries.ts
  __fixtures__/test-project-rsc-external-packages/web/src/entry.client.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/entry.server.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/index.css
  __fixtures__/test-project-rsc-external-packages/web/src/index.html
  __fixtures__/test-project-rsc-external-packages/web/src/layouts/NavigationLayout/NavigationLayout.css
  __fixtures__/test-project-rsc-external-packages/web/src/layouts/NavigationLayout/NavigationLayout.stories.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/layouts/NavigationLayout/NavigationLayout.test.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/layouts/NavigationLayout/NavigationLayout.tsx
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  tasks/smoke-tests/rsa/tests/rsa.spec.ts
  tasks/smoke-tests/rsc-external-packages/tests/rsc-external-packages.spec.ts
Labels: release:feature

#9612 chore(release): refactor release tooling
  .gitignore
  package.json
  tasks/release/.gitignore
  tasks/release/compare/compare.mjs
  tasks/release/compare/compareQA.mjs
  tasks/release/data/releaseCommits.json
  tasks/release/generateReleaseNotes.mjs
  tasks/release/generateReleaseNotesCommand.mjs
  tasks/release/getReleaseCommitsCommand.mjs
  tasks/release/jest.config.js
  tasks/release/prMilestoneCache.json
  tasks/release/release.mjs
  tasks/release/releaseCLI.mjs
  tasks/release/releaseCommand.mjs
  tasks/release/releaseLib.mjs
  tasks/release/tests/__snapshots__/release.test.mjs.snap
  tasks/release/tests/annotatedSymmetricDifference.json
  tasks/release/tests/release.test.mjs
  tasks/release/tests/releaseLibQA.mjs
  tasks/release/tests/releaseMock.test.mjs
  tasks/release/tests/setUpDataFileTest.mjs
  tasks/release/tests/test.commitTriageData.json
  tasks/release/triage/main_next.commitTriageData.json
  tasks/release/triage/triage.mjs
  tasks/release/triage/triageQA.mjs
  tasks/release/triageMainCommand.mjs
  tasks/release/triageNextCommand.mjs
  tasks/release/validateMilestonesCommand.mjs
Labels: release:chore

#9623 fix: add custom inspect to work around a Prisma issue that causes console to hang
  packages/cli/src/commands/consoleHandler.js
Labels: release:fix

#9624 fix(cli): avoid calling rw-vite-build via yarn
  packages/cli/src/commands/buildHandler.js
  packages/vite/package.json
Labels: release:fix

#9622 RSC: Add RW env var definitions to Vite config and include FatalErrorBoundary
  __fixtures__/test-project-rsa/web/src/AboutCounter.tsx
  __fixtures__/test-project-rsa/web/src/AboutPage.tsx
  __fixtures__/test-project-rsa/web/src/entry.client.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/AboutCounter.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/AboutPage.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/entry.client.tsx
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/templates/rsc/AboutCounter.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/AboutPage.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/entry.client.tsx.template
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/react-server-dom-webpack/node-loader.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildRwEnvVars.ts
  packages/vite/src/rsc/rscBuildServer.ts
  packages/vite/src/waku-lib/vite-plugin-rsc.ts
  packages/web/src/config.ts
  tasks/smoke-tests/rsc/tests/rsc.spec.ts
Labels: release:feature

#9630 RSC: Use Routes.tsx for (client-side) routing
  __fixtures__/test-project-rsa/web/src/Routes.tsx
  __fixtures__/test-project-rsa/web/src/entry.client.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/Routes.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/entry.client.tsx
  packages/cli/src/commands/experimental/templates/rsc/Routes.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/entry.client.tsx.template
Labels: release:feature

#9634 chore: Update Testing documentation to link to How to Test Email/Mailer
  docs/docs/testing.md
Labels: release:docs

#9635 chore: Linting and disable some console logs
  packages/vite/src/rsc/rscBuildServer.ts
  packages/web/src/config.ts
Labels: release:chore

#9631 RSC: Remove unused code. Improve code organization
  packages/vite/package.json
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscNodeLoader.ts
  packages/vite/src/rsc/rscVitePlugins.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/waku-lib/builder.ts
  packages/vite/src/waku-lib/config.ts
  packages/vite/src/waku-lib/rsc-utils.ts
Labels: release:chore

#9636 RSC: No need to patch Vite anymore
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/templates/rsc/vite-npm-4.4.9-e845c1bbf8.patch.template
Labels: release:chore

#9585 fix(CLI): merge NODE_OPTIONS in `yarn rw dev`
  packages/cli/src/commands/devHandler.js
  packages/cli/src/lib/__tests__/getDevNodeOptions.test.js
  tasks/release/release.mjs
Labels: release:fix

#9657 Proofreading fixes for realtime docs
  docs/docs/realtime.md
Labels: release:docs

#9656 Update test project fixture
  __fixtures__/test-project/.vscode/tasks.json
  __fixtures__/test-project/web/package.json
Labels: release:chore

#9542 fix: sentry no longer supports tracing as a seperate package
  packages/cli/src/commands/experimental/setupSentryHandler.js
  packages/cli/src/commands/experimental/templates/sentryApi.ts.template
  packages/cli/src/commands/experimental/templates/sentryWeb.ts.template
Labels: release:fix

#9081 chore(eslint): enable `import/no-extraneous-dependencies` rule
  .eslintrc.js
Labels: release:chore

#9664 chore(CI): work out Nx-related CI flakiness
  .gitignore
  .prettierignore
  nx.json
  package.json
  yarn.lock
Labels: release:chore

#9666 RSC: Update rsc test project fixtures
  __fixtures__/test-project-rsa/web/src/AboutCounter.tsx
  __fixtures__/test-project-rsa/web/src/AboutPage.css
  __fixtures__/test-project-rsa/web/src/AboutPage.tsx
  __fixtures__/test-project-rsa/web/src/HomePage.css
  __fixtures__/test-project-rsa/web/src/HomePage.module.css
  __fixtures__/test-project-rsa/web/src/HomePage.tsx
  __fixtures__/test-project-rsa/web/src/entry.server.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/entry.server.tsx
  __fixtures__/test-project-rsc-external-packages/web/src/pages/HomePage/actions.ts
  __fixtures__/test-project-rsc-external-packages/web/src/pages/HomePage/words.ts
Labels: release:chore

#9661 fix(clerk auth): remove errant comma in post-setup notes
  packages/auth-providers/clerk/setup/src/setupHandler.ts
Labels: release:chore

#9662 docs: auth - Clerk - Corrects Home Page generation instructions
  docs/docs/auth/clerk.md
Labels: topic/docs, release:docs

#9703 chore(CI): add RSC fixtures to detect changes list
  .github/actions/detect-changes/cases/rsc.mjs
Labels: release:chore

#9704 RSC: Fix the RSA test project fixture
  __fixtures__/test-project-rsa/web/src/pages/HomePage/Form.tsx
  __fixtures__/test-project-rsa/web/src/pages/HomePage/HomePage.tsx
  __fixtures__/test-project-rsa/web/src/pages/HomePage/chat.ts
Labels: release:chore

#9711 DT types for jest-dom should not be used
  packages/forms/package.json
  packages/web/package.json
  yarn.lock
Labels: release:breaking

#9710 Update Toast Notifications Docs with Example of Async Toast using `toast.promise`
  docs/docs/toast-notifications.md
Labels: topic/docs, topic/web, release:docs

#9713 Revert `@testing-library/jest-dom` v6 upgrade
  package.json
  packages/auth/package.json
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/forms/package.json
  packages/router/src/__tests__/location.test.tsx
  packages/router/src/__tests__/nestedSets.test.tsx
  packages/router/src/__tests__/route-announcer.test.tsx
  packages/router/src/__tests__/route-focus.test.tsx
  packages/router/src/__tests__/routeScrollReset.test.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/__tests__/setContextReuse.test.tsx
  packages/testing/jest.setup.ts
  packages/testing/package.json
  packages/web/package.json
  packages/web/src/components/FetchConfigProvider.test.tsx
  packages/web/src/components/GraphQLHooksProvider.test.tsx
  packages/web/src/components/cell/createCell.test.tsx
  packages/web/src/components/cell/createSuspendingCell.test.tsx
  packages/web/src/components/portalHead.test.tsx
  yarn.lock
Labels: release:chore

#9709 Studio: Make port configurable
  packages/cli/src/commands/experimental/templates/opentelemetry.ts.template
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
  packages/studio/api/fastify/react.ts
  packages/studio/api/graphql/yoga.ts
  packages/studio/api/index.ts
  packages/studio/api/lib/rewriteWebToUsePort.ts
  packages/studio/api/mail/index.ts
  packages/studio/api/types.ts
  packages/studio/web/index.html
  packages/studio/web/src/Pages/GraphiQL.tsx
  packages/studio/web/src/main.tsx
  packages/studio/web/src/vite-env.d.ts
Labels: release:feature

#9717 chore(RSC): update RSC test projects to latest canary
  __fixtures__/test-project-rsa/api/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-external-packages/api/package.json
  __fixtures__/test-project-rsc-external-packages/package.json
  __fixtures__/test-project-rsc-external-packages/web/package.json
Labels: release:chore

#9719 Revert "Revert `@testing-library/jest-dom` v6 upgrade (#9713)"
  __fixtures__/test-project/.nvmrc
  __fixtures__/test-project/web/tsconfig.json
  package.json
  packages/auth/package.json
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/babel-config/src/__tests__/common.test.ts
  packages/create-redwood-app/templates/js/web/jsconfig.json
  packages/create-redwood-app/templates/ts/web/tsconfig.json
  packages/forms/package.json
  packages/router/src/__tests__/location.test.tsx
  packages/router/src/__tests__/nestedSets.test.tsx
  packages/router/src/__tests__/route-announcer.test.tsx
  packages/router/src/__tests__/route-focus.test.tsx
  packages/router/src/__tests__/routeScrollReset.test.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/__tests__/setContextReuse.test.tsx
  packages/testing/jest.setup.ts
  packages/testing/package.json
  packages/web/package.json
  packages/web/src/components/FetchConfigProvider.test.tsx
  packages/web/src/components/GraphQLHooksProvider.test.tsx
  packages/web/src/components/cell/createCell.test.tsx
  packages/web/src/components/cell/createSuspendingCell.test.tsx
  packages/web/src/components/portalHead.test.tsx
  yarn.lock
Labels: release:breaking

#9721 docs(#9006) - Update redwoodjs cli to include correct forum url
  packages/cli/src/commands/experimental/setupSentryHandler.js
Labels: release:docs

#9722 Update yarn.lock for docs/ following yarn v4 upgrade
  docs/yarn.lock
Labels: release:chore

#9587 💬 Fixed formatting within the docs
  docs/docs/how-to/oauth.md
  docs/versioned_docs/version-6.0/how-to/oauth.md
Labels: topic/docs, release:docs

#9723 Update `.vscode/settings.json` files for ESLint setting
  .vscode/settings.json
  __fixtures__/test-project/.vscode/settings.json
  packages/create-redwood-app/templates/js/.vscode/settings.json
  packages/create-redwood-app/templates/ts/.vscode/settings.json
Labels: release:fix

#9621 fix "Core Team" link
  docs/docs/introduction.md
  tasks/all-contributors/README.md
Labels: topic/docs, release:docs

#9591 Use TS 5.3 import attributes
  babel.config.js
  packages/vite/src/buildRouteManifest.ts
  packages/vite/src/runFeServer.ts
Labels: release:chore

#9720 Fix grammar
  docs/docs/tutorial/chapter0/what-is-redwood.md
Labels: release:docs

#5869 Preserve trailing whitespace for Markdown, HTML & MJML (RedwoodJS project + create-redwood-app template)
  .vscode/settings.json
  __fixtures__/test-project-rsa/.vscode/settings.json
  docs/docs/project-configuration-dev-test-build.mdx
  packages/create-redwood-app/templates/js/.editorconfig
Labels: release:feature

#9724 Fixed closing tag </PrivateSet> used as opening tag in several places
  docs/docs/tutorial/chapter4/authentication.md
Labels: release:docs

#9637 e2e: Explain why we're setting package resolutions
  tasks/run-e2e
Labels: release:chore

#9547 ✨ Added autodocs to component Storybook Stories
  __fixtures__/test-project/web/src/components/Author/Author.stories.tsx
  __fixtures__/test-project/web/src/components/AuthorCell/AuthorCell.stories.tsx
  __fixtures__/test-project/web/src/components/BlogPost/BlogPost.stories.tsx
  __fixtures__/test-project/web/src/components/BlogPostCell/BlogPostCell.stories.tsx
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.stories.tsx
  __fixtures__/test-project/web/src/components/WaterfallBlogPostCell/WaterfallBlogPostCell.stories.tsx
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/templates/stories.tsx.template
  packages/cli/src/commands/generate/component/templates/stories.tsx.template
  tasks/smoke-tests/storybook/tests/storybook.spec.ts
Labels: release:feature

#9374 Adds `allowedUserFields` option to define the only data that can be returned to client by dbAuth functions
  docs/docs/auth/dbauth.md
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.ts.template
Labels: topic/auth, release:breaking, fixture-ok, topic/security

#9726 Add a note about build and runtime environments
  docs/docs/environment-variables.md
  docs/versioned_docs/version-6.0/environment-variables.md
Labels: release:docs

#9049 Export SignupHandlerOptions interface and update its userAttributes type
  __fixtures__/test-project/api/src/functions/auth.ts
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.ts.template
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.webAuthn.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.webAuthn.ts.template
  tasks/test-project/tasks.js
  tasks/test-project/tui-tasks.js
Labels: release:feature

#9012 fix: Safeguard for Sentry default templates + nitpick
  packages/cli/src/commands/experimental/setupSentryHandler.js
  packages/cli/src/commands/experimental/templates/sentryApi.ts.template
  packages/cli/src/commands/experimental/templates/sentryWeb.ts.template
Labels: release:fix

#9178 fix(docs): update webAuthn import in dbauth doc #9170
  docs/docs/auth/dbauth.md
  docs/versioned_docs/version-4.x/auth/dbauth.md
  docs/versioned_docs/version-5.x/auth/dbauth.md
  docs/versioned_docs/version-6.0/auth/dbauth.md
Labels: release:docs

#9544 chore(docs): Improve docs deploy preview ignore logic
  .github/actions/detect-changes/cases/code_changes.mjs
  .github/actions/detect-changes/cases/onlydocs.mjs
  .github/actions/detect-changes/detectChanges.mjs
  .github/actions/detect-changes/yarn.lock
  docs/ignore_build.mjs
Labels: release:chore

#8264 Support custom @id column name in scaffold
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldCustomIdName.test.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/Name.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NameCell.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NameForm.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/Names.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NewName.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/pages/EditNamePage.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/pages/NamePage.tsx.template
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/generate/sdl/templates/sdl.js.template
  packages/cli/src/commands/generate/sdl/templates/sdl.ts.template
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/generate/service/templates/service.ts.template
  packages/cli/src/commands/generate/service/templates/test.ts.template
Labels: release:feature, fixture-ok

#9315 Adds new <Metadata> component for proper <meta> tag generation
  __fixtures__/test-project/web/src/pages/AboutPage/AboutPage.tsx
  __fixtures__/test-project/web/src/pages/BlogPostPage/BlogPostPage.tsx
  __fixtures__/test-project/web/src/pages/ContactUsPage/ContactUsPage.tsx
  __fixtures__/test-project/web/src/pages/DoublePage/DoublePage.tsx
  __fixtures__/test-project/web/src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
  __fixtures__/test-project/web/src/pages/HomePage/HomePage.tsx
  __fixtures__/test-project/web/src/pages/LoginPage/LoginPage.tsx
  __fixtures__/test-project/web/src/pages/ProfilePage/ProfilePage.tsx
  __fixtures__/test-project/web/src/pages/ResetPasswordPage/ResetPasswordPage.tsx
  __fixtures__/test-project/web/src/pages/SignupPage/SignupPage.tsx
  docs/docs/seo-head.md
  docs/static/img/facebook_unfurl.png
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/dbAuth/__tests__/__snapshots__/dbAuth.test.js.snap
  packages/cli/src/commands/generate/dbAuth/templates/forgotPassword.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/login.webAuthn.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/resetPassword.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/signup.tsx.template
  packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/page/templates/page.tsx.template
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/ForgotPasswordPage/ForgotPasswordPage.js
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/HomePage/HomePage.js
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/AllJobProfilesPage/AllJobProfilesPage.tsx
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/AllJobsPage/AllJobsPage.tsx
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/JobPage/JobPage.tsx
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/JobProfilePage/JobProfilePage.tsx
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/JobsPage/JobsPage.tsx
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/NewJobPage/NewJobPage.tsx
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/NewJobProfilePage/NewJobProfilePage.tsx
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/LoginPage/LoginPage.js
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/ForgotPasswordPage/ForgotPasswordPage.js
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/HomePage/HomePage.js
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/AllJobProfilesPage/AllJobProfilesPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/AllJobsPage/AllJobsPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/JobPage/JobPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/JobProfilePage/JobProfilePage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/JobsPage/JobsPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/NewJobPage/NewJobPage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/Jobs/NewJobProfilePage/NewJobProfilePage.tsx
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/LoginPage/LoginPage.js
  packages/web/src/components/MetaTags.tsx
  packages/web/src/components/Metadata.test.tsx
  packages/web/src/components/Metadata.tsx
  packages/web/src/index.ts
  tasks/test-project/codemods/blogPostPage.js
  tasks/test-project/codemods/profilePage.js
  tasks/test-project/tasks.js
  tasks/test-project/tui-tasks.js
Labels: topic/web, release:feature

#9729 Fix Studio paths
  packages/studio/api/index.ts
  packages/studio/api/mail/index.ts
Labels: release:fix

#9732 fix(gitpod): enable corepack to get proper node version
  .gitpod.yml
Labels: release:fix

#9736 Fix isCodeFile logic
  .github/actions/detect-changes/cases/code_changes.mjs
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore

#9735 fix(CLI): fix `getDevNodeOptions`
  packages/cli/src/commands/__tests__/dev.test.js
  packages/cli/src/commands/devHandler.js
  packages/cli/src/lib/__tests__/getDevNodeOptions.test.js
Labels: release:fix

#9737 Trusted Documents docs: Proofreading corrections
  docs/docs/graphql/trusted-documents.md
Labels: release:docs

#9734 chore(tooling): add script for getting nested dependency data
  tasks/nmHoisting/README.md
  tasks/nmHoisting/nmHoisting.mjs
  tasks/nmHoisting/nmHoistingData.js
  tasks/nmHoisting/nmHoistingVisualize.html
  tasks/nmHoisting/nmHoistingVisualize.js
Labels: release:chore

#9730 chore(CI): update test project fixture and CRWA for deploy target CI repo
  __fixtures__/test-project/api/db/schema.prisma
  __fixtures__/test-project/web/src/App.tsx
  packages/create-redwood-app/templates/js/web/vite.config.js
  packages/create-redwood-app/templates/ts/web/vite.config.ts
Labels: release:chore

#9744 Update Metadata docs
  docs/docs/seo-head.md
Labels: release:docs

#9743 Fix sshExec() errors not displaying
  packages/cli/src/commands/deploy/baremetal.js
Labels: release:fix

#9742 docs: added some clarification on serverless functions getting executed in a non-serverless environment
  docs/docs/auth/supertokens.md
  docs/docs/serverless-functions.md
Labels: release:docs

#9728 feat(CLI): add check node version middleware, rm `.nvmrc`, yarn engines
  __fixtures__/test-project-rsa/.nvmrc
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsc-external-packages/.nvmrc
  __fixtures__/test-project-rsc-external-packages/package.json
  __fixtures__/test-project/.nvmrc
  __fixtures__/test-project/package.json
  docs/docs/tutorial/chapter1/prerequisites.md
  docs/docs/tutorial/foreword.md
  packages/cli/src/commands/build.js
  packages/cli/src/commands/dev.js
  packages/cli/src/commands/setup/deploy/__tests__/__snapshots__/netlify.test.js.snap
  packages/cli/src/commands/setup/deploy/templates/netlify.js
  packages/cli/src/commands/setup/deploy/templates/render.js
  packages/cli/src/lib/exit.js
  packages/cli/src/middleware/checkForBabelConfig.js
  packages/cli/src/middleware/checkNodeVersion.js
  packages/create-redwood-app/templates/js/.nvmrc
  packages/create-redwood-app/templates/js/README.md
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/.nvmrc
  packages/create-redwood-app/templates/ts/README.md
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-app/tests/template.test.js
Labels: release:feature

#9751 chore(tasks): Add comparison view to nmHoisting visualisation
  tasks/nmHoisting/nmHoisting.mjs
  tasks/nmHoisting/nmHoistingData.js
  tasks/nmHoisting/nmHoistingVisualize.html
  tasks/nmHoisting/nmHoistingVisualize.js
Labels: release:chore

#9639 #9620: Update studio to support variable components (Mailer)
  packages/studio/README.md
  packages/studio/api/mail/index.ts
  packages/studio/api/migrations.ts
  packages/studio/api/services/mail.ts
  packages/studio/package.json
  yarn.lock
Labels: release:feature

#9752 fix(studio): Fix windows path issues
  packages/studio/api/mail/index.ts
  packages/studio/api/services/mail.ts
Labels: release:fix

#9309 add TS support for storybook preview tsx config extension
  __fixtures__/test-project/web/tsconfig.json
  packages/cli/src/commands/setup/i18n/i18nHandler.js
  packages/cli/src/commands/setup/i18n/templates/storybook.preview.tsx.template
  packages/cli/src/commands/setup/ui/libraries/chakra-ui.js
  packages/cli/src/commands/setup/ui/libraries/mantine.js
  packages/cli/src/commands/setup/ui/templates/chakra.storybook.preview.tsx.template
  packages/cli/src/commands/setup/ui/templates/mantine.storybook.preview.tsx.template
  packages/cli/src/lib/__tests__/mergeBasics.test.js
  packages/cli/src/lib/configureStorybook.js
  packages/cli/src/lib/merge/index.js
  packages/cli/src/lib/templates/storybook.preview.js.template
  packages/cli/src/lib/templates/storybook.preview.tsx.template
  packages/create-redwood-app/templates/js/web/jsconfig.json
  packages/create-redwood-app/templates/ts/web/tsconfig.json
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/testing/config/storybook/main.js
Labels: release:feature

#9749 docs: Replaced deprecated <Set private> with PrivateSet within router.md
  docs/docs/router.md
Labels: release:docs

#9754 chore(unit tests): Use side-effect import to fix TS errors
  packages/forms/jest.config.js
  packages/forms/jest.setup.ts
  packages/forms/src/__tests__/form.test.tsx
  packages/router/jest.config.js
  packages/router/jest.setup.js
  packages/router/jest.setup.ts
  packages/router/src/__tests__/links.test.tsx
Labels: release:chore

#9756 Make it easier to find useMatch docs
  docs/docs/router.md
Labels: release:docs

#9574 fix(path-alias): Fix aliasing of paths using ts/jsconfig
  packages/babel-config/src/__tests__/common.test.ts
  packages/babel-config/src/__tests__/tsconfigParsing.test.ts
  packages/babel-config/src/api.ts
  packages/babel-config/src/common.ts
  packages/babel-config/src/web.ts
Labels: release:fix

#9762 chore(ci): Better error handling in detectChanges.mjs
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore

#9763 SSR smoke-test: Use <Metadata />
  .github/actions/detect-changes/cases/ssr.mjs
  tasks/test-project/codemods/delayedPage.js
Labels: release:fix

#9640 fix(apollo): Enhance error differently for Suspense Cells
  docs/docs/router.md
  docs/static/img/router/cell_req_error.png
  packages/web/src/apollo/links.tsx
  packages/web/src/apollo/suspense.tsx
  packages/web/src/components/DevFatalErrorPage.tsx
Labels: release:fix

#9757 Fix supertokens docs & integration issues
  docs/docs/auth/supertokens.md
  packages/auth-providers/supertokens/setup/src/templates/api/lib/supertokens.ts.template
  packages/auth-providers/supertokens/setup/src/templates/web/auth.tsx.template
  packages/cli-helpers/src/auth/__tests__/fixtures/supertokensSetup/templates/api/lib/supertokens.ts.template
Labels: topic/docs, topic/auth, release:fix, fixture-ok

#9765 docs: Supertokens.md: Fix typo
  docs/docs/auth/supertokens.md
Labels: release:docs

#8589 Adds a note about the two commands you will use with your schema to the top of the schema file
  __fixtures__/test-project/api/db/schema.prisma
  packages/create-redwood-app/templates/js/api/db/schema.prisma
  packages/create-redwood-app/templates/ts/api/db/schema.prisma
Labels: release:chore

#9755 [RFC]: useRoutePaths
  docs/docs/router.md
  packages/internal/src/generate/templates/web-routerRoutes.d.ts.template
  packages/router/src/__tests__/useRoutePaths.test.tsx
  packages/router/src/index.ts
  packages/router/src/router-context.tsx
  packages/router/src/router.tsx
  packages/router/src/useRoutePaths.ts
Labels: release:feature

#9764 Docker: Update to work with corepack and yarn v4
  docs/docs/docker.md
  packages/cli/src/commands/experimental/templates/docker/Dockerfile
Labels: release:fix

#9768 docker.md: Fix web path
  docs/docs/docker.md
Labels: release:docs

#9758 useRouteName
  docs/docs/router.md
  packages/internal/src/generate/templates/web-routerRoutes.d.ts.template
  packages/router/src/index.ts
  packages/router/src/router-context.tsx
  packages/router/src/router.tsx
  packages/router/src/useRouteName.tsx
Labels: release:feature

#9769 chore(ci): retry detectChanges on error
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore

#9772 chore(ci): retry detectChanges on error, and await result
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore

#9619 Allow GraphQL documents to be typed with a TypedDocumentNode for fully-typed result and variables objects
  packages/internal/src/__tests__/clientPreset.test.ts
  packages/internal/src/generate/clientPreset.ts
  packages/web/src/components/GraphQLHooksProvider.tsx
  packages/web/src/index.ts
Labels: release:feature

#9770 chore(router): Move useMatch to its own file
  packages/router/src/__tests__/links.test.tsx
  packages/router/src/__tests__/useMatch.test.tsx
  packages/router/src/index.ts
  packages/router/src/links.tsx
  packages/router/src/useMatch.ts
  packages/router/src/util.ts
Labels: release:chore

#9775 fix: Fixes way OpenTelemetry setup template uses project-config for port setting
  packages/cli/src/commands/experimental/templates/opentelemetry.ts.template
Labels: release:fix

#9777 fix(otel): Fix OTel sdk loading
  packages/api-server/src/watch.ts
  packages/cli/src/commands/experimental/setupOpentelemetryHandler.js
  packages/cli/src/commands/experimental/templates/opentelemetry.ts.template
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
Labels: release:fix

#9780 Fix dbAuth allowUserFields initialization syntax
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.ts.template
Labels: release:fix, fixture-ok

#9779 chore(test-project): Fix test-project generation script, and regenerate fixture
  __fixtures__/test-project/README.md
  __fixtures__/test-project/api/package.json
  __fixtures__/test-project/api/src/functions/auth.ts
  __fixtures__/test-project/api/src/functions/graphql.ts
  __fixtures__/test-project/api/src/lib/auth.ts
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/vite.config.ts
  tasks/test-project/codemods/models.js
  tasks/test-project/templates/api/context.test.ts.template
  tasks/test-project/tui-tasks.js
  tasks/test-project/util.js
Labels: release:chore

#9781 Use build:pack for dbauth when rebuilding the test project
  __fixtures__/test-project/api/package.json
  __fixtures__/test-project/web/package.json
  tasks/test-project/tui-tasks.js
Labels: release:chore

#9782 chore(framework-tools): .gitignore
  .gitignore
Labels: release:chore

#9778 fix: Support Custom Id Field Names in when generating Cells
  __fixtures__/test-project/web/src/App.tsx
  __fixtures__/test-project/web/src/graphql/possibleTypes.ts
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/__tests__/cell.test.js
  packages/cli/src/commands/generate/cell/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/cell/templates/cell.tsx.template
  packages/cli/src/commands/generate/cell/templates/cellList.tsx.template
  packages/cli/src/commands/generate/cell/templates/mock.js.template
  packages/cli/src/commands/generate/cell/templates/mockList.js.template
  packages/cli/src/commands/generate/cell/utils/utils.js
Labels: topic/cells, release:fix

#9693 feat(scaffold/cell): Adds TypedDocument Support to Cell and Scaffold Generators
  __fixtures__/test-project/web/src/components/AuthorCell/AuthorCell.tsx
  __fixtures__/test-project/web/src/components/BlogPostCell/BlogPostCell.tsx
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.tsx
  __fixtures__/test-project/web/src/components/Contact/Contact/Contact.tsx
  __fixtures__/test-project/web/src/components/Contact/ContactCell/ContactCell.tsx
  __fixtures__/test-project/web/src/components/Contact/ContactForm/ContactForm.tsx
  __fixtures__/test-project/web/src/components/Contact/Contacts/Contacts.tsx
  __fixtures__/test-project/web/src/components/Contact/ContactsCell/ContactsCell.tsx
  __fixtures__/test-project/web/src/components/Contact/EditContactCell/EditContactCell.tsx
  __fixtures__/test-project/web/src/components/Contact/NewContact/NewContact.tsx
  __fixtures__/test-project/web/src/components/Post/EditPostCell/EditPostCell.tsx
  __fixtures__/test-project/web/src/components/Post/NewPost/NewPost.tsx
  __fixtures__/test-project/web/src/components/Post/Post/Post.tsx
  __fixtures__/test-project/web/src/components/Post/PostCell/PostCell.tsx
  __fixtures__/test-project/web/src/components/Post/PostForm/PostForm.tsx
  __fixtures__/test-project/web/src/components/Post/Posts/Posts.tsx
  __fixtures__/test-project/web/src/components/Post/PostsCell/PostsCell.tsx
  __fixtures__/test-project/web/src/components/WaterfallBlogPostCell/WaterfallBlogPostCell.tsx
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/templates/cell.tsx.template
  packages/cli/src/commands/generate/cell/templates/cellList.tsx.template
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/Name.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NameCell.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NameForm.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/Names.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NewName.tsx.template
Labels: release:feature

#9784 chore(release-tooling): fetch -> pull
  tasks/release/releaseLib.mjs
Labels: release:chore

#9783 chore(crwa): add e2e tests for create-redwood-app
  .github/workflows/ci.yml
  packages/create-redwood-app/.babelrc.js
  packages/create-redwood-app/jest.config.js
  packages/create-redwood-app/package.json
  packages/create-redwood-app/scripts/setUpTestProject.mjs
  packages/create-redwood-app/scripts/tsToJS.mjs
  packages/create-redwood-app/templates/js/.editorconfig
  packages/create-redwood-app/templates/js/web/jsconfig.json
  packages/create-redwood-app/tests/e2e.test.mjs
  packages/create-redwood-app/tests/e2e_prompts.sh
  packages/create-redwood-app/tests/e2e_prompts_git.sh
  packages/create-redwood-app/tests/e2e_prompts_m.sh
  packages/create-redwood-app/tests/e2e_prompts_overwrite.sh
  packages/create-redwood-app/tests/e2e_prompts_ts.sh
  packages/create-redwood-app/tests/templates.test.mjs
Labels: release:chore, fixture-ok
