Repository redwoodjs/graphql, pull requests merged in 2023-04, with the labels that each got.

#7990 chore: unpublish packages script
  tasks/unpublishPackageVersions.mjs
Labels: release:chore

#7852 fix(clerk auth): set auth state to loading while reauthenticating
  packages/auth-providers/clerk/web/src/clerk.tsx
  packages/auth/src/AuthImplementation.ts
  packages/auth/src/AuthProvider/useReauthenticate.ts
Labels: release:fix

#7947 feat(clerk auth): make `getToken` options globally configurable
  packages/auth-providers/clerk/web/src/clerk.tsx
Labels: release:feature

#7993 remove serverless deploy option
  packages/cli/src/commands/deploy/serverless.js
  packages/cli/src/commands/setup/deploy/providers/serverless.js
  packages/cli/src/commands/setup/deploy/templates/serverless/api.js
  packages/cli/src/commands/setup/deploy/templates/serverless/web.js
Labels: release:feature-breaking, fixture-ok

#7995 feat: bump API build target 16.20
  __fixtures__/test-project/package.json
  babel.config.js
  packages/create-redwood-app/template/package.json
  packages/internal/src/build/babel/api.ts
Labels: release:feature-breaking, fixture-ok

#8004 chore(ci): Update node version for telemetry check
  .github/workflows/ci.yml
Labels: release:chore

#8013 Update docs to reference creating an ED25519 key instead of RSA
  docs/docs/intro-to-servers.md
  docs/versioned_docs/version-4.0/intro-to-servers.md
Labels: topic/deployment, release:docs

#7672 chore(build): Avoid prebuilding api side, instead use an esbuild plugin
  packages/api-server/src/watch.ts
  packages/cli/jsconfig.json
  packages/cli/src/commands/__tests__/build.test.js
  packages/cli/src/commands/buildHandler.js
  packages/cli/src/commands/deploy/__tests__/nftPack.test.js
  packages/internal/src/__tests__/build_api.test.ts
  packages/internal/src/build/api.ts
  packages/internal/src/build/babel/api.ts
Labels: release:chore

#8018 Fix spelling mistake in prerender error message
  packages/prerender/src/runPrerender.tsx
Labels: release:fix

#8030 fix(babel-vite): Also transform jsx Cell files
  packages/internal/src/build/babel/web.ts
Labels: release:fix

#8024 chore(cli): Enable 'next' and 'experimental' tags for `rw upgrade`
  docs/docs/cli-commands.md
  packages/cli/src/commands/upgrade.js
Labels: release:chore

#8031 update scaffold generator to use emptyAsUndefined when its needed
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/scaffold/__tests__/shouldUseEmptyAsUndefined.test.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/components/NameForm.tsx.template
Labels: release:feature, fixture-ok

#8015 Update Chapter 7 with info on adding User SDL
  docs/docs/tutorial/chapter7/api-side-currentuser.md
Labels: release:docs

#7813 chore: DRAFT Improve LogFormatter to include Types and Support Additional Options without the Custom attribute
  packages/api-server/src/__tests__/logFormatter.test.ts
  packages/api-server/src/logFormatter/formatters.ts
  packages/api-server/src/logFormatter/index.ts
Labels: release:feature-breaking, topic/logging

#7979 WIP: fix(#7787): Added userInsensitive for comparrison checks in dbAuth
  docs/docs/auth/dbauth.md
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
Labels: release:feature

#8054 Format source
  packages/api-server/src/__tests__/logFormatter.test.ts
Labels: release:chore

#8045 Fix(#7787) - Updates to previous PR for adding insensitive checks for signups
  docs/docs/auth/dbauth.md
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
Labels: release:feature

#8058 fix(cli): Install studio package if not found
  packages/cli/src/commands/experimental/studio.js
  packages/cli/src/lib/packages.js
Labels: release:fix

#8056 Revert "chore(build): Avoid prebuilding api side, instead use an esbuild plugin"
  packages/api-server/src/watch.ts
  packages/cli/src/commands/buildHandler.js
  packages/cli/src/commands/deploy/__tests__/nftPack.test.js
  packages/internal/src/__tests__/build_api.test.ts
  packages/internal/src/build/api.ts
  packages/internal/src/build/babel/api.ts
Labels: release:chore

#8062 fix(crwa): Fix failure in case of disabled telemetry
  packages/create-redwood-app/src/create-redwood-app.js
  packages/create-redwood-app/src/telemetry.js
Labels: release:fix

#8073 [CRWA] Housekeeping follow up to #8043
  packages/create-redwood-app/jsconfig.json
  packages/create-redwood-app/package.json
  yarn.lock
Labels: release:chore

#8074 [CRWA, Tui] Try removing Babel and bundling minimally
  .gitignore
  packages/create-redwood-app/.babelrc.js
  packages/create-redwood-app/build.mjs
  packages/create-redwood-app/jest.config.js
  packages/create-redwood-app/package.json
  packages/create-redwood-app/src/__tests__/web-template.test.js
  packages/tui/.babelrc.js
  packages/tui/build.mjs
  packages/tui/package.json
  tasks/run-e2e
  yarn.lock
Labels: release:chore

#8060 Deprecate serverless aws deploy as an officially supported option
  docs/docs/deploy/serverless.md
  packages/cli/src/commands/deploy/serverless.js
  packages/cli/src/commands/setup/deploy/providers/serverless.js
  packages/cli/src/commands/setup/deploy/templates/serverless/api.js
  packages/cli/src/commands/setup/deploy/templates/serverless/web.js
Labels: release:feature-breaking, fixture-ok

#8040 Don't error out when using Vite with RW v5
  packages/core/config/webpack.common.js
  packages/internal/src/__tests__/build_web.test.ts
  packages/internal/src/__tests__/nestedPages.test.ts
  packages/internal/src/build/babel/web.ts
  packages/internal/src/build/babelPlugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
  packages/internal/src/build/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts
  packages/internal/src/webpackPlugins/ChunkReferencesPlugin.ts
  packages/prerender/src/detection/index.ts
  packages/prerender/src/runPrerender.tsx
  packages/router/src/active-route-loader.tsx
  packages/router/src/util.ts
Labels: release:fix

#8106 Bump the Node.js build target to 18 LTS
  .github/actions/check_test_project_fixture/action.yml
  .github/actions/only_doc_changes/action.yml
  .github/actions/setup_test_project/action.yaml
  .github/actions/update_all_contributors/action.yml
  .github/workflows/check-test-project-fixture.yml
  .github/workflows/ci.yml
  .github/workflows/publish-release-candidate.yml
  .github/workflows/update-all-contributors.yml
  __fixtures__/test-project/package.json
  babel.config.js
  docs/docs/how-to/test-in-github-actions.md
  packages/create-redwood-app/template/package.json
  packages/internal/src/__tests__/build_api.test.ts
  packages/internal/src/build/api.ts
  packages/internal/src/build/babel/api.ts
  tasks/check/action.yml
Labels: release:feature-breaking

#8014 Option to enable GraphQL introspection in production
  docs/docs/graphql.md
  docs/docs/security.md
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/functions/types.ts
Labels: topic/graphql, release:feature

#8001 Allow multiple spaces in PRISMA_DIRECT_URL_REGEXP
  packages/testing/src/api/__tests__/directUrlHelpers.test.ts
  packages/testing/src/api/directUrlHelpers.ts
Labels: release:chore

#7683 [WIP] initial commit on coherence PR
  docs/docs/deploy/coherence.md
  docs/sidebars.js
  packages/cli/src/commands/setup/deploy/providers/coherence.js
  packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
Labels: release:feature, fixture-ok

#8037 changing react link
  docs/docs/tutorial/chapter1/prerequisites.md
Labels: release:docs

#7962 feat: Support env var interpolation in baremetal deploy.toml
  docs/docs/deploy/baremetal.md
  packages/cli/package.json
  packages/cli/src/commands/deploy/__tests__/baremetal.test.js
  packages/cli/src/commands/deploy/baremetal.js
  yarn.lock
Labels: release:feature

#8128 fix(CRWA): make node and yarn compatibility checks fail
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#8132 fix(CRWA): handle node version compat check failures
  __fixtures__/test-project/package.json
  packages/create-redwood-app/package.json
  packages/create-redwood-app/src/create-redwood-app.js
  packages/create-redwood-app/template/package.json
  packages/tui/src/index.ts
  yarn.lock
Labels: release:fix

#8134 fix(codemods): make react do install, add update node engines
  packages/codemods/src/codemods/v5.x.x/checkReactRoot/checkReactRoot.ts
  packages/codemods/src/codemods/v5.x.x/checkReactRoot/checkReactRoot.yargs.ts
  packages/codemods/src/codemods/v5.x.x/updateNodeEngines/README.md
  packages/codemods/src/codemods/v5.x.x/updateNodeEngines/updateNodeEngines.ts
  packages/codemods/src/codemods/v5.x.x/updateNodeEngines/updateNodeEngines.yargs.ts
Labels: release:fix

#8137 fix(v5): revert firebase admin v11 upgrades
  packages/auth-providers/firebase/api/package.json
  yarn.lock
Labels: release:chore

#8140 fix:(v5 codemods): rename react codemod and fix ui
  packages/codemods/src/codemods/v5.x.x/checkReactRoot/__tests__/checkReactRoot.test.ts
  packages/codemods/src/codemods/v5.x.x/checkReactRoot/checkReactRoot.yargs.ts
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/README.md
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/__testfixtures__/default/input/web/src/index.html
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/__testfixtures__/default/output/web/src/index.html
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/__tests__/upgradeToReact18.test.ts
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/upgradeToReact18.ts
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/upgradeToReact18.yargs.ts
Labels: release:fix

#8142 fix: Flightcontrol setup improve SameSite config
  packages/cli/src/commands/setup/deploy/providers/flightcontrol.js
Labels: release:fix, fixture-ok

#8039 fix(cli): Conditionally show nudge about upgrade version toml tags
  packages/cli/src/commands/upgrade.js
Labels: release:fix

#8141 chore(v5): tidy up codemods
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/restSyntax.input.ts
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__testfixtures__/restSyntax.output.ts
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/cellQueryResult.ts
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/cellQueryResult.yargs.ts
  packages/codemods/src/codemods/v5.x.x/detectEmptyCells/detectEmptyCells.ts
  packages/codemods/src/codemods/v5.x.x/detectEmptyCells/detectEmptyCells.yargs.ts
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/__tests__/renameValidateWith.test.ts
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/renameValidateWith.yargs.ts
  packages/codemods/src/codemods/v5.x.x/updateAuth0/__tests__/updateAuth0.ts
  packages/codemods/src/codemods/v5.x.x/updateAuth0ToV2/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v5.x.x/updateAuth0ToV2/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v5.x.x/updateAuth0ToV2/__tests__/updateAuth0ToV2.test.ts
  packages/codemods/src/codemods/v5.x.x/updateAuth0ToV2/updateAuth0ToV2.ts
  packages/codemods/src/codemods/v5.x.x/updateAuth0ToV2/updateAuth0ToV2.yargs.ts
  packages/codemods/src/codemods/v5.x.x/updateNodeEngineTo18/README.md
  packages/codemods/src/codemods/v5.x.x/updateNodeEngineTo18/updateNodeEngineTo18.ts
  packages/codemods/src/codemods/v5.x.x/updateNodeEngineTo18/updateNodeEngineTo18.yargs.ts
  packages/codemods/src/codemods/v5.x.x/updateNodeEngines/README.md
  packages/codemods/src/codemods/v5.x.x/updateNodeEngines/updateNodeEngines.yargs.ts
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/upgradeToReact18.ts
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/upgradeToReact18.yargs.ts
Labels: release:chore

#8143 chore-docs: add Experimental section to cli commands
  docs/docs/cli-commands.md
Labels: release:docs

#8145 fix: list project-config as a dependency in api-server, graphql-server, studio, vite
  packages/api-server/package.json
  packages/graphql-server/package.json
  packages/studio/package.json
  packages/vite/package.json
  yarn.lock
Labels: release:fix

#8149 chore(telemetry): Measure experimental features via toml
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
  packages/telemetry/src/sendTelemetry.ts
Labels: release:chore

#8155 fix(deploy): try-catch attempt to read `redwood.toml` in `makeMergedSchema`
  packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts
Labels: release:fix

#8154 fix(docs): v5-related updates to tutorial and docs
  docs/docs/tutorial/chapter1/file-structure.md
  docs/docs/tutorial/chapter1/installation.md
  docs/docs/tutorial/chapter1/layouts.md
  docs/docs/tutorial/chapter1/prerequisites.md
  docs/docs/tutorial/chapter1/second-page.md
  docs/docs/tutorial/chapter2/getting-dynamic.md
  docs/docs/tutorial/chapter2/side-quest.md
  docs/docs/tutorial/chapter5/first-test.md
  docs/docs/tutorial/chapter6/comment-form.md
  docs/docs/tutorial/chapter6/comments-schema.md
  docs/docs/tutorial/chapter6/multiple-comments.md
  docs/docs/tutorial/foreword.md
Labels: release:docs

#8162 chore(tasks): clean up release tooling
  tasks/release/data/releaseCommits.json
  tasks/release/data/triageMainData.json
  tasks/release/data/triageNextData.json
  tasks/release/generateReleaseNotesCommand.mjs
  tasks/release/sandbox.mjs
Labels: release:chore

#8163 chore(docs): backport v5 tutorial changes
  docs/versioned_docs/version-5.0/tutorial/chapter1/file-structure.md
  docs/versioned_docs/version-5.0/tutorial/chapter1/installation.md
  docs/versioned_docs/version-5.0/tutorial/chapter1/layouts.md
  docs/versioned_docs/version-5.0/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-5.0/tutorial/chapter1/second-page.md
  docs/versioned_docs/version-5.0/tutorial/chapter2/getting-dynamic.md
  docs/versioned_docs/version-5.0/tutorial/chapter2/side-quest.md
  docs/versioned_docs/version-5.0/tutorial/chapter5/first-test.md
  docs/versioned_docs/version-5.0/tutorial/chapter6/comment-form.md
  docs/versioned_docs/version-5.0/tutorial/chapter6/comments-schema.md
  docs/versioned_docs/version-5.0/tutorial/chapter6/multiple-comments.md
  docs/versioned_docs/version-5.0/tutorial/foreword.md
Labels: release:docs

#8161 fix(CRWA): point telemetry url to the new endpoint
  packages/create-redwood-app/src/telemetry.js
Labels: release:fix

#8170 fix(docs): rename authenticationMethod to authMethod
  docs/docs/auth/supabase.md
  docs/versioned_docs/version-5.0/auth/supabase.md
Labels: release:docs

#8171 fix(crwa): use yarn bin in crwa project to install
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#8169 structure package.json: add missing glob dependency
  __fixtures__/test-project/package.json
  packages/structure/package.json
  packages/structure/src/hosts.ts
  packages/structure/src/model/__tests__/model.test.ts
  packages/structure/src/model/util/process_env.ts
  yarn.lock
Labels: release:chore
