Repository redwoodjs/graphql, pull requests merged in 2023-06, with the labels that each got.

#8446 Update codemods package README.md
  packages/codemods/README.md
Labels: release:docs

#8397 feature: Configure Redwood Realtime in GraphQL Yoga
  packages/cli/src/commands/experimental/templates/server.ts.template
  packages/graphql-server/package.json
  packages/graphql-server/src/createGraphQLYoga.ts
  packages/graphql-server/src/index.ts
  packages/graphql-server/src/plugins/__fixtures__/common.ts
  packages/graphql-server/src/plugins/__tests__/__snapshots__/useRedwoodRealtime.test.ts.snap
  packages/graphql-server/src/plugins/__tests__/useRedwoodRealtime.test.ts
  packages/graphql-server/src/plugins/index.ts
  packages/graphql-server/src/plugins/useRedwoodDirective.ts
  packages/graphql-server/src/plugins/useRedwoodRealtime.ts
  packages/graphql-server/src/types.ts
  packages/internal/src/__tests__/__snapshots__/graphqlSchema.test.ts.snap
  packages/internal/src/__tests__/fixtures/graphqlCodeGen/realtime/api/db/schema.prisma
  packages/internal/src/__tests__/fixtures/graphqlCodeGen/realtime/api/src/directives/requireAuth/requireAuth.js
  packages/internal/src/__tests__/fixtures/graphqlCodeGen/realtime/api/src/directives/skipAuth/skipAuth.js
  packages/internal/src/__tests__/fixtures/graphqlCodeGen/realtime/api/src/graphql/currentUser.sdl.ts
  packages/internal/src/__tests__/fixtures/graphqlCodeGen/realtime/api/src/graphql/todos.sdl.js
  packages/internal/src/__tests__/fixtures/graphqlCodeGen/realtime/api/src/lib/db.js
  packages/internal/src/__tests__/fixtures/graphqlCodeGen/realtime/api/src/server.ts
  packages/internal/src/__tests__/fixtures/graphqlCodeGen/realtime/api/src/services/todos/todos.js
  packages/internal/src/__tests__/fixtures/graphqlCodeGen/realtime/api/src/services/todos/todos.test.js
  packages/internal/src/__tests__/fixtures/graphqlCodeGen/realtime/redwood.toml
  packages/internal/src/__tests__/graphqlSchema.test.ts
  packages/internal/src/generate/graphqlSchema.ts
  yarn.lock
Labels: release:feature

#8455 fix(containers): remove `@redwoodjs/api-server`'s `@redwoodjs/internal` requirement
  packages/api-server/package.json
  packages/api-server/src/__tests__/withWebServer.test.ts
  packages/api-server/src/plugins/findPrerenderedHtml.ts
  packages/api-server/src/plugins/lambdaLoader.ts
  packages/api-server/src/plugins/withWebServer.ts
  yarn.lock
Labels: release:fix

#8475 Docs: Fix create statement
  docs/docs/how-to/sending-emails.md
Labels: release:docs

#8487 chore: Cleans up server template for realtime
  packages/cli/src/commands/experimental/templates/server.ts.template
Labels: release:chore

#8454 feat(cli): Lazy install storybook
  package.json
  packages/cli-packages/storybook/README.md
  packages/cli-packages/storybook/build.mjs
  packages/cli-packages/storybook/package.json
  packages/cli-packages/storybook/src/commands/storybook.ts
  packages/cli-packages/storybook/src/commands/storybookHandler.ts
  packages/cli-packages/storybook/src/index.ts
  packages/cli-packages/storybook/src/lib/colors.ts
  packages/cli-packages/storybook/src/lib/project.ts
  packages/cli-packages/storybook/src/types.ts
  packages/cli-packages/storybook/tsconfig.json
  packages/cli/src/index.js
  packages/cli/src/lib/packages.js
  packages/cli/src/plugin.js
  packages/create-redwood-app/templates/js/.redwood/command-cache.json
  packages/create-redwood-app/templates/ts/.redwood/command-cache.json
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
  packages/testing/package.json
  packages/web/src/bins/storybook.ts
  yarn.lock
Labels: release:feature, fixture-ok

#8470 fix: authMiddleware swallows other headers
  packages/web/src/apollo/index.tsx
Labels: release:fix, fixture-ok

#8494 fix(cli): Fix plugin loading logic for built-in commands
  packages/cli/src/plugin.js
  packages/create-redwood-app/templates/js/.redwood/command-cache.json
  packages/create-redwood-app/templates/ts/.redwood/command-cache.json
Labels: release:fix, fixture-ok

#8493 Fix: return a jsx elemnet instead of string
  docs/docs/tutorial/chapter2/routing-params.md
Labels: release:docs

#8449 feat(ci): isolate smoke tests, introduce caching
  .github/actions/actionsLib.mjs
  .github/actions/set-up-test-project/action.yaml
  .github/actions/set-up-test-project/setUpTestProject.mjs
  .github/actions/set-up-yarn-cache/action.yml
  .github/actions/setup_test_project/action.yaml
  .github/actions/setup_test_project/setup_test_project.mjs
  .github/workflows/ci.yml
  package.json
  tasks/smoke-test/playwright-fixtures/devServer.fixture.ts
  tasks/smoke-test/playwright-fixtures/rwServe.fixture.ts
  tasks/smoke-test/playwright-fixtures/storybook.fixture.ts
  tasks/smoke-test/playwright.config.ts
  tasks/smoke-test/tests/authChecks.spec.ts
  tasks/smoke-test/tests/prerender.spec.ts
  tasks/smoke-test/tests/rbacChecks.spec.ts
  tasks/smoke-test/tests/rwDev.spec.ts
  tasks/smoke-test/tests/rwServe.spec.ts
  tasks/smoke-test/tests/storybook.spec.ts
  tasks/smoke-test/util.ts
  tasks/smoke-tests/auth/playwright.config.ts
  tasks/smoke-tests/auth/tests/authChecks.spec.ts
  tasks/smoke-tests/auth/tests/rbacChecks.spec.ts
  tasks/smoke-tests/basePlaywright.config.ts
  tasks/smoke-tests/common.ts
  tasks/smoke-tests/dev/playwright.config.ts
  tasks/smoke-tests/dev/tests/dev.spec.ts
  tasks/smoke-tests/prerender/playwright.config.ts
  tasks/smoke-tests/prerender/tests/prerender.spec.ts
  tasks/smoke-tests/serve/playwright.config.ts
  tasks/smoke-tests/serve/tests/serve.spec.ts
  tasks/smoke-tests/storybook/playwright.config.ts
  tasks/smoke-tests/storybook/tests/storybook.spec.ts
  yarn.lock
Labels: release:chore

#8504 chore(ci): deduplicate yarn cache by removing the `set-up-job` action
  .github/actions/set-up-job/action.yml
  .github/workflows/ci.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-release-candidate.yml
Labels: release:chore

#8471 fix(vite): Tailwind/postcss optimisation issue
  packages/cli/src/commands/buildHandler.js
  packages/internal/src/build/web.ts
  packages/vite/bins/rw-vite-build.mjs
  packages/vite/package.json
  yarn.lock
Labels: release:fix

#8526 chore(ci): use canary version of rwjs vite
  .github/actions/actionsLib.mjs
  .github/workflows/ci.yml
  __fixtures__/test-project/web/package.json
Labels: release:chore

#8510 fix #8509: link to react-hook-form api
  docs/docs/tutorial/chapter3/saving-data.md
Labels: release:docs

#8392 feat(router): Implement routing with Suspense
  packages/internal/src/__tests__/nestedPages.test.ts
  packages/internal/src/build/babelPlugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
  packages/internal/src/build/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts
  packages/router/src/AuthenticatedRoute.tsx
  packages/router/src/PageLoadingContext.tsx
  packages/router/src/Set.tsx
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/__tests__/redirect.test.tsx
  packages/router/src/__tests__/route-announcer.test.tsx
  packages/router/src/__tests__/route-validators.test.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/__tests__/setContextReuse.test.tsx
  packages/router/src/__tests__/util.test.ts
  packages/router/src/active-route-loader.tsx
  packages/router/src/index.ts
  packages/router/src/links.tsx
  packages/router/src/params.tsx
  packages/router/src/route-validators.tsx
  packages/router/src/router-context.tsx
  packages/router/src/router.tsx
  packages/router/src/splash-page.tsx
  packages/router/src/util.ts
  packages/vite/src/__tests__/viteNestedPages.test.mts
Labels: release:feature

#8548 Update routing-params.md
  docs/docs/tutorial/chapter2/routing-params.md
Labels: release:docs

#8555 chore(cli-storybook): improve types, style changes
  packages/cli-packages/storybook/build.mjs
  packages/cli-packages/storybook/package.json
  packages/cli-packages/storybook/src/commands/storybook.ts
  packages/cli-packages/storybook/src/commands/storybookHandler.ts
  yarn.lock
Labels: release:chore

#8545 Fix type `ScenarioData` JSDoc example
  packages/testing/src/api/scenario.ts
Labels: release:chore

#7575 Use defined path aliases for prerendering
  docs/docs/typescript/introduction.md
  packages/internal/src/build/api.ts
  packages/internal/src/build/babel/api.ts
  packages/internal/src/build/babel/common.ts
  packages/internal/src/build/babel/web.ts
Labels: release:fix, fixture-ok

#8544 Added verbose mode to baremetal
  packages/cli/src/commands/deploy/baremetal.js
Labels: release:fix

#8456 Get rid of 'proposal-dynamic-import'
  babel.config.js
  packages/auth-providers/auth0/setup/src/setup.ts
  packages/auth-providers/azureActiveDirectory/setup/src/setup.ts
  packages/auth-providers/clerk/setup/src/setup.ts
  packages/auth-providers/custom/setup/src/setup.ts
  packages/auth-providers/dbAuth/setup/src/setup.ts
  packages/auth-providers/firebase/setup/src/setup.ts
  packages/auth-providers/netlify/setup/src/setup.ts
  packages/auth-providers/supabase/setup/src/setup.ts
  packages/auth-providers/supertokens/setup/src/setup.ts
  packages/cli/src/commands/build.js
  packages/cli/src/commands/check.js
  packages/cli/src/commands/console.js
  packages/cli/src/commands/dataMigrate/install.js
  packages/cli/src/commands/dataMigrate/up.js
  packages/cli/src/commands/dataMigrate/upHandler.js
  packages/cli/src/commands/deploy/serverless.js
  packages/cli/src/commands/dev.js
  packages/cli/src/commands/exec.js
  packages/cli/src/commands/experimental/setupInngest.js
  packages/cli/src/commands/experimental/setupOpentelemetry.js
  packages/cli/src/commands/experimental/setupSentry.js
  packages/cli/src/commands/experimental/setupServerFile.js
  packages/cli/src/commands/experimental/studio.js
  packages/cli/src/commands/setup/cache/cache.js
  packages/cli/src/commands/setup/custom-web-index/custom-web-index.js
  packages/cli/src/commands/setup/deploy/providers/coherence.js
  packages/cli/src/commands/setup/generator/generator.js
  packages/cli/src/commands/setup/graphiql/graphiql.js
  packages/cli/src/commands/setup/graphiql/graphiqlHandler.js
  packages/cli/src/commands/setup/i18n/i18n.js
  packages/cli/src/commands/setup/tsconfig/tsconfig.js
  packages/cli/src/commands/setup/vite/vite.js
  packages/cli/src/commands/setup/webpack/webpack.js
  packages/cli/src/commands/test.js
  packages/cli/src/lib/exec.js
  packages/graphql-server/ambient.d.ts
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/tsconfig.json
  packages/prerender/src/graphql/graphql.ts
  packages/prerender/src/runPrerender.tsx
Labels: release:chore, fixture-ok

#8417 Initial support for using SDL codegen for GraphQL types
  packages/cli/src/commands/deploy/baremetal.js
  packages/internal/package.json
  packages/internal/src/generate/graphqlCodeGen.ts
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
  yarn.lock
Labels: release:feature, fixture-ok

#8533 feature: Support Auth in Fastify GraphQL Server by mimicking Lambda Events and Context
  packages/fastify/src/graphql.ts
  packages/fastify/src/lambda/index.ts
  packages/graphql-server/src/globalContext.ts
Labels: release:feature

#8577 fix(docs): Remove whitespace in `services.md`
  docs/docs/services.md
Labels: release:docs

#8529 fix(docs) test should query for postId, not comment id
  docs/docs/tutorial/chapter7/rbac.md
Labels: release:docs

#8582 Fix await import in auth setup
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:fix, fixture-ok

#8585 Fix the codegen path for the GraphQL context object
  packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
  packages/internal/src/generate/graphqlCodeGen.ts
Labels: release:fix

#8586 feat: Update the SDL types lib
  packages/internal/package.json
  yarn.lock
Labels: release:chore

#8588 Make the fastify logger respect the LOG_LEVEL value set in the env
  __fixtures__/test-project/.env.defaults
  packages/create-redwood-app/templates/js/.env.defaults
  packages/create-redwood-app/templates/ts/.env.defaults
  packages/fastify/src/config.ts
Labels: release:fix

#8590 Move fastify.logger.infos to fastify.logger.traces
  __fixtures__/test-project/api/server.config.js
  docs/docs/app-configuration-redwood-toml.md
  packages/api-server/src/fastify.ts
  packages/api-server/src/server.ts
  packages/cli/src/commands/serveHandler.js
  packages/create-redwood-app/templates/js/api/server.config.js
  packages/create-redwood-app/templates/ts/api/server.config.js
  packages/fastify/src/config.ts
Labels: release:feature-breaking

#8579 chore(rwfw): working refactor, make `project:sync` ignore more files
  tasks/framework-tools/frameworkDepsToProject.mjs
  tasks/framework-tools/frameworkFilesToProject.mjs
  tasks/framework-tools/frameworkSyncToProject.mjs
  tasks/framework-tools/lib/framework.mjs
  tasks/framework-tools/lib/project.mjs
Labels: release:chore

#8583 Only use the main lodash package
  package.json
  packages/api-server/package.json
  packages/api-server/src/plugins/lambdaLoader.ts
  packages/cli-helpers/package.json
  packages/cli-helpers/src/lib/paths.ts
  packages/cli-packages/storybook/package.json
  packages/cli/src/commands/deploy/edgio.js
  packages/cli/src/lib/index.js
  packages/cli/src/lib/merge/algorithms.js
  packages/cli/src/lib/merge/index.js
  packages/codemods/tasks/generateCodemod/generateCodemod.mjs
  packages/core/config/webpack.development.js
  packages/core/package.json
  packages/fastify/package.json
  packages/fastify/src/lambda/index.ts
  packages/graphql-server/package.json
  packages/graphql-server/src/makeMergedSchema.ts
  packages/studio/package.json
  yarn.lock
Labels: release:chore, fixture-ok

#8602 chore(CI): test webpack in tutorial e2e
  .github/workflows/ci.yml
  tasks/run-e2e
Labels: release:chore

#8605 chore(ci): use the line reporter for now
  .github/workflows/ci.yml
  package.json
  tasks/smoke-tests/basePlaywright.config.ts
  yarn.lock
Labels: release:chore

#8604 chore(CI): test webpack in the smoke tests
  .github/actions/actionsLib.mjs
  .github/actions/set-up-test-project/action.yaml
  .github/actions/set-up-test-project/setUpTestProject.mjs
  .github/workflows/ci.yml
Labels: release:chore

#8597 deprecate `setup ui windicss` (project is sunsetting)
  docs/docs/cli-commands.md
  packages/cli/src/commands/setup/deploy/__tests__/netlify.test.js
  packages/cli/src/commands/setup/deploy/helpers/index.js
  packages/cli/src/commands/setup/deploy/providers/baremetal.js
  packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
  packages/cli/src/commands/setup/deploy/providers/edgio.js
  packages/cli/src/commands/setup/deploy/providers/flightcontrol.js
  packages/cli/src/commands/setup/deploy/providers/netlify.js
  packages/cli/src/commands/setup/deploy/providers/render.js
  packages/cli/src/commands/setup/deploy/providers/serverless.js
  packages/cli/src/commands/setup/deploy/providers/vercel.js
  packages/cli/src/commands/setup/ui/libraries/windicss.js
  packages/cli/src/lib/index.js
Labels: release:fix, fixture-ok

#8592 chore(vite): Rename entry-client.tsx to entry.client
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/entry.client.tsx
  packages/cli/src/commands/setup/vite/viteHandler.js
  packages/create-redwood-app/templates/js/web/src/entry.client.jsx
  packages/create-redwood-app/templates/ts/web/src/entry.client.tsx
  packages/create-redwood-app/tests/template.test.js
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/vite/src/index.ts
Labels: release:feature-breaking

#8610 fix(vite): Do not use getPaths in vite setup handler
  packages/cli/src/commands/setup/vite/viteHandler.js
Labels: release:fix, fixture-ok

#8516 test-project-rebuild
  .github/actions/check_test_project_fixture/check_test_project_fixture.mjs
  package.json
  tasks/test-project/frameworkLinking.js
  tasks/test-project/rebuild-test-project-fixture.js
  tasks/test-project/test-project
  tasks/test-project/tui-tasks.js
  tasks/test-project/typing.js
  tasks/test-project/util.js
Labels: release:chore

#8598 remove `setup ui windicss` (project is sunsetting)
  docs/docs/cli-commands.md
  packages/cli/src/commands/setup/ui/libraries/windicss.js
Labels: release:feature-breaking, fixture-ok

#8624 Update command to rebuild test project fixture
  .github/actions/check_test_project_fixture/check_test_project_fixture.mjs
Labels: release:chore

#8612 ESLint rule: process-env-computed
  .eslintrc.js
  packages/api/src/auth/verifiers/common.ts
  packages/cli/src/commands/deploy/__tests__/baremetal.test.js
  packages/codemods/src/testUtils/matchFolderTransform.ts
  packages/core/config/__tests__/webpack.common.test.js
  packages/eslint-config/package.json
  packages/eslint-config/shared.js
  packages/eslint-plugin/build.mjs
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/__tests__/process-env-computed.test.ts
  packages/eslint-plugin/src/index.ts
  packages/eslint-plugin/src/process-env-computed.ts
  packages/eslint-plugin/tsconfig.json
  packages/project-config/src/__tests__/config.test.ts
  yarn.lock
Labels: release:feature

#8611 codemod(v6): Convert all process.env usage to dot notation
  packages/codemods/src/codemods/v6.x.x/processEnvDotNotation/README.md
  packages/codemods/src/codemods/v6.x.x/processEnvDotNotation/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v6.x.x/processEnvDotNotation/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v6.x.x/processEnvDotNotation/__tests__/processEnvDotNotation.test.ts
  packages/codemods/src/codemods/v6.x.x/processEnvDotNotation/processEnvDotNotation.ts
  packages/codemods/src/codemods/v6.x.x/processEnvDotNotation/processEnvDotNotation.yargs.ts
  packages/codemods/src/testUtils/matchInlineTransformSnapshot.ts
  packages/codemods/src/testUtils/matchTransformSnapshot.ts
  packages/codemods/tasks/generateCodemod/generateCodemod.mjs
  packages/codemods/tasks/generateCodemod/templates/code/codemod.yargs.ts.template
Labels: release:chore

#8581 chore(project-config): Cache results of common functions
  packages/project-config/src/configPath.ts
  packages/project-config/src/paths.ts
Labels: release:chore

#8568 chore(cli-plugins): make depcruise reusable
  .dependency-cruiser.mjs
  package.json
  packages/cli-packages/storybook/README.md
  packages/cli-packages/storybook/dependencyGraph.dist.svg
  packages/cli-packages/storybook/dependencyGraph.src.svg
  packages/cli-packages/storybook/src/commands/storybookHandler.ts
  packages/project-config/README.md
  packages/project-config/dependency-graph-dist.svg
  packages/project-config/dependency-graph-src.svg
  packages/project-config/dependencyGraph.dist.svg
  packages/project-config/dependencyGraph.src.svg
  packages/project-config/package.json
  tasks/generateDependencyGraph.mjs
  yarn.lock
Labels: release:chore

#8620 fix(vite): list imports before dns call
  __fixtures__/test-project/web/vite.config.ts
  packages/cli/src/commands/setup/vite/templates/vite.config.ts.template
Labels: release:fix

#8623 feat(cli): Support experimental server file from `yarn rw dev`
  packages/api-server/src/watch.ts
  packages/cli/src/commands/experimental/templates/server.ts.template
  packages/cli/src/commands/serve.js
Labels: release:feature

#8600 Update cli-commands.md
  docs/docs/cli-commands.md
Labels: release:docs

#8500 feat(apollo): add linkFactory for better customization of apollo links
  packages/web/src/apollo/index.tsx
Labels: release:feature

#8637 fix(publishing): remove tsconfig.tsbuildinfo
  tasks/release/releaseCommand.mjs
Labels: release:chore

#8638 chore(lint): Humanise eslint error for accessing process.env
  packages/eslint-plugin/src/__tests__/process-env-computed.test.ts
  packages/eslint-plugin/src/process-env-computed.ts
Labels: release:chore

#8621 chore(crwa): dedupe browserlist query
  __fixtures__/test-project/web/package.json
  babel.config.js
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
Labels: release:fix

#8607 chore(smoke-tests): make smoke tests easier to run locally
  .github/workflows/ci.yml
  package.json
  tasks/smoke-tests/auth/playwright.config.ts
  tasks/smoke-tests/auth/tests/rbacChecks.spec.ts
  tasks/smoke-tests/dev/playwright.config.ts
  tasks/smoke-tests/prerender/playwright.config.ts
  tasks/smoke-tests/prerender/tests/prerender.spec.ts
  tasks/smoke-tests/serve/playwright.config.ts
  tasks/smoke-tests/smoke-tests.mjs
  tasks/smoke-tests/storybook/playwright.config.ts
  tasks/smoke-tests/storybook/tests/storybook.spec.ts
Labels: release:chore

#8648 Remove DevFatalErrorPage import when building
  __fixtures__/test-project/api/db/migrations/20220101130000_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220102130000_create_contact/migration.sql
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  __fixtures__/test-project/web/vite.config.ts
  packages/create-redwood-app/templates/js/web/src/pages/FatalErrorPage/FatalErrorPage.jsx
  packages/create-redwood-app/templates/ts/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  packages/internal/src/__tests__/fixtures/nestedPages/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  packages/internal/src/build/babel/web.ts
  packages/internal/src/build/babelPlugins/__tests__/__fixtures__/dev-fatal-error-page/test/code.js
  packages/internal/src/build/babelPlugins/__tests__/__fixtures__/dev-fatal-error-page/test/output.js
  packages/internal/src/build/babelPlugins/__tests__/babel-plugin-redwood-remove-dev-fatal-error-page.ts
  packages/internal/src/build/babelPlugins/babel-plugin-redwood-remove-dev-fatal-error-page.ts
  packages/vite/src/__tests__/fixtures/nestedPages/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  packages/vite/src/index.ts
Labels: release:chore

#8654 regenerate test project fixture: Include @rwjs/vite in v6 specific step
  __fixtures__/test-project/web/package.json
  tasks/test-project/rebuild-test-project-fixture.js
Labels: release:chore

#8655 Remove unused global var RWJS_WEB_BUNDLER
  packages/core/config/webpack.common.js
  packages/prerender/ambient.d.ts
  packages/prerender/src/internal.ts
  packages/vite/src/index.ts
  packages/web/ambient.d.ts
  packages/web/src/global.web-auto-imports.ts
Labels: release:chore

#8657 rebuild-test-project-fixture: Print tmp dir and other output tweaks
  tasks/test-project/rebuild-test-project-fixture.js
Labels: release:chore

#8658 ChunkReferencesPlugin: Update types in webpack plugin
  packages/internal/src/webpackPlugins/ChunkReferencesPlugin.ts
Labels: release:fix

#8656 rebuild-test-project-fixture: Hardcode migration time
  __fixtures__/test-project/api/db/migrations/20220101120000_create_post_user/migration.sql
  __fixtures__/test-project/api/db/migrations/20220102120000_create_contact/migration.sql
  tasks/test-project/tui-tasks.js
Labels: release:chore

#8566 prepopulate apollo cache on prerendered pages
  packages/prerender/src/runPrerender.tsx
  packages/web/ambient.d.ts
  packages/web/src/apollo/index.tsx
  packages/web/src/components/createCell.tsx
Labels: bug/confirmed, topic/prerender, release:feature

#8661 Fix failing v5 codemod for DevFatalErrorPage
  packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/updateDevFatalErrorPage.ts
Labels: release:chore

#8639 fix(vite): Change config for mantine and chakra to use export default
  packages/cli/src/commands/setup/ui/libraries/chakra-ui.js
  packages/cli/src/commands/setup/ui/libraries/mantine.js
  packages/codemods/src/codemods/v6.x.x/updateThemeConfig/README.md
  packages/codemods/src/codemods/v6.x.x/updateThemeConfig/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v6.x.x/updateThemeConfig/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v6.x.x/updateThemeConfig/__testfixtures__/identifierTheme.input.js
  packages/codemods/src/codemods/v6.x.x/updateThemeConfig/__testfixtures__/identifierTheme.output.js
  packages/codemods/src/codemods/v6.x.x/updateThemeConfig/__tests__/updateThemeConfig.test.ts
  packages/codemods/src/codemods/v6.x.x/updateThemeConfig/updateThemeConfig.ts
  packages/codemods/src/codemods/v6.x.x/updateThemeConfig/updateThemeConfig.yargs.ts
Labels: release:fix, fixture-ok

#8596 fix(docs): Fix & make verifyOwnership consistent
  docs/docs/tutorial/chapter7/api-side-currentuser.md
Labels: release:docs

#8659 Fix typos in documentation
  docs/docs/how-to/using-a-third-party-api.md
  docs/docs/logger.md
  docs/versioned_docs/version-5.0/how-to/using-a-third-party-api.md
  docs/versioned_docs/version-5.0/logger.md
Labels: release:docs

#8687 chore(ci): Fix playwright timeout
  tasks/smoke-tests/prerender/tests/prerender.spec.ts
Labels: release:chore

#8688 chore(rwfw): Add force optimise to vite.config when running project:sync
  tasks/framework-tools/frameworkSyncToProject.mjs
  tasks/framework-tools/lib/project.mjs
  tasks/framework-tools/lib/viteConfig.mjs
Labels: release:chore

#8642 fix(clerk): add alternative decoder
  docs/docs/auth/clerk.md
  packages/auth-providers/clerk/api/src/__tests__/clerk.test.ts
  packages/auth-providers/clerk/api/src/decoder.ts
  packages/auth-providers/clerk/api/src/index.ts
  packages/auth-providers/clerk/setup/src/setupHandler.ts
  packages/auth-providers/clerk/setup/src/templates/api/lib/auth.ts.template
Labels: release:fix

#8699 chore(cli): Rename command cache file
  packages/cli/src/plugin.js
Labels: release:chore

#8721 Clerk decoder: Fix code format
  packages/auth-providers/clerk/api/src/decoder.ts
Labels: release:chore

#8569 fix(fastify): Ensure global context is unique and scoped to an individual request lifetime
  packages/fastify/src/api.ts
  packages/fastify/src/graphql.ts
  packages/graphql-server/src/functions/__tests__/authDecoders.test.ts
  packages/graphql-server/src/functions/__tests__/globalContext.test.ts
  packages/graphql-server/src/functions/__tests__/graphql.test.ts
  packages/graphql-server/src/functions/__tests__/useRequireAuth.test.ts
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/functions/useRequireAuth.ts
  packages/graphql-server/src/globalContext.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodGlobalContextSetter.test.ts
  packages/testing/src/api/directive.ts
Labels: release:fix

#8732 fix: Insert const in for...of loop
  __fixtures__/test-project/scripts/seed.ts
  packages/create-redwood-app/templates/js/scripts/seed.js
  packages/create-redwood-app/templates/ts/scripts/seed.ts
Labels: release:fix

#8729 chore(vite) Remove invalid comment
  packages/internal/src/build/web.ts
Labels: release:chore

#8731 Use vite unless bundler === webpack
  packages/cli/src/commands/__tests__/dev.test.js
  packages/cli/src/commands/buildHandler.js
  packages/cli/src/commands/devHandler.js
  packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts
  packages/prerender/src/runPrerender.tsx
Labels: release:fix

#8564 codemod(svgs): Convert imported SVGs to react components
  packages/codemods/package.json
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/README.md
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/input/mySvgs/Logo.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/input/mySvgs/kitten1.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/input/nested/kitten.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/output/mySvgs/Kitten1SVG.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/output/mySvgs/Logo.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/output/mySvgs/LogoSVG.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/output/mySvgs/kitten1.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/complex/output/nested/kitten.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/input/AsRenderProp.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/input/Simple.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/input/bazinga.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/output/AsRenderProp.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/output/BazingaSVG.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/output/Simple.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/simple/output/bazinga.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/input/redwood.toml
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/input/web/src/components/kitten.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/input/web/src/mySvgs/Logo.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/input/web/src/mySvgs/kitten1-with-dashes.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/output/web/src/components/kitten.tsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/output/web/src/mySvgs/Kitten1WithDashesSVG.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/output/web/src/mySvgs/Logo.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/output/web/src/mySvgs/LogoSVG.jsx
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__testfixtures__/srcAlias/output/web/src/mySvgs/kitten1-with-dashes.svg
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__tests__/replaceComponentSvgs.test.ts
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/replaceComponentSvgs.ts
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/replaceComponentSvgs.yargs.ts
  packages/codemods/src/lib/runTransform.ts
  packages/codemods/src/testUtils/matchFolderTransform.ts
  yarn.lock
Labels: release:chore

#8707 docs(vite): Remove references to webpack, and more docs on SVGs and fonts
  docs/docs/app-configuration-redwood-toml.md
  docs/docs/assets-and-files.md
  docs/docs/cli-commands.md
  docs/docs/environment-variables.md
  docs/docs/how-to/custom-function.md
  docs/docs/how-to/file-uploads.md
  docs/docs/router.md
  docs/docs/tutorial/chapter1/second-page.md
  docs/docs/vite-configuration.md
  docs/docs/webpack-configuration.md
  docs/sidebars.js
  packages/create-redwood-app/templates/js/web/public/README.md
  packages/create-redwood-app/templates/ts/web/public/README.md
Labels: release:docs, fixture-ok

#8713 v6 codemod: FatalErrorPage
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/README.md
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/__testfixtures__/js/input/web/src/pages/FatalErrorPage/FatalErrorPage.js
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/__testfixtures__/js/output/web/src/pages/FatalErrorPage/FatalErrorPage.js
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/__testfixtures__/jsx/input/web/src/pages/FatalErrorPage/FatalErrorPage.jsx
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/__testfixtures__/jsx/output/web/src/pages/FatalErrorPage/FatalErrorPage.jsx
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/__testfixtures__/tsx/input/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/__testfixtures__/tsx/output/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/__tests__/updateDevFatalErrorPage.test.ts
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/updateDevFatalErrorPage.ts
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/updateDevFatalErrorPage.yargs.ts
Labels: release:chore

#8740 Tweak vite setup output
  packages/cli/src/commands/setup/vite/viteHandler.js
Labels: release:chore, fixture-ok

#8744 DX: Tweak comments in redwood.toml
  __fixtures__/test-project/redwood.toml
  packages/create-redwood-app/templates/js/redwood.toml
  packages/create-redwood-app/templates/ts/redwood.toml
Labels: release:fix

#8745 Setup vite: No longer experimental
  packages/cli/src/commands/setup/vite/vite.js
Labels: release:fix, fixture-ok

#8723 fix(cli): Add experimental notice when `rw dev` uses server file
  packages/api-server/src/watch.ts
Labels: release:fix

#8742 chore: Remind to setup auth in server file GraphQL configuration
  packages/cli/src/commands/experimental/templates/server.ts.template
Labels: release:experiment

#8750 chore(vite): Remove unused vite-plugin-commonjs
  packages/vite/package.json
  packages/vite/tsconfig.json
  packages/vite/vite-plugin-commonjs.d.ts
  yarn.lock
Labels: release:chore

#8305 feat(firebase-admin): upgrade to v11
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/setup/src/setupHandler.ts
  yarn.lock
Labels: release:feature-breaking

#8622 OAuth cookbook
  docs/docs/how-to/oauth.md
Labels: release:docs

#8755 Update test-project after Vite doc changes
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/public/README.md
Labels: release:chore

#8757 Added Amy to README
  README.md
Labels: release:docs

#8758 Updates tutorial to use .jsx instead of .js for JSX files
  docs/docs/tutorial/chapter1/file-structure.md
  docs/docs/tutorial/chapter1/first-page.md
  docs/docs/tutorial/chapter1/layouts.md
  docs/docs/tutorial/chapter1/second-page.md
  docs/docs/tutorial/chapter2/cells.md
  docs/docs/tutorial/chapter2/getting-dynamic.md
  docs/docs/tutorial/chapter2/routing-params.md
  docs/docs/tutorial/chapter3/forms.md
  docs/docs/tutorial/chapter3/saving-data.md
  docs/docs/tutorial/chapter4/authentication.md
  docs/docs/tutorial/chapter5/first-story.md
  docs/docs/tutorial/chapter5/first-test.md
  docs/docs/tutorial/chapter5/storybook.md
  docs/docs/tutorial/chapter6/comment-form.md
  docs/docs/tutorial/chapter6/comments-schema.md
  docs/docs/tutorial/chapter6/multiple-comments.md
  docs/docs/tutorial/chapter6/the-redwood-way.md
  docs/docs/tutorial/chapter7/api-side-currentuser.md
  docs/docs/tutorial/chapter7/rbac.md
Labels: release:docs

#8705 chore(vite): Hide API proxy error on start
  packages/vite/src/index.ts
Labels: release:fix

#8754 internal(rwfw) Add bins as scripts
  packages/core/package.json
  packages/core/src/bins/rimraf.ts
  tasks/framework-tools/frameworkFilesToProject.mjs
  tasks/framework-tools/lib/project.mjs
  yarn.lock
Labels: release:chore

#8756 chore(crwa): Fix blank UID on project creation
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:chore

#8762 chore(cli): Update checker background process logging improvement
  packages/cli/src/lib/background.js
  packages/cli/src/lib/updateCheck.js
Labels: release:chore

#8761 chore(apollo): make previous Apollo Link change breaking
  packages/web/src/apollo/index.tsx
Labels: release:feature-breaking

#8591 Lets the watcher CLI show some logs in debug/trace and others all the time (and adds duration)
  packages/api/src/logger/index.ts
  packages/internal/src/cliLogger.ts
  packages/internal/src/generate/watch.ts
Labels: release:feature

#8765 chore(v6): temporarily revert host-related changes
  docs/docs/cli-commands.md
  packages/api-server/src/cliHandlers.ts
  packages/api-server/src/server.ts
  packages/api-server/src/watch.ts
  packages/cli/src/commands/__tests__/dev.test.js
  packages/cli/src/commands/__tests__/serve.test.js
  packages/cli/src/commands/devHandler.js
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveHandler.js
  packages/core/config/webpack.development.js
Labels: release:chore

#8770 fix(cli): Revert change to error display for `rw test`
  packages/cli/src/commands/testHandler.js
Labels: release:fix

#8772 fix(v6): specify that the custom web index webpack only
  docs/docs/cli-commands.md
  docs/docs/custom-web-index.md
  packages/cli/src/commands/setup/custom-web-index/custom-web-index-handler.js
  packages/cli/src/commands/setup/custom-web-index/custom-web-index.js
Labels: release:fix, fixture-ok

#8764 React Streaming and SSR feature flag
  packages/cli/src/commands/experimental/setupStreamingSsr.js
  packages/cli/src/commands/experimental/setupStreamingSsrHandler.js
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
  packages/vite/src/index.ts
  packages/web/ambient.d.ts
  packages/web/src/config.ts
Labels: release:feature

#8774 eslint rule: unsupported-route-components
  packages/eslint-config/index.js
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/__tests__/unsupported-route-components.test.ts
  packages/eslint-plugin/src/index.ts
  packages/eslint-plugin/src/unsupported-route-components.ts
  yarn.lock
Labels: release:feature

#8448 fix(type defs): log type-def generation errors at the end
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/directive/directive.js
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/lib/test.js
  packages/internal/src/__tests__/graphqlCodeGen.test.ts
  packages/internal/src/__tests__/graphqlSchema.test.ts
  packages/internal/src/generate/generate.ts
  packages/internal/src/generate/graphqlCodeGen.ts
  packages/internal/src/generate/graphqlSchema.ts
  packages/internal/src/generate/typeDefinitions.ts
  packages/internal/src/generate/watch.ts
Labels: release:fix, fixture-ok

#8599 eslint rule to add types to service functions
  packages/eslint-config/index.js
  packages/eslint-plugin/src/__tests__/service-type-annotations.test.ts
  packages/eslint-plugin/src/index.ts
  packages/eslint-plugin/src/service-type-annotations.ts
Labels: release:feature

#8776 Make unsupported route components rule error for v6
  packages/eslint-plugin/src/unsupported-route-components.ts
Labels: release:feature

#8753 chore: Update graphql-server to Yoga v4 and latest subscriptions
  packages/codemods/package.json
  packages/core/package.json
  packages/forms/package.json
  packages/graphql-server/package.json
  packages/graphql-server/src/plugins/__tests__/useArmor.test.ts
  packages/graphql-server/src/plugins/__tests__/useRedwoodError.test.ts
  packages/graphql-server/src/plugins/useArmor.ts
  packages/internal/package.json
  packages/prerender/package.json
  packages/structure/package.json
  packages/studio/frontend/package.json
  packages/studio/package.json
  packages/web/package.json
  tasks/run-e2e
  yarn.lock
Labels: release:chore

#8779 Change router rule to error in ESLint config
  packages/eslint-config/index.js
Labels: release:fix

#8766 chore: RedwoodJS GraphQL subscription templates now use Dynamic Topic IDs
  packages/cli/src/commands/experimental/templates/realtime.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/blank/blank.service.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/blank/blank.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/newMessage/newMessage.ts.template
  packages/cli/src/commands/experimental/templates/subscriptions/newMessage/rooms.ts.template
Labels: release:feature

#8561 Beginnings of Server Rendering & Streaming
  packages/cli/src/commands/buildHandler.js
  packages/cli/src/commands/serve.js
  packages/core/package.json
  packages/core/src/bins/rw-dev-fe.ts
  packages/core/src/bins/rw-serve-api.ts
  packages/core/src/bins/rw-serve-fe.ts
  packages/internal/package.json
  packages/internal/src/build/babel/api.ts
  packages/internal/src/build/babel/common.ts
  packages/internal/src/build/babel/web.ts
  packages/internal/src/files.ts
  packages/internal/src/generate/templates/api-globImports.d.ts.template
  packages/internal/src/routes.ts
  packages/internal/tsconfig.json
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/structure/src/model/RWRoute.ts
  packages/vite/ambient.d.ts
  packages/vite/inject/reactRefresh.js
  packages/vite/package.json
  packages/vite/src/buildFeServer.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/index.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/triggerRouteHooks.ts
  packages/vite/src/types.ts
  packages/vite/src/utils.ts
  packages/vite/tsconfig.json
  packages/web/src/apollo/index.tsx
  packages/web/src/components/RedwoodProvider.tsx
  packages/web/src/components/htmlTags.tsx
  packages/web/src/index.ts
  packages/web/src/routeHooks.types.ts
  packages/web/src/serverContext.tsx
  yarn.lock
Labels: release:feature

#8794 Only enable new eslint rule for the Routes file
  packages/eslint-config/index.js
Labels: release:fix

#8796 vite utils.ts: fix source format
  packages/vite/src/utils.ts
Labels: release:chore

#8782 fix(graphql-server): Conditionally enable OTel plugin and OTel plugin updates
  packages/cli/src/commands/experimental/setupOpentelemetryHandler.js
  packages/graphql-server/src/createGraphQLYoga.ts
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/makeMergedSchema.ts
  packages/graphql-server/src/plugins/useRedwoodOpenTelemetry.ts
  packages/graphql-server/src/types.ts
Labels: release:fix

#8797 eslint unsupported-route-components: Minor tweaks
  packages/eslint-plugin/src/__tests__/unsupported-route-components.test.ts
  packages/eslint-plugin/src/unsupported-route-components.ts
Labels: release:chore

#8795 buildHandler: Give execa cwd for yarn to find the rw-vite-build binary
  packages/cli/src/commands/buildHandler.js
Labels: release:fix
