Repository redwoodjs/graphql, pull requests merged in 2023-09, with the labels that each got.

#9113 fix(meta): Remove duplicated title and meta attributes (possible edge cases)
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:fix

#9115 Streaming fe server: bind to 0.0.0.0 in prod
  packages/vite/src/runFeServer.ts
Labels: release:fix

#9116 fix(types): wrong type path on server.config.js
  packages/create-redwood-app/templates/js/api/server.config.js
  packages/create-redwood-app/templates/ts/api/server.config.js
Labels: release:fix, fixture-ok

#9104 fix: Refactor logic to enable/allow disable/not allow GraphiQL and Introspection Configuration in Dev vs Prod
  packages/graphql-server/src/__tests__/__snapshots__/graphiql.test.ts.snap
  packages/graphql-server/src/__tests__/graphiql.test.ts
  packages/graphql-server/src/__tests__/introspection.test.ts
  packages/graphql-server/src/createGraphQLYoga.ts
  packages/graphql-server/src/graphiql.ts
  packages/graphql-server/src/introspection.ts
  packages/graphql-server/src/types.ts
Labels: bug/confirmed, release:fix

#9121 fix(babel-config): read TS config files using TS parser functions
  packages/babel-config/package.json
  packages/babel-config/src/__tests__/common.test.ts
  packages/babel-config/src/common.ts
Labels: release:fix

#9122 fix(render): redirect to 200.html for prerender
  packages/cli/src/commands/setup/deploy/templates/render.js
Labels: release:fix, fixture-ok

#9120 fix(studio): Quick fix for trace rendering bug
  packages/studio/web/src/Pages/Explore/TraceList.tsx
Labels: release:fix

#9065 fix(jest): Include RWJS_DEBUG_ENV in jest web env
  packages/testing/config/jest/web/jest-preset.js
  packages/web/src/components/DevFatalErrorPage.tsx
Labels: release:fix

#9132 RSC: Don't set the react-server condition for client builds
  packages/vite/src/buildRscFeServer.ts
Labels: release:fix

#9133 Support jsx/tsx on the api side (for mail templates, ai-jsx, etc)
  __fixtures__/test-project/api/server.config.js
  __fixtures__/test-project/api/tsconfig.json
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/components/Author/Author.stories.tsx
  __fixtures__/test-project/web/src/pages/BlogPostPage/BlogPostPage.stories.tsx
  __fixtures__/test-project/web/src/pages/WaterfallPage/WaterfallPage.stories.tsx
  package.json
  packages/babel-config/package.json
  packages/babel-config/src/__tests__/api.test.ts
  packages/babel-config/src/api.ts
  packages/create-redwood-app/templates/js/api/jsconfig.json
  packages/create-redwood-app/templates/ts/api/tsconfig.json
  packages/internal/package.json
  yarn.lock
Labels: release:feature-breaking

#9134 Streaming SSR: Fix RWJS_EXP_SSR_GRAPHQL_ENDPOINT logic
  packages/vite/src/streaming/registerGlobals.ts
Labels: release:fix

#9119 dbAuth: Catch fetch failure in getToken
  packages/auth-providers/dbAuth/web/src/dbAuth.ts
Labels: release:fix

#9138 feat(realtime): Expose store and pubsub for easier access
  packages/realtime/src/graphql/index.ts
  packages/realtime/src/graphql/plugins/useRedwoodRealtime.ts
  packages/realtime/src/index.ts
Labels: release:feature

#8578 chore(tasks): Benchmark tests
  package.json
  tasks/benchmark/README.md
  tasks/benchmark/run-benchmarks.mts
  tasks/benchmark/setups/context_magic_number/setup.mts
  tasks/benchmark/setups/context_magic_number/templates/benchmark.sdl.ts
  tasks/benchmark/setups/context_magic_number/templates/benchmarks.ts
  tasks/benchmark/setups/context_magic_number/templates/func.ts
  tasks/benchmark/setups/scalable_graphql_schema/setup.mts
  tasks/benchmark/setups/scalable_graphql_schema/templates/definition.sdl.ts
  tasks/benchmark/setups/scalable_graphql_schema/templates/implementation.ts
  tasks/benchmark/setups/scalable_graphql_schema/templates/relation.sdl.ts
  tasks/benchmark/tests/context_functions.js
  tasks/benchmark/tests/context_graphql.js
  tasks/benchmark/tests/scalable_graphql_schema.js
  tasks/benchmark/util/util.mts
  yarn.lock
Labels: release:chore

#9142 Streaming: meta charSet=utf-8
  packages/cli/src/commands/experimental/templates/streamingSsr/Document.tsx.template
Labels: release:fix

#9154 RSC: Make code and execution easier to follow. Improve error handling.
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/client.ts
  packages/vite/src/lib/StatusError.ts
  packages/vite/src/rscBuild.ts
  packages/vite/src/waku-lib/rsc-handler-worker.ts
  packages/vite/src/waku-lib/rsc-utils.ts
  packages/vite/src/waku-lib/vite-plugin-rsc.ts
Labels: release:chore

#9155 RSC: RSF aka Server Actions
  packages/vite/src/waku-lib/build-server.ts
Labels: release:feature

#9157 RSC: Decode RSF args from request
  packages/vite/package.json
  packages/vite/src/lib/StatusError.ts
  packages/vite/src/runRscFeServer.ts
  yarn.lock
Labels: release:feature

#9158 fix(cli): import redwoodjs/record correctly in `yarn rw g model`
  packages/cli/src/commands/generate/model/model.js
Labels: release:fix, fixture-ok

#9149 Update `NODE_VERSION` for Render to 18 (close #8508)
  packages/cli/src/commands/setup/deploy/templates/render.js
Labels: release:fix, fixture-ok

#9151 Update what-is-redwood.md
  docs/docs/tutorial/chapter0/what-is-redwood.md
Labels: release:docs

#9166 chore(ci): undo changes to test project stories
  __fixtures__/test-project/web/src/components/Author/Author.stories.tsx
  __fixtures__/test-project/web/src/pages/BlogPostPage/BlogPostPage.stories.tsx
  __fixtures__/test-project/web/src/pages/WaterfallPage/WaterfallPage.stories.tsx
  package.json
  packages/auth/package.json
  packages/testing/package.json
  yarn.lock
Labels: release:chore

#9164 RSC: Switch to React experimental
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/studio/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore

#9169 fix(cli): Prevent stale command cache defaults
  packages/cli/src/plugin.js
Labels: release:fix

#9173 Allow resuming rebuild-test-project-fixture at a specific sub step
  tasks/test-project/rebuild-test-project-fixture.js
  tasks/test-project/typing.js
  tasks/test-project/util.js
Labels: release:chore

#8920 feat(cli): Setup command which uses an npm package
  packages/cli-helpers/src/index.ts
  packages/cli-helpers/src/lib/__tests__/version.test.ts
  packages/cli-helpers/src/lib/version.ts
  packages/cli/src/commands/setup/package/__tests__/packageHandler.test.js
  packages/cli/src/commands/setup/package/package.js
  packages/cli/src/commands/setup/package/packageHandler.js
Labels: release:feature, fixture-ok

#9174 fix(babel): use caret to specify some package versions
  constraints.pro
  package.json
  packages/api-server/package.json
  packages/api/package.json
  packages/auth-providers/auth0/api/package.json
  packages/auth-providers/auth0/setup/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/setup/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/setup/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/custom/setup/package.json
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/setup/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/netlify/setup/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/setup/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/api/package.json
  packages/auth-providers/supertokens/setup/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/babel-config/package.json
  packages/cli-helpers/package.json
  packages/cli/package.json
  packages/codemods/package.json
  packages/core/package.json
  packages/create-redwood-app/package.json
  packages/eslint-config/package.json
  packages/forms/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/prerender/package.json
  packages/record/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/studio/package.json
  packages/telemetry/package.json
  packages/testing/package.json
  packages/web/package.json
  yarn.lock
Labels: release:fix, fixture-ok

#9171 fix(cli): Fix plugin loading with rewrite of loading logic
  packages/cli-helpers/src/lib/__tests__/version.test.ts
  packages/cli-helpers/src/lib/version.ts
  packages/cli/src/__tests__/__snapshots__/plugin.test.js.snap
  packages/cli/src/__tests__/plugin.test.js
  packages/cli/src/lib/plugin.js
  packages/cli/src/plugin.js
  packages/project-config/src/config.ts
Labels: release:fix, fixture-ok

#9176 Fixed broken link (404) in the cell tutorial
  docs/docs/cells.md
Labels: release:docs

#8917 Notes SDL codegen in docs
  docs/docs/typescript/generated-types.md
Labels: release:docs

#9188 fix(cli): Remove extraneous console.log from debugging
  packages/cli/src/commands/setup/package/packageHandler.js
Labels: release:fix

#9191 RSC: Support 'use client' in 3pp packages
  packages/vite/src/waku-lib/build-server.ts
  packages/vite/src/waku-lib/builder.ts
  packages/vite/src/waku-lib/rsc-handler-worker.ts
Labels: release:feature

#9192 RSC: Patch vite when running setup command
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/templates/rsc/vite-npm-4.4.9-e845c1bbf8.patch.template
Labels: release:fix

#9196 RSC: Use react/experimental types
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/vite/ambient.d.ts
  packages/vite/src/fully-react/assets.tsx
Labels: release:fix

#9197 RSC: Check if index.html has already been updated during setup
  packages/cli/src/commands/experimental/setupRscHandler.js
Labels: release:feature

#9193 smoke-tests: Fix red squiggles (type import, * as)
  tasks/smoke-tests/auth/tests/rbacChecks.spec.ts
  tasks/smoke-tests/common.ts
  tasks/smoke-tests/prerender/tests/prerender.spec.ts
  tasks/smoke-tests/storybook/tests/storybook.spec.ts
Labels: release:chore

#9189 Update services.md
  docs/docs/services.md
Labels: release:docs

#9199 fix(cli): run dedupe after installing a redwood plugin
  packages/cli/src/lib/packages.js
Labels: release:fix, fixture-ok

#9200 chore: bump babel packages' versions
  package.json
  packages/api-server/package.json
  packages/api/package.json
  packages/auth-providers/auth0/api/package.json
  packages/auth-providers/auth0/setup/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/setup/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/setup/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/custom/setup/package.json
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/setup/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/netlify/setup/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/setup/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/api/package.json
  packages/auth-providers/supertokens/setup/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/babel-config/package.json
  packages/cli-helpers/package.json
  packages/cli/package.json
  packages/codemods/package.json
  packages/create-redwood-app/package.json
  packages/eslint-config/package.json
  packages/forms/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/prerender/package.json
  packages/record/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/studio/package.json
  packages/telemetry/package.json
  packages/testing/package.json
  packages/web/package.json
  yarn.lock
Labels: release:fix, fixture-ok

#9204 Fix infinite loops on nested private routes with roles
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/router.tsx
  packages/router/src/util.ts
Labels: release:fix

#9206 chore(crwa): remove React `prop-types` package
  __fixtures__/test-project/web/package.json
  babel.config.js
  packages/babel-config/src/web.ts
  packages/core/config/webpack.common.js
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/eslint-config/shared.js
  packages/web/package.json
  packages/web/src/global.web-auto-imports.ts
  yarn.lock
Labels: release:feature-breaking

#9215 docs(cli): Setup from npm package
  docs/docs/cli-commands.md
Labels: release:docs

#9216 Fix typos, removing erroneous apostrophes from personal possessive pronouns
  docs/docs/cli-commands.md
Labels: release:docs

#9233 RSC: Handle Windows paths in clientEntries
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/waku-lib/rsc-handler-worker.ts
Labels: release:fix

#9194 RSC: Smoke test
  .github/actions/actionsLib.mjs
  .github/actions/rsc_related_changes/action.yml
  .github/actions/rsc_related_changes/package.json
  .github/actions/rsc_related_changes/rsc_related_changes.mjs
  .github/actions/rsc_related_changes/yarn.lock
  .github/actions/set-up-rsc-project/README.md
  .github/actions/set-up-rsc-project/action.yaml
  .github/actions/set-up-rsc-project/jsconfig.json
  .github/actions/set-up-rsc-project/package.json
  .github/actions/set-up-rsc-project/setUpRscProject.mjs
  .github/actions/set-up-rsc-project/setUpRscProjectGitHub.mjs
  .github/actions/set-up-rsc-project/setUpRscProjectLocally.mjs
  .github/workflows/ci.yml
  packages/vite/src/waku-lib/rsc-handler-worker.ts
  tasks/smoke-tests/basePlaywright.config.ts
  tasks/smoke-tests/rsc/playwright.config.ts
  tasks/smoke-tests/rsc/tests/rsc.spec.ts
Labels: release:chore

#9239 graphql possibleTypes: Fix formatting
  __fixtures__/test-project/web/package.json
  packages/create-redwood-app/templates/js/web/src/graphql/possibleTypes.js
  packages/create-redwood-app/templates/ts/web/src/graphql/possibleTypes.ts
Labels: release:chore
