Repository redwoodjs/graphql, pull requests merged in 2024-09, with the labels that each got.

#11406 feat(rsc): Initial support for RSA rerender
  .changesets/11406.md
  packages/router/src/rsc/ClientRouter.tsx
  packages/router/src/rsc/RscFetcher.tsx
Labels: release:feature, fixture-ok, experimental

#11407 chore(rsc): Rename rscFetch to rscFetchRoutes and hardcode the rscId
  packages/router/src/rsc/ClientRouter.tsx
  packages/router/src/rsc/RscFetcher.tsx
Labels: release:chore, fixture-ok

#11408 chore(test-project): Update postcss to 8.4.42
  __fixtures__/test-project/web/package.json
Labels: release:chore

#11409 chore(rsc): Refactor: Rename RscFetcher -> RscRoutes
  packages/router/src/rsc/ClientRouter.tsx
  packages/router/src/rsc/RscRoutes.tsx
Labels: release:chore, fixture-ok

#11413 chore: Rebuild fixture
  __fixtures__/test-project/web/package.json
Labels: release:chore, changesets-ok

#11412 feat(uploads): Increase default fastify body limit to 100MB
  .changesets/11412.md
  packages/api-server/src/createServerHelpers.ts
Labels: release:feature

#11414 fix(cli-helpers): Don't add spaces around `=` for env vars
  .changesets/11414.md
  packages/cli-helpers/src/lib/__tests__/__snapshots__/project.test.ts.snap
  packages/cli-helpers/src/lib/project.ts
Labels: release:fix

#11411 chore(uploads): Reorganise, change uploads package to storage
  .changesets/11411.md
  .eslintrc.js
  packages/storage/.gitignore
  packages/storage/README.md
  packages/storage/attw.ts
  packages/storage/build.mts
  packages/storage/package.json
  packages/storage/prisma-override.d.ts
  packages/storage/src/UrlSigner.ts
  packages/storage/src/__tests__/createSavers.test.ts
  packages/storage/src/__tests__/queryExtensions.test.ts
  packages/storage/src/__tests__/resultExtensions.test.ts
  packages/storage/src/__tests__/signedUrls.test.ts
  packages/storage/src/__tests__/unit-test-schema.prisma
  packages/storage/src/adapters/BaseStorageAdapter.ts
  packages/storage/src/adapters/FileSystemStorage/FileSystemStorage.ts
  packages/storage/src/adapters/FileSystemStorage/FileSystemsStorage.test.ts
  packages/storage/src/adapters/MemoryStorage/MemoryStorage.test.ts
  packages/storage/src/adapters/MemoryStorage/MemoryStorage.ts
  packages/storage/src/createSavers.ts
  packages/storage/src/fileToDataUri.ts
  packages/storage/src/index.ts
  packages/storage/src/prismaExtension.ts
  packages/storage/tsconfig.json
  packages/storage/tsconfig.types-cjs.json
  packages/storage/vitest.config.mts
  packages/storage/vitest.setup.mts
  packages/uploads/src/index.ts
  yarn.lock
Labels: release:chore

#11375 fix: Use sse link with `@live` directive
  .changesets/11375.md
  packages/web/src/apollo/index.tsx
  packages/web/src/apollo/sseLink.ts
Labels: release:fix

#11415 chore(rsc): Refactor: Clean up RSA babel transform
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:chore

#11420 RSC: Add blog pages to kitchen sink test project
  __fixtures__/test-project-rsc-kitchen-sink/api/db/blog/butterflies.md
  __fixtures__/test-project-rsc-kitchen-sink/api/db/blog/hello-world.md
  __fixtures__/test-project-rsc-kitchen-sink/web/src/Routes.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/BlogPostCell/BlogPostCell.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/BlogPostsNavCell/BlogPostsNavCell.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/EditBlogPostCell/EditBlogPostCell.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/BlogLayout/BlogLayout.css
  __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/BlogLayout/BlogLayout.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/NavigationLayout/NavigationLayout.css
  __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/NavigationLayout/NavigationLayout.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/lib/actions.ts
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/BlogPage/BlogPage.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/BlogPostPage/BlogPostPage.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/EditBlogPostPage/EditBlogPostPage.css
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/EditBlogPostPage/EditBlogPostPage.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/NewBlogPostPage/NewBlogPostPage.css
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/NewBlogPostPage/NewBlogPostPage.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/NewBlogPostPage/actions.ts
Labels: release:chore

#11421 chore(rsa): Add missing routes to test project blog
  __fixtures__/test-project-rsc-kitchen-sink/web/src/Routes.tsx
Labels: release:chore

#11424 chore(test-project): Update to postcss 8.4.45
  __fixtures__/test-project/web/package.json
Labels: release:chore

#11417 fix(rsa): Use dist filenames when registering server references
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-server.function-scope.test.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-server.test.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscWorker.ts
Labels: release:fix, fixture-ok, changesets-ok

#11425 fix(rsc): Don't run the Vite dev server in production
  packages/vite/src/rsc/rscWorker.ts
Labels: release:fix, changesets-ok, experimental

#11429 chore(publishing): Fix canary publishing for next branch
  .github/scripts/publish_canary.sh
Labels: release:chore, changesets-ok

#11430 chore(rsc): Simplify worker by not using vite config
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
  packages/vite/src/rsc/rscWorker.ts
Labels: release:chore, changesets-ok, experimental

#11431 chore(rsc): Remove unused methods in the worker
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
Labels: release:chore, fixture-ok

#11446 Updates SDL codegen to handle prettier 3 correctly
  packages/internal/package.json
  packages/internal/src/generate/graphqlCodeGen.ts
  yarn.lock
Labels: release:fix, changesets-ok

#11447 fix(resolutions): Remove rehackt resolution
  .changesets/11447.md
  __fixtures__/rsc-caching/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
Labels: release:fix

#11416 chore(storage): Add type tests & extra tests for savers and result extension
  packages/framework-tools/src/buildDefaults.ts
  packages/storage/package.json
  packages/storage/src/__tests__/createSavers.test.ts
  packages/storage/src/__tests__/queryExtensions.test.ts
  packages/storage/src/__tests__/resultExtensions.test.ts
  packages/storage/src/__typetests__/types.test.ts
  packages/storage/src/adapters/FileSystemStorage/FileSystemStorage.test.ts
  packages/storage/src/adapters/MemoryStorage/MemoryStorage.test.ts
  packages/storage/src/index.ts
  packages/storage/src/prismaExtension.ts
  packages/storage/tsconfig.build.json
  packages/storage/tsconfig.types-cjs.json
  packages/storage/vitest.config.mts
  yarn.lock
Labels: release:chore, fixture-ok, changesets-ok

#11398 docs(uploads): Add upload docs
  docs/docs/docker.md
  docs/docs/server-file.md
  docs/docs/uploads.md
  docs/sidebars.js
  docs/static/img/uploads/uploads-flow.png
Labels: release:docs, changesets-ok

#11423 feat(uploads): Add setup command
  docs/docs/uploads.md
  packages/cli/src/commands/setup/uploads/__codemod_tests__/dbCodemod.test.ts
  packages/cli/src/commands/setup/uploads/__testfixtures__/defaultDb.input.ts
  packages/cli/src/commands/setup/uploads/__testfixtures__/defaultDb.output.ts
  packages/cli/src/commands/setup/uploads/__testfixtures__/oldFormat.input.ts
  packages/cli/src/commands/setup/uploads/dbCodemod.ts
  packages/cli/src/commands/setup/uploads/templates/signedUrl.ts.template
  packages/cli/src/commands/setup/uploads/templates/srcLibUploads.ts.template
  packages/cli/src/commands/setup/uploads/uploads.js
  packages/cli/src/commands/setup/uploads/uploadsHandler.js
Labels: release:feature, fixture-ok, changesets-ok

#11451 chore(rsc): Random changes, mostly to comments etc, in prep for removing the worker
  packages/router/src/rsc/ServerRouter.tsx
  packages/vite/modules.d.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/utils.ts
Labels: release:chore, fixture-ok

#11452 chore(rsc): Refactor: Split rscWorker into worker and renderer
  packages/vite/src/rsc/rscRenderer.ts
  packages/vite/src/rsc/rscStudioHandlers.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
Labels: release:chore, fixture-ok

#11454 chore: fix ending newline in package.json
  packages/storage/package.json
Labels: release:chore, changesets-ok

#11453 chore(rsc): Fix executeRsa comments
  packages/vite/src/rsc/rscRenderer.ts
Labels: release:chore, fixture-ok, changesets-ok, experimental

#11456 chore(ci): Revert scorecard related action bump
  .github/workflows/scorecard.yml
Labels: release:chore, changesets-ok

#11455 Correct Note Admonition
  docs/docs/uploads.md
Labels: release:docs, changesets-ok

#11458 fix(linting): Re-enable babel presets during linting of javascript projects
  .changesets/11458.md
  packages/babel-config/src/web.ts
  packages/eslint-config/index.js
  packages/project-config/src/paths.ts
Labels: release:fix

#11459 fix(jobs): Make deleteSuccessfulJobs configurable
  .changesets/11459.md
  packages/jobs/src/core/Executor.ts
  packages/jobs/src/core/__tests__/Executor.test.ts
Labels: release:fix

#11460 chore(ci): fix type tests running in ci
  package.json
Labels: release:chore, changesets-ok

#11449 chore(rsc): Remove Node RSC worker
  packages/vite/src/rsc/rscRenderer.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscStudioHandlers.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/utils.ts
Labels: release:chore, changesets-ok, experimental

#11461 fix(cli): explicitly set the version so `--version` works
  packages/cli/src/index.js
Labels: release:fix, changesets-ok

#11462 chore(ci): Fix snapshots after CLI update
  tasks/server-tests/bothServer.test.mts
Labels: release:chore, changesets-ok

#11466 chore(auth-providers): switch firebase-web to vitest
  packages/auth-providers/firebase/web/jest.config.js
  packages/auth-providers/firebase/web/jest.setup.js
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/firebase/web/resolver.js
  packages/auth-providers/firebase/web/src/__tests__/firebase.test.tsx
  packages/auth-providers/firebase/web/vitest.config.mts
  yarn.lock
Labels: release:chore, changesets-ok

#11467 chore(auth-providers): switch firebase web to esbuild
  packages/auth-providers/firebase/web/.babelrc.js
  packages/auth-providers/firebase/web/build.ts
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/firebase/web/src/__tests__/firebase.test.tsx
  packages/auth-providers/firebase/web/src/index.ts
  packages/auth-providers/firebase/web/tsconfig.build.json
  packages/auth-providers/firebase/web/tsconfig.cjs.json
  packages/auth-providers/firebase/web/tsconfig.json
  yarn.lock
Labels: release:chore, changesets-ok

#11468 fix: update community discussion link in output from cli - yarn rw upgrade
  packages/cli/src/commands/upgrade.js
Labels: release:fix, changesets-ok

#11520 chore(ci): Temporarily disable 'check:package' step
  .github/workflows/ci.yml
Labels: release:chore, changesets-ok

#11524 docs(chore): Fix formatting
  docs/versions.json
Labels: release:docs

#11521 chore(rsc): Unify RSC and RSA cache structure
  packages/router/src/rsc/RscCache.ts
  packages/router/src/rsc/RscRoutes.tsx
  packages/vite/src/rsc/rscRenderer.ts
Labels: release:chore

#11527 chore(rsc): Remove client.ts and clean-up outdated tests
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
  packages/vite/src/client.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-client.test.ts
Labels: release:chore

#11528 chore(rsc): Remove RSC-specific logic from our babel config
  packages/babel-config/src/web.ts
  packages/vite/src/index.ts
Labels: release:chore

#11531 fix(auth0): avoid use of undefined global in browser environment
  .changesets/11531.md
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/src/auth0.ts
Labels: release:fix

#11534 fix(cli): handle both single and double quotes during dbAuth setup
  .changesets/11534.md
  packages/cli-helpers/src/auth/authTasks.ts
  packages/cli/src/lib/index.js
Labels: release:fix

#11538 chore(crwa): transform lint ignore line as part of ts-to-js
  packages/create-redwood-app/scripts/tsToJS.js
Labels: release:chore, changesets-ok

#11533 [gh11385] Updated the generated page template
  .changesets/11533.md
  __fixtures__/rsc-caching/web/src/pages/CachingOnePage/CachingOnePage.tsx
  __fixtures__/rsc-caching/web/src/pages/CachingTwoPage/CachingTwoPage.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/BlogPage/BlogPage.tsx
  __fixtures__/test-project/web/src/pages/BlogPostPage/BlogPostPage.tsx
  __fixtures__/test-project/web/src/pages/ProfilePage/ProfilePage.tsx
  docs/docs/cli-commands.md
  docs/docs/tutorial/chapter2/routing-params.md
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap
  packages/cli/src/commands/generate/page/templates/page.tsx.template
  packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/__testfixtures__/default.input.js
  packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/__testfixtures__/default.output.js
  packages/codemods/src/codemods/v6.x.x/convertJsToJsx/__testfixtures__/example/input/web/src/pages/TestPage/TestPage.js
  packages/codemods/src/codemods/v6.x.x/convertJsToJsx/__testfixtures__/example/output/web/src/pages/TestPage/TestPage.jsx
Labels: release:feature

#11539 chore(rsc): Don't pass any props to the user's Routes
  packages/router/src/rsc/ClientRouter.tsx
  packages/router/src/rsc/RscRoutes.tsx
  packages/router/src/rsc/ServerRouter.tsx
  packages/vite/src/__tests__/utils.test.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/rsc/rscRenderer.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscStudioHandlers.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/utils.ts
Labels: release:chore

#11544 fix(crwrsca): Check for Node >= 20.10.0
  packages/create-redwood-rsc-app/src/prerequisites.ts
Labels: release:fix

#11552 chore(fixture): update deps
  __fixtures__/test-project/web/package.json
Labels: release:chore, changesets-ok

#11557 fix(crwa): silence telemetry errors
  packages/create-redwood-app/src/telemetry.js
Labels: release:fix, changesets-ok

#11564 Replace MetaTags with Metadata component
  docs/docs/how-to/dbauth-passwordless.md
  docs/versioned_docs/version-8.1/how-to/dbauth-passwordless.md
Labels: release:docs, changesets-ok

#11565 fix(crwrsca): Spawn in shell on Windows
  packages/create-redwood-rsc-app/src/install.ts
  packages/create-redwood-rsc-app/src/latest.ts
Labels: release:fix, changesets-ok

#11566 Docs: Use Redwood's hashPassword() for loginToken hashing in the password-less dbAuth flow
  docs/docs/how-to/dbauth-passwordless.md
Labels: release:docs, changesets-ok

#11567 docs(how-to): Fix example in dbauth-passwordless docs
  docs/docs/how-to/dbauth-passwordless.md
Labels: release:docs, changesets-ok

#11542 feat(cli): Make scaffolded layout routing type-safe
  .changesets/11542.md
  __fixtures__/test-project/web/src/layouts/ScaffoldLayout/ScaffoldLayout.tsx
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/layouts/ScaffoldLayout.tsx.template
Labels: release:feature

#11546 fix(scaffold): Use plain strings in NamesCell template
  __fixtures__/test-project/web/src/components/Contact/ContactsCell/ContactsCell.tsx
  __fixtures__/test-project/web/src/components/Post/PostsCell/PostsCell.tsx
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.tsx.template
Labels: release:fix, changesets-ok

#11570 chore(kitchen-sink): Fix css for page width
  __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/NavigationLayout/NavigationLayout.css
Labels: release:chore

#11568 docs(how-to): replace crypto-js with node's crypto module for random number generation in passwordless auth
  docs/docs/how-to/dbauth-passwordless.md
Labels: release:docs, changesets-ok

#11571 docs(uploads): Tweaks from updating the Recipes example app
  docs/docs/uploads.md
Labels: release:docs, changesets-ok

#11573 Add note to error message about running `yarn rw dev` or `yarn rw build` before the workers can be started
  packages/jobs/src/errors.ts
Labels: release:chore, changesets-ok

#11574 chore(rsc): Simplify RscRoutes by removing external promise
  packages/router/src/rsc/RscRoutes.tsx
Labels: release:chore, fixture-ok, experimental

#11575 chore(deps): Upgrade to React 19 RC 20240916
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/rsc-caching/package.json
  __fixtures__/rsc-caching/web/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project-rsc-kitchen-sink/web/package.json
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/storybook/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:breaking, changesets-ok, experimental

#11583 chore(test-project): Update TailwindCSS
  __fixtures__/test-project/web/package.json
Labels: release:chore

#11572 Default NODE_ENV to "development" if it's `undefined` when starting jobs worker
  .changesets/11572.md
  docs/docs/background-jobs.md
  docs/versioned_docs/version-8.0/background-jobs.md
  docs/versioned_docs/version-8.1/background-jobs.md
  packages/jobs/src/__tests__/setupEnv.test.ts
  packages/jobs/src/bins/rw-jobs-worker.ts
  packages/jobs/src/bins/rw-jobs.ts
  packages/jobs/src/setupEnv.ts
Labels: release:fix

#11540 fix(graphql): Allow including 'File' scalar by default to be disabled
  .changesets/11540.md
  docs/docs/graphql.md
  packages/graphql-server/src/createGraphQLYoga.ts
  packages/graphql-server/src/makeMergedSchema.ts
  packages/graphql-server/src/rootSchema.ts
  packages/graphql-server/src/types.ts
  packages/internal/src/__tests__/clientPreset.test.ts
  packages/internal/src/generate/graphqlCodeGen.ts
  packages/internal/src/generate/graphqlSchema.ts
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
Labels: release:fix

#11578 Fixes `yarn rw jobs clear` command
  .changesets/11578.md
  packages/jobs/src/bins/__tests__/rw-jobs.test.ts
  packages/jobs/src/bins/rw-jobs.ts
Labels: release:fix

#11590 fix(docs): warn that uploads/storage is experimental
  docs/docs/uploads.md
  docs/versioned_docs/version-8.1/uploads.md
Labels: release:docs, changesets-ok

#11592 fix(rsc): Set a yarn resolution for rollup 4.21.3
  __fixtures__/fragment-test-project/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
Labels: release:fix, changesets-ok, experimental

#11591 fix(router): Add missing dependency for RSC
  .changesets/11591.md
  packages/router/package.json
  yarn.lock
Labels: release:fix

#11600 Revert "fix(rsc): Set a yarn resolution for rollup 4.21.3 (#11592)"
  __fixtures__/fragment-test-project/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
Labels: release:fix, changesets-ok

#11593 Fix storybook-vite not starting when `auth.ts` contains named imports after `createAuth`
  .changesets/11593.md
  __fixtures__/test-project/web/package.json
  packages/storybook/src/plugins/mock-auth.ts
Labels: release:fix

#11623 chore(deps): Bump rollup
  yarn.lock
Labels: release:chore, changesets-ok

#10890 Update the Deployment step of the tutorial for GROVE
  docs/docs/tutorial/chapter4/deployment.md
  docs/static/img/tutorial/grove-dashboard.png
Labels: release:docs, changesets-ok

#11636 Fix email link in tutorial
  docs/docs/tutorial/chapter4/deployment.md
Labels: release:docs, changesets-ok

#11116 Removed 'Azure' as deploy provider mention'
  docs/docs/tutorial/chapter0/what-is-redwood.md
  docs/versioned_docs/version-5.x/tutorial/chapter0/what-is-redwood.md
  docs/versioned_docs/version-6.x/tutorial/chapter0/what-is-redwood.md
  docs/versioned_docs/version-7.x/tutorial/chapter0/what-is-redwood.md
  docs/versioned_docs/version-8.0/tutorial/chapter0/what-is-redwood.md
  docs/versioned_docs/version-8.1/tutorial/chapter0/what-is-redwood.md
Labels: release:docs, changesets-ok

#11582 chore(rsc): Refactor: Extract rscFetch and rsaFetch
  packages/router/src/rsc/RscRoutes.tsx
Labels: release:chore, experimental

#11642 chore(rsc): Remove unused node-loader
  packages/vite/attw.ts
  packages/vite/package.json
  packages/vite/src/react-server-dom-webpack/node-loader.ts
Labels: release:chore, experimental

#11643 docs: fix versioned docs
  docs/versioned_docs/version-8.3/tutorial/chapter4/deployment.md
Labels: release:docs, changesets-ok
