Repository redwoodjs/graphql, pull requests merged in 2024-08, with the labels that each got.

#11136 chore(crwrsca): Update knip config to include publish.ts
  packages/create-redwood-rsc-app/knip.json
Labels: release:chore

#11137 chore(crwrsca): log process.argv when --verbose
  packages/create-redwood-rsc-app/src/config.ts
  packages/create-redwood-rsc-app/src/latest.ts
Labels: release:chore

#11138 fix(crwrsca): Fix handling of positional args
  packages/create-redwood-rsc-app/src/config.ts
  packages/create-redwood-rsc-app/src/zip.ts
Labels: release:chore

#11135 fix(cli-cache): Remove RW CLI cache on upgrade
  .changesets/11135.md
  packages/cli/src/commands/upgrade.js
  packages/cli/src/lib/plugin.js
Labels: bug/confirmed, release:fix

#11139 fix(rsc): Remove unused Set in vite plugin
  packages/vite/src/plugins/vite-plugin-rsc-analyze.ts
Labels: release:fix, changesets-ok

#11140 fix(cli): Update react versions during RSC setup command
  packages/cli/src/commands/experimental/setupRscHandler.js
Labels: release:fix, changesets-ok

#11142 fix(crwrsca): Remove execa to loosen up node version requirements
  packages/create-redwood-rsc-app/package.json
  packages/create-redwood-rsc-app/src/git.ts
  packages/create-redwood-rsc-app/src/index.ts
  packages/create-redwood-rsc-app/src/install.ts
  packages/create-redwood-rsc-app/src/latest.ts
  packages/create-redwood-rsc-app/src/prerequisites.ts
  packages/create-redwood-rsc-app/yarn.lock
Labels: release:chore

#11143 fix(crwrsca): Spell please correctly
  packages/create-redwood-rsc-app/src/prerequisites.ts
Labels: release:chore

#11141 Remove erronerous console.log("In decorators") in Storybook package
  packages/storybook/src/preview.tsx
Labels: release:fix, changesets-ok

#11144 fix(rsc): Use functions provided by RSDW
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-client.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-transform-client.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:fix, changesets-ok

#11145 fix(crwrsca): Use the correct version of crwrsca when spawning
  packages/create-redwood-rsc-app/src/latest.ts
Labels: release:chore, fixture-ok

#11146 fix(crwrsca): Set env when re-spawning crwrsca
  packages/create-redwood-rsc-app/src/latest.ts
Labels: release:chore, fixture-ok

#11147 feat(crwrsca): Add support for --version/-V
  packages/create-redwood-rsc-app/src/config.ts
  packages/create-redwood-rsc-app/src/index.ts
  packages/create-redwood-rsc-app/src/version.ts
Labels: release:chore, fixture-ok

#11148 chore(test-project): Update autoprefier
  __fixtures__/test-project/web/package.json
Labels: release:chore

#11150 chore(deps): Upgrade to React 19 RC 20240802
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/rsc-caching/package.json
  __fixtures__/rsc-caching/web/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project-rsc-kitchen-sink/web/package.json
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/storybook/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: changesets-ok, release:dependency

#11151 RSC: 🦄 🦋
  __fixtures__/test-project-rsa/web/src/words.ts
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/HomePage/words.ts
Labels: release:chore

#11152 RSC: Set react resolutions during setup
  packages/cli/src/commands/experimental/setupRscHandler.js
Labels: release:fix

#11155 RSC: Improve type safety in RSC transform plugins
  packages/vite/src/plugins/vite-plugin-rsc-transform-client.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:chore

#11156 RSC: Fix red squiggles in transform client tests
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-client.test.mts
Labels: release:chore

#11159 RSC: RSA: Remove unused check for '$$id'
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:fix, fixture-ok

#11160 RSC: RSA: Add more comments to the basic 'use server' check
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:chore, fixture-ok

#11161 RSC: RSA: Better match error handling with how we generally do it in RW
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:chore, fixture-ok

#11162 chore(tsconfig): Format vite tsconfig
  packages/vite/tsconfig.json
Labels: release:chore, fixture-ok

#11164 chore(ci): Print full diff when check-test-project-fixture fails
  .github/workflows/check-test-project-fixture.yml
Labels: release:chore, fixture-ok

#11166 chore(fixture): Rebuild test project fixture
  __fixtures__/test-project/web/package.json
Labels: release:chore, changesets-ok

#11168 feat(rsc): Detect single RSA functions (not just entire files)
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-analyze.test.ts
  packages/vite/src/plugins/vite-plugin-rsc-analyze.ts
  packages/vite/src/rsc/rscWorker.ts
Labels: release:feature, changesets-ok, experimental

#11169 chore(rsc): Add RSA unit test for module scoped 'use server'
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-server.test.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:chore, changesets-ok, experimental

#11171 fix: Comment out unused import line in seed script template
  __fixtures__/test-project/scripts/seed.ts
  __fixtures__/test-project/web/package.json
  packages/create-redwood-app/templates/js/scripts/seed.js
  packages/create-redwood-app/templates/ts/scripts/seed.ts
  tasks/test-project/codemods/seed.js
Labels: release:fix, changesets-ok

#11110 refactor: api-server's `watch` build process
  packages/api-server/src/__tests__/buildManager.test.ts
  packages/api-server/src/buildManager.ts
  packages/api-server/src/serverManager.ts
  packages/api-server/src/watch.ts
Labels: release:fix, changesets-ok

#11173 Docs: update GitHub workflow file for running tests
  docs/docs/how-to/test-in-github-actions.md
Labels: release:docs, changesets-ok, contributor-pr

#11189 fix(babel-plugins): Handle additional syntax when extracting graphql options
  .changesets/11189.md
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/aliased-import/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/aliased-import/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/wrapper-function/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/wrapper-function/output.js
  packages/babel-config/src/plugins/babel-plugin-redwood-graphql-options-extract.ts
Labels: release:fix

#11176 fix(api-server): Use createServer in all cases, to make fastify config consistent
  .changesets/11176.md
  packages/api-server/src/apiCLIConfigHandler.ts
  packages/api-server/src/bothCLIConfigHandler.ts
Labels: release:breaking

#11226 fix(deps): update dependency core-js to v3.38.0
  package.json
  packages/api/package.json
  packages/auth-providers/auth0/api/package.json
  packages/auth-providers/auth0/setup/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/setup/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/setup/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/custom/setup/package.json
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/setup/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/netlify/setup/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/setup/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/api/package.json
  packages/auth-providers/supertokens/setup/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/babel-config/dist.test.ts
  packages/babel-config/package.json
  packages/babel-config/src/__tests__/api.test.ts
  packages/cli/package.json
  packages/codemods/package.json
  packages/core/package.json
  packages/forms/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/prerender/package.json
  packages/record/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/testing/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: changesets-ok, release:dependency

#11227 chore(deps): update yarn to v4.4.0
  .github/actions/check_changesets/package.json
  .github/actions/check_create_redwood_app/package.json
  .github/actions/detect-changes/package.json
  __fixtures__/test-project/package.json
  docs/package.json
  package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
  tasks/check/package.json
Labels: changesets-ok, release:dependency

#11228 chore(deps): update babel monorepo
  package.json
  packages/api/package.json
  packages/auth-providers/auth0/api/package.json
  packages/auth-providers/auth0/setup/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/setup/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/setup/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/custom/setup/package.json
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/setup/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/netlify/setup/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/setup/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/api/package.json
  packages/auth-providers/supertokens/setup/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/babel-config/dist.test.ts
  packages/babel-config/package.json
  packages/babel-config/src/__tests__/api.test.ts
  packages/cli/package.json
  packages/codemods/package.json
  packages/core/package.json
  packages/eslint-config/package.json
  packages/forms/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/prerender/package.json
  packages/record/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/testing/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: changesets-ok, release:dependency

#11236 docs(serverConfig): Remove server config option from TOML
  .changesets/11176.md
  docs/docs/app-configuration-redwood-toml.md
Labels: topic/docs, release:docs

#10911 chore: brought in typescript-eslint@v8 with stylistic preset
  .changesets/10911.md
  .eslintrc.js
  packages/codemods/src/codemods.ts
  packages/eslint-config/shared.js
  yarn.lock
Labels: release:breaking

#11240 chore(rsc): Switch last remaining transform-server test to inline snapshot
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-server.test.ts
Labels: release:chore, fixture-ok, experimental

#11241 chore(fixture): Update tailwind dep
  __fixtures__/test-project/web/package.json
Labels: release:chore

#11170 fix: Update default tsconfig options (target, module and moduleResolution)
  .changesets/11170.md
  __fixtures__/test-project/api/tsconfig.json
  __fixtures__/test-project/web/tsconfig.json
  packages/create-redwood-app/templates/js/api/jsconfig.json
  packages/create-redwood-app/templates/js/web/jsconfig.json
  packages/create-redwood-app/templates/ts/api/tsconfig.json
  packages/create-redwood-app/templates/ts/web/tsconfig.json
  packages/router/src/index.ts
Labels: release:breaking

#11242 chore(linting): Separate out framework and user linting config
  .eslintrc.js
Labels: release:chore, changesets-ok

#11244 chore(lint): Remove override for 'unused-imports/no-unused-imports'
  .eslintrc.js
  packages/testing/src/web/global.ts
Labels: release:chore, changesets-ok

#11243 chore(rsa): Use swc for parsing server actions
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-server.test.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:chore, experimental

#11249 chore(formatting): Remove 'insert_final_newline' from editor config
  .editorconfig
Labels: release:chore, changesets-ok

#11251 chore(formatting): Formatting 1 of n
  .dependency-cruiser.mjs
  .gitattributes
  .gitpod.yml
  .vscode/extensions.json
  .vscode/settings.json
  nx.json
  package.json
  packages/storybook/package.json
  packages/storybook/tsconfig.json
  packages/testing/src/web/mockRequests.ts
  packages/testing/vitest.config.mts
  packages/tui/tsconfig.json
  packages/vite/package.json
  packages/vite/vitest.config.mts
  packages/web-server/build.mts
  packages/web-server/tsconfig.json
  packages/web/package.json
  packages/web/tsconfig.build.json
  packages/web/tsconfig.json
  packages/web/vitest.config.mts
Labels: release:chore, changesets-ok

#11253 chore(formatting): Add prettier check to CI
  .github/workflows/ci.yml
Labels: release:chore, changesets-ok

#11254 chore(lint): refactor react, react-hooks and ts-eslint usage
  .eslintrc.js
  package.json
  yarn.lock
Labels: release:chore, changesets-ok

#11255 feat(rsc): Register top-level function-scoped RSAs
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-server.function-scope.test.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:feature, changesets-ok, experimental

#11256 chore(linting): Re-enable some ts-eslint rules
  .eslintrc.js
  packages/api/src/validations/validations.ts
  packages/auth-providers/auth0/web/src/auth0.ts
  packages/auth-providers/dbAuth/middleware/build.mts
  packages/auth-providers/supabase/middleware/build.mts
  packages/cli-packages/storybook-vite/build.mts
  packages/cli/build.mts
  packages/cli/testUtils.d.ts
  packages/context/src/context.ts
  packages/forms/vitest.setup.mts
  packages/graphql-server/src/globalContext.ts
  packages/router/src/index.ts
  packages/router/src/location.tsx
  packages/router/vitest.setup.mts
  packages/server-store/src/serverStore.ts
  packages/structure/src/x/vscode.ts
  packages/testing/vitest.setup.mts
  packages/web/src/apollo/typeOverride.ts
  packages/web/src/global.web-auto-imports.ts
  packages/web/vitest.setup.mts
Labels: release:chore, changesets-ok

#11257 chore(lint): lint config refactoring and re-enable some stylistic rules
  .eslintrc.js
  packages/api-server/src/logFormatter/formatters.ts
  packages/api-server/src/plugins/graphql.ts
  packages/api/src/auth/index.ts
  packages/api/src/cache/index.ts
  packages/api/src/validations/validations.ts
  packages/auth-providers/dbAuth/api/src/shared.ts
  packages/babel-config/src/api.ts
  packages/babel-config/src/common.ts
  packages/babel-config/src/web.ts
  packages/cli-helpers/src/auth/setupHelpers.ts
  packages/cli/src/commands/setup/graphql/features/fragments/__tests__/fragmentsHandler.test.ts
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/trustedDocuments.test.ts
  packages/cli/src/commands/setup/monitoring/sentry/sentryHandler.ts
  packages/cli/src/commands/setup/ui/__tests__/tailwindcss.test.ts
  packages/cli/src/testLib/cells.ts
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/replaceComponentSvgs.ts
  packages/codemods/src/lib/cells.ts
  packages/forms/src/FormError.tsx
  packages/graphql-server/src/createGraphQLYoga.ts
  packages/internal/src/gql.ts
  packages/mailer/core/src/__tests__/mailer.test.ts
  packages/mailer/core/src/utils.ts
  packages/mailer/handlers/resend/src/index.ts
  packages/prerender/src/runPrerender.tsx
  packages/project-config/src/paths.ts
  packages/realtime/src/graphql/plugins/useRedwoodRealtime.ts
  packages/router/rsdw.modules.d.ts
  packages/router/src/analyzeRoutes.ts
  packages/router/src/router.tsx
  packages/router/src/rsc/ServerRouter.tsx
  packages/router/src/rsc/ssrModuleMap.ts
  packages/router/src/util.ts
  packages/structure/src/interactive_cli/RedwoodCommandString.ts
  packages/structure/src/interactive_cli/command_builder.ts
  packages/structure/src/interactive_cli/dry_run.ts
  packages/structure/src/model/RWRoute.ts
  packages/structure/src/model/RWRouter.ts
  packages/structure/src/model/RWSDL.ts
  packages/structure/src/model/RWService.ts
  packages/structure/src/model/RWServiceFunction.ts
  packages/structure/src/x/vscode.ts
  packages/telemetry/src/sendTelemetry.ts
  packages/telemetry/src/telemetry.ts
  packages/testing/src/cache/index.ts
  packages/testing/src/web/mockRequests.ts
  packages/vite/modules.d.ts
  packages/vite/src/middleware/types.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-analyze.test.ts
  packages/vite/src/plugins/vite-plugin-remove-from-bundle.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-client.ts
  packages/vite/src/react-server-dom-webpack/node-loader.ts
  packages/vite/src/streaming/collectCss.ts
  packages/vite/src/streaming/triggerRouteHooks.ts
  packages/web/src/__typetests__/cellProps.test.tsx
  packages/web/src/apollo/links.ts
  packages/web/src/components/ServerInject.tsx
  packages/web/src/server/middleware.ts
Labels: release:chore, changesets-ok

#11258 chore(linting): enable type checked linting
  .eslintrc.js
  tsconfig.eslint.json
Labels: release:chore, changesets-ok

#11262 fix(exec): Include nested scripts in --list
  .changesets/11262.md
  __fixtures__/test-project/scripts/one/two/myNestedScript.ts
  packages/cli/src/commands/__tests__/exec.test.ts
  packages/cli/src/commands/execHandler.js
  packages/internal/src/files.ts
  tasks/test-project/rebuild-test-project-fixture.ts
Labels: release:fix

#11261 chore(lint): enable 'typescript-eslint/prefer-includes'
  .eslintrc.js
  packages/api-server/src/plugins/lambdaLoader.ts
  packages/cli/src/commands/setup/monitoring/sentry/sentryHandler.ts
  packages/graphql-server/src/makeMergedSchema.ts
  packages/internal/src/generate/watch.ts
  packages/router/src/util.ts
  packages/structure/src/util.ts
  packages/telemetry/src/sendTelemetry.ts
Labels: release:chore, changesets-ok

#11259 chore(lint): enable 'typescript-eslint/prefer-find'
  .eslintrc.js
  packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader.ts
Labels: release:chore, changesets-ok

#11260 chore(lint): enable '@typescript-eslint/only-throw-error'
  .eslintrc.js
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/graphql-server/src/plugins/__tests__/useRedwoodError.test.ts
  packages/prerender/src/errors.tsx
  packages/web/src/components/cell/createSuspendingCell.tsx
  tsconfig.eslint.json
Labels: release:chore, changesets-ok

#11250 fix(cli): Service generator supports relations
  .changesets/11250.md
  packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
  packages/cli/src/commands/generate/service/service.js
  packages/internal/package.json
  yarn.lock
Labels: topic/generators-&-scaffolds, release:fix, changesets-ok

#11278 feat(exec): Add --silent to silence all RW output
  .changesets/11278.md
  packages/cli/src/commands/exec.js
  packages/cli/src/commands/execHandler.js
Labels: release:feature

#11281 chore(lint): enable 'typescript-eslint/no-unsafe-enum-comparison'
  .eslintrc.js
  packages/babel-config/src/plugins/babel-plugin-redwood-mock-cell-data.ts
  packages/cli/src/testLib/cells.ts
  packages/codemods/src/lib/cells.ts
  packages/eslint-plugin/src/service-type-annotations.ts
  packages/eslint-plugin/src/unsupported-route-components.ts
  packages/graphql-server/src/directives/makeDirectives.ts
  packages/internal/src/generate/graphqlCodeGen.ts
  packages/internal/src/gql.ts
  packages/structure/src/model/RWCell.ts
  packages/structure/src/model/RWSDL.ts
  packages/web/src/apollo/index.tsx
  packages/web/src/graphql.ts
Labels: release:chore, changesets-ok

#11283 chore(lint): enable 'typescript-eslint/no-duplicate-type-constituents'
  .eslintrc.js
  packages/api/src/auth/verifiers/common.ts
  packages/forms/src/coercion.ts
Labels: release:chore, changesets-ok

#11282 chore(lint): enable 'typescript-eslint/no-implied-eval'
  .eslintrc.js
  packages/internal/src/generate/templates.ts
Labels: release:chore, changesets-ok

#11280 chore(lint): enable 'typescript-eslint/prefer-string-starts-ends-with'
  .eslintrc.js
  packages/adapters/fastify/web/src/helpers.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-src-alias.ts
  packages/cli/src/commands/setup/monitoring/sentry/sentryHandler.ts
  packages/forms/src/coercion.ts
  packages/router/src/router.tsx
  packages/router/src/rsc/ServerRouter.tsx
  packages/router/src/util.ts
  packages/structure/src/x/URL.ts
Labels: release:chore, changesets-ok

#11284 chore(lint): enable 'typescript-eslint/no-unnecessary-type-assertion'
  .eslintrc.js
  packages/api/src/cache/index.ts
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/firebase/web/src/__tests__/firebase.test.tsx
  packages/auth-providers/supertokens/web/src/__tests__/supertokens.test.tsx
  packages/babel-config/src/common.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-graphql-options-extract.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-mock-cell-data.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-otel-wrapping.ts
  packages/cli/src/testLib/cells.ts
  packages/codemods/src/lib/cells.ts
  packages/context/src/store.ts
  packages/eslint-plugin/src/service-type-annotations.ts
  packages/graphql-server/src/globalContextStore.ts
  packages/graphql-server/src/plugins/useRedwoodLogger.ts
  packages/internal/src/ast.ts
  packages/internal/src/gql.ts
  packages/prerender/src/babelPlugins/utils.ts
  packages/router/src/util.ts
  packages/structure/src/ide.ts
  packages/structure/src/model/RWRoute.ts
  packages/structure/src/model/util/advanced_path_parser.ts
  packages/structure/src/x/URL.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/rsc/rscBuildEntriesFile.ts
  packages/vite/src/rsc/rscStudioHandlers.ts
  packages/web/src/components/Metadata.tsx
  packages/web/src/components/cell/createSuspendingCell.tsx
  packages/web/src/config.ts
Labels: release:chore, changesets-ok

#11279 chore(lint): first refactoring towards enabling 'require-await' rule
  packages/api-server/src/__tests__/api.test.ts
  packages/api-server/src/__tests__/requestHandlers/awsLambdaFastify.test.ts
  packages/api/src/auth/__tests__/getAuthenticationContext.test.ts
  packages/api/src/logger/logger.test.ts
  packages/internal/src/__tests__/ast.test.ts
  packages/internal/src/__tests__/resolverFn.test.ts
  packages/internal/src/__tests__/validateSchemaForReservedNames.test.ts
  packages/ogimage-gen/src/OgImageMiddleware.test.ts
  packages/realtime/src/graphql/plugins/__tests__/useRedwoodRealtime.test.ts
  packages/structure/src/model/__tests__/model.test.ts
  packages/structure/src/model/util/__tests__/process_env_diagnostics.test.ts
  packages/structure/src/x/__tests__/URL.test.ts
  packages/structure/src/x/__tests__/prisma.test.ts
  packages/structure/src/x/__tests__/vscode-languageserver-types-x.test.ts
  packages/vite/src/middleware/createMiddlewareRouter.test.ts
  packages/vite/src/middleware/register.test.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-analyze.test.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.ts
  packages/web/src/components/cell/createCell.test.tsx
  packages/web/src/components/cell/createSuspendingCell.test.tsx
Labels: release:chore, changesets-ok

#11285 chore(lint): enable 'typescript-eslint/prefer-optional-chain'
  .eslintrc.js
  packages/api/src/auth/index.ts
  packages/api/src/cors.ts
  packages/auth-providers/auth0/web/src/auth0.ts
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/setup/src/__tests__/setupDataMockDMMF.test.ts
  packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/tsconfigForRouteHooks.ts
  packages/forms/src/FormError.tsx
  packages/graphql-server/src/__tests__/makeMergedSchema.test.ts
  packages/internal/src/generate/trustedDocuments.ts
  packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts
  packages/realtime/src/graphql/plugins/useRedwoodRealtime.ts
  packages/router/src/a11yUtils.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/lib/registerFwGlobalsAndShims.ts
  packages/vite/src/middleware/register.test.ts
  packages/vite/src/react-server-dom-webpack/node-loader.ts
  packages/web/src/components/DevFatalErrorPage.tsx
Labels: release:chore, changesets-ok

#11286 chore(formatting): include .changesets dir in prettier config
  .changesets/10064.md
  .changesets/10179.md
  .changesets/10266.md
  .changesets/10342.md
  .changesets/10344.md
  .changesets/10395.md
  .changesets/10420.md
  .changesets/10441.md
  .changesets/10444.md
  .changesets/10453.md
  .changesets/10457.md
  .changesets/10460.md
  .changesets/10464.md
  .changesets/10465.md
  .changesets/10469.md
  .changesets/10493.md
  .changesets/10498.md
  .changesets/10499.md
  .changesets/10502.md
  .changesets/10520.md
  .changesets/10522.md
  .changesets/10538.md
  .changesets/10542.md
  .changesets/10570.md
  .changesets/10585.md
  .changesets/10586.md
  .changesets/10656.md
  .changesets/10668.md
  .changesets/10677.md
  .changesets/10680.md
  .changesets/10697.md
  .changesets/10702.md
  .changesets/10768.md
  .changesets/10817.md
  .changesets/10825.md
  .changesets/10830.md
  .changesets/10833.md
  .changesets/10865.md
  .changesets/10867.md
  .changesets/10869.md
  .changesets/10888.md
  .changesets/10893.md
  .changesets/10900.md
  .changesets/10911.md
  .changesets/10961.md
  .changesets/11062.md
  .changesets/11072.md
  .changesets/11108.md
  .changesets/11109.md
  .changesets/11135.md
  .changesets/11170.md
  .changesets/11189.md
  .changesets/young-spiders-ring.md
  .prettierignore
Labels: release:chore, changesets-ok

#11287 chore(formatting): include .github dir in prettier
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/rfc.yml
  .github/actions/actionsLib.mjs
  .github/actions/check_changesets/check_changesets.mjs
  .github/actions/check_create_redwood_app/check_create_redwood_app.mjs
  .github/actions/detect-changes/README.md
  .github/actions/detect-changes/cases/rsc.mjs
  .github/actions/detect-changes/cases/ssr.mjs
  .github/actions/require-milestone/requireMilestone.mjs
  .github/actions/set-up-rsa-project/jsconfig.json
  .github/actions/set-up-rsa-project/setUpRsaProjectGitHub.mjs
  .github/actions/set-up-rsa-project/setUpRsaProjectLocally.mjs
  .github/actions/set-up-rsc-kitchen-sink-project/jsconfig.json
  .github/actions/set-up-rsc-kitchen-sink-project/setUpRscKitchenSinkProjectGitHub.mjs
  .github/actions/set-up-rsc-kitchen-sink-project/setUpRscKitchenSinkProjectLocally.mjs
  .github/actions/set-up-rsc-project/jsconfig.json
  .github/actions/set-up-rsc-project/setUpRscProject.mjs
  .github/actions/set-up-rsc-project/setUpRscProjectLocally.mjs
  .github/actions/set-up-test-project/action.yaml
  .github/actions/set-up-test-project/setUpTestProject.mjs
  .github/actions/telemetry_check/check.mjs
  .github/scripts/publish_canary.sh
  .github/workflows/check-changelog.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-release-candidate.yml
  .github/workflows/require-release-label.yml
  .prettierignore
Labels: release:chore, changesets-ok

#11290 chore(yarn): update to use js config for constraints
  .github/workflows/ci.yml
  constraints.pro
  package.json
  yarn.config.cjs
  yarn.lock
Labels: release:chore, changesets-ok

#11291 chore: delete crowdin config file
  crowdin.yml
Labels: release:chore, changesets-ok

#11292 chore(check): Refactor 'yarn check' away from being a standalone node script
  .github/workflows/ci.yml
  package.json
  tasks/check/action.yml
  tasks/check/check.mjs
  tasks/check/package.json
  tasks/check/yarn.lock
Labels: release:chore, changesets-ok

#11295 chore(lint): fix prettier configs and ignores
  .prettierignore
  docs/prettier.config.js
  prettier.config.js
Labels: release:chore, changesets-ok

#11294 feat(context): Build and publish package as dual esm/cjs
  packages/context/build.mts
  packages/context/package.json
  packages/context/src/context.ts
  packages/context/src/global.api-auto-imports.ts
  packages/context/src/index.ts
  packages/context/src/store.ts
  packages/context/tsconfig.cjs.json
  packages/context/tsconfig.json
  yarn.lock
Labels: release:feature, changesets-ok

#11297 chore(lint): tidy up the prettier ignore
  .prettierignore
Labels: release:chore, changesets-ok

#9848 Detect/resolve ambiguous script names
  .changesets/9848.md
  packages/cli/src/commands/__tests__/exec.test.ts
  packages/cli/src/commands/execHandler.js
Labels: release:fix, contributor-pr

#11302 chore(exec test): Clean up
  packages/cli/src/commands/__tests__/exec.test.ts
Labels: release:chore, changesets-ok

#11298 chore(build): build core with esbuild
  packages/core/.babelrc.js
  packages/core/build.mts
  packages/core/package.json
  packages/core/src/bins/cross-env.ts
  packages/core/src/bins/eslint.ts
  packages/core/src/bins/jest.ts
  packages/core/src/bins/nodemon.ts
  packages/core/src/bins/redwood.ts
  packages/core/src/bins/rw-api-server-watch.ts
  packages/core/src/bins/rw-dev-fe.ts
  packages/core/src/bins/rw-gen-watch.ts
  packages/core/src/bins/rw-gen.ts
  packages/core/src/bins/rw-log-formatter.ts
  packages/core/src/bins/rw-serve-api.ts
  packages/core/src/bins/rw-serve-fe.ts
  packages/core/src/bins/rw-server.ts
  packages/core/src/bins/rw-web-server.ts
  packages/core/src/bins/rwfw.ts
  yarn.lock
Labels: release:chore, changesets-ok

#11299 chore(deps): Remove webpack related dependencies
  packages/core/package.json
  yarn.lock
Labels: changesets-ok, release:dependency

#11303 fix(auth-providers): Move away from babel for building 'setup' packages
  packages/auth-providers/auth0/setup/.babelrc.js
  packages/auth-providers/auth0/setup/build.mts
  packages/auth-providers/auth0/setup/package.json
  packages/auth-providers/auth0/setup/tsconfig.json
  packages/auth-providers/azureActiveDirectory/setup/.babelrc.js
  packages/auth-providers/azureActiveDirectory/setup/build.mts
  packages/auth-providers/azureActiveDirectory/setup/package.json
  packages/auth-providers/azureActiveDirectory/setup/tsconfig.json
  packages/auth-providers/clerk/setup/.babelrc.js
  packages/auth-providers/clerk/setup/build.mts
  packages/auth-providers/clerk/setup/package.json
  packages/auth-providers/clerk/setup/tsconfig.json
  packages/auth-providers/custom/setup/.babelrc.js
  packages/auth-providers/custom/setup/build.mts
  packages/auth-providers/custom/setup/package.json
  packages/auth-providers/custom/setup/tsconfig.json
  packages/auth-providers/firebase/setup/.babelrc.js
  packages/auth-providers/firebase/setup/build.mts
  packages/auth-providers/firebase/setup/package.json
  packages/auth-providers/firebase/setup/tsconfig.json
  packages/auth-providers/netlify/setup/.babelrc.js
  packages/auth-providers/netlify/setup/build.mts
  packages/auth-providers/netlify/setup/package.json
  packages/auth-providers/netlify/setup/tsconfig.json
  packages/auth-providers/supabase/setup/.babelrc.js
  packages/auth-providers/supabase/setup/build.mts
  packages/auth-providers/supabase/setup/package.json
  packages/auth-providers/supabase/setup/tsconfig.json
  packages/auth-providers/supertokens/setup/.babelrc.js
  packages/auth-providers/supertokens/setup/build.mts
  packages/auth-providers/supertokens/setup/package.json
  packages/auth-providers/supertokens/setup/tsconfig.json
  packages/cli-helpers/package.json
  packages/cli-helpers/tsconfig.build.cjs.json
  packages/framework-tools/src/buildDefaults.ts
  yarn.lock
Labels: release:fix, changesets-ok

#11301 fix(auth-providers): Move away from babel for building 'api' packages
  packages/auth-providers/auth0/api/.babelrc.js
  packages/auth-providers/auth0/api/build.mts
  packages/auth-providers/auth0/api/package.json
  packages/auth-providers/auth0/api/tsconfig.json
  packages/auth-providers/azureActiveDirectory/api/.babelrc.js
  packages/auth-providers/azureActiveDirectory/api/build.mts
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/api/tsconfig.json
  packages/auth-providers/clerk/api/.babelrc.js
  packages/auth-providers/clerk/api/build.mts
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/api/tsconfig.json
  packages/auth-providers/dbAuth/api/.babelrc.js
  packages/auth-providers/dbAuth/api/build.mts
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/api/tsconfig.json
  packages/auth-providers/firebase/api/.babelrc.js
  packages/auth-providers/firebase/api/build.mts
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/api/tsconfig.json
  packages/auth-providers/netlify/api/.babelrc.js
  packages/auth-providers/netlify/api/build.mts
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/netlify/api/tsconfig.json
  packages/auth-providers/supabase/api/.babelrc.js
  packages/auth-providers/supabase/api/build.mts
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/api/tsconfig.json
  packages/auth-providers/supertokens/api/.babelrc.js
  packages/auth-providers/supertokens/api/build.mts
  packages/auth-providers/supertokens/api/package.json
  packages/auth-providers/supertokens/api/tsconfig.json
  yarn.lock
Labels: release:fix, changesets-ok

#11304 fix(internal): Move away from babel for building package
  packages/internal/.babelrc.js
  packages/internal/build.mts
  packages/internal/package.json
  packages/internal/tsconfig.json
  yarn.lock
Labels: release:breaking, changesets-ok

#11305 fix(api): Move away from babel for building package
  packages/api/.babelrc.js
  packages/api/build.mts
  packages/api/package.json
  packages/api/tsconfig.json
  yarn.lock
Labels: release:fix, changesets-ok

#11306 fix(codemods): Move away from babel for building package
  packages/codemods/.babelrc.js
  packages/codemods/build.mts
  packages/codemods/package.json
  packages/codemods/tsconfig.json
  yarn.lock
Labels: release:fix, changesets-ok

#11308 chore(README): Move Kris from Maintainer to Alumni
  README.md
Labels: release:chore

#11309 chore(README): Fix formatting. One row
  README.md
Labels: release:chore

#11310 chore(readme): Add my middle initials
  README.md
Labels: release:chore, changesets-ok

#11307 refactor(api): Add conditional exports to package.json
  .changesets/11307.md
  packages/api-server/src/plugins/graphql.ts
  packages/api/cache/index.js
  packages/api/cache/package.json
  packages/api/logger/index.js
  packages/api/logger/package.json
  packages/api/package.json
  packages/api/webhooks/index.js
  packages/api/webhooks/package.json
  packages/framework-tools/package.json
  packages/framework-tools/src/attw.ts
  packages/framework-tools/src/bins/rw-fwtools-attw.ts
  packages/graphql-server/tsconfig.json
  packages/mailer/core/tsconfig.json
  packages/testing/tsconfig.json
  yarn.lock
Labels: release:breaking

#11311 linting: enable 'typescript-eslint/await-thenable' rule
  .eslintrc.js
  packages/api-server/src/bothCLIConfigHandler.ts
  packages/auth-providers/dbAuth/web/src/webAuthn.ts
  packages/auth-providers/netlify/web/src/netlify.ts
  packages/auth-providers/supabase/api/src/decoder.ts
  packages/cli/src/testUtils/matchFolderTransform.ts
  packages/ogimage-gen/src/vite-plugin-ogimage-gen.test.ts
  packages/router/src/__tests__/routeScrollReset.test.tsx
  packages/vite/src/devFeServer.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscStudioHandlers.ts
  packages/web/src/server/MiddlewareResponse.test.ts
Labels: release:chore, changesets-ok

#11313 chore(babel-config): Fix incorrect internal type for tsconfig paths option
  packages/babel-config/src/common.ts
Labels: release:chore, changesets-ok

#11312 chore(build): refactoring cjs type generation
  packages/auth-providers/dbAuth/middleware/build.mts
  packages/auth-providers/dbAuth/middleware/package.json
  packages/auth-providers/dbAuth/middleware/tsconfig.cjs.json
  packages/auth-providers/dbAuth/middleware/tsconfig.json
  packages/auth-providers/supabase/middleware/build.mts
  packages/auth-providers/supabase/middleware/package.json
  packages/auth-providers/supabase/middleware/tsconfig.cjs.json
  packages/auth-providers/supabase/middleware/tsconfig.json
  packages/context/build.mts
  packages/context/package.json
  packages/context/tsconfig.cjs.json
  packages/framework-tools/package.json
  packages/framework-tools/src/cjsTypes.ts
  packages/framework-tools/src/generateTypes.ts
  packages/router/build.ts
  packages/router/package.json
  packages/router/tsconfig.build.json
  packages/router/tsconfig.cjs.json
  packages/router/tsconfig.json
  yarn.lock
Labels: release:chore, changesets-ok

#11314 Docs: Updated api-side-currentuser.md
  docs/docs/tutorial/chapter7/api-side-currentuser.md
Labels: release:docs, changesets-ok

#11321 chore(docs): fix docs formatting
  docs/docs/tutorial/chapter7/api-side-currentuser.md
Labels: release:docs, changesets-ok

#11324 chore(ci): Temporary fix for format checking on all PRs
  .github/workflows/ci.yml
Labels: release:chore, changesets-ok

#11325 chore(playwright): Make RSC tests less flakey
  tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
  tasks/smoke-tests/shared/common.ts
Labels: release:chore

#11327 chore(test): Fix RSC server cell smoke test
  tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
Labels: release:chore

#11326 chore(build): Consistent tsconfig and buildinfo naming for CJS
  packages/auth/package.json
  packages/auth/tsconfig.cjs.json
  packages/cli-helpers/package.json
  packages/cli-helpers/tsconfig.cjs.json
  packages/project-config/package.json
  packages/project-config/tsconfig.cjs.json
  packages/web/package.json
  packages/web/tsconfig.cjs.json
  tasks/clean.mjs
  tasks/framework-tools/frameworkSyncToProject.mjs
Labels: release:chore

#11300 fix(record): Update dependencies and build dual esm/cjs
  packages/record/.babelrc.js
  packages/record/build.mts
  packages/record/package.json
  yarn.lock
Labels: release:fix, changesets-ok

#11323 [gh11317] Added documentation for working with Jest and Alias Paths
  docs/docs/typescript/introduction.md
Labels: release:docs, changesets-ok

#11330 chore(tsconfig): Properly link to api-server's tsconfig
  packages/api-server/tsconfig.json
  packages/cli/tsconfig.json
Labels: release:chore

#11332 chore(ci): Split formatting check into separate job
  .github/workflows/ci.yml
Labels: release:chore, changesets-ok

#11333 Jobs doc updates
  docs/docs/background-jobs.md
  docs/static/img/background-jobs/jobs-after.png
  docs/static/img/background-jobs/jobs-before.png
  docs/static/img/background-jobs/jobs-queues.png
  docs/static/img/background-jobs/jobs-terminal.png
  docs/static/img/background-jobs/jobs-workers.png
Labels: release:docs

#11334 refactor(auth-providers): switch to esbuild for some 'web' packages
  packages/auth-providers/auth0/web/.babelrc.js
  packages/auth-providers/auth0/web/build.ts
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/auth0/web/src/__tests__/auth0.test.tsx
  packages/auth-providers/auth0/web/src/index.ts
  packages/auth-providers/auth0/web/tsconfig.build.json
  packages/auth-providers/auth0/web/tsconfig.cjs.json
  packages/auth-providers/auth0/web/tsconfig.json
  packages/auth-providers/azureActiveDirectory/web/.babelrc.js
  packages/auth-providers/azureActiveDirectory/web/build.ts
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/azureActiveDirectory/web/src/__tests__/azureActiveDirectory.test.tsx
  packages/auth-providers/azureActiveDirectory/web/src/index.ts
  packages/auth-providers/azureActiveDirectory/web/tsconfig.build.json
  packages/auth-providers/azureActiveDirectory/web/tsconfig.cjs.json
  packages/auth-providers/azureActiveDirectory/web/tsconfig.json
  packages/auth-providers/clerk/web/.babelrc.js
  packages/auth-providers/clerk/web/build.ts
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/clerk/web/src/__tests__/clerk.test.tsx
  packages/auth-providers/clerk/web/src/index.ts
  packages/auth-providers/clerk/web/tsconfig.build.json
  packages/auth-providers/clerk/web/tsconfig.cjs.json
  packages/auth-providers/clerk/web/tsconfig.json
  packages/auth-providers/netlify/web/.babelrc.js
  packages/auth-providers/netlify/web/build.ts
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/netlify/web/src/__tests__/netlify.test.tsx
  packages/auth-providers/netlify/web/src/index.ts
  packages/auth-providers/netlify/web/tsconfig.build.json
  packages/auth-providers/netlify/web/tsconfig.cjs.json
  packages/auth-providers/netlify/web/tsconfig.json
  packages/auth-providers/supabase/web/.babelrc.js
  packages/auth-providers/supabase/web/build.ts
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supabase/web/src/__tests__/supabase.middleware.test.tsx
  packages/auth-providers/supabase/web/src/__tests__/supabase.test.tsx
  packages/auth-providers/supabase/web/src/index.ts
  packages/auth-providers/supabase/web/tsconfig.build.json
  packages/auth-providers/supabase/web/tsconfig.cjs.json
  packages/auth-providers/supabase/web/tsconfig.json
  packages/auth-providers/supertokens/web/.babelrc.js
  packages/auth-providers/supertokens/web/build.ts
  packages/auth-providers/supertokens/web/package.json
  packages/auth-providers/supertokens/web/src/__tests__/supertokens.test.tsx
  packages/auth-providers/supertokens/web/src/index.ts
  packages/auth-providers/supertokens/web/tsconfig.build.json
  packages/auth-providers/supertokens/web/tsconfig.cjs.json
  packages/auth-providers/supertokens/web/tsconfig.json
  yarn.lock
Labels: release:chore, changesets-ok

#11335 Adds more tests! Refactor rw-jobs-worker
  packages/jobs/src/bins/__tests__/rw-jobs-worker.test.ts
  packages/jobs/src/bins/__tests__/rw-jobs.test.ts
  packages/jobs/src/bins/rw-jobs-worker.ts
  packages/jobs/src/core/JobManager.ts
  packages/jobs/src/core/__tests__/Executor.test.ts
Labels: release:chore, changesets-ok

#11338 refactor(forms): Build with esbuild and add conditional exports
  .changesets/11338.md
  packages/forms/.babelrc.js
  packages/forms/build.mts
  packages/forms/package.json
  packages/forms/tsconfig.build.json
  packages/forms/tsconfig.json
  yarn.lock
Labels: release:breaking

#11339 chore(test-fixture): correct rebuild script string suffix substitution
  tasks/test-project/codemods/scenarioValueSuffix.js
Labels: release:chore, changesets-ok

#11340 fix(api-server): Fix issue with clean builds
  packages/api-server/package.json
  packages/api-server/tsconfig.build.json
  packages/cli/tsconfig.json
  packages/core/package.json
  packages/graphql-server/package.json
  packages/graphql-server/tsconfig.json
  packages/jobs/tsconfig.build.json
  packages/testing/tsconfig.json
  yarn.lock
Labels: release:fix, changesets-ok

#11341 chore(project-sync): Fix infinite looping due to package.json changes
  tasks/framework-tools/frameworkSyncToProject.mjs
Labels: release:chore, changesets-ok

#11328 chore(jobs): Mostly nitpicky changes to the Jobs PR
  docs/docs/background-jobs.md
  packages/babel-config/src/plugins/babel-plugin-redwood-job-path-injector.ts
  packages/cli/src/commands/generate/job/__tests__/job.test.ts
  packages/cli/src/commands/generate/job/job.js
  packages/cli/src/commands/setup/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/setup/__tests__/jobsHandler.test.ts
  packages/cli/src/commands/setup/jobs/jobsHandler.js
  packages/jobs/build.ts
  packages/jobs/package.json
  packages/jobs/src/adapters/PrismaAdapter/PrismaAdapter.ts
  packages/jobs/src/adapters/PrismaAdapter/errors.ts
  packages/jobs/src/bins/rw-jobs.ts
  packages/jobs/src/core/JobManager.ts
  packages/jobs/src/core/Scheduler.ts
  packages/jobs/src/core/Worker.ts
  packages/jobs/src/core/__tests__/Worker.test.ts
  packages/jobs/src/loaders.ts
  packages/jobs/src/types.ts
  packages/jobs/tsconfig.json
  yarn.lock
Labels: release:chore, changesets-ok

#11343 Highlight output commands
  packages/cli/src/commands/setup/jobs/jobsHandler.js
Labels: release:chore

#11344 fix(jobs): Include bin proxies and only build to cjs
  packages/cli-helpers/package.json
  packages/cli-helpers/src/lib/loadEnvFiles.ts
  packages/core/package.json
  packages/core/src/bins/rw-jobs-worker.ts
  packages/core/src/bins/rw-jobs.ts
  packages/jobs/build.mts
  packages/jobs/build.ts
  packages/jobs/package.json
  packages/jobs/src/bins/rw-jobs.ts
  packages/jobs/tsconfig.cjs.json
  yarn.lock
Labels: release:fix, changesets-ok

#11345 Adds a "highlight" color option
  packages/cli-helpers/src/lib/colors.ts
  packages/cli-packages/dataMigrate/src/lib/colors.ts
  packages/cli/src/commands/setup/jobs/jobsHandler.js
  packages/cli/src/lib/colors.js
Labels: release:feature, changesets-ok

#11349 chore(jobs tests): Fix types
  packages/cli/src/commands/setup/__tests__/jobsHandler.test.ts
Labels: release:chore, changesets-ok

#11350 chore(tests): TypeScript Listr2 mock
  packages/cli/src/__tests__/Listr2Mock.ts
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.mockListr.test.js
  packages/cli/src/commands/setup/__tests__/jobsHandler.test.ts
  packages/cli/vitest.workspaces.ts
Labels: release:chore, changesets-ok

#11351 chore(cli tests): Fix include glob
  packages/cli/vitest.workspaces.ts
Labels: release:chore, changesets-ok

#11348 chore(jobs): Add e2e test script and CI job
  .github/workflows/ci.yml
  package.json
  tasks/e2e-background-jobs/README.md
  tasks/e2e-background-jobs/fixtures.mts
  tasks/e2e-background-jobs/run.mts
  tasks/e2e-background-jobs/util.mts
Labels: release:chore, changesets-ok

#11352 chore(listr2mock): Improve types and make it more capable
  packages/cli/src/__tests__/Listr2Mock.ts
  packages/cli/src/commands/setup/graphql/features/fragments/__tests__/fragmentsHandler.test.ts
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/trustedDocuments.test.ts
  packages/cli/src/commands/setup/ui/__tests__/tailwindcss.test.ts
Labels: release:chore, changesets-ok

#11354 chore(listr2mock): Move comments closer to referenced code
  packages/cli/src/__tests__/Listr2Mock.ts
Labels: release:chore, changesets-ok

#11355 chore(jobs test): Remove unused file. Use toContain()
  packages/cli/src/commands/setup/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/setup/__tests__/jobsHandler.test.ts
Labels: release:chore, changesets-ok

#11346 feat(storybook): Remove consideration of mjs from docgen plugin
  packages/storybook/src/plugins/react-docgen.ts
  packages/storybook/src/preset.ts
Labels: release:fix, changesets-ok

#11359 Adds docs for jobs setup and generate commands
  docs/docs/cli-commands.md
Labels: release:docs, changesets-ok

#11361 Adds docs for how to do recurring jobs
  docs/docs/background-jobs.md
Labels: release:docs, changesets-ok

#11363 chore(deps): bump micromatch to 4.0.8 in create-redwood-rsc-app
  packages/create-redwood-rsc-app/yarn.lock
Labels: release:chore, changesets-ok

#11362 chore(deps): bump micromatch to 4.0.8
  yarn.lock
Labels: release:chore, changesets-ok

#11364 fix(cli): Fix tests generated by `g cell`
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/templates/test.js.template
Labels: release:fix, changesets-ok

#11368 fix(tsconfig): set "module" to "ESNext" for web/tsconfig.json
  __fixtures__/fragment-test-project/web/tsconfig.json
  __fixtures__/test-project-rsa/web/tsconfig.json
  __fixtures__/test-project-rsc-kitchen-sink/web/tsconfig.json
  __fixtures__/test-project/web/tsconfig.json
  packages/create-redwood-app/templates/js/web/jsconfig.json
  packages/create-redwood-app/templates/ts/web/tsconfig.json
Labels: release:breaking, changesets-ok

#11365 fix(template): Format tsconfig and jsconfig
  __fixtures__/test-project/api/tsconfig.json
  __fixtures__/test-project/scripts/tsconfig.json
  __fixtures__/test-project/web/tsconfig.json
  packages/create-redwood-app/templates/js/api/jsconfig.json
  packages/create-redwood-app/templates/js/scripts/jsconfig.json
  packages/create-redwood-app/templates/js/web/jsconfig.json
  packages/create-redwood-app/templates/ts/api/tsconfig.json
  packages/create-redwood-app/templates/ts/scripts/tsconfig.json
  packages/create-redwood-app/templates/ts/web/tsconfig.json
Labels: release:fix, changesets-ok

#11366 fix(template): Set scripts/ module resolution to match api/
  .changesets/11366.md
  __fixtures__/test-project/scripts/tsconfig.json
  packages/create-redwood-app/templates/js/scripts/jsconfig.json
  packages/create-redwood-app/templates/ts/scripts/tsconfig.json
Labels: release:breaking

#11369 feat(jobs): Expose types
  packages/jobs/src/index.ts
Labels: release:feature, changesets-ok

#11370 chore(jobs tests): String literal array for queues
  packages/jobs/src/core/__tests__/JobManager.test.ts
Labels: release:chore, changesets-ok

#11371 fix(jobs): Type-safe arguments passing to jobs from scheduler
  packages/jobs/src/core/JobManager.ts
  packages/jobs/src/core/Scheduler.ts
  packages/jobs/src/core/__tests__/JobManager.test.ts
  packages/jobs/src/core/__tests__/Scheduler.test.ts
Labels: release:fix, changesets-ok

#11376 RCS: Basic support for 'use server' inside components
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-server.function-scope.test.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:feature, changesets-ok, experimental

#11377 fix(jobs): Fix the `deleteSuccessfulJobs` type showing up
  packages/jobs/src/core/Worker.ts
  packages/jobs/src/types.ts
Labels: release:fix, changesets-ok

#11378 feat(uploads): Add File scalar to rootSchema
  .changesets/11378.md
  __fixtures__/example-todo-main/web/src/graphql/graphql.ts
  packages/graphql-server/src/rootSchema.ts
  packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
  packages/internal/src/__tests__/__snapshots__/graphqlSchema.test.ts.snap
Labels: release:feature

#11379 template(db): Update `api/src/lib/db` template
  .changesets/11379.md
  __fixtures__/test-project/api/src/lib/db.ts
  packages/create-redwood-app/templates/js/api/src/lib/db.js
  packages/create-redwood-app/templates/ts/api/src/lib/db.ts
Labels: release:feature

#11387 Catch errors when studio is not running and mail tries to send
  packages/mailer/handlers/studio/src/index.ts
Labels: release:fix, changesets-ok

#11384 chore(test): Update tests to make them compatible with Vite's ecosystem CI
  packages/cli/src/commands/__tests__/dev.test.js
  packages/cli/src/lib/__tests__/getDevNodeOptions.test.js
Labels: release:chore

#11263 feat(uploads): Create uploads package with prisma extension and upload processors
  .changesets/11154.md
  .eslintrc.js
  packages/uploads/.gitignore
  packages/uploads/README.md
  packages/uploads/attw.ts
  packages/uploads/build.mts
  packages/uploads/package.json
  packages/uploads/prisma-override.d.ts
  packages/uploads/src/FileSystemStorage.ts
  packages/uploads/src/MemoryStorage.ts
  packages/uploads/src/StorageAdapter.ts
  packages/uploads/src/__tests__/FileSystemsStorage.test.ts
  packages/uploads/src/__tests__/MemoryStorage.test.ts
  packages/uploads/src/__tests__/createProcessors.test.ts
  packages/uploads/src/__tests__/queryExtensions.test.ts
  packages/uploads/src/__tests__/resultExtensions.test.ts
  packages/uploads/src/__tests__/signedUrls.test.ts
  packages/uploads/src/__tests__/unit-test-schema.prisma
  packages/uploads/src/createProcessors.ts
  packages/uploads/src/fileHandling.ts
  packages/uploads/src/index.ts
  packages/uploads/src/prismaExtension.ts
  packages/uploads/src/signedUrls.ts
  packages/uploads/tsconfig.json
  packages/uploads/tsconfig.types-cjs.json
  packages/uploads/vitest.config.mts
  packages/uploads/vitest.setup.mts
  yarn.lock
Labels: release:feature

#11389 chore(jobs tests): Fix a couple of TS issues
  packages/jobs/src/bins/__tests__/rw-jobs-worker.test.ts
  packages/jobs/tsconfig.json
  packages/jobs/vitest.config.mts
Labels: release:chore

#11391 chore(rsc): Rename rsf -> rsa
  packages/router/src/rsc/rscFetchForClientRouter.tsx
  packages/vite/src/buildRscClientAndServer.ts
  packages/vite/src/client.ts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscStudioHandlers.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
Labels: release:chore

#11392 Add OSSF scorecard action to our CI
  .github/workflows/scorecard.yml
Labels: release:chore, changesets-ok

#11393 chore(ci): Add permissions to some workflows/jobs
  .github/workflows/codeql-analysis.yml
  .github/workflows/require-milestone.yml
  .github/workflows/require-release-label.yml
Labels: release:chore, changesets-ok

#11394 chore(ci): More workflow permission changes
  .github/workflows/check-changelog.yml
  .github/workflows/check-create-redwood-app.yml
  .github/workflows/check-test-project-fixture.yml
  .github/workflows/codeql-analysis.yml
Labels: release:chore, changesets-ok

#11395 chore(ci): Pin action dependencies by digest
  .github/workflows/check-changelog.yml
  .github/workflows/check-create-redwood-app.yml
  .github/workflows/check-test-project-fixture.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-release-candidate.yml
  .github/workflows/require-milestone.yml
  .github/workflows/require-release-label.yml
  .github/workflows/scorecard.yml
Labels: release:chore, changesets-ok

#11396 chore(deps): Bump 'loader-utils' within docs
  docs/yarn.lock
Labels: release:chore, changesets-ok

#11397 chore(ci): Follow up to workflow permissions
  .github/workflows/check-test-project-fixture.yml
  .github/workflows/ci.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-release-candidate.yml
Labels: release:chore, changesets-ok

#8556 feat(codegen): support sdl generation for model with compound id
  .changesets/8556.md
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/generate/sdl/templates/sdl.js.template
  packages/cli/src/commands/generate/sdl/templates/sdl.ts.template
Labels: release:fix, contributor-pr

#11390 feat(storage): Add support for createMany, updateMany and upsert
  .changesets/11390.md
  packages/uploads/src/__tests__/queryExtensions.test.ts
  packages/uploads/src/prismaExtension.ts
Labels: release:feature

#11399 chore(fixtures): Use proper name for AuthLayout component
  __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/AuthLayout/AuthLayout.tsx
Labels: release:chore

#11400 RSC: Disable client side flight caching for now
  packages/router/src/rsc/RscCache.ts
Labels: release:fix, fixture-ok, changesets-ok, experimental

#11367 fix(template): api type declaration merging for scripts
  .changesets/11367.md
  __fixtures__/test-project/scripts/tsconfig.json
  packages/create-redwood-app/templates/js/scripts/jsconfig.json
  packages/create-redwood-app/templates/ts/scripts/tsconfig.json
Labels: release:fix

#11401 rscRequestHandler.ts: Make BASE_PATH naming match client.ts
  packages/vite/src/rsc/rscRequestHandler.ts
Labels: release:chore

#11403 chore(rsc): Return flight from RSAs
  packages/router/src/rsc/ClientRouter.tsx
  packages/router/src/rsc/RscFetcher.tsx
  packages/router/src/rsc/rscFetchForClientRouter.tsx
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
Labels: release:chore, changesets-ok, experimental
