Repository redwoodjs/graphql, pull requests merged in 2024-05, with the labels that each got.

#10499 feat(auth): Implement Supabase Auth Middleware
  .changesets/10499.md
  packages/api/src/auth/index.ts
  packages/auth-providers/netlify/api/src/decoder.ts
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/api/src/__tests__/supabase.test.ts
  packages/auth-providers/supabase/api/src/decoder.ts
  packages/auth-providers/supabase/api/src/index.ts
  packages/auth-providers/supabase/api/tsconfig.json
  packages/auth-providers/supabase/middleware/README.md
  packages/auth-providers/supabase/middleware/build.mts
  packages/auth-providers/supabase/middleware/cjsWrappers/plugin.js
  packages/auth-providers/supabase/middleware/package.json
  packages/auth-providers/supabase/middleware/src/__tests__/createSupabaseAuthMiddleware.test.ts
  packages/auth-providers/supabase/middleware/src/index.ts
  packages/auth-providers/supabase/middleware/src/util.ts
  packages/auth-providers/supabase/middleware/tsconfig.json
  packages/auth-providers/supabase/middleware/vitest.config.mts
  packages/vite/src/middleware/CookieJar.test.ts
  packages/vite/src/middleware/CookieJar.ts
  yarn.lock
Labels: release:feature

#10532 chore(canary): Avoid `workspace:*` in published package.json files
  .github/scripts/publish_canary.sh
Labels: release:chore, changesets-ok

#10531 feat(server-auth): Refactor useReauthenticate to prevent double currentUser calls
  .changesets/10531.md
  packages/auth-providers/dbAuth/web/src/dbAuth.ts
  packages/auth-providers/netlify/web/src/__tests__/netlify.test.tsx
  packages/auth-providers/supertokens/web/src/__tests__/supertokens.test.tsx
  packages/auth/src/AuthProvider/useReauthenticate.ts
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/auth/src/__tests__/fixtures/customTestAuth.ts
Labels: release:feature

#10533 feat(RSC): Remove `entries.ts` file
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/vite/package.json
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRscClientAndServer.ts
  packages/vite/src/clientSsr.ts
  packages/vite/src/entries.ts
  packages/vite/src/lib/entries.ts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildEntriesFile.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscWorker.ts
Labels: release:feature, changesets-ok

#10535 chore(router): Refactor: Move analyzeRoutes to separate file
  packages/router/src/AuthenticatedRoute.tsx
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/analyzeRoutes.ts
  packages/router/src/router-context.tsx
  packages/router/src/router.tsx
  packages/router/src/server-router.tsx
  packages/router/src/useRoutePaths.ts
  packages/router/src/util.ts
Labels: release:chore, changesets-ok

#10539 RSC: Remove one level of nesting for server-router
  packages/router/src/server-router.tsx
Labels: release:chore, changesets-ok

#10541 RSC: Chore: Need to await getEntries in console.log
  packages/vite/src/clientSsr.ts
Labels: release:chore, changesets-ok

#10545 chore(linting): fix minor lint warnings
  packages/router/src/__tests__/analyzeRoutes.test.tsx
Labels: release:chore, changesets-ok

#10542 Rename og component assets from *.png.jsx to just *.og.jsx
  .changesets/10542.md
  packages/ogimage-gen/src/OgImageMiddleware.test.ts
  packages/ogimage-gen/src/OgImageMiddleware.ts
  packages/ogimage-gen/src/hooks.ts
  packages/ogimage-gen/src/vite-plugin-ogimage-gen.test.ts
  packages/ogimage-gen/src/vite-plugin-ogimage-gen.ts
Labels: topic/cells, release:chore

#10549 fix(rsc): Remove entries file setup step and remove from test fixtures
  __fixtures__/test-project-rsa/web/src/entries.ts
  __fixtures__/test-project-rsc-kitchen-sink/web/src/entries.ts
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/templates/rsc/entries.ts.template
Labels: release:fix, changesets-ok

#10550 Adds a generator for creating og:image components
  .changesets/10550.md
  packages/cli/src/commands/generate/ogImage/__tests__/__snapshots__/ogImage.test.jsx.snap
  packages/cli/src/commands/generate/ogImage/__tests__/ogImage.test.jsx
  packages/cli/src/commands/generate/ogImage/ogImage.js
  packages/cli/src/commands/generate/ogImage/templates/ogImage.og.tsx.template
Labels: release:feature

#10548 Fix links to other sections
  docs/docs/graphql.md
  docs/docs/graphql/fragments.md
Labels: release:docs, changesets-ok

#10054 docs: Adds GraphQL Caching docs for Client and Response caching
  .changesets/10054.md
  docs/docs/graphql/caching.md
  docs/docs/graphql/fragments.md
  docs/sidebars.js
Labels: release:docs

#10510 Fix radio button null element default prop to use correct input
  .changesets/10510.md
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/generate/scaffold/templates/components/NameForm.tsx.template
Labels: release:fix, contributor-pr

#10554 chore(middleware): Format code and comments and fix comment grammar
  packages/vite/src/middleware/invokeMiddleware.ts
Labels: release:chore, changesets-ok

#10555 fix(functions): Mock context in function test template
  .changesets/10555.md
  packages/cli/src/commands/generate/function/__tests__/__snapshots__/function.test.ts.snap
  packages/cli/src/commands/generate/function/templates/test.ts.template
Labels: release:fix

#10556 fix(functions): Fix context variable warning/error
  .changesets/10556.md
  packages/cli/src/commands/generate/function/__tests__/__snapshots__/function.test.ts.snap
  packages/cli/src/commands/generate/function/templates/function.ts.template
Labels: release:fix

#10558 chore(deps): React beta 20240508
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-kitchen-sink/web/package.json
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10559 Revert "chore(deps): React beta 20240508 (#10558)"
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-kitchen-sink/web/package.json
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10560 chore(deps): Upgrade React 19 to beta 20240508
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project-rsc-kitchen-sink/web/package.json
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10552 chore(docs): Update dbAuth and Supabase middleware READMEs
  packages/auth-providers/dbAuth/middleware/README.md
  packages/auth-providers/supabase/middleware/README.md
Labels: release:chore, changesets-ok

#10553 Define `process.env.NODE_ENV` in build process.
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/streaming/buildForStreamingServer.ts
Labels: release:fix, changesets-ok

#10551 fix(cli): Add deprecation notice for edgio deployment
  .changesets/10551.md
  docs/docs/deploy/edgio.md
  packages/cli/src/commands/deploy/edgio.js
  packages/cli/src/commands/setup/deploy/providers/edgio.js
Labels: release:fix

#10544 fix(rsc): Load all css links to support css with rsc
  packages/vite/src/buildRscClientAndServer.ts
  packages/vite/src/clientSsr.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-css-preinit-fixture-values.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-css-preinit.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-analyze.ts
  packages/vite/src/plugins/vite-plugin-rsc-css-preinit.ts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscCss.ts
  packages/vite/src/runFeServer.ts
  tasks/smoke-tests/rsc-dev/tests/rsc.spec.ts
  tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
  tasks/smoke-tests/rsc/tests/rsc.spec.ts
Labels: release:fix, fixture-ok, changesets-ok

#10231 Added warning note to not add WebAuthn
  .changesets/10231.md
  docs/docs/tutorial/chapter4/authentication.md
  docs/versioned_docs/version-6.x/tutorial/chapter4/authentication.md
  docs/versioned_docs/version-7.0/tutorial/chapter4/authentication.md
Labels: release:docs

#10561 Docs: QoL Updates to Contributing.md
  .changesets/10561.md
  CONTRIBUTING.md
Labels: release:docs

#10562 RSC: Fix TODO regarding SSR in client.ts
  packages/vite/src/client.ts
Labels: release:chore, changesets-ok

#10564 RSC: Extract the fetchRSC function
  packages/vite/src/client.ts
Labels: release:chore, changesets-ok

#10565 Split RSC and RSA handling in rscWorker
  packages/vite/src/rsc/rscWorker.ts
Labels: release:chore, changesets-ok

#10567 RSC: getViteConfig in rscWorker
  packages/vite/src/rsc/rscWorker.ts
Labels: release:chore, changesets-ok

#10569 chore(router): Add more code comments to analyzeRoutes
  packages/router/src/analyzeRoutes.ts
Labels: release:chore, changesets-ok

#10566 Docs: Correcting the prop name to `roles` from `hasRoles` for the `PrivateSet` component in the Authentication doc
  docs/docs/authentication.md
  docs/docs/router.md
Labels: release:docs, changesets-ok

#10571 fix(mw): Pass matched params in invokeOptions in runFeServer
  packages/vite/src/runFeServer.ts
Labels: release:fix, changesets-ok

#10570 fix(functions-test): Fix mockHttpEvent for null bodies
  .changesets/10570.md
  packages/testing/src/api/apiFunction.ts
Labels: release:breaking

#10574 feat(cli): Add experimental setup command for React Compiler
  .changesets/10574.md
  packages/babel-config/src/web.ts
  packages/cli/src/commands/experimental/setupReactCompiler.js
  packages/cli/src/commands/experimental/setupReactCompilerHandler.js
  packages/eslint-config/index.js
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
Labels: release:feature

#10584 Updated Form URL in Input Components
  packages/forms/src/InputComponents.tsx
Labels: release:chore, changesets-ok

#10645 chore(deps): Remove unused octokit package
  package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10585 feat(rsc-auth): Implement serverStore to hold and pass req info to RSC
  .changesets/10585.md
  packages/vite/package.json
  packages/vite/src/devFeServer.ts
  packages/vite/src/middleware/invokeMiddleware.test.ts
  packages/vite/src/middleware/invokeMiddleware.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscStudioHandlers.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/serverStore.ts
  packages/vite/src/utils.ts
Labels: release:feature

#10648 Add missing rwjs/auth deps
  packages/auth-providers/supabase/middleware/package.json
  packages/vite/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10649 chore(deps): Remove unused deps from prerender
  packages/prerender/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10643 chore(serverAuth): Rename serverAuthContext to serverAuthState where relevant
  .changesets/10499.md
  .changesets/10643.md
  packages/auth-providers/dbAuth/middleware/src/__tests__/createDbAuthMiddleware.test.ts
  packages/auth-providers/dbAuth/middleware/src/index.ts
  packages/auth-providers/supabase/middleware/src/__tests__/createSupabaseAuthMiddleware.test.ts
  packages/auth-providers/supabase/middleware/src/index.ts
  packages/auth-providers/supabase/middleware/src/util.ts
  packages/vite/src/middleware/MiddlewareRequest.test.ts
  packages/vite/src/middleware/MiddlewareRequest.ts
  packages/vite/src/middleware/invokeMiddleware.test.ts
  packages/vite/src/middleware/invokeMiddleware.ts
Labels: release:chore

#10650 chore(ci): Update rsc readme
  .github/actions/set-up-rsc-project/README.md
Labels: release:chore, changesets-ok

#10651 patch(crwa): Fix small annoyances (formatting, spell-check)
  .changesets/10651.md
  .vscode/settings.json
  __fixtures__/test-project/web/src/entry.client.tsx
  packages/create-redwood-app/templates/js/web/src/entry.client.jsx
  packages/create-redwood-app/templates/ts/web/src/entry.client.tsx
Labels: release:fix

#10652 chore(ssr): Make entry.client.tsx better match standard entry.client
  packages/cli/src/commands/experimental/templates/streamingSsr/entry.client.tsx.template
Labels: release:chore, fixture-ok, changesets-ok

#10586 feat(middleware): Add .shortCircuit to MiddlewareResponse
  .changesets/10586.md
  packages/vite/src/middleware/MiddlewareResponse.test.ts
  packages/vite/src/middleware/MiddlewareResponse.ts
  packages/vite/src/middleware/invokeMiddleware.test.ts
  packages/vite/src/middleware/invokeMiddleware.ts
Labels: release:feature

#10653 fix(vite): Rename `serverAuthContext` to `serverAuthState`
  packages/vite/src/middleware/invokeMiddleware.ts
Labels: release:fix, changesets-ok

#10642 feat(auth-middleware): Return a Tuple with Route pattern configuration when creating dbAuth middleware
  .changesets/10642.md
  packages/auth-providers/dbAuth/middleware/README.md
  packages/auth-providers/dbAuth/middleware/src/__tests__/initDbAuthMiddleware.test.ts
  packages/auth-providers/dbAuth/middleware/src/index.ts
Labels: release:feature

#10655 chore(__fixtures__): Make test projects match newer CRWA template
  __fixtures__/fragment-test-project/web/src/App.tsx
  __fixtures__/fragment-test-project/web/src/entry.client.tsx
  __fixtures__/test-project-rsa/web/src/App.tsx
  __fixtures__/test-project-rsa/web/src/entry.client.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/App.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/entry.client.tsx
  packages/create-redwood-app/templates/ts/web/src/App.tsx
Labels: release:chore, fixture-ok, changesets-ok

#10572 feat: Reworks RSC server entries and route manifest building to derive from routes and include if route info related to authentication
  .changesets/10572.md
  __fixtures__/example-todo-main/web/src/Routes.js
  __fixtures__/fragment-test-project/web/src/Routes.tsx
  packages/internal/src/__tests__/__snapshots__/typeDefinitions.test.ts.snap
  packages/internal/src/routes.ts
  packages/project-config/src/paths.ts
  packages/structure/src/model/RWPage.ts
  packages/structure/src/model/RWProject.ts
  packages/structure/src/model/RWRoute.ts
  packages/structure/src/model/RWRouter.ts
  packages/structure/src/model/__tests__/model.test.ts
  packages/vite/src/buildRouteManifest.ts
  packages/vite/src/lib/entries.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-routes-auto-loader.ts
  packages/vite/src/rsc/rscRequestHandler.ts
Labels: release:feature

#10657 chore(__fixtures__): Follow-up: Make test projects match newer CRWA template
  __fixtures__/test-project-rsa/web/src/entry.client.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/entry.client.tsx
Labels: release:chore, changesets-ok

#10659 RSC: Add 'use client' to all client cells in kitchen-sink
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/UserExample/EditUserExampleCell/EditUserExampleCell.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/UserExample/UserExampleCell/UserExampleCell.tsx
Labels: release:fix, changesets-ok

#10658 RSC: Source format of EmptyUsersCell in kitchen-sink
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/EmptyUser/EmptyUsersCell/EmptyUsersCell.tsx
Labels: release:chore, changesets-ok

#10660 RSC: Make the kitchen-sink smoke-test more robust/resilient
  tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
Labels: release:chore, changesets-ok

#10661 RSC: kitchen-sink: Make it more clear where layout ends and main content starts
  __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/NavigationLayout/NavigationLayout.tsx
Labels: release:chore, changesets-ok

#10663 fix(cli): Handle case for no arguments for verbose baremetal deploy
  .changesets/10663.md
  packages/cli/src/commands/deploy/baremetal/SshExecutor.js
Labels: release:fix

#10662 RSC: vite auto-loader: Spell out 'path' and other chores
  packages/vite/src/plugins/vite-plugin-rsc-routes-auto-loader.ts
Labels: release:chore, changesets-ok

#10665 RSC: Add 'use client' to remaining client cells in kitchen-sink
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/EmptyUser/EditEmptyUserCell/EditEmptyUserCell.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/EmptyUser/EmptyUserCell/EmptyUserCell.tsx
Labels: release:chore, fixture-ok, changesets-ok

#10557 RSC Client Router
  __fixtures__/test-project-rsa/web/src/Routes.tsx
  __fixtures__/test-project-rsa/web/src/entry.server.tsx
  __fixtures__/test-project-rsa/web/src/layouts/NavigationLayout/NavigationLayout.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/Routes.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/ServerRoutes.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/EmptyUser/EmptyUsersCell/EmptyUsersCell.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/ReadFileServerCell/ReadFileServerCell.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/entry.server.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/NavigationLayout/NavigationLayout.tsx
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/templates/rsc/NavigationLayout.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/Routes.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/entry.client.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/entry.server.tsx.template
  packages/router/src/dummyComponent.ts
  packages/vite/package.json
  packages/vite/src/ClientRouter.tsx
  packages/vite/src/ServerRouter.ts
  packages/vite/src/lib/entries.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-routes-auto-loader.ts
  packages/vite/src/plugins/vite-plugin-rsc-routes-imports.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/tsconfig.json
  tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
Labels: release:feature, changesets-ok

#10666 RSC: Remove commented code related to prefixToRemove transform()
  packages/vite/src/rsc/rscWorker.ts
Labels: release:chore, changesets-ok

#10667 RSC: kitchen-sink: Make the ReadFileServerCell output take up less space
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/ReadFileServerCell/ReadFileServerCell.tsx
Labels: release:chore, changesets-ok

#10669 RSC: worker: getFunctionComponent -> getRoutesComponent
  packages/vite/src/rsc/rscWorker.ts
Labels: release:chore, changesets-ok

#10670 RSC: clientSsr: getServerEntryComponent()
  packages/vite/src/clientSsr.ts
Labels: release:chore, changesets-ok

#10671 RSC: rscBuildEntriesFile: Only ServerEntry and Routes needed for serverEntries
  packages/vite/src/rsc/rscBuildEntriesFile.ts
Labels: release:chore, changesets-ok

#10673 chore(crwa): Remove unused jest dev dependency
  packages/create-redwood-app/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10672 RSC: routes-auto-loader is not used for SSR anymore
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-routes-auto-loader.ts
Labels: release:chore, changesets-ok

#10675 fix(cli): Correct baremetal deploy command construction
  .changesets/10675.md
  packages/cli/src/commands/deploy/baremetal/SshExecutor.js
Labels: release:fix

#10676 RSC: clientSsr changes to make usage more clear
  packages/vite/src/clientSsr.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.mts
Labels: release:chore, changesets-ok

#10674 chore(router): switch to vitest
  packages/router/jest.setup.ts
  packages/router/package.json
  packages/router/src/PageLoadingContext.tsx
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/__tests__/history.test.tsx
  packages/router/src/__tests__/links.test.tsx
  packages/router/src/__tests__/location.test.tsx
  packages/router/src/__tests__/nestedSets.test.tsx
  packages/router/src/__tests__/pageLoadingContext.test.tsx
  packages/router/src/__tests__/redirect.test.tsx
  packages/router/src/__tests__/route-announcer.test.tsx
  packages/router/src/__tests__/route-focus.test.tsx
  packages/router/src/__tests__/route-validators.test.tsx
  packages/router/src/__tests__/routeScrollReset.test.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/__tests__/setContextReuse.test.tsx
  packages/router/src/__tests__/useMatch.test.tsx
  packages/router/src/__tests__/useRoutePaths.test.tsx
  packages/router/src/__tests__/util.test.ts
  packages/router/src/link.tsx
  packages/router/src/navLink.tsx
  packages/router/vitest.config.mts
  packages/router/vitest.setup.mts
  yarn.lock
Labels: release:chore, changesets-ok

#10677 In useOgImage() hook adds searchParams option for setting arbitrary query string vars to generated URL
  .changesets/10677.md
  packages/ogimage-gen/src/hooks.test.ts
  packages/ogimage-gen/src/hooks.ts
Labels: release:feature

#10646 fix: Serverless Deployment provider packs correctly
  .changesets/10646.md
  packages/cli/src/commands/deploy/packing/nft.js
Labels: release:fix

#10679 docs: update useAuth import in Supabase how-to
  docs/docs/how-to/supabase-auth.md
Labels: topic/docs, release:docs, changesets-ok

#10681 RSC: Better typings for acorn-loose usage
  packages/vite/modules.d.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-client.ts
Labels: release:chore, changesets-ok

#10682 RSC: Support CJS 'use client' modules
  packages/vite/src/lib/registerFwGlobalsAndShims.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-client.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-transform-client.ts
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:fix, changesets-ok

#10683 RSC: Support CJS 'use client' modules
  packages/vite/src/plugins/vite-plugin-rsc-transform-client.ts
Labels: release:chore, changesets-ok

#10684 RSC: client side navigation
  packages/vite/src/ClientRouter.tsx
Labels: release:chore, changesets-ok

#10680 chore: Adds pageIdentifier to route manifest
  .changesets/10680.md
  packages/internal/src/routes.ts
  packages/structure/src/model/__tests__/__snapshots__/model.test.ts.snap
  packages/structure/src/model/__tests__/model.test.ts
  packages/vite/src/buildRouteManifest.ts
Labels: release:chore

#10686 RSC: Cache client side navigation
  packages/vite/src/ClientRouter.tsx
Labels: release:feature, changesets-ok

#10687 chore(supabase-mw): Return tuple from initSupabaseMw to prevent accidental misconfiguration
  packages/auth-providers/supabase/middleware/README.md
  packages/auth-providers/supabase/middleware/src/__tests__/createSupabaseAuthMiddleware.test.ts
  packages/auth-providers/supabase/middleware/src/index.ts
Labels: release:chore, changesets-ok

#10690 fix(deps) Temporary fix for broken @swc/types package publishing
  .changesets/10690.md
  __fixtures__/fragment-test-project/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
Labels: release:fix

#10689 RSC: Extract fetchRsc out into its own file
  packages/vite/src/ClientRouter.tsx
  packages/vite/src/rsc/rscFetchForClientRouter.tsx
Labels: release:chore, changesets-ok

#10692 chore(comments): Explain how class components work >.<
  packages/router/src/location.tsx
Labels: release:chore, changesets-ok

#10695 RSC: kitchen-sink: Use `<Link>` from @redwoodjs/router
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/EmptyUser/EmptyUsersCell/EmptyUsersCell.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/NavigationLayout/NavigationLayout.tsx
Labels: release:chore, changesets-ok

#10696 RSC: kitchen-sink: Fix css pixels unit
  __fixtures__/test-project-rsc-kitchen-sink/web/src/components/ReadFileServerCell/ReadFileServerCell.tsx
Labels: release:chore, fixture-ok, changesets-ok

#10698 fix(cli): Directive generator command was not creating files
  .changesets/10698.md
  packages/cli/src/commands/generate/directive/directive.js
Labels: topic/generators-&-scaffolds, topic/cli, release:fix

#10699 chore(testing): Remove unused member in Props interface
  packages/testing/src/web/MockParamsProvider.tsx
Labels: release:chore, changesets-ok

#10664 Use Replay for smoke tests
  .github/workflows/ci.yml
  package.json
  tasks/smoke-tests/basePlaywright.config.ts
  tasks/smoke-tests/smoke-tests.mjs
  yarn.lock
Labels: release:chore, changesets-ok

#10702 docs: Clarify how to setup Docker with custom Server File
  .changesets/10702.md
  docs/docs/docker.md
  packages/cli/src/commands/experimental/templates/docker/Dockerfile
  packages/cli/src/commands/experimental/templates/docker/docker-compose.prod.yml
Labels: release:fix, topic/docker

#10705 Cleanup `DISABLE_REPLAY_UPLOAD` logic
  .github/workflows/ci.yml
  tasks/smoke-tests/basePlaywright.config.ts
Labels: release:chore, changesets-ok

#10708 Revert "Use Replay for smoke tests (#10664)"
  .github/workflows/ci.yml
  package.json
  tasks/smoke-tests/basePlaywright.config.ts
  tasks/smoke-tests/smoke-tests.mjs
  yarn.lock
Labels: release:chore, changesets-ok

#10697 feat(serverStore): Add location to serverStore for RSCs to access location
  .changesets/10697.md
  packages/vite/src/devFeServer.ts
  packages/vite/src/rsc/rscFetchForClientRouter.tsx
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscStudioHandlers.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/serverStore.ts
  packages/vite/src/utils.ts
Labels: release:feature

#10706 chore(auth): Fix auth build
  packages/prerender/tsconfig.json
  packages/router/tsconfig.json
  packages/testing/tsconfig.json
  packages/web/tsconfig.json
  tasks/clean.mjs
  tasks/framework-tools/frameworkSyncToProject.mjs
Labels: release:chore, changesets-ok

#10656 feat(rsc-auth): Implement getRoles function in auth mw & update default ServerAuthState
  .changesets/10656.md
  packages/auth-providers/dbAuth/middleware/README.md
  packages/auth-providers/dbAuth/middleware/src/__tests__/defaultGetRoles.test.ts
  packages/auth-providers/dbAuth/middleware/src/__tests__/initDbAuthMiddleware.test.ts
  packages/auth-providers/dbAuth/middleware/src/defaultGetRoles.ts
  packages/auth-providers/dbAuth/middleware/src/index.ts
  packages/auth-providers/supabase/middleware/README.md
  packages/auth-providers/supabase/middleware/src/__tests__/defaultGetRoles.test.ts
  packages/auth-providers/supabase/middleware/src/__tests__/initSupabaseAuthMiddleware.test.ts
  packages/auth-providers/supabase/middleware/src/defaultGetRoles.ts
  packages/auth-providers/supabase/middleware/src/index.ts
  packages/auth-providers/supabase/middleware/src/util.ts
  packages/auth/src/AuthProvider/ServerAuthProvider.tsx
  packages/graphql-server/src/types.ts
  packages/ogimage-gen/empty.js
  packages/ogimage-gen/package.json
  packages/router/src/location.tsx
  packages/vite/src/lib/getMergedConfig.ts
  packages/vite/src/middleware/MiddlewareRequest.test.ts
  packages/vite/src/middleware/MiddlewareRequest.ts
  packages/vite/src/middleware/invokeMiddleware.test.ts
  packages/vite/src/middleware/invokeMiddleware.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/web/src/apollo/links.tsx
Labels: release:feature

#10709 chore(build) reference auth.tsconfig.build
  packages/auth-providers/auth0/web/tsconfig.json
  packages/auth-providers/azureActiveDirectory/web/tsconfig.json
  packages/auth-providers/clerk/web/tsconfig.json
  packages/auth-providers/dbAuth/api/tsconfig.json
  packages/auth-providers/dbAuth/middleware/tsconfig.json
  packages/auth-providers/dbAuth/web/tsconfig.json
  packages/auth-providers/firebase/web/tsconfig.json
  packages/auth-providers/netlify/web/tsconfig.json
  packages/auth-providers/supabase/api/tsconfig.json
  packages/auth-providers/supabase/middleware/tsconfig.json
  packages/auth-providers/supabase/web/tsconfig.json
  packages/auth-providers/supertokens/web/tsconfig.json
Labels: release:chore, changesets-ok

#10710 chore: spelling, comment
  packages/auth/src/AuthProvider/AuthProvider.tsx
  packages/cli/src/commands/serveBothHandler.js
  packages/vite/src/clientSsr.ts
Labels: release:chore, changesets-ok

#10711 chore(exports): Separate export for ServerAuthProvider
  packages/auth/package.json
  packages/auth/src/index.ts
  packages/vite/src/middleware/MiddlewareRequest.ts
  packages/vite/src/middleware/invokeMiddleware.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
  packages/vite/src/serverStore.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/web/src/apollo/suspense.tsx
Labels: release:chore, changesets-ok

#10712 chore(auth): Separate AuthProviderState export
  packages/auth/package.json
  packages/auth/src/index.ts
  packages/vite/src/middleware/MiddlewareRequest.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
Labels: release:chore, changesets-ok

#10713 chore(vite): dist imports from router
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/triggerRouteHooks.ts
Labels: release:chore, changesets-ok

#10714 chore(ServerInject): Named imports and source format
  packages/web/src/components/ServerInject.tsx
Labels: release:chore, changesets-ok
