Repository redwoodjs/graphql, pull requests merged in 2024-06, with the labels that each got.

#10718 fix(deps): Remove @swc/core resolution
  .changesets/10718.md
  __fixtures__/fragment-test-project/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
Labels: release:fix

#10719 chore(auth): auth-supabase-api dependency fixes
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/api/tsconfig.json
Labels: release:chore, changesets-ok

#10721 chore(imports): Differentiate between React type import and method imports
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:chore, changesets-ok

#10723 chore(logging): Remove overly verbose logging
  packages/vite/src/clientSsr.ts
Labels: release:chore, changesets-ok

#10688 RSC: Include `<App>` in SSR
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveBothHandler.js
  packages/cli/src/commands/serveWebHandler.js
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/vite/package.json
  packages/vite/src/SsrRouter.tsx
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRscClientAndServer.ts
  packages/vite/src/clientSsr.ts
  packages/vite/src/middleware/register.ts
  packages/vite/src/plugins/vite-plugin-rsc-routes-auto-loader.ts
  packages/vite/src/plugins/vite-plugin-rsc-ssr-router-import.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildCopyCssAssets.ts
  packages/vite/src/rsc/rscBuildEntriesFile.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscBuildForSsr.ts
  packages/vite/src/rsc/rscBuildRwEnvVars.ts
  packages/vite/src/streaming/buildForStreamingServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/vite/src/streaming/transforms/serverInjectionTransform.ts
Labels: release:feature, changesets-ok

#10727 chore(ci): Track `@redwoodjs/router` in RSC CI
  .github/actions/detect-changes/cases/rsc.mjs
Labels: release:chore, changesets-ok

#10730 chore(yarn): Remove studio workspace reference
  package.json
Labels: release:chore, changesets-ok

#10731 chore(ci): Fix set-up-job description
  .github/actions/set-up-job/action.yml
Labels: release:chore, changesets-ok

#10732 chore(formatting): Fix "check annotations" in mock-router
  packages/storybook/src/plugins/mock-router.ts
Labels: release:chore, changesets-ok

#10729 Run smoke-tests on React 18 too
  .github/workflows/ci.yml
  packages/web/apollo/package.json
  tasks/downgradeToReact18.mts
  tasks/tsconfig.json
Labels: release:chore, changesets-ok

#10733 RSC: Remove forbidden non-null assertion
  packages/vite/src/lib/getMergedConfig.ts
Labels: release:chore, changesets-ok

#10344 feat(tw): Add IntelliSense settings for Tailwind CSS VS Code plugin
  .changesets/10344.md
  __fixtures__/test-project/.vscode/settings.json
  packages/cli/src/commands/setup/ui/__tests__/tailwindcss.test.ts
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
Labels: release:feature

#10736 fix(og-mw-setup): Fix typo in notes for og-middleware setup
  packages/cli/src/commands/setup/middleware/ogImage/ogImageHandler.ts
Labels: release:fix, changesets-ok

#10734 chore(auth): add password validation to dbAuth resetPassword handler
  .changesets/10734.md
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
Labels: bug/confirmed, release:fix, fixture-ok

#10738 chore(release): Remove old changeset entries
  .changesets/10054.md
  .changesets/10151.md
  .changesets/10152.md
  .changesets/10160.md
  .changesets/10204.md
  .changesets/10231.md
  .changesets/10265.md
  .changesets/10280.md
  .changesets/10335.md
  .changesets/10355.md
  .changesets/10359.md
  .changesets/10374.md
  .changesets/10376.md
  .changesets/10442.md
  .changesets/10479.md
  .changesets/10504.md
  .changesets/10510.md
  .changesets/10515.md
  .changesets/10518.md
  .changesets/10525.md
  .changesets/10527.md
  .changesets/10551.md
  .changesets/10555.md
  .changesets/10556.md
  .changesets/10561.md
  .changesets/10574.md
  .changesets/10646.md
  .changesets/10651.md
  .changesets/10663.md
  .changesets/10675.md
  .changesets/10690.md
  .changesets/10698.md
  .changesets/10718.md
Labels: release:chore, changesets-ok

#10573 feat: add customize content type parsers for api plugin
  .changesets/10573.md
  __fixtures__/test-project/web/package.json
  docs/docs/docker.md
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/createServer.ts
  packages/api-server/src/createServerHelpers.ts
  packages/api-server/src/plugins/api.ts
Labels: release:feature

#10717 Update oauth.md | Small typoe on react code
  docs/docs/how-to/oauth.md
Labels: release:docs, changesets-ok

#10740 chore(rename): Rename output to distSsr
  packages/ogimage-gen/src/OgImageMiddleware.test.ts
  packages/ogimage-gen/src/OgImageMiddleware.ts
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/vite/src/buildRouteManifest.ts
  packages/vite/src/clientSsr.ts
  packages/vite/src/middleware/createMiddlewareRouter.test.ts
  packages/vite/src/middleware/register.ts
  packages/vite/src/rsc/rscBuildEntriesFile.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscBuildForSsr.ts
  packages/vite/src/streaming/buildForStreamingServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:chore, changesets-ok

#10741 chore(client-entry): Slight tweaks around entry.client handling
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildForSsr.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:chore, changesets-ok

#10742 RSC: Add `<App>` to kitchen-sink test project
  __fixtures__/test-project-rsc-kitchen-sink/web/src/entry.server.tsx
Labels: release:chore, changesets-ok

#10744 RSC: Rename dist/client to dist/browser
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/vite/src/buildRouteManifest.ts
  packages/vite/src/clientSsr.ts
  packages/vite/src/lib/getMergedConfig.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildCopyCssAssets.ts
  packages/vite/src/rsc/rscBuildEntriesFile.ts
  packages/vite/src/rsc/rscCss.ts
  packages/vite/src/runFeServer.ts
Labels: release:chore, changesets-ok

#10743 RSC: Remove redundant code in register.ts
  packages/vite/src/middleware/register.ts
Labels: release:chore, changesets-ok

#10749 chore(tasks): Switch target react version in downgrade script
  tasks/downgradeToReact18.mts
Labels: release:chore, changesets-ok

#10750 RSC: Silence unsupported-dynamic-import warning
  packages/vite/src/rsc/rscBuildForSsr.ts
Labels: release:fix, changesets-ok

#10746 chore(deps): Switch to smol-toml
  packages/cli-helpers/package.json
  packages/cli-helpers/src/lib/__tests__/__snapshots__/project.test.ts.snap
  packages/cli-helpers/src/lib/__tests__/project.test.ts
  packages/cli-helpers/src/lib/project.ts
  packages/cli/package.json
  packages/cli/src/commands/deploy/baremetal.js
  packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
  packages/codemods/package.json
  packages/project-config/package.json
  packages/project-config/src/config.ts
  packages/structure/package.json
  packages/structure/src/model/RWTOML.ts
  yarn.lock
Labels: release:chore, changesets-ok

#10739 Updates seeds script to be generic, no more errors throw on first run
  .changesets/10739.md
  __fixtures__/empty-project/scripts/seed.ts
  __fixtures__/fragment-test-project/scripts/seed.ts
  __fixtures__/test-project-rsa/scripts/seed.ts
  __fixtures__/test-project/scripts/seed.ts
  docs/docs/database-seeds.md
  docs/sidebars.js
  packages/create-redwood-app/templates/js/scripts/seed.js
  packages/create-redwood-app/templates/ts/scripts/seed.ts
Labels: topic/docs, topic/prisma, release:fix

#10747 feat(cli): Notices for vite storybook command
  packages/cli-packages/storybook-vite/src/commands/storybookHandler.ts
  packages/cli-packages/storybook/src/commands/storybookHandler.ts
Labels: release:feature, changesets-ok

#10753 RSC: Externalize more modules during build
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildForSsr.ts
Labels: release:feature, changesets-ok

#10755 chore(spelling): Fix some spelling mistakes in vite/middleware
  packages/vite/src/middleware/MiddlewareRequest.ts
  packages/vite/src/middleware/MiddlewareResponse.ts
Labels: release:chore, changesets-ok

#10756 @redwoodjs/server-store and @redwoodjs/cookie-jar
  packages/cookie-jar/README.md
  packages/cookie-jar/build.mts
  packages/cookie-jar/package.json
  packages/cookie-jar/src/CookieJar.test.ts
  packages/cookie-jar/src/CookieJar.ts
  packages/cookie-jar/tsconfig.json
  packages/server-store/README.md
  packages/server-store/build.mts
  packages/server-store/package.json
  packages/server-store/src/serverStore.ts
  packages/server-store/tsconfig.json
  packages/vite/package.json
  packages/vite/src/devFeServer.ts
  packages/vite/src/middleware/MiddlewareRequest.ts
  packages/vite/src/middleware/MiddlewareResponse.ts
  packages/vite/src/middleware/index.ts
  packages/vite/src/middleware/invokeMiddleware.test.ts
  packages/vite/src/middleware/invokeMiddleware.ts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscBuildForSsr.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscStudioHandlers.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/runFeServer.ts
  packages/vite/tsconfig.json
  yarn.lock
Labels: release:chore, changesets-ok

#10760 RSC: Wrap App around Routes in ServerEntry
  __fixtures__/test-project-rsa/web/src/entry.server.tsx
  packages/cli/src/commands/experimental/templates/rsc/entry.server.tsx.template
Labels: release:chore, changesets-ok

#10759 RSC: getLocation in ServerRouter
  __fixtures__/test-project-rsa/web/src/entry.server.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/entry.server.tsx
  packages/cli/src/commands/experimental/templates/rsc/entry.server.tsx.template
  packages/router/package.json
  packages/router/src/server-router.tsx
  packages/router/tsconfig.json
  yarn.lock
Labels: release:feature, changesets-ok

#10716 Updates to the FlightControl deployment
  docs/docs/deploy/flightcontrol.md
Labels: release:docs, changesets-ok

#10761 feat(cli): react compiler lint only setting
  .changesets/10761.md
  packages/babel-config/src/web.ts
  packages/cli/src/commands/experimental/setupReactCompilerHandler.js
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/config.ts
Labels: release:feature

#10763 chore(graphql-server): Fix ts-refs, a comment and imports
  packages/graphql-server/src/rootSchema.ts
  packages/graphql-server/tsconfig.json
Labels: release:chore, changesets-ok

#10764 fix: smol-toml imports
  packages/cli-helpers/src/lib/project.ts
  packages/cli/src/commands/deploy/baremetal.js
  packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
  packages/project-config/src/config.ts
  packages/structure/src/model/RWTOML.ts
Labels: release:fix, changesets-ok

#10765 RSC: externalize modules for dbAuth
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscBuildForSsr.ts
Labels: release:fix, changesets-ok

#10766 RSC: Add 'use client' to auth templates
  packages/auth-providers/auth0/setup/src/templates/web/auth.rsc.ts.template
  packages/auth-providers/azureActiveDirectory/setup/src/templates/web/auth.rsc.ts.template
  packages/auth-providers/clerk/setup/src/templates/web/auth.rsc.tsx.template
  packages/auth-providers/custom/setup/src/templates/web/auth.rsc.ts.template
  packages/auth-providers/dbAuth/setup/src/templates/web/auth.rsc.ts.template
  packages/auth-providers/dbAuth/setup/src/templates/web/auth.webAuthn.rsc.ts.template
  packages/auth-providers/firebase/setup/src/templates/web/auth.rsc.ts.template
  packages/auth-providers/netlify/setup/src/templates/web/auth.rsc.ts.template
  packages/auth-providers/supabase/setup/src/templates/web/auth.rsc.ts.template
  packages/auth-providers/supertokens/setup/src/templates/web/auth.rsc.tsx.template
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/__tests__/setupHelpers.test.ts
  packages/cli-helpers/src/auth/authTasks.ts
Labels: release:feature, changesets-ok

#10767 chore(naming): Rename variable to match usage
  .vscode/settings.json
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.mts
Labels: release:chore, changesets-ok

#10769 chore: upgrade TSTyche to v2
  package.json
  packages/router/package.json
  packages/router/src/__typetests__/routeParamsTypes.test.ts
  packages/web/package.json
  packages/web/src/__typetests__/cellProps.test.tsx
  packages/web/src/__typetests__/cellSuccessData.test.tsx
  yarn.lock
Labels: release:chore, changesets-ok

#10788 fix(dbauth): Combine react imports
  .changesets/10788.md
  __fixtures__/test-project/web/src/pages/LoginPage/LoginPage.tsx
  __fixtures__/test-project/web/src/pages/SignupPage/SignupPage.tsx
  packages/auth-providers/dbAuth/middleware/src/index.ts
  packages/cli/src/commands/generate/dbAuth/__tests__/__snapshots__/dbAuth.test.js.snap
  packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/login.webAuthn.tsx.template
  packages/cli/src/commands/generate/dbAuth/templates/signup.tsx.template
  packages/vite/src/middleware/invokeMiddleware.ts
Labels: release:fix

#10791 fix(dbauth): Don't duplicate authDecoder creation
  .changesets/10791.md
  packages/auth-providers/dbAuth/setup/jest.config.js
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/setup/src/__tests__/__snapshots__/setup.test.ts.snap
  packages/auth-providers/dbAuth/setup/src/__tests__/setup.test.ts
  packages/auth-providers/dbAuth/setup/src/setupHandler.ts
  yarn.lock
Labels: release:fix

#10811 fix(dbauth): Fix spacing issue in task titles
  .changesets/10811.md
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.mockListr.test.js
  packages/cli/src/commands/generate/dbAuth/dbAuth.js
Labels: release:fix

#10813 fix(dbAuth): Print the correct "post message" after generation
  .changesets/10813.md
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
  packages/cli/src/commands/generate/dbAuth/dbAuth.js
Labels: release:fix

#10814 chore(dbAuth): Fix test for webauthn prompt in `g dbAuth`
  packages/cli/src/commands/generate/dbAuth/__tests__/__snapshots__/dbAuth.test.js.snap
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
Labels: release:chore, changesets-ok

#10793 feat(dbAuth): Only suggest dbAuth setup if needed
  .changesets/10793.md
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.postInstallMessage.test.js
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
  packages/cli/src/commands/generate/dbAuth/dbAuth.js
Labels: release:feature

#10818 chore(testing dbAuth): provide mock implementations
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
Labels: release:chore, changesets-ok

#10819 chore(testing dbAuth): Consistent naming and fix blue squiggles
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
Labels: release:chore, changesets-ok

#10820 chore(testing dbAuth): Remove outdated code
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
Labels: release:chore, changesets-ok

#10822 chore(testing dbAuth): Remove duplicated tests
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.mockListr.test.js
Labels: release:chore, changesets-ok

#10821 chore(testing dbAuth): Mock console.log to silence test output
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.mockListr.test.js
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
Labels: release:chore, changesets-ok

#10823 chore(testing dbAuth): Add "yes" prompt testing for WebAuthn
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.mockListr.test.js
Labels: release:chore, changesets-ok

#10830 fix(cli): Add check for excessively long route
  .changesets/10830.md
  packages/cli/src/lib/index.js
Labels: release:fix

#10832 chore(fixtures): change redwood versions in fixtures
  __fixtures__/empty-project/api/package.json
  __fixtures__/empty-project/package.json
  __fixtures__/empty-project/web/package.json
  __fixtures__/example-todo-main-with-errors/api/package.json
  __fixtures__/example-todo-main-with-errors/package.json
  __fixtures__/example-todo-main-with-errors/web/package.json
  __fixtures__/example-todo-main/api/package.json
  __fixtures__/example-todo-main/package.json
  __fixtures__/example-todo-main/web/package.json
Labels: release:chore, changesets-ok

#10840 chore(deps): bump ws (docs)
  docs/yarn.lock
Labels: release:chore, changesets-ok

#10839 chore(deps): bump ws
  yarn.lock
Labels: release:chore, changesets-ok

#10838 chore(deps): bump semver to 5.7.2
  yarn.lock
Labels: release:chore, changesets-ok

#10842 chore(fixtures): use canary instead of latest
  __fixtures__/empty-project/api/package.json
  __fixtures__/empty-project/package.json
  __fixtures__/empty-project/web/package.json
  __fixtures__/example-todo-main-with-errors/api/package.json
  __fixtures__/example-todo-main-with-errors/package.json
  __fixtures__/example-todo-main-with-errors/web/package.json
  __fixtures__/example-todo-main/api/package.json
  __fixtures__/example-todo-main/package.json
  __fixtures__/example-todo-main/web/package.json
Labels: release:chore, changesets-ok

#10841 chore(cli): switch from `param-case` to `change-case`
  packages/cli/package.json
  packages/cli/src/commands/generate/dataMigration/dataMigration.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/lib/index.js
  yarn.lock
Labels: release:chore, changesets-ok

#10745 Small edits on the trusted documents page
  docs/docs/graphql/trusted-documents.md
Labels: topic/docs, release:docs, changesets-ok, contributor-pr

#10858 chore(ci): do not enforce changeset entry for certain milestones
  .github/actions/check_changesets/check_changesets.mjs
  .github/workflows/check-changelog.yml
Labels: release:chore

#10849 feat(dbAuth): Prompt for creating User table
  .changesets/10849.md
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/setup/src/__tests__/setup.test.ts
  packages/auth-providers/dbAuth/setup/src/__tests__/setupData.test.ts
  packages/auth-providers/dbAuth/setup/src/__tests__/setupDataMockDMMF.test.ts
  packages/auth-providers/dbAuth/setup/src/setup.ts
  packages/auth-providers/dbAuth/setup/src/setupData.ts
  packages/auth-providers/dbAuth/setup/src/setupHandler.ts
  packages/auth-providers/dbAuth/setup/src/shared.ts
  packages/auth-providers/dbAuth/setup/src/webAuthn.setupData.ts
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/authTasks.ts
  packages/cli-helpers/src/auth/setupHelpers.ts
  packages/cli/src/commands/setup/auth/auth.js
  yarn.lock
Labels: release:feature

#10860 chore: fix deps
  packages/auth-providers/dbAuth/setup/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10863 fix(docs): Update url for new docs subdomain
  docs/docusaurus.config.ts
Labels: release:fix, changesets-ok

#10827 docs(directives): Removes outdated mockAsyncRedwoodDirective and explains how to test async directives
  .changesets/10827.md
  docs/docs/directives.md
Labels: release:docs

#10817 fix(auth): Allows RedwoodAuthCurrentUserQuery when using Auth, GraphQL and Trusted Documents
  .changesets/10817.md
  packages/graphql-server/src/plugins/useRedwoodTrustedDocuments.ts
Labels: release:fix

#10864 feat(g dbAuth): Detect WebAuthn support
  .changesets/10864.md
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.mockListr.test.js
  packages/cli/src/commands/generate/dbAuth/dbAuth.js
  packages/cli/src/lib/test.js
Labels: release:feature

#10865 feat(dbAuth): Prompt to generate dbAuth pages
  .changesets/10865.md
  packages/auth-providers/dbAuth/setup/src/__tests__/setup.test.ts
  packages/auth-providers/dbAuth/setup/src/setup.ts
  packages/auth-providers/dbAuth/setup/src/setupData.ts
  packages/auth-providers/dbAuth/setup/src/setupHandler.ts
  packages/auth-providers/dbAuth/setup/src/shared.ts
  packages/auth-providers/dbAuth/setup/src/webAuthn.setupData.ts
  packages/cli-helpers/src/auth/setupHelpers.ts
  packages/cli-helpers/src/index.ts
  packages/cli/src/commands/setup/auth/auth.js
Labels: release:feature

#10871 feat(dbAuth): Automatically create User model in fresh projects
  .changesets/10871.md
  packages/auth-providers/dbAuth/setup/src/__tests__/setup.test.ts
  packages/auth-providers/dbAuth/setup/src/__tests__/setupDataMockDMMF.test.ts
  packages/auth-providers/dbAuth/setup/src/setupHandler.ts
  packages/auth-providers/dbAuth/setup/src/shared.ts
  tasks/test-project/tui-tasks.js
Labels: release:feature

#10826 chore(esm/cjs): Build rwjs/web to cjs with new build system
  .eslintrc.js
  packages/cli/src/commands/setup/custom-web-index/custom-web-index-handler.js
  packages/forms/src/FormError.tsx
  packages/framework-tools/src/buildDefaults.ts
  packages/router/src/rsc-link.tsx
  packages/vite/src/plugins/vite-plugin-remove-from-bundle.ts
  packages/web/build.mts
  packages/web/package.json
  packages/web/src/apollo/index.tsx
  packages/web/src/apollo/links.ts
  packages/web/src/apollo/sseLink.ts
  packages/web/src/apollo/suspense.tsx
  packages/web/src/apollo/useCache.ts
  packages/web/src/components/DevFatalErrorPage.tsx
  packages/web/src/components/FatalErrorBoundary.tsx
  packages/web/src/components/GraphQLHooksProvider.tsx
  packages/web/src/components/MetaTags.tsx
  packages/web/src/components/RedwoodProvider.tsx
  packages/web/src/components/cell/createCell.tsx
  packages/web/src/components/cell/createServerCell.tsx
  packages/web/src/components/cell/createSuspendingCell.tsx
  packages/web/src/components/cell/isCellEmpty.ts
  packages/web/src/components/htmlTags.tsx
  packages/web/src/entry/index.jsx
  yarn.lock
Labels: release:chore, changesets-ok

#10874 feat(router): Navigate to splash page using routes.home()
  .changesets/10874.md
  packages/internal/src/generate/typeDefinitions.ts
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/analyzeRoutes.ts
  packages/router/src/router.tsx
  packages/router/src/server-router.tsx
Labels: release:feature

#10878 chore(eslint-config): Remove `jest` devDep
  packages/eslint-config/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10859 remove(cli): Remove deprecated deploy providers
  .changesets/10859.md
  packages/cli/src/commands/deploy/edgio.js
  packages/cli/src/commands/deploy/serverless.js
  packages/cli/src/commands/setup/deploy/providers/edgio.js
  packages/cli/src/commands/setup/deploy/providers/serverless.js
  packages/cli/src/commands/setup/deploy/templates/serverless/api.js
  packages/cli/src/commands/setup/deploy/templates/serverless/web.js
Labels: release:breaking

#10882 fix(dbAuth): Generate types to make `routes.pageName()` work
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
  packages/cli/src/commands/generate/dbAuth/dbAuth.js
Labels: release:fix, changesets-ok

#10889 fix(dbauth): multiValueHeaders
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/buildDbAuthResponse.test.ts
  packages/auth-providers/dbAuth/api/src/shared.ts
Labels: release:fix

#10868 Convert @redwoodjs/web to ESM/CJS dual package
  packages/core/config/webpack.common.js
  packages/internal/src/generate/typeDefinitions.ts
  packages/prerender/src/graphql/graphql.ts
  packages/testing/config/jest/web/jest-preset.js
  packages/testing/config/storybook/main.js
  packages/vite/package.json
  packages/vite/src/devFeServer.ts
  packages/vite/src/index.ts
  packages/vite/src/rsc/rscBuildForSsr.ts
  packages/vite/src/streaming/buildForStreamingServer.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/web/apollo/index.js
  packages/web/build.mts
  packages/web/package.json
  packages/web/src/__typetests__/cellProps.test.tsx
  packages/web/src/apollo/fragmentRegistry.ts
  packages/web/src/apollo/index.tsx
  packages/web/src/apollo/links.ts
  packages/web/src/apollo/sseLink.ts
  packages/web/src/apollo/suspense.tsx
  packages/web/src/apollo/useCache.ts
  packages/web/src/assetImports.ts
  packages/web/src/components/DevFatalErrorPage.tsx
  packages/web/src/components/FatalErrorBoundary.tsx
  packages/web/src/components/MetaTags.tsx
  packages/web/src/components/Metadata.tsx
  packages/web/src/components/RedwoodProvider.tsx
  packages/web/src/components/__tests__/GraphQLHooksProvider.test.tsx
  packages/web/src/components/cell/createSuspendingCell.test.tsx
  packages/web/src/components/cell/createSuspendingCell.tsx
  packages/web/src/index.ts
  packages/web/tsconfig.json
  packages/web/tsconfig.types-cjs.json
  packages/web/vitest.config.mts
  yarn.lock
Labels: release:chore

#10888 fix(prerender): Fold output to prevent crashing on large prerender counts
  .changesets/10888.md
  packages/cli/src/commands/prerenderHandler.js
Labels: release:fix

#10825 fix: Fixes support for Mocking GraphQL Queries in Storybook when using GraphQL Fragments
  .changesets/10825.md
  __fixtures__/test-project/web/src/components/AuthorCell/AuthorCell.mock.ts
  __fixtures__/test-project/web/src/components/BlogPostCell/BlogPostCell.mock.ts
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.mock.ts
  __fixtures__/test-project/web/src/components/WaterfallBlogPostCell/WaterfallBlogPostCell.mock.ts
  docs/docs/graphql/fragments.md
  docs/docs/graphql/mocking-graphql-requests.md
  docs/docs/testing.md
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/cell/templates/mock.ts.template
  packages/cli/src/commands/generate/cell/templates/mockList.js.template
  packages/cli/src/commands/generate/cell/templates/mockList.ts.template
Labels: release:fix
