Repository redwoodjs/graphql, pull requests merged in 2024-03, with the labels that each got.

#10081 chore: remove release tooling
  CONTRIBUTING.md
  package.json
  tasks/all-contributors/README.md
  tasks/release/.gitignore
  tasks/release/compare/compare.mjs
  tasks/release/compare/compareQA.mjs
  tasks/release/generateReleaseNotes.mjs
  tasks/release/jest.config.js
  tasks/release/release.mjs
  tasks/release/releaseLib.mjs
  tasks/release/tests/__snapshots__/release.test.mjs.snap
  tasks/release/tests/annotatedSymmetricDifference.json
  tasks/release/tests/release.test.mjs
  tasks/release/tests/releaseLibQA.mjs
  tasks/release/tests/releaseMock.test.mjs
  tasks/release/tests/setUpDataFileTest.mjs
  tasks/release/tests/test.commitTriageData.json
  tasks/release/triage/triage.mjs
  tasks/release/triage/triageQA.mjs
Labels: release:chore, changelog-ok

#10083 fix(esm): fix initial esm blockers for redwood apps
  CHANGELOG.md
  packages/api-server/src/__tests__/lambdaLoaderNumberFunctions.test.ts
  packages/api-server/src/plugins/lambdaLoader.ts
  packages/babel-config/src/__tests__/__fixtures__/redwood-app/package.json
  packages/babel-config/src/api.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-context-wrapping.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-import-dir.ts
  packages/cli-packages/dataMigrate/src/__tests__/upHandler.test.ts
  packages/graphql-server/build.mts
  packages/graphql-server/package.json
  packages/internal/src/build/api.ts
  packages/project-config/src/__tests__/esmHelpers.test.ts
  packages/project-config/src/__tests__/fixtures/esm-api-only/api/package.json
  packages/project-config/src/__tests__/fixtures/esm-api-only/package.json
  packages/project-config/src/__tests__/fixtures/esm-api-only/redwood.toml
  packages/project-config/src/__tests__/fixtures/esm-api-only/web/package.json
  packages/project-config/src/__tests__/fixtures/esm/api/package.json
  packages/project-config/src/__tests__/fixtures/esm/package.json
  packages/project-config/src/__tests__/fixtures/esm/redwood.toml
  packages/project-config/src/__tests__/fixtures/esm/web/package.json
  packages/project-config/src/paths.ts
  yarn.lock
Labels: release:fix

#10093 Iterate on `.env` file loading
  CHANGELOG.md
  __fixtures__/test-project/web/package.json
  packages/cli/src/__tests__/loadEnvFiles.test.js
  packages/cli/src/index.js
  packages/cli/src/lib/loadEnvFiles.js
  packages/cli/src/middleware/addAdditionalEnvFiles.js
  tasks/server-tests/bothServer.test.mts
Labels: release:fix

#10085 RSC: distRsc and distClient paths
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/vite/src/buildRouteManifest.ts
  packages/vite/src/fully-react/ProdRwRscServerGlobal.ts
  packages/vite/src/react-server-dom-webpack/node-loader.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildClientEntriesFile.ts
  packages/vite/src/rsc/rscBuildCopyCssAssets.ts
  packages/vite/src/rsc/rscBuildRwEnvVars.ts
  packages/vite/src/rsc/rscBuildServer.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
Labels: release:fix, fixture-ok, changelog-ok

#10095 chore: Removes logger specs from e2e tests
  .github/workflows/ci.yml
  tasks/e2e/cypress/e2e/04-logger/codemods/Step1_1_Setup_Logger.js
  tasks/e2e/cypress/e2e/04-logger/codemods/Step1_2_Add_Logger_to_Posts.js
  tasks/e2e/cypress/e2e/04-logger/codemods/Step2_1_Setup_Prisma_Logger.js
  tasks/e2e/cypress/e2e/04-logger/logger.cy.js
Labels: release:chore

#10098 RSC: smoke-tests: Compare text, not html
  tasks/smoke-tests/rsa/tests/rsa.spec.ts
  tasks/smoke-tests/rsc-external-packages-and-cells/tests/rsc-external-packages-and-cells.spec.ts
Labels: release:chore, changelog-ok

#10094 Iterate on `.env` files: make the behavior override
  CHANGELOG.md
  packages/cli/src/__tests__/loadEnvFiles.test.js
  packages/cli/src/index.js
  packages/cli/src/lib/loadEnvFiles.js
  tasks/server-tests/bothServer.test.mts
Labels: release:fix

#10097 chore(unit-tests): Silence middleware error logging
  packages/vite/src/middleware/invokeMiddleware.test.ts
Labels: release:chore, changelog-ok

#10099 SSR: Extract buildForStreamingServer function
  packages/vite/src/buildFeServer.ts
  packages/vite/src/streaming/buildForStreamingServer.ts
Labels: release:chore, changelog-ok

#10102 RSC: Rename to rscBuildForServer, and tweak some comments
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/rsc/rscBuildClientEntriesFile.ts
  packages/vite/src/rsc/rscBuildCopyCssAssets.ts
  packages/vite/src/rsc/rscBuildForServer.ts
Labels: release:chore, changelog-ok

#10103 RSC: Rename to buildRscClientAndServer
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRscClientAndServer.ts
Labels: release:chore, changelog-ok

#10104 RSC: Update comments, naming etc based on Danny's input
  packages/project-config/src/paths.ts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildClientEntriesFile.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscBuildRwEnvVars.ts
  packages/vite/src/rsc/rscVitePlugins.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
  packages/vite/src/runFeServer.ts
Labels: release:chore, changelog-ok

#10105 RSC: runFeServer: wrap RSC code with `if (rscEnabled)`
  packages/vite/src/runFeServer.ts
Labels: release:chore, changelog-ok

#10106 RSC: Babel react plugin not needed for analyze phase
  packages/vite/src/rsc/rscBuildAnalyze.ts
Labels: release:fix, changelog-ok

#10107 RSC: Extract webpack shims into their own file
  packages/vite/src/rsc/rscVitePlugins.ts
  packages/vite/src/rsc/rscWebpackShims.ts
Labels: release:chore, changelog-ok

#10108 RSC: ensureProcessDirWeb()
  packages/vite/src/rsc/rscBuildClient.ts
Labels: release:fix, changelog-ok

#10109 RSC: rscBuildAnalyze: Start at web/src/
  packages/vite/src/rsc/rscBuildAnalyze.ts
Labels: release:fix, changelog-ok

#10110 chore(refactor): vite - extract default vite config
  packages/vite/src/index.ts
  packages/vite/src/lib/envVarDefinitions.ts
  packages/vite/src/lib/getDefaultViteConfig.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildForServer.ts
Labels: release:chore, changelog-ok

#10111 chore(style): getDefaultViteConfig source format
  packages/vite/src/lib/getDefaultViteConfig.ts
Labels: release:chore, changelog-ok

#10031 feat(rsc-streaming): Integrating RSC builds with Streaming and Client side hydration
  packages/project-config/src/paths.ts
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRouteManifest.ts
  packages/vite/src/client.ts
  packages/vite/src/index.ts
  packages/vite/src/lib/getMergedConfig.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildClientEntriesFile.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscVitePlugins.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:feature, changelog-ok

#10112 fix(scenario): Make sure to cleanup even if test fails
  CHANGELOG.md
  packages/testing/config/jest/api/jest.setup.js
Labels: topic/testing, release:fix

#10117 fix(context): Re-export context from `graphql-server`
  CHANGELOG.md
  packages/graphql-server/src/index.ts
Labels: release:fix

#10118 fix(deps): add missing dependency `@redwoodjs/babel-config` to `@redwoodis/vite`
  packages/vite/package.json
  yarn.lock
Labels: release:fix, changelog-ok

#10121 RSC: Remove our own rscNodeLoader
  packages/vite/package.json
  packages/vite/src/rsc/rscNodeLoader.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
Labels: release:chore, changelog-ok

#10122 chore(web): switch to vitest
  packages/web/jest.config.js
  packages/web/package.json
  packages/web/src/components/FetchConfigProvider.test.tsx
  packages/web/src/components/GraphQLHooksProvider.test.tsx
  packages/web/src/components/Metadata.test.tsx
  packages/web/src/components/cell/createCell.test.tsx
  packages/web/src/components/cell/createSuspendingCell.test.tsx
  packages/web/src/components/portalHead.test.tsx
  packages/web/vitest.config.mts
  packages/web/vitest.setup.mts
  yarn.lock
Labels: release:chore, changelog-ok

#10082 fix(api-server): Preserve original host header for proxied API requests
  CHANGELOG.md
  packages/adapters/fastify/web/src/web.ts
  packages/vite/src/runFeServer.ts
Labels: release:fix

#10123 fix(env files): rename to `--load-env-files`
  CHANGELOG.md
  packages/cli/src/index.js
  packages/cli/src/lib/loadEnvFiles.js
  tasks/server-tests/bothServer.test.mts
Labels: release:fix

#10130 RSC: Update templates for setup command
  packages/cli/src/commands/experimental/templates/rsc/AboutPage.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/App.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/HomePage.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/Routes.tsx.template
Labels: release:feature, changelog-ok

#10131 chore(esm): Use .js imports in @redwoodjs/vite to prep for ESM
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRouteManifest.ts
  packages/vite/src/buildRscClientAndServer.ts
  packages/vite/src/client.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/fully-react/DevRwRscServerGlobal.ts
  packages/vite/src/fully-react/ProdRwRscServerGlobal.ts
  packages/vite/src/fully-react/rwRscGlobal.ts
  packages/vite/src/index.ts
  packages/vite/src/lib/getMergedConfig.ts
  packages/vite/src/middleware/MiddlewareRequest.ts
  packages/vite/src/middleware/MiddlewareResponse.ts
  packages/vite/src/middleware/index.ts
  packages/vite/src/middleware/invokeMiddleware.ts
  packages/vite/src/plugins/__tests__/remove-from-bundle.test.mts
  packages/vite/src/plugins/__tests__/swap-apollo-provider.test.mts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildClientEntriesFile.ts
  packages/vite/src/rsc/rscBuildCopyCssAssets.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscVitePlugins.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/vite/src/streaming/transforms/serverInjectionTransform.ts
Labels: release:chore, changelog-ok

#10119 fix(esm): use CJS wrapper for ESM default interop
  CHANGELOG.md
  packages/vite/cjsWrapper.js
  packages/vite/package.json
Labels: release:fix

#10135 chore(prerender): switch to vitest
  packages/prerender/jest.config.js
  packages/prerender/package.json
  packages/prerender/src/__tests__/detectRoutes.test.ts
  packages/prerender/src/babelPlugins/__tests__/babel-plugin-redwood-prerender-media-imports.test.ts
  packages/prerender/vitest.config.mts
  yarn.lock
Labels: release:chore, changelog-ok

#10137 RSC: Remove App.tsx from setup
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/templates/rsc/App.tsx.template
Labels: release:fix, changelog-ok

#10138 chore(release): try changesets instead of changelog
  .github/actions/check_changelog/action.yml
  .github/actions/check_changelog/check_changelog.mjs
  .github/actions/check_changesets/action.yml
  .github/actions/check_changesets/check_changesets.mjs
  .github/actions/check_changesets/package.json
  .github/actions/check_changesets/yarn.lock
  .github/workflows/check-changelog.yml
  package.json
  tasks/changesets/changesets.mts
  tasks/changesets/changesetsHelpers.mts
  tasks/changesets/placeholder.md
  yarn.lock
Labels: release:chore, changesets-ok

#10143 chore(deps): add missing dependencies `@babel/core` and `fs-extra`
  packages/internal/package.json
  packages/structure/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10147 chore(vite): use esbuild instead of babel
  packages/framework-tools/src/buildDefaults.ts
  packages/vite/.babelrc.js
  packages/vite/build.mts
  packages/vite/package.json
  yarn.lock
Labels: release:chore, fixture-ok, changesets-ok

#10149 chore(vite): remove babel dependencies
  packages/vite/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10151 fix(setup realtime): remove "exp" from suggested setup command
  .changesets/10151.md
  packages/cli/src/commands/experimental/util.js
Labels: release:fix

#10160 Fix storybook preview config path reference
  .changesets/10160.md
  packages/testing/config/storybook/main.js
Labels: release:fix

#10164 fix(rsc/ssr): build SSR as ESM
  packages/vite/modules.d.ts
  packages/vite/package.json
  packages/vite/src/streaming/buildForStreamingServer.ts
  yarn.lock
Labels: release:fix, changesets-ok

#10168 chore(rsc): remove unnecessary cjs option
  packages/vite/src/rsc/rscBuildAnalyze.ts
Labels: release:chore, changesets-ok

#10170 RSC: setClientEntries: Always 'load', so let's get rid of it
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
  packages/vite/src/runFeServer.ts
Labels: release:chore, changesets-ok

#10171 RSC: Fix syntax error in node-loader ('2024' -> 2024)
  packages/vite/src/react-server-dom-webpack/node-loader.ts
Labels: release:fix, changesets-ok

#10172 RSC: Move vite plugins into their own files
  packages/vite/src/plugins/vite-plugin-rsc-analyze.ts
  packages/vite/src/plugins/vite-plugin-rsc-reload.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform.ts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscWorker.ts
Labels: release:chore, changesets-ok

#10162 chore(internal): switch to vitest
  packages/internal/jest.config.js
  packages/internal/package.json
  packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
  packages/internal/src/__tests__/__snapshots__/graphqlSchema.test.ts.snap
  packages/internal/src/__tests__/__snapshots__/possibleTypes.test.ts.snap
  packages/internal/src/__tests__/__snapshots__/typeDefinitions.test.ts.snap
  packages/internal/src/__tests__/__snapshots__/validateSchemaForReservedNames.test.ts.snap
  packages/internal/src/__tests__/ast.test.ts
  packages/internal/src/__tests__/build_api.test.ts
  packages/internal/src/__tests__/build_web.test.ts
  packages/internal/src/__tests__/clientPreset.test.ts
  packages/internal/src/__tests__/configPath.test.ts
  packages/internal/src/__tests__/files.test.ts
  packages/internal/src/__tests__/gql.test.ts
  packages/internal/src/__tests__/graphqlCodeGen.test.ts
  packages/internal/src/__tests__/graphqlSchema.test.ts
  packages/internal/src/__tests__/jsx.test.ts
  packages/internal/src/__tests__/nestedPages.test.ts
  packages/internal/src/__tests__/possibleTypes.test.ts
  packages/internal/src/__tests__/project.test.ts
  packages/internal/src/__tests__/resolverFn.test.ts
  packages/internal/src/__tests__/routes-mocked.test.ts
  packages/internal/src/__tests__/routes.test.ts
  packages/internal/src/__tests__/typeDefinitions.test.ts
  packages/internal/src/__tests__/validateSchema.test.ts
  packages/internal/src/__tests__/validateSchemaForAuthDirectives.test.ts
  packages/internal/src/__tests__/validateSchemaForReservedNames.test.ts
  packages/internal/src/__tests__/validateSchemaWithErrors.test.ts
  packages/internal/src/generate/graphqlCodeGen.ts
  packages/internal/src/routes.ts
  packages/internal/vitest.config.mts
  yarn.lock
Labels: release:chore, changesets-ok

#10174 RSC: Remove hack from transform plugin
  packages/vite/src/plugins/vite-plugin-rsc-transform.ts
Labels: release:chore, changesets-ok

#10176 chore(ci): try yarn installing after npx crwa
  .github/actions/set-up-rsc-project/setUpRscProject.mjs
Labels: release:chore, changesets-ok

#10152 fix(esm): get lint working
  .changesets/10152.md
  packages/cli-helpers/src/auth/__tests__/authFiles.test.ts
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/authFiles.ts
  packages/cli-helpers/src/auth/authTasks.ts
  packages/cli-helpers/src/lib/__tests__/index.test.ts
  packages/cli-helpers/src/lib/index.ts
  packages/cli/src/commands/destroy/component/__tests__/component.test.js
  packages/cli/src/commands/destroy/page/__tests__/page.test.js
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/component/__tests__/component.test.ts
  packages/cli/src/commands/generate/component/component.js
  packages/cli/src/commands/generate/dataMigration/__tests__/dataMigration.test.js
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
  packages/cli/src/commands/generate/dbAuth/dbAuth.js
  packages/cli/src/commands/generate/directive/__tests__/directive.test.ts
  packages/cli/src/commands/generate/directive/directive.js
  packages/cli/src/commands/generate/function/__tests__/function.test.ts
  packages/cli/src/commands/generate/function/function.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/layout/__tests__/layout.test.ts
  packages/cli/src/commands/generate/layout/layout.js
  packages/cli/src/commands/generate/page/__tests__/page.test.js
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldCustomIdName.test.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/setup/graphql/features/fragments/fragmentsHandler.ts
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/trustedDocumentsHandler.ts
  packages/cli/src/commands/setup/monitoring/sentry/sentryHandler.ts
  packages/cli/src/lib/__tests__/index.test.js
  packages/cli/src/lib/index.js
  packages/codemods/src/codemods/v0.39.x/updateBabelConfig/updateBabelConfig.ts
  packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/tsconfigForRouteHooks.ts
  packages/codemods/src/codemods/v2.x.x/configureFastify/configureFastify.yargs.ts
  packages/codemods/src/lib/prettify.ts
  packages/internal/src/generate/clientPreset.ts
  packages/internal/src/generate/possibleTypes.ts
  packages/internal/src/generate/trustedDocuments.ts
  packages/internal/src/ts2js.ts
Labels: release:fix

#10177 chore(ci): try `yarn rw upgrade -t canary` instead of npx@canary
  .github/actions/set-up-rsc-project/setUpRscProject.mjs
Labels: release:chore, changesets-ok

#10173 RSC: transform inside plugin
  packages/vite/src/plugins/vite-plugin-rsc-transform.ts
Labels: release:chore, changesets-ok

#10179 feat(prettier) upgrade to prettier v3
  .changesets/10179.md
  packages/cli-helpers/package.json
  packages/cli/package.json
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/trustedDocumentsHandler.ts
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
  packages/cli/src/lib/__tests__/mergeBasics.test.js
  packages/cli/src/lib/__tests__/mergeConfig.test.js
  packages/cli/src/lib/merge/index.js
  packages/codemods/jest.config.js
  packages/codemods/package.json
  packages/codemods/src/codemods/v0.37.x/updateApiImports/__tests__/updateApiImports.test.ts
  packages/codemods/src/codemods/v0.37.x/updateForms/__tests__/updateForms.test.ts
  packages/codemods/src/codemods/v0.37.x/updateGraphQLFunction/__tests__/updateGraphQLFunction.test.ts
  packages/codemods/src/codemods/v0.37.x/updateScenarios/__tests__/updateScenarios.test.ts
  packages/codemods/src/codemods/v0.39.x/updateBabelConfig/__tests__/updateBabelConfig.test.ts
  packages/codemods/src/codemods/v0.39.x/updateCellMocks/__tests__/updateCellMocks.test.ts
  packages/codemods/src/codemods/v0.44.x/updateJestConfig/__tests__/updateJestConfig.test.ts
  packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/__tests__/renameVerifierTimestamp.test.ts
  packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/__tests__/updateDevFatalErrorPage.test.ts
  packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/__tests__/tsconfigForRouteHooks.test.ts
  packages/codemods/src/codemods/v2.x.x/configureFastify/__tests__/configureFastify.test.ts
  packages/codemods/src/codemods/v2.x.x/updateResolverTypes/__tests__/updateResolverTypes.test.ts
  packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/__tests__/updateClerkGetCurrentUser.test.ts
  packages/codemods/src/codemods/v4.x.x/useArmor/__tests__/useArmor.test.ts
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/__tests__/cellQueryResult.test.ts
  packages/codemods/src/codemods/v5.x.x/renameValidateWith/__tests__/renameValidateWith.test.ts
  packages/codemods/src/codemods/v5.x.x/updateAuth0ToV2/__tests__/updateAuth0ToV2.test.ts
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/__tests__/upgradeToReact18.test.ts
  packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/__tests__/changeGlobalToGlobalThis.test.ts
  packages/codemods/src/codemods/v6.x.x/convertJsToJsx/__tests__/convertJsToJsx.test.ts
  packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/__tests__/entryClientNullCheck.test.ts
  packages/codemods/src/codemods/v6.x.x/processEnvDotNotation/__tests__/processEnvDotNotation.test.ts
  packages/codemods/src/codemods/v6.x.x/replaceComponentSvgs/__tests__/replaceComponentSvgs.test.ts
  packages/codemods/src/codemods/v6.x.x/updateDevFatalErrorPage/__tests__/updateDevFatalErrorPage.test.ts
  packages/codemods/src/codemods/v6.x.x/updateThemeConfig/__tests__/updateThemeConfig.test.ts
  packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/__tests__/updateGraphqlConfig.test.ts
  packages/codemods/src/testUtils/matchFolderTransform.ts
  packages/codemods/src/testUtils/matchInlineTransformSnapshot.ts
  packages/codemods/src/testUtils/matchTransformSnapshot.ts
  packages/codemods/vite.config.mts
  packages/codemods/vite.setup.mts
  packages/eslint-config/package.json
  packages/internal/package.json
  tasks/test-project/tasks.js
  tasks/test-project/tui-tasks.js
  yarn.lock
Labels: release:feature, fixture-ok

#10181 RSC: Inline transform plugin code and add tests
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-transform.ts
  packages/vite/src/rsc/rscWorker.ts
Labels: release:chore, fixture-ok, changesets-ok

#10158 RSC: Initial pass at enabling `rw dev` for RSC
  packages/vite/src/devFeServer.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform.ts
  packages/vite/src/react-server-dom-webpack/node-loader.ts
  packages/vite/src/rsc/rscWorker.ts
Labels: release:feature, fixture-ok, changesets-ok

#10184 RSC: Simplify node-loader and clientEntryFiles
  packages/vite/src/plugins/vite-plugin-rsc-transform.ts
  packages/vite/src/react-server-dom-webpack/node-loader.ts
Labels: release:chore, fixture-ok, changesets-ok

#10188 fix(prettier): revert breaking changes in prettier v3 upgrade
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
  tasks/test-project/tasks.js
  tasks/test-project/tui-tasks.js
Labels: release:fix

#10183 fix(cli): avoid `require` in prettier config during tailwind setup
  .changesets/10183.md
  __fixtures__/fragment-test-project/prettier.config.js
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/test-project/prettier.config.js
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.tsx
  __fixtures__/test-project/web/src/components/Contact/ContactsCell/ContactsCell.tsx
  __fixtures__/test-project/web/src/components/Post/PostCell/PostCell.tsx
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
  tasks/test-project/tasks.js
  tasks/test-project/tui-tasks.js
Labels: release:fix

#10150 chore(testing): switch to vitest
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth/package.json
  packages/router/package.json
  packages/testing/jest.config.js
  packages/testing/jest.setup.ts
  packages/testing/package.json
  packages/testing/src/api/__tests__/directUrlHelpers.test.ts
  packages/testing/src/web/__tests__/MockHandlers.test.tsx
  packages/testing/src/web/__tests__/MockRouter.test.tsx
  packages/testing/src/web/__tests__/findCellMocks.test.ts
  packages/testing/vitest.config.mts
  packages/testing/vitest.setup.mts
  yarn.lock
Labels: release:chore, changesets-ok

#10146 chore(realtime): switch to vitest
  packages/realtime/package.json
  packages/realtime/src/graphql/plugins/__tests__/__snapshots__/useRedwoodRealtime.test.ts.snap
  packages/realtime/src/graphql/plugins/__tests__/useRedwoodRealtime.test.ts
  packages/realtime/vitest.config.mts
  packages/realtime/vitest.setup.mts
  yarn.lock
Labels: release:chore, changesets-ok

#10189 fix(rsc): emit files with `.mjs` instead of `.js`
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-transform.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildForServer.ts
Labels: release:fix, changesets-ok

#10191 RSC: Make rw dev not crash for /about
  packages/vite/src/plugins/vite-plugin-rsc-transform.ts
Labels: release:fix, changesets-ok

#10193 chore(rsc): add smoke test for rsc dev
  .github/workflows/ci.yml
  tasks/smoke-tests/rsc-dev/playwright.config.ts
  tasks/smoke-tests/rsc-dev/tests/rsc.spec.ts
Labels: release:chore, changesets-ok

#10199 RSC: Add some types for RSDW/client
  .vscode/settings.json
  packages/vite/modules.d.ts
  packages/vite/src/client.ts
Labels: release:fix, changesets-ok

#10197 feat(vite): upgrade to v5
  packages/cli/src/commands/buildHandler.js
  packages/cli/src/commands/devHandler.js
  packages/vite/package.json
  packages/vite/src/lib/getMergedConfig.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  yarn.lock
Labels: release:feature, changesets-ok

#10202 fix(rsc): try fixing dev
  packages/vite/src/devFeServer.ts
Labels: release:fix, changesets-ok

#10206 chore(ci): refactor out CLI smoke tests
  .github/workflows/ci.yml
Labels: release:chore

#10208 chore(ci): upgrade cache action
  .github/actions/set-up-yarn-cache/action.yml
Labels: release:chore

#10209 chore(ci): improve set up yarn cache action
  .github/actions/set-up-yarn-cache/action.yml
Labels: release:chore

#10211 chore(ci): use tarsync for rsc test projects
  .github/actions/actionsLib.mjs
  .github/actions/set-up-rsc-project/setUpRscProject.mjs
  .github/actions/set-up-test-project/setUpTestProject.mjs
Labels: release:chore

#10212 RSC: Use throw-on-client package
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/HomePage/words.ts
Labels: release:chore, changesets-ok

#10215 RSC: Split transform plugin into client and server
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-transform-client.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscWorker.ts
Labels: release:chore, changesets-ok

#10218 fix(rsc): only use `web/src/entries.ts` as the `rscBuildAnalyze` entry point
  packages/vite/src/rsc/rscBuildAnalyze.ts
Labels: release:fix, changesets-ok

#10217 RSC: Inline dependencies during rsc build
  packages/vite/src/rsc/rscBuildForServer.ts
Labels: release:fix, changesets-ok

#10222 RSC: Fix a prisma client warning during build
  packages/vite/src/rsc/rscBuildAnalyze.ts
Labels: release:fix, changesets-ok

#10221 chore(rsc): prefix `rsc-analyze-plugin` plugin
  packages/vite/src/plugins/vite-plugin-rsc-analyze.ts
Labels: release:chore

#10228 chore(tests): avoid needlessly matching on `src`
  packages/adapters/fastify/web/package.json
  packages/api/package.json
  packages/auth-providers/auth0/api/package.json
  packages/auth-providers/auth0/setup/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/setup/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/custom/setup/package.json
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/setup/package.json
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/netlify/setup/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/api/package.json
  packages/auth-providers/supertokens/setup/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/mailer/core/package.json
  packages/prerender/package.json
  packages/project-config/package.json
  packages/record/package.json
  packages/telemetry/package.json
  packages/vite/package.json
Labels: release:chore, changesets-ok

#10229 chore(ci): update `yarn rwfw project:tarsync` to handle react resolutions
  tasks/framework-tools/tarsync.mjs
Labels: release:chore

#10226 RSC: fix css and add smoke tests for it
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-css-preinit.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-analyze.ts
  packages/vite/src/plugins/vite-plugin-rsc-css-preinit.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  tasks/smoke-tests/rsc-dev/tests/rsc.spec.ts
  tasks/smoke-tests/rsc-external-packages-and-cells/tests/rsc-external-packages-and-cells.spec.ts
  tasks/smoke-tests/rsc/tests/rsc.spec.ts
Labels: release:fix, changesets-ok

#10227 chore(rsc): unminify dist
  packages/vite/src/lib/getMergedConfig.ts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/streaming/buildForStreamingServer.ts
Labels: release:chore

#10213 feat: Send RSC Flight Payload to Studio
  .changesets/four-adults-jog.md
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscStudioHandlers.ts
Labels: release:feature

#10239 RSC: Random vite package cleanup and tweaks
  packages/vite/src/client.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscWebpackShims.ts
Labels: release:chore, changesets-ok

#10240 RSC: Tweak comment in vite/client
  packages/vite/src/client.ts
Labels: release:chore, changesets-ok

#10243 fix(rsc): use query string in rsc url
  packages/vite/src/client.ts
  packages/vite/src/rsc/rscRequestHandler.ts
Labels: release:fix

#10237 fix(rsc): avoid overriding `NODE_ENV`
  packages/vite/bins/rw-vite-build.mjs
Labels: release:fix

#10245 RSC: Use vite plugin to inject webpack shims
  packages/vite/src/index.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-entry.ts
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:fix, changesets-ok

#10246 RSC: Clean up webpack shims
  packages/vite/src/plugins/vite-plugin-rsc-transform-entry.ts
  packages/vite/src/rsc/rscWebpackShims.ts
Labels: release:chore, changesets-ok

#10247 RSC: Remove `<Assets>` component
  __fixtures__/test-project-rsa/web/src/pages/AboutPage/AboutPage.tsx
  __fixtures__/test-project-rsa/web/src/pages/HomePage/HomePage.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/AboutPage/AboutPage.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/HomePage/HomePage.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/MultiCellPage/MultiCellPage.tsx
  packages/cli/src/commands/experimental/templates/rsc/AboutPage.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/HomePage.tsx.template
  packages/vite/package.json
  packages/vite/src/fully-react/DevRwRscServerGlobal.ts
  packages/vite/src/fully-react/ProdRwRscServerGlobal.ts
  packages/vite/src/fully-react/RwRscServerGlobal.ts
  packages/vite/src/fully-react/assets.tsx
  packages/vite/src/fully-react/find-styles.ts
  packages/vite/src/fully-react/findAssetsInManifest.ts
  packages/vite/src/fully-react/rwRscGlobal.ts
Labels: release:chore, changesets-ok

#10248 RSC: Don't edit index.html during setup
  __fixtures__/test-project-rsa/web/src/index.html
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/index.html
  packages/cli/src/commands/experimental/setupRscHandler.js
Labels: release:chore, changesets-ok

#10244 Update first-test.md
  docs/docs/tutorial/chapter5/first-test.md
Labels: release:docs, changesets-ok

#10241 RSC: Differentiate routes autoloading behaviour
  packages/babel-config/src/index.ts
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-routes-auto-loader-rsc-client.test.ts
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-routes-auto-loader-rsc-server.test.ts
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader-rsc-client.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader-rsc-server.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader.ts
  packages/babel-config/src/web.ts
  packages/vite/package.json
  packages/vite/src/buildFeServer.ts
  packages/vite/src/client.ts
  packages/vite/src/clientSsr.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/index.ts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/streaming/buildForStreamingServer.ts
Labels: release:fix, changesets-ok

#10194 chore(rsc): upgrade to react canary
  .github/renovate.json
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/vite/ambient.d.ts
  packages/vite/build.mts
  packages/vite/modules.d.ts
  packages/vite/package.json
  packages/vite/src/bundled/react-server-dom-webpack.server.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/index.ts
  packages/vite/src/lib/registerFwGlobalsAndShims.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-entry.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10249 chore(ci): refactor out set up steps
  .github/actions/set-up-job/action.yml
  .github/workflows/check-changelog.yml
  .github/workflows/check-create-redwood-app.yml
  .github/workflows/check-test-project-fixture.yml
  .github/workflows/ci.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-release-candidate.yml
Labels: release:chore

#10250 chore(ci): remove unused workflows
  .github/actions/update_all_contributors/action.yml
  .github/actions/update_all_contributors/update_all_contributors.mjs
  .github/workflows/monthly_issue_metrics_json.yml
  .github/workflows/update-all-contributors.yml
  .github/workflows/weekly_issue_metrics_json.yml
Labels: release:chore, changesets-ok

#10251 docs: fix typo on router page
  docs/docs/router.md
Labels: release:docs, changesets-ok

#10252 RSC: Vite plugin for route loading
  __fixtures__/test-project/web/package.json
  packages/babel-config/src/index.ts
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-routes-auto-loader-rsc-client.test.ts
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-routes-auto-loader-rsc-server.test.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader-rsc-client.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader-rsc-server.ts
  packages/vite/src/client.ts
  packages/vite/src/clientSsr.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/index.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-routes-auto-loader.ts
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildForServer.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/streaming/buildForStreamingServer.ts
Labels: release:fix, changesets-ok

#10254 Update Prisma Dataguide Link
  docs/docs/local-postgres-setup.md
Labels: release:docs, changesets-ok

#10268 chore(changesets): Update the name of an older entry
  .changesets/10213.md
Labels: release:chore, fixture-ok, changesets-ok

#10267 Update deployment.md
  docs/docs/tutorial/chapter4/deployment.md
Labels: release:docs, fixture-ok, changesets-ok

#10265 fix(cli): Update build and serve to handle the absence of the api side
  .changesets/10265.md
  __fixtures__/test-project/web/package.json
  packages/cli/src/commands/__tests__/build.test.js
  packages/cli/src/commands/buildHandler.js
  packages/cli/src/commands/serve.js
  packages/vite/src/index.ts
Labels: release:fix

#10275 Don't try to start the api server unless RSC is enabled
  .changesets/10275.md
  packages/cli/src/commands/serve.js
Labels: release:chore, fixture-ok

#10279 RSC: serve.js: Extract "enabled" var rsc and streaming
  packages/cli/src/commands/serve.js
Labels: release:chore, fixture-ok, changesets-ok

#10278 [#10273] Fix react docs links
  README.md
  __fixtures__/fragment-test-project/web/src/entry.client.tsx
  __fixtures__/test-project-rsa/web/src/entry.client.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/entry.client.tsx
  __fixtures__/test-project/web/src/entry.client.tsx
  docs/docs/custom-web-index.md
  docs/docs/introduction.md
  docs/versioned_docs/version-1.x/custom-web-index.md
  docs/versioned_docs/version-2.x/custom-web-index.md
  docs/versioned_docs/version-3.x/custom-web-index.md
  docs/versioned_docs/version-4.x/custom-web-index.md
  docs/versioned_docs/version-5.x/custom-web-index.md
  docs/versioned_docs/version-6.x/custom-web-index.md
  docs/versioned_docs/version-7.0/custom-web-index.md
  packages/cli/src/commands/experimental/templates/streamingSsr/entry.client.tsx.template
  packages/create-redwood-app/templates/js/web/src/entry.client.jsx
  packages/create-redwood-app/templates/ts/web/src/entry.client.tsx
  packages/web/src/entry/index.js
Labels: release:docs, changesets-ok

#10280 chore(babel-config): Fix error message grammar
  .changesets/10280.md
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader.ts
Labels: release:fix, fixture-ok

#10281 chore(test-project): Update autoprefixer and postcss versions
  __fixtures__/test-project/web/package.json
Labels: release:chore, changesets-ok

#10282 RSC: Refactor forRsc camelcase and add rscEnabled
  packages/babel-config/src/web.ts
  packages/vite/src/index.ts
Labels: release:chore, changesets-ok

#10283 RSC: Vite route auto loader plugin: Fix error message grammar
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-routes-auto-loader.ts
Labels: release:fix, changesets-ok

#10284 chore(types): Type react-dom/server.edge
  packages/vite/modules.d.ts
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:chore, changesets-ok

#10285 RSC: Only shim webpack when RSC is enabled
  packages/vite/src/lib/registerFwGlobalsAndShims.ts
Labels: release:chore, changesets-ok

#10291 Update Readme for Bighorn epoch.
  README.md
Labels: release:chore, changesets-ok

#10335 chore(deps): update many misc deps
  .changesets/10335.md
  docs/package.json
  package.json
  packages/api-server/package.json
  packages/api/package.json
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/setup/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/cli-helpers/package.json
  packages/cli-packages/dataMigrate/package.json
  packages/cli/package.json
  packages/codemods/package.json
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/__testfixtures__/default/input/package.json
  packages/codemods/src/codemods/v0.48.x/upgradeYarn/__testfixtures__/default/output/package.json
  packages/core/package.json
  packages/create-redwood-app/package.json
  packages/eslint-config/package.json
  packages/eslint-plugin/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/mailer/handlers/nodemailer/package.json
  packages/mailer/renderers/mjml-react/package.json
  packages/mailer/renderers/react-email/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/telemetry/package.json
  packages/testing/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, fixture-ok

#10342 fix(navlink): Replace (don't merge) className of active link
  .changesets/10342.md
  packages/router/src/navLink.tsx
Labels: release:breaking

#10341 chore(types): Improve `flattenSearchParams` types and docs
  packages/router/src/util.ts
Labels: release:chore, changesets-ok

#10343 chore(tw): Add tests to the tailwind setup command
  .vscode/settings.json
  packages/cli/src/commands/setup/ui/__tests__/tailwindcss.test.ts
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
Labels: release:chore, changesets-ok

#10354 chore(test-project): Update tailwindcss version
  __fixtures__/test-project/web/package.json
Labels: release:chore, changesets-ok

#10294 docs: Add information about how to turn off Prisma/db operations during a Vercel deploy to reduce Postgres Storage use
  docs/docs/deploy/vercel.md
Labels: release:docs, changesets-ok

#10293 docs: Adds important admonition for generate dbAuth to clarify that must setup dbAuth not just generate the pages
  docs/docs/cli-commands.md
Labels: release:docs, changesets-ok

#10353 chore(changesets): Throw an error if no GH token is set
  tasks/changesets/changesetsHelpers.mts
Labels: release:chore, changesets-ok

#10266 chore(linting): Update versions and avoid `{}`
  .changesets/10266.md
  packages/eslint-config/package.json
  packages/eslint-config/shared.js
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/__tests__/process-env-computed.test.ts
  packages/eslint-plugin/src/__tests__/service-type-annotations.test.ts
  packages/eslint-plugin/src/__tests__/unsupported-route-components.test.ts
  packages/eslint-plugin/src/index.ts
  packages/eslint-plugin/src/process-env-computed.ts
  packages/eslint-plugin/src/service-type-annotations.ts
  packages/eslint-plugin/src/unsupported-route-components.ts
  packages/eslint-plugin/tsconfig.json
  packages/eslint-plugin/vitest.config.mts
  packages/router/src/skipNav.tsx
  packages/structure/src/x/vscode.ts
  tasks/linting-diff/.gitignore
  tasks/linting-diff/lintingDiff.mts
  yarn.lock
Labels: release:breaking

#10323 chore(CLI): build with esbuild
  packages/cli/.babelrc.js
  packages/cli/build.mts
  packages/cli/package.json
  packages/cli/src/commands/generate/layout/layout.js
  packages/cli/src/commands/generate/layout/templates/layout.tsx.a11y.template
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/page/templates/stories.tsx.parameters.template
  packages/cli/src/commands/generate/realtime/templates/liveQueries/.keep
  packages/cli/src/commands/generate/realtime/templates/subscriptions/.keep
  packages/cli/src/commands/setup/realtime/templates/liveQueries/.keep
  packages/cli/vitest.codemods.setup.ts
  packages/cli/vitest.workspaces.ts
  packages/framework-tools/src/buildDefaults.ts
  yarn.lock
Labels: release:chore

#10360 chore(telemetry): build with esbuild
  packages/telemetry/.babelrc.js
  packages/telemetry/build.mts
  packages/telemetry/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10373 chore(fixtures): linting comment
  __fixtures__/example-todo-main/web/src/graphql/fragment-masking.ts
Labels: release:chore, fixture-ok, changesets-ok

#10381 chore(docs): Update yarn.lock in /docs
  docs/yarn.lock
Labels: release:chore, changesets-ok

#10382 chore(ci): Don't check the test project fixture for docs-only PRs
  .github/workflows/check-test-project-fixture.yml
Labels: release:chore, changesets-ok

#10384 chore(ci): Rename onlydocs -> docs_only
  .github/actions/detect-changes/detectChanges.mjs
  .github/workflows/check-test-project-fixture.yml
  .github/workflows/ci.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-release-candidate.yml
Labels: release:chore, changesets-ok

#10385 chore(ci): Refactor docs_only detection
  .github/actions/detect-changes/cases/code_changes.mjs
  .github/actions/detect-changes/cases/docs_changes.mjs
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore, changesets-ok

#10386 chore(ci): Detect changesets-only changes
  .github/actions/detect-changes/cases/changesets_changes.mjs
  .github/actions/detect-changes/detectChanges.mjs
  .github/workflows/ci.yml
Labels: release:chore, changesets-ok

#10387 chore(ci): Refactor detectChanges and add README
  .github/actions/detect-changes/README.md
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore, changesets-ok

#10388 chore(ci): detectChanges: Only analyze newly changed files
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore, changesets-ok

#10389 chore(ci): Undo unrelated docs-only change
  .github/workflows/publish-canary.yml
  .github/workflows/publish-release-candidate.yml
Labels: release:chore, changesets-ok

#10390 chore(ci): detectChanges: Check for "code" changes
  .github/actions/detect-changes/cases/changesets_changes.mjs
  .github/actions/detect-changes/cases/code_changes.mjs
  .github/actions/detect-changes/cases/docs_changes.mjs
  .github/actions/detect-changes/detectChanges.mjs
  .github/workflows/check-test-project-fixture.yml
  .github/workflows/ci.yml
Labels: release:chore, changesets-ok

#10391 chore(ci): detectChanges: Retry fetch on NOK
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore, changesets-ok

#10392 chore(ci): detectChanges: Prefer GH_TOKEN
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore, changesets-ok
