Repository redwoodjs/graphql, pull requests merged in 2024-12, with the labels that each got.

#11737 [TS] Include query parameters in typed Cell component props
  .changesets/11737.md
  docs/docs/tutorial/chapter2/routing-params.md
  packages/web/src/components/cell/cellTypes.ts
Labels: release:fix, fixture-ok

#11749 fix(cli): Update cell test template to include `id`
  __fixtures__/test-project/web/src/components/AuthorCell/AuthorCell.test.tsx
  __fixtures__/test-project/web/src/components/BlogPostCell/BlogPostCell.test.tsx
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.test.tsx
  __fixtures__/test-project/web/src/components/WaterfallBlogPostCell/WaterfallBlogPostCell.test.tsx
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/cell.js
  packages/cli/src/commands/generate/cell/templates/test.js.template
Labels: release:fix, changesets-ok

#11746 Fix absolute & component folder imports in Storybook config folder
  .changesets/11746.md
  __fixtures__/test-project/web/tsconfig.json
  packages/create-redwood-app/templates/js/web/jsconfig.json
  packages/create-redwood-app/templates/ts/web/tsconfig.json
Labels: release:fix

#11745 [Storybook] Improve typing, add doc links & remove redundant JSDoc in preview.tsx
  .changesets/11745.md
  packages/cli/src/commands/setup/i18n/templates/storybook.preview.tsx.template
  packages/cli/src/commands/setup/ui/templates/chakra.storybook.preview.tsx.template
  packages/cli/src/commands/setup/ui/templates/mantine.storybook.preview.tsx.template
  packages/cli/src/lib/templates/storybook.preview.tsx.template
Labels: release:feature

#11744 fix: :bug: add custom headers to subscription in apollo client
  .changesets/11744.md
  packages/web/src/apollo/sseLink.ts
Labels: release:fix

#11758 feat(cells): Optimize default afterQuery by avoiding memcopy
  .changesets/11758.md
  packages/web/src/components/cell/createCell.tsx
Labels: release:feature

#11748 Include `.storybook` folder in Linting
  .changesets/11748.md
  packages/cli/src/commands/lint.js
  packages/eslint-config/index.js
  packages/eslint-config/shared.js
Labels: release:fix

#11731 fix(api-server): prevent race condition in server restart process
  .changesets/11731.md
  packages/api-server/src/serverManager.ts
Labels: release:fix

#11761 Update router.md
  docs/docs/router.md
Labels: release:docs

#11756 [Router][TS] Auto-complete route names for unauthenticated prop
  .changesets/11756.md
  packages/router/src/Set.tsx
Labels: release:breaking

#11764 [docs] Add offline_access to implicit scopes added by msal-browser
  docs/docs/auth/azure.md
Labels: release:docs

#11767 chore(set): Use the existing AvailableRoutes type
  packages/router/src/Set.tsx
Labels: release:chore, changesets-ok

#11768 fix(set): Correctly infer generic
  packages/router/src/Set.tsx
Labels: release:fix, changesets-ok

#11751 chore(docs): Add additional hints to serverless functions
  docs/docs/serverless-functions.md
Labels: release:docs

#11638 breaking(baremetal): Throw an error if there is not enough available space
  .changesets/11638.md
  packages/cli/src/commands/deploy/__tests__/baremetal.test.js
  packages/cli/src/commands/deploy/baremetal.js
Labels: release:breaking

#11772 fix(docs): Fix relative link to env vars page
  docs/docs/how-to/custom-function.md
Labels: release:docs

#11770 fix(cli): Fix TS warnings in custom function template
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/function/__tests__/__snapshots__/function.test.ts.snap
  packages/cli/src/commands/generate/function/function.js
  packages/cli/src/commands/generate/function/templates/function.ts.template
Labels: release:fix, changesets-ok

#11771 breaking(dbAuth): rename cookieName() -> generateCookieName()
  .changesets/11771.md
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/shared.test.ts
  packages/auth-providers/dbAuth/api/src/decoder.ts
  packages/auth-providers/dbAuth/api/src/shared.ts
  packages/auth-providers/dbAuth/middleware/src/index.ts
Labels: release:breaking

#11769 feat(router): Better autocomplete for `<Set>`s
  .changesets/11769.md
  packages/router/src/Set.tsx
Labels: release:feature

#11775 docs: update wording for .env symlink step
  docs/docs/deploy/baremetal.md
  docs/versioned_docs/version-1.x/deploy/baremetal.md
  docs/versioned_docs/version-2.x/deploy/baremetal.md
  docs/versioned_docs/version-3.x/deploy/baremetal.md
  docs/versioned_docs/version-4.x/deploy/baremetal.md
  docs/versioned_docs/version-5.x/deploy/baremetal.md
  docs/versioned_docs/version-6.x/deploy/baremetal.md
  docs/versioned_docs/version-7.x/deploy/baremetal.md
  docs/versioned_docs/version-8.0/deploy/baremetal.md
  docs/versioned_docs/version-8.1/deploy/baremetal.md
  docs/versioned_docs/version-8.2/deploy/baremetal.md
  docs/versioned_docs/version-8.3/deploy/baremetal.md
  docs/versioned_docs/version-8.4/deploy/baremetal.md
Labels: release:docs

#11779 fix(cli): Fix Cell test generation for list cells
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.test.tsx
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/cell.js
Labels: release:fix, changesets-ok

#11773 [TS + Docs] Include potential gql input variables in ListCell's Loading and Success component typing & improve TS docs
  .changesets/11773.md
  __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.tsx
  docs/docs/how-to/pagination.md
  docs/docs/tutorial/chapter2/cells.md
  docs/docs/tutorial/chapter2/routing-params.md
  docs/docs/tutorial/chapter5/first-story.md
  docs/docs/tutorial/chapter5/first-test.md
  docs/docs/tutorial/chapter6/comment-form.md
  docs/docs/tutorial/chapter6/multiple-comments.md
  docs/docs/tutorial/chapter7/rbac.md
  packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
  packages/cli/src/commands/generate/cell/templates/cellList.tsx.template
  packages/web/src/components/cell/cellTypes.ts
Labels: release:feature

#11781 [docs] Reflect new structure of cookie config object since RW 6.4
  docs/docs/auth/dbauth.md
  docs/versioned_docs/version-6.x/auth/dbauth.md
  docs/versioned_docs/version-7.x/auth/dbauth.md
  docs/versioned_docs/version-8.0/auth/dbauth.md
  docs/versioned_docs/version-8.1/auth/dbauth.md
  docs/versioned_docs/version-8.2/auth/dbauth.md
  docs/versioned_docs/version-8.3/auth/dbauth.md
  docs/versioned_docs/version-8.4/auth/dbauth.md
Labels: release:docs

#11784 chore(deps): Update test project to use TW 3.4.17
  __fixtures__/test-project/web/package.json
Labels: release:chore

#11766 Fix AuthProviderProps export missing from `@redwood/auth`
  .changesets/11766.md
  packages/auth/src/index.ts
Labels: release:fix

#11790 chore(deps): Upgrade Prettier from 3.3.3 to 3.4.2
  package.json
  packages/cli-helpers/package.json
  packages/cli/package.json
  packages/codemods/package.json
  packages/eslint-config/package.json
  packages/internal/package.json
  yarn.lock
Labels: release:chore

#11792 chore(formatting): Fix formatting in auth/src/index.ts
  packages/auth/src/index.ts
Labels: release:chore, changesets-ok

#11791 chore(prettier): Ignore a few docs pages because of prettier issue
  .prettierignore
Labels: release:chore

#11788 Fix `useEffect is not defined` in i18n template
  packages/cli/src/commands/setup/i18n/templates/storybook.preview.tsx.template
Labels: release:fix, changesets-ok

#11789 Remove extraneous `i18n` dependency from i18n setup
  packages/cli/src/commands/setup/i18n/i18nHandler.js
Labels: release:chore, changesets-ok

#11793 chore(deps): Bump systeminformation from 5.23.5 to 5.23.8
  packages/cli/package.json
  packages/create-redwood-app/package.json
  packages/internal/package.json
  packages/telemetry/package.json
  yarn.lock
Labels: changesets-ok, release:dependency

#11795 chore(deps): Bump express from 4.21.0 to 4.21.2
  packages/vite/package.json
  yarn.lock
Labels: release:dependency

#11803 chore(deps): Bump memfs from 4.13.0 to 4.15.1
  packages/auth-providers/supertokens/setup/package.json
  packages/cli-packages/dataMigrate/package.json
  packages/cli/package.json
  packages/vite/package.json
  yarn.lock
Labels: release:chore

#11804 chore(cli): Remove debug console.log
  packages/cli/src/commands/generate/page/__tests__/page.test.js
Labels: release:chore

#11802 chore(cli): Add tests for custom scaffold templates
  packages/cli/package.json
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  yarn.lock
Labels: release:chore

#11776 Remove header example with broken link
  .changesets/11776.md
  packages/graphql-server/src/__tests__/__snapshots__/graphiql.test.ts.snap
  packages/graphql-server/src/graphiql.ts
Labels: release:fix

#11601 Prompt to confirm upgrade
  .changesets/11601.md
  .github/actions/set-up-test-project/setUpTestProject.mjs
  packages/cli/src/commands/upgrade.js
Labels: release:feature

#11812 Revert "chore(deps): update dependency supertokens-auth-react to v0.48.0"
  packages/auth-providers/supertokens/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#11822 fix(babel-config): Specify 'target' for the react compiler plugin
  packages/babel-config/src/web.ts
Labels: release:fix, changesets-ok

#11827 [setup i18n storybook] Use function with capitalized name to comply with eslint-rule
  packages/cli/src/commands/setup/i18n/templates/storybook.preview.tsx.template
Labels: release:fix, changesets-ok

#11841 chore(router): util.ts: Remove unused code
  packages/router/src/util.ts
Labels: release:chore

#11635 fix(router): Skip search params with undefined and null values passed to named routes
  packages/router/src/__tests__/util.test.ts
  packages/router/src/util.ts
Labels: release:fix, changesets-ok

#11842 fix(crwrsca): add @types/node to fix peer deps
  packages/create-redwood-rsc-app/package.json
  packages/create-redwood-rsc-app/yarn.lock
Labels: release:fix, changesets-ok, experimental

#11843 chore(deps): Add missing dep `cookie` to `@redwoodjs/web`
  packages/web/package.json
  yarn.lock
Labels: release:chore

#11852 chore(deps): nx v19.8.14
  package.json
  yarn.lock
Labels: release:chore

#11856 chore(cookie-jar): Add test script and a few more tests
  packages/cookie-jar/package.json
  packages/cookie-jar/src/CookieJar.test.ts
  yarn.lock
Labels: release:chore

#11857 fix(deploy): Restore Render deploy setup script
  packages/cli/src/commands/setup/deploy/providers/render.js
Labels: release:fix

#11866 fix(cookie): Fix regression after v1 upgrade
  packages/api/src/auth/index.ts
Labels: release:fix, changesets-ok

#11865 chore(deps): nx v20.3.0
  package.json
  yarn.lock
Labels: changesets-ok, release:dependency

#11868 chore(deps): listr2 v7.0.2
  package.json
  packages/cli-helpers/package.json
  packages/cli-helpers/src/auth/authTasks.ts
  packages/cli-helpers/src/lib/index.ts
  packages/cli-packages/dataMigrate/package.json
  packages/cli/package.json
  packages/cli/src/__tests__/Listr2Mock.ts
  packages/cli/src/commands/experimental/setupOpentelemetryHandler.js
  packages/cli/src/commands/experimental/setupReactCompilerHandler.js
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/setupStreamingSsrHandler.js
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.mockListr.test.js
  packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
  packages/cli/src/commands/generate/dbAuth/dbAuth.js
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
  packages/cli/src/commands/upgrade.js
  yarn.lock
Labels: changesets-ok, release:dependency

#11870 [chore] Use framer-motion @^11 instead of @^9 for Chakra UI setup
  packages/cli/src/commands/setup/ui/libraries/chakra-ui.js
Labels: changesets-ok, release:dependency
