Repository redwoodjs/graphql, pull requests merged in 2024-10, with the labels that each got.

#11644 chore(rsc): Make Router-related imports safer for RSC
  packages/internal/src/routes.ts
  packages/router/ambient.d.ts
  packages/router/package.json
  packages/router/src/react-util.ts
  packages/router/src/util.ts
  packages/storybook/src/mocks/MockRouter.tsx
  packages/testing/src/web/MockRouter.tsx
Labels: release:chore, experimental

#11645 fix(crwa): Better handling of installing to .
  .changesets/11645.md
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#11639 fix(web) type NonSuspenseCellQueryResult...
  .changesets/11639.md
  packages/web/src/components/cell/cellTypes.ts
Labels: release:fix, changesets-ok

#11648 breaking(rsc): Removing live-reload RSC dev server approach
  packages/vite/package.json
  packages/vite/src/devRscServer.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/streamHelpers.ts
  yarn.lock
Labels: release:breaking, changesets-ok, experimental

#11650 chore(rsc): Fix TODO and simplify SSR code
  packages/router/src/rsc/clientSsr.ts
Labels: release:chore, fixture-ok, experimental

#11651 fix(crwa): Add missing quotes to seed example
  .changesets/11651.md
  __fixtures__/test-project/scripts/seed.ts
  packages/create-redwood-app/templates/js/scripts/seed.js
  packages/create-redwood-app/templates/ts/scripts/seed.ts
Labels: release:fix

#11653 fix(jobs): Fixes creating worker with deleteSuccessfulJobs config setting in JobManager
  .changesets/11653.md
  packages/jobs/src/core/JobManager.ts
  packages/jobs/src/core/__tests__/JobManager.test.ts
Labels: release:fix

#11666 fix(jobs): merge job options to prevent 'undefined' values in place of defaults
  packages/jobs/src/core/Worker.ts
Labels: release:fix, changesets-ok

#11685 chore(rsc): Fix console log and add todo
  packages/router/src/rsc/clientSsr.ts
Labels: release:chore, changesets-ok, experimental

#11688 chore(rsc): Extract importRsdwServer() and move type assertions to utils
  packages/router/src/rsc/clientSsr.ts
  packages/router/src/rsc/utils.ts
Labels: release:chore, experimental

#11689 docs(deploy): fix grove command
  docs/docs/tutorial/chapter4/deployment.md
  docs/versioned_docs/version-8.3/tutorial/chapter4/deployment.md
Labels: release:docs, changesets-ok

#11693 Fix build with TS alias without basePath
  .changesets/11693.md
  packages/babel-config/src/common.ts
Labels: release:fix

#11691 Properly kill dev api-server
  .changesets/11691.md
  packages/api-server/src/buildManager.ts
  packages/api-server/src/serverManager.ts
Labels: release:fix

#11701 chore(rsc): Extract RSA handling in rscRequestHandler.ts
  packages/vite/src/rsc/rscRequestHandler.ts
Labels: release:chore, fixture-ok, experimental

#11702 chore(rsc): Refactor/format code that sends Flight to Studio
  packages/vite/src/rsc/rscStudioHandlers.ts
  packages/vite/src/runFeServer.ts
Labels: release:chore, fixture-ok, experimental

#11705 chore(test-project): Update TailwindCSS to 3.4.14
  __fixtures__/test-project/web/package.json
Labels: release:chore

#11684 feat(rsc): dev server
  .changesets/11684.md
  packages/router/ambient.d.ts
  packages/router/src/rsc/RscCache.ts
  packages/router/src/rsc/clientSsr.ts
  packages/router/src/rsc/utils.ts
  packages/vite/ambient.d.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/lib/registerFwGlobalsAndShims.ts
  packages/vite/src/plugins/vite-plugin-rsc-ssr-router-import.ts
  packages/vite/src/rsc/rscRenderer.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscWebSocketServer.ts
  packages/vite/src/rsc/utils.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:feature, experimental
