Repository redwoodjs/graphql, pull requests merged in 2024-04, with the labels that each got.

#10393 chore(ci): Fix bug related to when setting the detectChanges `code` output
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore, changesets-ok

#10394 chore(ci): detectChanges: Iterate on merge commit handling
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore, changesets-ok

#10375 docs(router): Use .jsx filenames
  docs/docs/router.md
Labels: release:docs, changesets-ok

#10378 chore(deps): Upgrade `lru-cache`
  packages/structure/package.json
  packages/structure/src/x/ts-morph.ts
  yarn.lock
Labels: release:chore, changesets-ok

#10377 chore(changesets): Automatically find PR number
  tasks/changesets/changesets.mts
  tasks/changesets/changesetsHelpers.mts
Labels: release:chore, changesets-ok

#10361 chore(babel-config): switch to vitest
  packages/babel-config/dist.test.ts
  packages/babel-config/package.json
  packages/babel-config/src/__tests__/api.test.ts
  packages/babel-config/src/__tests__/tsconfigParsing.test.ts
  packages/babel-config/src/api.ts
  packages/babel-config/src/plugins/__tests__/__fixtures__/__fixtures__/a.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/__fixtures__/a.test.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/__fixtures__/b.ts
  packages/babel-config/src/plugins/__tests__/__fixtures__/__fixtures__/c.sdl.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/__fixtures__/nested/d.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/__fixtures__/nested/d.scenarios.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/__fixtures__/types.d.ts
  packages/babel-config/src/plugins/__tests__/__fixtures__/import-dir/import-dir-default/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/import-dir/import-dir-default/output.js
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-graphql-options-extract.test.ts
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-otel-wrapping.test.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-graphql-options-extract.ts
  packages/babel-config/vitest.config.mts
  yarn.lock
Labels: release:chore, changesets-ok

#10376 feat(router): Allow redirect routes to use route names as target
  .changesets/10376.md
  docs/docs/router.md
  packages/router/src/__tests__/redirect.test.tsx
  packages/router/src/router.tsx
Labels: release:feature

#10380 docs(router): NavLink wording improvements
  docs/docs/router.md
Labels: release:docs, changesets-ok

#10395 Middleware Routing & `registerMiddleware`
  .changesets/10395.md
  packages/vite/package.json
  packages/vite/src/devFeServer.ts
  packages/vite/src/middleware/invokeMiddleware.test.ts
  packages/vite/src/middleware/invokeMiddleware.ts
  packages/vite/src/middleware/register.test.ts
  packages/vite/src/middleware/register.ts
  packages/vite/src/middleware/types.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/utils.ts
  yarn.lock
Labels: release:feature

#10404 fix(rw-eslint): Implement more specific checking on Routes
  .changesets/10404.md
  packages/eslint-plugin/src/__tests__/unsupported-route-components.test.ts
  packages/eslint-plugin/src/unsupported-route-components.ts
Labels: release:fix

#10411 RSC: Add comment explaining `use()`
  packages/vite/src/client.ts
Labels: release:chore, changesets-ok

#10412 SSR: Better ServerEntry types
  .changesets/10412.md
  __fixtures__/test-project-rsa/web/src/entry.server.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/entry.server.tsx
  packages/cli/src/commands/experimental/templates/streamingSsr/entry.server.tsx.template
  packages/vite/src/middleware/register.ts
  packages/vite/src/middleware/types.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/vite/src/types.ts
  packages/vite/src/utils.ts
  packages/web/ambient.d.ts
Labels: release:fix, fixture-ok

#10415 chore(middleware): Fix some internal types, spelling etc
  .vscode/settings.json
  packages/vite/src/middleware/CookieJar.ts
  packages/vite/src/middleware/register.test.ts
Labels: release:chore, changesets-ok

#10416 chore(route-manifest): Add relativeFilePath to route manifest
  packages/internal/src/routes.ts
  packages/vite/src/buildRouteManifest.ts
Labels: release:chore, changesets-ok

#10424 chore(whatwg-fetch): Switch to importing instead of requiring
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/testing/src/web/__tests__/MockHandlers.test.tsx
Labels: release:chore, changesets-ok

#10426 chore(framework-tools): Warn about missing metafile
  packages/framework-tools/src/buildDefaults.ts
Labels: release:chore, changesets-ok

#10427 chore(deps): Update vite to 5.2.8
  packages/forms/src/index.tsx
  packages/vite/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10220 chore(rsc): simplify `noExternals` config
  packages/vite/src/rsc/rscBuildAnalyze.ts
Labels: release:chore, changesets-ok

#10428 chore(refactor): Split rwjs/forms up into several smaller logical units
  packages/forms/src/CheckboxField.tsx
  packages/forms/src/FieldError.tsx
  packages/forms/src/FieldProps.ts
  packages/forms/src/Form.tsx
  packages/forms/src/InputComponents.tsx
  packages/forms/src/Label.tsx
  packages/forms/src/SelectField.tsx
  packages/forms/src/ServerErrorsContext.tsx
  packages/forms/src/Submit.tsx
  packages/forms/src/TextAreaField.tsx
  packages/forms/src/coercion.ts
  packages/forms/src/index.tsx
  packages/forms/src/useErrorStyles.ts
  packages/forms/src/useRegister.ts
Labels: release:chore, changesets-ok

#10430 chore(web): .js imports to prep for ESM
  packages/web/src/apollo/index.tsx
  packages/web/src/apollo/suspense.tsx
  packages/web/src/components/FetchConfigProvider.test.tsx
  packages/web/src/components/MetaTags.tsx
  packages/web/src/components/Metadata.test.tsx
  packages/web/src/components/Metadata.tsx
  packages/web/src/components/PortalHead.tsx
  packages/web/src/components/cell/CellErrorBoundary.tsx
  packages/web/src/components/cell/createCell.test.tsx
  packages/web/src/components/cell/createCell.tsx
  packages/web/src/components/cell/createServerCell.tsx
  packages/web/src/components/cell/createSuspendingCell.test.tsx
  packages/web/src/components/cell/createSuspendingCell.tsx
  packages/web/src/components/cell/isCellEmpty.tsx
  packages/web/src/components/portalHead.test.tsx
  packages/web/src/index.ts
  packages/web/src/routeHooks.types.ts
Labels: release:chore, changesets-ok

#10431 chore(web): Fix .d.ts overwrite build issue
  packages/web/ambient.d.ts
  packages/web/src/components/htmlTags.tsx
Labels: release:chore, changesets-ok

#10429 RSC: Explain noExternal vite config option
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildForServer.ts
Labels: release:chore, changesets-ok

#10432 chore(ci): get ci running on next
  .github/actions/detect-changes/detectChanges.mjs
Labels: release:chore, changesets-ok

#10418 fix(middleware): Handle POST requests in middleware router too
  .changesets/10418.md
  packages/vite/src/devFeServer.ts
  packages/vite/src/middleware/createMiddlewareRouter.test.ts
  packages/vite/src/middleware/register.ts
  packages/vite/src/runFeServer.ts
Labels: release:fix

#10355 fix(vercel): write `vercel.json` as a part of setup
  .changesets/10355.md
  packages/cli/src/commands/setup/deploy/providers/vercel.js
Labels: release:fix

#10436 fix(vercel): specify build env vars as a string
  packages/cli/src/commands/setup/deploy/providers/vercel.js
Labels: release:fix, changesets-ok

#10359 fix(cli): only show webpack options for dev if `bundler = "webpack"`
  .changesets/10359.md
  packages/cli/src/commands/dev.js
Labels: release:breaking

#10437 chore: make crwa e2e test work across branches
  packages/create-redwood-app/tests/e2e.test.ts
Labels: release:chore, changesets-ok

#10405 Update rbac.md - code match
  docs/docs/tutorial/chapter7/rbac.md
Labels: release:fix, changesets-ok

#10442 fix(auth): Handle when authorization header is lowercased
  .changesets/10442.md
  packages/api/src/auth/__tests__/parseAuthorizationHeader.test.ts
  packages/api/src/auth/index.ts
Labels: release:fix

#10439 feat(og-gen): Adds package and vite plugin for dynamic og generation
  .changesets/10439.md
  packages/ogimage-gen/.gitignore
  packages/ogimage-gen/build.mts
  packages/ogimage-gen/cjsWrappers/plugin.js
  packages/ogimage-gen/package.json
  packages/ogimage-gen/src/vite-plugin-ogimage-gen.test.ts
  packages/ogimage-gen/src/vite-plugin-ogimage-gen.ts
  packages/ogimage-gen/tsconfig.json
  yarn.lock
Labels: release:feature, fixture-ok

#10441 feat(og-gen): Update implementation of useLocation | Update App template
  .changesets/10441.md
  __fixtures__/empty-project/web/src/App.tsx
  __fixtures__/test-project/web/src/App.tsx
  packages/create-redwood-app/templates/js/web/src/App.jsx
  packages/create-redwood-app/templates/ts/web/src/App.tsx
  packages/ogimage-gen/package.json
  packages/prerender/src/runPrerender.tsx
  packages/router/src/location.tsx
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/web/src/components/__tests__/FetchConfigProvider.test.tsx
  packages/web/src/components/__tests__/GraphQLHooksProvider.test.tsx
  packages/web/src/components/__tests__/Metadata.test.tsx
  packages/web/src/components/__tests__/PortalHead.test.tsx
Labels: release:feature

#10450 chore: remove aws-lambda
  packages/api-server/package.json
  packages/graphql-server/package.json
  packages/graphql-server/src/functions/__tests__/fixtures/auth.ts
  yarn.lock
Labels: release:chore, changesets-ok

#10451 (docs) Fix useCache headers and links
  docs/docs/graphql.md
Labels: release:docs, changesets-ok

#10455 fix(ssr): Successfully serve static assets like `favicon.png`
  packages/vite/src/runFeServer.ts
  tasks/smoke-tests/dev/tests/staticAssets.spec.ts
  tasks/smoke-tests/rsc-dev/tests/staticAssets.spec.ts
  tasks/smoke-tests/rsc/tests/staticAssets.spec.ts
  tasks/smoke-tests/serve/tests/staticAssets.spec.ts
  tasks/smoke-tests/shared/staticAssets.ts
  tasks/smoke-tests/streaming-ssr-dev/tests/staticAssets.spec.ts
  tasks/smoke-tests/streaming-ssr-prod/tests/staticAssets.spec.ts
Labels: release:fix, changesets-ok

#10458 chore(auth): Build: Put ESM at the root, and CJS in /cjs
  packages/auth/build.ts
  packages/auth/package.json
  packages/auth/tsconfig.build-cjs.json
  packages/auth/tsconfig.build-esm.json
Labels: release:chore, changesets-ok

#10444 feat(server-auth): Part 1/3: dbAuth middleware support (web side changes)
  .changesets/10444.md
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.middleware.test.ts
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.test.ts
  packages/auth-providers/dbAuth/web/src/dbAuth.ts
  packages/auth-providers/dbAuth/web/src/getCurrentUserFromMiddleware.ts
  packages/auth/src/AuthImplementation.ts
  packages/auth/src/AuthProvider/useReauthenticate.ts
Labels: release:feature

#10434 chore(refactor): Split the router out into smaller logical units
  packages/router/src/Route.tsx
  packages/router/src/__tests__/pageLoadingContext.test.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/active-route-loader.tsx
  packages/router/src/page.ts
  packages/router/src/route-validators.tsx
  packages/router/src/router.tsx
  packages/router/src/util.ts
Labels: release:chore, changesets-ok

#10401 docs(router): Document new NavLink className replacement behavior
  docs/docs/router.md
Labels: release:docs, changesets-ok

#10457 feat(server-auth): dbAuth 3/3 - handle login, logout, signup, etc. requests if forwarded from middleware
  .changesets/10457.md
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.fetch.test.js
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
  packages/auth-providers/dbAuth/api/src/__tests__/buildDbAuthResponse.test.ts
  packages/auth-providers/dbAuth/api/src/shared.ts
Labels: release:feature

#10462 chore(router): route-validators: types and comments
  packages/router/src/route-validators.tsx
Labels: release:chore, changesets-ok

#10463 chore(router): Prevent circular dependency for namedRoutes
  packages/router/src/AuthenticatedRoute.tsx
  packages/router/src/index.ts
  packages/router/src/namedRoutes.ts
  packages/router/src/router.tsx
Labels: release:chore, changesets-ok

#10460 chore(dbauth-mw): Refactor web side dbAuth creation
  .changesets/10460.md
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.middleware.test.ts
  packages/auth-providers/dbAuth/web/src/dbAuth.ts
Labels: release:chore

#10464 fix(router): Remove barrel exports from router.tsx
  .changesets/10464.md
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/__tests__/redirect.test.tsx
  packages/router/src/__tests__/route-announcer.test.tsx
  packages/router/src/__tests__/route-focus.test.tsx
  packages/router/src/__tests__/route-validators.test.tsx
  packages/router/src/__tests__/routeScrollReset.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/__tests__/useRoutePaths.test.tsx
  packages/router/src/index.ts
  packages/router/src/router.tsx
  packages/testing/src/web/MockRouter.tsx
Labels: release:breaking

#10467 chore(location): Accept URL-like object
  packages/router/src/location.tsx
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:chore, changesets-ok

#10465 feat(server-auth): Update getAuthenticationContext to support cookies and tokens both
  .changesets/10465.md
  packages/api/package.json
  packages/api/src/auth/__tests__/getAuthenticationContext.test.ts
  packages/api/src/auth/index.ts
  packages/web/src/apollo/links.tsx
  packages/web/src/components/FetchConfigProvider.tsx
  packages/web/src/components/__tests__/FetchConfigProvider.test.tsx
  packages/web/testing-library.d.ts
  packages/web/tsconfig.json
  yarn.lock
Labels: release:feature

#10471 chore(paths): Remove outdated comment
  packages/project-config/src/paths.ts
Labels: release:chore, changesets-ok

#10473 Revert "chore(location): Accept URL-like object"
  packages/router/src/location.tsx
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:chore, changesets-ok

#10475 chore(filepath): Use node:url to convert to file path
  packages/vite/src/middleware/createMiddlewareRouter.test.ts
  packages/vite/src/utils.ts
Labels: release:chore, changesets-ok

#10476 chore(crwa): Fix `ts-to-js` script
  packages/create-redwood-app/scripts/tsToJS.js
Labels: release:chore, changesets-ok

#10478 fix(cli): await async prettier functions
  packages/cli/src/commands/experimental/setupOpentelemetryHandler.js
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/setupStreamingSsrHandler.js
  packages/cli/src/commands/generate/model/model.js
  packages/cli/src/commands/generate/realtime/realtimeHandler.js
  packages/cli/src/commands/setup/graphql/features/fragments/__codemod_tests__/appGqlConfigTransform.test.ts
  packages/cli/src/commands/setup/graphql/features/fragments/fragmentsHandler.ts
  packages/cli/src/commands/setup/mailer/mailerHandler.js
  packages/cli/src/commands/setup/realtime/realtimeHandler.js
  packages/cli/src/commands/setup/server-file/serverFileHandler.js
  packages/cli/src/commands/setup/ui/libraries/mantine.js
  packages/cli/src/commands/setup/vite/viteHandler.js
  packages/cli/src/lib/__tests__/mergeConfig.test.js
  packages/cli/src/lib/configureStorybook.js
  packages/cli/src/lib/index.js
  packages/cli/src/lib/merge/index.js
  packages/cli/src/testLib/prettify.ts
  packages/cli/src/testLib/ts2js.ts
  packages/cli/src/testUtils/index.ts
  packages/cli/src/testUtils/matchFolderTransform.ts
  packages/cli/src/testUtils/matchInlineTransformSnapshot.ts
  packages/cli/testUtils.d.ts
  packages/cli/vitest.codemods.setup.ts
  packages/codemods/src/testUtils/index.ts
Labels: release:fix, changesets-ok

#10453 feat: Remove `--performance` option from `yarn rw build`
  .changesets/10453.md
  packages/cli/src/commands/build.js
  packages/cli/src/commands/buildHandler.js
  packages/core/config/webpack.perf.js
  packages/core/package.json
  yarn.lock
Labels: release:breaking

#10474 chore(tests): add use location typetests to prevent regressions
  packages/router/src/__typetests__/useLocation.test.ts
Labels: release:chore, changesets-ok

#10447 feat: redwoodjs/auth-dbauth-middleware - Part 2/3 - Auth Middleware for dbAuth to authenticate users via cookie
  .changesets/10447.md
  packages/api/src/auth/index.ts
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/middleware/README.md
  packages/auth-providers/dbAuth/middleware/build.mts
  packages/auth-providers/dbAuth/middleware/cjsWrappers/plugin.js
  packages/auth-providers/dbAuth/middleware/package.json
  packages/auth-providers/dbAuth/middleware/src/__tests__/createDbAuthMiddleware.test.ts
  packages/auth-providers/dbAuth/middleware/src/index.ts
  packages/auth-providers/dbAuth/middleware/tsconfig.json
  packages/auth-providers/dbAuth/middleware/vitest.config.mts
  yarn.lock
Labels: release:feature

#10480 RSC: Clean up some comments and logs
  packages/router/src/server-router.tsx
  packages/vite/src/plugins/vite-plugin-rsc-css-preinit.ts
  packages/vite/src/rsc/rscBuildForServer.ts
Labels: release:chore, changesets-ok

#10479 fix(cli): avoid `npx` during upgrade command
  .changesets/10479.md
  packages/cli/src/commands/upgrade.js
Labels: release:fix, fixture-ok

#10486 Move .mdx import into separate file
  docs/docs/ReactPlayer.jsx
  docs/docs/project-configuration-dev-test-build.mdx
Labels: release:docs, fixture-ok, changesets-ok

#10484 chore(ssr): Switch to use `@apollo/client-react-streaming` package
  .vscode/settings.json
  packages/cli/src/commands/experimental/setupStreamingSsrHandler.js
  packages/web/package.json
  packages/web/src/apollo/suspense.tsx
  packages/web/src/components/ServerInject.tsx
  yarn.lock
Labels: release:chore, changesets-ok

#10487 RSC: Remove unused vite patch from test-project-rsa
  __fixtures__/test-project-rsa/.yarn/patches/vite-npm-4.4.9-e845c1bbf8.patch
  __fixtures__/test-project-rsa/package.json
Labels: release:chore, changesets-ok

#10488 RSC: Update test projects to use new @apollo/client-react-streaming
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
Labels: release:chore, changesets-ok

#10489 chore(renovate): Remove config for unused package
  .github/renovate.json
Labels: release:chore, changesets-ok

#10481 RSC: css preinit: Add required option precedence
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-css-preinit.test.mts
  packages/vite/src/plugins/vite-plugin-rsc-css-preinit.ts
Labels: release:fix, changesets-ok

#10490 chore(dataMigrate): Fix package.json directory value
  packages/cli-packages/dataMigrate/package.json
Labels: release:chore, changesets-ok

#10482 fix(deps): update React to latest canary 19.x
  .github/workflows/ci.yml
  .yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  .yarn/patches/@storybook-react-dom-shim-npm-7.6.17-789bc900f0.patch
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/test-project-rsa/.yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/.yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
  __fixtures__/test-project/.yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  __fixtures__/test-project/.yarn/patches/@storybook-react-dom-shim-npm-7.6.17-789bc900f0.patch
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
  package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/.yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  packages/create-redwood-app/templates/js/.yarn/patches/@storybook-react-dom-shim-npm-7.6.17-789bc900f0.patch
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/.yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  packages/create-redwood-app/templates/ts/.yarn/patches/@storybook-react-dom-shim-npm-7.6.17-789bc900f0.patch
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/create-redwood-app/tests/templates.test.ts
  packages/forms/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:fix, changesets-ok

#10491 fix(upgrade): Download yarn patches
  packages/cli/src/commands/upgrade.js
Labels: release:fix, changesets-ok

#10468 Modified type for describeScenario
  packages/testing/src/api/scenario.ts
Labels: topic/testing, topic/typescript, release:fix

#10495 Revert React 19 upgrade (#10482 and #10491)
  .github/workflows/ci.yml
  .yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  .yarn/patches/@storybook-react-dom-shim-npm-7.6.17-789bc900f0.patch
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/test-project-rsa/.yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/.yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
  __fixtures__/test-project/.yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  __fixtures__/test-project/.yarn/patches/@storybook-react-dom-shim-npm-7.6.17-789bc900f0.patch
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
  package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/cli/src/commands/upgrade.js
  packages/create-redwood-app/templates/js/.yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  packages/create-redwood-app/templates/js/.yarn/patches/@storybook-react-dom-shim-npm-7.6.17-789bc900f0.patch
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/.yarn/patches/@apollo-client-npm-3.9.9-15c2e13518.patch
  packages/create-redwood-app/templates/ts/.yarn/patches/@storybook-react-dom-shim-npm-7.6.17-789bc900f0.patch
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/create-redwood-app/tests/templates.test.ts
  packages/forms/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10497 fix(upgrade): Download yarn patches
  packages/cli/src/commands/upgrade.js
Labels: release:feature, changesets-ok

#10496 fix(deps): update React to latest canary 19.x
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
  package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10493 feat(cookieJar): Change cookie.get to directly return value
  .changesets/10493.md
  packages/vite/src/middleware/CookieJar.test.ts
  packages/vite/src/middleware/CookieJar.ts
  packages/vite/src/middleware/MiddlewareRequest.test.ts
  packages/vite/src/middleware/register.test.ts
Labels: release:feature

#10498 feat(server-auth): WebAuthN support during SSR
  .changesets/10498.md
  packages/auth-providers/dbAuth/web/src/webAuthn.ts
  packages/auth/src/AuthProvider/AuthProvider.tsx
  packages/auth/src/AuthProvider/AuthProviderState.ts
  packages/auth/src/AuthProvider/ServerAuthProvider.tsx
  packages/auth/src/AuthProvider/useLogIn.ts
  packages/vite/src/middleware/MiddlewareRequest.ts
  packages/vite/src/middleware/invokeMiddleware.test.ts
  packages/vite/src/middleware/invokeMiddleware.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
Labels: release:feature

#10503 fix(rsc): Disable RSC CSS loading plugin
  packages/vite/src/rsc/rscBuildForServer.ts
  tasks/smoke-tests/rsc-dev/tests/rsc.spec.ts
  tasks/smoke-tests/rsc-external-packages-and-cells/tests/rsc-external-packages-and-cells.spec.ts
  tasks/smoke-tests/rsc/tests/rsc.spec.ts
Labels: release:fix, fixture-ok, changesets-ok

#10504 Fix invisible tags in MetaTag & Metadata JSDoc
  .changesets/10504.md
  packages/web/src/components/MetaTags.tsx
  packages/web/src/components/Metadata.tsx
Labels: release:fix

#10507 Fix typo in Azure setup command description
  packages/auth-providers/azureActiveDirectory/setup/src/setup.ts
Labels: release:chore, changesets-ok

#10508 Fixed typo
  README.md
Labels: release:chore, changesets-ok

#10512 chore(tests): Fix `act` import warning
  packages/router/src/__tests__/useRoutePaths.test.tsx
Labels: release:chore, changesets-ok

#10515 feat(upgrade): Use GitHub token if available when downloading patches
  .changesets/10515.md
  packages/cli/src/commands/upgrade.js
Labels: release:feature

#10514 chore(deps): Upgrade to React Testing Library 14.3.1
  package.json
  packages/auth/package.json
  packages/forms/package.json
  packages/testing/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10513 chore(deps): Upgrade to React canary 20240424
  __fixtures__/fragment-test-project/web/package.json
  __fixtures__/test-project-rsa/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/router/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#10502 fix(dbauth-mw): Unset cookie instead of clearing
  .changesets/10502.md
  packages/auth-providers/dbAuth/middleware/src/__tests__/createDbAuthMiddleware.test.ts
  packages/auth-providers/dbAuth/middleware/src/index.ts
Labels: release:fix

#10517 chore(tests): Fix packages/web tests
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/package.json
  __fixtures__/test-project/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
Labels: release:chore, changesets-ok

#10518 Add redwood.toml to `yarn rw info`
  .changesets/10518.md
  .vscode/settings.json
  packages/cli/src/commands/__tests__/info.test.js
  packages/cli/src/commands/info.js
Labels: release:feature

#10469 feat(og-gen): Implement middleware and hooks
  .changesets/10469.md
  .vscode/settings.json
  __fixtures__/test-project/web/src/App.tsx
  __fixtures__/test-project/web/src/entry.client.tsx
  packages/cli/src/commands/experimental/templates/streamingSsr/entry.client.tsx.template
  packages/cli/src/commands/experimental/templates/streamingSsr/entry.server.tsx.template
  packages/cli/src/commands/setup/graphql/features/fragments/__codemod_tests__/appGqlConfigTransform.test.ts
  packages/cli/src/lib/index.js
  packages/core/config/webpack.common.js
  packages/create-redwood-app/templates/js/web/src/App.jsx
  packages/create-redwood-app/templates/js/web/src/entry.client.jsx
  packages/create-redwood-app/templates/ts/web/src/App.tsx
  packages/create-redwood-app/templates/ts/web/src/entry.client.tsx
  packages/internal/src/routes.ts
  packages/ogimage-gen/cjsWrappers/hooks.js
  packages/ogimage-gen/cjsWrappers/middleware.js
  packages/ogimage-gen/package.json
  packages/ogimage-gen/src/OgImageMiddleware.test.ts
  packages/ogimage-gen/src/OgImageMiddleware.ts
  packages/ogimage-gen/src/getRoutesList.ts
  packages/ogimage-gen/src/hooks.test.ts
  packages/ogimage-gen/src/hooks.ts
  packages/ogimage-gen/src/vite-plugin-ogimage-gen.test.ts
  packages/ogimage-gen/src/vite-plugin-ogimage-gen.ts
  packages/ogimage-gen/tsconfig.json
  packages/prerender/src/runPrerender.tsx
  packages/vite/src/devFeServer.ts
  packages/vite/src/middleware/index.ts
  packages/vite/src/middleware/types.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/web/src/entry/index.js
  yarn.lock
Labels: release:feature

#10523 chore(deps): Stop using PR build of rehackt - use proper version
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
Labels: release:chore, changesets-ok

#10505 Fix broken Azure / MSAL documentation links
  docs/docs/auth/azure.md
Labels: release:docs

#10524 chore(cli): Wrap NodeSSH to make sshExec an instance method
  .vscode/settings.json
  packages/cli/src/commands/deploy/baremetal.js
  packages/cli/src/commands/deploy/baremetal/SshExecutor.js
Labels: release:chore, changesets-ok

#10526 Fix typos in seo-head (`<Metadata />`) docs
  docs/docs/seo-head.md
Labels: release:docs, changesets-ok

#10525 feat(baremetal): Add verbose output to ssh exec
  .changesets/10525.md
  packages/cli/src/commands/deploy/baremetal.js
  packages/cli/src/commands/deploy/baremetal/SshExecutor.js
Labels: release:feature

#10527 feat(baremetal): Add more details to error messages
  .changesets/10527.md
  packages/cli/src/commands/deploy/baremetal/SshExecutor.js
Labels: release:feature

#10529 chore(server-auth): Automagic middleware auth on supported providers (dbAuth so far)
  .changesets/10529.md
  packages/auth-providers/dbAuth/web/ambient.d.ts
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.middleware.test.ts
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.test.ts
  packages/auth-providers/dbAuth/web/src/dbAuth.ts
  packages/auth/src/AuthImplementation.ts
  packages/auth/src/AuthProvider/useReauthenticate.ts
Labels: release:chore
