Repository redwoodjs/graphql, pull requests merged in 2024-01, with the labels that each got.

#9787 fix(crwa): use `fs.renameSync` instead of `fs.rename`
  .github/workflows/ci.yml
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix, fixture-ok

#9788 fix(dbAuth): Correct hardcoded DB column
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
Labels: release:fix

#9791 Use regex to make test pass in VSCode
  packages/cli-packages/dataMigrate/src/__tests__/install.test.ts
Labels: release:chore

#9792 Router: Use a single RouterContext
  packages/router/src/router-context.tsx
Labels: release:chore

#9790 useRoutePath(): Get the path for the current route by default
  docs/docs/router.md
  packages/router/src/__tests__/useRoutePaths.test.tsx
  packages/router/src/useRoutePaths.ts
Labels: release:feature

#9794 fix(fastify): Prevent duplicate `@fastify/url-data` registration
  packages/api-server/src/plugins/withFunctions.ts
  packages/api-server/src/plugins/withWebServer.ts
  packages/fastify/src/api.ts
  packages/fastify/src/graphql.ts
  packages/fastify/src/web.ts
  packages/web-server/src/web.ts
Labels: release:fix

#9793 Add routeParams to useMatch
  docs/docs/router.md
  packages/router/src/__tests__/useMatch.test.tsx
  packages/router/src/useMatch.ts
Labels: release:feature

#9795 chore(data-migration): Fix test exit code
  packages/cli-packages/dataMigrate/src/__tests__/upHandler.test.ts
Labels: release:chore

#9796 data migrate: Clean up upHandler test
  packages/cli-packages/dataMigrate/src/__tests__/upHandler.test.ts
Labels: release:chore

#9802 docs(fragments): Typo, grammar and formatting fixes
  docs/docs/graphql/fragments.md
Labels: release:docs

#9803 chore: bump TSTyche
  package.json
  packages/router/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore

#9804 Use TS for rebuild-test-project-fixture script
  __fixtures__/test-project/web/package.json
  package.json
  tasks/test-project/rebuild-test-project-fixture.ts
  tasks/test-project/typing.js
  tasks/test-project/typing.ts
Labels: release:chore

#9806 chore(cli): More robust isAwaitable
  tasks/test-project/typing.ts
Labels: release:chore

#9808 fix(server): error early on incompatible config (apiHost and apiUrl)
  packages/cli/src/commands/serveWebHandler.js
  packages/web-server/src/server.ts
Labels: release:fix

#9811 yarn rw setup graphql fragments
  .eslintrc.js
  docs/docs/cli-commands.md
  docs/docs/graphql/fragments.md
  packages/cli-helpers/src/lib/index.ts
  packages/cli/jest.config.js
  packages/cli/jest.config.ts
  packages/cli/package.json
  packages/cli/src/commands/setup/graphql/features/fragments/__codemod_tests__/appGqlConfigTransform.test.ts
  packages/cli/src/commands/setup/graphql/features/fragments/__codemod_tests__/appImportTransform.test.ts
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/config-simple/input/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/config-simple/output/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/existingImport/input/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/existingImport/output/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/existingPropInline/input/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/existingPropInline/output/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/existingPropVariable/input/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/existingPropVariable/output/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/existingPropVariableCustomName/input/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/existingPropVariableCustomName/output/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/existingPropVariableNoCacheConfig/input/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/existingPropVariableNoCacheConfig/output/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/import-simple/input/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__testfixtures__/import-simple/output/App.tsx
  packages/cli/src/commands/setup/graphql/features/fragments/__tests__/fragmentsHandler.test.ts
  packages/cli/src/commands/setup/graphql/features/fragments/appGqlConfigTransform.ts
  packages/cli/src/commands/setup/graphql/features/fragments/appImportTransform.ts
  packages/cli/src/commands/setup/graphql/features/fragments/fragments.ts
  packages/cli/src/commands/setup/graphql/features/fragments/fragmentsHandler.ts
  packages/cli/src/commands/setup/graphql/features/fragments/runTransform.ts
  packages/cli/src/commands/setup/graphql/graphql.ts
  packages/cli/src/jest.codemods.setup.ts
  packages/cli/src/testLib/cells.ts
  packages/cli/src/testLib/fetchFileFromTemplate.ts
  packages/cli/src/testLib/getFilesWithPattern.ts
  packages/cli/src/testLib/getRootPackageJSON.ts
  packages/cli/src/testLib/isTSProject.ts
  packages/cli/src/testLib/prettify.ts
  packages/cli/src/testLib/runTransform.ts
  packages/cli/src/testLib/ts2js.ts
  packages/cli/src/testUtils/index.ts
  packages/cli/src/testUtils/matchFolderTransform.ts
  packages/cli/src/testUtils/matchInlineTransformSnapshot.ts
  packages/cli/src/testUtils/matchTransformSnapshot.ts
  packages/cli/testUtils.d.ts
  packages/cli/tsconfig.json
  packages/codemods/README.md
Labels: release:feature, fixture-ok

#9821 fragments setup: newline fix + refactor->rename
  packages/cli/src/commands/setup/graphql/features/fragments/__tests__/fragmentsHandler.test.ts
  packages/cli/src/commands/setup/graphql/features/fragments/fragmentsHandler.ts
Labels: release:fix, fixture-ok

#9822 Update cli tsconfig to reference used packages
  packages/cli/tsconfig.json
Labels: release:chore

#9800 feat: Adds Setup CLI Command to Configure GraphQL Trusted Documents
  docs/docs/cli-commands.md
  docs/docs/graphql/trusted-documents.md
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__codemod_tests__/grapqlTransform.test.ts
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__testfixtures__/alreadySetUp/input/graphql.js
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__testfixtures__/alreadySetUp/output/graphql.js
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__testfixtures__/graphql/input/graphql.js
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__testfixtures__/graphql/output/graphql.js
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/__fixtures__/toml/default.toml
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/__fixtures__/toml/fragments.toml
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/__fixtures__/toml/fragments_no_space_equals.toml
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/__fixtures__/toml/trusted_docs_already_setup.toml
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/__fixtures__/toml/trusted_docs_commented_graphql.toml
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/__fixtures__/toml/trusted_docs_fragments_already_setup.toml
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/__fixtures__/toml/trusted_docs_no_space_equals.toml
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/__snapshots__/trustedDocuments.test.ts.snap
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/trustedDocuments.test.ts
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/graphqlTransform.ts
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/trustedDocuments.ts
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/trustedDocumentsHandler.ts
  packages/cli/src/commands/setup/graphql/graphql.ts
Labels: release:feature, fixture-ok

#9819 graphql setup fragments: Move telemetry to main handler
  packages/cli/src/commands/setup/graphql/features/fragments/fragments.ts
  packages/cli/src/commands/setup/graphql/features/fragments/fragmentsHandler.ts
Labels: release:fix, fixture-ok

#9823 cli: add missing dep jscodeshift
  packages/cli/package.json
  yarn.lock
Labels: release:fix

#9826 Add trusted-documents to fragments CI smoke-test
  .github/workflows/ci.yml
  tasks/test-project/set-up-trusted-documents.ts
Labels: release:chore

#9827 Remove unused Fastify plugin
  packages/fastify/build.mjs
  packages/fastify/src/plugins/withApiProxy.ts
Labels: release:chore

#9828 Fastify config: Use exact file extension in log message
  packages/fastify/src/config.ts
Labels: release:feature

#9829 exp setup sentry: Fix file extension
  packages/cli/src/commands/experimental/setupSentryHandler.js
Labels: release:fix

#9831 Tweak graphiql setup messages
  packages/cli/src/commands/setup/graphiql/__tests__/graphiqlHandler.test.js
  packages/cli/src/commands/setup/graphiql/graphiqlHandler.js
  packages/cli/src/commands/setup/graphiql/supportedProviders.js
Labels: release:fix, fixture-ok

#9832 Add cli-helpers util to update redwood.toml
  packages/cli-helpers/src/lib/__tests__/project.test.ts
  packages/cli-helpers/src/lib/project.ts
  packages/cli/src/commands/setup/graphql/features/fragments/__tests__/fragmentsHandler.test.ts
  packages/cli/src/commands/setup/graphql/features/fragments/fragmentsHandler.ts
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/trustedDocumentsHandler.ts
Labels: release:feature, fixture-ok

#9833 Add missing cli-helpers test file
  packages/cli-helpers/src/lib/__tests__/project.addTomlSetting.test.ts
Labels: release:chore, fixture-ok

#9830 setup sentry out of experimental
  packages/cli-helpers/src/lib/index.ts
  packages/cli/src/commands/experimental/setupSentry.js
  packages/cli/src/commands/setup/monitoring/monitoring.ts
  packages/cli/src/commands/setup/monitoring/sentry/sentry.ts
  packages/cli/src/commands/setup/monitoring/sentry/sentryHandler.ts
  tasks/test-project/set-up-trusted-documents.ts
Labels: release:feature, fixture-ok

#9836 rw-studio-impersonation-cookie
  packages/auth-providers/dbAuth/api/src/shared.ts
Labels: release:feature

#9838 Only watch inside web/ and api/
  packages/internal/src/generate/watch.ts
Labels: release:fix

#9834 check_test_project_fixture: Fail if rebuilding changes files
  .github/actions/check_test_project_fixture/action.yml
  .github/actions/check_test_project_fixture/check_test_project_fixture.mjs
  .github/actions/check_test_project_fixture/package.json
  .github/actions/check_test_project_fixture/yarn.lock
  .github/workflows/check-test-project-fixture.yml
  __fixtures__/test-project/web/package.json
Labels: release:chore, fixture-ok

#9810 Add default getCurrentUser to api/src/lib/auth
  packages/create-redwood-app/templates/js/api/src/lib/auth.js
  packages/create-redwood-app/templates/ts/api/src/lib/auth.ts
Labels: release:fix, fixture-ok

#9840 chore(fwtools): handle existing resolutions in tarsync
  tasks/framework-tools/tarsync.mjs
Labels: release:chore

#9844 Fix url query param encoding
  __fixtures__/test-project/web/package.json
  packages/router/src/__tests__/util.test.ts
  packages/router/src/util.ts
Labels: release:fix

#9767 chore(build): Avoid prebuilding api side, instead use an esbuild plugin
  .github/workflows/ci.yml
  package.json
  packages/api-server/src/watch.ts
  packages/babel-config/jest.config.js
  packages/babel-config/package.json
  packages/babel-config/src/__tests__/api.test.ts
  packages/babel-config/src/__tests__/prebuildApiFile.test.ts
  packages/babel-config/src/api.ts
  packages/babel-config/src/common.ts
  packages/babel-config/src/index.ts
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-directory-named-imports.test.ts
  packages/babel-config/tsconfig.json
  packages/cli/src/commands/buildHandler.js
  packages/cli/src/commands/deploy/__tests__/nftPack.test.js
  packages/internal/src/__tests__/build_api.test.ts
  packages/internal/src/build/api.ts
  packages/vite/src/buildFeServer.ts
  tasks/e2e/cypress.config.js
  tasks/e2e/cypress/e2e/04-logger/logger.cy.js
  tasks/e2e/cypress/support/e2e.js
  tasks/run-e2e
  yarn.lock
Labels: release:chore

#9846 mapPrismaScalarToPagePropTsType: Fix Decimal test case
  packages/cli/src/commands/generate/__tests__/helpers.test.js
Labels: release:chore

#9849 packages/cli: Switch from substr (deprecated) to slice
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/generate/service/templates/test.ts.template
Labels: release:chore

#9847 Add support for Prisma Bytes and GraphQL scalar Byte
  __fixtures__/example-todo-main/web/src/graphql/graphql.ts
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/sdl/__tests__/__snapshots__/sdl.test.js.snap
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/sdl/__tests__/sdl.test.js
  packages/cli/src/commands/generate/sdl/sdl.js
  packages/cli/src/commands/generate/service/service.js
  packages/cli/src/commands/generate/service/templates/test.ts.template
  packages/graphql-server/src/rootSchema.ts
  packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
  packages/internal/src/__tests__/__snapshots__/graphqlSchema.test.ts.snap
  packages/internal/src/__tests__/graphqlCodeGen.test.ts
  packages/internal/src/__tests__/graphqlSchema.test.ts
  packages/internal/src/generate/generate.ts
  packages/internal/src/generate/graphqlCodeGen.ts
Labels: release:feature

#9850 docs(typo): correct grammar in realtime docs
  docs/docs/realtime.md
Labels: release:docs

#9841 Improve how the api-server watch command works
  packages/api-server/src/watch.ts
  packages/cli/src/commands/__tests__/dev.test.js
  packages/cli/src/commands/devHandler.js
Labels: release:fix

#9853 chore(api): Switch to use vitest over jest
  .github/workflows/ci.yml
  package.json
  packages/api/__mocks__/@prisma/client.js
  packages/api/__mocks__/@redwoodjs/path.js
  packages/api/package.json
  packages/api/src/__tests__/normalizeRequest.test.ts
  packages/api/src/__tests__/transforms.test.ts
  packages/api/src/auth/__tests__/getAuthenticationContext.test.ts
  packages/api/src/auth/__tests__/parseJWT.test.ts
  packages/api/src/auth/verifiers/__tests__/base64Sha1Verifier.test.ts
  packages/api/src/auth/verifiers/__tests__/base64Sha256Verifier.test.ts
  packages/api/src/auth/verifiers/__tests__/jwtVerifier.test.ts
  packages/api/src/auth/verifiers/__tests__/secretKeyVerifier.test.ts
  packages/api/src/auth/verifiers/__tests__/sha1Verifier.test.ts
  packages/api/src/auth/verifiers/__tests__/sha256Verifier.test.ts
  packages/api/src/auth/verifiers/__tests__/skipVerifier.test.ts
  packages/api/src/auth/verifiers/__tests__/timestampSchemeVerifier.test.ts
  packages/api/src/cache/__tests__/cache.test.ts
  packages/api/src/cache/__tests__/cacheFindMany.test.ts
  packages/api/src/cache/__tests__/deleteCacheKey.test.js
  packages/api/src/cache/__tests__/disconnect.test.ts
  packages/api/src/cache/__tests__/shared.test.ts
  packages/api/src/logger/logger.test.ts
  packages/api/src/validations/__tests__/validations.test.js
  packages/api/src/webhooks/webhooks.test.ts
  packages/api/vitest.config.mts
  packages/api/vitest.setup.mts
  yarn.lock
Labels: release:chore, fixture-ok

#9855 chore(crwa): switch to vitest
  .github/workflows/ci.yml
  packages/create-redwood-app/jest.config.js
  packages/create-redwood-app/package.json
  packages/create-redwood-app/tests/e2e.test.ts
  packages/create-redwood-app/tests/templates.test.ts
  packages/create-redwood-app/vitest.config.mts
  yarn.lock
Labels: release:chore

#9856 Fix(crwa): Exit 0 after Quit install
  packages/create-redwood-app/src/create-redwood-app.js
Labels: release:fix

#9857 chore(crwa): set `REDWOOD_CI` and `REDWOOD_DISABLE_TELEMETRY`
  .github/workflows/ci.yml
Labels: release:chore

#9845 feat(server file): add `createServer`
  packages/api-server/ambient.d.ts
  packages/api-server/dist.test.ts
  packages/api-server/package.json
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/cliHandlers.ts
  packages/api-server/src/createServer.ts
  packages/api-server/src/plugins/graphql.ts
  packages/api-server/src/plugins/lambdaLoader.ts
  packages/api-server/src/requestHandlers/awsLambdaFastify.ts
  packages/api-server/src/watch.ts
  packages/babel-config/src/api.ts
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/default-graphql-function/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/default-graphql-function/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/evil-graphql-function/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/evil-graphql-function/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/function-graphql-function/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/function-graphql-function/output.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/modified-graphql-function/code.js
  packages/babel-config/src/plugins/__tests__/__fixtures__/graphql-options-extract/modified-graphql-function/output.js
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-graphql-options-extract.test.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-graphql-options-extract.ts
  packages/cli/src/commands/experimental/setupServerFileHandler.js
  packages/cli/src/commands/experimental/templates/server.ts.template
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveApiHandler.js
  packages/cli/src/commands/serveBothHandler.js
  packages/cli/src/commands/setup/realtime/realtimeHandler.js
  packages/cli/src/commands/setup/server-file/serverFile.js
  packages/cli/src/commands/setup/server-file/serverFileHandler.js
  packages/cli/src/commands/setup/server-file/templates/server.ts.template
  packages/fastify/build.mjs
  packages/fastify/package.json
  packages/fastify/src/index.ts
  packages/graphql-server/src/types.ts
  packages/web-server/src/server.ts
  yarn.lock
Labels: release:feature

#9858 fix(studio): Upgrade to 11.0.1 and enable web-side
  packages/cli/src/commands/studioHandler.js
Labels: release:fix

#9860 fix(cli): Skip Studio when running `rw upgrade`
  packages/cli/src/commands/upgrade.js
Labels: release:fix

#9861 feat(crwa): Always install using yarn v4
  packages/create-redwood-app/src/create-redwood-app.js
  packages/create-redwood-app/tests/e2e.test.ts
Labels: release:feature

#9862 chore(crwa): update e2e test to handle yarn install patch
  packages/create-redwood-app/package.json
  packages/create-redwood-app/scripts/buildPack.js
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/create-redwood-app/tests/e2e.test.ts
  packages/create-redwood-app/tests/e2e_prompts.sh
  packages/create-redwood-app/tests/e2e_prompts_git.sh
  packages/create-redwood-app/tests/e2e_prompts_m.sh
  packages/create-redwood-app/tests/e2e_prompts_node_greater.sh
  packages/create-redwood-app/tests/e2e_prompts_node_less.sh
  packages/create-redwood-app/tests/e2e_prompts_overwrite.sh
  packages/create-redwood-app/tests/e2e_prompts_ts.sh
Labels: release:chore

#9865 chore(ci): Fix CRWA telemetry check
  .github/actions/telemetry_check/check.mjs
Labels: release:chore

#9864 chore(project-config): switch to vitest
  packages/project-config/.babelrc.js
  packages/project-config/jest.config.js
  packages/project-config/package.json
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/vitest.config.mts
  yarn.lock
Labels: release:chore

#9706 `describeScenario` docs
  docs/docs/testing.md
Labels: release:docs

#9867 chore: switch some more packages to vitest
  packages/mailer/core/package.json
  packages/mailer/core/src/__tests__/mailer.test.ts
  packages/mailer/core/src/__tests__/utils.test.ts
  packages/record/package.json
  packages/record/src/redwoodrecord/__tests__/Core.test.js
  packages/record/src/redwoodrecord/__tests__/RedwoodRecord.test.js
  packages/record/src/redwoodrecord/__tests__/Reflection.test.js
  packages/record/src/redwoodrecord/__tests__/RelationProxy.test.js
  packages/record/src/redwoodrecord/__tests__/Validation.test.js
  packages/telemetry/package.json
  packages/telemetry/src/__tests__/sendTelemetry.test.js
  packages/tui/package.json
  packages/tui/src/__tests__/index.test.js
  yarn.lock
Labels: release:chore

#9868 chore(vite): switch to vitest
  packages/vite/package.json
  packages/vite/src/__tests__/viteNestedPages.test.mts
  packages/vite/src/plugins/__tests__/remove-from-bundle.test.mts
  packages/vite/src/plugins/__tests__/swap-apollo-provider.test.mts
  packages/vite/vitest.config.mts
  yarn.lock
Labels: release:chore

#9866 feat(testing): Add `describeScenario` utility to group scenario tests
  __fixtures__/test-project/api/src/services/contacts/describeContacts.scenarios.ts
  __fixtures__/test-project/api/src/services/contacts/describeContacts.test.ts
  docs/docs/testing.md
  packages/internal/src/generate/templates/api-scenarios.d.ts.template
  packages/testing/config/jest/api/jest.setup.js
  packages/testing/src/api/scenario.ts
  tasks/test-project/tasks.js
  tasks/test-project/templates/api/contacts.describeScenario.test.ts.template
  tasks/test-project/tui-tasks.js
Labels: release:feature

#9871 fix(createServer): use addHook instead of ready
  packages/api-server/src/plugins/graphql.ts
Labels: release:fix

#9870 chore(esm): convert `@redwoodjs/project-config` to ESM
  packages/project-config/build.js
  packages/project-config/build.mjs
  packages/project-config/package.json
  packages/project-config/src/config.ts
  packages/project-config/src/configPath.ts
  packages/project-config/src/index.ts
  packages/project-config/src/paths.ts
  packages/project-config/tsconfig.json
  packages/vite/bins/rw-vite-dev.mjs
  packages/vite/src/__tests__/viteNestedPages.test.mts
Labels: release:breaking

#9876 fix(studio): Add version checks when first running Studio
  packages/cli/src/commands/__tests__/studioHandler.test.js
  packages/cli/src/commands/studioHandler.js
  packages/cli/src/lib/packages.js
Labels: release:fix

#9872 chore(esm): convert `@redwoodjs/cli-helpers` to ESM
  packages/cli-helpers/.babelrc.js
  packages/cli-helpers/__mocks__/fs.js
  packages/cli-helpers/build.js
  packages/cli-helpers/jest.config.js
  packages/cli-helpers/package.json
  packages/cli-helpers/src/auth/__tests__/__snapshots__/authTasks.test.ts.snap
  packages/cli-helpers/src/auth/__tests__/authFiles.test.ts
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/__tests__/setupHelpers.test.ts
  packages/cli-helpers/src/auth/authFiles.ts
  packages/cli-helpers/src/auth/authTasks.ts
  packages/cli-helpers/src/auth/setupHelpers.ts
  packages/cli-helpers/src/index.ts
  packages/cli-helpers/src/lib/__tests__/__snapshots__/index.test.ts.snap
  packages/cli-helpers/src/lib/__tests__/__snapshots__/project.test.ts.snap
  packages/cli-helpers/src/lib/__tests__/index.test.ts
  packages/cli-helpers/src/lib/__tests__/project.addTomlSetting.test.ts
  packages/cli-helpers/src/lib/__tests__/project.test.ts
  packages/cli-helpers/src/lib/__tests__/version.test.ts
  packages/cli-helpers/src/lib/index.ts
  packages/cli-helpers/src/lib/installHelpers.ts
  packages/cli-helpers/src/lib/paths.ts
  packages/cli-helpers/src/lib/project.ts
  packages/cli-helpers/tsconfig.json
  packages/cli-helpers/vitest.config.mts
  packages/project-config/tsconfig.json
  yarn.lock
Labels: release:breaking

#9880 Updates OAuth how-to to use new cookie encryption function, use user service for creation
  docs/docs/how-to/oauth.md
  docs/versioned_docs/version-6.3/how-to/oauth.md
  docs/versioned_docs/version-6.4/how-to/oauth.md
  docs/versioned_docs/version-6.5/how-to/oauth.md
  docs/versioned_docs/version-6.6/how-to/oauth.md
Labels: topic/docs, release:docs

#9881 fix(crwa): remove yarn-install option for yarn 1
  packages/create-redwood-app/src/create-redwood-app.js
  packages/create-redwood-app/tests/e2e.test.ts
Labels: release:fix

#9878 chore(structure): switch to vitest
  packages/structure/package.json
  packages/structure/src/model/__tests__/model.test.ts
  packages/structure/src/model/util/__tests__/advanced_path_parser.test.ts
  packages/structure/src/model/util/__tests__/process_env_diagnostics.test.ts
  packages/structure/src/outline/__tests__/outline.test.ts
  packages/structure/src/x/__tests__/URL.test.ts
  packages/structure/src/x/__tests__/prisma.test.ts
  packages/structure/src/x/__tests__/vscode-languageserver-types-x.test.ts
  yarn.lock
Labels: release:chore

#9882 chore(tests): Fix some TS errors
  packages/auth-providers/netlify/api/src/__tests__/netlify.test.ts
  packages/cli-helpers/src/auth/__tests__/authFiles.test.ts
  packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
  packages/cli-helpers/src/auth/__tests__/setupHelpers.test.ts
  packages/cli-helpers/src/lib/__tests__/index.test.ts
  packages/cli-helpers/src/lib/__tests__/project.addTomlSetting.test.ts
  packages/cli-helpers/src/lib/__tests__/project.test.ts
  packages/cli-helpers/src/lib/__tests__/version.test.ts
  packages/cli-helpers/tsconfig.json
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/trustedDocuments.test.ts
  packages/cli/src/commands/setup/graphql/features/trustedDocuments/trustedDocumentsHandler.ts
Labels: release:chore

#9885 chore(cli tests): jest -> vitest
  packages/cli/testUtils.d.ts
Labels: release:chore

#9887 Update installation.md
  docs/docs/tutorial/chapter1/installation.md
Labels: release:docs

#9888 fix(gql): Add back gql global type
  packages/internal/src/generate/trustedDocuments.ts
  packages/web/src/global.web-auto-imports.ts
Labels: release:fix

#9889 chore(fixtures): Update gql file content as a result of trusted documents fix
  __fixtures__/example-todo-main/web/src/graphql/gql.ts
Labels: release:chore

#9890 chore(tests): api-server: Suppress logs
  packages/api-server/src/__tests__/createServer.test.ts
Labels: release:chore, fixture-ok

#9891 chore(cli): Move coerceRootPath()
  packages/adapters/fastify/web/build.mjs
  packages/adapters/fastify/web/package.json
  packages/adapters/fastify/web/src/helpers.ts
  packages/adapters/fastify/web/src/web.ts
  packages/api-server/src/cliHandlers.ts
  packages/cli/package.json
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveBothHandler.js
  packages/fastify/src/index.ts
  yarn.lock
Labels: release:breaking

#9895 fix(studio): Bump minimum RW canary version
  packages/cli/src/commands/studioHandler.js
Labels: release:chore

#9894 fix(serve): fix server listening logs
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/cliHandlers.ts
  packages/api-server/src/createServer.ts
  packages/api-server/src/fastify.ts
  packages/api-server/src/plugins/lambdaLoader.ts
  packages/api-server/src/server.ts
  packages/api-server/src/watch.ts
  packages/cli/src/commands/serveApiHandler.js
  packages/cli/src/commands/serveBothHandler.js
  packages/fastify/src/config.ts
  packages/web-server/src/webServer.ts
Labels: release:fix

#9900 cli-helpers: Don't emit tests to dist/
  packages/cli-helpers/package.json
  packages/cli-helpers/tsconfig.build.json
Labels: release:fix

#9927 fix(web): import helmet from node_modules
  packages/web/src/components/Metadata.tsx
Labels: release:fix

#9928 chore(forms): switch tests to vitest
  packages/forms/jest.config.js
  packages/forms/jest.setup.ts
  packages/forms/package.json
  packages/forms/src/__tests__/form.test.tsx
  packages/forms/vitest.config.mts
  packages/forms/vitest.setup.mts
  yarn.lock
Labels: release:chore

#9931 fix(server): don't mix async and callback styles
  packages/adapters/fastify/web/src/web.ts
  packages/api-server/src/createServer.ts
  packages/api-server/src/plugins/graphql.ts
  packages/fastify/src/api.ts
Labels: release:fix

#9933 fix(docusaurus): Make {jsx,tsx} file extensions switch properly
  docs/docusaurus.config.ts
  docs/src/components/FileExtSwitcher.tsx
  docs/src/remark/file-ext-switcher.mjs
Labels: release:fix

#9937 feat(crwa): Make the seed template idempotent
  __fixtures__/test-project/scripts/seed.ts
  packages/create-redwood-app/templates/js/scripts/seed.js
  packages/create-redwood-app/templates/ts/scripts/seed.ts
Labels: release:feature

#9883 feat(middleware): Add support for Middleware to SSR-Streaming server
  packages/api/package.json
  packages/auth/ambient.d.ts
  packages/auth/src/AuthProvider/AuthProvider.tsx
  packages/auth/src/AuthProvider/ServerAuthProvider.tsx
  packages/auth/src/index.ts
  packages/codemods/package.json
  packages/graphql-server/package.json
  packages/prerender/package.json
  packages/telemetry/package.json
  packages/vite/package.json
  packages/vite/src/devFeServer.ts
  packages/vite/src/middleware/CookieJar.test.ts
  packages/vite/src/middleware/CookieJar.ts
  packages/vite/src/middleware/MiddlewareRequest.test.ts
  packages/vite/src/middleware/MiddlewareRequest.ts
  packages/vite/src/middleware/MiddlewareResponse.test.ts
  packages/vite/src/middleware/MiddlewareResponse.ts
  packages/vite/src/middleware/index.ts
  packages/vite/src/middleware/invokeMiddleware.test.ts
  packages/vite/src/middleware/invokeMiddleware.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/web/src/apollo/links.tsx
  packages/web/src/apollo/suspense.tsx
  yarn.lock
Labels: release:feature

#9943 chore(apollo): Introduce TS type helper to reduce repetition
  packages/web/src/apollo/links.tsx
Labels: release:chore

#9942 fix(cli): Prevent caching blank information about plugins
  packages/cli/src/__tests__/plugin.test.js
  packages/cli/src/lib/plugin.js
  packages/cli/src/plugin.js
Labels: release:fix

#9945 fix(crwa): Use actual filename in seed file template
  __fixtures__/fragment-test-project/scripts/seed.ts
  __fixtures__/test-project/scripts/seed.ts
  packages/create-redwood-app/scripts/tsToJS.js
  packages/create-redwood-app/templates/js/scripts/seed.js
  packages/create-redwood-app/templates/ts/scripts/seed.ts
Labels: release:fix

#9946 fix(internal): Remove unused import
  packages/internal/src/__tests__/__snapshots__/typeDefinitions.test.ts.snap
  packages/internal/src/__tests__/typeDefinitions.test.ts
  packages/internal/src/generate/templates/web-routerRoutes.d.ts.template
  packages/internal/src/generate/typeDefinitions.ts
Labels: release:fix

#9947 @redwoodjs/framework-tools for buildDefaults
  nx.json
  packages/adapters/fastify/web/build.mjs
  packages/adapters/fastify/web/package.json
  packages/babel-config/build.mjs
  packages/babel-config/package.json
  packages/cli-packages/dataMigrate/build.mjs
  packages/cli-packages/dataMigrate/package.json
  packages/cli-packages/storybook/build.mjs
  packages/cli-packages/storybook/package.json
  packages/context/build.mjs
  packages/context/package.json
  packages/create-redwood-app/package.json
  packages/create-redwood-app/scripts/build.js
  packages/eslint-plugin/build.mjs
  packages/eslint-plugin/package.json
  packages/fastify/build.mjs
  packages/fastify/package.json
  packages/framework-tools/README.md
  packages/framework-tools/build.ts
  packages/framework-tools/package.json
  packages/framework-tools/src/buildDefaults.ts
  packages/framework-tools/tsconfig.json
  packages/mailer/core/build.mjs
  packages/mailer/core/package.json
  packages/mailer/handlers/in-memory/build.mjs
  packages/mailer/handlers/in-memory/package.json
  packages/mailer/handlers/nodemailer/build.mjs
  packages/mailer/handlers/nodemailer/package.json
  packages/mailer/handlers/resend/build.mjs
  packages/mailer/handlers/resend/package.json
  packages/mailer/handlers/studio/build.mjs
  packages/mailer/handlers/studio/package.json
  packages/mailer/renderers/mjml-react/build.mjs
  packages/mailer/renderers/mjml-react/package.json
  packages/mailer/renderers/react-email/build.mjs
  packages/mailer/renderers/react-email/package.json
  packages/project-config/build.js
  packages/project-config/package.json
  packages/realtime/build.mjs
  packages/realtime/package.json
  packages/tui/build.mjs
  packages/tui/package.json
  packages/web-server/build.mjs
  packages/web-server/package.json
  yarn.lock
Labels: release:chore
