Repository redwoodjs/graphql, pull requests merged in 2024-07, with the labels that each got.

#10895 Docs: Update Storybook docs to differentiate between the Webpack and Vite versions
  docs/docs/storybook/about.md
  docs/docs/storybook/vite.md
  docs/docs/storybook/webpack.md
  docs/sidebars.js
Labels: release:docs

#10898 chore(readme): Update contributors section: Dom to Alumni
  README.md
Labels: release:chore, changesets-ok

#10896 chore(esm): Update storybook build and package.json to build dual package
  packages/storybook/build.ts
  packages/storybook/package.json
Labels: release:chore

#10902 Updates document template to use exports field for htmlTags
  __fixtures__/test-project-rsa/web/src/Document.tsx
  __fixtures__/test-project-rsa/web/src/entry.server.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/Document.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/entry.server.tsx
  packages/cli/src/commands/experimental/templates/rsc/Document.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/entry.server.tsx.template
  packages/cli/src/commands/experimental/templates/streamingSsr/Document.tsx.template
  packages/web/package.json
Labels: release:chore

#10903 RSC: Make `rw g page` work for RSC projects
  packages/cli/src/commands/destroy/page/__tests__/page.test.js
  packages/cli/src/commands/generate/__tests__/helpers.test.js
  packages/cli/src/commands/generate/helpers.js
  packages/cli/src/commands/generate/page/__tests__/page.test.js
  packages/cli/src/commands/generate/page/page.js
  packages/cli/src/commands/generate/page/templates/page.tsx.template
  packages/cli/src/lib/test.js
Labels: release:feature

#10905 RSC: No need to pass location to Router anymore
  __fixtures__/test-project-rsa/web/src/Routes.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/Routes.tsx
  packages/cli/src/commands/experimental/templates/rsc/Routes.tsx.template
Labels: release:chore

#10901 chore(esm): Fix project-config dual packaging
  packages/project-config/build.ts
  packages/project-config/package.json
  packages/project-config/tsconfig.types-cjs.json
Labels: release:chore

#10912 chore(comment): Remove comment that's wrong
  packages/router/src/AuthenticatedRoute.tsx
Labels: release:chore

#10914 chore(ci): Exit canary publishing if version cannot be determined
  .github/scripts/publish_canary.sh
Labels: release:chore

#10915 chore(ci): Use more supported syntax in publish_canary script
  .github/scripts/publish_canary.sh
Labels: release:chore

#10916 debug(ci): Print publishing command output
  .github/scripts/publish_canary.sh
Labels: release:chore

#10918 fix(internal gql): Update types in test fixture
  __fixtures__/example-todo-main/web/src/graphql/fragment-masking.ts
Labels: release:chore

#10920 chore(tests): Fix failing kitchen-sink tests by logging in
  tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
Labels: release:chore

#10919 chore(ci): Cleaner log when publishing, unless failure
  .github/scripts/publish_canary.sh
Labels: release:chore

#10904 chore(server-store): Alias imports for getting request details to `@redwoodjs/web/request`
  packages/web/package.json
  packages/web/src/server/request.ts
  yarn.lock
Labels: release:chore

#10908 RSC: Add auth support to ClientRouter
  packages/vite/src/ClientRouter.tsx
  tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
Labels: release:feature

#10921 RSC: Test logging out
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/LoginPage/LoginForm.tsx
  tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
  tasks/smoke-tests/shared/common.ts
Labels: release:chore

#10922 feat(baremetal): Check for setup before running deploy
  .changesets/10922.md
  packages/cli/src/commands/deploy/baremetal.js
Labels: release:feature

#10910 feat(eslint-plugin): support flat config
  .changesets/10910.md
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/index.ts
Labels: release:feature

#10923 chore(structure): Remove obsolete placeholder implementation
  packages/structure/src/model/RWRoute.ts
Labels: release:chore

#10924 chore: apply code cleanups from typescript-eslint@v8's stylistic preset
  packages/adapters/fastify/web/src/resolveOptions.ts
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/shared.ts
  packages/auth-providers/dbAuth/middleware/src/defaultGetRoles.ts
  packages/auth-providers/dbAuth/setup/src/__tests__/setup.test.ts
  packages/auth-providers/dbAuth/setup/src/__tests__/setupDataMockDMMF.test.ts
  packages/auth-providers/netlify/web/src/netlify.ts
  packages/auth-providers/supabase/middleware/src/defaultGetRoles.ts
  packages/auth/src/__tests__/AuthProvider.test.tsx
  packages/babel-config/src/plugins/babel-plugin-redwood-directory-named-import.ts
  packages/cli-helpers/src/auth/setupHelpers.ts
  packages/cli-helpers/src/lib/index.ts
  packages/cli-helpers/src/lib/project.ts
  packages/cli-packages/dataMigrate/src/commands/upHandler.ts
  packages/cli/src/commands/setup/middleware/ogImage/ogImageHandler.ts
  packages/cli/src/commands/testHandler.js
  packages/cli/src/testLib/getFilesWithPattern.ts
  packages/cli/src/testUtils/matchTransformSnapshot.ts
  packages/codemods/src/codemods/v5.x.x/detectEmptyCells/detectEmptyCells.ts
  packages/codemods/src/lib/getFilesWithPattern.ts
  packages/codemods/src/lib/prettify.ts
  packages/codemods/src/testUtils/matchTransformSnapshot.ts
  packages/forms/src/coercion.ts
  packages/graphql-server/src/createGraphQLYoga.ts
  packages/graphql-server/src/functions/graphql.ts
  packages/graphql-server/src/plugins/useRedwoodLogger.ts
  packages/internal/src/ts2js.ts
  packages/mailer/core/src/mailer.ts
  packages/prerender/src/babelPlugins/utils.ts
  packages/prerender/src/graphql/graphql.ts
  packages/project-config/src/paths.ts
  packages/router/src/util.ts
  packages/storybook/src/mocks/MockProviders.tsx
  packages/structure/src/model/RWProject.ts
  packages/structure/src/model/RWRoute.ts
  packages/structure/src/model/RWTOML.ts
  packages/structure/src/model/__tests__/model.test.ts
  packages/structure/src/model/util/__tests__/process_env_diagnostics.test.ts
  packages/structure/src/model/util/process_env.ts
  packages/structure/src/outline/__tests__/outline.test.ts
  packages/structure/src/x/__tests__/vscode-languageserver-types-x.test.ts
  packages/structure/src/x/child_process.ts
  packages/structure/src/x/prisma.ts
  packages/structure/src/x/vscode.ts
  packages/telemetry/src/sendTelemetry.ts
  packages/testing/src/web/MockProviders.tsx
  packages/web/src/__typetests__/cellProps.test.tsx
  packages/web/src/components/cell/createCell.tsx
Labels: release:chore

#10925 RSC: Add auth support to ServerRouter
  packages/router/src/server-router.tsx
Labels: release:feature

#10928 chore(dbAuth): Fix typo in comment, and refactor dbAuthSession
  packages/auth-providers/dbAuth/api/src/shared.ts
Labels: release:chore

#10927 fix(dbAuth): Don't throw errors under normal auth flow conditions
  packages/auth-providers/dbAuth/middleware/src/__tests__/initDbAuthMiddleware.test.ts
  packages/auth-providers/dbAuth/middleware/src/index.ts
Labels: release:fix

#10933 chore(cli-helpers): Fix dual package build. Align with new pattern
  packages/cli-helpers/build.ts
  packages/cli-helpers/package.json
  packages/cli-helpers/tsconfig.build.json
  packages/cli-helpers/tsconfig.json
  yarn.lock
Labels: release:chore

#10931 feat(cli-helpers): Add loadEnvFiles
  packages/api-server/tsconfig.json
  packages/cli-helpers/build.ts
  packages/cli-helpers/package.json
  packages/cli-helpers/src/lib/loadEnvFiles.ts
  packages/cli-helpers/tsconfig.build.json
  packages/cli-packages/dataMigrate/src/bin.ts
  packages/internal/src/routes.ts
  packages/structure/src/model/RWEnvHelper.ts
  packages/vite/src/runFeServer.ts
  yarn.lock
Labels: release:chore

#10935 chore(cli-helpers): loadEnvFiles cleanup
  packages/cli-helpers/package.json
  packages/cli-helpers/src/lib/loadEnvFiles.ts
Labels: release:chore

#10936 fix(cli-helpers): Fix CJS support
  packages/cli-helpers/build.ts
  packages/cli-helpers/package.json
Labels: release:chore

#10930 hotfix(js-setup): Await all transformTSToJS functions
  .github/actions/detect-changes/action.yml
  .github/actions/detect-changes/detectChanges.mjs
  .github/workflows/check-test-project-fixture.yml
  .github/workflows/ci.yml
  packages/cli/src/commands/experimental/setupOpentelemetryHandler.js
  packages/cli/src/commands/generate/realtime/realtimeHandler.js
  packages/cli/src/commands/setup/mailer/mailerHandler.js
  packages/cli/src/commands/setup/realtime/realtimeHandler.js
  packages/cli/src/commands/setup/server-file/serverFileHandler.js
  packages/cli/src/commands/setup/vite/viteHandler.js
  packages/cli/src/lib/configureStorybook.js
  packages/cli/src/lib/index.js
Labels: release:fix

#10938 fix(docs): Fix introduction link
  docs/docs/introduction.md
Labels: release:docs, changesets-ok

#10940 fix(g directive): Notes formatting
  packages/cli/src/commands/generate/directive/directive.js
Labels: release:fix, changesets-ok

#10939 feat(colors): Add more chalk colors. And prepare for chalk upgrade
  .changesets/10939.md
  packages/api-server/src/logFormatter/formatters.ts
  packages/cli-helpers/src/lib/colors.ts
  packages/cli-packages/dataMigrate/src/commands/upHandler.ts
  packages/cli-packages/dataMigrate/src/lib/colors.ts
  packages/cli/src/commands/deploy/helpers/helpers.js
  packages/cli/src/commands/generate/directive/directive.js
  packages/cli/src/commands/prismaHandler.js
  packages/cli/src/commands/setup/cache/cacheHandler.js
  packages/cli/src/commands/setup/custom-web-index/custom-web-index-handler.js
  packages/cli/src/commands/setup/i18n/i18nHandler.js
  packages/cli/src/commands/setup/monitoring/sentry/sentryHandler.ts
  packages/cli/src/commands/setup/tsconfig/tsconfigHandler.js
  packages/cli/src/commands/setup/webpack/webpackHandler.js
  packages/cli/src/commands/test.js
  packages/cli/src/lib/colors.js
  packages/cli/src/middleware/checkNodeVersion.js
Labels: release:breaking

#10917 chore(middleware): Move middleware out of rwjs/vite -> rwjs/web/middleware
  __fixtures__/test-project-rsc-kitchen-sink/web/src/middleware/self.mts
  packages/auth-providers/dbAuth/middleware/package.json
  packages/auth-providers/dbAuth/middleware/src/__tests__/initDbAuthMiddleware.test.ts
  packages/auth-providers/dbAuth/middleware/src/index.ts
  packages/auth-providers/supabase/middleware/package.json
  packages/auth-providers/supabase/middleware/src/__tests__/initSupabaseAuthMiddleware.test.ts
  packages/auth-providers/supabase/middleware/src/index.ts
  packages/auth-providers/supabase/middleware/src/util.ts
  packages/ogimage-gen/package.json
  packages/ogimage-gen/src/OgImageMiddleware.test.ts
  packages/ogimage-gen/src/OgImageMiddleware.ts
  packages/vite/package.json
  packages/vite/src/devFeServer.ts
  packages/vite/src/middleware/index.ts
  packages/vite/src/middleware/invokeMiddleware.test.ts
  packages/vite/src/middleware/invokeMiddleware.ts
  packages/vite/src/middleware/register.test.ts
  packages/vite/src/middleware/register.ts
  packages/vite/src/middleware/types.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/web/package.json
  packages/web/src/server/MiddlewareRequest.test.ts
  packages/web/src/server/MiddlewareRequest.ts
  packages/web/src/server/MiddlewareResponse.test.ts
  packages/web/src/server/MiddlewareResponse.ts
  packages/web/src/server/middleware.ts
  packages/web/tsconfig.json
  yarn.lock
Labels: release:chore

#10942 chore(auth): Fix esm cjs exports and add tooling to verify correctness
  packages/auth/attw.ts
  packages/auth/build.ts
  packages/auth/package.json
  packages/auth/tsconfig.json
  packages/router/src/router-context.tsx
  yarn.lock
Labels: release:chore

#10943 chore(web): publint and attw
  packages/auth/build.ts
  packages/web/attw.ts
  packages/web/build.ts
  packages/web/package.json
  packages/web/tsconfig.json
  yarn.lock
Labels: release:chore

#10944 chore(web): Use attw args instead of custom output parsing
  packages/web/attw.ts
Labels: release:chore

#10947 chore(auth): build tweaks and add missing devdep
  packages/auth/build.ts
  packages/auth/package.json
  packages/auth/tsconfig.types-cjs.json
  yarn.lock
Labels: release:chore

#10949 chore(apollo client): Add types for cjs imports
  packages/web/modules.d.ts
  packages/web/src/apollo/fragmentRegistry.ts
  packages/web/src/apollo/index.tsx
  packages/web/src/apollo/sseLink.ts
  packages/web/src/apollo/useCache.ts
  packages/web/src/components/cell/createSuspendingCell.tsx
  packages/web/tsconfig.build.json
Labels: release:chore

#10951 chore(project-config): Verify package.json with publint and attw
  packages/project-config/package.json
  yarn.lock
Labels: release:chore

#10952 fix(web): Re-add generating ESM types
  packages/web/package.json
Labels: release:fix

#10953 chore(auth): More gracefully handle build failures
  packages/auth/build.ts
Labels: release:chore

#10934 chore(esm/cjs): Make the rwjs/vite package dual
  .vscode/settings.json
  packages/auth-providers/dbAuth/middleware/src/index.ts
  packages/auth-providers/dbAuth/middleware/tsconfig.types-cjs.json
  packages/auth-providers/supabase/middleware/src/index.ts
  packages/auth-providers/supabase/middleware/src/util.ts
  packages/project-config/src/paths.ts
  packages/vite/attw.ts
  packages/vite/build.mts
  packages/vite/cjsWrapper.js
  packages/vite/modules.d.ts
  packages/vite/package.json
  packages/vite/src/ClientRouter.tsx
  packages/vite/src/ServerRouter.ts
  packages/vite/src/SsrRouter.tsx
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRouteHooks.ts
  packages/vite/src/buildRouteManifest.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/index.ts
  packages/vite/src/lib/entries.ts
  packages/vite/src/middleware/invokeMiddleware.ts
  packages/vite/src/middleware/register.ts
  packages/vite/src/plugins/__tests__/swap-apollo-provider.test.mts
  packages/vite/src/plugins/vite-plugin-jsx-loader.ts
  packages/vite/src/plugins/vite-plugin-remove-from-bundle.ts
  packages/vite/src/plugins/vite-plugin-rsc-routes-auto-loader.ts
  packages/vite/src/plugins/vite-plugin-rsc-routes-imports.ts
  packages/vite/src/plugins/vite-plugin-rsc-ssr-router-import.ts
  packages/vite/src/plugins/vite-plugin-swap-apollo-provider.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/rsc/rscWorkerCommunication.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/ssrModuleMap.ts
  packages/vite/src/streaming/streamHelpers.ts
  packages/vite/src/types.ts
  packages/vite/src/utils.ts
  packages/vite/tsconfig.json
  packages/vite/vitest.config.mts
  yarn.lock
Labels: release:chore

#10954 chore(supabase-mw): Convert supabase-mw to dual package
  packages/auth-providers/supabase/middleware/build.mts
  packages/auth-providers/supabase/middleware/cjsWrappers/plugin.js
  packages/auth-providers/supabase/middleware/package.json
  packages/auth-providers/supabase/middleware/tsconfig.types-cjs.json
  packages/framework-tools/package.json
  packages/framework-tools/src/cjsTypes.ts
  yarn.lock
Labels: release:chore

#10955 RSC: Fix red squiggles in default template
  packages/cli/src/commands/experimental/templates/rsc/Counter.tsx.template
  packages/cli/src/commands/experimental/templates/rsc/HomePage.tsx.template
Labels: release:fix

#10948 chore(esm/cjs): Make dbauth middleware a dual package
  packages/auth-providers/dbAuth/middleware/build.mts
  packages/auth-providers/dbAuth/middleware/cjsWrappers/plugin.js
  packages/auth-providers/dbAuth/middleware/package.json
  packages/auth-providers/dbAuth/middleware/src/__tests__/initDbAuthMiddleware.test.ts
  packages/auth-providers/dbAuth/middleware/src/index.ts
  packages/auth-providers/dbAuth/middleware/tsconfig.types-cjs.json
  packages/framework-tools/src/cjsTypes.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/rsc/rscBuildForSsr.ts
  packages/vite/src/streaming/buildForStreamingServer.ts
  yarn.lock
Labels: release:chore

#10956 chore(check:pkg): Make all ESM packages have check:package script
  .github/workflows/ci.yml
  package.json
  packages/auth-providers/dbAuth/middleware/package.json
  packages/auth-providers/supabase/middleware/package.json
  packages/auth/package.json
  packages/project-config/package.json
  packages/vite/package.json
  packages/web/package.json
Labels: release:chore

#10959 chore: remove MailChimp Tutorial all versions
  docs/docs/tutorial/foreword.md
  docs/versioned_docs/version-1.x/tutorial/foreword.md
  docs/versioned_docs/version-2.x/tutorial/foreword.md
  docs/versioned_docs/version-3.x/tutorial/foreword.md
  docs/versioned_docs/version-4.x/tutorial/foreword.md
  docs/versioned_docs/version-5.x/tutorial/foreword.md
  docs/versioned_docs/version-6.x/tutorial/foreword.md
  docs/versioned_docs/version-7.0/tutorial/foreword.md
Labels: release:docs, changesets-ok

#10960 chore(docs): remove MailChimp from minor versions
  docs/versioned_docs/version-7.1/tutorial/foreword.md
  docs/versioned_docs/version-7.3/tutorial/foreword.md
  docs/versioned_docs/version-7.4/tutorial/foreword.md
  docs/versioned_docs/version-7.5/tutorial/foreword.md
  docs/versioned_docs/version-7.6/tutorial/foreword.md
  docs/versioned_docs/version-7.7/tutorial/foreword.md
Labels: release:chore, changesets-ok

#10961 fix(storybook): Fix import issues with storybook vite
  .changesets/10961.md
  packages/storybook/build.ts
  packages/storybook/package.json
  packages/storybook/preset.js
  packages/storybook/src/preset.ts
Labels: release:fix

#10900 feat(Storybook Vite): Add JS project support
  .changesets/10900.md
  packages/cli-packages/storybook-vite/src/commands/storybookHandler.ts
  packages/storybook/src/plugins/auto-imports.ts
Labels: release:feature

#10969 chore(publint): fix concurrently usage
  packages/auth-providers/dbAuth/middleware/package.json
  packages/auth-providers/supabase/middleware/package.json
  packages/auth/package.json
  packages/project-config/package.json
  packages/vite/package.json
  packages/web/package.json
Labels: release:chore, changesets-ok

#10891 docs: Updates vercel config for functions
  docs/docs/deploy/vercel.md
Labels: topic/docs, topic/deployment, release:docs, changesets-ok

#10869 feat(prisma): Support multi file Prisma schemas
  .changesets/10869.md
  docs/docs/app-configuration-redwood-toml.md
  packages/auth-providers/dbAuth/setup/src/__tests__/setupDataMockDMMF.test.ts
  packages/auth-providers/dbAuth/setup/src/shared.ts
  packages/cli/src/commands/prismaHandler.js
  packages/cli/src/commands/setup/deploy/providers/render.js
  packages/cli/src/lib/schemaHelpers.js
  packages/internal/src/generate/graphqlSchema.ts
  packages/record/src/tasks/parse.js
  packages/structure/src/model/RWProject.ts
  packages/testing/config/jest/api/globalSetup.js
  packages/testing/config/jest/api/jest.setup.js
Labels: release:feature

#10894 feat(trusted-docs): Allows useRedwoodTrustedDocuments to set more custom UsePersistedOperationsOptions
  .changesets/10894.md
  docs/docs/graphql/trusted-documents.md
  packages/graphql-server/src/plugins/useRedwoodTrustedDocuments.ts
Labels: release:feature

#10893 fix(realtime/trusted-docs): Supports GraphQL subscriptions and trusted documents
  .changesets/10893.md
  packages/api/src/validations/validations.ts
  packages/graphql-server/package.json
  packages/vite/src/buildRouteManifest.ts
  packages/web/src/apollo/sseLink.ts
  yarn.lock
Labels: topic/graphql, release:fix

#10987 chore(docs): Update Storybook Vite docs to reflect recent change
  docs/docs/storybook/vite.md
Labels: release:docs, changesets-ok

#9366 📝 Added page for using GitPod to the documentation
  .changesets/9366.md
  docs/docs/how-to/using-gitpod.md
  docs/docs/quick-start.md
Labels: release:docs

#11011 chore(storybook): Pin versions and update them
  packages/storybook/package.json
  packages/web/src/apollo/sseLink.ts
  yarn.lock
Labels: release:chore, changesets-ok

#11021 chore(deps): update dependency vitest to v2
  package.json
  packages/adapters/fastify/web/package.json
  packages/api-server/package.json
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/vitest.config.mts
  packages/api/package.json
  packages/auth-providers/auth0/api/package.json
  packages/auth-providers/auth0/setup/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/setup/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/custom/setup/package.json
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/middleware/package.json
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/setup/package.json
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/netlify/setup/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/middleware/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/api/package.json
  packages/auth-providers/supertokens/setup/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/babel-config/package.json
  packages/cli-helpers/package.json
  packages/cli-helpers/src/lib/__tests__/project.test.ts
  packages/cli-helpers/src/lib/__tests__/version.test.ts
  packages/cli/package.json
  packages/codemods/package.json
  packages/create-redwood-app/package.json
  packages/eslint-plugin/package.json
  packages/forms/package.json
  packages/internal/package.json
  packages/mailer/core/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/project-config/package.json
  packages/realtime/package.json
  packages/record/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/telemetry/package.json
  packages/testing/package.json
  packages/vite/package.json
  packages/vite/src/middleware/createMiddlewareRouter.test.ts
  packages/web/package.json
  tasks/server-tests/vitest.config.mts
  yarn.lock
Labels: release:chore, changesets-ok

#11028 chore(deps): Remove webpack related packages
  packages/core/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#11031 chore(vite): Don't exclude Router in attw check
  packages/vite/attw.ts
Labels: release:chore

#11032 chore(test): Document vitest issue in cli-helper test
  packages/cli-helpers/src/lib/__tests__/project.test.ts
Labels: release:chore

#11038 fix(deps): update dependency http-proxy-middleware to v3
  packages/vite/package.json
  packages/vite/src/runFeServer.ts
  yarn.lock
Labels: release:chore, changesets-ok

#11040 fix(deps): update dependency resend to v3
  packages/mailer/handlers/resend/package.json
  packages/mailer/handlers/resend/src/index.ts
  yarn.lock
Labels: release:chore, changesets-ok

#11041 fix(deps): update dependency ts-morph to v22
  packages/structure/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#11042 chore(deps): update chore
  .gitignore
  package.json
  tasks/test-project/rebuild-test-project-fixture.ts
  yarn.lock
Labels: release:chore, changesets-ok

#11043 Update saving-data.md
  docs/docs/tutorial/chapter3/saving-data.md
Labels: release:docs, changesets-ok

#11045 chore(router): attw: removed invalid copy/pasted comment
  packages/router/attw.ts
Labels: release:chore

#11046 chore(prerender types): Remove `any` type
  packages/prerender/src/runPrerender.tsx
Labels: release:chore

#11047 chore(vite): attw: Update outdated comment
  packages/vite/attw.ts
Labels: release:chore

#11048 RSC: Fix RscRouter import order
  __fixtures__/test-project-rsa/web/src/Routes.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/Routes.tsx
  packages/cli/src/commands/experimental/templates/rsc/Routes.tsx.template
Labels: release:chore

#11051 fix(deps): update dependency jscodeshift to v0.16.1
  package.json
  packages/cli/package.json
  packages/cli/src/testLib/runTransform.ts
  packages/codemods/package.json
  packages/codemods/src/lib/runTransform.ts
  yarn.lock
Labels: release:chore, changesets-ok

#10873 feat(router): add router useBlocker hook
  .changesets/10873.md
  __fixtures__/test-project/web/src/pages/ContactUsPage/ContactUsPage.tsx
  docs/docs/router.md
  packages/router/src/__tests__/history.test.tsx
  packages/router/src/__tests__/useBlocker.test.tsx
  packages/router/src/history.tsx
  packages/router/src/index.ts
  packages/router/src/useBlocker.ts
  tasks/smoke-tests/serve/tests/contactUs.spec.ts
Labels: release:feature

#11049 chore(rsc): Update page generate templates to use exports fields
  packages/cli/src/commands/generate/page/templates/page.tsx.template
  packages/web/package.json
Labels: release:chore

#11050 chore(RSC): Add smoke tests for retrieving headers and cookies in RSC
  __fixtures__/test-project-rsc-kitchen-sink/web/src/Routes.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/NavigationLayout/NavigationLayout.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/HomePage/HomePage.tsx
  __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/RequestPage/RequestPage.tsx
  tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
Labels: release:chore

#11058 feat(link): Pass options to navigate()
  .changesets/11058.md
  packages/router/src/__tests__/history.test.tsx
  packages/router/src/__tests__/links.test.tsx
  packages/router/src/link.tsx
Labels: release:feature

#11059 chore(router): Fix type errors in our routes tests
  packages/internal/tsconfig.json
  packages/ogimage-gen/tsconfig.json
  packages/prerender/tsconfig.json
  packages/router/build.ts
  packages/router/package.json
  packages/router/src/__tests__/analyzeRoutes.test.tsx
  packages/router/src/__tests__/history.test.tsx
  packages/router/src/__tests__/links.test.tsx
  packages/router/src/__tests__/location.test.tsx
  packages/router/src/__tests__/nestedSets.test.tsx
  packages/router/src/__tests__/pageLoadingContext.test.tsx
  packages/router/src/__tests__/redirect.test.tsx
  packages/router/src/__tests__/route-announcer.test.tsx
  packages/router/src/__tests__/route-focus.test.tsx
  packages/router/src/__tests__/route-validators.test.tsx
  packages/router/src/__tests__/routeScrollReset.test.tsx
  packages/router/src/__tests__/router.test.tsx
  packages/router/src/__tests__/set.test.tsx
  packages/router/src/__tests__/setContextReuse.test.tsx
  packages/router/src/__tests__/useBlocker.test.tsx
  packages/router/src/__tests__/useMatch.test.tsx
  packages/router/src/__tests__/useRoutePaths.test.tsx
  packages/router/src/__tests__/util.test.ts
  packages/router/tsconfig.build.json
  packages/router/tsconfig.json
  packages/router/tsconfig.types-cjs.json
  packages/testing/tsconfig.json
  packages/vite/tsconfig.json
  yarn.lock
Labels: release:chore

#11060 chore(deps): Add missing semver dep to cli-helpers
  packages/cli-helpers/package.json
  yarn.lock
Labels: release:chore

#11061 chore(deps): update dependency vitest to v2.0.4
  package.json
  packages/adapters/fastify/web/package.json
  packages/api-server/package.json
  packages/api/package.json
  packages/auth-providers/auth0/api/package.json
  packages/auth-providers/auth0/setup/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/setup/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/custom/setup/package.json
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/middleware/package.json
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/setup/package.json
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/netlify/setup/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/middleware/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/api/package.json
  packages/auth-providers/supertokens/setup/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/babel-config/package.json
  packages/cli-helpers/package.json
  packages/cli-helpers/src/lib/__tests__/project.test.ts
  packages/cli/package.json
  packages/codemods/package.json
  packages/create-redwood-app/package.json
  packages/eslint-plugin/package.json
  packages/forms/package.json
  packages/internal/package.json
  packages/mailer/core/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/project-config/package.json
  packages/realtime/package.json
  packages/record/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/telemetry/package.json
  packages/testing/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#11062 fix(router): Add check for excessively long path
  .changesets/11062.md
  packages/router/src/util.ts
Labels: release:fix

#11068 fix(cli): restore serverless deploy
  .changesets/11068.md
  packages/cli/src/commands/deploy/serverless.js
  packages/cli/src/commands/setup/deploy/providers/serverless.js
  packages/cli/src/commands/setup/deploy/templates/serverless/api.js
  packages/cli/src/commands/setup/deploy/templates/serverless/web.js
Labels: release:fix

#10768 Add Storybook Vite unit tests
  .changesets/10768.md
  packages/cli-packages/storybook-vite/package.json
  packages/cli-packages/storybook-vite/src/__tests__/storybook.test.ts
  packages/cli-packages/storybook-vite/src/__tests__/storybookConfigFixtures.test.ts
  packages/cli-packages/storybook-vite/src/__tests__/storybookHandler.test.ts
  yarn.lock
Labels: release:chore, changesets-ok

#11070 chore(types): Fix/improve types config for the router package
  packages/router/tsconfig.json
Labels: release:chore

#11071 fix(deps): update @apollo/client to v3.11.1
  packages/forms/src/FormError.tsx
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#11072 feat(cli): Move docker setup out of experimental
  .changesets/11072.md
  docs/docs/docker.md
  packages/cli/src/commands/experimental/setupDocker.js
  packages/cli/src/commands/setup/docker/__tests__/setupDocker.test.js
  packages/cli/src/commands/setup/docker/docker.js
  packages/cli/src/commands/setup/docker/dockerHandler.js
  packages/cli/src/commands/setup/docker/templates/Dockerfile
  packages/cli/src/commands/setup/docker/templates/docker-compose.dev.yml
  packages/cli/src/commands/setup/docker/templates/docker-compose.prod.yml
  packages/cli/src/commands/setup/docker/templates/dockerignore
Labels: release:feature

#11073 fix(deps): update dependency @escape.tech/graphql-armor to v2.4.0
  packages/graphql-server/package.json
  packages/graphql-server/src/plugins/useArmor.ts
  yarn.lock
Labels: release:chore, changesets-ok

#11085 chore(lint): tell eslint to ignore crwrsca
  package.json
Labels: release:chore

#10932 Introduce RSC "live reload."
  packages/vite/package.json
  packages/vite/src/devRscServer.ts
  packages/vite/src/runFeServer.ts
  packages/vite/src/streaming/streamHelpers.ts
  yarn.lock
Labels: release:feature

#11086 feat(storybook): Switch docs to be only about the new version
  docs/docs/introduction.md
  docs/docs/storybook.md
  docs/docs/storybook/about.md
  docs/docs/storybook/vite.md
  docs/docs/storybook/webpack.md
  docs/sidebars.js
Labels: release:docs, changesets-ok

#11069 feat(storybook): switch command for storybook vite
  .changesets/11069.md
  .github/workflows/ci.yml
  packages/cli-packages/storybook-vite/README.md
  packages/cli-packages/storybook-vite/src/__tests__/storybook.test.ts
  packages/cli-packages/storybook-vite/src/commands/storybook.ts
  packages/cli/src/lib/plugin.js
  packages/internal/src/generate/typeDefinitions.ts
  packages/web/src/bins/storybook-vite.ts
  packages/web/src/bins/storybook.ts
  tasks/smoke-tests/storybook/playwright.config.ts
Labels: release:feature

#11096 chore(clean): Don't clean inside nested node_modules
  tasks/clean.mjs
Labels: release:chore

#11095 chore(lint): Make `yarn lint` lint both the FW and CRWRSCA
  .github/actions/set-up-job/action.yml
  package.json
  yarn.lock
Labels: release:chore

#11104 chore(crwrsca): Remove tsup, use esbuild
  packages/create-redwood-rsc-app/build.ts
  packages/create-redwood-rsc-app/framework-tools.ts
  packages/create-redwood-rsc-app/knip.json
  packages/create-redwood-rsc-app/modules.d.ts
  packages/create-redwood-rsc-app/package.json
  packages/create-redwood-rsc-app/tsconfig.json
  packages/create-redwood-rsc-app/tsup.config.ts
  packages/create-redwood-rsc-app/yarn.lock
Labels: release:chore

#11105 chore(crwrsca): Fix TS issue in error.ts
  packages/create-redwood-rsc-app/src/error.ts
Labels: release:chore

#11107 fix(crwrsca): Fix yarn detection when running using tsx
  packages/create-redwood-rsc-app/src/prerequisites.ts
Labels: release:fix

#11106 chore(crwrsca): Get rid of vitest as we don't have any tests (for now)
  packages/create-redwood-rsc-app/eslint.config.js
  packages/create-redwood-rsc-app/package.json
  packages/create-redwood-rsc-app/src/greet.test.ts
  packages/create-redwood-rsc-app/src/greet.ts
  packages/create-redwood-rsc-app/src/types.ts
  packages/create-redwood-rsc-app/vitest.config.ts
  packages/create-redwood-rsc-app/yarn.lock
Labels: release:chore

#11103 chore(test-project): Fix rebuild-test-project-fixture script
  __fixtures__/test-project/package.json
  __fixtures__/test-project/web/package.json
  __fixtures__/test-project/web/src/pages/AboutPage/AboutPage.tsx
  __fixtures__/test-project/web/src/pages/BlogPostPage/BlogPostPage.tsx
  __fixtures__/test-project/web/src/pages/ContactUsPage/ContactUsPage.tsx
  __fixtures__/test-project/web/src/pages/HomePage/HomePage.tsx
  __fixtures__/test-project/web/src/pages/ProfilePage/ProfilePage.tsx
  tasks/test-project/codemods/aboutPage.js
  tasks/test-project/codemods/blogPostPage.js
  tasks/test-project/codemods/contactUsPage.js
  tasks/test-project/codemods/homePage.js
  tasks/test-project/codemods/profilePage.js
  tasks/test-project/codemods/updateAuthorCellMock.js
  tasks/test-project/codemods/updateBlogPostMocks.js
  tasks/test-project/codemods/updateWaterfallBlogPostMocks.js
  tasks/test-project/tui-tasks.js
Labels: release:chore, changesets-ok

#11111 chore(changelog): tweaks to existing entries
  .changesets/10266.md
  .changesets/10412.md
  .changesets/10464.md
  .changesets/10538.md
  .changesets/10677.md
  .changesets/10859.md
  .changesets/10867.md
  .changesets/10871.md
  .changesets/10873.md
  .changesets/10874.md
  .changesets/10910.md
  .changesets/10922.md
  .changesets/11068.md
Labels: release:chore, changesets-ok

#11109 fix: concurrent api builds
  .changesets/11109.md
  packages/api-server/src/watch.ts
Labels: release:fix

#11112 fix(crwrsca): Stop using parseArgs
  packages/create-redwood-rsc-app/src/config.ts
Labels: release:fix

#11113 chore(crwrsca): npm pkg fix
  packages/create-redwood-rsc-app/package.json
  packages/create-redwood-rsc-app/yarn.lock
Labels: release:chore

#11114 crwrsca: publish.ts script
  packages/create-redwood-rsc-app/README.md
  packages/create-redwood-rsc-app/package.json
  packages/create-redwood-rsc-app/publish.ts
  packages/create-redwood-rsc-app/yarn.lock
Labels: release:chore

#11117 fix(crwrsca): push to upstream in last step
  packages/create-redwood-rsc-app/publish.ts
Labels: release:fix

#11118 chore(kitchen-sink): Disable test and stories generation
  __fixtures__/test-project-rsc-kitchen-sink/redwood.toml
Labels: release:chore

#11119 Disable RSC live reload in production.
  packages/vite/src/streaming/streamHelpers.ts
Labels: release:fix

#11102 Update GraphQL docs for Docusaurus graphql documentation generator plugin
  docs/docs/graphql.md
Labels: release:docs, changesets-ok

#11120 RSC: Add rsc-caching project fixture
  __fixtures__/rsc-caching/.editorconfig
  __fixtures__/rsc-caching/.env.defaults
  __fixtures__/rsc-caching/.env.example
  __fixtures__/rsc-caching/.gitignore
  __fixtures__/rsc-caching/.gitpod.yml
  __fixtures__/rsc-caching/.redwood/README.md
  __fixtures__/rsc-caching/.vscode/extensions.json
  __fixtures__/rsc-caching/.vscode/launch.json
  __fixtures__/rsc-caching/.vscode/settings.json
  __fixtures__/rsc-caching/.vscode/tasks.json
  __fixtures__/rsc-caching/.yarnrc.yml
  __fixtures__/rsc-caching/README.md
  __fixtures__/rsc-caching/api/db/dev.db
  __fixtures__/rsc-caching/api/db/schema.prisma
  __fixtures__/rsc-caching/api/jest.config.js
  __fixtures__/rsc-caching/api/package.json
  __fixtures__/rsc-caching/api/src/directives/requireAuth/requireAuth.test.ts
  __fixtures__/rsc-caching/api/src/directives/requireAuth/requireAuth.ts
  __fixtures__/rsc-caching/api/src/directives/skipAuth/skipAuth.test.ts
  __fixtures__/rsc-caching/api/src/directives/skipAuth/skipAuth.ts
  __fixtures__/rsc-caching/api/src/functions/graphql.ts
  __fixtures__/rsc-caching/api/src/graphql/.keep
  __fixtures__/rsc-caching/api/src/lib/auth.ts
  __fixtures__/rsc-caching/api/src/lib/db.ts
  __fixtures__/rsc-caching/api/src/lib/logger.ts
  __fixtures__/rsc-caching/api/src/services/.keep
  __fixtures__/rsc-caching/api/tsconfig.json
  __fixtures__/rsc-caching/graphql.config.js
  __fixtures__/rsc-caching/jest.config.js
  __fixtures__/rsc-caching/package.json
  __fixtures__/rsc-caching/prettier.config.js
  __fixtures__/rsc-caching/redwood.toml
  __fixtures__/rsc-caching/scripts/.keep
  __fixtures__/rsc-caching/scripts/seed.ts
  __fixtures__/rsc-caching/scripts/tsconfig.json
  __fixtures__/rsc-caching/web/jest.config.js
  __fixtures__/rsc-caching/web/package.json
  __fixtures__/rsc-caching/web/public/README.md
  __fixtures__/rsc-caching/web/public/favicon.png
  __fixtures__/rsc-caching/web/public/robots.txt
  __fixtures__/rsc-caching/web/src/App.tsx
  __fixtures__/rsc-caching/web/src/Document.tsx
  __fixtures__/rsc-caching/web/src/Routes.tsx
  __fixtures__/rsc-caching/web/src/components/CachingBoxes/CachingBoxes.css
  __fixtures__/rsc-caching/web/src/components/CachingBoxes/CachingBoxes.tsx
  __fixtures__/rsc-caching/web/src/entry.client.tsx
  __fixtures__/rsc-caching/web/src/entry.server.tsx
  __fixtures__/rsc-caching/web/src/index.css
  __fixtures__/rsc-caching/web/src/layouts/.keep
  __fixtures__/rsc-caching/web/src/layouts/MainLayout/MainLayout.css
  __fixtures__/rsc-caching/web/src/layouts/MainLayout/MainLayout.tsx
  __fixtures__/rsc-caching/web/src/pages/CachingOnePage/CachingOnePage.tsx
  __fixtures__/rsc-caching/web/src/pages/CachingTwoPage/CachingTwoPage.tsx
  __fixtures__/rsc-caching/web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  __fixtures__/rsc-caching/web/src/pages/HomePage/HomePage.tsx
  __fixtures__/rsc-caching/web/src/pages/NotFoundPage/NotFoundPage.tsx
  __fixtures__/rsc-caching/web/tsconfig.json
  __fixtures__/rsc-caching/web/vite.config.ts
Labels: release:chore

#11108 feat(testing): Configure jest to ignore sidecar files in __tests__ folder
  .changesets/11108.md
  packages/testing/config/jest/api/jest-preset.js
  packages/testing/config/jest/web/jest-preset.js
Labels: release:fix

#11123 feat(crwrsca): Add support for --template
  packages/create-redwood-rsc-app/src/config.ts
  packages/create-redwood-rsc-app/src/index.ts
  packages/create-redwood-rsc-app/src/zip.ts
Labels: release:feature

#11124 fix(isCellEmpty): Fix doc comment
  packages/web/src/components/cell/isCellEmpty.ts
Labels: release:fix, changesets-ok

#11125 Disable unused imports/ vars/ params in TypeScript compiler, opt for ESLint instead
  .eslintrc.js
  package.json
  tsconfig.compilerOption.json
  yarn.lock
Labels: release:chore

#11126 RSC cache control
  packages/router/src/rsc/ClientRouter.tsx
  packages/router/src/rsc/RscCache.ts
  packages/router/src/rsc/rscFetchForClientRouter.tsx
  packages/vite/package.json
  packages/vite/src/runFeServer.ts
  yarn.lock
Labels: release:feature

#11127 feat(rsc): rsc-cache-read
  packages/router/src/rsc/RscCache.ts
Labels: release:feature

#11128 chore(rsc): Add ServerDelayForm to rsc-caching fixture
  __fixtures__/rsc-caching/web/src/components/CachingBoxes/CachingBoxes.tsx
  __fixtures__/rsc-caching/web/src/layouts/MainLayout/MainLayout.css
  __fixtures__/rsc-caching/web/src/layouts/MainLayout/MainLayout.tsx
Labels: release:chore

#11130 chore(rsc): Add ServerDelayForm to rsc-caching fixture (missing files)
  __fixtures__/rsc-caching/web/src/components/ServerDelayForm/ServerDelayForm.css
  __fixtures__/rsc-caching/web/src/components/ServerDelayForm/ServerDelayForm.tsx
  __fixtures__/rsc-caching/web/src/components/ServerDelayForm/actions.ts
Labels: release:chore

#11129 chore(ci): update release label list
  .github/workflows/require-release-label.yml
Labels: release:chore, changesets-ok

#11133 chore(crwrsca): Fix TS issues in index.ts
  packages/create-redwood-rsc-app/src/index.ts
Labels: release:chore, fixture-ok
