Repository redwoodjs/graphql, pull requests merged in 2024-02, with the labels that each got.

#9949 fix(server): spelling, fix deploy handler imports, dedupe server builder
  .vscode/settings.json
  packages/cli/src/commands/__tests__/serve.test.js
  packages/cli/src/commands/deploy/flightcontrol.js
  packages/cli/src/commands/deploy/render.js
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveBothHandler.js
Labels: release:fix

#9950 fix(api-server): Remove duplicate command alias
  packages/api-server/src/createServerHelpers.ts
Labels: release:fix

#9952 chore(test): Remove yarn.lock from some test fixtures
  __fixtures__/example-todo-main-with-errors/yarn.lock
  __fixtures__/example-todo-main/yarn.lock
Labels: release:chore

#9929 chore(api-server): switch to vitest
  packages/api-server/dist.test.ts
  packages/api-server/jest.config.js
  packages/api-server/package.json
  packages/api-server/src/__tests__/api.test.ts
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/__tests__/fastify.test.ts
  packages/api-server/src/__tests__/lambdaLoader.test.ts
  packages/api-server/src/__tests__/lambdaLoaderNumberFunctions.test.ts
  packages/api-server/src/__tests__/logFormatter.test.ts
  packages/api-server/src/__tests__/requestHandlers/awsLambdaFastify.test.ts
  packages/api-server/src/__tests__/requestHandlers/utils.test.ts
  packages/api-server/src/apiCLIConfigHandler.ts
  packages/api-server/src/bothCLIConfigHandler.ts
  packages/api-server/src/createServer.ts
  packages/api-server/src/fastify.ts
  packages/api-server/src/plugins/api.ts
  packages/api-server/src/plugins/graphql.ts
  packages/api-server/vitest.config.mts
  yarn.lock
Labels: release:chore

#9954 docs(typo): Removed `rw` from `yarn install` command
  packages/mailer/handlers/resend/README.md
Labels: topic/docs, release:docs

#9956 fix(studio): Remove unused setting inMemory
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/__tests__/fixtures/redwood.studio.dbauth.toml
  packages/project-config/src/__tests__/fixtures/redwood.studio.supabase.toml
  packages/project-config/src/__tests__/fixtures/redwood.studio.toml
  packages/project-config/src/config.ts
Labels: release:fix

#9957 fix(gql): Better graphql.config.js template
  __fixtures__/fragment-test-project/graphql.config.js
  __fixtures__/fragment-test-project/package.json
  __fixtures__/test-project/graphql.config.js
  __fixtures__/test-project/package.json
  packages/create-redwood-app/templates/js/graphql.config.js
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/graphql.config.js
  packages/create-redwood-app/templates/ts/package.json
Labels: release:fix

#9955 Update Studio docs
  .vscode/settings.json
  docs/docs/studio.md
Labels: release:docs

#9959 feat(gql): Codemod existing projects to get newest gql config
  packages/cli/src/testUtils/matchFolderTransform.ts
  packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/README.md
  packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/__testfixtures__/input/graphql.config.js
  packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/__testfixtures__/output/graphql.config.js
  packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/__tests__/updateGraphqlConfig.test.ts
  packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/updateGraphqlConfig.ts
  packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/updateGraphqlConfig.yargs.ts
  packages/codemods/src/testUtils/matchFolderTransform.ts
Labels: release:feature

#9958 chore(server): improve server tests
  .github/workflows/ci.yml
  tasks/server-tests/__snapshots__/bothServer.test.mts.snap
  tasks/server-tests/bothServer.test.mts
  tasks/server-tests/bothServerAPI.test.mts
  tasks/server-tests/bothServerWeb.test.mts
  tasks/server-tests/helpers.mts
  tasks/server-tests/vitest.config.mts
  tasks/server-tests/vitest.setup.mts
Labels: release:chore

#9960 Mention the you need corepack enabled to run this repo
  CONTRIBUTING.md
Labels: release:chore

#9965 fix(cell-suspense): pass through variables if passed to refetch
  packages/web/src/components/cell/cellTypes.ts
  packages/web/src/components/cell/createSuspendingCell.tsx
Labels: release:fix, fixture-ok

#9964 cli: Remove graphiql setup command
  __fixtures__/test-project/web/package.json
  docs/docs/cli-commands.md
  packages/cli/src/commands/destroy/graphiql/graphiql.js
  packages/cli/src/commands/setup/graphiql/__tests__/graphiqlHandler.test.js
  packages/cli/src/commands/setup/graphiql/graphiql.js
  packages/cli/src/commands/setup/graphiql/graphiqlHandler.js
  packages/cli/src/commands/setup/graphiql/graphiqlHelpers.js
  packages/cli/src/commands/setup/graphiql/supportedProviders.js
  packages/cli/src/commands/setup/graphiql/templates/graphiql-mock.ts.template
  packages/cli/src/commands/setup/graphiql/templates/graphiql-token.ts.template
Labels: release:breaking

#9966 fix(studio): Remove unused settings 'endpoint' and 'roles'
  packages/project-config/src/__tests__/config.test.ts
  packages/project-config/src/__tests__/fixtures/redwood.studio.dbauth.toml
  packages/project-config/src/__tests__/fixtures/redwood.studio.supabase.toml
  packages/project-config/src/config.ts
Labels: release:fix

#9967 chore(cleanup): Remove debug console.log call
  packages/internal/src/generate/generate.ts
Labels: release:chore

#9971 RSC: Make RWJS_ENV etc available on the server during runtime
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRscFeServer.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/lib/registerGlobals.ts
  packages/vite/src/rsc/rscWorker.ts
  packages/vite/src/runFeServer.ts
Labels: release:fix

#9972 RSC: Take full control over the env vars
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildServer.ts
Labels: release:fix

#9973 RSC: Enable babel plugins to get client Cell support
  packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildServer.ts
Labels: release:feature

#9941 chore(build): use `tsx` to run build scripts
  __fixtures__/test-project/web/package.json
  packages/adapters/fastify/web/build.mts
  packages/adapters/fastify/web/package.json
  packages/api-server/build.mts
  packages/api-server/package.json
  packages/babel-config/build.mts
  packages/babel-config/package.json
  packages/cli-helpers/build.js
  packages/cli-helpers/build.ts
  packages/cli-helpers/package.json
  packages/cli-packages/dataMigrate/build.mts
  packages/cli-packages/dataMigrate/package.json
  packages/cli-packages/storybook/build.mts
  packages/cli-packages/storybook/package.json
  packages/context/build.mts
  packages/context/package.json
  packages/create-redwood-app/package.json
  packages/create-redwood-app/scripts/build.ts
  packages/eslint-plugin/build.mts
  packages/eslint-plugin/package.json
  packages/mailer/core/build.mts
  packages/mailer/core/package.json
  packages/mailer/handlers/in-memory/build.mts
  packages/mailer/handlers/in-memory/package.json
  packages/mailer/handlers/nodemailer/build.mts
  packages/mailer/handlers/nodemailer/package.json
  packages/mailer/handlers/resend/build.mts
  packages/mailer/handlers/resend/package.json
  packages/mailer/handlers/studio/build.mts
  packages/mailer/handlers/studio/package.json
  packages/mailer/renderers/mjml-react/build.mts
  packages/mailer/renderers/mjml-react/package.json
  packages/mailer/renderers/react-email/build.mts
  packages/mailer/renderers/react-email/package.json
  packages/project-config/build.ts
  packages/project-config/package.json
  packages/realtime/build.mts
  packages/realtime/package.json
  packages/tui/build.mts
  packages/tui/package.json
  packages/web-server/build.mts
  packages/web-server/package.json
  yarn.lock
Labels: release:chore

#8874 fix(deps) resolve yarn warnings regarding unmet peer dependencies for Redwood projects
  docs/docs/a11y.md
  packages/cli/src/commands/generate/layout/__tests__/__snapshots__/layout.test.ts.snap
  packages/cli/src/commands/generate/layout/templates/layout.tsx.a11yTemplate
  packages/forms/package.json
  packages/router/package.json
  packages/router/skip-nav.css
  packages/router/src/index.ts
  packages/router/src/skipNav.tsx
  yarn.lock
Labels: release:breaking

#9976 fix(docker): corepack permissions fix and style updates
  docs/docs/docker.md
  packages/cli/src/commands/experimental/templates/docker/Dockerfile
  packages/cli/src/commands/experimental/templates/docker/docker-compose.prod.yml
Labels: release:fix

#9977 fix(test): Update createServer test to use a different port to normal
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/__tests__/fixtures/redwood-app/redwood.toml
Labels: release:chore

#9975 fix(cli): use fetch instead of `yarn npm info`
  packages/cli/src/commands/setup/auth/auth.js
  packages/cli/src/lib/packages.js
Labels: release:fix

#9982 fix(docker): compose dev and prod
  packages/cli/src/commands/experimental/templates/docker/docker-compose.dev.yml
  packages/web-server/package.json
  yarn.lock
Labels: release:fix

#9727 fix: unpin react types
  __fixtures__/test-project/web/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/create-redwood-app/templates/js/web/package.json
  packages/create-redwood-app/templates/ts/web/package.json
  packages/forms/package.json
  packages/router/package.json
  packages/testing/package.json
  packages/vite/package.json
  packages/web/package.json
  yarn.lock
Labels: release:fix

#9984 fix(server): use file extension in import, fix graphql route registering
  packages/api-server/src/createServer.ts
  packages/api-server/src/plugins/graphql.ts
Labels: release:fix

#9986 chore: update rsc fixture
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
Labels: release:chore

#9985 chore(project-config): make chore changes to trigger ci
  packages/project-config/README.md
  packages/project-config/dependencyGraph.dist.svg
  packages/project-config/dependencyGraph.src.svg
Labels: release:chore

#9988 chore(refactor): Router: Splitting things up into smaller files
  __fixtures__/test-project/web/src/layouts/BlogLayout/BlogLayout.tsx
  packages/router/src/ActivePageContext.tsx
  packages/router/src/AuthenticatedRoute.tsx
  packages/router/src/PageLoadingContext.tsx
  packages/router/src/__tests__/links.test.tsx
  packages/router/src/__tests__/useMatch.test.tsx
  packages/router/src/createNamedContext.ts
  packages/router/src/index.ts
  packages/router/src/link.tsx
  packages/router/src/links.tsx
  packages/router/src/location.tsx
  packages/router/src/navLink.tsx
  packages/router/src/params.tsx
  packages/router/src/redirect.ts
  packages/router/src/router.tsx
  packages/router/src/util.ts
  tasks/test-project/codemods/blogLayout.js
Labels: release:chore

#9987 RSC: createServerCell
  packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
  packages/router/src/rsc-link.tsx
  packages/web/src/components/cell/CellErrorBoundary.tsx
  packages/web/src/components/cell/createServerCell.tsx
  packages/web/src/components/cell/isCellEmpty.tsx
Labels: release:breaking

#9990 RSC: chore(test): Update RSC test fixture project
  __fixtures__/test-project-rsc-external-packages-and-cells/.vscode/settings.json
  __fixtures__/test-project-rsc-external-packages-and-cells/README.md
  __fixtures__/test-project-rsc-external-packages-and-cells/api/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/Routes.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/UserExample/NewUserExample/NewUserExample.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/UserExample/UserExamplesCell/UserExamplesCell.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/entries.ts
Labels: release:chore

#9992 fix(dependencies): Use RW-specific version of apollo ssr package
  packages/web/package.json
  yarn.lock
Labels: release:chore

#9994 RSC: Fix babel-plugin-redwood-cell to work wiht more than one cell
  packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
Labels: release:fix

#9993 RSC: Keep aligning test project with CRWA template
  __fixtures__/test-project-rsc-external-packages-and-cells/.redwood/README.md
  __fixtures__/test-project-rsc-external-packages-and-cells/.vscode/launch.json
  __fixtures__/test-project-rsc-external-packages-and-cells/.vscode/tasks.json
  __fixtures__/test-project-rsc-external-packages-and-cells/api/db/schema.prisma
  __fixtures__/test-project-rsc-external-packages-and-cells/api/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/api/src/lib/auth.ts
  __fixtures__/test-project-rsc-external-packages-and-cells/api/tsconfig.json
  __fixtures__/test-project-rsc-external-packages-and-cells/graphql.config.js
  __fixtures__/test-project-rsc-external-packages-and-cells/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/scripts/tsconfig.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/tsconfig.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/vite.config.ts
Labels: release:chore

#9997 bug: Update setupHandler.ts firebase version
  packages/auth-providers/firebase/setup/src/setupHandler.ts
Labels: release:fix

#9999 chore(jsdocs): Fix jsdoc formatting for hover help
  packages/cli/src/lib/index.js
Labels: release:chore

#10000 fix(telemetry): Fix 'destroy' spelling
  packages/cli/src/commands/destroy/helpers.js
  packages/cli/src/commands/destroy/page/page.js
  packages/cli/src/commands/destroy/sdl/sdl.js
Labels: release:chore

#9998 RSC: Insert 'use client' in scaffolded components
  packages/cli/src/commands/destroy/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/destroy/scaffold/__tests__/scaffoldNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
  packages/cli/src/commands/generate/scaffold/__tests__/editableColumns.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldCustomIdName.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPath.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMulti.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiword.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiwordNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathNoNest.test.js
  packages/cli/src/commands/generate/scaffold/__tests__/shouldUseEmptyAsUndefined.test.js
  packages/cli/src/commands/generate/scaffold/scaffold.js
  packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NameCell.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.tsx.template
  packages/cli/src/commands/generate/scaffold/templates/components/NewName.tsx.template
Labels: release:feature

#10003 fix(docs): Spelling of `data-migrate` command
  docs/docs/cli-commands.md
Labels: release:docs

#10002 chore(deps): Upgrade to yarn v4.1.0
  .github/actions/check_create_redwood_app/package.json
  .github/actions/check_create_redwood_app/yarn.lock
  .github/actions/detect-changes/package.json
  .github/actions/detect-changes/yarn.lock
  __fixtures__/test-project-rsc-external-packages-and-cells/package.json
  __fixtures__/test-project/package.json
  docs/package.json
  docs/yarn.lock
  package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
  tasks/check/package.json
  tasks/check/yarn.lock
  yarn.lock
Labels: release:chore

#10006 RSC: babel-plugin-redwood-cell remove redundant reset
  packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
Labels: release:chore

#10007 RSC: test-project EmptyUser 'use client' cell
  __fixtures__/test-project-rsc-external-packages-and-cells/api/db/dev.db
  __fixtures__/test-project-rsc-external-packages-and-cells/api/db/migrations/20240212134007_empty_user/migration.sql
  __fixtures__/test-project-rsc-external-packages-and-cells/api/db/schema.prisma
  __fixtures__/test-project-rsc-external-packages-and-cells/api/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/api/src/graphql/emptyUsers.sdl.ts
  __fixtures__/test-project-rsc-external-packages-and-cells/api/src/services/emptyUsers/emptyUsers.scenarios.ts
  __fixtures__/test-project-rsc-external-packages-and-cells/api/src/services/emptyUsers/emptyUsers.test.ts
  __fixtures__/test-project-rsc-external-packages-and-cells/api/src/services/emptyUsers/emptyUsers.ts
  __fixtures__/test-project-rsc-external-packages-and-cells/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/Routes.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/EmptyUser/EditEmptyUserCell/EditEmptyUserCell.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/EmptyUser/EmptyUser/EmptyUser.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/EmptyUser/EmptyUserCell/EmptyUserCell.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/EmptyUser/EmptyUserForm/EmptyUserForm.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/EmptyUser/EmptyUsers/EmptyUsers.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/EmptyUser/EmptyUsersCell/EmptyUsersCell.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/EmptyUser/NewEmptyUser/NewEmptyUser.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/entries.ts
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/EmptyUser/EditEmptyUserPage/EditEmptyUserPage.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/EmptyUser/EmptyUserPage/EmptyUserPage.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/EmptyUser/EmptyUsersPage/EmptyUsersPage.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/EmptyUser/NewEmptyUserPage/NewEmptyUserPage.tsx
  tasks/smoke-tests/rsc-external-packages-and-cells/tests/rsc-external-packages-and-cells.spec.ts
Labels: release:chore

#10008 RSC: Server cell smoke tests
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/Routes.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/UserExample/UserExample/UserExample.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/UserExample/UserExampleServerCell/UserExampleServerCell.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/entries.ts
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/UserExample/UserExamplePage/UserExamplePage.tsx
  tasks/smoke-tests/rsc-external-packages-and-cells/tests/rsc-external-packages-and-cells.spec.ts
Labels: release:chore

#10010 Typos in realtime.md
  docs/docs/realtime.md
Labels: release:docs

#10011 Spelling fix in what-is-redwood.md
  docs/docs/tutorial/chapter0/what-is-redwood.md
Labels: release:docs

#10013 7.0 RC: Remove hardcoded check for `session.id`
  packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.fetch.test.js
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
Labels: bug/confirmed, topic/auth, release:fix, fixture-ok

#10012 fix(RSC/SSR): pass CLI options through to apiServerHandler
  packages/cli/src/commands/serveBothHandler.js
Labels: release:fix

#10015 RSC: server cells lowercase data function
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/UserExample/UserExampleServerCell/UserExampleServerCell.tsx
  packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
  packages/web/src/components/cell/createServerCell.tsx
Labels: release:fix

#10016 chore(renovate): Disable for experimental apollo package
  .github/renovate.json
Labels: release:chore

#10017 chore(release): add back `update-package-versions` task
  tasks/update-package-versions
Labels: release:chore

#10020 fix(deps): remove react types packages from `@redwoodjs/testing` dependencies
  packages/testing/package.json
  yarn.lock
Labels: release:fix

#10021 fix(server): fix env var loading in `createServer`
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/createServer.ts
Labels: release:fix

#10018 fix: Handle static assets on the `rw-serve-fe`
  packages/vite/src/runFeServer.ts
Labels: release:fix

#10023 fix(types): Fix TS type in createServer.test.ts
  packages/api-server/src/__tests__/createServer.test.ts
Labels: release:chore

#10019 feat(server): add docs on the server file
  docs/docs/app-configuration-redwood-toml.md
  docs/docs/docker.md
  docs/docs/realtime.md
  docs/netlify.toml
Labels: release:docs

#10024 chore(k6 tests): update entry point
  tasks/k6-test/run-k6-tests.mts
Labels: release:chore

#10025 fix(realtime): update logic for including sseLink
  packages/vite/src/index.ts
Labels: release:fix

#9989 chore(ci): add changelog check to ci
  .github/actions/check_changelog/action.yml
  .github/actions/check_changelog/check_changelog.mjs
  .github/actions/check_changelog/package.json
  .github/actions/check_changelog/yarn.lock
  .github/workflows/check-changelog.yml
  CHANGELOG.md
Labels: release:chore

#10026 chore(release): link to previous releases and upgrade guides in the changelog
  CHANGELOG.md
Labels: release:chore

#10028 RSC chore(tests): Add links to scaffolds in test fixture
  __fixtures__/test-project-rsc-external-packages-and-cells/api/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/Routes.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/layouts/NavigationLayout/NavigationLayout.css
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/layouts/NavigationLayout/NavigationLayout.tsx
Labels: release:chore, changelog-ok

#10029 RSC: Add MultiCellPage to test fixture
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/Routes.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/RandomNumberServerCell/RandomNumberServerCell.css
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/RandomNumberServerCell/RandomNumberServerCell.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/RandomNumberServerCell/UpdateRandomButton.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/RandomNumberServerCell/actions.ts
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/entries.ts
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/layouts/NavigationLayout/NavigationLayout.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/MultiCellPage/MultiCellPage.css
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/MultiCellPage/MultiCellPage.tsx
Labels: release:chore, changelog-ok

#10030 RSC: No basePath arg to serve()
  packages/vite/src/client.ts
Labels: release:fix, changelog-ok

#10032 docs: Within describeScenario documentation, change optimisation to use American English
  docs/docs/testing.md
Labels: topic/docs, release:docs, changelog-ok

#10033 docs: Removes warning within Mailer documentation about Studio being experimental
  docs/docs/mailer.md
Labels: topic/docs, release:docs, fixture-ok, changelog-ok

#10035 fix(server): prefix port/host with api, fix logging
  docs/docs/docker.md
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/apiCLIConfigHandler.ts
  packages/api-server/src/createServer.ts
  packages/api-server/src/createServerHelpers.ts
  packages/api-server/src/watch.ts
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/serveApiHandler.js
  packages/cli/src/commands/serveBothHandler.js
Labels: release:fix, changelog-ok

#10038 chore(changelog): add v7
  CHANGELOG.md
Labels: release:chore, fixture-ok

#10036 chore: bump TSTyche
  package.json
  packages/router/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, changelog-ok

#10039 chore(ci): update yarn.lock for changelog action
  .github/actions/check_changelog/yarn.lock
Labels: release:chore, fixture-ok, changelog-ok

#10037 chore(crwa): update version in e2e test
  packages/create-redwood-app/tests/e2e.test.ts
Labels: release:chore, changelog-ok

#10045 chore(release): fix updating `peerDependencies` in release script
  tasks/release/release.mjs
Labels: release:chore, changelog-ok

#10042 chore(deps): acorn-loose 8.4.0
  packages/vite/package.json
  yarn.lock
Labels: release:chore, changelog-ok

#10046 RSC: Refactor node-loader and some vite plugins
  packages/vite/src/react-server-dom-webpack/node-loader.ts
  packages/vite/src/rsc/rscVitePlugins.ts
Labels: release:chore, changelog-ok

#10049 RSC: Refactor: extract common code for env vars
  packages/vite/src/envVarDefinitions.ts
  packages/vite/src/index.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildServer.ts
Labels: release:chore, changelog-ok

#10050 RSC: Upgrade test-project-rsa to v8 canary
  __fixtures__/test-project-rsa/api/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsa/web/package.json
Labels: release:chore, changelog-ok

#10048 RSC: Transform client components during build
  packages/vite/src/client.ts
  packages/vite/src/react-server-dom-webpack/node-loader.ts
  packages/vite/src/rsc/rscBuildServer.ts
  packages/vite/src/rsc/rscVitePlugins.ts
  packages/vite/src/rsc/rscWorker.ts
Labels: release:feature, changelog-ok

#10056 chore(types): Get rid of TS typecast in babel config
  packages/babel-config/src/web.ts
Labels: release:chore, changelog-ok

#10057 RSC: Simplify entriesFile loading
  packages/vite/src/rsc/rscWorker.ts
Labels: release:feature, changelog-ok

#10055 fix(render): reduce memory and handle server file
  CHANGELOG.md
  packages/api-server/src/apiCLIConfigHandler.ts
  packages/cli/src/commands/deploy/render.js
Labels: release:fix

#10058 RSC: Remove commented code from worker
  packages/vite/src/rsc/rscWorker.ts
Labels: release:chore, changelog-ok

#10062 Update studio.md
  docs/docs/studio.md
Labels: release:docs

#9961 Add support for additional env var files
  CHANGELOG.md
  __fixtures__/fragment-test-project/.gitignore
  __fixtures__/test-project-rsa/.gitignore
  __fixtures__/test-project-rsc-external-packages-and-cells/.gitignore
  __fixtures__/test-project/.gitignore
  packages/cli/src/__tests__/__fixtures__/redwood-app-env-collision/.env.base
  packages/cli/src/__tests__/__fixtures__/redwood-app-env-collision/.env.collision
  packages/cli/src/__tests__/__fixtures__/redwood-app-env-many/.env.dev
  packages/cli/src/__tests__/__fixtures__/redwood-app-env-many/.env.prod
  packages/cli/src/__tests__/__fixtures__/redwood-app-env-node-env/.env.bazinga
  packages/cli/src/__tests__/__fixtures__/redwood-app-env-node-env/.env.prod
  packages/cli/src/__tests__/__fixtures__/redwood-app-env-prod/.env.prod
  packages/cli/src/__tests__/addAdditionalEnvFiles.test.js
  packages/cli/src/index.js
  packages/cli/src/middleware/addAdditionalEnvFiles.js
  packages/create-redwood-app/templates/js/gitignore.template
  packages/create-redwood-app/templates/ts/gitignore.template
  tasks/server-tests/bothServer.test.mts
Labels: release:feature

#10066 Update jsdoc for ScenarioData type
  CHANGELOG.md
  packages/testing/src/api/scenario.ts
Labels: release:fix

#10069 RSC: Fix path in setup script readme
  .github/actions/set-up-rsc-external-packages-and-cells-project/README.md
Labels: release:chore, changelog-ok

#10060 fix(coherence): update setup command to detect server file
  CHANGELOG.md
  packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
Labels: release:fix

#10072 chore(.vscode): Enable find inside root __fixtures__
  .vscode/settings.json
Labels: release:chore, changelog-ok

#10073 RSC: chore - upgrade @tobbe.dev/rsc-test to v0.0.5
  __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
Labels: release:chore, changelog-ok

#10067 chore(docs): Add link to SuperTokens auth
  CHANGELOG.md
  docs/docs/authentication.md
Labels: topic/docs, release:docs

#10077 RSC: Fix node-loader message typo
  packages/vite/src/react-server-dom-webpack/node-loader.ts
Labels: release:chore, fixture-ok, changelog-ok

#10061 fix(deploy): handle server file
  .vscode/settings.json
  CHANGELOG.md
  __fixtures__/test-project/web/package.json
  packages/cli/src/commands/__tests__/dev.test.js
  packages/cli/src/commands/__tests__/serve.test.js
  packages/cli/src/commands/deploy/flightcontrol.js
  packages/cli/src/commands/devHandler.js
  packages/cli/src/commands/experimental/util.js
  packages/cli/src/commands/serve.js
  packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
  packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
  packages/cli/src/commands/setup/deploy/templates/render.js
  packages/cli/src/commands/setup/realtime/realtimeHandler.js
  packages/cli/src/lib/project.js
Labels: release:fix

#10078 RSC: Add build step debug logs
  packages/vite/src/rsc/rscBuildAnalyze.ts
  packages/vite/src/rsc/rscBuildClient.ts
  packages/vite/src/rsc/rscBuildClientEntriesFile.ts
  packages/vite/src/rsc/rscBuildCopyCssAssets.ts
  packages/vite/src/rsc/rscBuildRwEnvVars.ts
  packages/vite/src/rsc/rscBuildServer.ts
Labels: release:chore, fixture-ok, changelog-ok

#10076 RSC: Fix server build root
  packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
  packages/vite/src/rsc/rscBuildServer.ts
Labels: release:fix, changelog-ok

#10074 RSC: Make babel insert `renderFromRscServer` calls into Routes.tsx
  __fixtures__/test-project-rsa/web/src/Routes.tsx
  __fixtures__/test-project-rsc-external-packages-and-cells/web/src/Routes.tsx
  packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
  packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader.ts
  packages/babel-config/src/web.ts
  packages/cli/src/commands/experimental/setupRscHandler.js
  packages/cli/src/commands/experimental/templates/rsc/Routes.tsx.template
  packages/vite/src/client.ts
  packages/vite/src/entries.ts
  packages/vite/src/index.ts
  packages/vite/src/rsc/rscBuildClient.ts
Labels: release:feature, fixture-ok, changelog-ok

#10080 chore(refactor): vite - extract into buildRouteHooks.ts
  packages/vite/src/buildFeServer.ts
  packages/vite/src/buildRouteHooks.ts
Labels: release:chore, changelog-ok
