Repository redwoodjs/graphql, pull requests merged in 2024-11, with the labels that each got.

#11713 docs(cli): Match description with command
  docs/docs/cli-commands.md
Labels: release:docs

#11715 Fix typo in deployment.md
  docs/docs/tutorial/chapter4/deployment.md
Labels: release:docs

#11710 fix(docs): make bold the whole word, not just the first char
  docs/docs/tutorial/chapter5/testing.md
Labels: release:docs, changesets-ok

#11717 chore: upgrade TSTyche
  package.json
  packages/router/package.json
  packages/storage/package.json
  packages/web/package.json
  yarn.lock
Labels: release:chore, changesets-ok

#11718 fix(dbAuth): Don't use Multi Value Headers on Vercel
  .changesets/11718.md
  packages/auth-providers/dbAuth/api/src/shared.ts
Labels: release:fix, fixture-ok

#11721 chore(test-project): Update TailwindCSS to 3.4.15 and PostCSS to 8.4.49
  __fixtures__/test-project/web/package.json
Labels: release:chore

#11722 chore(dbAuth): Early return to make code easier to read
  packages/auth-providers/dbAuth/api/src/shared.ts
Labels: release:chore, fixture-ok

#11698 docs: update oauth.md
  docs/docs/how-to/oauth.md
Labels: release:docs, changesets-ok

#11726 chore(vite): Rename 'vite' to more descriptive 'viteSsrDevServer'
  packages/ogimage-gen/src/OgImageMiddleware.test.ts
  packages/ogimage-gen/src/OgImageMiddleware.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/rsc/rscRequestHandler.ts
  packages/vite/src/streaming/createReactStreamingHandler.ts
  packages/vite/src/streaming/triggerRouteHooks.ts
  packages/web/src/server/middleware.ts
Labels: release:chore

#11727 chore(vite): Refactor vite plugin - early return
  packages/vite/src/devFeServer.ts
Labels: release:chore, fixture-ok

#11728 fix(rsc): Make SSR work when there are module level server actions
  packages/vite/ambient.d.ts
  packages/vite/src/devFeServer.ts
  packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Labels: release:fix, changesets-ok, experimental

#11724 fix(ogimage): Corrected package.json exports
  .changesets/11724.md
  packages/ogimage-gen/package.json
Labels: release:fix

#11729 feat(rsc): Make RSAs work in dev
  packages/vite/src/rsc/rscRenderer.ts
Labels: release:feature, changesets-ok, experimental
