Repository redwoodjs/graphql, pull requests merged in 2025-01, with the labels that each got.

#11879 fix(forms): Re-export InputFieldProps
  .changesets/11879.md
  packages/forms/src/index.tsx
Labels: release:fix

#11880 fix(dev): Remove redundant whitespace in cli output
  packages/cli/src/commands/devHandler.js
Labels: release:fix, changesets-ok

#11874 [Chore] Update yarn to v4.6.0
  .github/actions/check_changesets/package.json
  .github/actions/check_create_redwood_app/package.json
  .github/actions/detect-changes/package.json
  __fixtures__/fragment-test-project/package.json
  __fixtures__/rsc-caching/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project/package.json
  docs/package.json
  package.json
  packages/cli/src/commands/upgrade.js
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-rsc-app/yarn.lock
  yarn.lock
Labels: release:chore, changesets-ok

#11869 Fix Storybook preview config being set up in old config directory
  .changesets/11869.md
  packages/cli/src/commands/setup/i18n/i18nHandler.js
  packages/cli/src/lib/configureStorybook.js
  packages/cli/src/lib/templates/storybook.preview.tsx.template
  packages/project-config/src/__tests__/paths.test.ts
  packages/project-config/src/paths.ts
Labels: release:fix

#11881 [refactor] Reduce repetition in paths tests
  packages/project-config/src/__tests__/paths.test.ts
Labels: release:chore

#11883 chore(tests): Fix TS errors in paths tests
  packages/project-config/src/__tests__/paths.test.ts
Labels: release:chore

#11885 [chore] Re-use loadEnvFiles from cli-helpers lib, elimininating code duplicatation
  packages/cli-helpers/src/index.ts
  packages/cli-helpers/src/lib/__tests__/__fixtures__/redwood-app-env-collision/.env.base
  packages/cli-helpers/src/lib/__tests__/__fixtures__/redwood-app-env-collision/.env.collision
  packages/cli-helpers/src/lib/__tests__/__fixtures__/redwood-app-env-many/.env.dev
  packages/cli-helpers/src/lib/__tests__/__fixtures__/redwood-app-env-many/.env.prod
  packages/cli-helpers/src/lib/__tests__/__fixtures__/redwood-app-env-node-env/.env.bazinga
  packages/cli-helpers/src/lib/__tests__/__fixtures__/redwood-app-env-node-env/.env.prod
  packages/cli-helpers/src/lib/__tests__/__fixtures__/redwood-app-env-prod/.env.prod
  packages/cli-helpers/src/lib/__tests__/loadEnvFiles.test.ts
  packages/cli/src/index.js
  packages/cli/src/lib/loadEnvFiles.js
Labels: release:chore, changesets-ok

#11889 feat(dbAuth): Lax SameSite cookie policy
  .changesets/11889.md
  __fixtures__/fragment-test-project/api/src/functions/auth.ts
  __fixtures__/test-project-rsc-kitchen-sink/api/src/functions/auth.ts
  __fixtures__/test-project/api/src/functions/auth.ts
  docs/docs/auth/dbauth.md
  docs/docs/cors.md
  docs/docs/how-to/oauth.md
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.fetch.test.js
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.ts.template
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.webAuthn.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.ts.template
  packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.webAuthn.ts.template
  tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
Labels: release:feature

#11891 chore(docs): Update yarn.lock
  docs/yarn.lock
Labels: release:chore

#11895 chore(deps): react-hook-form@7.54.2
  packages/forms/package.json
  yarn.lock
Labels: changesets-ok, release:dependency

#11581 chore(docs): Fix links in Storybook docs; add link to dbAuth OAuth plugin
  docs/docs/how-to/oauth.md
  docs/docs/storybook.md
Labels: release:docs

#11878 Update to @typescript-eslint version that supports TypeScript 5.6.2
  .changesets/11878.md
  package.json
  packages/eslint-config/package.json
  packages/eslint-plugin/package.json
  packages/storage/src/createSavers.ts
  packages/storage/src/prismaExtension.ts
  yarn.lock
Labels: release:dependency

#11896 [CLI] Refactor & simplify schema helpers
  packages/cli/src/lib/schemaHelpers.js
Labels: release:chore, fixture-ok

#11898 chore(test-project): Update PostCSS to 8.5.1
  __fixtures__/test-project/web/package.json
Labels: release:chore

#11892 fix(templates+docs) Make Storybook links link to correct versions
  __fixtures__/fragment-test-project/web/src/components/Author/Author.stories.tsx
  __fixtures__/fragment-test-project/web/src/components/BlogPost/BlogPost.stories.tsx
  __fixtures__/test-project/web/src/components/Author/Author.stories.tsx
  __fixtures__/test-project/web/src/components/BlogPost/BlogPost.stories.tsx
  docs/docs/cli-commands.md
  docs/docs/storybook.md
  docs/versioned_docs/version-1.x/cli-commands.md
  docs/versioned_docs/version-1.x/storybook.md
  docs/versioned_docs/version-2.x/cli-commands.md
  docs/versioned_docs/version-2.x/storybook.md
  docs/versioned_docs/version-3.x/cli-commands.md
  docs/versioned_docs/version-3.x/storybook.md
  docs/versioned_docs/version-4.x/cli-commands.md
  docs/versioned_docs/version-4.x/storybook.md
  docs/versioned_docs/version-5.x/cli-commands.md
  docs/versioned_docs/version-5.x/storybook.md
  docs/versioned_docs/version-6.x/cli-commands.md
  docs/versioned_docs/version-6.x/storybook.md
  docs/versioned_docs/version-7.x/cli-commands.md
  docs/versioned_docs/version-7.x/storybook.md
  docs/versioned_docs/version-8.0/cli-commands.md
  docs/versioned_docs/version-8.0/storybook.md
  docs/versioned_docs/version-8.1/cli-commands.md
  docs/versioned_docs/version-8.1/storybook.md
  docs/versioned_docs/version-8.2/cli-commands.md
  docs/versioned_docs/version-8.2/storybook.md
  docs/versioned_docs/version-8.3/cli-commands.md
  docs/versioned_docs/version-8.3/storybook.md
  docs/versioned_docs/version-8.4/cli-commands.md
  docs/versioned_docs/version-8.4/storybook.md
  packages/cli/src/commands/generate/component/__tests__/__snapshots__/component.test.ts.snap
  packages/cli/src/commands/generate/component/templates/stories.jsx.template
  packages/cli/src/commands/generate/component/templates/stories.tsx.template
  packages/codemods/src/codemods/v6.x.x/convertJsToJsx/__testfixtures__/example/input/web/src/components/TestComponent/TestComponent.stories.js
  packages/codemods/src/codemods/v6.x.x/convertJsToJsx/__testfixtures__/example/output/web/src/components/TestComponent/TestComponent.stories.jsx
Labels: release:fix, changesets-ok

#11900 chore(deps): docusaurus 3.7.0
  docs/package.json
  docs/yarn.lock
Labels: release:dependency

#11901 chore(docs): Add missing Docusaurus peer-dep
  docs/package.json
  docs/yarn.lock
Labels: release:chore

#11902 Revert "feat(router): Better autocomplete for `<Set>`s (#11769)"
  .changesets/11769.md
  packages/router/src/Set.tsx
Labels: release:feature, changesets-ok

#11903 Revert "fix(set): Correctly infer generic (#11768)"
  packages/router/src/Set.tsx
Labels: release:fix, changesets-ok

#11904 Revert "chore(set): Use the existing AvailableRoutes type (#11767)"
  packages/router/src/Set.tsx
Labels: release:fix, changesets-ok

#11905 Revert "[Router][TS] Auto-complete route names for unauthenticated prop (#11756)"
  .changesets/11756.md
  packages/router/src/Set.tsx
Labels: release:fix, changesets-ok

#11906 chore(router): Fix spelling/grammar and type import in tests
  packages/router/src/__tests__/route-validators.test.tsx
  packages/router/src/__tests__/router.test.tsx
Labels: release:chore, fixture-ok

#11908 Revert the recent NX upgrades
  package.json
  yarn.lock
Labels: release:fix, changesets-ok

#11909 chore(deps): nx@19.8.14
  package.json
  yarn.lock
Labels: release:chore

#11910 chore(deps): nx@20.3.2
  package.json
  yarn.lock
Labels: release:chore

#11911 chore(deps) re-upgrade to yarn 4.6.0
  .github/actions/check_changesets/package.json
  .github/actions/check_create_redwood_app/package.json
  .github/actions/detect-changes/package.json
  __fixtures__/fragment-test-project/package.json
  __fixtures__/rsc-caching/package.json
  __fixtures__/test-project-rsa/package.json
  __fixtures__/test-project-rsc-kitchen-sink/package.json
  __fixtures__/test-project/package.json
  docs/package.json
  docs/yarn.lock
  package.json
  packages/cli/src/commands/upgrade.js
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
  packages/create-redwood-rsc-app/yarn.lock
  yarn.lock
Labels: changesets-ok, release:dependency

#11920 fix(cli): Pin TailwindCSS to v3
  .changesets/11920.md
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
Labels: release:fix, fixture-ok

#11923 feat(cli): Add support for RWJS_CWD and --cwd to TW setup
  packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
Labels: release:feature, fixture-ok, changesets-ok

#11924 chore(test-project): Pin TW to v3
  tasks/test-project/tui-tasks.js
Labels: release:chore

#11926 chore(test-project): Switch tui-tasks to TypeScript
  tasks/test-project/codemods/models.js
  tasks/test-project/rebuild-fragments-test-project-fixture.ts
  tasks/test-project/rebuild-test-project-fixture.ts
  tasks/test-project/tasks.js
  tasks/test-project/tui-tasks.ts
  tasks/test-project/typing.ts
  tasks/tsconfig.json
Labels: release:chore

#11929 chore(cli): Remove redundant loops and checks
  packages/cli/src/commands/generate/scaffold/scaffold.js
Labels: release:chore

#11931 feat(cli): Support generating sdls for models with only an id and relation
  .changesets/11931.md
  packages/cli/src/commands/generate/sdl/__tests__/__snapshots__/sdl.test.js.snap
  packages/cli/src/commands/generate/sdl/__tests__/fixtures/schema.prisma
  packages/cli/src/commands/generate/sdl/__tests__/sdl.test.js
  packages/cli/src/commands/generate/sdl/sdl.js
Labels: release:feature

#11380 feat(router): Add option to not reset scroll to the top on navigate/link
  .changesets/11380.md
  docs/docs/router.md
  packages/router/src/__tests__/routeScrollReset.test.tsx
  packages/router/src/history.tsx
  packages/router/src/location.tsx
Labels: release:feature, contributor-pr

#11919 [TS] Fix missing default Page type export
  packages/router/src/__tests__/pageLoadingContext.test.tsx
Labels: release:chore

#11933 docs: fix discord invite link
  docs/docs/contributing-overview.md
  docs/docs/how-to/sending-emails.md
  docs/docs/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-1.x/contributing-overview.md
  docs/versioned_docs/version-1.x/how-to/sending-emails.md
  docs/versioned_docs/version-1.x/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-2.x/contributing-overview.md
  docs/versioned_docs/version-2.x/how-to/sending-emails.md
  docs/versioned_docs/version-2.x/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-3.x/contributing-overview.md
  docs/versioned_docs/version-3.x/how-to/sending-emails.md
  docs/versioned_docs/version-3.x/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-4.x/contributing-overview.md
  docs/versioned_docs/version-4.x/how-to/sending-emails.md
  docs/versioned_docs/version-4.x/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-5.x/contributing-overview.md
  docs/versioned_docs/version-5.x/how-to/sending-emails.md
  docs/versioned_docs/version-5.x/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-6.x/contributing-overview.md
  docs/versioned_docs/version-6.x/how-to/sending-emails.md
  docs/versioned_docs/version-6.x/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-7.x/contributing-overview.md
  docs/versioned_docs/version-7.x/how-to/sending-emails.md
  docs/versioned_docs/version-7.x/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-8.0/contributing-overview.md
  docs/versioned_docs/version-8.0/how-to/sending-emails.md
  docs/versioned_docs/version-8.0/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-8.1/contributing-overview.md
  docs/versioned_docs/version-8.1/how-to/sending-emails.md
  docs/versioned_docs/version-8.1/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-8.2/contributing-overview.md
  docs/versioned_docs/version-8.2/how-to/sending-emails.md
  docs/versioned_docs/version-8.2/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-8.3/contributing-overview.md
  docs/versioned_docs/version-8.3/how-to/sending-emails.md
  docs/versioned_docs/version-8.3/tutorial/chapter1/prerequisites.md
  docs/versioned_docs/version-8.4/contributing-overview.md
  docs/versioned_docs/version-8.4/how-to/sending-emails.md
  docs/versioned_docs/version-8.4/tutorial/chapter1/prerequisites.md
Labels: release:docs, changesets-ok

#11932 docs(deployment): Removes grove based deployment information
  docs/docs/tutorial/chapter4/deployment.md
  docs/versioned_docs/version-8.3/tutorial/chapter4/deployment.md
  docs/versioned_docs/version-8.4/tutorial/chapter4/deployment.md
Labels: release:docs, changesets-ok
