Repository redwoodjs/graphql, pull requests merged in 2025-03, with the labels that each got.

#11964 docs: Fix spelling in graphql docs
  docs/docs/graphql.md
Labels: release:docs

#11966 fix(cli): flightcontrol:deploy handle command errors
  .changesets/11966.md
  __fixtures__/test-project/web/package.json
  packages/cli/src/commands/deploy/__tests__/flightcontrol.test.ts
  packages/cli/src/commands/deploy/flightcontrol.ts
Labels: release:breaking

#11971 chore(vitest): Consistently use .mts
  packages/auth/vitest.config.mts
  packages/auth/vitest.setup.mts
Labels: release:chore

#11973 chore(babel-config): Remove unused jest config file
  packages/babel-config/jest.config.js
Labels: release:chore

#11972 chore(fastify): TS: Improve web adapter tests
  packages/adapters/fastify/web/src/resolveOptions.test.ts
  packages/adapters/fastify/web/src/web.test.ts
  packages/adapters/fastify/web/src/webFallback.test.ts
  packages/adapters/fastify/web/vitest.config.mts
  packages/adapters/fastify/web/vitest.setup.mts
Labels: release:chore

#11974 chore(babel-config): Fix TS warning about converting require into import
  packages/babel-config/src/common.ts
Labels: release:chore

#11976 chore(babel-config): @babel/register comment
  packages/babel-config/src/common.ts
Labels: release:chore

#11978 chore(dataMigrate): Switch from jest to vitest
  packages/cli-packages/dataMigrate/dist.test.ts
  packages/cli-packages/dataMigrate/package.json
  packages/cli-packages/dataMigrate/src/__tests__/install.test.ts
  packages/cli-packages/dataMigrate/src/__tests__/installHandler.test.ts
  packages/cli-packages/dataMigrate/src/__tests__/up.test.ts
  packages/cli-packages/dataMigrate/src/__tests__/upHandler.test.ts
  packages/cli-packages/dataMigrate/src/commands/installHandler.ts
  packages/cli-packages/dataMigrate/src/commands/upHandler.ts
  packages/cli-packages/dataMigrate/vitest.config.mts
  yarn.lock
Labels: release:chore

#11980 chore(deps): @babel/cli 7.26.4
  package.json
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/cli/package.json
  packages/codemods/package.json
  packages/core/package.json
  packages/eslint-config/package.json
  packages/graphql-server/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/web/package.json
  yarn.lock
Labels: release:dependency

#11982 chore(dbAuth): Fix flaky webAuthn unit test (timing issue)
  packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
Labels: release:chore

#11981 deps(@babel/core): Bump to 7.26.10
  .changesets/11981.md
  package.json
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/babel-config/package.json
  packages/cli-helpers/package.json
  packages/cli/package.json
  packages/codemods/package.json
  packages/create-redwood-app/package.json
  packages/eslint-config/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/web/package.json
  yarn.lock
Labels: release:dependency

#11983 deps(@babel/generator): Bump to 7.26.10
  package.json
  packages/vite/package.json
  yarn.lock
Labels: release:dependency

#11984 chore(deps): @babel/node 7.26.0
  package.json
  yarn.lock
Labels: release:dependency

#11985 deps(babel): @babel/runtime-corejs3 7.26.10
  .changesets/11985.md
  package.json
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/babel-config/dist.test.ts
  packages/babel-config/package.json
  packages/babel-config/src/__tests__/api.test.ts
  packages/cli/package.json
  packages/codemods/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/router/package.json
  packages/structure/package.json
  packages/web/package.json
  yarn.lock
Labels: release:dependency

#11988 deps(babel): Bump presets and plugins to their latest versions
  .changesets/11988.md
  package.json
  packages/babel-config/package.json
  packages/codemods/package.json
  packages/create-redwood-app/package.json
  packages/internal/package.json
  packages/web/package.json
  yarn.lock
Labels: release:dependency

#11989 deps(babel): Bump @babel parser, register and traverse
  .changesets/11989.md
  packages/babel-config/package.json
  packages/codemods/package.json
  packages/internal/package.json
  packages/vite/package.json
  yarn.lock
Labels: release:dependency

#11990 Update auth.webAuthn.ts.template
  packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.webAuthn.ts.template
Labels: release:docs, changesets-ok

#11994 docs(dbauth): Update the passwordless/OTP how-to
  docs/docs/how-to/dbauth-passwordless.md
Labels: release:docs

#11992 fix(testing): Don't generate scenarios with red squiggles
  packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
  packages/cli/src/commands/generate/service/templates/scenarios.ts.template
Labels: release:fix, fixture-ok, changesets-ok

#11996 chore(test-project): Fix test project after updating service scenario template
  __fixtures__/test-project/api/src/services/posts/posts.scenarios.ts
  __fixtures__/test-project/api/src/services/users/users.scenarios.ts
Labels: release:chore

#11998 chore(codemods): Format README
  packages/codemods/README.md
Labels: release:chore, fixture-ok

#12001 chore(ci): Fix broken storybook smoke tests
  .github/actions/set-up-job/action.yml
Labels: release:chore

#12000 chore(codemods): Try `pool: 'forks'` instead of 'vmForks'
  packages/codemods/vite.config.mts
Labels: release:chore

#11999 chore(codemods): Fix TS errors
  packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/__testfixtures__/default.input.ts
  packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/__testfixtures__/default.output.ts
  packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/updateClerkGetCurrentUser.ts
  packages/codemods/src/codemods/v5.x.x/cellQueryResult/cellQueryResult.ts
  packages/codemods/src/codemods/v5.x.x/updateAuth0ToV2/updateAuth0ToV2.ts
  packages/codemods/src/codemods/v5.x.x/upgradeToReact18/upgradeToReact18.ts
  packages/codemods/src/lib/cells.ts
  packages/codemods/tsconfig.json
Labels: release:chore

#11997 chore(test-project): Fix cjs/esm warning during regeneration
  tasks/test-project/codemods/models.ts
Labels: release:chore, fixture-ok

#12002 chore(deps): storybook 7.6.20
  __fixtures__/test-project/package.json
  package.json
  packages/cli-packages/storybook-vite/package.json
  packages/create-redwood-app/templates/js/package.json
  packages/create-redwood-app/templates/ts/package.json
  packages/storybook/package.json
  yarn.lock
Labels: dependencies, changesets-ok, release:dependency

#12004 chore(ci): Don't pin the Node version. Storybook issue fixed
  .github/actions/set-up-job/action.yml
Labels: release:chore

#12005 chore(dbAuth): Switch to vitest for /web
  packages/auth-providers/dbAuth/web/__mocks__/@simplewebauthn/browser.js
  packages/auth-providers/dbAuth/web/jest.config.js
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.middleware.test.ts
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.test.ts
  packages/auth-providers/dbAuth/web/src/__tests__/webAuthn.test.ts
  packages/auth-providers/dbAuth/web/vitest.config.mts
  packages/auth-providers/dbAuth/web/vitest.setup.mts
  yarn.lock
Labels: release:chore

#12006 chore(dbAuth): Switch to vitest for /setup
  packages/auth-providers/dbAuth/setup/jest.config.js
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/setup/src/__tests__/__snapshots__/setup.test.ts.snap
  packages/auth-providers/dbAuth/setup/src/__tests__/setup.test.ts
  packages/auth-providers/dbAuth/setup/src/__tests__/setupData.test.ts
  packages/auth-providers/dbAuth/setup/src/__tests__/setupDataMockDMMF.test.ts
  yarn.lock
Labels: release:chore

#12007 fix(dbAuth): Don't include .snap files in the built package
  babel.config.js
  packages/auth-providers/dbAuth/setup/package.json
Labels: release:fix, changesets-ok

#12012 chore(deps): Bump vite to 5.4.15
  packages/ogimage-gen/package.json
  packages/storybook/package.json
  packages/vite/package.json
  yarn.lock
Labels: release:dependency

#12010 chore(deps): Upgrade Vitest to 2.1.9
  package.json
  packages/adapters/fastify/web/package.json
  packages/api-server/package.json
  packages/api/package.json
  packages/auth-providers/auth0/api/package.json
  packages/auth-providers/auth0/setup/package.json
  packages/auth-providers/auth0/web/package.json
  packages/auth-providers/azureActiveDirectory/api/package.json
  packages/auth-providers/azureActiveDirectory/setup/package.json
  packages/auth-providers/azureActiveDirectory/web/package.json
  packages/auth-providers/clerk/api/package.json
  packages/auth-providers/clerk/web/package.json
  packages/auth-providers/custom/setup/package.json
  packages/auth-providers/dbAuth/api/package.json
  packages/auth-providers/dbAuth/middleware/package.json
  packages/auth-providers/dbAuth/setup/package.json
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/firebase/api/package.json
  packages/auth-providers/firebase/setup/package.json
  packages/auth-providers/firebase/web/package.json
  packages/auth-providers/netlify/api/package.json
  packages/auth-providers/netlify/setup/package.json
  packages/auth-providers/netlify/web/package.json
  packages/auth-providers/supabase/api/package.json
  packages/auth-providers/supabase/middleware/package.json
  packages/auth-providers/supabase/web/package.json
  packages/auth-providers/supertokens/api/package.json
  packages/auth-providers/supertokens/setup/package.json
  packages/auth-providers/supertokens/web/package.json
  packages/auth/package.json
  packages/babel-config/package.json
  packages/babel-config/src/__tests__/prebuildApiFile.test.ts
  packages/cli-helpers/package.json
  packages/cli-packages/dataMigrate/package.json
  packages/cli-packages/storybook-vite/package.json
  packages/cli/package.json
  packages/codemods/package.json
  packages/cookie-jar/package.json
  packages/create-redwood-app/package.json
  packages/eslint-plugin/package.json
  packages/forms/package.json
  packages/graphql-server/package.json
  packages/internal/package.json
  packages/jobs/package.json
  packages/mailer/core/package.json
  packages/ogimage-gen/package.json
  packages/prerender/package.json
  packages/project-config/package.json
  packages/realtime/package.json
  packages/record/package.json
  packages/router/package.json
  packages/storage/package.json
  packages/structure/package.json
  packages/telemetry/package.json
  packages/testing/package.json
  packages/vite/package.json
  packages/vite/src/index.ts
  packages/web/package.json
  yarn.lock
Labels: release:dependency

#12014 chore(deps): Bump vite-plugin-node-polyfills to v0.23.0
  packages/vite/package.json
  yarn.lock
Labels: changesets-ok, release:dependency
