Repository redwoodjs/graphql, pull requests merged in 2025-02, with the labels that each got.

#11935 fix(babel-config): react compiler target should be a string
  packages/babel-config/src/web.ts
Labels: release:fix

#11946 feat(scripts): Args type for script arguments
  .changesets/11946.md
  packages/cli/src/commands/generate/script/__tests__/__snapshots__/script.test.ts.snap
  packages/cli/src/commands/generate/script/__tests__/script.test.ts
  packages/cli/src/commands/generate/script/script.js
  packages/cli/src/commands/generate/script/templates/script.js.template
  packages/cli/src/commands/generate/script/templates/script.ts.template
Labels: release:feature

#11947 fix(cli): Await files() when generating scripts
  packages/cli/src/commands/generate/script/script.js
Labels: release:fix, changesets-ok

#11948 fix(cli): Support passing numeric args to prisma
  packages/cli/src/commands/prismaHandler.js
Labels: release:fix, changesets-ok

#11952 fix a spelling error (principal -> principle)
  docs/docs/tutorial/chapter0/what-is-redwood.md
Labels: release:docs

#11958 chore(test-project): Update PostCSS to 8.5.3
  __fixtures__/test-project/web/package.json
Labels: release:chore
