Repository redwoodjs/graphql, pull requests merged in 2025-07, with the labels that each got.

#12063 feat(api-server): lambdaLoader: add discoverfunctionsGlob option...
  docs/docs/server-file.md
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/__tests__/lambdaLoader.test.ts
  packages/api-server/src/createServer.ts
  packages/api-server/src/createServerHelpers.ts
  packages/api-server/src/plugins/api.ts
  packages/api-server/src/plugins/lambdaLoader.ts
  packages/internal/src/files.ts
Labels: release:feature, changesets-ok

#12064 fix(api-server): lambdaLoader: improve handler import logic...
  packages/api-server/src/plugins/lambdaLoader.ts
Labels: release:fix, changesets-ok

#12066 chore(deps): Bump docusaurus to v3.8.1
  docs/package.json
  docs/yarn.lock
Labels: release:dependency

#12067 chore(deps): Bump express in docs/ to v4.21.2
  docs/yarn.lock
Labels: changesets-ok, release:dependency
